### ISSUE TITLE
DriverDataSource should have constructors that take either DriverClassName or Driver

### ISSUE THREAD

**Issue by beargiles** [brettwooldridge/HikariCP#1000]
This is a followup to a prior issue and digs deeper into classloader issues.

The DriverDataSource checks the DriverManager for an existing driver using the provided driver classname:

      if (driverClassName != null) {
         Enumeration<Driver> drivers = DriverManager.getDrivers();
         while (drivers.hasMoreElements()) {
            Driver d = drivers.nextElement();
            if (d.getClass().getName().equals(driverClassName)) {
               driver = d;
               break;
            }
         }

Our application uses multiple classloaders but they all ultimately share the standard java runtime that includes the DriverManager. That means every child classloader will see drivers loaded by other classloaders. This is, uh, less than optimal since 1) the other driver might be an incompatible version and 2) you have various classloader-related issues when you try to use an object created by a sibling, not parent or child, classloader.

It is possible to add a check on the d.getClassloader() but that doesn't make sense since we are using different classloaders for the Hikari jar and the user-provided jars.

The best approach is probably to add a second constructor that is similar to the current one but removes all of the code under "if (driverClassname != null)" - it can use a Driver provided in the constructor arguments..

An additional complication is that JDBC 4.0 requires driver jars to include a META-INF/services/java/sql.Driver file that contains the classname of the JDBC driver. This allows the standard classloader to auto-register JDBC drivers. Our default jar will usually be loaded before we try loading the user-provided jar. It was just dumb luck that our initial tests didn't include a bundled jar or sibling projects with their own classloaders.

#### Environment
```
HikariCP version: 2.7.2
JDK version     : 1.8.0_111
Database        : PostgreSQL|MySQL|...
Driver version  : x.x.x
```
-----------------------------------------------------------------------------------------
*Have you searched the CLOSED issues already? How about checking [stackoverflow](https://stackoverflow.com/search?q=HikariCP)?*

**Comment by brettwooldridge** [comment]
@beargiles If you have multiple driver jars, with different versions or the same, accessible to multiple classloaders *that* is a problem.

I have worked in extremely restricted classloader environments such as OSGi, and know well how important classloading hierarchies are.  If you truly need to control classloading, ensure that the driver is *not* accessible to the system classloader, and set the thread context classloader to whatever classloader you desire before initializing HikariCP.
