### ISSUE TITLE
Gradle bundles an old version of HikariCP

### ISSUE THREAD

**Issue by paranaliyanage** [brettwooldridge/HikariCP#1005]
#### Environment
```
HikariCP version: 2.7.2
JDK version     : 1.8.0_111
Database        : Oracle
```
-----------------------------------------------------------------------------------------

I have my gradle script as follows, 
compile group: 'com.zaxxer', name: 'HikariCP', version: 2.7.2

But, when I checked the bundled version it is 2.5.1.
com.zaxxer:HikariCP:2.7.2 -> 2.5.1

What is the reason for the gradle to bundles an old version?

**Comment by billoneil** [comment]
Are you sure another dependency is not pulling in the older version of HikariCP?

**Comment by paranaliyanage** [comment]
I have not purposely specified any Hikari version. 

But I am using spring-boot-gradle-plugin, which seems causing the issue when I google.

**Comment by billoneil** [comment]
The plugin itself depends on the correct version but it also pulls in `hibernate-hikaricp` which depends on the older version. You can probably force override it in gradle but this is not a bug with hikariCP in any way.
