### ISSUE TITLE
Connection is not available, request timed out after 30002ms.

### ISSUE THREAD

**Issue by emin** [brettwooldridge/HikariCP#1007]
Hey,

I'm getting this exception for last few days, I searched and found the old issues that may be a leak but I switched to debug log level and it's not that. I don't see any leak, I lower the leak threshold etc.

I'm using Hikari with Jooq library. This is the debug output for pool stats:

`Pool stats (total=0, active=0, idle=0, waiting=1)`

And the log which shows the exception:

`Caused by: java.sql.SQLTransientConnectionException: Yuzbirokey - Connection is not available, request timed out after 30001ms.
	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:591)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:194)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:146)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
	at org.jooq.impl.DataSourceConnectionProvider.acquire(DataSourceConnectionProvider.java:80)`

#### Environment
```
HikariCP version: 2.6.0
JDK version     : 1.8.0_111
Database        :MySQL
Driver version  : 5.1.20
```

**Comment by johnou** [comment]
@emin check your pool configuration, looks like you have configured 1 connection..?

**Comment by emin** [comment]
it's not 1, it's configured to 48 and works normally when started, this is initialization of it;

`HikariDataSource ds = new HikariDataSource();
        ds.setPoolName("something");

        ds.setMaximumPoolSize(48);
        ds.setMaxLifetime(60000);
        ds.setMinimumIdle(13);
        ds.setIdleTimeout(30000);
        ds.setLeakDetectionThreshold(48);

        ds.setDataSourceClassName("com.mysql.jdbc.jdbc2.optional.MysqlDataSource");
        ds.addDataSourceProperty("url", url);
        ds.addDataSourceProperty("user", userName);
        ds.addDataSourceProperty("password", password);
        ds.addDataSourceProperty("cachePrepStmts", true);
        ds.addDataSourceProperty("prepStmtCacheSize", 250);
        ds.addDataSourceProperty("prepStmtCacheSqlLimit", 2048);
        ds.addDataSourceProperty("useServerPrepStmts", true);
        ds.addDataSourceProperty("verifyServerCertificate", false);`

**Comment by johnou** [comment]
@emin would you try updating Hikari to 2.7.2 and report back if it's still a problem with additional snippets of the com.zaxxer.hikari debug log please?

**Comment by emin** [comment]
yes, I did that first thing after writing the issue, it happened again but not sure I was rebuild and relaunch some part of it, now fully restarted and waiting on it. If it happens again, I'll be giving more detail on it.

**Comment by brettwooldridge** [comment]
@emin You might also try upgrading your driver.  Connection/J is at v5.1.44.

I hope your ``leakDetectionThreshold`` is not actually 48 (*"ds.setLeakDetectionThreshold(48)"*) ... maybe 48000?  It's the number of milliseconds that a connection is out of the pool before a leak is reported.

Having said that, I can say fairly definitively that the issue is *not* a leak.  If there were a leak, you wouldn't see this:

> Pool stats (total=0, active=0, idle=0, waiting=1)

You would instead see this:

> Pool stats (total=48, active=48, idle=0, waiting=1)

-------------------------------------
If you have DEBUG logging enabled, you can watch the pool size, and take note when it starts to decrease.  Since you have ``minimumIdle`` set to 13, you should *always* have at least that number in the pool.

> Pool stats (total=13, active=0, idle=13, waiting=0)

When the number of connections start to drop you should see one or both of following logs appearing:

> Yuzbirokey - Failed to create/setup connection: *driver exception message*

or

> Yuzbirokey - Closing connection <connection identifier>: (Failed to create/setup connection)

You may *also* see messages like:

> Yuzbirokey - Failed to validate connection <connection identifier> (*driver exception message*)

or

> Yuzbirokey - Closing connection <connection identifier>: (connection is dead)

Please send a log fragment from when these start appearing ... starting from maybe 2 minutes prior to the first such message.

**Comment by brettwooldridge** [comment]
@emin Also, 48 connections seems a bit high.  If you have 24-cores of compute it's probably fine, otherwise, I recommended [reading our pool sizing recommendation](https://github.com/brettwooldridge/HikariCP/wiki/About-Pool-Sizing).

**Comment by emin** [comment]
Thanks, I increased leak threashold 48000 (Idk why it's this number but anyway);
My code leaks I think, it wasn't the issue last week I changed something and now I'm having this problem;

This is stacktrace;

`16:15:39.446 [Yuzbirokey housekeeper] DEBUG com.zaxxer.hikari.pool.HikariPool - Yuzbirokey - Before cleanup stats (total=14, active=1, idle=13, waiting=0)
16:15:39.446 [Yuzbirokey housekeeper] DEBUG com.zaxxer.hikari.pool.HikariPool - Yuzbirokey - After cleanup  stats (total=14, active=1, idle=13, waiting=0)
16:15:57.344 [Yuzbirokey housekeeper] WARN  com.zaxxer.hikari.pool.ProxyLeakTask - Connection leak detection triggered for com.mysql.jdbc.JDBC4Connection@36ebc363 on thread main, stack trace follows
java.lang.Exception: Apparent connection leak detected
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
	at com.mynet.proxyserver.db.DBController.getConnection(DBController.java:32)
	at com.mynet.proxyserver.db.DBController.getRooms(DBController.java:130)
	at com.mynet.proxyserver.ProxyServerLauncher.launch(ProxyServerLauncher.java:47)
	at com.mynet.shared.MainUnit.main(MainUnit.java:39)
16:16:08.003 [Yuzbirokey connection closer] DEBUG com.zaxxer.hikari.pool.PoolBase - Yuzbirokey - Closing connection com.mysql.jdbc.JDBC4Connection@446d70f0: (connection has passed maxLifetime)
16:16:08.029 [Yuzbirokey connection adder] DEBUG com.zaxxer.hikari.pool.HikariPool - Yuzbirokey - Added connection com.mysql.jdbc.JDBC4Connection@2c91c59b`


Basically, what I'm doing is;

I've static instance of HikariDataSource stored after initialization of pools, then when I need a connection,  I call the method I wrote like this;


```
public Connection getConnection(){
        Connection con = null;
        try {
            con = DataSources.getDataSource(DataSourceType.YUZBIROKEY).getConnection();
        } catch (SQLException e) {
           logger.error(e.getMessage(), e);
        }

        return con;
    }
```

`DataSources.getDataSource(DataSourceType.YUZBIROKEY)`

this just returns the `HikariDataSource`


Then I use it with jooq like this;

```
Connection con = getConnection();
        if(con != null){
            try {
                DSLContext db = DSL.using(con, SQLDialect.MYSQL);
                Record rec = db.select().from(Users.USERS).where(Users.USERS.PLATFORM_ID.eq(id)).fetchOne();
                if (rec != null) {
                    return rec.into(UserModel.class);
                } else {
                    return null;
                }
            }catch (Exception ex){
                logger.error(ex.getMessage(), ex);
                return null;
            }

        }else{
            return null;
        }
```

Whole thing is like this code, which is leaking

**Comment by brettwooldridge** [comment]
@emin You probably want to do everything in a "try-with-resources" block, whenever possible, to ensure that the Connection is closed (i.e. returned to the pool):
```java
try (Connection con = getConnection()) {
   if(con != null) {
      ...
   }else{
      ...
   }
}
```
The stacktrace above would seem to indicate that the leak originated at ``DBController.getRooms(DBController.java:130)``.  Unless you have a try-with-resources block, or a try-finally that closes the Connection in the ``finally``, then an exception will cause your code to leak.

**Comment by emin** [comment]
Thanks,  

if I do it this;

```
try{
 // do stufff
}finally{
  con.close();
}
```
is that ok? I don't remember exactly but first time I was using hikari, it wasn't happy that I closed connections manually.

**Comment by brettwooldridge** [comment]
@emin Yes, that is fine.

**Comment by emin** [comment]
Thanks for the help, I changed that it works by not calling getConnection() myself, instead using HikariDatasource in try block like you showed. I'll monitor it and hopefully, it'll be fixed. Thanks again.
