### ISSUE TITLE
Is HikariDataSource thread safe？

### ISSUE THREAD

**Issue by j782070772** [brettwooldridge/HikariCP#1008]
`PoolBase` class has a  `dataSource` field and publish it by ` getUnwrappedDataSource()`  method.

HikariDataSource execute `HikariDataSource.setLogWriter(PrintWriter out)` method depend on dataSource.

is it thread-safe in multithreading ？ 

one thread setLogWriter and one thread write log by LogWriter。

**Comment by brettwooldridge** [comment]
HikariCP relies on the underlying DataSource to handle synchronization in this case.

**Comment by martin-andersson-vcc** [comment]
I do not understand much of both of you.

This should be documented. The official [JavaDoc](https://javadoc.io/doc/com.zaxxer/HikariCP/latest/com/zaxxer/hikari/HikariDataSource.html) I see has one line in it. Pretty dismal to be honest.
