### ISSUE TITLE
Update maxLifetime re adding random 10 sec

### ISSUE THREAD

**Issue by obperryo** [brettwooldridge/HikariCP#1011]
Please update maxLifetime configuration comments with comments about Adding random 10 second for every hour in the maxlifetime. 

https://github.com/mmuruganandam/HikariCP/commit/0b99b0655c3cc855f9d006746784ff0bca229926

**Comment by obperryo** [comment]
You might also add to idleTimeout that it doe not renew the life of a connection within the minimumIdle connections. I see it being renewed when maxLifetime is reached.. I watched this with five connections in a pool of five, where I was using one connection and then stopped using it. It did not retire at 30 seconds and start the count over... and It was 150 seconds off from the other four connections.. when the other four got close to my 600 sec count that I set, they all started to randomly renewed along with the one lagging behind by 150 seconds.

**Comment by brettwooldridge** [comment]
The documentation says:

> This property controls the **_maximum_** lifetime of a connection in the pool. An in-use connection will never be retired, only when it is closed will it then be removed.

The pool *could* choose to retire the connection at any time. The algorithm *has* changed over time, and may change again.  The behavior of the current version of HikariCP is subtly different than the version that you linked to.

Because of this, any further specificity in the documentation would be an implementation detail.  The *contract* of the configuration setting is correctly specified by the documentation.

I am not sure I understand the ``idleTimeout`` issue you are reporting.  Can you please post the configuration you were running with?  At this point in the HikariCP maturity curve, you probably have higher likelihood of being hit by a bus than finding a bug in HikariCP.

**Comment by obperryo** [comment]
I'll try to be more clear. I am new to this and am just trying to provide some feedback on things that I came across as I was trying to understand it all and fix some issue I have been running into.

I am using 2.7.2

[Issue 256](https://github.com/mmuruganandam/HikariCP/commit/0b99b0655c3cc855f9d006746784ff0bca229926
) says that it added random 10 second for every hour in maxLifetime to manage the closing of connection in a span of seconds instead of all at once. It might be good to note that under maxLifetime.


I don't think it is a bug, but based on the behavior I observed, I do not think the idleTimeout applies to idle connections within the minimumIdle connections in the pool. The minimumIdle connections appear to be being managed by the maxLifetime or a cleanup cycle. It might be good to note that under idleTimeout if that is true.

The above two are just feedback, it they are off and not accurate then don't worry about them. But, I have been having debugging and have been trying to really understand what each of these settings are dong to work through the issue, that's where the feedback is coming from.

Thanks for the consideration on the above!  

---

Can I ask this... what datasource or jdbcUrl I should be using with Percona, as I don't see it in the table? I am not sure if I should be leaning towards MySQL or MariaDB. Could/Should you add Percona to the table and identify if it can use a Datasource or needs to be jdbcUrl configuration? I was going the MySQL route, and once I came across this [MariaDB Connector/J driver](https://mariadb.com/kb/en/library/about-mariadb-connector-j/), I went this route and started having some success, but I am still not sure what specific change has brought that success, or if I should be going the direction of the MariaDB driver with Percona.   



Here is what I have been going through. I would appreciate any comments you might have on any of this:

We have been running MariaDB local on CentOS7 with the com.mysql.jdbc.Driver, Hikari 2.4.1 a MaximumPoolSize=100 and minimumIdle default with no problems for a long time. The business is switching us to Percona. When switching to Percona we have run into two things, SSL warning, easy fix to the url, but the main issue is that we lose all connections around 10, 20, 80 or 90 minutes and they don't recover. 

Switching to Percona I have been using the approach of MySQL from your table, and I have been using the Connector/J and jdbcUrl configuration with the com.mysql.cj.jdbc.Driver, Hikari 2.4.1 and tried 2.7.2. Is this the right approach or should I be taking another approach? I have been running into various issues where my pool blows up, and I get log errors like Failed to validate connection and Communications link failure. I am finding the documented solutions for these that are very clear, and making a lot of changes per all you have documented and other online resources, but the pool keeps blowing up at various times. I have a routine that gets a connection from the pool every minute and that is how I know that there are no connections around 10, 20, 80 or 90 minutes, which is the longest it has managed to keep connections. I was using all the default timeouts and a maximumPoolSize of 100 and minimumIdle 20. The database wait_timeout was the default 28800. I have verified time sync and my Google Cloud VM is running Crony.

The good news as of this morning... I seem to finally be able to run with the following configuration for 15 hours now, using one connection each minute, by doing the following, but I do not know what has resolved it just yet, I suspect either the larger VM, or taking maximumPoolSize from 100 to 20, or the MaxLifetime relative and the specific setting of 600 in the my.cnf file.

Current configuration with 15+ hours of up time now:

Increased my Google Cloud VM form micro to a small.
Hikari 2.7.2
Set MySQL default wait_timeout=600 and interactive_timeout=600
Using this [Mariadb Connector/J driver]( https://mariadb.com/kb/en/library/about-mariadb-connector-j/)

		HikariConfig config = new HikariConfig();		
		config.setJdbcUrl(cfg.get("jdbc.url", "jdbc:mysql://123.123.123:3306/TestDB"));
		config.setUsername(cfg.get("jdbc.user", "xxx"));
		config.setPassword(cfg.get("jdbc.password", "xxx"));
		config.setConnectionTimeout(cfg.getInt("ConnectionTimeout", 10000));
		config.setIdleTimeout(cfg.getInt("IdleTimeout", 30000 ));
		config.setMaxLifetime(cfg.getInt("MaxLifetime", 570000  ));
		config.setConnectionTestQuery(cfg.get("ConnectionTestQuery", "SELECT 1"));		
		config.setMinimumIdle(cfg.getInt("MinimumIdle", 5));
		config.setMaximumPoolSize(cfg.getInt("MaximumPoolSize", 20));
		config.setPoolName(this.getName());
		config.setRegisterMbeans(true);
		config.setCatalog(cfg.get("jdbc.catalog", ""));
		config.setDriverClassName(cfg.get("jdbc.driver", "com.mysql.jdbc.Driver"));
		config.addDataSourceProperty("cachePrepStmts", "true");
		config.addDataSourceProperty("prepStmtCacheSize", "250");
		config.addDataSourceProperty("prepStmtCacheSqlLimit", "2048");
		config.addDataSourceProperty("useServerPrepStmts", "true");
		
I know that I may not need some of these like ConnectionTestQuery and DriverClassName, but I have them there for assurance until I can narrow down exactly what is making my pool connections blow up.

Long, I know, but thanks for the help!

**Comment by brettwooldridge** [comment]
I have updated the documentation for idleTimeout and maxLifetime.

My understanding is that Percona is essentially MySQL.  I think you can use either the MariaDB driver or Connector/J.  Personally I favor the MariaDB driver as it carries less legacy baggage.  Because of previous issues with the DataSource implementations of both I would recommend using jdbcUrl based configuration.

Note properties such as cachePrepStmts are likely different from the Connector/J driver. And yes you do not need the connection test query.

**Comment by johnou** [comment]
@brettwooldridge do you happen to know if there is a compatibility guarantee of running the MariaDB driver with MySQL or it might break at some point in the future?

**Comment by brettwooldridge** [comment]
Of course there are no guarantees, but I doubt the MariaDB project wants to break wire compatibility with MySQL.

**Comment by johnou** [comment]
@rusher could I trouble you for your input too?

**Comment by rusher** [comment]
@johnou clearly, with an asterisk: no support for mysql protocol X. 
Regarding the datasource problem, it has been corrected there must be 1 year and a half

**Comment by brettwooldridge** [comment]
@johnou The MariaDB blog states that the MariaDB JDBC driver *is* compatible with MySQL, but requires MySQL to be at least v5.5.3.

**Comment by brettwooldridge** [comment]
@rusher I am not sure which issue you think was corrected in the past 1.5 years, but the issue of MysqlDataSource [not supporting login timeout](https://github.com/mysql/mysql-connector-j/blob/release/5.1/src/com/mysql/jdbc/jdbc2/optional/MysqlDataSource.java#L181) still remains.

This means that a new connection creation that occurs during a network outage can hang indefinitely (8 hours on Linux by default).

It *does* appear that the MariaDB driver DataSource implementation corrected this issue.

**Comment by obperryo** [comment]
I don't need a driver class name using jdbcURL, but I want to build in a config for it.  Can I set a default to Null or pass a bad driver name and Hikari will then behave like I did not set the driver class name?

config.setDriverClassName(cfg.get("jdbc.driver", NULL));
config.setDriverClassName(cfg.get("jdbc.driver", "Hikari.decides"));
