### ISSUE TITLE
setMinimumIdle and setMaximumPoolSize break pool connection on startup

### ISSUE THREAD

**Issue by obperryo** [brettwooldridge/HikariCP#1014]
#### Environment
```
HikariCP version: 2.7.2
JDK version     : 1.8.0_131-b11
Database        :  Percona
Driver version  : mysql-connector-java-8.0.8-dmr-bin.jar
```
-----------------------------------------------------------------------------------------

Are there any known issue with setMinimumIdle and setMaximumPoolSize? All of the other methods work just find, however when I include either of these I can't get a pool connection upon startup. I have them commented out in the code below.

	/* GET AND SET SIZE AND TIMEOUTS */
	
	public long getConnectionTimeout() {
		return dsource.getHikariConfigMXBean().getConnectionTimeout();
	}
	
	public void setConnectionTimeout(long timeout) {
		dsource.getHikariConfigMXBean().setConnectionTimeout(timeout);
	}
	
	public long getIdleTimeout() {
		return dsource.getHikariConfigMXBean().getIdleTimeout();
	}
	
	public void setIdleTimeout(long timeout) {
		dsource.getHikariConfigMXBean().setIdleTimeout(timeout);
	}
	
	public long getMaxLifetime() {
		return dsource.getHikariConfigMXBean().getMaxLifetime();
	}
	
	public void setMaxLifetime(long lifetime) {
		dsource.getHikariConfigMXBean().setMaxLifetime(lifetime);
	}
	
	public long getMinimumIdle() {
		return dsource.getHikariConfigMXBean().getMinimumIdle();
	}
	
//	public void setMinimumIdle(int idletime) {
//		dsource.getHikariConfigMXBean().setMinimumIdle(idletime);
//	}	
	
	public long getMaximumPoolSize() {
		return dsource.getHikariConfigMXBean().getMaximumPoolSize();
	}
	
//	public void setMaximumPoolSize(int poolsize) {
//		dsource.getHikariConfigMXBean().setMaximumPoolSize(poolsize);
//	}

**Comment by brettwooldridge** [comment]
@obperryo There are no known issue related to that.  Looking at the code, nothing appears to be incorrect.  What error are you getting?  Can you enable DEBUG logging, and attach a section of the log showing the pool status?

**Comment by obperryo** [comment]
Got it... thanks!  I had longs instead of int for the getters.

`exception name="Getter and setter for MaximumPoolSize have inconsistent types"`
