### ISSUE TITLE
Print driver when Hikari chooses it

### ISSUE THREAD

**Issue by obperryo** [brettwooldridge/HikariCP#1018]
#### Environment
```
HikariCP version: 2.7.2
JDK version     : 1.8.0_131-b11
Database        :  Percona
Driver version  : mysql-connector-java-8.0.8-dmr-bin.jar
```
-----------------------------------------------------------------------------------------
I am using the jdbcURL without driverClassName. We have run into some misleading errors making us think it was not using the correct driver, however it was, we just couldn't see it.  I have tried many ways to print the driver that Hikari is using when it determines it itself with no luck. How can I get and print the driver Hikari chooses to be able to confirm it is using what I think it is using?

**Comment by brettwooldridge** [comment]
Closed by #1136
