### ISSUE TITLE
how to identify why the connection pool is full

### ISSUE THREAD

**Issue by marcusavi** [brettwooldridge/HikariCP#1020]
Hi,

We have cases when the poor reach to its maximum total connections, and all the connections are busy.
Mostly in cases of high load on the application.
Is it possible in such cases to know which threads, or which queries are those who catch the connections,
in order to identify the source for the load, or bug.

I mean, if there's an option to write to log all the connections statuses, or what happened to each connection in a specific time period?

Thanks,
Avi

#### Environment
```
HikariCP version: 2.2.5
JDK version     : 1.8.0_25
Database        : Oracle
Driver version  : ojdbc7
```

**Comment by brettwooldridge** [comment]
If you are running on Oracle you already have some of the most powerful analysis tools available; certainly much more powerful than the pool can provide.  Maybe check out some YouTube videos on Oracle performance troubleshooting?

You can get a [very] rough idea of potentially long running queries by setting the leakDetectionThreshold to its minimum value (2000ms).  Any connection used longer than that will log a stacktrace pointing to where it was allocated in your code.

Finally, you reported that you are using Java 8.  Please upgrade to the latest version of HikariCP — v.2.7.3.

**Comment by marcusavi** [comment]
The DB performance is ok, Oracle can handle the load. 
but because of the load on the application server, 
the pool gets full, and refuses new threads to get connection.
I can investigate my regular logs what caused the load, which requests and user actions,
but I hoped maybe I can get this information from the pool in some way.
I will check the information from the leak detention.
