### ISSUE TITLE
PreparedStatement.setNull(int,  java.sql.Types.INTEGER)  --  bad query generated

### ISSUE THREAD

**Issue by urikjaro** [brettwooldridge/HikariCP#1021]
#### Environment
```
HikariCP version: 2.6.3
JDK version     : 1.8.0_121
Database        : PostgreSQL
```
Hi, 
I have problem with setting NULL to an integer field with method:
ps.**setNull**(1, Types.**INTEGER**);   // where ps is an instance of java.sql.PreparedStatement
When i print out the sql with 'ps.toString()' I get  "... int_**variable = NULL** ..." instead of "... int_**variable IS NULL** ..." ! 
I also do not get any results (when I manually try query with ".. is null .." I get results of course..)

I have tried searching StackOverflow and other places, but without any luck..

Please fix this issue or tell me where have I made a mistake.

Thank you 

Jaroslav

**Comment by brettwooldridge** [comment]
HikariCP is simply passing the call through to the delegate, both in the case of setNull() and toString().  You can try creating a DataSource and PreparedStatement without HikariCP and compare comparing the two.

I don’t recall fixing any issues related to this, but I would recommend upgrading v2.7.3 and running with the latest PostgreSQL driver.

**Comment by urikjaro** [comment]
You are right, I have tried this only with postgres driver and the behavior is the same, which means it is not problem of HikariCP. 
Sorry for this "false issue", I will close it now, since it is not an issue. I have also found, that this behavior of the postgres driver can be changed (link bellow - search for 'transform_null_equals' ) - going to test this now..
