### ISSUE TITLE
SQL server snapshot isolation level

### ISSUE THREAD

**Issue by znikola** [brettwooldridge/HikariCP#1024]
Since Spring Boot 2 switched to HikariCP as the default data source connection pool we were looking forward to that change, since we are on Tomcat's pool. 
But we're unable to do so, since HikariCP doesn't support SQL server's snapshot isolation level. We tried setting an integer constant (4096) as the value for `transactionIsolation` property, but as documentation states it requires a String value from `Connection` class.

Is there a way to set this Snapshot isolation level?

**Comment by brettwooldridge** [comment]
@znikola Do me a favor, I'm totally crushed on another project this week, can you send me a pull request?  [You can change the code here](https://github.com/brettwooldridge/HikariCP/blob/dev/src/main/java/com/zaxxer/hikari/util/UtilityElf.java#L164), add a case for 4096 with a comment about SQL Server SNAPSHOT isolation.

**Comment by znikola** [comment]
Sure thing, no problem.

**Comment by znikola** [comment]
Excuse for my ignorance, but how can I create a pull request?

I cloned your repo, made changes, and push doesn't work - I got 403.
The same is when I try with "Create Pull Request" option from IntelliJ.

**Comment by billoneil** [comment]
@znikola You need to [fork the repo](https://help.github.com/articles/fork-a-repo/) then you can make a pull request from your fork to the main repo.

**Comment by znikola** [comment]
Thank you.
