### ISSUE TITLE
HikariCP 2.4.7 TCP count is more than the pool size

### ISSUE THREAD

**Issue by ilawrencewu** [brettwooldridge/HikariCP#1039]
#### Environment
```
HikariCP version: 2.4.7
JDK version     : 1.8.0_111
Database        :  MySQL
Driver version  : com.mysql.jdbc.Driver 
<dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <version>5.1.29</version>
</dependency>

the bean configuration
<bean id="hikariConfig" class="com.zaxxer.hikari.HikariConfig">
        <property name="poolName" value="springHikariCP" />
        <property name="connectionTestQuery" value="SELECT 1" />
        <property name="driverClassName" value="com.mysql.jdbc.Driver" />
        <property name="maximumPoolSize" value="20" />
        <property name="minimumIdle" value="3" />
        <property name="idleTimeout" value="15000"/>
        <property name="allowPoolSuspension" value="true" />
        <property name="registerMbeans" value="true"/>
        <property name="username" value="${username}"/>
        <property name="password" value="${password}" />
        <property name="jdbcUrl" value="${jdbcUrl}"/>
    </bean>
```
-----------------------------------------------------------------------------------------
I found an issue when using Hikaricp 2.4.7 that, the TCP count established is more than the pool size, and the TCP count will go on increase when application running. see the picture as below:
![f097a0cb-4315-41aa-a6e6-a59c9dbf2603](https://user-images.githubusercontent.com/13930780/33588261-9781b9c4-d937-11e7-99ce-9b367af767b7.png)

**Comment by brettwooldridge** [comment]
@ilawrencewu v2.4.7 is approximately 18 months old, and there have been more than 12 releases since that time, please upgrade to v2.7.4 and see if the issue still exists.

**Comment by lawrencewu** [comment]
@brettwooldridge   I have upgrade to v2.7.4, and seems it works fine, but I want to know why this happens, can you please find the reason?

**Comment by brettwooldridge** [comment]
@ilawrencewu You can always read the [CHANGES](https://github.com/brettwooldridge/HikariCP/blob/dev/CHANGES) log.

Could be #714 or #880 ...

**Comment by ilawrencewu** [comment]
@brettwooldridge   I've read #714 and #983, but this is not the same issue.

**Comment by brettwooldridge** [comment]
@ilawrencewu In that case, I have no idea;  consider yourself lucky.
