### ISSUE TITLE
Provide Automatic-Module-Name attribute in MANIFEST.MF

### ISSUE THREAD

**Issue by orionll** [brettwooldridge/HikariCP#1045]
It would be nice to have an `Automatic-Module-Name` attribute in MANIFEST.MF. This is very easy to add:

```
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-jar-plugin</artifactId>
    <version>3.0.2</version>
    <configuration>
        <archive>
            <manifestEntries>
                <Automatic-Module-Name>com.zaxxer.hikari</Automatic-Module-Name>
            </manifestEntries>
        </archive>
    </configuration>
</plugin>
```

**Comment by johnou** [comment]
JSR has pretty poor recommendations on module names, see discussions here..

https://github.com/netty/netty/pull/7245
https://github.com/ben-manes/caffeine/issues/211#issuecomment-352069631

**Comment by orionll** [comment]
@johnou Indeed they had poor recommendations in the past, but now it's pretty clear: a module's name should correspond to the name of its super package. In case of HikariCP it is `com.zaxxer.hikari`. Source: http://mail.openjdk.java.net/pipermail/jpms-spec-experts/2017-May/000687.html

**Comment by kashike** [comment]
#1047 added this.

**Comment by cowwoc** [comment]
So... can this issue be closed? Are there any plans to add `module-info.java`?
