### ISSUE TITLE
Password authentication failing for postgres

### ISSUE THREAD

**Issue by LJNeon** [brettwooldridge/HikariCP#1046]
#### Environment
```
HikariCP version: 2.7.4
JDK version     : 9.0.1+11
Database        : PostgreSQL
Driver version  : 42.1.4
```
-----------------------------------------------------------------------------------------
While using HikariCP to connect to a PostgreSQL database I keep getting this error:
```
org.postgresql.util.PSQLException: FATAL: password authentication failed for user "cobra"
```
I'm 100% sure that the password is correct, I've double checked that I am passing a `String` containing the password to `HikariConfig.setPassword()` and that it matches the password I've set for the database I'm trying to connect to.

**Comment by LJNeon** [comment]
Also note that the Java 9 early release version is completely broken and won't even run, which is why I'm using the one marked as Java 8+.

**Comment by johnutting** [comment]
Any movement on this, works with the following versions locally:
Hikari: 2.7.7
Java: 1.8.0_152
Postgres: 9.4

Connecting from AWS ec2 instance to RDS running Postgres authentication failure:
Hikari: 2.7.7
Java: 1.80_161
Postgres: 9.6.2

Error:
org.postgresql.util.PSQLException: FATAL: password authentication failed for user "activemq"

**Comment by aravindanck** [comment]
@LJNeon Were you able to resolve this? I'm facing a similar issue

**Comment by rosscdh** [comment]
+1 postgres 5 minideb

**Comment by LJNeon** [comment]
I never ended up figuring this out, and since this issue is clearly dead, I'm going to close it.
