### ISSUE TITLE
Don't validate connection EVERY borrow

### ISSUE THREAD

**Issue by sternr** [brettwooldridge/HikariCP#1050]
#### Environment
```
HikariCP version: 2.6.1
JDK version     : 1.8.0_101
Database        : MySQL|Vertica
Driver version  : x.x.x
```
-----------------------------------------------------------------------------------------
Before moving to Hikari we used Tomcat connection pool which had a configuration called validationInterval which means the pool didn't validate the connection EVERY time it was borrowed, rather only every certain interval.
While using Hikari, I couldn't find an equivalent parameter hence our validation query is running ALOT of times...
Is there some similar mechanism in Hikari?

Thanks!

**Comment by shakuzen** [comment]
From [HikariCP's README](https://github.com/brettwooldridge/HikariCP#frequently-used), you should not be setting a validation query if your driver is JDBC4 compatible:

> &#128288;``connectionTestQuery``<br/>
**If your driver supports JDBC4 we strongly recommend not setting this property.** This is for 
"legacy" drivers that do not support the JDBC4 ``Connection.isValid() API``.  This is the query that
will be executed just before a connection is given to you from the pool to validate that the 
connection to the database is still alive. *Again, try running the pool without this property,
HikariCP will log an error if your driver is not JDBC4 compliant to let you know.*

Letting Hikari use the `Connection.isValid` method should be more efficient than executing a query.
Also, if you look at https://github.com/brettwooldridge/HikariCP/issues/406#issuecomment-136660574, Brett explains that there is an optimization built into HikariCP to not validate a connection every time it is borrowed:

> HikariCP tries to strike a balance between performance and reliability. One of the concessions to performance is the alive test bypass window. It was designed under the assumption that if a connection was known valid within the past few hundred milliseconds, it is still valid. Forcing validation on every call to getConnection() is sure to be a performance killer.

Given the above, connections should already not be validated on every borrow as the title of this issue claims. It is not exposed as a configuration option as explained in the linked comment:

> One of HikariCP's basic tenants is that we won't provide a means by which the end user can construct an unreliable configuration.

**Comment by sternr** [comment]
Sweet! its a shame aliveBypassWindow is not in HikariConfig, but awesome that it exists.
As for isValid, digging up the vertica driver isValid, we saw its using a sub-optimal query, so we had to replace it.

Thanks!

**Comment by brettwooldridge** [comment]
@sternr The truth is, though unsupported, you can change the "alive bypass window" though a [system property](https://github.com/brettwooldridge/HikariCP/blob/dev/src/main/java/com/zaxxer/hikari/pool/HikariPool.java#L80).  However, I strongly recommend that you don't mess with internal settings and let HikariCP do its thing.  The defaults perform extremely well and have been arrived at through battle-tested installations both large and small.

If your application is fairly active in terms of DB interactions, it may *never* actually execute explicit validation.  In the case that validation does occur, for example if your application goes many seconds between DB interactions, it is typical of most databases to encounter less than a 2ms delay.

**Comment by venky424** [comment]
I have similar issue. below is the configuration. How can I control the frequency of connectionTestQuery . Currently it is hitting the database 4 times per second. Could you please advise  which property helps to set the interval of the connectionTestQuery ? 

    hikari:
      readOnly: true
      connectionTestQuery: CALL HeartBeatProcedure("I am from Int2")
      connectionTimeout: 120000
      idleTimeout: 120000
      poolName: ALRDBPool
      maximumPoolSize: 50
