### ISSUE TITLE
Java 9 status

### ISSUE THREAD

**Issue by sergey-morenets** [brettwooldridge/HikariCP#1052]
Hi

Currently there are two versions of HikariCP displayed on the site main page:

1) Java 8 maven artifact:
2) Java 9 Early Access maven artifact:

However it is not clear the difference between them? Java 9 Early Access version was last released on April, 2017. So now when JDK 9 is released what version should we use? Is it safe to use Java 8 artifact or Java 9 is preferred?

Please, give more detail. Thanks.

**Comment by brettwooldridge** [comment]
@sergey-morenets I just released v2.7.5, which contains a fix for Java 9 compatibility with respect to the Java 8 library.

The Java 8 artifact would be the preferred artifact at this point.

**Comment by sergey-morenets** [comment]
@brettwooldridge Thank you. So you propose using version 2.7.5 if I have JDK 9.0.1 ?

**Comment by brettwooldridge** [comment]
Correct.
