### ISSUE TITLE
HikariDataSource copy-constructor prevents inheriting configuration

### ISSUE THREAD

**Issue by cowwoc** [brettwooldridge/HikariCP#1053]
#### Environment
```
HikariCP version: 2.7.4
JDK version     : 9.0.1+11
Database        : PostgreSQL
Driver version  : 42.1.4.jre7
```
-----------------------------------------------------------------------------------------
*Have you searched the CLOSED issues already? How about checking [stackoverflow](https://stackoverflow.com/search?q=HikariCP)?* Yes

https://github.com/brettwooldridge/HikariCP/issues/231 resulted in a public copy-constructor being added. Unfortunately, it doesn't work the way I expected it to.

I thought the entire point of the copy-constructor is to enable users to inherit configuration from an existing pool, then override some parameters, then launch the pool. Maybe this used to work in a past release, but it no longer does.

The copy-constructor is launching the new pool immediately. This means that any configuration changes requested after the copy constructor is invoked are being ignored silently.

Expected behavior:

1. Users should be able to reconfigure the pool after invoking the copy-constructor, before pulling the first Connection.
2. Configuration methods (e.g. `setJdbcUrl()`) should throw `IllegalStateException` if the pool is already started instead of ignoring such calls silently.

**Comment by cowwoc** [comment]
I was trying to track down at what point my code broke (used to work with configuration overriding but no longer does). Originally my code was invoking:

```
		HikariDataSource result = new HikariDataSource();
		// configure, then invoke result.getConnection()
                // then later on...
		result.setJdbcUrl(newUrl);
                doSomething(result.getConnection())
```
and this used to work at some point. Somewhere down the line, the code changed and invoking `setJdbcUrl()` after pulling a connection no longer reconfigured the `DataSource`. So I tried using the copy-constructor to achieve the same goal and that failed too.

There are multiple issues here:
1. Why does `setJdbcUrl()` get ignored? Is this by design?
2. If so, can you please have it throw `IllegalStateException` to avoid silent failures?
3. Should the copy-constructor spin up the pool right away? What's the point of this constructor if the configuration cannot be altered after construction?

**Comment by brettwooldridge** [comment]
@cowwoc The purpose of the "copy" is to ensure that changes to the configuration, through ``HikariConfig`` or subclasses (e.g. ``HikariDataSource``), do not affect the operation of the pool once the pool is started.  The only pool configuration that can be changed at runtime are those exposed via ``HikariConfigMXBean``.

The purpose of the ``HikariDataSource(HikariConfig configuration)`` constructor is to support constructing a ``HikariDataSource`` with a ``HikariConfig``, which is assumed to have been configured and the pool ready to start.  The no-arg constructor originally did not exist, and ``HikariDataSource`` did not extend ``HikariConfig``; it was only added [to make Spring-based configuration more convenient](https://github.com/brettwooldridge/HikariCP/commit/6865443ddf8dfbde869fcac8fcdb669990d3709d).

I will take throwing ``IllegalStateException`` as an enhancement and one that makes perfect sense to me in service of the goal outlined above.

**Comment by cowwoc** [comment]
> The purpose of the HikariDataSource(HikariConfig configuration) constructor is to support constructing a HikariDataSource with a HikariConfig, which is assumed to have been configured and the pool ready to start.

Makes sense. Can you please mention in the Javadoc that this constructor starts the pool right away? The no-op constructor Javadoc implies this indirectly, but users who read one Javadoc without the other are bound to miss it.

>I will take throwing IllegalStateException as an enhancement and one that makes perfect sense to me in service of the goal outlined above.

Perfect, thank you.

**Comment by brettwooldridge** [comment]
@cowwoc Having looked at throwing ``IllegalStateException`` I believe that change would break some users.  For example, because of the copy semantic, the ``HikariConfig`` is re-usable to start another pool, and users may be doing so.  For example:
```java
HikariConfig config = new HikariConfig();
config.setMaximumPoolSize(8);
config.setPoolName("Pool1");

HikariDataSource ds1 = new HikariDataSource(config);

config.setMaximumPoolSize(20);
config.setPoolName("Pool2");

HikariDataSource ds2 = new HikariDataSource(config);
```
"Sealing" the ``HikariConfig`` after first use is likely not an option, but I will certainly improve the JavaDoc around the constructor behavior.

**Comment by cowwoc** [comment]
@brettwooldridge Maybe I missed something, but why is the above code problematic?

Specifically, although `config` is passed into `ds1` and `ds2`'s constructor, those constructors make a copy of the configuration and fire a pool against the copy. Hence, the original `config` is never sealed and there is no problem with modifying it.

My expectation for the above code is that `ds1.setMaximumPoolSize()` would throw an exception after the constructor, but `config.setMaximumPoolSize()` would not. Makes sense?

**Comment by brettwooldridge** [comment]
@cowwoc The above code would be problematic, if, after ``HikariConfig`` is used to initialize ``ds1`` it is "sealed" such that further calls to setters throw ``IllegalStateException``.  Having said *that*, I do (now) realize that it is possible to seal the ``HikariDataSource`` itself to disallow setter invocation.  In summary, you're right. 😄

**Comment by cowwoc** [comment]
Excellent. Looks good except for a small typo: https://github.com/brettwooldridge/HikariCP/commit/c48ccf6e12f13827914cde3cab209324d1e78009#r26665682
