### ISSUE TITLE
misconfig the setBreakAfterAcquireFailure(true) of C3P0 connection pool in DbDownTest case

### ISSUE THREAD

**Issue by guogl** [brettwooldridge/HikariCP#1057]
Hi,
https://github.com/brettwooldridge/HikariCP/wiki/Bad-Behavior:-Handling-Database-Down is a great document.
And I download the source code to have a try by myself.
I found the C3P0 connection pool cannot recover even the network is back. The reason is in the line#173 of DbDownTest.java
In C3P0 document, http://www.mchange.com/projects/c3p0/#breakAfterAcquireFailure, it says
"If you set breakAfterAcquireFailure to true, the DataSource will consider itself broken after a failed round of Connection attempts, and future client requests will fail immediately." 

I think it is the reason why you see the weird behavior of C3P0 connection pool in the Bad bahivor document.
C3P0 didn't respond at first with a connection, because it was stuck in the validation query, but after approximately 2 minutes C3P0 finally wakes up with an error. **Unfortunately, it does not seem to honor the 5 second timeout, and continues to fail immediately when the harness calls getConnection() every 2 seconds.**

Thanks
Gary

**Comment by brettwooldridge** [comment]
@guogl Very interesting, thanks for the feedback.  I'll remove the ``breakAfterAcquireFailure`` setting.  I frankly can't remember why it was added.  But also interesting to know that the pool still does not recover.
