### ISSUE TITLE
HikariDataSource extending HikariConfig makes dynamic passwords dirty

### ISSUE THREAD

**Issue by Simon-Lessard** [brettwooldridge/HikariCP#1059]
#### Environment
```
HikariCP version: 2.7.4
JDK version     : 1.8.0_111
Database        : all
Driver version  : all
```
#### Problem statement
The current implementation makes HikariDataSource extend HikariConfig and then copy the content of the configuration passed to the constructor using configuration.copyStateTo(this). Then, when the poll is created, "this" gets passed to the pool constructor. This creates two issues.

Firstly, it's an OOP anti-pattern since the extends does not represent a "IS A" relationship. Indeed, the DataSource is not conceptually a Config object. As an aside here on "purism" subject, there are some circular dependencies between the packages com.zaxxer.hikari and com.zaxxer.hikari.pool (HikariDataSource depends on HikariPool which depend on HikariConfig and HikariPoolMXBean).

Secondly, and most importantly, the fact that the configuration gets copied instead of referenced forces application to extend the DataSource rather than the Config object to support dynamic configuration that can vary over time. The best use case I can think of here is with dynamic database passwords that can change over time without restarting the application and/or the connection pool. For example, we are trying to externalize most of our passwords to a vault solution (for example CyberArk) and to have applications and servers query the passwords on demand (with local caching to reduce the performance overhead). The first approach we considered would have been to override the HikariConfig class with one overriding the getPassword method. However, the current implementation won't work with that since the config's getPassword method gets called only once, at startup. Therefore, the only workaround right now is to create a HikariDataSource subclass instead. It's not much harder to do so, but it is certainly dirtier.

#### Recommendation
- Remove the extends HikariConfig from HikariDataSource. 
- Create a local HikariConfig attribute in HikariDataSource.
- Change HikariConfig to implement Cloneable.
- Add a public clone() method to HikariConfig.
- Change configuration.copyStateTo(this); to this.configuration = configuration.clone().
- Pass the configuration attribute to the pool constructor instead of this.

**Comment by brettwooldridge** [comment]
@Simon-Lessard A couple of things...

``HikariDataSource`` has two constructors.  One that is initialized by a ``HikariConfig``...
```java
HikariConfig config = new HikariConfig();
config.setJdbcUrl("...");
config.setMaximumPoolSize(12);
HikariDataSource ds = new HikariDataSource(config);
...
Connection conn = ds.getConnection();
```
and one that constructs an *uninitialized* ``HikariDataSource`` where configuration is performed directly against the object itself...
```java
HikariDataSource ds = new HikariDataSource();
ds.setJdbcUrl("...");
ds.setMaximumPoolSize(12);
...
Connection conn = ds.getConnection();
```
The later is provided primarily as a convenience for Spring and other IOC configuration frameworks.

*Both* constructors ultimately result in a copy being performed.  In the case of the former, the copy occurs immediately.  In the case of the later, the copy occurs when the pool is constructed during the first call to ``getConnection()``.

The purpose of the copy is to keep users from f*cking with the configuration once the pool is started.  The only supported way to modify the pool once it is running is via the ``HikariConfigMXBean``.  However, it should be noted that the use-case you are trying to support is employed by many users and is supported via the ``HikariConfigMXBean``.

Re: circular dependencies, take it up with the Java language committee for the poor structure that is forced by *public* or *package* visibility with no mechanism for "friend" classes.  The classes in ``com.zaxxer.hikari`` and ``com.zaxxer.hikari.metrics`` are the [public API](http://javadoc.io/doc/com.zaxxer/HikariCP/2.7.4), everything else is off limits -- if only Java could actually *enforce* such an idea.  Out of self-preservation, internal classes are tucked away in sub-packages.
