### ISSUE TITLE
HikariProxyStatement.getGeneratedKeys does not return ProxyResultSet

### ISSUE THREAD

**Issue by stepbeekio** [brettwooldridge/HikariCP#1061]
#### Environment
```
HikariCP version: 2.7.2
JDK version     : 1.8.0_111
Database        : SqlServer
Driver version  : group: 'com.microsoft.sqlserver', name: 'mssql-jdbc', version: '6.2.1.jre8'
```
-----------------------------------------------------------------------------------------
*Have you searched the CLOSED issues already? How about checking [stackoverflow](https://stackoverflow.com/search?q=HikariCP)?*

I'm using the [requery.io](requery) library and am experiencing a connection leak when it calls:

```
statement.getGeneratedKeys() // where statement is a HikariProxyStatement
```

Instead of returning a proxied ResultSet this seems to return the raw JDBC ResultSet. Requery then goes on later to close the connection by calling something like:

```
Statement statement = resultSet.getStatement();
Connection connection = statement.getConnection();
resultSet.close();
statement.close();
connection.close();
```

The connection and statement returned here are the underlying JDBC connection and statement rather than the proxied connections. 

Is this behaviour from getGenerateKeys the expected behaviour? I'm not hugely familiar with what's "right" here so am uncertain whether the fault lies with Hikari or how it's being used.

I can see a naive fix where ProxyStatement in Hikari implements getGeneratedKeys and returns a ProxyResultSet. Is this a reasonable change to make?

**Comment by brettwooldridge** [comment]
Absolutely a reasonable change.
