### ISSUE TITLE
helpe me 

### ISSUE THREAD

**Issue by molele2** [brettwooldridge/HikariCP#1068]
#### Environment

HikariCP version: 2.4.13
JDK version     : 1.8.0_111
Database        : MySQL

```
Want to ask, how do HikariCP do distributed transactions

**Comment by billoneil** [comment]
What exactly is your question? Doing transactions across databases? Or across services hitting the same database? Either way you can't with JDBC. You cannot share the same connection across different servers.

You would need to look into a framework that supports distributed transactions and handle rollbacks on your own utilizing that framework.

**Comment by brettwooldridge** [comment]
@molele2 You would need to look at a JTA solution like Bitronix or Atomicos, both of which have built-in pools.
