### ISSUE TITLE
Pool size not honored with  Firebird database and Tomcat 9?

### ISSUE THREAD

**Issue by raffas** [brettwooldridge/HikariCP#1070]
#### Environment
```
HikariCP version: 2.7.6
JDK version     : 1.8.0_111
Database        :  Firebird
Driver version  : 3.0.2
```

I've a strange problem with HikariCP 2.7.3 and Firebird 2.5 Database working under Tomcat 9
HikariCP is configured as follow:

```
hibernate.hikari.minimumIdle=3 
hibernate.hikari.maximumPoolSize=3 
hibernate.hikari.idleTimeout=60000 
hibernate.hikari.maxLifetime=360000
```
As per documentation on HikariCP idleTimeout is ignored 
using this configuration and the connections are closed after 360 seconds (6 minutes)

`maxLifetime` is less than the connection keep-alive of Firebird  server 12min (settings is done via `/proc/sys/net/ipv4/tcp/tcp_keepalive_time`)

Using the application that is deployed under Tomcat 9, 
Hikari is creating a lot of pools that are never released. In my case 15 pools

Has someone noted this kind of behaviour using Tomcat 9? 
Regarding the doc, the expected behaviour will be to refuse via SQLException all the connection that cannot be served with `maxConnectionTime`.

Is there a reason why HikariCP is creating so many pools ?

**Comment by lfbayer** [comment]
If you are seeing 15 pool threads, could it be that there are actually 5 separate instances of HikariCP running, each with 3 threads? My suspicion is that this is probably more of a tomcat configuration question than a HikariCP question.

**Comment by billoneil** [comment]
If you turn on debug logging it will log when pools are started and connections are created / closed. Should give you something to go on.
