### ISSUE TITLE
I have a new problem

### ISSUE THREAD

**Issue by molele2** [brettwooldridge/HikariCP#1071]
DEBUG] 2018-01-24 15:54:05,911 method:com.zaxxer.hikari.pool.PoolBase.quietlyCloseConnection(PoolBase.java:128)
HikariPool-3 - Closing connection com.mysql.jdbc.JDBC4ReplicationMySQLConnection@58ef2741: (connection has passed maxLifetime)
[DEBUG] 2018-01-24 15:54:06,179 method:com.zaxxer.hikari.pool.PoolBase.quietlyCloseConnection(PoolBase.java:128)
HikariPool-2 - Closing connection com.mysql.jdbc.JDBC4ReplicationMySQLConnection@4549063c: (connection has passed maxLifetime)
[DEBUG] 2018-01-24 15:54:06,288 method:com.zaxxer.hikari.pool.PoolBase.quietlyCloseConnection(PoolBase.java:128)
HikariPool-4 - Closing connection com.mysql.jdbc.JDBC4ReplicationMySQLConnection@7e0c9a67: (connection has passed maxLifetime)
[DEBUG] 2018-01-24 15:54:06,704 method:com.zaxxer.hikari.pool.PoolBase.quietlyCloseConnection(PoolBase.java:128)
HikariPool-4 - Closing connection com.mysql.jdbc.JDBC4ReplicationMySQLConnection@2da630e8: (connection has passed maxLifetime)
[DEBUG] 2018-01-24 15:54:06,776 method:com.zaxxer.hikari.pool.PoolBase.quietlyCloseConnection(PoolBase.java:128)
HikariPool-3 - Closing connection com.mysql.jdbc.JDBC4ReplicationMySQLConnection@208cc548: (connection has passed maxLifetime)
[DEBUG] 2018-01-24 15:54:06,802 method:com.zaxxer.hikari.pool.PoolBase.quietlyCloseConnection(PoolBase.java:128)
HikariPool-4 - Closing connection com.mysql.jdbc.JDBC4ReplicationMySQLConnection@67c4f5bf: (connection has passed maxLifetime)
[DEBUG] 2018-01-24 15:54:06,970 method:com.zaxxer.hikari.pool.PoolBase.quietlyCloseConnection(PoolBase.java:128)
HikariPool-3 - Closing connection com.mysql.jdbc.JDBC4ReplicationMySQLConnection@7f3b94ee: (connection has passed maxLifetime)
[DEBUG] 2018-01-24 15:54:07,978 method:com.zaxxer.hikari.pool.PoolBase.quietlyCloseConnection(PoolBase.java:128)
HikariPool-3 - Closing connection com.mysql.jdbc.JDBC4ReplicationMySQLConnection@7298e09a: (connection has passed maxLifetime)
[DEBUG] 2018-01-24 15:54:08,113 method:com.zaxxer.hikari.pool.PoolBase.quietlyCloseConnection(PoolBase.java:128)
HikariPool-4 - Closing connection com.mysql.jdbc.JDBC4ReplicationMySQLConnection@29f558d: (connection has passed maxLifetime)
[DEBUG] 2018-01-24 15:54:08,693 method:com.zaxxer.hikari.pool.PoolBase.quietlyCloseConnection(PoolBase.java:128)
HikariPool-3 - Closing connection com.mysql.jdbc.JDBC4ReplicationMySQLConnection@57e41fea: (connection has passed maxLifetime)

**Comment by lfbayer** [comment]
Please read this: https://www.chiark.greenend.org.uk/~sgtatham/bugs.html

Once you have read that, then post some more information that can be of more help in understanding the issue.

The maintainers of HikariCP don't get paid for their contributions, and low effort bug reports are disrespectful of their time.

**Comment by brettwooldridge** [comment]
@molele2 There are two possibilities.

 * Everything is normal.
 * Sometime is not normal.

### Something is not normal
If you are on a laptop that goes to sleep, or you have a virtual machine (VM) that is suspended and resumed, then at the point of "wake-up" HikariCP will detect that substantial time has passed.  If that time exceeds the ``maxLifetime``, HikariCP has no choice but to eject all of the connections from the pool and replace them.

### Everything is normal
Assuming a non-sleeping/suspending machine ... Imagine that you specify a ``maxLifetime`` of 30 minutes...

When HikariCP starts up, it creates all of the connections in the pool *very* quickly -- typically within a few tens of milliseconds.  If HikariCP *strictly* honors the ``maxLifetime``, then exactly 30 minutes later, *all* connections will be closed and replaced at the same time.

This is called *mass extinction*.  It doesn't sound good, and is not.

HikariCP tries to avoid mass extinction by injecting random variation into the ``maxLifetime`` of each connection.  I believe the current variation is between 0-2.5% of the ``maxLifetime`` value.  Therefore, with a ``maxLifetime`` of 30 minutes, the *maximum* variation would be 45 seconds.  Meaning statistically, the closing of the connections will be spread over a 45 second period -- with replacement of each occurring within a few milliseconds.

With each subsequent *"generation"* of connections, the random variation will cause connection closing to spread farther and farther apart.  Until, after approximately 40 generations, the closing of connections at ``maxLifetime`` will be evenly distributed over the 30 minute period.

If you observe the first generations, e.g. "Generation 1", "Generation 2", you will see that the connection closing is fairly tightly clustered, but increasing over time.

### Epilog
Having said all of that, your log seems to indicate a roughly 100-500ms separation between closures.  This means either "Something is not normal" *or* "You have a very short maxLifetime".

A short ``maxLifetime``, for example 5 minutes, yields a maximum variation of only 7.5 seconds.  So, all connections in "Generation 1" will all be closed within a ~7.5 second period.  Nevertheless, given time, those connection retirement times will eventually spread into an even distribution over the 5 minute span.

**Comment by molele2** [comment]
thanks
