### ISSUE TITLE
Is there any particular reason for using (AtomicIntegerFieldUpdater+volatile int state) instead of AtomicInteger in PoolEntry?

### ISSUE THREAD

**Issue by 18814127356** [brettwooldridge/HikariCP#1076]
#### Environment
```
HikariCP version: 2.7.7-SNAPSHOT
```
-----------------------------------------------------------------------------------------
*Have you searched the CLOSED issues already? How about checking [stackoverflow](https://stackoverflow.com/search?q=HikariCP)?*

**Comment by billoneil** [comment]
Each `PoolEntry` has its own state so you can't use a static `AtomicInteger`. `AtomicIntegerFieldUpdater` can be made statically and shared across instances of objects to allow for atomic operations on volatile fields while using less memory than an `AtomicInteger` per instance.

I'm sure a quick google search will give you much more information.

**Comment by johnou** [comment]
http://normanmaurer.me/blog/2013/10/28/Lesser-known-concurrent-classes-Part-1/

**Comment by brettwooldridge** [comment]
@18814127356 In the case of HikariCP, there is no measurable performance difference between ``AtomicInteger`` and ``AtomicIntegerFieldUpdater`` -- both have benchmark results within the margin-of-error of each other.  However, ``AtomicIntegerFieldUpdater`` is *smaller* in terms of allocation per ``PoolEntry`` -- only the size of the ``int`` field versus an object reference plus the internals of ``AtomicInteger``.
