### ISSUE TITLE
BoneCP also tested???

### ISSUE THREAD

**Issue by du-it** [brettwooldridge/HikariCP#1080]
I wonder who is responsible for the output of:
`04:49:427 [Timer-3] INFO DbDownTest - BoneCPDataSource got a connection.`
?

I thought you only tested C3P0, Tomcat DBCP2, Vibur and Hikari.

**Comment by brettwooldridge** [comment]
Bone was removed because the author stop development of the pool, and I wanted to focus on active projects.

**Comment by du-it** [comment]
I see. Thank you. So maybe it would be a good hint to remove the line in the log or to annotate it in the article what you told me.
