### ISSUE TITLE
Change properties at runtime

### ISSUE THREAD

**Issue by du-it** [brettwooldridge/HikariCP#1082]
Is it possible to modify any property at runtime? For instance, changeing the maximum number of database connections, timeouts and so on?

**Comment by brettwooldridge** [comment]
You can change some settings through the MBean.

https://github.com/brettwooldridge/HikariCP/wiki/MBean-(JMX)-Monitoring-and-Management

You can either register it in JMX and retrieve it from there, or call ``HikariDataSource.getHikariPoolMXBean()`` to access it.
