### ISSUE TITLE
Maybe connection leak?

### ISSUE THREAD

**Issue by mogudy** [brettwooldridge/HikariCP#1085]
#### Environment
```
HikariCP version: 2.7.7
JDK version     : 1.8.0_91
Database        : MySQL
Driver version  : 6.0.6

Sping Boot: 2.0.0.BUILD-SNAPSHOTS / 2.0.0.RC1
Hibernate-core: 5.2.13.Final

```

-----------------------------------------------------------------------------------------
*Have you searched the CLOSED issues already? How about checking [stackoverflow](https://stackoverflow.com/search?q=HikariCP)?*

Yes, there are lots of answers in stackoverflow & issues relevant to connections or leaks, however, my problem is a bit different. Hikari tried to kill connections that over max-life-time, but mysql doesn't know it. All closed connections are shown as SLEEP in mysql and at the end hikari cannot get any more connection from mysql (or have to wait till mysql free some resources)

#### mysql screen cut (part of)
![cut](https://user-images.githubusercontent.com/2450351/36127831-5769a9ba-109a-11e8-9a56-da43438abacd.png)

#### logs
[hikari.log](https://github.com/brettwooldridge/HikariCP/files/1718188/hikari.log)

Appreciate for your help.

**Comment by brettwooldridge** [comment]
@mogudy Thank you for the logs.

First, I see no signs of leaks, which is good.

Every connection that I checked in the log was created and retired within your 30 minute ``maxLifetime`` setting.

Ideally, HikariCP should never encounter a ``Communications link failure`` when retiring a connection.  However, it appears that this error is encountered on some connections that are retired within the ``maxLifetime`` interval.

This indicates that MySQL (or some network component in-between) is terminating the connection.

I suggest making sure that the MySQL timeouts are explicitly defined.  For example, if HikariCP ``maxLifetime`` is set to ``1800000`` milliseconds (30 minutes) as your log indicates, set the MYSQL timeouts to *slightly* longer:
```
[mysqld]
interactive_timeout=1900
wait_timeout=1900
```
If you cannot change the MySQL timeouts, for example if you do not manage the server yourself, then I would suggest decreasing the HikariCP ``maxLifetime`` to 30-90 seconds shorter than the MySQL settings.
