### ISSUE TITLE
HikariCP and active connections in Postgresql

### ISSUE THREAD

**Issue by mantesat** [brettwooldridge/HikariCP#109]
Hi all, Brett,

I'm using HikariCP for the past month, transitioning from BoneCP to remedy some leak connection problems. I'm using Hikari with Postgresql, Spring and Hibernate, and I'm printing some MBean statistics  about the active/idle connections. As reported by Hikari pool MBean, active connections slowly but steadily increase. However, when running 

select query, state, state_change from pg_stat_activity

to the postgresql, all connections are reported as idle.

I'm sure that when the active connections reach the max pool size, the application will freeze. Which one reports the correct status of the connections, Hikari or postgresql? Is there a way to see which query is running on the active connections from Hikari?

Thanks in advance
mantesat, Greece

**Comment by mantesat** [comment]
Brett, apologies for re-posting to this after a long time, seems not to be resolved (although latest versions have considerably improved things). From statistics, it seems that slowly but steadily, active connections tend to increase.  I don't know if anyone has already reported such behavior, I'll try to use it from source code and find out why connections stay marked as active. Any suggestions are welcomed!

**Comment by zsoca8711** [comment]
We have the same issue, since we have moved to Hikari on our postgres databases, we have frequent (once every 1-2 weeks) issues, the database runs out of connections. Restarting the tomcats using Hikari fixes the issue. 

Code sample:

```java
HikariConfig config = new HikariConfig(dcAccessDetails.getDetailsAsPropertiesForHikari());
    	config.setIdleTimeout(180000);
    	config.setMaxLifetime(1800000);
    	config.setInitializationFailFast(true);
    	config.setConnectionTestQuery("SELECT current_timestamp");
```
```java
public Properties getDetailsAsPropertiesForHikari(){
		Properties props = new Properties();
		props.setProperty("dataSourceClassName", DatabaseUtil.POSTGRES_DATASOURCE_CLASS);
		props.setProperty("dataSource.user", this.dcDbUser);
		props.setProperty("dataSource.password", this.dcDbPassword);
		props.setProperty("dataSource.databaseName", this.dcDbDatabaseName);
		props.setProperty("dataSource.serverName", this.dcDbServer);
		
		return props;
	}
```

**Comment by prostobog** [comment]
I have a similar issue with Hibernate+Postgresql:
http://stackoverflow.com/questions/32968530/hikaricp-connection-is-not-available

**Comment by amanakshe** [comment]
I am experiencing similar issue, I am using hibernate, spring-JPA with HikariCP. The application hangs and things return to normal on appserver restart.

HikariDataSource dataSource = new HikariDataSource();
dataSource.setDriverClassName(DB_DRIVER_STRING);
dataSource.setJdbcUrl(URI_STRING);
dataSource.setUsername(USERNAME);
dataSource.setPassword(PASSWORD);
dataSource.setMaximumPoolSize(20);
dataSource.setTransactionIsolation("TRANSACTION_READ_COMMITTED");
dataSource.setLeakDetectionThreshold(30000);
dataSource.setIdleTimeout(60000);
dataSource.setInitializationFailFast(true);
dataSource.setConnectionTestQuery("SELECT current_timestamp");

I have enabled debug logging but could not detect any connection leak.
Any suggestions will be helpful.

**Comment by aparincu** [comment]
How can convert HikariDataSource to PGSimpleDataSoaurce?

**Comment by brettwooldridge** [comment]
@arlampin This is not the right issue thread for that question. [The answer is here](https://github.com/brettwooldridge/HikariCP/issues/549).

**Comment by flojdek** [comment]
Has this issue been resolved? I don't see any obvious resolution on the thread. Am I missing something?

**Comment by jnehlmeier** [comment]
IMHO it is a library configuration issue. I use EclipseLink (JPA) + HikariCP + Postgres without any additional library like Spring. EntityManger instance is created inside a servlet filter (which results in obtaining a connection) and that EntityManager instance is closed in that same filter after the request is done (which releases the connection to the pool). 

So it not really an issue with HikariCP.

**Comment by aparincu** [comment]
Thanck you very much.
Alex Parincu

On Thursday, April 27, 2017, 9:28:48 PM GMT+3, Jens Nehlmeier <notifications@github.com> wrote:
IMHO it is a library configuration issue. I use EclipseLink (JPA) + HikariCP + Postgres without any additional library like Spring. EntityManger instance is created inside a servlet filter (which results in obtaining a connection) and that EntityManager instance is closed in that same filter after the request is done (which releases the connection to the pool).

So it not really an issue with HikariCP.

**Comment by wotbstars** [comment]
This issue is real. I am confirming that is is reproducible without hibernate and spring. Just plain JDBC.
Postgres is flooded with "SHOW default_transaction_read_only" queries (Hikary 3.3.1)
