### ISSUE TITLE
Breaking change in HikariDataSource constructor behaviour in 2.7.7

### ISSUE THREAD

**Issue by MikeBlink** [brettwooldridge/HikariCP#1092]
Hello,

It seems that the behaviour of the constructor for HikariDataSource(HikariConfig configuration) has changed between 2.7.6. and 2.7.7. The data source no longer contains the information passed to it via the given configuration and instead just the default values. Not sure what the underlying reasons for this was but it breaks code which assumed the information was there.

It used to contain `configuration.copyStateTo(this)` which got replaced by constructing and initialising a copy `configuration.copyStateTo(copy)`.

Is it intended for the HikariDataSource to return just the default values on all of the methods that it exposes by inheriting from HikariConfig? Is there a list of any other potential breaking changes in that release?

**Comment by mkurz** [comment]
2.7.8 is released, does that fix your problem?

**Comment by brettwooldridge** [comment]
@mkurz @MikeBlink v2.7.8 should fix this issue, but I will await confirmation before closing it.

**Comment by MikeBlink** [comment]
@mkurz @brettwooldridge Works like a charm, thank you.
