### ISSUE TITLE
Possible weirdness with PostgreSQL 10

### ISSUE THREAD

**Issue by beargiles** [brettwooldridge/HikariCP#1103]
This may be more of a "UFO sighting" than something actionable but I wanted to report our experience in case others encounter it.

We have a long-running application and are adding support for PostgreSQL 10 drivers. On our dev boxes we were able to connect to a PostgreSQL 10 database without incident. On our test boxes we could connect to a new PostgreSQL 9.6 instance without incident but were unable to connect to either an existing or new PostgreSQL 10 instance.

The underlying stack trace is

    exc: Caused by: org.postgresql.util.PSQLException: This ResultSet is closed.
    exc:  at org.postgresql.jdbc2.AbstractJdbc2ResultSet.checkClosed(AbstractJdbc2ResultSet.java:2656)
    exc:  at org.postgresql.jdbc2.AbstractJdbc2ResultSet.setFetchSize(AbstractJdbc2ResultSet.java:1773)
    exc:  at org.postgresql.jdbc4.Jdbc4Statement.createResultSet(Jdbc4Statement.java:37)
    exc:  at org.postgresql.jdbc2.AbstractJdbc2Statement$StatementResultHandler.handleResultRows(AbstractJdbc2Statement.java:207) 
    exc:  at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1764)
    exc:  at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
    exc:  at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:508)
    exc:  at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:370)
    exc:  at org.postgresql.jdbc2.AbstractJdbc2Connection.execSQLUpdate(AbstractJdbc2Connection.java:260) 
  e
te(AbstractJdbc2Connection.java:260)
    exc:  at org.postgresql.jdbc2.AbstractJdbc2Connection.getTransactionIsolation(AbstractJdbc2Connection.java:737)
    exc:  at com.zaxxer.hikari.pool.BaseHikariPool.addConnection(BaseHikariPool.java:446)
    exc:  at com.zaxxer.hikari.pool.BaseHikariPool.initializeConnections(BaseHikariPool.java:542)
    exc:  at com.zaxxer.hikari.pool.BaseHikariPool.<init>(BaseHikariPool.java:171)
    exc:  at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:60)
    exc:  at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:48)
    exc:  at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:80)     

We tried to identify all of the differences between the two systems but had no success in identifying the issue. One of the problem children worked after bouncing it. (This is a desperate measure though - enterprise customers don't like it when your suggestion is restarting their server.) That suggests there's a caching problem - the problem children had something in their cache that prevented new connections.

I don't know if the long-running apps will become problem children as their connections time out. It hasn't been so far but it's only been a few hours.

We can't rule out a classloader issue - we aren't using a traditional appserver but it's a similar situation where we have a platform and applications that run within it and both have Hikari in their classpath. That's why this is more informational than a "this works for PostgreSQL 9.6 but breaks on PostgreSQL 10" comment.

However I wanted to toss it out in case others have/have had this problem as well.

#### Environment
```
HikariCP version: 2.3.8
JDK version     : 1.8.0_111
Database        : PostgreSQL
Driver version  : 42.2.1
```
-----------------------------------------------------------------------------------------

**Comment by brettwooldridge** [comment]
@beargiles For the sake of everything that is Holy and good, please tell me v2.3.8 is a typo, and that you meant v2.7.8...

**Comment by beargiles** [comment]
Unfortunately not. Enterprise customers.

I'll ping my boss with your comment. :-)

**Comment by beargiles** [comment]
Seriously, it's an ongoing battle between us shouting "bug fixes!" and the support people shouting "no changes!". sigh.

Meanwhile we may have made some progress - we actually use a cache from (roughly) url -> HikariCP DS. We might be pulling a stale entry and getting an error since the PostgreSQL 9.x drivers don't support PostgreSQL 10 servers but getting a seemingly unrelated error. Hence my comment that this might just be nothing but warning others of the unexpected problems you can have if you have both 9.x and 10.x drivers.

(Did I mention that our previously bundled driver version was for PostgreSQL 8.4?)

**Comment by beargiles** [comment]
I have a bit more information.

The problem is that PostgreSQL 9.x drivers can't talk to PostgreSQL 10.x databases. (Note: the jdbc driver version jumped from 9.x to 42.x for unrelated reasons. I'm on the mailing list and they were solving a different issue when they jumped versions.)

That's normally not an issue since the jdbc driver is still backward compatible for several releases... I think the jdbc 42.2 drivers are still good back to PostgreSQL 9.4.  However we're a *AAS provider for Enterprise customers. Hence still having 8.4 drivers and still using Java 6 when I started 2 years ago. (We just started requiring Java 8.)

Well.. the other reason for the 8.4 drivers is because it still worked with Redshift. It had limited functionality but was Good Enough and we weren't really making a distinction between PostgreSQL and Redshift. That said it would not surprise me if some of our customers were still using PostgreSQL 8.4 on some mission-critical database that they were afraid to touch because of the consequences if stored procedures broke after an upgrade.

We just changed our caching so we use a key with both the driver classname AND the driver major and minor versions in addition to other information. We can now distinguish between a connection with the bundled driver and a connection to the same server and account using a driver uploaded by the customer... but HikariConfig seems to only support specifying the driver classname.

IIRC the dreaded Apache DBCP allows you to provide a Driver instance instead of a driver classname.

We're still investigating the issue but I wanted to point out we seem to have tracked the issue down to the assumption that the driver classname will be sufficient to uniquely identify the desired driver.

**Comment by beargiles** [comment]
(phew - during the discussion someone mentioned that a pending bug fix bumps us to 2.7.3!)

**Comment by beargiles** [comment]
BTW another approach is allowing the user to provide a ClassLoader in HikariConfig. The same driver classname + different classloader = different Drivers. It is possible to wrap the initial call in code that sets and restores the Thread.currentThread.getContextClassLoader() value but that won't be right classloader if objects are created later, e.g., when establishing new connections after old ones are retired.

**Comment by brettwooldridge** [comment]
Glad you found the issue.  Couple of things...

HikariCP supports setting an instance of a ``DataSource`` directly on a ``HikariConfig``.  It’s not a Driver instance, but equivalent.

As far as I have been able to think through, setting the thread context classloader during initialization should be sufficient, even when later connection acquisition occurs.  I’m pretty sure I did this in some project.  HikariCP holds on to the Driver/DataSource instance, and classloading attempted by that instance, even in the future, should first try its parent loader which is the one that was present in the context originally.

**Comment by brettwooldridge** [comment]
Note, the thread context classloader support underwent changes and bug fixes between v2.3.8 and v2.7.8.

**Comment by rdp** [comment]
Anybody know which version of postgres JDBC introduced support for 10.x by chance? :)

**Comment by arulprabin** [comment]
https://jdbc.postgresql.org/download.html   <---- scroll a lil bit down. there u go!
