### ISSUE TITLE
Batch insert mysql is very slow

### ISSUE THREAD

**Issue by iamjohnnyzhuang** [brettwooldridge/HikariCP#1118]
#### Environment
```
HikariCP version: 2.7.8
JDK version     : 1.8.0_111
Database        : MySQL
Driver version  : 5.1.6
```
<sup>⚠️ Please verify that your issue still occurs on the latest version of HikariCP before reporting. </sup>

-----------------------------------------------------------------------------------------
*Have you searched the CLOSED issues already? How about checking [stackoverflow](https://stackoverflow.com/search?q=HikariCP)?*

I want to use JDBC to insert a lot of data, I have set rewriteBatchedStatements to true and use jdbc batch api to make it. However it's very slow. I have insert just 10000 rows it taken 20 seconds! 
However the same code I used in c3p0 is under 1 second.

here is the code
``` java
    public static void main(String[] args) throws SQLException {
        Random random = new Random();
        String sql = "INSERT INTO CUST_STATUS_CODE_ALARM(ALARM_ID,SCOPE,CACHE_GROUP,ISP,CACHE_IP,CHECK_RESULT,ORI_DATA) VALUES(?,?,?,?,?,?,?)";

        HikariConfig config = new HikariConfig();
        config.setJdbcUrl("jdbc:mysql://10.8.226.171:63751/wsms");
        config.setUsername("root");
        config.setPassword("adminwangsu");
        config.setAutoCommit(false);
        config.addDataSourceProperty("rewriteBatchedStatements", "true");
        HikariDataSource dataSource = new HikariDataSource(config);

        Connection conn = dataSource.getConnection();
        PreparedStatement pstmt = conn.prepareStatement(sql);

        long now = System.currentTimeMillis();

        for (int i = 0; i < 10000; i++) {
            pstmt.setString(1, random.nextInt() + "bbb" + random.nextInt());
            pstmt.setString(2, "");
            pstmt.setString(3, "");
            pstmt.setString(4, "");
            pstmt.setString(5, "");
            pstmt.setString(6, "");
            pstmt.setString(7, "");
            pstmt.addBatch();
        }

        pstmt.executeBatch();
        conn.commit();
        System.out.println("use time " + (System.currentTimeMillis() - now));
    }
```

I don't know where the problems are.Please help me thanks!

**Comment by brettwooldridge** [comment]
I suspect it has nothing to do with HikariCP, and more to do with the use of ``Random`` running out of entropy (when this slowdown occurs is also random).  Use [ThreadLocalRandom](https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/ThreadLocalRandom.html).  Are you on Linux, Windows, or Mac?

**Comment by iamjohnnyzhuang** [comment]
Thank you for your response.
But I don't think it's Random that make my progress slow. This is just a simple example I write to express this type problem.
I change my code there to avoid the affect of Random:
``` java
        for (int i = 0; i < 10000; i++) {
            pstmt.setString(1, "" + i);
            pstmt.setString(2, "");
            pstmt.setString(3, "");
            pstmt.setString(4, "");
            pstmt.setString(5, "");
            pstmt.setString(6, "");
            pstmt.setString(7, "");
            pstmt.addBatch();
        }
```
It's running as slow as before. My computer is Mac,and I have put my code into a jar which ran on Linux,they were all running slow.

**Comment by iamjohnnyzhuang** [comment]
I have try to copy my code to a Windows PC,But it led to the same result.
Also,I have try to change the database to a another mysql server,but still it didn't work either.

However if I change the code before getting connection by c3p0,it could work very well which just cost less than 1 second (there it cost more than 100 seconds!) . So I suspect the problem might come from the HikariCP.

**Comment by billoneil** [comment]
Can you try commenting out `config.addDataSourceProperty("rewriteBatchedStatements", "true");`

Maybe c3p0 is ignoring that?

**Comment by brettwooldridge** [comment]
@iamjohnnyzhuang @billoneil I am unable to reproduce this.

I created a class nearly identical to yours [which you can find here](https://gist.github.com/brettwooldridge/2085f7707564a37833cc6212c8485215).  I am on a Mac, and I ran MySQL in a docker using this command:
```
docker run --name some-mysql -e MYSQL_USER=brettw -e MYSQL_PASSWORD=secret -e MYSQL_DATABASE=issue1118 -e MYSQL_ALLOW_EMPTY_PASSWORD=yes -p 3306:3306 -d mysql:5.5
```
You can also find the command in the comment at the top of the above linked class.

Running the code shows 10k rows inserted in 241ms.

![screen shot 2018-03-21 at 1 38 38](https://user-images.githubusercontent.com/1538661/37668781-a0a4b294-2ca8-11e8-9633-f2d845890e36.png)

**Comment by iamjohnnyzhuang** [comment]
@brettwooldridge 
I've tried your code and just modified the jdbc url & jdbc username & jdbc password, but still it's slow on my computuer. It took almost 5 seconds to insert 10K data.

Later, I tried to modify my JDBC driver version, and I changed it from 5.1.6 to 5.1.39. The magic things happened, and the operation just only took 620ms!

So, the problem may be the compatibility of JDBC driver's version with HikariCP, but why does c3p0 work well with 5.1.6?

What I do is just change the version of jdbc driver in maven pom file as below.

``` xml
        <!--<dependency>-->
            <!--<groupId>mysql</groupId>-->
            <!--<artifactId>mysql-connector-java</artifactId>-->
            <!--<version>5.1.6</version>-->
        <!--</dependency>-->

        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <version>5.1.39</version>
        </dependency>
```

**Comment by brettwooldridge** [comment]
I’m not at my computer right now, but I can investigate a bit later.  What I will probably do, and what you can do as well, is search the change logs for the driver looking for clues.

Even 620ms seems slow to me, but if your table has indexes and/or foreign keys that could account for the difference between your 620ms and my 170ms.

**Comment by dee-kandau** [comment]
How are you not running into java.lang.Exception: Apparent connection leak detected

**Comment by iamjohnnyzhuang** [comment]
您好，我已经收到您的邮件，我将尽快回复，谢谢！
