### ISSUE TITLE
using HikariCP  with Hive JDBC,Connection is not available, request timed out after 30000ms.

### ISSUE THREAD

**Issue by sunsence** [brettwooldridge/HikariCP#1119]
#### Environment
```
HikariCP version: 2.7.8
JDK version     : 1.8.0_111
Database        : hive
Driver version  : hive.1.1.0-cdh5.7.0
```
<sup>⚠️ Please verify that your issue still occurs on the latest version of HikariCP before reporting. </sup>
<img width="1190" alt="2018-03-21 5 36 37" src="https://user-images.githubusercontent.com/17471768/37702743-7a54c83c-2d2e-11e8-92f7-ddcf285d0eea.png">
  config.setJdbcUrl(jdbc:hive2://localhost:16000/stg)
    config.setMaxLifetime(1800000)
    config.setIdleTimeout(600000)
    config.setMaximumPoolSize(100)
    config.setMinimumIdle(5)
-----------------------------------------------------------------------------------------
*Have you searched the CLOSED issues already? How about checking [stackoverflow](https://stackoverflow.com/search?q=HikariCP)?*

**Comment by brettwooldridge** [comment]
@sunsence This is almost certainly a Hive JDBC issue and not HikariCP.

**Comment by NagarajuAnthati** [comment]
Hi , This issue still exists , because of this Hive metastore connectivity is dropped for every 4 hours
