### ISSUE TITLE
Hikari ProxyConnection not checking read only flag while marking isCommitStateDirty true for autoCommit false

### ISSUE THREAD

**Issue by Jack4560** [brettwooldridge/HikariCP#1120]
#### Environment
```
HikariCP version: 2.6.1
JDK version     : 1.8.0_111
Database        : PostgreSQL|MySQL|...
Driver version  : x.x.x
```
We are setting HikariConfig setReadOnly true and also setIsolateInternalQueries.
config.setIsolateInternalQueries(true);
config.setReadOnly(true);

I notice that ProxyConnection class gets instantiated with readOnly true. My intention is to build a read only connection pool, so that I can run select queries without causing any roll back when i close connection to pool. But, looks like below method is not checking for readOnly flag while marking isCommitStateDirty to true for autoCommit False.
-----------------------------------------------------------------------------------------
final void markCommitStateDirty()
   {
      if (isAutoCommit) {
         lastAccess = currentTime();
      }
      else {
         isCommitStateDirty = true;
      }
   }

Shouldn't this method consider readOnly flag too along with isAutoCommit in if condition?
      if (isAutoCommit || isReadOnly) {

**Comment by brettwooldridge** [comment]
It’s not quite that simple.  For example, in MySQL, even when the transaction mode is READ ONLY one is still permitted to modify temporary tables.  If auto-commit is false, explicit commit or rollback is still required.

**Comment by Jack4560** [comment]
I see, but then how do we leverage read only flag in database like oracle to avoid un necessary rollbacks? Not sure, if you can support a check. As of now the only option is autoCommit false for read only connection pools.

**Comment by brettwooldridge** [comment]
My understanding is that rollback is still necessary.

> Well, you can rollback and commit in read only transactions -- in fact they are pretty much mandatory -- and if you never do them, your view of the database would be FROZEN forever. 
> 
> When you issue "set transaction read only", it is as if you "stopped time". All of your queries will be as of the point in time you began that transaction (via the set transaction statement). 
> 
> Until you commit or rollback -- your view of the data in the database is frozen. It is much like flashback query (in fact, it uses the same exact mechanism -- read consistency)

[See here](https://asktom.oracle.com/pls/apex/f?p=100:11:0::::P11_QUESTION_ID:31886463139563)

**Comment by brettwooldridge** [comment]
In summary, let HikariCP do it’s job.  We know what we’re doing.

**Comment by Jack4560** [comment]
Thanks, just to understand better, read only doesn't have any feature in HikariCP?

**Comment by brettwooldridge** [comment]
I’m not sure I understand the comment. In JDBC, Read-only allows the database to perform optimizations in query execution.  But transaction semantics must be obeyed regardless of which connection pool is used.
