### ISSUE TITLE
MySQL ,No operations allowed after connection closed errors in HikariCP

### ISSUE THREAD

**Issue by darkread** [brettwooldridge/HikariCP#1121]
#### Environment
```
HikariCP version: 2.7.8
JDK version     : 1.8.0_144
Database        : MySQL
Driver version  : 5.1.45
```
<sup>⚠️ It has been reported, but not solved
</sup>

-----------------------------------------------------------------------------------------
*Have you searched the CLOSED issues already? How about checking [stackoverflow](https://stackoverflow.com/search?q=HikariCP)?*

I use SpringBoot 2.0 with HikariCP version: 2.7.8. The properties file is only
app.ds.url=''
app.ds.username=''
app.ds.password=''

Other propertes do not set, use the default .
The Application idle 24 hours, I visiter app, It bombed, background log show "No operations allowed after connection closed errors ", MySQL wait_timeout is 28800(8 hours). maxLifeTime use the default value 1800000.
Can you help me?

**Comment by brettwooldridge** [comment]
@darkread This sounds like a connection was held out of the pool for an excessively long time and then used.  I suggest enabling the ``leakDetectionThreshold`` and enabling DEBUG level logging for the ``com.zaxxer.hikari`` package.  You would be able to observe connection creation and retirement events from the log, and the leak detection will catch any code holding connections.

If there are no leaks reported, attach the log for the 30 minutes leading up to the error here, and I will re-open this issue.
