### ISSUE TITLE
Can I use hikariCP with ReplicationDriver?

### ISSUE THREAD

**Issue by yiwong2001** [brettwooldridge/HikariCP#1123]
#### Environment
```
HikariCP version: x.x.x
JDK version     : 1.8.0_111
Database        : Mysql
Driver version  : x.x.x
```
<sup>Cool solution. Currently we run one slave and multiple slaves on Amazon RDS. We use ReplicationDriver with c3p0 in a spring/hibernate application.  We control transaction in Spring. All write transaction goes to db1-private (master) and read go to slaves (readonly)

We have following configures:
```
 <property name="driverClass" value="com.mysql.jdbc.ReplicationDriver"/>  
 <property name="jdbcUrl" value="jdbc:mysql://db1-private:3306,db2-private:3306/mydb?autoReconnect=true&amp;failOverReadOnly=false&amp;roundRobinLoadBalance=true&amp;characterEncoding=utf8"/> 
```

I wonder if it is available to do same in hikariCP?

Thanks, Ian

 </sup>

-----------------------------------------------------------------------------------------
*Have you searched the CLOSED issues already? How about checking [stackoverflow](https://stackoverflow.com/search?q=HikariCP)?*

**Comment by brettwooldridge** [comment]
@yiwong2001 The MySQL Replication driver is not supported.  Please follow the discussion here:

https://github.com/brettwooldridge/HikariCP/issues/625
