### ISSUE TITLE
HikariConfig#setInitializationFailTimeout javadoc seems wrong.

### ISSUE THREAD

**Issue by jezovuk** [brettwooldridge/HikariCP#1126]
#### Environment
```
HikariCP version: 2.7.8
```

#### Problem description

If I understand the behavior correctly, there is an error in the javadoc for `HikariConfig.setInitializationFailTimeout()`; more specifically, the section describing behavior for negative timeout value:

```
A value less than zero will <i>not</i> bypass any connection attempt and
validation during startup, and therefore the pool will start immediately.  The
pool will continue to try to obtain connections in the background. This can mean
that callers to {@code DataSource#getConnection()} may encounter exceptions.
```

It is my understanding that if timeout is less than zero connection initialization and validation during startup _will be_ bypassed, so the `<i>not</i>` part should be removed.

**Comment by brettwooldridge** [comment]
You are correct.  Will fix.

**Comment by jezovuk** [comment]
👍
