### ISSUE TITLE
Unable to connect to AWS postgres 10.x (RDS)

### ISSUE THREAD

**Issue by DanoOM** [brettwooldridge/HikariCP#1127]
#### Environment
```
HikariCP version: 3.0.0
JDK version     : 1.8.0_111
Database        : PostgreSQL  (in AWS - RDS its version: PostgreSQL 10.3)
Driver version  : <version>9.1-901-1.jdbc4</version>
```
I can connect when doing without issue:
```
Class.forName("org.postgresql.Driver");
Connection c = DriverManager.getConnection(config.getString("aws.postgres.db.url"), un, pd);
```
When connecting via HikariCP..
Method 1:
```
HikariConfig poolConfig = new HikariConfig();
poolConfig.setDataSourceClassName("org.postgresql.ds.PGSimpleDataSource");
poolConfig.setJdbcUrl(url);		
poolConfig.setUsername(un);
poolConfig.setPassword(pd);
poolConfig.setMaximumPoolSize(40);
try {
	dataSource = new HikariDataSource(poolConfig);
```
I get Exception:
com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: [Amazon](500150) Error setting/closing connection: Connection refused.

Method 2: only using jdbcUrl
```
HikariConfig poolConfig = new HikariConfig();
		//poolConfig.setDataSourceClassName("org.postgresql.ds.PGSimpleDataSource");
		poolConfig.setJdbcUrl(url);		
		poolConfig.setUsername(un);
		poolConfig.setPassword(pd);
		poolConfig.setMaximumPoolSize(40);
		try {
			dataSource = new HikariDataSource(poolConfig);
```
I get Exception..
com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: [Amazon](600000) Error setting/closing connection: General SSLEngine problem.

I suspect I may be doing something wrong??

**Comment by DanoOM** [comment]
Sorry..looks like I should have put the exceptions in code..markup is messing it up, and hiding some details:
```
Method 1 Exception:
com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: [Amazon](500150) Error setting/closing connection: Connection refused.
Method 2 Exception:
com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: [Amazon](600000) Error setting/closing connection: General SSLEngine problem.
```

**Comment by brettwooldridge** [comment]
If SSL is required, you're going to need to enable it:
```
poolConfig.addDataSourceProperty("ssl", "true");
```
There are a lot of other SSL parameters that *may* be required.  See the JavaDoc for [PGSimpleDataSource](https://jdbc.postgresql.org/documentation/publicapi/org/postgresql/ds/common/BaseDataSource.html).
