### ISSUE TITLE
IdleTimeout is unreliable

### ISSUE THREAD

**Issue by javrasya** [brettwooldridge/HikariCP#1128]
#### Environment
```
HikariCP version: 2.7.2
JDK version     : 1.8.0_152
Database        : PostgreSQL with ELB
Driver version  : 42.2.2
```

-----------------------------------------------------------------------------------------
#### Description

We spotted some reliability issues with `idleTimeout`. In some cases, the idle connections are not evicted right after they breached the `idleTimout`. In our case, we have idle session timeout is enabled on ELB which is running ahead of PostgreSQL. ELB is dropping the connection after the idle timeout. Yet the connection pool on client side thinks the connection can still be used. 

We have checked the latest version of `HikariCP` but the issue still remains. **We are preparing a pull request for this as well.**

Here is a stack trace I can share after this happens;

```
org.postgresql.util.PSQLException: An I/O error occurred while sending to the backend.
    at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:333)
    at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
    at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
    at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:155)
    at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:132)
    at org.postgresql.jdbc.PgConnection.isValid(PgConnection.java:1364)
    at com.zaxxer.hikari.pool.PoolBase.isConnectionAlive(PoolBase.java:160)
    at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:173)
    at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:149)
    at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:85)
    at org.skife.jdbi.v2.DataSourceConnectionFactory.openConnection(DataSourceConnectionFactory.java:34)
    at org.skife.jdbi.v2.DBI.open(DBI.java:211)
```

**Comment by brettwooldridge** [comment]
I'm not sure what you mean by "unreliable".  But the documentation clearly states:

> Whether a connection is retired as idle or not is subject to a maximum variation of +30 seconds, and average variation of +15 seconds.

**Comment by javrasya** [comment]
Idle connections are supposed to be removed if they have been there for more than `idleTimout` in **every case** according to the definition in the documentation (`"This property controls the maximum amount of time that a connection is allowed to sit idle in the pool"`). It means that that kind of idle connections should be evicted and replaced with the newly created ones right after `idleTimout`.  But it doesn't happen in one particular case;

In the code there is a part which I think causing this issue;
```java
final List<PoolEntry> notInUse = connectionBag.values(STATE_NOT_IN_USE);
int toRemove = notInUse.size() - config.getMinimumIdle();
for (PoolEntry entry : notInUse) {
  if (toRemove > 0 && elapsedMillis(entry.lastAccessed, now) > idleTimeout && connectionBag.reserve(entry)) {
     closeConnection(entry, "(connection has passed idleTimeout)");
     toRemove--;
  }
}
```

According to this code, if there is no connection which make `toRemove` variable turn out to be `0`, no idle connections will be closed even the ones have been there for more than idleTimeout.

As far as I see, there is no use of this checking `toRemove` value to close some connections.

**Comment by brettwooldridge** [comment]
The code that is there is intentional, and debated back and forth quite some time ago.  HikariCP *will not remove* connections below the ``minimumIdle`` limit, even if they have been idle for longer than ``idleTimeout``.

You must have missed this part of the documentation:
> Once the pool reaches minimumIdle connections, _connections will no longer be retired,_ _**even if idle**_.

Stated another way, more clearly:
* ``idleTimeout`` is not a *lifecycle* management property.  It's only purpose is pool size management; to allow the pool to shrink back to ``minimumIdle`` level.
* Connection *lifecycle* is managed solely through by ``maxLifetime``.

The documentation for ``maxLifetime`` states:
>  ... it should be at least 30 seconds less than any database _**or infrastructure imposed connection time limit.**_

If your load-balancer terminates connections after 2 minutes of idle activity, then by definition that is an "infrastructure imposed connection time limit", and ``maxLifetime`` must be set to less than that.

**Comment by javrasya** [comment]
What is the point of not retiring idle connections have been there for more than `idleTimout` if it reaches the minimumIdle? Is it to make sure there is no point in time which we have idle connections less than minimum idle? Because it is fairly confusing and missleading.

**Comment by brettwooldridge** [comment]
@javrasya The behavior *used* to be as you suggest.  However, other users found *that* to be confusing.  See #379 and [#657](https://github.com/brettwooldridge/HikariCP/issues/657#issuecomment-229086631).

So, yes, the point is exactly as you state; to ensure that there are never fewer than ``minimumIdle`` connections in the pool.

Additionally, in order to *avoid confusion*, the documentation was updated to be *explicit* about the behavior.  We're not asking users to read pages of documentation; we're talking about a single paragraph that is quite clear about the behavior of the property:

> This property controls the maximum amount of time that a connection is allowed to sit idle in the pool. This setting only applies when minimumIdle is defined to be less than maximumPoolSize. Whether a connection is retired as idle or not is subject to a maximum variation of +30 seconds, and average variation of +15 seconds. A connection will never be retired as idle before this timeout. Once the pool reaches minimumIdle connections, connections will no longer be retired, even if idle. A value of 0 means that idle connections are never removed from the pool. The minimum allowed value is 10000ms (10 seconds). Default: 600000 (10 minutes)

**Comment by johnou** [comment]
@javrasya couldn't you just configure your pool to be a fixed size?

**Comment by norna** [comment]
If I have understood correctly, the `idletimeout` is used intentionally to control the minimum number of idle connections in the pool. In our case (@javrasya) it would be nice to have another property and can let us clean idle connections or dead connections from the pool (connections that got kicked out by the server).  To go around the problem, we have to use `maxlifetime` instead.

**Comment by norna** [comment]
@brettwooldridge abd @johnou : the `fillPool` will make sure that the pool has the minimum number of connections, so why can't we remove `toRemove` checking?

**Comment by javrasya** [comment]
@brettwooldridge , shouldn't have this been covered with a different approach. It can be like first create a new idle connection as a replacement for prospectively closed old idle connections. Then close the old connections. Thus, there would be no point in time when we have less than minimum idle. The actual solution seems a quick and dirty solution. Or according to its name (`idleTimout`, not something like `idleTimoutAfterReachMinimumIdle`), Real `idleTimout` would be needed to avoid hitting server side `idleTimout`. `maxLifetime` isn't exactly for this.

@johnou Do you mean connection size in the pool?. Because this is nothing to do with pool size. It is having idleTimeout sometimes works, sometimes doesn't.

**Comment by brettwooldridge** [comment]
Let me be clear.  The purpose of ``idleTimeout`` is for the benefit of the *database server*, to allow connection resources to be conserved when shared by  multiple applications.

Whether the server has an idle timeout, or whether an HA Proxy has a timeout, or a firewall, or load-balancer, they all appear the same from the perspective of the pool.  And the way to manage Connection lifecycle in all cases is ``maxLifetime``.  That is the maximum time that the infrastructure purports to guarantee its existence.  *Another* timeout is literally meaningless.

While backseat driving or armchair quarterbacking might be fun, HikariCP has been battle tested by some of the largest internet companies on the planet, handling billions of transactions per day (at a single one of them).  Not good enough to handle your environment?

What other pools have done in the past is largely irrelevant, as most were implemented by developers who, though well intentioned, never had to manage anything approaching massive load.

**Comment by norna** [comment]
Thank you! Have nice weekend!

**Comment by brettwooldridge** [comment]
@norna Thanks, you too.
