### ISSUE TITLE
[code suggest]: The FastList constructor can reused FastList (clazz,capacity) constructor

### ISSUE THREAD

**Issue by yonnia** [brettwooldridge/HikariCP#1130]
https://github.com/brettwooldridge/HikariCP/blob/cd03cc891207f6e189cc8b0ca6a3c469aa016ac5/src/main/java/com/zaxxer/hikari/util/FastList.java#L53

**Comment by brettwooldridge** [comment]
@yonnia It could, but we wanted to avoid the extra method call. 🏎

**Comment by yonnia** [comment]
yeah you are right
