### ISSUE TITLE
support for redshift explicitly 

### ISSUE THREAD

**Issue by sharaf31** [brettwooldridge/HikariCP#1144]
#### Environment
```
HikariCP version: x.x.x
JDK version     : 1.8.0_111
Database        : Redshift
Driver version  : x.x.x
```
<sup>⚠️ Please verify that your issue still occurs on the latest version of HikariCP before reporting. </sup>

Provide support for redshift 
-----------------------------------------------------------------------------------------
*Have you searched the CLOSED issues already? How about checking [stackoverflow](https://stackoverflow.com/search?q=HikariCP)?*

**Comment by Danilo-Araujo-Silva** [comment]
@brettwooldridge , do you know where I can find a working code using Redshift with Hikari to perform insert on the database? I can retrieve results from the database but I had no success on inserts yet. Thanks in advance.

**Comment by brettwooldridge** [comment]
@Danilo-Araujo-Silva Redshift is just PostgreSQL, so it shouldn't be hard to find working configurations out on the internet.

Even though [this old issue](https://github.com/brettwooldridge/HikariCP/issues/603) was related to failure recovery, the bug report includes a debug log that reveals the pool configuration.

You might also [read this issue](https://github.com/brettwooldridge/HikariCP/issues/1103) and verify that your driver versions are correct.

**Comment by brettwooldridge** [comment]
Try using the PostgreSQL 8.4 dialect.  I also see that someone made a [custom dialect](https://gist.github.com/EugenioLaghi/fdd891ea7df801b3017b) — 2yrs old, may no longer apply.

Either way, this is a Hibernate/Redshift issue, not a HikariCP issue.
