### ISSUE TITLE
你是中国人吗？为啥文档会一个中文字(-.-

### ISSUE THREAD

**Issue by qq443672581** [brettwooldridge/HikariCP#1145]
#### Environment
```
HikariCP version: x.x.x
JDK version     : 1.8.0_111
Database        : PostgreSQL|MySQL|...
Driver version  : x.x.x
```
<sup>⚠️ Please verify that your issue still occurs on the latest version of HikariCP before reporting. </sup>

-----------------------------------------------------------------------------------------
*Have you searched the CLOSED issues already? How about checking [stackoverflow](https://stackoverflow.com/search?q=HikariCP)?*

**Comment by lzysuqianqiu** [comment]
Maybe the author is Japanese

**Comment by brettwooldridge** [comment]
@lzysuqianqiu @qq443672581 I am an American, living in Japan.

**Comment by MrXionGe** [comment]
Hikari is Akali in LOL，Hikari is her Japanese name！

**Comment by qq443672581** [comment]
Today I read the commentary, I saw four down thumbs. You felt that some of the words were not very friendly. I am sorry here, but I did not mean anything bad.
