### ISSUE TITLE
change the MySQL configuration dynamic

### ISSUE THREAD

**Issue by SwagYoYo** [brettwooldridge/HikariCP#1147]
#### Environment
```
HikariCP version: 2.6.1
JDK version     : 1.8.0_144
Database        : MySQL
Driver version  : 5.1.15
```
 Have hikaricp provided an interface  to change the MySQL configuration dynamicly?ex. change the cachePrepStmts=true to cachePrepStmts=false?

-----------------------------------------------------------------------------------------
*Have you searched the CLOSED issues already? How about checking [stackoverflow](https://stackoverflow.com/search?q=HikariCP)?*

**Comment by brettwooldridge** [comment]
You cannot change that parameter.  The parameters that are supported are [documented here](https://github.com/brettwooldridge/HikariCP/wiki/MBean-(JMX)-Monitoring-and-Management),
