### ISSUE TITLE
HikariCP recovery after DB was down

### ISSUE THREAD

**Issue by levirullezz** [brettwooldridge/HikariCP#1148]
Apache 2.4
tomcat 8.5.9
HikariCP version: 2.2.5
JDK version     : 1.8.0_25
Database        : Oracle
Driver version  : ojdbc7

i tried to reconstruct the issue on the lastest hikariCP version (3.1.0) and this also happened, but seems to be in higher scale on HikariCP 2.2.5.

we are running tomcat container on Apache 2.4. we had problem were the database was disconnected and was down for about 50 minutes. as expected, we had many Database related exceptions when the DB was down. 
after the DB return active, we kept seeing timeout exceptions, even after long time has passed since the DB was OK(even 30 minutes after the DB has returned active we kept seeing SQLException).  finally, we had to restart the whole application to make this exceptions disappear.  why hikari kept sending these exceptions even after a very long time? can hikari recover after the DB was down and return active?

the hikari pool is configured to start with 15 idle connections up to max of 100 connections. usually it doesn't get higher than 5-6 busy connections.

stack trace for hikaricp2.2.5:
java.sql.SQLException: Timeout after 30000ms of waiting for a connection.
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:205)
        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:108)
        at com.irrsol.Database.DBManager.getConnection(DBManager.java:85)
        at com.Managers.UserManager.getUserByLoginCode(UserManager.java:2768)

when i tried to reconstruct the issue with hikariCP 3.1.0 i saw that i also get exceptions after the DB had return active , but it seems that they stopped showing after short time(about 2 minutes).

stack trace for hikaricp3.1.0:
java.sql.SQLTransientConnectionException: GS172HikariPool - Connection is not available, request timed out after 30001ms.
        at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:676)
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:190)
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:155)
        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:128)
        at com.irrsol.Database.DBManager.getConnection(DBManager.java:84)
        at com.EUC.GameLibrary.Managers.UserManager.getBalance2(UserManager.java:1503)
-----------------------------------------------------------------------------------------
*Have you searched the CLOSED issues already? How about checking [stackoverflow](https://stackoverflow.com/search?q=HikariCP)?*

**Comment by brettwooldridge** [comment]
Can you post your HikariCP configuration?  If you enable DEBUG level logging for the package ``com.zaxxer.hikari``, the entire pool configuration is logged.

Additionally, it would be useful if you could reproduce the issue while debug logging is enabled, and attach a .zip file of the log here.

**Comment by levirullezz** [comment]
this is the hikariCP configuration:


this is HikariCP pool configuration on test environment, where i reproduced the issue:
[the only change between production and test is that the maximumPoolSize and minimumIdle on prod is 100 and 15 respectively.]

autoCommit......................true
catalog.........................
connectionCustomizer............com.zaxxer.hikari.HikariConfig$1@61e02250
connectionCustomizerClassName...
connectionInitSql...............
connectionTestQuery.............
connectionTimeout...............30000
dataSource......................
dataSourceClassName.............
dataSourceJNDI..................
dataSourceProperties............{password=<masked>}
driverClassName.................
idleTimeout.....................600000
initializationFailFast..........true
isolateInternalQueries..........false
jdbc4ConnectionTest.............false
jdbcUrl.........................jdbc:oracle:thin:@oracle.is.local:1521/sgames
leakDetectionThreshold..........0
maxLifetime.....................1800000
maximumPoolSize.................5
metricRegistry..................
minimumIdle.....................1
password........................<masked>
poolName........................GS18HikariPool
readOnly........................false
registerMbeans..................true
threadFactory...................
transactionIsolation............
username........................gamer


i attached the DB log. at 2018-05-13 13:22:14 i shutdown the DB, and got it back on 2018-05-13 13:23:35.

i get many timeout exceptions even long after the DB was up. see the log attached.
[hikari.log](https://github.com/brettwooldridge/HikariCP/files/1998358/hikari.log)

**Comment by brettwooldridge** [comment]
This is a very old version of HikariCP, please upgrade to v3.0.1.
