### ISSUE TITLE
HikariCP and Jaybird 3.0.3 - org.firebirdsql.jdbc.FBSQLException: This method is only supported on Statement and not supported on PreparedStatement and CallableStatement

### ISSUE THREAD

**Issue by dunda123** [brettwooldridge/HikariCP#1157]
#### Environment
```
HikariCP version: 3.1.0
JDK version     : 1.8.0_162
Database        : Firebird (Jaybird)
Driver version  : 3.03
```
Hi, sorry for my English.
This code:
...
String query1 = "select r_polozka_id, r_ret_val, r_ret_val1 from pps_rec_vcv(?, ?, ?, ?)";
	    try {
	    	Connection con = ds.getConnection();
	    	PreparedStatement st = con.prepareStatement(query1);
	    	st.setInt(1, 1);
	    	st.setInt(2, 1020);
	    	st.setInt(3, 1);
	    	st.setInt(4, 2);
	    	ResultSet rs = st.executeQuery(query1);
...
throw exception for line: ResultSet rs = st.executeQuery(query1);
...
"org.firebirdsql.jdbc.FBSQLException: This method is only supported on Statement and not supported on PreparedStatement and CallableStatement
	at org.firebirdsql.jdbc.AbstractPreparedStatement.executeQuery(AbstractPreparedStatement.java:1296)
	at com.zaxxer.hikari.pool.ProxyStatement.executeQuery(ProxyStatement.java:111)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
	at cz.dunda.pps.ppsservice.model.ppsrecvcv.PpsRecVcvImpl.runPpsRecVcv(PpsRecVcvImpl.java:72)
...

When I try direct JDBC Jaybird, all is ok. When I use HikariCP datasource, code throw exception.

Thank you for your help.
Zdenek.
-----------------------------------------------------------------------------------------
*Have you searched the CLOSED issues already? How about checking [stackoverflow](https://stackoverflow.com/search?q=HikariCP)?*

**Comment by brettwooldridge** [comment]
@dunda123 That makes absolutely no sense.  The exception is clearly thrown by FirebirdSQL [here](https://github.com/FirebirdSQL/jaybird/blob/master/src/main/org/firebirdsql/jdbc/AbstractPreparedStatement.java#L1297).

**Comment by brettwooldridge** [comment]
@dunda123 Do *not* use ``st.executeQuery(query1)`` ... you have already specified ``query1`` when you prepared the statement (ie. ``con.prepareStatement(query1)``).  Use ``st.executeQuery()`` instead (no parameters passed).

**Comment by dunda123** [comment]
Ouuu, i'm stupid. Thanks.
