### ISSUE TITLE
HikariPool-1 - Exception during pool initialization.

### ISSUE THREAD

**Issue by vinod2581** [brettwooldridge/HikariCP#1160]
#### Environment
```
HikariCP version: 3.0.0
JDK version     : 1.8
Database        : SQLServer.
Driver version  : sqljdbc4.0
```
<sup> Hi,  I have an application whiuch is using Hikari CP for  connection pooling. In the eclipse we are able to successfully build the project.  But in the Jenkins it is throwing below error . 

Error Logs
HikariPool-1 - Exception during pool initialization.
com.microsoft.sqlserver.jdbc.SQLServerException: The TCP/IP connection to the host, port 4868 has failed. Error: "connect timed out. Verify the connection properties. Make sure that an instance of SQL Server is running on the host and accepting TCP/IP connections at the port. Make sure that TCP connections to the port are not blocked by a firewall.".

In the pom.xml we are using Hikari CP version 3.0.0 and sqljdbc4.0. 
Any inputs on how to solve the error is very much apprecaited.
Thanks,
Vinod
</sup>

-----------------------------------------------------------------------------------------
*Have you searched the CLOSED issues already? How about checking [stackoverflow](https://stackoverflow.com/search?q=HikariCP)?*

**Comment by brettwooldridge** [comment]
Well, have you verified that you can actually connect to SQL Server from the Jenkins box?  You should be able to telnet to that host and port and at least establish a connection:
```
> telnet mssqlhost 4868
```
If you cannot, that’s you problem; likely something like a firewall or incorrect DNS (if you connect my hostname and not IP).

**Comment by vinod2581** [comment]
Thanks for the solution. But we are not using Jenkins box . we are running jenkins in a browser. Any help is much appreciated.
