### ISSUE TITLE
HikariCP connection gets blocked and does not time out if the external service goes down.

### ISSUE THREAD

**Issue by PallaviSingh1992** [brettwooldridge/HikariCP#1163]
#### Environment
```
HikariCP version: 2.5.1
JDK version     : 1.8.0_111
Database        :  Microsoft SQL Server
```
We have a Lagom service that uses HickariCP to connect to an external service. The issue we are facing is that HickariCP doesn't support FailFast. The request in case the external service goes down goes into a blocking state and does not fail to give us any Failure Response.

Below is the configuration we have used:

db.default {
 hikaricp {
   dataSourceClassName = "com.microsoft.sqlserver.jdbc.SQLServerDataSource"
   dataSource.url = "jdbc:sqlserver://<ip address>;databaseName=default_db"
   dataSource.user = "user"
   dataSource.user = ${?DB_USERNAME}
   dataSource.password = "password"
   dataSource.password = ${?DB_PASSWORD}
 }
}
 
We tried to fix the issue by using the following configurations to make the request fail fast, but none of them worked for us.

connectionTimeout = 5000
maxLifeTime = 4000
validationTimeout = 1000
initializationFailFast = true
initializationFailTimeout = 1
validationTimeout = 5 seconds
acquireRetryAttempts = 1

**Comment by brettwooldridge** [comment]
You will need a driver that supports network timeout.  Use [this driver](https://github.com/Microsoft/mssql-jdbc).
