### ISSUE TITLE
Unknown Thread ID 

### ISSUE THREAD

**Issue by Larisho** [brettwooldridge/HikariCP#1166]
```
HikariCP version: 2.7.8
JDK version     : 1.8.0_111
Database        : MySQL
Driver version  : 5.1.45
```
I've been receiving this error message in production at random intervals and I don't really understand why or how. It started occurring when we switched from Glassfish connection pooling to HikariCP so my first instinct is to think that Hikari is either incorrectly configured or there is a bug, but please feel free to prove me wrong!

Here's the stacktrace:
```
java.sql.SQLException
Unknown thread id: 5052089
at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2480)
at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2438)
at com.mysql.jdbc.StatementImpl.executeInternal(StatementImpl.java:845)
at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:745)
at com.mysql.jdbc.StatementImpl$CancelTask$1.run(StatementImpl.java:120) 
```

Here's my Hikari Configuration:
```
      url: jdbc:mysql://***********************************************
      username: **********
      password: *********************
      type: com.zaxxer.hikari.HikariDataSource
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useServerPrepStmts: true
      useLocalSessionState: true
      useLocalTransactionState: true
      rewriteBatchedStatements: true
      cacheResultSetMetadata: true
      cacheServerConfiguration: true
      elideSetAutoCommits: true
      maintainTimeStats: false
```

**Comment by Larisho** [comment]
I've done some more poking around and this exception is thrown when a query is killed due to a timeout. 
When a query takes too long to execute, Hikari aborts the query. Unfortunately, sometimes MySQL responds with 'Unknown Thread ID: XXXXX' and on checking the process list, the thread is running in MySQL in a locked state. Is there anything that can be done on Hikari's end to handle this or is this purely a MySQL problem?

**Comment by brettwooldridge** [comment]
HikariCP never aborts queries, except on pool shutdown, so the the exception is probably some kind of timeout internal to the driver (or configured on the driver).  If the thread in MySQL is in a locked state, it sounds like a potential deadlock -- or at least heavy lock contention.  Either way, it sounds like an issue to be investigated on the MySQL-side.  You should be able to query the internal locks table (google for it) and find the connection/thread that is _holding_ the lock.

**Comment by Larisho** [comment]
Thank you for the response. Now that you mention that it could be a timeout internal to the driver, could this code be responsible for that timeout? If so, how do I correctly tell HikariCP to give up on a query after a certain amount of time?

```
@Bean
public JdbcTemplate getJDBCTemplate(DataSource source) {
  JdbcTemplate temp = new JdbcTemplate(source);
  temp.setQueryTimeout(timeout);
  return temp;
}
```

**Comment by brettwooldridge** [comment]
Yup, that would do it.  HikariCP has no control over query-level timeouts.  Even if it did, code like the above would surely given precedence, so the net effect would be the same.

Note that ``useLocalTransactionState`` is no longer recommended.  You might start by either removing all of those kinds of settings and adding them back one by one, after verifying that the issue no longer occurs, *or* taking them away one by one until the issue disappears.

If the issue occurs even when all of those optimization’s have been removed, you can investigate why the query is taking so long to run that it hits tgat timeout.

**Comment by Larisho** [comment]
Thank you so much for your help! I really appreciate it.
