### ISSUE TITLE
When will the release 3.1.1 be published？

### ISSUE THREAD

**Issue by yuanpli** [brettwooldridge/HikariCP#1168]
Hi,

There has been more issues had been fixed. And I am looking forward to the new release to enhance our application. 
So could you kindly please publish a new release ASAP?
Thanks a lot!
-----------------------------------------------------------------------------------------
*Have you searched the CLOSED issues already? How about checking [stackoverflow](https://stackoverflow.com/search?q=HikariCP)?*

**Comment by brettwooldridge** [comment]
Release v3.2.0 has been published.
