### ISSUE TITLE
Connection pool thinks all connection are active after a short network downtime

### ISSUE THREAD

**Issue by mihhail-lapushkin** [brettwooldridge/HikariCP#1170]
#### Environment
```
HikariCP version: 2.7.8
JDK version     : 1.8.0_16X
Database        : PostgreSQL
Driver version  : 42.2.2
```
-----------------------------------------------------------------------------------------

We have a Multi-AZ Amazon RDS and one AZ went down. There were 2 separate apps running and connecting to the same DB. One app got a lot of `This connection has been closed` and `connection is dead` exceptions and then recovered nicely. The other one continued throwing `Connection is not available, request timed out after 30000ms` and thinking that 10 out of 10 connections are active for many hours until we restarted it: `Timeout failure stats (total=10, active=10, idle=0, waiting=24)`. From RDS monitoring it is visible that all connections were dropped during AZ switch and only the ones from the first app were re-established again, so the problem seems to be on the Java side.
This might be PG related or due to some weird network anomalies, but nevertheless I wanted to double check.
How is this even possible that a connection is assumed to be alive forever?
Faulty connection handling by Hikari?
Faulty connection handling by Postgres Driver? This was improved in https://github.com/brettwooldridge/HikariCP/issues/593 already.
Faulty connection handling by Java?

**Comment by brettwooldridge** [comment]
HikariCP protects its *own* interactions with the connection (such as validation tests) from network issues by bracketing those interactions with ``setNetworkTimeout()``.

However, application level interactions enjoy no such protection.  If a TCP connection is severed by a network failure or power loss, the normal ACK of packets simply doesn’t occur.  The OS default timeout in the case of unacknowledged TCP is something like 8 hours.

One pool likely had no active queries at the instant of interruption, and therefore recovered quickly.  The other was not so lucky.

I recommend setting the global socket timeout for the pgsql driver.  You need to know your longest running query time and set the timeout a safe margin above that.

If your app servers are on Linux, you can also investigate lowering the OS-level connection keep-alive timeout.  However, if you can set the pgsql global timeout this may not be necessary.

**Comment by mihhail-lapushkin** [comment]
Thanks for clarification!
But it clearly could not have been the case that all 10 connections were active during the failure. The usual load for us according to `Pool stats` is only a few connections at a time. What are the circumstances in which Hikari is able to say that a connection is dead vs it is an active zombie connection?

**Comment by brettwooldridge** [comment]
Do you have a way to simulate the DB down?  A thread dump, to see exactly where the threads were blocked would be extremely useful.

Either way, setting the global socket timeout would cover all possible unacknowledged TCP cases.

**Comment by mihhail-lapushkin** [comment]
Seems that the timeout is the optimal solution here. Thank you!
If someone reading this uses SpringBoot + Postgres, then this is how you set it (in seconds):
```
spring.datasource.connectionProperties=socketTimeout=300
```
