### ISSUE TITLE
Documentation About Pool Sizing (Threads or Connections?)

### ISSUE THREAD

**Issue by evbo** [brettwooldridge/HikariCP#1171]
In your [formula here](https://github.com/brettwooldridge/HikariCP/wiki/About-Pool-Sizing), you describe units of "connections". But in the first paragraph, you discuss tuning the number of threads. Which is this article advocating the use of this equation for? max connections or number of threads?
```
connections = ((core_count * 2) + effective_spindle_count)
```
The slick API seems to indicate this article is discussing tuning the number of threads:
```
numThreads (Int, optional, default: 20): The number of concurrent threads in the thread pool for asynchronous execution of database actions. See the HikariCP wiki for more imformation about sizing the thread pool correctly. Note that for asynchronous execution in Slick you should tune the thread pool size (this parameter) accordingly instead of the maximum connection pool size.
```

**Comment by brettwooldridge** [comment]
The number of threads here are the threads within the database process.  In concrete terms, a query, dispatched over a connection, will execute on a single thread in the database.  So, in practical terms, there ends up being a one-to-one relationship between connections and threads (in nearly all cases).
