### ISSUE TITLE
Connection pool release when terminal the application

### ISSUE THREAD

**Issue by exotfboy** [brettwooldridge/HikariCP#1173]
The `maxconnection` is set to `400` in my application, and when I debug or run the application in IDEA, 400 connections will be created (I can see this from the logs).

Then when I hit the `stop` button in the ide, and start the application again extra 400 connections will be created again. So the database will throw exception like `too many connections` after a few restart operation.

I have tried to add the exit hook like this:

```
    Runtime.getRuntime().addShutdownHook(new Thread()
    {
      public void run()
      {
       //close HikariCP  connection pool
      }
    });
```

However this is not called at all when I hit the `stop` button.

So I wonder if  HikariCP can close the connection by itself?

I have found this [issue](https://github.com/brettwooldridge/HikariCP/issues/210), but things does not change after I set the `idleTimeout` and `maxLifetime`.

How do you handle this kind of problem?

**Comment by brettwooldridge** [comment]
HikariCP cannot “close itself”.  You need to investigate why the stop button in IDEA does not terminate the JVM in a graceful manner.  Maybe there is a setting that controls that behavior.

Also, 400 connections is ridiculous, unless you have 200 CPU cores.  Please read the [sizing recommendations](https://github.com/brettwooldridge/HikariCP/wiki/About-Pool-Sizing).
