### ISSUE TITLE
Setting `useLocalTransactionState` to `true` causes INSERTS with LOBs to silently fail

### ISSUE THREAD

**Issue by bsbodden** [brettwooldridge/HikariCP#1176]
#### Environment
```
HikariCP version: 2.7.2
JDK version     : 1.8.0_45
Database        : 10.2.11-MariaDB-log MariaDB Server
Driver version  : mysql-connector-java:5.1.44
```
Just an FYI, the issue goes away if you:
- set `useLocalTransactionState` to `false` OR
- switch to the MariaDB driver (I used `mariadb-java-client:2.2.3`)

**Comment by brettwooldridge** [comment]
Yup.  It causes other issues as well.  I removed it from the wiki page [about a month ago](https://github.com/brettwooldridge/HikariCP/wiki/MySQL-Configuration/_compare/874346e007a1632d3e0273ed0413168ea0cdbe35...fbafda5e998de73185d4c21f99a0d7fec6649b5c).
