### ISSUE TITLE
Idle connections aren't returned to pool

### ISSUE THREAD

**Issue by kaisteel** [brettwooldridge/HikariCP#1178]
#### Environment
```
HikariCP version: 2.7.8
JDK version : 1.8.0_161
Database : PostgreSQL
Driver version: 9.6.3 (AWS RDS)
```
I'm using HikariCP for data pooling in my webapps deployed on tomcat server with the following configuration
```
<Resource auth="Container"
             poolName="testApp"
             factory="com.zaxxer.hikari.HikariJNDIFactory" 
             driverClassName="org.postgresql.Driver"
             minimumIdle="1" 
	     maximumPoolSize="2" 
	     connectionTimeout="300000"
	     idleTimeout="120000"
	     maxLifetime="1800000"
	     dataSource.implicitCachingEnabled="true"
             name="jdbc/mtgPostgreSQL"
	     type="javax.sql.DataSource"
             jdbcUrl="jdbc:postgresql://rds_link:5432/testing?ApplicationName=testApp&amp;useOldAliasMetadataBehavior=true&amp;useEncoding=true&amp;characterEncoding=UTF-8&amp;zeroDateTimeBehavior=convertToNull&amp;characterSetResults=UTF-8&amp;allowMultiQueries=true"
             username="foo"
             password="bar"/>
```
@brettwooldridge I've 15 webapps use the above configuration whereas and 3 more which uses Spring Boot which uses default HikariCP config so going by that at any given point there should be (2\*15+3\*10) 60 idle connections rather there are 80 idle connections, due to which when I try to perform Jmeter test (on any 1 out of 15 webapps which uses above config) for 100 concurrent users I get error saying `remaining connection slots are reserved for non-replication superuser connections, too many clients already` that's because RDS allows 87 connections for normal users and reserves 2-3 for superuser.
But that shouldn't be the case..because I'm setting my `maximumPoolSize` to `2` so if a request asks for the connection it should wait for 5mins as per my `connectionTimeout` and then throw a `HikariDataSource Exception getting connection: Timeout after 300000ms of waiting for a connection.` instead of `remaining slots are reserved...`
Now I've read it in one of the issues's in which you were explaining how HikariCP replenishes the pool every 30 sec but there can be a condition where the current `minimunIdle` is 0 since all are under utilization but it still adds default number of connections in pool ie 10 which might be little too much sometime but again those are removed after the `idleTimeout` is reached.
That might be the case why I get `remaining slots are reserved...` error since it tries to add more than allowed connections.
But here is the thing, when I use pgAdmin to monitor the real-time graph of connections... I never see a drop in the graph of `idle connection` in spite of setting the `idle timeout`, the graph either goes up or just stays at 80. What should I do to get this idle connections number down?
Sorry for the lengthy post, please let me know how can I solve this.

**Comment by kaisteel** [comment]
![image](https://user-images.githubusercontent.com/8086855/41464280-603b8a4a-70b7-11e8-9409-c07427690b64.png)
the `adminapi` application uses the above configuration still there are 3 idle connections open and this happens with all those 15 webapps.

**Comment by kaisteel** [comment]
@brettwooldridge I know you must be very busy, please have a look at it. The problem might be very trivial but I can't see where I'm going wrong.

**Comment by brettwooldridge** [comment]
First, please upgrade to the latest HikariCP version and see if the problem still occurs.

Second, enable debug logging for com.zaxxer on all servers.  Every connection creation will be logged, as well as pool stats every 30 seconds.

**Comment by kaisteel** [comment]
Thanx, I've upgraded to the latest version and will observe how the connection-pool behaves.

**Comment by rveede** [comment]
@kaisteel did that solve your issue?
I am experiencing the same problem with the HikariCP version (2.7.9) that comes with Spring Boot 2.0.3.

**Comment by kaisteel** [comment]
@rveede I've upgraded to latest version and now I've added `closeMethod="close"` attribute in my above `<Resource>` tag that has helped in bringing the number of open connections down a bit, but it still comes up when I run JMeter tests to make a lot of concurrent requests.

**Comment by kaisteel** [comment]
The seems to have gone now mysteriously, thank you for the support @brettwooldridge.
Closing this issue.
PS: @rveede I didn't make any new changes apart from my last comment. Hope that had helped you

**Comment by SachiAnn** [comment]
@brettwooldridge Can you explain me what is idle connection in Hikari pool?

**Comment by brettwooldridge** [comment]
@Jony2907 Come'on man.  https://en.wikipedia.org/wiki/Connection_pool

**Comment by SachiAnn** [comment]
@brettwooldridge 
spring.datasource.hikari.idle-timeout=60000
spring.datasource.hikari.maxLifetime=120000

If I close the idle connection, then what about max life time? I am getting confuse with them.

**Comment by brettwooldridge** [comment]
If ``minimumIdle`` is not set, HikariCP operates as a _fixed-size_ pool with ``maximumPoolSize`` connections.  In this case, ``idleTimeout`` **does nothing**, and if you set it a warning will be logged at startup.

If ``minimumIdle`` _is_ set, then ``idleTimeout`` will be honored and connections that sit idle (unused) for longer than that time will be closed.

Finally, even with ``minimumIdle`` set it is possible that your pool is always busy, and therefore connections never reach the ``idleTimeout`` and are never closed.  This would be fine except that database servers, load-balancers, etc. often limit a connection/socket lifetime to some maximum -- such as 1 hour, or 8 hours.

The ``maxLifetime`` property is meant to allow the pool to pro-actively retire connections before they are closed by the "other side".  If that happens, it can cause delays for the application as it has to await the creation of a new connection right when it is was ready to execute a query.  The pool will close connections that reach ``maxLifetime`` pro-actively in a way to tries to avoid delays for the application -- such as closing them as soon as they return to the pool.

**Comment by SachiAnn** [comment]
@brettwooldridge Thank you so much for your reply. Now its very clear

**Comment by SachiAnn** [comment]
@brettwooldridge 
I am getting the pool stats, when I set minIdle=10 and maxPoolSize=20
HikariPool-1 - Pool stats (total=10, active=0, idle=10, waiting=0)  then what is the purpose we set size=20? can you explain??

**Comment by brettwooldridge** [comment]
Ok, these questions are really too basic.  Please read documentation anywhere about any connection pool on any blog or stackoverflow, this is really fundamental. I’m pretty sure the documentation on the project page is completely clear on these properties.

Please direct any further questions to stackoverflow.
