### ISSUE TITLE
Pool Connections were not getting released and application gets hanged by throwing java.sql.SQLException waiting for connection 

### ISSUE THREAD

**Issue by subbumopuri** [brettwooldridge/HikariCP#1183]
#### Environment
```
HikariCP version: 2.7.4
JDK version     : 1.8.0_151
Database        : Oracle 12c
JDBC Driver    : ojdbc8
Tomcat version : 8.5.12
```
<sup>Hi @brettwooldridge,

We have migrated connection pool from primerose (leagcy) to HikariCP in our application. When we perform load test with 10 and 20 users below errors were occurring and connections were not getting closed even after the load test completes.

Connections are not getting closed,even application also not working and throwing SQLException and we had to restart the tomcat server whenever load test is performed.

We tried with increasing the maximumPoolSize from 25,50, 100, 200. When performing with more poolSize then there was no issue. But this seems to be strange, that for handling requests below 5000 also we need to configure more pool size which was not desirable.

HikariCP config
        class="com.zaxxer.hikari.HikariDataSource" destroy-method="close"
        p:username="${database.jdbc.username}"
        p:password="${database.jdbc.password}"
        p:jdbcUrl="${database.jdbc.url}"
        p:readOnly="true"
        p:driverClassName="oracle.jdbc.OracleDriver"
        p:initializationFailFast="true"
        p:leakDetectionThreshold="120000"
        p:connectionTimeout="45000"
        p:autoCommit="false"
        p:minimumIdle="5"
        p:maximumPoolSize="50"  

         defaultRowPrefetch = 250
         oracle.jdbc.TcpNoDelay= true

Please find below logs
============================
**DEBUG {HH:mm:ss.SSS} c.z.hikari.pool.ProxyConnection - HikariPool-2 - Executed rollback on connection oracle.jdbc.driver.T4CConnection@1a922b2 due to dirty commit state on close().
DEBUG {HH:mm:ss.SSS} c.z.hikari.pool.ProxyConnection - HikariPool-2 - Executed rollback on connection oracle.jdbc.driver.T4CConnection@895983 due to dirty commit state on close().
[pool-9-thread-4] DEBUG {HH:mm:ss.SSS} c.z.hikari.pool.ProxyConnection - HikariPool-2 - Executed rollback on connection oracle.jdbc.driver.T4CConnection@1a922b2 due to dirty commit state on close().
[pool-9-thread-6] DEBUG {HH:mm:ss.SSS} c.z.hikari.pool.ProxyConnection - HikariPool-2 - Executed rollback on connection oracle.jdbc.driver.T4CConnection@18bc456 due to dirty commit state on close().
[pool-9-thread-1] DEBUG {HH:mm:ss.SSS} c.z.hikari.pool.ProxyConnection - HikariPool-2 - Executed rollback on connection oracle.jdbc.driver.T4CConnection@1a922b2 due to dirty commit state on close().
[pool-9-thread-2] DEBUG {HH:mm:ss.SSS} c.z.hikari.pool.ProxyConnection - HikariPool-2 - Executed rollback on connection oracle.jdbc.driver.T4CConnection@18bc456 due to dirty commit state on close().
[HikariPool-2 housekeeper] WARN  {HH:mm:ss.SSS} c.zaxxer.hikari.pool.ProxyLeakTask - Connection leak detection triggered for oracle.jdbc.driver.T4CConnection@1b453b8 onthread http-nio-13.129.103.19-8085-exec-4, stack trace follows
java.lang.Exception: Apparent connection leak detected at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112) ~[HikariCP-2.7.4.jar:na]
....
....		
DEBUG {HH:mm:ss.SSS} com.zaxxer.hikari.pool.HikariPool - HikariPool-2 - Before cleanup stats (total=50, active=50, idle=0, waiting=13)
DEBUG {HH:mm:ss.SSS} com.zaxxer.hikari.pool.HikariPool - HikariPool-2 - After cleanup  stats (total=50, active=50, idle=0, waiting=13)
DEBUG {HH:mm:ss.SSS} com.zaxxer.hikari.pool.HikariPool - HikariPool-2 - Timeout failure stats (total=50, active=50, idle=0, waiting=13)
DEBUG {HH:mm:ss.SSS} com.zaxxer.hikari.pool.HikariPool - HikariPool-2 - Timeout failure stats (total=50, active=50, idle=0, waiting=12)
DEBUG {HH:mm:ss.SSS} com.zaxxer.hikari.pool.HikariPool - HikariPool-2 - Timeout failure stats (total=50, active=50, idle=0, waiting=12)
.....
DEBUG {HH:mm:ss.SSS} com.zaxxer.hikari.pool.HikariPool - HikariPool-2 -Before cleanup stats (total=50, active=50, idle=0, waiting=1)
DEBUG {HH:mm:ss.SSS} com.zaxxer.hikari.pool.HikariPool - HikariPool-2 - After cleanup  stats (total=50, active=50, idle=0, waiting=1)
DEBUG {HH:mm:ss.SSS} com.zaxxer.hikari.pool.HikariPool - HikariPool-2 - Timeout failure stats (total=50, active=50, idle=0, waiting=0)
.....
DEBUG {HH:mm:ss.SSS} com.zaxxer.hikari.pool.HikariPool - HikariPool-2 - Before cleanup stats (total=50, active=50, idle=0, waiting=0)
DEBUG {HH:mm:ss.SSS} com.zaxxer.hikari.pool.HikariPool - HikariPool-2 - After cleanup  stats (total=50, active=50, idle=0, waiting=0)
DEBUG {HH:mm:ss.SSS} com.zaxxer.hikari.pool.HikariPool - HikariPool-2 - Before cleanup stats (total=50, active=50, idle=0, waiting=0)
DEBUG {HH:mm:ss.SSS} com.zaxxer.hikari.pool.HikariPool - HikariPool-2 - After cleanup  stats (total=50, active=50, idle=0, waiting=0)**

======================================
And after the load test completed and if we try to access the application we are getting below errors
**java.sql.SQLException: Timeout of 450000ms encountered waiting for connection** 

Can you please advise here in this scenario.
</sup>

-----------------------------------------------------------------------------------------
*Have you searched the CLOSED issues already? How about checking [stackoverflow](https://stackoverflow.com/search?q=HikariCP)?*

**Comment by brettwooldridge** [comment]
Enable the ``leakDetectionThreshold`` and watch the log for reported leaks.  If there are no leaks, feel free to reopen this issue.

**Comment by subbumopuri** [comment]
I have enabled **leakDetectionThreshold** already. You can see the configuration in the issues details posted. Still we are not able to find leak detection. But connections were not getting released once pool reaches maximum and application becomes down. I’m tired of trying various configurations and other parameters to analyse issue. Still I was not able find the cause.

> Any thoughts on this ?

**Comment by carloshager** [comment]
did you get it fix? I'm having the same problem.
recently I thought it could be the missing socketTimeout, but even the connection is not there anymore, it's not updating the pool and releasing from active.

**Comment by brettwooldridge** [comment]
@carloshager you case sounds like a connection leak.  Please set the leakDetectionThreshold and check your logs.
