### ISSUE TITLE
About Hikari and Alibaba-Druid

### ISSUE THREAD

**Issue by MrXionGe** [brettwooldridge/HikariCP#1188]
Execuse me !
I always use Druid in my project.
Alibaba says it is the best CP in Java World.
Do we have a comparison with Alibaba-Druid ?
When I meet HikariCP , I think maybe it is a good choice for Vert.x or Play Framework.
Now , I am trying reactive web(Vert.x&Spring WebFlux).
Is HikariCP more suitable for reactive development with Ebean ?

**Comment by Chris2018998** [comment]
Here is a performance test comparison that may not be very accurate,please visit
https://github.com/Chris2018998/Bee
