### ISSUE TITLE
Question: Setting connection properties in spring application.yml

### ISSUE THREAD

**Issue by dannycohn** [brettwooldridge/HikariCP#1189]
Using Spring with TomcatCP, I can do this:

```
spring:
  datasource:
    driverClassName: oracle.jdbc.OracleDriver
    tomcat:
      connectionProperties: defaultRowPrefetch=1000;
```

How would I set the defaultRowPrefetch when using Hikari? Can I do it only with Spring config files?

**Comment by brettwooldridge** [comment]
I’m pretty sure you can, but you’ll need to ask on stackoverflow or the Spring groups.

**Comment by mar1ged** [comment]
Linking to this SO question because Google brought me here ...

https://stackoverflow.com/questions/34856811/how-to-set-custom-connection-properties-on-datasource-in-spring-boot-1-3-x-with/55648779#55648779

(Despite the URL this is relevant for HikariCP and current versions of Spring Boot >= 2.x)
