### ISSUE TITLE
how to use for mysql5  and  mysql8  on one time

### ISSUE THREAD

**Issue by ywww** [brettwooldridge/HikariCP#1192]
how to use for mysql5  and  mysql8  on one time

**Comment by billoneil** [comment]
Make two connection pools?

**Comment by ywww** [comment]
how to dynamic load different mysql jdbc driver on one time

**Comment by johnou** [comment]
load two drivers and then use the correct driver in the jdbc url for each pool.

**Comment by brettwooldridge** [comment]
You’ll need two separate classloaders, and set the Thread context classloader before initializing each pool.

**Comment by minesunny** [comment]
> You’ll need two separate classloaders, and set the Thread context classloader before initializing each pool.


‎HikariConfig::setDriverClassName, it just check to Load driver class using contentClassLoader, but
‎DriverDataSource::DriverDataSource use DriverManager.getDrivers() to get driver instance firstly. DriverManager.getDrivers() will check driver througth Reflection.getCallerClass() which is DriverDataSource.class,and it would return a driver class loaded by DriverDataSource's classsloader. what if the DriverDataSource's classsloader is different from the current context classloader, the result is the class not found.so if I want load different version mysql driver,I need the separate classloaders to load two separate hikaricp jar firstly and let each hikaricp jar to load one drive;
