### ISSUE TITLE
Please help me on JMH test

### ISSUE THREAD

**Issue by Chris2018998** [brettwooldridge/HikariCP#1194]
I'm a Java beginner and made a connection pool(BeeCP), 
then test it with HikariCP's Benchmark test code, but its score is too high,I think must exists some problems. I have no enough ability to find out the reason in long time so,I hope to get help from grand master. please visit : https://github.com/Chris2018998/BeeCP

**Comment by Chris2018998** [comment]
Please add the follow method to :com.zaxxer.hikari.benchmark.hikari.BenchBase

private void setupBee() {
	try {
		JdbcPoolConfig sourceInfo = new JdbcPoolConfig("com.zaxxer.hikari.benchmark.stubs.StubDriver",jdbcUrl,"brettw","");
		sourceInfo.setPoolMaxSize(maxPoolSize);
		sourceInfo.setPoolInitSize(MIN_POOL_SIZE);
		sourceInfo.setConnectionMaxWaitTime(8000);
		sourceInfo.setStatementCacheSize(20);
		sourceInfo.setConnectionTestQuerySql("SELECT 1");
		BeeDataSource datasource = new BeeDataSource(sourceInfo);
		DS = datasource;
	} catch (SQLException e) {
		e.printStackTrace();
	}
}

Download BeeCP :https://github.com/Chris2018998/Bee/blob/master/Doc/jmin_bee_0.5.jar

**Comment by brettwooldridge** [comment]
@Chris2018998 Congratulations on undertaking writing a connection pool.  Unfortunately, there is no source code at the repository link provided.

A key part of writing a robust pool is handling the many edge cases that exist and adherring to JDBC compliance.  Feel free to copy my junit tests and modify them to fit you needs.  I think at least 50-60% of them are not dependent on HikariCP implementation details, and could be run for any pool.

Most of the tests that can be adapted to your pool simply require replacing the HikariDataSource with your own.

**Comment by Chris2018998** [comment]
Thanks , I have found the  reason.
