### ISSUE TITLE
what's the purpose to generate HikariProxyConnection by javaassist since you already write ProxyConnection ?

### ISSUE THREAD

**Issue by Mobel123** [brettwooldridge/HikariCP#1198]
according to the source code, I found ProxyConnection already do a lot of things, HikariProxyConnection only add a try catch block to every method. 
I was so confused. it would be nice if anyone can give an explanation. thanks in advance!

**Comment by brettwooldridge** [comment]
The proxies delegate to the real driver classes.  Some proxies, like the one for ResultSet, only intercept a few methods.  Without the code generation, the proxy would have to implement all 50+ methods which simply delegate to the wrapped instance.

Code generation, based on reflection, also means that nothing needs to be done when a new JDK version introduces new JDBC methods to existing interfaces.

**Comment by Mobel123** [comment]
@brettwooldridge  thanks a lot

**Comment by fengchangsheng** [comment]
Although the ProxyConnection is a abstract class, as a connection-pooling, must impl this method in fact. Generate these class just for compatible with high version JDK?

**Comment by brettwooldridge** [comment]
A concrete class is generated from the abstract ``ProxyConnection`` class.  Any methods that are not "overridden" by the abstract class, and that throw SQLException have delegates generated with the following code:
```java
{
  try {
    return delegate.method($$);
  } catch (SQLException e) {
    throw checkException(e);
  }
}
```
... which allows us to inspect the exception to see if it represents a disconnection error.

A side-effect is that, yes, the code ends of being flexible with respect to JDBC API changes -- at least all that we have encountered so far.

**Comment by fengchangsheng** [comment]
@brettwooldridge thanks for the "official" response!
