### ISSUE TITLE
Timeout at com.zaxxer.hikari.HikariDataSource.getConnection

### ISSUE THREAD

**Issue by sazonov** [brettwooldridge/HikariCP#1199]
#### Environment
```
HikariCP version: 2.7.9
JDK version     : 1.8.0_101
Database        : PostgreSQL 9.5
Driver version  : 42.2.2
ORM : EclipseLink 2.7.1
```

Hi! I'm facing a strange behaviour using Spring Boot 2.0.2 and HikariCP 2.7.9. Sometimes pool connections start to hang in getConnection method but in the same time pool has many idle connections.

Logs:
2018-07-12 09:05:38.261 DEBUG 19298 --- [HikariPool-1 housekeeper] com.zaxxer.hikari.pool.HikariPool        : HikariPool-1 - Pool stats (total=64, active=49, idle=15, waiting=0)
2018-07-12 09:05:42.935  WARN 19298 --- [HikariPool-1 housekeeper] com.zaxxer.hikari.pool.ProxyLeakTask     : Connection leak detection triggered for org.postgresql.jdbc.PgConnection@64f03727 on thread XNIO-2 task-36, stack trace follows

java.lang.Exception: Apparent connection leak detected
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:128)
        ....

Datasource configuration:
dataSource.driverClassName=org.postgis.DriverWrapper
dataSource.maximumPoolSize=64
dataSource.maxLifetime=300000
dataSource.leakDetectionThreshold=60000

Ussually this happens after 20-30 hours of application uptime.

If it helps the database had 64 connections "idle in transaction" at the time from logs. If I swith to tomcat-jdbc this issue doesn't reproduce and I have no lags with database connections.

Could you please tell how I can fix that?

**Comment by brettwooldridge** [comment]
A hang would produce timeout exceptions, but you don’t show any.

You do show a connection leak, which will eventually kill your server.  Tomcat will allow you to abandon connections and keep running, HikariCP will not.

Fix your connection leak first.

**Comment by sazonov** [comment]
Found unresolved issue that looks very similar to mine: https://github.com/brettwooldridge/HikariCP/issues/109

**Comment by brettwooldridge** [comment]
@sazonov Maybe [this answer](https://stackoverflow.com/questions/26490967/how-do-i-configure-hikaricp-in-my-spring-boot-app-in-my-application-properties-f/33213802) helps?

Did you originally follow [these guidelines](http://wiki.eclipse.org/EclipseLink/Examples/JPA/Tomcat_Web_Tutorial#Install_the_Tomcat_6_Web_Container)?

Can you turn on DEBUG level logging for the ``com.zaxxer.hikari`` package?  I really want to see the logs that preceed and follow a timeout exception.  You can zip a log and attach it here.

**Comment by sazonov** [comment]
Okay, I will try to reproduce it on my test environment and send additional info. Production env was moved to tomcat-jdbc today.

**Comment by sazonov** [comment]
Thanks for the links. I used Spring guides to configure my app.

**Comment by brettwooldridge** [comment]
We haven't had a lot of user's on EclipseLink.  Not that there is anything wrong with the choice.  If we can sort out the cause of the failure, and pin down what a good SpringBoot-EclipseLink-HikariCP configuration looks like, I would love your help/input in wiki'ing up the result for future users!

**Comment by brettwooldridge** [comment]
Are you running with?
 * ``eclipselink.persistence-context.close-on-commit=true``
 * ``eclipselink.persistence-context.flush-mode=commit``
 * ``eclipselink.jdbc.exclusive-connection.mode=Transactional``

**Comment by sazonov** [comment]
I have all options set except the last one.

spring.jpa.properties.eclipselink.persistence-context.close-on-commit=true
spring.jpa.properties.eclipselink.persistence-context.flush-mode=commit
spring.jpa.properties.eclipselink.persistence-context.persist-on-commit=false

**Comment by brettwooldridge** [comment]
@sazonov The last one is the default value, I just wanted to make sure it wasn't changed to some other mode.

**Comment by sazonov** [comment]
Yes, I'm using the default value.

**Comment by sazonov** [comment]
Just reproduced issue on the test env. Attached you will find a log file. Just after a few seconds after application start hikari health checker detected connection leak but both connection pools had idle connections at the same time. There was no connection timeout error after that and the connection was returned to the pool 10 minutes later.

Could you please tell if house keeper says that we have a leak at getConnection method so it means that active thread is waiting for a connection or thread already has a connection and query is in progress?

[HikariCP debug.log](https://github.com/brettwooldridge/HikariCP/files/2191881/HikariCP.debug.log)

**Comment by brettwooldridge** [comment]
Ok, a couple of things to note...

The idle timeout in pool #1 is too close to the maxLifetime, so idle connections are being ignored.  I suggest setting the idleTimeout to 180000, and minimumIdle to 16.

Pool #2 does not have the leakDetectionThreshold enabled.

Some thread is borrowing a connection for 10 minutes, what is going on there?

Some thread seems to borrow a connection from Pool #2, but does not return it.  Because the leakDetectionThreshold is not enabled, it is not reported.

**Comment by sazonov** [comment]
Second pool has no timeout because it is used to build quite big reports and we have no problems with it. Log error is about pool 1. Okay, I will try to set idleTimeout.

I couldn't find the answer to my previous question. Could you please tell if house keeper says that we have a leak at getConnection method so it means that active thread is waiting for a connection or that thread already has a connection and query is in progress?

**Comment by brettwooldridge** [comment]
@sazonov The leak detection log means that a thread "already has a connection and query is in progress" (not that it is waiting).  The stacktrace that is logged shows where the code acquired the connection -- i.e. where it originally called ``getConnection()`` -- not where it currently is.

**Comment by maximmold** [comment]
Is it possible to get information about the last query ran on a connection when a leak is detected? Sometimes the stack trace provides no useful information, e.g. when using scala and slick it uses a ThreadPoolExecutor to acquire sessions in response to Futures.

**Comment by itmifen** [comment]
Is there any conclusion to this question？I had a similar problem.
Is this a problem caused by multiple data sources or multiple thread pools and inconsistent set parameters for each thread pool?


db1: 
  connection-init-sql: select 1
  driver-class-name: com.mysql.jdbc.Driver
  idle-timeout: 10000
  maxLifetime: 1800000
  maximum-pool-size: 40
  minimum-idle: 10
  pool-name: DataSource1
db2:
  connection-init-sql: select 1
  driver-class-name: com.mysql.jdbc.Driver
  idle-timeout: 10000
  maxLifetime: 1800000
  maximum-pool-size: 20
  minimum-idle: 10
  pool-name: DataSource2

**Comment by ZacParize** [comment]
Hi, i got the similar issue. Basically i am using spring boot with hibernate and hikari db pool. My service is quite typical: spring transactions and hibernate as JPA. Settings of db pool:

hikari:
      connection-timeout: 15000
      max-lifetime: 60000
      maximum-pool-size: 90
      health-check-properties:
        connectivity-check-timeout-ms: 1000
      validation-timeout: 2000
      leak-detection-threshold: 60000
      connection-test-query: SELECT 1
      minimum-idle: 80

After 30 minute of my application's work i got following exceptions:

o.h.engine.jdbc.spi.SqlExceptionHelper   : HikariPool-1 - Connection is not available, request timed out after 5099ms.
o.h.engine.jdbc.spi.SqlExceptionHelper   : SQL Error: 0, SQLState: null

**Comment by brettwooldridge** [comment]
@ZacParize I have the same question as above.  Are you getting leak detection exceptions in your log?

**Comment by sazonov** [comment]
I've been inspecting my app for last two weeks and found that I have a code that uses both datasources at the same time in one transaction. So app got stucked in pool 1 because of pool 2. It is wrong and I rewrote that code. Now I'm waiting for the next release to depoy to production env and test it under high load. I hope that will solve the issue. Anyway I will write down issue status after that release.

**Comment by ZacParize** [comment]
@brettwooldridge , Yes i turned up leak detection debug and got leak detection exception. 
I want to add that the problem apperars under high load. 

I suspect the exception occurs because of my incorrect settings. If i have connection-timeout 15 seconds and processing of all records needs more than 15 seconds than i get connection timeout exception. But when will it be? When i will try to commit or when i will release the connection to pool?

Thanks for your help.

**Comment by ZacParize** [comment]
Sorry for the stupid question, but what does mean 

ERROR 7 --- [l-1312-thread-1] o.h.engine.jdbc.spi.SqlExceptionHelper   : HikariPool-1 - Connection is not available, request timed out after 30499ms

the exception? 

Is it a situation when connection was obtained from pool's connection bag but it was closed?

**Comment by brettwooldridge** [comment]
@ZacParize That error occurs when all of the connections are out of the pool (in-use) for more than the ``connectionTimeout``, and another thread calls ``ds.getConnection()``.

Essentially, the pool was at maximum size, so no new Connections could be created, and all of the Connections were in-use.  After 30 seconds (``connectionTimeout``) of waiting for a connection to be returned to the pool, the requesting thread timed out.

If you look in the log, at DEBUG level, you can probably see that the available (idle) connections were 0, and there were one or more (possibly many) threads waiting for a connection.  Even if some connections are returned during the 30 seconds, if there are too many threads waiting, then the thread at the back of the queue may not get one before the timeout is reached.

**Comment by ZacParize** [comment]
@brettwooldridge , thanks for your responds. 

I figured out that my problem was in the incorrectly calculated transaction time.
Your explanation helped me a lot.
Thanks for cool product.

**Comment by sazonov** [comment]
I checked the last build of my app on production env and the issue didn't reproduce. So the problem was caused by using two pools in the same time. When one one pool was exceeded I got error messages with timeout from the other pool. I'm closing this issue. @brettwooldridge thanks for your time and assistance.

**Comment by daiguocheng** [comment]
It seemed that the timeout has happened.
Append `&connectTimeout=3&socketTimeout=3` to `dataSource.url` and try again.

**Comment by jameskandau** [comment]
[DEBUG] [] [HikariPool-1 housekeeper] [c.zaxxer.hikari.pool.HikariPool] - HikariPool-1 - Pool stats (total=20, active=0, idle=20, waiting=0) and the application still freezes. I am using RabbitMQ to save data to Mysql Database
