### ISSUE TITLE
Unable to set connection pool to read-only

### ISSUE THREAD

**Issue by lhartzman** [brettwooldridge/HikariCP#1200]
#### Environment
```
HikariCP version: 3.2.0
JDK version     : 1.8.0_161
Database        : MySQL
Driver version  : 8.0.11
```
<sup>⚠️ Using the latest and greatest </sup>

-----------------------------------------------------------------------------------------
*Have you searched the CLOSED issues already? How about checking [stackoverflow]
Yes

I've got 2 datasources - 1 is for write and the other for read. I've tried to set the property in my Spring Boot application.properties file, but the configuration shown in the _catalina.out_ log shows that the readOnly setting is false. 

I have a configuration class that uses the properties in the application.properties files to configure the pool, but can't seem to get it to change the _readOnly_ property from ```false``` to ```true```.
I also tried to put a ```setReadOnly(true);``` statement within the ```dataSource()``` method - didn't work.

```
@Configuration
@EnableTransactionManagement
@EnableConfigurationProperties
@ConfigurationProperties(prefix = "reader.datasource")
@EnableJpaRepositories(
        entityManagerFactoryRef = "entityManagerFactory",
        basePackages = {"com.abc.data.reader.repo"})
public class ReaderDataSourceConfig extends HikariConfig {

    @Bean(name = "readerDataSource")
    public DataSource dataSource() {
        return new HikariDataSource(this);
    }
    
    @Bean(name = "entityManagerFactory")
    public LocalContainerEntityManagerFactoryBean entityManagerFactory(
            EntityManagerFactoryBuilder builder, @Qualifier("readerDataSource") DataSource dataSource) {
        return builder.dataSource(dataSource).packages("com.abc.repo")
                .persistenceUnit("reader")
                .build();
    }
    
    @Bean(name = "transactionManager")
    public PlatformTransactionManager transactionManager(@Qualifier("entityManagerFactory") EntityManagerFactory entityManagerFactory) {
        return new JpaTransactionManager(entityManagerFactory);
    }
}
```
And the lines from the properties file:
```
#HikariCP Reader config
reader.datasource.jdbc-url=jdbc:mysql://...
reader.datasource.username=###
reader.datasource.password=#####
reader.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
reader.datasource.maximum-pool-size=10
reader.datasource.connection-timeout=60000
reader.datasource.max-lifetime=1800000
reader.datasource.minimum-idle=10
reader.datasource.validation-timeout=15000
reader.datasource.read-only=true         ***tried multiple variations***
reader.datasource.hikari.read-only=true      
reader.datasource.readOnly=true
reader.dataSource.cachePrepStmts=true
reader.dataSource.prepStmtCacheSize=250
reader.dataSource.prepStmtCacheSqlLimit=2048
reader.dataSource.useServerPrepStmts=true
reader.dataSource.useLocalSessionState=true
reader.dataSource.rewriteBatchedStatements=true
reader.dataSource.cacheResultSetMetadata=true
reader.dataSource.cacheServerConfiguration=true
reader.dataSource.elideSetAutoCommits=true
reader.dataSource.maintainTimeStats=false
reader.datasource.pool-name=ReaderPool
```
Is it not possible to set it through a property file?

**Comment by neoxpert** [comment]
For me the readOnly property works when I pass it using my properties file. How does the created HikariConfig look like if you load the properties file? May it be that you misspelled "datasource". As shown in the example configuration it should spell "data**S**ource".

**Comment by lhartzman** [comment]
So I found that I did have lowercase and snake case mixed in. I converted it all to snake case and made sure that the config classes were looking for that as well. I tried both `reader.dataSource.read-only` and `reader.dataSource.readOnly`. The log file shows:
`DEBUG com.zaxxer.hikari.HikariConfig - readOnly........................false`

So no change at all.

**Comment by brettwooldridge** [comment]
readOnly is a first order property, and should not be qualified with ``dataSource.``.
