### ISSUE TITLE
Ability to route connections to read only servers

### ISSUE THREAD

**Issue by davecramer** [brettwooldridge/HikariCP#1203]
This is more of a enquiry than an issue.

Does HikariCP have this facility ?
Would this be of any use ?

Currently in PostgreSQL you can mark a transaction read only but that is a very limited use case.

I am contemplating a startup message which would indicate that I want a read or write  connection.

Mostly curious if you could utilize this.

**Comment by billoneil** [comment]
You would probably want to create more than one HikariCP pool and route them according to your own logic.

The same recommendation is made if your app has a mix of OLAP and OLTP queries. You can make multiple pools with different sizes / timeouts.

**Comment by davecramer** [comment]
Spring has a readonly annotation which doesn't really know which pool it is connecting to. Being able to route based on some information in the protocol is what I am contemplating to allow this to be somewhat invisible to the app.

**Comment by brettwooldridge** [comment]
I would suggest that this is a behavior best implemented at the Spring-tier.  I don’t think it belongs in the pool.
