### ISSUE TITLE
connectionTimeout not working properly

### ISSUE THREAD

**Issue by DamilyApp** [brettwooldridge/HikariCP#1205]
#### Environment
```
HikariCP version: 2.3.7
JDK version     : 1.8.0_172
Database        : SQL Server/ JTDS
Driver version  :  1.3.1
Play version: 2.4.6

-----------------------------------------------------------------------------------------
We use HikariCP with Play! 2.4.6. The application ran fine before, but throw SQLTimeoutException due to increase load. 
A request timed out after 23607ms , but the Hikari connectionTimeout is set to 10000ms.
Shouldn't the connection acquire timeout after 10000ms?  
I haven't been able to reproduce this problem locally. And ConnectionTimeout is set to HikariCP correctly I confirm.

**Play's HikariCP config**
play.db.pool=hikaricp
db.default.url=${database.jdbc.url}
db.default.driver="net.sourceforge.jtds.jdbc.Driver"
db.default.hikaricp.autocommit=true
db.default.hikaricp.maximumPoolSize=25
db.default.hikaricp.minimumIdle=10
db.default.username=${username}
db.default.password=${password}
db.default.hikaricp.connectionTimeout = 10000
db.default.hikaricp.connectionTestQuery="select 1"
db.default.hikaricp.readOnly = true
db.default.hikaricp.poolName = current
db.default.hikaricp.disableJMX = false
db.default.hikaricp.registerMbeans= true

db.central.url=${database.jdbc.url}
db.central.driver="net.sourceforge.jtds.jdbc.Driver"
db.central.hikaricp.autocommit=true
db.central.hikaricp.maximumPoolSize=15
db.central.hikaricp.minimumIdle=10
db.central.username=${username}
db.central.password=${password}
db.central.hikaricp.connectionTimeout = 10000
db.central.hikaricp.connectionTestQuery="select 1"
db.central.hikaricp.readOnly = true
db.central.hikaricp.poolName = central
db.central.hikaricp.disableJMX = false
db.central.hikaricp.registerMbeans= true


Below Log :
java.sql.SQLTimeoutException: Timeout after 23607ms of waiting for a connection.
        at com.zaxxer.hikari.pool.BaseHikariPool.getConnection(BaseHikariPool.java:227) ~[com.zaxxer.HikariCP-2.3.7.jar:na]
        at com.zaxxer.hikari.pool.BaseHikariPool.getConnection(BaseHikariPool.java:182) ~[com.zaxxer.HikariCP-2.3.7.jar:na]
        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:93) ~[com.zaxxer.HikariCP-2.3.7.jar:na]
        at play.api.db.DefaultDatabase.getConnection(Databases.scala:143) ~[com.typesafe.play.play-jdbc_2.11-2.4.6.jar:2.4.6
]

**Comment by brettwooldridge** [comment]
Typically, HikariCP has extremely accurate timeouts, +/-2ms.  However, HikariCP threads, like all Java threads, are subject to the OS scheduler.  

Under sufficient load all threads will begin to experience CPU starvation.  In the case, approximately 13ms delay.  If, as you say, this timeout occurs due to increasing load, it is hardly surprising.

Having said that, I would be remiss if I did not also mention that running the latest version of HikariCP is always recommended. v2.3.7 is very old, and many fixes and improvements have been made since.

**Comment by DamilyApp** [comment]
@brettwooldridge  Thanks for your response.  We will update the version later. 

But I have a confusion for this SQLTimeoutException. 

If delay, my understand is that timeouts should be accurate timeouts, +13ms.  But it is amazing for exception Timeout 23607ms, it is much larger than connectionTimeout config.  

Could you give me some advice for finding the cause?  Thanks.

**Comment by brettwooldridge** [comment]
@DamilyLi There can only be one cause, as far as I am concerned: over-committed CPU.

I strong suggest enabling monitoring for the pool and collecting metrics.  Additionally, also collect metrics from the application server itself.  If you graph a histogram if CPU usage, and compare it with the timestamps of timeouts in the logs, as well as the histogram of *active* connections in the pool, you will almost certainly find that the timeouts occur when the CPU usage is max'ed out at 100%.
