### ISSUE TITLE
Information on hikari spring branch

### ISSUE THREAD

**Issue by benduke** [brettwooldridge/HikariCP#1206]
#### Environment
```
HikariCP version: 2.7.6
Database        : Oracle
Driver version  : ojdbc8.jar
```
I am using the version from the spring branch and was wondering if there was some wiki info on this specific branch. What are the differences with this branch and is there any reason i might want to try the 3.x dev branch ? 

Any response is greatly appreciated. I have been searching around for a couple of days and could not locate any significant information. (Please forgive me if i missed something in my search)

**Comment by brettwooldridge** [comment]
@benduke The only difference between the Spring v2.7.9 release and v2.7.8 is the upgrade of Micrometer support from the 1.0.0.RC (release candidate) to the final v1.0.0 release.

Originally, this change was only on HikariCP v3.0.0, but it came too late in the Spring release cycle, and according to their release rules, they could not pick-up a major revision change so late.  So, the support for Micrometers v1.0.0 was cherry-picked from HikariCP v3.0.0 into a special v2.7.9 build to accomodate their release schedule.
