### ISSUE TITLE
Wiki: MBean (JMX) Monitoring and Management

### ISSUE THREAD

**Issue by mattrberry** [brettwooldridge/HikariCP#1220]
https://github.com/brettwooldridge/HikariCP/wiki/MBean-(JMX)-Monitoring-and-Management

It took me a little of time to figure out the name of the config bean (PoolConfig rather than Pool). I was trying to set a few properties programmatically, and I couldn't figure out the name until I opened up JConsole and saw it. I also don't see it anywhere else in the repo other than in the code https://github.com/brettwooldridge/HikariCP/blob/74fa2a84e8155726bcc92d36c178fe978addafb9/src/main/java/com/zaxxer/hikari/pool/PoolBase.java#L277

Maybe it should have been obvious and I just missed it. This was just my experience

**Comment by brettwooldridge** [comment]
@mattrberry I have updated the [wiki page](https://github.com/brettwooldridge/HikariCP/wiki/MBean-(JMX)-Monitoring-and-Management).

**Comment by arunbulls** [comment]
java.lang.RuntimeException: javax.management.InstanceNotFoundException: com.zaxxer.hikari:type=Pool (name)

I have received this error. How to overcome it.


  poolConfigAccessor = new ObjectName("com.zaxxer.hikari:type=PoolConfig (" + poolName + ")"); 
  poolAccessor = new ObjectName("com.zaxxer.hikari:type=Pool (" + poolName + ")"); 

Config :
        config.setDriverClassName("oracle.jdbc.driver.OracleDriver");
        config.setJdbcUrl( "jdbc:oracle:thin:@117.xxx.xxx.xx:1530:arun" );
        config.setUsername( "insr" );
        config.setPassword( "inur" );
        config.addDataSourceProperty( "cachePrepStmts" , "true" );
        config.addDataSourceProperty( "prepStmtCacheSize" , "250" );
        config.addDataSourceProperty( "prepStmtCacheSqlLimit" , "2048" );
        config.setPoolName("insurance");
        config.setRegisterMbeans(true);
        config.setAllowPoolSuspension(true);
        ds = new HikariDataSource( config );
