### ISSUE TITLE
Disable HikariCP Log

### ISSUE THREAD

**Issue by devzonetrack** [brettwooldridge/HikariCP#1221]
I have search about "Howto Disable HikariCP Debug" but i can't find solution, so i want to ask about is there are function howto disable hikariCP Debug log?

**Comment by brettwooldridge** [comment]
@devzonetrack The logging level is controlled by your logging framework (``log4j``, ``logback``, ``java.util.loggin``, etc.).  See the documentation for the logging framework about how to control logging levels.
