### ISSUE TITLE
Connection recovery problem less than minimum Idle

### ISSUE THREAD

**Issue by zaurhasanov** [brettwooldridge/HikariCP#1223]
When kill all connection from database, Hikari recover connections that less than has been configed.
For example, if I set setMinimumIdle(10) after kill all ten connection from database Hikari will create 9 connection. No more or less.

#### Environment
```
HikariCP version: 3.1.0
JDK version     : 1.8.0_111
Database        : |MySQL|... unchecked others
Driver version  : 5.1.6
```

**Comment by brettwooldridge** [comment]
@zaurhasanov I have added an [additional unit test](https://github.com/brettwooldridge/HikariCP/blob/dev/src/test/java/com/zaxxer/hikari/pool/TestConnections.java#L262) and am unable to reproduce the issue you have reported.
