### ISSUE TITLE
Desktop java applicaiton Using HikariCP with thread pooling (executor framework) that uses db connection and web service calls.

### ISSUE THREAD

**Issue by anprasad85** [brettwooldridge/HikariCP#1224]
#### Environment
```
HikariCP version: HikariCP-java6-2.3.13
JDK version     : 1.6.0_41
Database        : Oracle
Driver version  : 11g
```
I am new to connection pooling.

I have a requirement to get the attachments with a web service calls and i need to use db queries before and after the web service calls. I am interested and using HikariCP to create connection pool and executor framework for thread pooling. I am running the program with jar file. 
Below is my hikariCP config:

HikariConfig config = new HikariConfig();				
	        config.setJdbcUrl(url);
	        config.setUsername(user);
	        config.setPassword(pass); 
	        config.setMaximumPoolSize(20);	       
	        //config.setMaxLifetime(2000000);
	        config.setAutoCommit(true);
	        config.setLeakDetectionThreshold(90000);
	        config.addDataSourceProperty("cachePrepStmts", "true");
	        config.addDataSourceProperty("prepStmtCacheSize", "250");
	        config.addDataSourceProperty("prepStmtCacheSqlLimit", "2048");
	        dataSource = new HikariDataSource(config);

I'm able to establish connection with Oracle but it is immediately failing saying SQLTimeoutException: waiting for 30005s...

I observed few connection leaks.
Can i use thread pooling along with HikariCP? is this causing the issue.
Below is how i'm using the thread pooling and connection:

executor = Executors.newFixedThreadPool(10);				
				for (int i = 0; i < personList.size(); i++) {  //personList.size() can be 2000 or 3000
					Runnable contract = new PersonThread(dataSource.getConnection());					
					executor.execute(contract);					
				}
				executor.shutdown();

public static void closeCP() throws InterruptedException
	{
		dataSource.shutdown();
	}
	
	public static Connection getAConnection() throws SQLException {
		return dataSource.getConnection();
	}

When i tried above by passing getConnection in PersonThread (has db and web service calls), i'm getting the issues (SQLTimeoutException)
I have also tried as not passing the dataSource.getConnection() from MainThread, but instead i am calling getAConnection() each time when required a db query execution and closing it, but it is taking very long time to complete the execution i.e., for 100 persons it is taking approx. 1 hour (performance issue). Why is this difference in performance?

Can you please tell me whether i'm using HikariCP correctly? please advise for any changes.

**Comment by neoxpert** [comment]
May it be that you only request connections from the datasource but you never close and by doing so return them to the connection pool? This is not a problem that Hikari can solve. As with every resource "you" have to release used resources when all operations are done.

If you don't do so and call the method running the queries again and again the connection pool will dry out and no new connections can be opened (returned by the connection pool) and you will receive the mentioned exceptions.

In a first attempt I would consider some restructioring of your code to a pattern like:

- get a connection
- do something with the connection
- close the connection

**Comment by anprasad85** [comment]
Thanks for the suggestion.
Actually in first case also I am closing the connection but that is not done immediately. After several web service calls and few db calls I am closing the connection. Will not closing the connection creates SQLTimeout issue.

If I update my code to the below mentioned pattern:
- get a connection
- do something with the connection
- close the connection

The job completion is taking more time.
Just want to let know that in a single run there could be around 12000 db calls or more i.e., around 12000 times connection should be taken, use it and close it.

Will this impact the performance, runtime, heap space etc?

 Please advice on this.
