### ISSUE TITLE
When does hikaricp reconnect if connection is killed manually

### ISSUE THREAD

**Issue by yogiverma007** [brettwooldridge/HikariCP#1225]
My application is running successfully. I had to kill all the connections(idle and active). So when will hikaricp will reconnect to the connections?

#### Environment
```
HikariCP version: 2.7.2
JDK version     : 1.8.0_111
Database        :MySQL
Driver version  : 5.1.43
```
<sup>⚠️ Please verify that your issue still occurs on the latest version of HikariCP before reporting. </sup>

-----------------------------------------------------------------------------------------
*Have you searched the CLOSED issues already? How about checking [stackoverflow](https://stackoverflow.com/search?q=HikariCP)?*

**Comment by brettwooldridge** [comment]
@yogiverma007 When the connection is borrowed next from the pool, it will be checked to see if it is still alive, and evicted that that time.
