### ISSUE TITLE
[PoolBase] Failed to validate connection

### ISSUE THREAD

**Issue by BreatherLeiYu** [brettwooldridge/HikariCP#1228]
#### Environment
```
HikariCP version: 3.2.0
JDK version     : 1.8.0_181
Database        : MySQL
Driver version  : 8.0.12 5.1.44
```

-----------------------------------------------------------------------------------------
*Have you searched the CLOSED issues already? How about checking [stackoverflow](https://stackoverflow.com/search?q=HikariCP)?*
here is my hikariConfig
```xml
<bean id="hikariConfig" class="com.zaxxer.hikari.HikariConfig">
        <property name="driverClassName" value="com.mysql.jdbc.Driver"/>
        <property name="jdbcUrl" value="${jdbc.url}"/>
        <property name="username" value="${jdbc.username}"/>
        <property name="password" value="${jdbc.password}"/>
        <property name="connectionTestQuery" value="select 1"/>
        <property name="connectionTimeout" value="30000"/>
        <property name="minimumIdle" value="5"/>
        <property name="maximumPoolSize" value="20"/>
        <property name="idleTimeout" value="600000"/>
        <property name="maxLifetime" value="1800000"/>
        <property name="dataSourceProperties">
            <props>
                <prop key="cachePrepStmts">true</prop>
                <prop key="prepStmtCacheSize">250</prop>
                <prop key="prepStmtCacheSqlLimit">2048</prop>
            </props>
        </property>
    </bean>
```
but when I run my project , it always show annoying  warning msg like below:
"WARN - om.zaxxer.hikari.pool.PoolBase - HikariPool-1 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@25c11d53 (Communications link failure

The last packet successfully received from the server was 53,304 milliseconds ago.  The last packet sent successfully to the server was 53,534 milliseconds ago.). Possibly consider using a shorter maxLifetime value. "

and I've checked my mysql env config,the default maxLifetime is much shorter than wait_timeout
![image](https://user-images.githubusercontent.com/40288715/44836054-7daf0b00-ac68-11e8-8d68-c1ee97adb9e7.png)

I debugged PoolBase.isConnectionAlive 
 `statement.execute(config.getConnectionTestQuery());`
 always throw exception so that the warn log show

how could I fix this issue

**Comment by BreatherLeiYu** [comment]
It‘s our mysql proxy’s feature cause it，thx

**Comment by climbingDog** [comment]
> It‘s our mysql proxy’s feature cause it，thx

I also get this warn message in my project. I use haproxy as mysql proxy,but I don't know how to fix it.
Could you please show me how to fix it?

**Comment by JulianHang** [comment]
I also want to know how it was fixed. thanks
@BreatherLeiYu

**Comment by billoneil** [comment]
> We strongly recommend setting this value, and it should be several seconds shorter than any database or infrastructure imposed connection time limit.

This note under `maxLifetime` is likely the fix. You want the max lifetime to be shorter than any connection timeout between the connection pool (client) and the SQL host. This includes the max lifetime of the connections on the SQL server itself as well as any max connection timeouts of any proxy. If you have connections going through some form of SQL proxy or HAProxy you should track down their connection timeouts and increase them to be above `maxLifetime` or decrease `maxLifetime`.
