### ISSUE TITLE
Get multiple databases meta info

### ISSUE THREAD

**Issue by zzt93** [brettwooldridge/HikariCP#1231]
#### Environment
```
HikariCP version: 2.6.3
JDK version     : 1.8.0_111
Database        : |MySQL|
Driver version  : 5.1.43
```
When use `DriverManagerDataSource`, I can use the following code to fetch multiple databases meta info:
``` 
       ((JDBC4Connection) connection).setNullCatalogMeansCurrent(false);
```
How can I use Hikari to do the same thing (I have tried `null` & `""` but failed)?

**Comment by brettwooldridge** [comment]
Unwrap the ``Connection``, using the JDBC ``unwrap()`` API.  Like so:
```java
((ConnectionProperties) connection.unwrap(ConnectionProperties.class)). setNullCatalogMeansCurrent(false);
```
