### ISSUE TITLE
com.zaxxer.hikari.pool.PoolBase : HikariPool-1 - Failed to validate connection com.mysql.jdbc.JDBC4Connection@XXXXXXX (No operations allowed after connection closed.) 

### ISSUE THREAD

**Issue by mayurb90** [brettwooldridge/HikariCP#1241]
#### Environment
```
HikariCP version: Spring boot 2.0.3-RELEASE (Do not know about HikariCP version)
JDK version     : 1.8.0_111
Database        :  10.1.22-MariaDB
Driver version  : No Idea
```

-----------------------------------------------------------------------------------------
*Have you searched the CLOSED issues already? How about checking [stackoverflow](https://stackoverflow.com/search?q=HikariCP)?*
Yes, tried all possible solutions (Which I was able to understand) like:

https://github.com/brettwooldridge/HikariCP/issues/1034

Application.property file:

spring.jpa.hibernate.ddl-auto=none
logging.level.org.hibernate.SQL=debug
spring.profiles.active=prod
spring.datasource.hikari.minimumIdle=3
spring.datasource.hikari.maximumPoolSize=10
spring.datasource.hikari.maxLifetime =2000
spring.datasource.hikari.connection-test-query: SELECT 1 FROM DUAL

**Comment by brettwooldridge** [comment]
Is “SELECT 1 FROM DUAL” even valid for MariaDB?  I don’t think so.
