### ISSUE TITLE
Get connection method taking approx. 300 ms

### ISSUE THREAD

**Issue by deepakarora3** [brettwooldridge/HikariCP#1243]
HikariCP version: 3.1.0
JDK version     : 1.8
Database        : Oracle
Driver version  : ojdbc8.jar (12.2.0.1)

Hi Brett,

We want to use the HikariCP connection pool in one of our applications but we are seeing a bit of a strange behavior. Below is the code. Nothing fancy, just a small driver program in Java to test the performance. Please note the following:

1. For testing purpose, the max pool size is set to 1
2. The first time a connection is requested, it will take whatever time is required to connect (as expected)
3. Then when we again request a connection, we get it in 1 to 2 ms (again as expected)
4. But then, when we sleep for 10 seconds and then request the connection, it takes approx. 300 ms (not expected)
5. The taking of 300 ms happens each time when we sleep for some time

Is there something wrong that I am doing?

Thanks much in advance for your help.

package hikaricp;
import com.zaxxer.hikari.HikariDataSource;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
public static void main(String[] args) throws SQLException, InterruptedException {
    DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
    HikariDataSource ds = new HikariDataSource();
    ds.setJdbcUrl("jdbcurl");
    ds.setUsername("username");
    ds.setPassword("password");
    ds.setAutoCommit(false);
    ds.setMaximumPoolSize(1);

    // this is the first time a connection is requested and hence will take some time
    Connection cnn = ds.getConnection();
    cnn.close();

    // second time
    long now = System.currentTimeMillis();
    cnn = ds.getConnection();
    System.out.println("Successfully got connection");
    cnn.close();
    System.out.println("Successfully released connection. Time taken = " + (System.currentTimeMillis() - now));

    Thread.sleep(10000);

    // third time after sleeping for some time
    now = System.currentTimeMillis();
    cnn = ds.getConnection();
    System.out.println("Successfully got connection");
    cnn.close();
    System.out.println("Successfully released connection. Time taken = " + (System.currentTimeMillis() - now));
  }
}

This is the output I am seeing:

Sep 27, 2018 11:45:27 AM com.zaxxer.hikari.HikariDataSource getConnection
INFO: HikariPool-1 - Starting...
Sep 27, 2018 11:45:32 AM com.zaxxer.hikari.HikariDataSource getConnection
INFO: HikariPool-1 - Start completed.
Successfully got connection
Successfully released connection. Time taken = 2
Successfully got connection
Successfully released connection. Time taken = 292

**Comment by nunnrlc** [comment]
That sounds normal. HikariCP is likely spending the 300ms performing connection validation, i.e. a call to the database, before handing out the connection. The connection has been idle 10s and should be revalidated.

Conversely, there is an optimisation in place that the connection validation is skipped when a connection is borrowed just a few ms after being returned, as long as it was returned in working order. The database calls made on connection return are as good as a validation anyhow. That is why keeping the pool busy sees borrow times reduce to 2ms.

**Comment by deepakarora3** [comment]
Thanks for the quick response. Just a quick followup question. Is there a way to turn off this validation? Thanks

**Comment by deepakarora3** [comment]
Solved! The code looks for a value in the system property and defaults to 500 ms in case it is not present. Hence when we sleep for more than 500 ms and request a connection, Hikari will attempt to validate the connection. If I wanted that the validation be deferred to a minute, just add the following lines during initialization. Now it works the way I want it to. It would be great if it were documented.

    Properties props = System.getProperties();
    props.setProperty("com.zaxxer.hikari.aliveBypassWindowMs", "60000");

**Comment by brettwooldridge** [comment]
Just a comment that this system property is both undocumented and unsupported.  I cannot recommend any values longer than a few seconds, otherwise you risk getting invalid connections from the pool.
