### ISSUE TITLE
marked as broken because of SQLSTATE(08S01), ErrorCode(0)

### ISSUE THREAD

**Issue by Zhangjk2012** [brettwooldridge/HikariCP#1246]
#### Environment
```
HikariCP version: 3.2.0
JDK version     : 1.8.0_181-b13
Database        : MySQL
Driver version  : 5.1.46
```
com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure
The last packet successfully received from the server was 13,529 milliseconds ago.  The last packet sent successfully to the server was 13,529 milliseconds ago.

I have been inserting data into the database, this error has occurred in the middle.

`      HikariConfig cfg = new HikariConfig();
        cfg.setAutoCommit(false);
        cfg.setConnectionTimeout(2000);
        cfg.setJdbcUrl(config.getUrl());
        cfg.setDriverClassName("com.mysql.jdbc.Driver");
        cfg.setUsername(config.getUser());
        cfg.setPassword(config.getPassword());
        cfg.setMaximumPoolSize(config.getPoolSize());
        cfg.setPoolName(config.getPoolName());
        cfg.addDataSourceProperty("characterEncoding", "utf8");
        cfg.addDataSourceProperty("useUnicode", true);
        cfg.addDataSourceProperty("cachePrepStmts", true);
        cfg.addDataSourceProperty("prepStmtCacheSize", 250);
        cfg.addDataSourceProperty("useServerPrepStmts", true);
`
do i need to set the `idleTimeout` and `minimumIdle` properties?

**Comment by brettwooldridge** [comment]
maxLifetime is more important. Try setting it to half ita current value (from 30min to 15min).  minimumIdle and IdleTimeout should not matter.  You want to try to ensure that HikariCP kills connections before the DB does.

**Comment by Zhangjk2012** [comment]
OK.  ths.

**Comment by jparakut** [comment]
was this resolved?
