### ISSUE TITLE
Postgresql datasource needs datasource propertis in fixed order

### ISSUE THREAD

**Issue by rainoko** [brettwooldridge/HikariCP#1254]
#### Environment
```
HikariCP version: 3.2.0
JDK version     : 1.8.0_111
Database        : PostgreSQL
Driver version  : 42.2.5
```

if datasource properties are applied before url and url doesn't specify these properties, property is set back to default value.

HikariCP should use ordered Properties, otherwise its not possible to use, because java.util.Properties is using the HashTable implementation the order is not guaranteed and library user cant force properties order. Only workaround is to use properties in url string which is not preferred way to configure datasource - too error prone

Relevant code from Postgresql driver BaseDataSource.java
```
public void setUrl(String url) {

    Properties p = org.postgresql.Driver.parseURL(url, null);

    for (PGProperty property : PGProperty.values()) {
      setProperty(property, property.get(p));
    }
  }
```

Relevant code from configuration of HikariCP
```
HikariConfig config = new HikariConfig();
    config.setDataSourceClassName(env.getProperty("spring.datasource.dataSourceClassName"));
    config.addDataSourceProperty("autosave", AutoSave.CONSERVATIVE);
    config.addDataSourceProperty("user", env.getProperty("spring.datasource.username"));
    config.addDataSourceProperty("password", env.getProperty("spring.datasource.password"));
    config.addDataSourceProperty("url", env.getProperty(DATABASE_URL_KEY));
```

**Comment by rainoko** [comment]
This might be postresql driver bug.
even thought that url doesnät have property, pgjdbc driver overwrites previous property value with default value.

**Comment by rainoko** [comment]
I reported issue to pgjdbc project about this. https://github.com/pgjdbc/pgjdbc/issues/1308

**Comment by brettwooldridge** [comment]
I concur that this is a PostgreSQL driver bug.
