### ISSUE TITLE
Unable to instantiate H2 with Hikari CP

### ISSUE THREAD

**Issue by Ramanpreetsingh** [brettwooldridge/HikariCP#1255]
I am trying to setup H2 as in memory database for my test environment with spring boot. I have configured the 
```
spring.datasource.url=jdbc:h2:mem:test
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.platform=postgres
```
 
But I am getting this error:
`Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.sql.DataSource]: Factory method 'dataSource' threw exception; nested exception is java.lang.RuntimeException: Driver org.postgresql.Driver claims to not accept jdbcUrl, jdbc:h2:mem:test`

I am using Hikari version 3.2.0.

**Comment by brettwooldridge** [comment]
This is a spring configuration issue.  It is trying to use the PostgreSQL driver. Ask on stackoverflow or the spring forums.
