### ISSUE TITLE
Is the HikariProxyConnection object thread-safe?

### ISSUE THREAD

**Issue by markkolich** [brettwooldridge/HikariCP#1269]
#### Environment
```
HikariCP version: 3.2.0
JDK version     : OpenJDK 11.0.1+13
Database        : MySQL
Driver version  : 8.0.12
```

I'd like to:

1. start a transaction on a connection (`connection.setAutoCommit(false)`)
2. execute several statements, _each on its own thread_, reusing the same `java.sql.Connection`
3. commit the transaction (`connection.commit()`)

Can I do that with `HikariProxyConnection` and rely on such an operation to be thread-safe?

I have several DAOs that run queries asynchronously, and I'm curious if it's safe to pass a single `java.sql.Connection` to each DAO, or should I force async operations (each thread) to pull a fresh connection from my pool.

There's lots of documentation floating around that states vanilla JDBC connections are not thread-safe, while other sources state "it depends on the driver you're using".  How does HikariCP handle this internally?

**Comment by johnou** [comment]
> execute several statements, each on its own thread

Why? What are you trying to achieve?

**Comment by markkolich** [comment]
> Why? What are you trying to achieve?

I have a set of N-independent queries I'd like to run in a batch &mdash; a bunch of `SELECT`'s mostly. 
 Instead of running them serially in a transaction, I am considering parallelizing this operation for performance reasons.  That is, run these N-queries from a thread pool, one query per thread:

- Run N-queries in a thread pool, one query per thread
- Wait for each query to complete, via a `CompletableFuture<T>`
- Stitch the results together

Can I pass a single `java.sql.Connection` instance from Hikari to each thread?  Or, should I pull a fresh connection from my Hikari pool for each thread?

I assumed, perhaps incorrectly, that it'll be faster to pull a single `java.sql.Connection` instance and pass that to multiple threads as part of a "transaction" but I'm not sure if that's thread safe.  It seemed logical that if these queries are part of the same operation, pull a single `java.sql.Connection` from Hikari and use it in each thread.

((I also assumed it'll be generally faster to run these queries in parallel, instead of serially &mdash; I haven't actually measured yet if parallelizing this operation is beneficial.  Before I went down that rabbit hole I wanted to see if it's even possible.))

**Comment by johnou** [comment]
Better not to use the term transaction because it just adds confusion. A transaction is a set of database _manipulation_ operations, which are performed as if they were a single work unit.

The JDBC spec states that "We require that all operations on all the java.sql objects be multi-thread safe and able to cope correctly with having several threads simultaneously calling the same object.
" [1].

While you may be able to share a connection between multiple threads like you are suggesting I wouldn't recommend it, as you are stitching the results together this gives me the impression that we can simplify your application code and leverage the DB to do the work instead (using UNIONS).

[1] http://web.archive.org/web/20130619235736/https://docs.oracle.com/javase/1.3/docs/guide/jdbc/spec/jdbc-spec.frame9.html

**Comment by markkolich** [comment]
> Better not to use the term transaction because it just adds confusion. A transaction is a set of database _manipulation_ operations, which are performed as if they were a single work unit.

Noted.

I'm effectively using the term transaction here to describe a set of queries (that just so happen to be `SELECT`'s) which run between a `connection.setAutoCommit(false)` and a `connection.setAutoCommit(true)`:

```java
connection.setAutoCommit(false);
// SELECT #1
// SELECT #2
// SELECT #3
// SELECT #4
connection.commit();
connection.setAutoCommit(true);
```

> The JDBC spec states that "We require that all operations on all the java.sql objects be multi-thread safe and able to cope correctly with having several threads simultaneously calling the same object."

👍 

> as you are stitching the results together this gives me the impression that we can simplify your application code and leverage the DB to do the work instead (using UNIONS).

Fair point &mdash; that might be a possibility, I'll investigate that approach.

Thanks!

**Comment by johnou** [comment]
I think it's also worth noting that running selects in a transaction is essentially a noop / pointless unless you are updating rows too.

**Comment by markkolich** [comment]
> running selects in a transaction is essentially a noop / pointless unless you are updating rows too.

Yes, of course.

But, I thought Hikari suggests it's more performant to pull a single connection from the pool and use that connection across a set of related queries, as opposed to pulling one connection per query?

That said, I'm pulling one connection from my pool and using it across a set of `SELECT` statements &mdash; the fact that these queries happen to be wrapped between a `setAutoCommit(false)` and a `setAutoCommit(true)` is a detail that's controlled by the toolkit I'm using to interact with the database.  The toolkit doesn't know that I'm running a bunch of `SELECT`'s, I could very well be running a `SELECT` followed by an `UPDATE` and so on.

**Comment by johnou** [comment]
Depends on the application, and how work is processed. I generally keep a connection out of the pool no longer than needed (for a transaction then release it) while trying to cut down on large amounts of selects using simple data structures / joins / unions.

If you are talking about Spring wrt autocommit that can be avoided but in most cases you won't benefit from the optimization, happy to go into more details if you are interested.

I don't see any immediate threats, but I would still be interested in hearing @brettwooldridge 's thoughts.

**Comment by markkolich** [comment]
@johnou @brettwooldridge I definitely agree it depends on the application and use-case.

Unrelated to the original thread safety question, I was curious about the performance of using a single connection across multiple `SELECT`'s vs. pulling a new connection from the pool for each `SELECT`.

I put together a quick and dirty test that, I think, empirically shows what we already knew: don't keep a connection out of the pool for longer than needed, but in some cases, **if you know you have a "transaction" that consists of only read-only operations it may be beneficial to reuse a single connection for all queries in that transaction**.

Fair statement?

Whether or not the `Connection` is safely reused across multiple threads is an implementation detail.

Some very rough numbers...

- Pulling a **new connection** for each `SELECT` across 10,000 `SELECT`'s:

```
[ONE CONNECTION PER QUERY] 10000 SELECT's took 00:00:07.876
[ONE CONNECTION PER QUERY] 10000 SELECT's took 00:00:05.846
[ONE CONNECTION PER QUERY] 10000 SELECT's took 00:00:05.788
[ONE CONNECTION PER QUERY] 10000 SELECT's took 00:00:05.756
[ONE CONNECTION PER QUERY] 10000 SELECT's took 00:00:05.758
[ONE CONNECTION PER QUERY] 10000 SELECT's took 00:00:05.761
[ONE CONNECTION PER QUERY] 10000 SELECT's took 00:00:05.696
[ONE CONNECTION PER QUERY] 10000 SELECT's took 00:00:05.745
[ONE CONNECTION PER QUERY] 10000 SELECT's took 00:00:05.739
[ONE CONNECTION PER QUERY] 10000 SELECT's took 00:00:05.668
[ONE CONNECTION PER QUERY] 10000 SELECT's took 00:00:05.656
[ONE CONNECTION PER QUERY] 10000 SELECT's took 00:00:05.957
[ONE CONNECTION PER QUERY] 10000 SELECT's took 00:00:05.725
[ONE CONNECTION PER QUERY] 10000 SELECT's took 00:00:05.699
[ONE CONNECTION PER QUERY] 10000 SELECT's took 00:00:05.683
[ONE CONNECTION PER QUERY] 10000 SELECT's took 00:00:05.822
[ONE CONNECTION PER QUERY] 10000 SELECT's took 00:00:05.819
[ONE CONNECTION PER QUERY] 10000 SELECT's took 00:00:05.889
[ONE CONNECTION PER QUERY] 10000 SELECT's took 00:00:05.801
[ONE CONNECTION PER QUERY] 10000 SELECT's took 00:00:05.897
```

- Reusing a **single connection** across 10,000 `SELECT`'s:

```
[SINGLE CONNECTION] 10000 SELECT's took 00:00:05.511
[SINGLE CONNECTION] 10000 SELECT's took 00:00:02.702
[SINGLE CONNECTION] 10000 SELECT's took 00:00:02.512
[SINGLE CONNECTION] 10000 SELECT's took 00:00:02.519
[SINGLE CONNECTION] 10000 SELECT's took 00:00:03.011
[SINGLE CONNECTION] 10000 SELECT's took 00:00:02.558
[SINGLE CONNECTION] 10000 SELECT's took 00:00:02.555
[SINGLE CONNECTION] 10000 SELECT's took 00:00:02.854
[SINGLE CONNECTION] 10000 SELECT's took 00:00:02.529
[SINGLE CONNECTION] 10000 SELECT's took 00:00:02.728
[SINGLE CONNECTION] 10000 SELECT's took 00:00:02.811
[SINGLE CONNECTION] 10000 SELECT's took 00:00:02.579
[SINGLE CONNECTION] 10000 SELECT's took 00:00:02.488
[SINGLE CONNECTION] 10000 SELECT's took 00:00:02.549
[SINGLE CONNECTION] 10000 SELECT's took 00:00:02.576
[SINGLE CONNECTION] 10000 SELECT's took 00:00:02.648
[SINGLE CONNECTION] 10000 SELECT's took 00:00:02.903
[SINGLE CONNECTION] 10000 SELECT's took 00:00:03.029
[SINGLE CONNECTION] 10000 SELECT's took 00:00:02.860
[SINGLE CONNECTION] 10000 SELECT's took 00:00:02.836
```

As shown, on average, reusing a single connection cut the total time by more than half.

Of course, in the "real world" you're not going to use a single connection across 10,000 queries &mdash; I just picked that number of iterations to make the data points I measured more tangible.

I'm satisfied with the information gathered in this thread, thanks for the help!  No further discussion is needed, unless you'd like to chat further about these results.  If not, feel free to close this out.
