### ISSUE TITLE
Statement parameter 1 not set.

### ISSUE THREAD

**Issue by github-ganyu** [brettwooldridge/HikariCP#1270]
#### Environment
```
HikariCP version: 2.4.13
JDK version     : 1.7.0_79
Database        : MySQL
Driver version  : 5.1.38
```
I don not know what is wrong , this problem occasionally arises in the production environment.

![06c8a3de-9be8-4a48-a9f8-cbd3626c157b](https://user-images.githubusercontent.com/25056767/47703107-17d80300-dc5a-11e8-8513-29ad7a2194e7.png)

**Comment by brettwooldridge** [comment]
Unfortunately, nothing to do with HikariCP.  If you remove the pool, or swap in another pool, you will get the same error eventually.
