### ISSUE TITLE
Connection not closed after MaxLifeTime

### ISSUE THREAD

**Issue by mthirani** [brettwooldridge/HikariCP#1278]
#### Environment
```
HikariCP version: 2.7.5
JDK version     : 1.8.0_91
Database        : Oracle|MySQL|
Driver version  : any driver
```
-----------------------------------------------------------------------------------------
When I set the maxLifeTime in hikari connection pool to 30minutes and my idle timeout is 5minutes. I closed all connections calling close() but while monitoring the sessions in Oracle (for example), I can see the connection is still INACTIVE.
Do we need to set the idle timeout < max Life Time?

**Comment by mthirani** [comment]
@brettwooldridge  I would like to know if the idleTimeOut closes the connection after the value given then what is the actual use of maxLifeTime. Document is not clear. 
Suppose the idleTimeOut of connection is 5minutes and maxLifeTime is 30mins and the connection is idle for 5 mins then it will be closed based on idleTimeOut (where does the maxLifeTime comes into picture here?)

**Comment by ramakrishna90** [comment]
If what I understand is correct, idleTimeout applies only when the number of connections in the pool are more than the minimum idle. So idleTimeout is used to remove those extra connections from the pool which are in excess above minimumIdle connections. And maxLifeTime is the time after which any idle connection will be removed from the pool. So it would be illogical to set maxLifeTime less than idleTimeout

**Comment by brettwooldridge** [comment]
@ramakrishna90 is very close.  Maybe I need to improve the documentation, though I tried very hard to be precise in the language used.

As @ramakrishna90 said, the ``idleTimeout`` will retire connections *that have not been used* for the entire ``idleTimeout`` period -- *as long as* retiring that connection would not decrease the pool below the ``minimumIdle`` level.

The ``maxLifetime`` is the total (maximum) time that a connection is allowed to stay in the pool.  When the ``maxLifetime`` is reached, if the connection is not in use then it will be closed *immediately*.  But if the connection *is* in use when its ``maxLifetime`` is reached, then it will be *marked* for retirement, and retired *immediately when it returns to the pool*.

Simple as that.

**Comment by brettwooldridge** [comment]
@mthirani If you want to monitor pool activity, you can enable DEBUG level logging for the ``com.zaxxer.hikari`` package -- it is not too noisey.

**Comment by mthirani** [comment]
@ramakrishna90 @brettwooldridge The thing is I saw some very weird behavior, 

Case 1: 
Hikari Settings: I put Idle timeout = 0 and Max life time = 9mins

I ran a query for 12mins in Oracle and then I closed all my connections after that using connections.close(). I was running the jconsole to monitor the pool activity and it seems that connections stayed in Idle Connection tab forever (never came to 0) unless I start my node and TotalConnection = 1 (never came to 0)
![idleconnection](https://user-images.githubusercontent.com/13495519/48858638-c3afd280-ed70-11e8-8d5e-3a17ea67a4fd.JPG)


Case 2:
Hikari Settings: I put Idle timeout = 0 and Max life time = 15mins

I ran the same query again and then I closed all my connections after that using connections.close().
Both Idle Connection tab and Total Connections shows 0 after 1 minute which seems fine.
<img width="452" alt="screen shot 2018-11-21 at 9 36 00 am" src="https://user-images.githubusercontent.com/13495519/48858707-e7731880-ed70-11e8-9a94-ff94d0895ccc.png">


But for Case1: even the connections are closed and it stayed in Idle but it never closed (though as you said, connection should be evicted when that connection is retired and returned to pool since Max life time of the connection is reached?).
Any reason for this behavior?

**Comment by maichitho** [comment]
In my case, the bug is not HikariCP bug. The reason is Hibernate config.
1. I removed hikaricp and use DriverManagerDataSource. Connections did not release after using.
2. So i add this to hibernate config:
**properties.put("hibernate.connection.release_mode", "after_transaction");**
And Connections released after using.
3. Back to use HikariCP and everything is ok.

So my results:
1. Hibernate do not release connection to the pool, so pool don't close connection to the database.

2. Default release_mode of hibernate is auto. I think there are some bugs in this mode. Otherwise, in my development environment. No need to config release_mode, connections automatic close after MaxLifeTime. But in production environment. I have to add release_mode = after_transaction.

3. Set release_mode of hibernate = **after_transaction** => After transaction, Hibernate will release connection to the pool, and after MaxLifeTime, pool will close connection to the database.

**Comment by brettwooldridge** [comment]
Thanks for the update, maybe this will help future users.

**Comment by fireroundgithub** [comment]
Why close the connection when it reached the "maxLifeTime", if HikariCP do not do that, what will happen?

**Comment by codeBeforeBC** [comment]
> Why close the connection when it reached the "maxLifeTime", if HikariCP do not do that, what will happen?

Database session is a scarce resource, do not keep it for long time if you are done using it. If HikariCP does not close a connection, the database session used by the connection will not be closed either. For a database, when the time that a session has been occupied by an account reaches a predefined limitation, an alert will be sent to the DBA and the account may be banned.
