### ISSUE TITLE
Where are the release notes ?

### ISSUE THREAD

**Issue by liujiawei9** [brettwooldridge/HikariCP#1284]
I can not find them anywhere , neither the website  http://brettwooldridge.github.io/HikariCP/  nor github here

**Comment by shakuzen** [comment]
You can check the changelog available at https://github.com/brettwooldridge/HikariCP/blob/dev/CHANGES

**Comment by liujiawei9** [comment]
> You can check the changelog available at https://github.com/brettwooldridge/HikariCP/blob/dev/CHANGES

How should I choose the version of HikariCP ? 
Is the latest version a good and safe choice to use in a production environment ?
Normally , we will choose the latest GA version , but the CHANGES does not tell the version is GA or not.

**Comment by brettwooldridge** [comment]
All released versions are considered GA, so we *always* recommend running the latest version supported by your JVM.

**Comment by liujiawei9** [comment]
> All released versions are considered GA, so we _always_ recommend running the latest version supported by your JVM.

I see, thanks a lot.
