### ISSUE TITLE
Timed out connections are not closed

### ISSUE THREAD

**Issue by tiwarivikash** [brettwooldridge/HikariCP#1286]
#### Environment
```
HikariCP version: 3.1.0
JDK version     : 1.8.0_171
Database        : PostgreSQL
Driver version  : 42.2.5
```

My goal is to make sure that API calls fail in 10 seconds when database is not available. API operation makes one read call to Postgres RDS instance. Here is the Hikari Config - 

```
HikariConfig hikariConfig = new HikariConfig();
hikariConfig.setJdbcUrl("*******");
hikariConfig.setUsername("******");
hikariConfig.setPassword("********");
hikariConfig.setDriverClassName("org.postgresql.Driver");
hikariConfig.setMaximumPoolSize(10);
hikariConfig.setConnectionTimeout(10000);
```

I restarted the database instance in the middle of performance testing and API calls started to fail after 10 seconds which was as expected. Problem was that timed out connections were returned to the pool and many calls failed after database was available after reboot. It was a force failover so different RDS instance (different IP) was master after reboot.

```
HikariPool-1 - Timeout failure stats (total=10, active=10, idle=0, waiting=189)
HikariPool-1 - Connection is not available, request timed out after 10000ms.
```

Java Exception - 

`org.springframework.transaction.CannotCreateTransactionException: Could not open JPA EntityManager for transaction; nested exception is org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection`

I am using spring-data-jpa-1.11.4.RELEASE and repository interface - 

```
@Transactional(readOnly = true)
public interface XXRepository extends JpaRepository<SomeEntity, String> {
    SomeEntity findById(String id);
}
```

Is there a way to close the connections from the pool after they time out and create new connection objects?

<sup>⚠️ Please verify that your issue still occurs on the latest version of HikariCP before reporting. </sup>

-----------------------------------------------------------------------------------------
*Have you searched the CLOSED issues already? How about checking [stackoverflow](https://stackoverflow.com/search?q=HikariCP)?*

**Comment by tiwarivikash** [comment]
HikariPool-1 - Timeout failure stats (total=10, active=10, idle=0, waiting=189)

@brettwooldridge active connection count remained 10 while database was down and getConnection call was throwing timeout exception.

**Comment by brettwooldridge** [comment]
@tiwarivikash The log shows that all connections were out of the pool, ie. ``total=10, active=10, idle=0``.  HikariCP is in no way involved with the Connection while it is out of the pool.

What you encountered is due to unacknowledged TCP packets.  The only solution is to set a driver-level socket timeout.  Search for ``socketTimeout`` on [this page](https://jdbc.postgresql.org/documentation/94/connect.html).  I recommend that it be set to 2x your longest running transaction time, or 30 seconds -- whichever is longer.

**Comment by tiwarivikash** [comment]
@brettwooldridge Thanks. I have tried setting socketTimeout as connectionProperties with Apache DBCP in past and it had worked. 

Do you think it would be a good idea to set driver level socketTimeout same as Hikari's ConnectionTimeout property or to some sane value by default? I assumed that Hikari could handle unacknowledged TCP based on this wiki - https://github.com/brettwooldridge/HikariCP/wiki/Bad-Behavior:-Handling-Database-Down

I will try following - 
hikariConfig.addDataSourceProperty("socketTimeout", "5");

**Comment by tiwarivikash** [comment]
@brettwooldridge I tried following configuration and it worked. 

```
hikariConfig.setConnectionTimeout(TimeUnit.SECONDS.toMillis(5));
 // Add Postgres Driver level properties in seconds
hikariConfig.addDataSourceProperty("socketTimeout", 5);
hikariConfig.addDataSourceProperty("connectTimeout", 5);
```

**Comment by brettwooldridge** [comment]
@tiwarivikash I always recommend using datasource properties for readability.  Long JDBC URLs with lots of options are difficult to manage and understand.
