### ISSUE TITLE
HikariCP getConnection blocks when establishing new connection

### ISSUE THREAD

**Issue by mversic** [brettwooldridge/HikariCP#1287]
#### Environment
```
HikariCP version: 3.2.0
JDK version     : 1.8.0_191
Database        : any
Driver version  : x.x.x
```
I am creating an ETL application where I actually need a large number of concurrent connections running **long slow** queries. It is not uncommon to see the number of concurrent connections to be as large as 100 depending on the machine running the application. The application has a spike demand on startup and continues to use all the connections until it shuts down, but reacting to a spike demand is **very slow** when there are no idle connections in the pool.

Let's assume it takes about 2s to establish a connection with the database. If I don't use pooling and parallelize connection retrieval with 100 threads then all connection are still established in about 2s. However, while using HikariCP I've noticed that time to establish 100 connections at the start of the application when there is a spike in connection requests, it takes about 2*100=200s to establish all connections and results in timeout.

This drives me to the conclusion that obtaining a new connection is a heavily **blocking call**. Also it seems that hikariCP pool is **lazy initialized** and I assume that once it establishes all 100 connections it will try to keep the pool size at 100.

Is there a way to enable more concurrent establishing of new connections in hikariCP? Could I at least force the pool to concurrently initialize (establish 100 connections)?

One could say that the time to initially establish all connections is irelevant in the lifetime of the application, but I would also want to have timeout set to 30seconds which will always result in timeout exception during initial spike demand.

**Comment by brettwooldridge** [comment]
@mversic HikariCP establishes connections sequentially, which is the source of the slowdown in this use-case.

I have several questions...

1/ Does each thread acquire a connection and hold it for the duration of processing?  Or does it acquire and release the connection between "major" (heavy) queries?  Releasing more frequently, even between queries, can increase throughput dramatically, compared to acquire and hold.  In fact, if using an "acquire and hold" model, I doubt that a connection pool is contributing much of anything in terms of performance.

2/ Why does each connection take 2 seconds to establish?  I am used to MySQL and PostgreSQL instances that I work with having connection establishment times measures in low millisecond times.

3/ One hundred concurrent connections does not make a lot of sense to me, unless your server has ~50 CPU cores (excluding Hyperthreading).  Having a number of active running queries that exceeds the number of physical CPU cores by more than 2x is likely to run slower -- possibly *much* slower -- than a pool size that is tuned properly to what the hardware can support.

**Comment by mversic** [comment]
Hi @brettwooldridge 

1. yes it releases connection between major heavy queries. Each query after it finishes returns connection to the pool as I've realized it yields better performance. Queries usually take about 10-30s

2. I wouldn't know. I've noticed that for Oracle it takes 1.7s to get a connection. Yes, for MySQL and PostgreSQL obtaining a connection takes few hundreds milliseconds I believe. Only when connecting to Oracle do I experience connection timeouts, if the time to establish connection was lower I think it would work fine as it does with MySQL and PostgreSQL

3. Application was tested on heavy AWS machines with 32 or more cores. Also, consider that application runs on a different machine than the databases it connects to and it does not do much processing, rather it waits a considerable amount of time on network responses from both ends (source and destination database). By measuring CPU usage it was observed that about 8*cpu_cores saturates CPU. It depends what bottleneck is based on the configuration of source database machine, machine running the application, destination database machine, network speed, etc.

I figured that HikarCP establishes connections sequentially Is that because you don't want to open excess connections? If you would offer an option to open some number of connections (like maxPoolSize or lower) concurrently during pool initialization I think it could resolve the issue. Currently, I have observed that pool is lazy initialized

**Comment by brettwooldridge** [comment]
@mversic Yes, this was exactly the solution I was considering.

*During* operation, having a single thread responsible for adding connections greatly simplifies the code, and avoids many possible race conditions.

However, HikariCP supports an "undocumented" system property ``com.zaxxer.hikari.blockUntilFilled`` (see [here](https://github.com/brettwooldridge/HikariCP/blob/dev/src/main/java/com/zaxxer/hikari/pool/HikariPool.java#L139)) that blocks the application until the pool has reached ``minimumIdle`` size.  Currently, this behavior is still single-threaded, but because no acquisitions can occur during this time, it is possible to modify the pool filling to be multi-threaded -- only during the initialization phase.

This is the solution that I intend to pursue.

**Comment by brettwooldridge** [comment]
@mversic HikariCP v3.3.0 has been published with a parallel pool initialization change.  If the ``com.zaxxer.hikari.blockUntilFilled`` system property is set to ``true``, and ``initializationFailTimeout`` is greater than 1, the pool will be filled by multiple threads.  The number of threads is determined by ``Runtime.getRuntime().availableProcessors()``.  After initialization, the number of threads drops back down to 1 for the lifetime of the pool.

**Comment by mversic** [comment]
Thanks @brettwooldridge, you are very prompt. Will `com.zaxxer.hikari.blockUntilFilled` open `minimumIdle` connections? I suppose the answer is yes

**Comment by mversic** [comment]
@brettwooldridge also, I believe you have a bug [here](https://github.com/brettwooldridge/HikariCP/blob/dev/src/main/java/com/zaxxer/hikari/pool/HikariPool.java#L148). You need to set the core pool size before setting max pool size, as per the [ThreadPoolExecutor java doc](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ThreadPoolExecutor.html#setMaximumPoolSize-int-) because `IllegalArgumentException` is thrown when setting max pool size to a value lower then core pool size

**Comment by brettwooldridge** [comment]
Re: com.zaxxer.hikari.blockUntilFilled, yes.  Also, thanks for the bug report.  I will fix now.

**Comment by tellisnz-shift** [comment]
@brettwooldridge - are you planning on documenting `com.zaxxer.hikari.blockUntilFilled` at all? can we rely on it sticking around?
