### ISSUE TITLE
Multiple invocations of Connection.close in HikariCP

### ISSUE THREAD

**Issue by mversic** [brettwooldridge/HikariCP#1299]
Is `Connection.close` guaranteed to be a **no-op** for all but the first invocation or does HikariCP `Connection.close` break Java `Connection` API(https://docs.oracle.com/javase/7/docs/api/java/sql/Connection.html#close())?

**Comment by brettwooldridge** [comment]
@mversic Yes.

**Comment by mversic** [comment]
@brettwooldridge just to be certain I interpreted your answer correctly, you are saying that 2nd close on a connection will be a no-op in HikariCP? How do you accomplish that? 

Here is what is worrying me:
- First owner obtains connection from the pool via `HikariCP.getConnection`
- First owner closes connection. Once the connection is closed it is returned to the pool and I presume it could be handed out in the next call to getConnection from the pool.
- Second owner obtains connection from the pool via `HikariCP.getConnection`. By chance, he obtains the same physical connection as the first owner
- First owner closes the same connection again

Is second owner affected with this chain of events? Will his connection be returned to the pool without him knowing about it?

**Comment by winflex** [comment]
Second owner will not be affected with this chain of events! The second time the first owner invoke close() actually does nothing. The code of close method is quite simple:
```
public final void close() throws SQLException
   {
      // Closing statements can cause connection eviction, so this must run before the conditional below
      closeStatements();

      if (delegate != ClosedConnection.CLOSED_CONNECTION) {
         leakTask.cancel();

         try {
            if (isCommitStateDirty && !isAutoCommit) {
               delegate.rollback();
               lastAccess = currentTime();
               LOGGER.debug("{} - Executed rollback on connection {} due to dirty commit state on close().", poolEntry.getPoolName(), delegate);
            }

            if (dirtyBits != 0) {
               poolEntry.resetConnectionState(this, dirtyBits);
               lastAccess = currentTime();
            }

            delegate.clearWarnings();
         }
         catch (SQLException e) {
            // when connections are aborted, exceptions are often thrown that should not reach the application
            if (!poolEntry.isMarkedEvicted()) {
               throw checkException(e);
            }
         }
         finally {
            delegate = ClosedConnection.CLOSED_CONNECTION;
            poolEntry.recycle(lastAccess);
         }
      }
   }
```
