### ISSUE TITLE
Serverless compatibility 

### ISSUE THREAD

**Issue by feinstein** [brettwooldridge/HikariCP#1304]
I am wondering how would HikariCP behave in a Serverless environment. I am developing an application with AWS Lambda functions, but since those functions are pretty stateless, it's hard to deal with connection pooling.

Most of the issues are summarized [here](https://github.com/aws-samples/aws-lambda-manage-rds-connections), but I really don't like that solution, it's cumbersome and depends on a synchronization that can fail.

Other websites show simpler options, like [this one](https://blog.spotinst.com/2017/11/19/best-practices-serverless-connection-pooling-database/), which could be replaced by HikariCP.

In a nutshell, they tell you to create a connection on the first run and save it as a global variable, then reuse it every time the Lambda function is invoked. In case the function is never invoked again, set a small connection lifetime in the database so it won't run out of connections. 

I wonder if I could just use HikariCP with AWS Lambda, telling HikariCP to only manage 1 connection. There's always the problem of maxing out the database connections, but I can limit how many Lambda instances can be created at the same time. 

The main issue for me will be how HikariCP would behave once the Lambda function freezes background tasks after returning, and then resume them after being triggered another time. 

Do have any best practices for using HikariCP with AWS Lambda? Have this been tested before? Or is it not recommended at all?

**Comment by brettwooldridge** [comment]
Sorry, I have no experience with AWS Lambda at all.  Try asking on stackoverfow or the AWS support forums.

**Comment by feinstein** [comment]
Ok, but I don't expect them to know much about it because they won't know the inner workings of your library.

AWS Lambda basically initiates a container on a first invocation, so we can set up static variables that will live as long as the container lives. Then it calls a handler function we defined in the configurations. This handler function executes, does it magic, and returns. Upon returning any background threads created by the handler function are freezed and the whole container is freezed, until a new invocation is made. Invocations can be triggers by events like API calls or cron jobs or modifications in AWS systems. 

Once a new invocation arrives the container is already created, so this is like a hot start, it just unfreezes the container and all the background threads come back to life and the handler function is invoked once again, with the new Event data that triggered the invocation, then the whole cycle repeats itself. From time to time AWS will kill some freezed containers, which means a new invocation will be a cold start, just like the first one I described. 

This "unfreeze" behavior on a static HikariCP instance that bothers me.

**Comment by brettwooldridge** [comment]
It is difficult to see how a pool can work well in such a scenario.  The housekeeper thread cannot retire connections, and if the container is truly frozen it is possible that unacknowledged TCP can even hang connections from the DB perspective.

It seems like other Lambda users must be using databases.  The question is what are they doing to manage connections?  Maybe there is a pool implementation specifically for Lambda...

**Comment by feinstein** [comment]
For what I have seen so far there are 3 solutions that most people use:

1 - open and close a connection every time you need to query a DB. 

2 - Open a connection at the first invocation and store it as a static variable. Reuse this connection as much as possible. If the connection fails, reopen it and store it again in the same static variable. Also configure your DB to have short lived connections, this way a container that isn't invoked in a while won't lock one of the connections (since they are limited).

3 - Have a separate Lambda Function that manages the total number of DB connections and ask that function if we can proceed to connect or not. This method is one recommended by AWS and the library for it is the first link I posted. 

I don't like `1` because of performance issues, `3` I think it's too complicated and prone to errors if the orchestration fails (like an Exception aborts the function in the middle of its managing logic, leaking the connection count on its nosql DB). I was hoping to use HikariCP as `2`. I am afraid it won't work, so I might just do a small implementation of `2` where I check a connection for validity before every transaction. I am open to suggestions :)

**Comment by brettwooldridge** [comment]
You can try HikariCP with one connection.  It is likely to log a thread starvation warning when it unfreezes, but shouldn’t be a problem.   Let me know how it works.

**Comment by feinstein** [comment]
I will try it out.

Just to clarify things a bit further, AWS actually recommends `2`, with some brief words. `3` is another AWS recommendation on how to avoid maxing out the DB connections. Other strategies are to limit the number of containers a Lambda function can create.

So as far as I can see, no perfect solution for serverless DB connections yet.

**Comment by boluok** [comment]
@feinstein Where you able to find a perfect solution eventually ?

**Comment by feinstein** [comment]
Nope, I stopped using pooling and did my own code where I cache one connection and one only.

**Comment by boluok** [comment]
Could you please send a link to your implementation of that

**Comment by feinstein** [comment]
I am not comfortable with that as that code wasn't thoroughly tested yet.

**Comment by billoneil** [comment]
Handling connections in serverless is pretty complicated. AWS has their recommendations [here](https://github.com/aws-samples/aws-lambda-manage-rds-connections).

**Comment by feinstein** [comment]
Yes they are, and many of those recommendations have caveats, as I exposed in a previous comment on this thread.

Serverless architectures benefit more from nosql databases.
