### ISSUE TITLE
HikariCP does not evict (and call connection close) on Query Timeout

### ISSUE THREAD

**Issue by jbialos** [brettwooldridge/HikariCP#1308]
#### Environment
```
HikariCP version: 2.7.8
JDK version     : jdk1.8.0_45
Database        : MS SQL SERVER
Driver version  : 7.0.0.jre8
```
More configuration:
```
Auto commit: true
TransactionIsolationLevel: default (TRANSACTION_READ_COMMITTED)
Query Timeout: set in jdbc url 10 seconds
Socket Timeout: set in jdbc url 11000 ms
Max Lifetime: 600000
```

I'm moving a legacy application over to hikaricp. When a query times out and the driver throws a java.sql.SQLTimeoutException, the legacy connection pool evicts and closes the underlying MS SQL Driver connection. Upon SQLTimeoutException, HikariCP just closes the statement and does not evict.

The HikariCP behavior leaves a bunch of sleeping spids on the DB with open transactions. This is unacceptable for my specific use-case and DB configuration.

I can hack it and just call HikariDataSource.evictConnection() from my application code when the driver throws a SQLException that I deem unrecoverable. This fixes my problem. Am I missing the proper way to do this through configuration?

**Comment by brettwooldridge** [comment]
@jbialos This is a little curious to me.  Can you post your configuration?

By default, when you close the connection (presumably in a try-with-resources or finally block), any "in-flight" (uncommitted) transaction should be rolled back by HikariCP.  I also recommend upgrading to the latest HikariCP version to see if the issue still occurs.

**Comment by jbialos** [comment]
I have confirmed that cda2605 fixes the original problem in our system. Thanks!
