### ISSUE TITLE
Hikari Leaked Connection not printing stacktrace

### ISSUE THREAD

**Issue by barun-mishra** [brettwooldridge/HikariCP#1310]
#### Environment
```
HikariCP version: 2.4.13
JDK version     : 1.7.0_131
Database        : MySQL
```
In the logs I am getting the following message:

`Connection leak detection triggered for <ThreadName>, stack trace follows`

**However there is no stacktrace following this message**.

My application is tied to JDK7 so unable to try it out the latest Hikari release. Hoping someone has some advice about what I can do about it. I can see a lot of messages being logged for leaks but not getting any info about them.

**Comment by barun-mishra** [comment]
Probably an issue the loggers are setup in the application. Will update if I can figure out the necessary logging configuration.

**Comment by barun-mishra** [comment]
Just in case anyone has the same problem - please upgrade your log4j to 1.2.16 or more. The log pattern Hikari uses to log the stacktrace is not supported in the older log4j versions and hence doesn't get logged.
Hope it helps!

**Comment by NightWuYo** [comment]
I have met the same problem with newest Hikari: HikariCP-3.2.0.jar

I'm using log4j-over-slf4j-1.7.25.jar and slf4j-api-1.7.25.jar.

---- update ----
Just notice that the newest version is 3.3.0, will try that.

**Comment by barun-mishra** [comment]
Also make sure your logger layout uses **org.apache.log4j.EnhancedPatternLayout** instead of just **PatternLayout**

**Comment by NightWuYo** [comment]
@barun-mishra 
Would you please share more details about how to specific logger layout to org.apache.log4j.EnhancedPatternLayout?
log4j is not used by my application, seems it comes with spring-boot-starter-web package.
I do not have any custom configuration for it.

**Comment by barun-mishra** [comment]
I see. Well you need to create a log4j.properties in your application which would then override your default spring-boot logger file. Guide to create sample log4j.properties with enhancedPatternLayout: https://github.com/apache/logging-log4j2/blob/master/log4j-1.2-api/src/test/resources/config-1.2/log4j-console-EnhancedPatternLayout.properties

**Comment by NightWuYo** [comment]
Thanks so much.
