### ISSUE TITLE
Disconnecting all the connections after certain time of Idleness in HikariCP

### ISSUE THREAD

**Issue by ernitishkumar** [brettwooldridge/HikariCP#1312]
#### Environment
```
HikariCP version 2.7.9
JDK version     : 1.8.0_111
Database        : PostgreSQL
Driver version  : 42.2.4
```
<sup>
Occurs in latest version also
</sup>

I am using SpringBoot(2.0.4),Hibernate,Postgres and HikariCP(2.7.9)

I want a configuration in which the pooled connections by HikariCP should be released back to DB after certain amount of being Idle.

For example considering the default configuration of HikariCP in SpringBoot, the pool is initialized with 10 DB Connections.

I want that if there is inactivity for suppose 2 hours all the connections should be return back to DB.

If after 2 hours any request for connections comes, the HikariCP should reinitialize the whole pool of 10 connections and serve it.

Is this possible ? Is there any configuration setting for such requirement ?

-----------------------------------------------------------------------------------------
*Have you searched the CLOSED issues already?  Yes
How about checking [stackoverflow](https://stackoverflow.com/search?q=HikariCP)?* Yes nothing found

**Comment by nunnr** [comment]
Yes should be possible. Please read the readme on the project home page! https://github.com/brettwooldridge/HikariCP/blob/dev/README.md The settings are documented there.

The settings idleTimeout (in milliseconds) and minimumIdle (number of connections) you asked for:
  idleTimeout: 7200000
  minimumIdle: 0

I'd recommend a shorter idleTimeout than 2 hours though. Your database may be configured to kill idle connections much sooner than that. HikariCP would be wasting time holding dead connections then.

**Comment by ernitishkumar** [comment]
Ohk got it. Thanks !
