### ISSUE TITLE
About Pool Sizing

### ISSUE THREAD

**Issue by jimforcode** [brettwooldridge/HikariCP#1317]
https://github.com/brettwooldridge/HikariCP/wiki/About-Pool-Sizing
i‘ve read this article. i have a  few question.
  
very simple situation （without complicated business logic）.
i just set  higher connections ,get better performance. just not   exceed the max connections of mysql  database server.

**Comment by brettwooldridge** [comment]
@jimforcode Just follow the basic formula.  The pool size should probably be approximately roughly equal to the number of CPU cores (on the DB server) times 2 (eg. 2x).  A higher connection count will likely not increase performance, and is more likely to decrease it.
