### ISSUE TITLE
Changing schema in a multi-tenant solution?

### ISSUE THREAD

**Issue by gdubya** [brettwooldridge/HikariCP#1323]
We're trying to create an application featuring a schema-based multitenancy database. There is an application user for the DB (e.g. FOO), and multiple data schemas (e.g. BAR and BAZ). Each data schema has an identical structure.

From what i've read, the way to go about implementing such an application with Spring Boot is to create an implementation of MultiTenantConnectionProvider, and then add the logic to org.hibernate.engine.jdbc.connections.spi.MultiTenantConnectionProvider#getConnection to switch schemas as required. 
```
    @Override
    public Connection getConnection(String currentTenantIdentifier) throws SQLException {
        String tenantIdentifier = TenantContext.getCurrentTenant();
        final Connection connection = getAnyConnection();
        try (Statement statement = connection.createStatement()) {
            statement.execute("ALTER SESSION SET CURRENT_SCHEMA = " + tenantIdentifier);
        } catch (SQLException e) {
            throw new HibernateException("Problem setting schema to " + tenantIdentifier, e);
        }
        return connection;
    }
```

But this does not appear to work in our case.  Is this because the "schema" information is "sealed" in the Hikari DataSource? Or is there a different way to set the schema?

I've also posted on SO here: https://stackoverflow.com/questions/54430716/spring-boot-hibernate-oracle-schema-multitenancy

#### Environment
```
Spring Boot: 2.1.2
HikariCP version: 3.2.0
JDK version     : OpenJDK 11.0.1
Database        : Oracle12g
Driver version  : 12.2.0.1
```

**Comment by gdubya** [comment]
This may be similar to #1087 ? But in that example repo the model is using single-table tenancy (discriminator column), so no schema switching is required.

We too don't want to have to set up a separate datasource for each tenant, instead connecting through the single "application user" (FOO) and relying on Oracle grants to enforce privileges.

**Comment by brettwooldridge** [comment]
@gdubya It is unclear to me why, given the Spring implementation, this would not work.  Maybe ask on the Spring forums?  I hope someone on stackoverflow can answer as well.  [Does this help?](https://dzone.com/articles/multi-tenancy-using-jpa-spring-and-hibernate-part)

**Comment by gdubya** [comment]
Thanks for the link, @brettwooldridge. It looks pretty similar to what i'm already doing, but it lead me to revisit the TenantIdentifierResolver, and it looks like my problem is caused by the fact that I set the ThreadLocal "too late". i.e. setting it on the first line of the Controller "findAll" method. I'm don't yet understand why though. Something to do with the transaction management in Spring. Anyway, it's not HIkari's fault! )

**Comment by brettwooldridge** [comment]
@gdubya Great to hear that you found a solution.
