### ISSUE TITLE
HikariCP don't work with PGroonga extension

### ISSUE THREAD

**Issue by alxspn** [brettwooldridge/HikariCP#1333]
#### Environment
```
HikariCP version: 3.3.1
JDK version     : 1.8.0_181
Database        : PostgreSQL9.6
Driver version  : 42.2.5
```

HikariCP with installed PGroonga extension (https://pgroonga.github.io).

Query "select id from contact where (resume &@ 'test')" throw ERROR: operator does not exist: text &@ unknown.

Request with native JDBC connection works as expected.

**Comment by brettwooldridge** [comment]
This makes no sense.  HikariCP does not parse, alter, or inspect the query in any way.  Please step into the HikariCP code with a debugger to verify for yourself.
