### ISSUE TITLE
How to increase maximumPoolSize while project running?

### ISSUE THREAD

**Issue by lbysimun** [brettwooldridge/HikariCP#1342]
There is a requirement  that is to increase maximumPoolSize while project running and make it effective.  I see the druidPC provide a menthod to reset the pool size dynamicly withoud restarting the project  .   I wander if HikariCP provider the same method or other optioins ?   thanks a lot.

**Comment by PascalSchumacher** [comment]
You should be able to do this by using JMX and `HikariConfigMXBean#setMaximumPoolSize` see: https://github.com/brettwooldridge/HikariCP/blob/dev/src/main/java/com/zaxxer/hikari/HikariConfigMXBean.java#L150

**Comment by brettwooldridge** [comment]
Correct.
