### ISSUE TITLE
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder"

### ISSUE THREAD

**Issue by juman123** [brettwooldridge/HikariCP#1348]
#### Environment
```
HikariCP version: 3.3.1
JDK version     : 1.8.x
Database        : PostgreSQL
```

Hi,

I know this isn't _strictly_ Hikari's problem - it's probably just SLF4J spewing garbage from some static initializer block or something.

But after adding Hikari to my project, now I keep seeing this every time I run my application, and every time I compile it:

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

It's 2019 and the Java world is _still_ casually using these needless libraries from like 1999 as if there's no problem whatsoever?

Seriously, who wants to see that SLF4J failed to put logging inside your logging so you could log while you log? .. or whatever that means. 

Inserting text into files is a solved problem since ancient times. The JDK got a logging library in Java 1.4 or something. How about we use that instead of hauling around dozens of megabytes of several logging libraries in every single project in the world?

Surely I'm not the only sane person using Hikari? Brett could make our lives easier by switching to JDK logging.

**Comment by PascalSchumacher** [comment]
If you just want to silence the warning add the `slf4j-nop` dependency (just 6 kb).

Otherwise you can log using JDK (java.util) logging by adding the `slf4j-jdk14` dependency (just 9 kb).

Or use any other logging framework (see https://www.slf4j.org/manual.html#swapping for details).

Not everybody likes/uses JDK logging, so imho it is great that HikariCP gives users the choice.

**Comment by juman123** [comment]
Alright, thanks for the tips!

**Comment by Xeravax** [comment]
If you're using maven, add this: 

```xml        
       <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>1.7.25</version>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-core</artifactId>
            <version>1.2.3</version>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>1.2.3</version>
        </dependency>
