### ISSUE TITLE
Feature: Auto retry on lost connection

### ISSUE THREAD

**Issue by feinstein** [brettwooldridge/HikariCP#1349]
As far as I understand, HikariCP will check (although it can be disabled) if a connection is valid before removing it from the pool. This involves calling `isValid()` from the JDBC, which triggers a `SELECT 1` on the database.

The problem with this approach is that at every single time we take a connection out of the pool, there will be a round-trip delay, from the client code to the database, for the `isValid()` verification.

Is it possible to instead of verifying the connection with a dummy query BEFORE using the connection, to actually use the query our code wants run as the verification itself? So in case of failure in the query, HikariCP can check for the validity of the connection AFTER it failed and reconnect and resend the query automatically and transparently, only returning the actual Exception if it failed to retry/reconnect the query.

I understand this model is much more complicated, but it seems to be more optimized.

**Comment by chenchao** [comment]
good

**Comment by PascalSchumacher** [comment]
Quoting Brett from https://github.com/brettwooldridge/HikariCP/issues/311#issuecomment-96157673

>If a connection has been used within the last 1000ms, HikariCP will bypass the validation check automatically in getConnection().

>Having said that, with JDBC4 capable drivers, the cost of validation has largely dropped to sub-millisecond or single digit milliseconds. Wherever possible, validation queries should be avoided, allowing HikariCP to use Connection.isValid() instead.

**Comment by feinstein** [comment]
Interesting to know, thanks!
