### ISSUE TITLE
Setting transactionIsolation level in HikariCP configuration

### ISSUE THREAD

**Issue by PriyaSodexo** [brettwooldridge/HikariCP#135]
Hello,
I have the following configuration

```
<property name="idleTimeout" value = "3600000" />
<property name="maximumPoolSize" value = "10" />
<property name="connectionTestQuery" value="SELECT 1 from dual" />
<property name="maxLifetime" value="1800000" />
<property name="transactionIsolation" value="TRANSACTION_READ_COMMITTED" />
```

for which I get the exception given below:

Initialization of bean failed; nested exception is org.springframework.beans.TypeMismatchException: Failed to convert property value of type 'java.lang.String' to required type 'int' for property 'transactionIsolation'; nested exception is java.lang.NumberFormatException: For input string: "TRANSACTION_READ_COMMITTED"

so i tried this:

```
 <property name="transactionIsolation" value="2" />
```

And this still throws an exception as shown below 
Property 'transactionIsolation' threw exception; nested exception is java.lang.IllegalArgumentException: argument type mismatch

Can someone pls help. Thanks in advance, Priya

**Comment by rnjava86** [comment]
Can you please let me know  how can we setup the CallableStatement into cache.
hikariConfig.addDataSourceProperty("dataSource.cachePrepStmts", "true");
		    hikariConfig.addDataSourceProperty("dataSource.prepStmtCacheSize", "250");
		    hikariConfig.addDataSourceProperty("dataSource.prepStmtCacheSqlLimit", "2048");
		    hikariConfig.addDataSourceProperty("dataSource.useServerPrepStmts", "true");
		    
		    hikariConfig.addDataSourceProperty("dataSource.useLocalSessionState", "true");
		    hikariConfig.addDataSourceProperty("dataSource.rewriteBatchedStatements", "true");
		    hikariConfig.addDataSourceProperty("dataSource.cacheResultSetMetadata", "true");
		    hikariConfig.addDataSourceProperty("dataSource.cacheServerConfiguration", "true");
		    hikariConfig.addDataSourceProperty("dataSource.elideSetAutoCommits", "true");
		    hikariConfig.addDataSourceProperty("dataSource.maintainTimeStats", "false");
what should be the parameter to setup the Callable statement caching in config object.
