### ISSUE TITLE
Looks like Connection adder threads keeps retrying indefinitely in case of connection is not reachable due to some reasons

### ISSUE THREAD

**Issue by shani2907** [brettwooldridge/HikariCP#1351]
#### Environment
```
HikariCP version: 3.3.1
JDK version     : 1.8.0_111
Database        : Oracle 
Driver version  : OJDBC 6
```
Lets assume that, I have an Oracle connection and It was working when the Pool was created.
In the mean time, becuase of the Network connectivity, oracle host machine is not reachable.

Now, in the logs i was only able to see the indefinite HikariCP connection adder logs with failure exception.
Ideally, adder thread should stop retrying affter definite attempts and mark the pool as dead.

**Comment by brettwooldridge** [comment]
The connection attempts never stop.  The assumption is that the database connectivity will be restored eventually.  

There is no such concept as a pool being marked “bad”.  Presumably you are monitoring HikariCP and the database, and your application or monitoring system can react appropriately.
