### ISSUE TITLE
Restart connection pools when DB credentials expire

### ISSUE THREAD

**Issue by amarouni** [brettwooldridge/HikariCP#1363]
#### Environment
```
HikariCP version: 2.7.1
JDK version     : 1.8.0_171
Database        : PostgreSQL
Driver version  : 42.1.4
```

-----------------------------------------------------------------------------------------
Hi,

I'm working on an app with a particular setup where DB credentials change overtime. The username/password can change at any instant which with the current code/config causes the app to fail (expected).

My question is the following : what is the best way to manage this particular setup ? Is there any possible way to restart the connection pool with the new credentials when they get rotated without restarting the app ? Any HikariCP config to force pool restart when the connections cannot be created ?

Thanks,

**Comment by marcospereira** [comment]
Looks like what you want is to use `allowPoolSuspension` (see [the docs](https://github.com/brettwooldridge/HikariCP)) to suspend/resume the pool when the credentials change.

**Comment by brettwooldridge** [comment]
See also #1350
