### ISSUE TITLE
Thread pool is EXHAUSTED and most threads waiting on ConcurrentBag.borrow

### ISSUE THREAD

**Issue by Ryanznoco** [brettwooldridge/HikariCP#1368]
#### Environment
```
HikariCP version: 2.4.13
JDK version : 1.7.0_79
Database : MySQL 5.7
Driver version : 5.1.35
```
#### Pool configuration
```
ConnectionTimeout: 30000
IdleTimeout: 600000
MaxLifetime: 1800000
MaximumPoolSize: 500
MinimumIdle: 200
ValidationTimeout: 5000
```
We are using dubbo and configure the max threads as 500. The thread pool is EXHAUSTED error was occured sometimes, and we can see that most of threads are waiting on ConcurrentBag.borrow. Could you give me some suggestions?

My hikari debug log file:
[hikari-2019-04-30.0.log](https://github.com/brettwooldridge/HikariCP/files/3130439/hikari-2019-04-30.0.log)
My thread dump files:
[Dubbo_JStack.2019-04-30_00_02_25.log](https://github.com/brettwooldridge/HikariCP/files/3130423/Dubbo_JStack.2019-04-30_00_02_25.log)
[Dubbo_JStack.2019-04-30_00_31_15.log](https://github.com/brettwooldridge/HikariCP/files/3130424/Dubbo_JStack.2019-04-30_00_31_15.log)
[Dubbo_JStack.2019-04-30_01_53_32.log](https://github.com/brettwooldridge/HikariCP/files/3130426/Dubbo_JStack.2019-04-30_01_53_32.log)
[Dubbo_JStack.2019-04-30_10_03_04.log](https://github.com/brettwooldridge/HikariCP/files/3130427/Dubbo_JStack.2019-04-30_10_03_04.log)

**Comment by brettwooldridge** [comment]
@Ryanznoco The Java 7 codebase is no longer receiving updates.  According ot Oracle:
> Oracle ceased public availability of security fixes and upgrades for Java 7 as of April 2015

I recommend upgrading to Java 8 and the latest HikariCP release.  Additionally, a 200/500 pool is excessive.  Looking at your log, I see no such demand for connections.  Looking at your log, I recommend, at maximum, 20/100.

**Comment by Ryanznoco** [comment]
2019-04-30 10:03:04.924 -DEBUG [l-1 housekeeper] com.zaxxer.hikari.pool.HikariPool        : HikariPool-1 - Pool stats (total=221, active=219, idle=2, waiting=336)
2019-04-30 01:53:32.765 -DEBUG [l-1 housekeeper] com.zaxxer.hikari.pool.HikariPool        : HikariPool-1 - Pool stats (total=316, active=316, idle=0, waiting=184)
@brettwooldridge  There I find some demands for connections in the log. And you know the pool state log output once every 30s by default, so I think there are some connection demands does not be exported.

**Comment by Ryanznoco** [comment]
@brettwooldridge According to your suggestion, I modified the pool to 20/100, but the frequency of Thread pool EXHAUSTED is obviously higher.
![image](https://user-images.githubusercontent.com/17562936/59178298-378cbd80-8b91-11e9-8a6f-89e69a91686a.png)
