### ISSUE TITLE
HikariCP监听连接是否存活性能下降

### ISSUE THREAD

**Issue by kingyifan** [brettwooldridge/HikariCP#1370]
感谢HikariCP这么好的连接池，我遇到一个问题 没有配置connection-test-query: SELECT 1 之前 程序会有的时候报连接超时，但是配置了之后网上又说 “如果您的驱动程序支持JDBC4，“我们强烈建议您不要设置此属性” 有没有好的办法不会超时又不会影响性能呢？

**Comment by winflex** [comment]
1.如果是jdbc4，那官方建议是不配connectionTestQuery，hikaricp会用java.sql.Connection.isValid()方法来检查连接是否有效
2. 如果不是jdbc4或者你硬要配connectTestQuery，然后执行这个connectionTestQuery超时，那说明此时网络慢或者数据库本身负载高的原因，这个hikaricp也管不到。但是你可以把validationTimeout设大一点（默认是5秒），好让它”不那么快超时“，这个也治标不治本，还是要定位为什么执行select 1会超时。

**Comment by winflex** [comment]
ps:还有源码作者看不懂中文的=_=

**Comment by kingyifan** [comment]
那如果配置了connectionTestQuery 每次都要去查询连接是否有效性 HikariCP 号称java最快的连接池 会不会影响性能。

**Comment by winflex** [comment]
配了比不配要慢，但是这个影响很小，对业务tps基本造不成什么影响

**Comment by winflex** [comment]
并不是每次都检测连接的有效性的，只有在连接空闲超过500ms才会检测

**Comment by kingyifan** [comment]
那这个500ms 在哪里配置的呢？ 对于我们的业务来说停留1s我觉得也是正常的，相当于每秒都会去检测是否有效性，能不能配置的稍微时间长点。

**Comment by KingYiFan** [comment]
原来我英文不太好。。。

**Comment by winflex** [comment]
这个500ms是指当从池里面获取到一条空闲连接时，会判断该连接距上一次被使用（即归还）是否超过500ms，如果超过500ms那么hikaricp会认为该连接有可能坏掉了，因此才做一次有效性检测。这个时间可以通过-Dcom.zaxxer.hikari.aliveBypassWindowMs配，但是我不理解你为啥要更改这个值

**Comment by winflex** [comment]
你可能认为这个500ms是从两次borrow之间的间隔，不是的，是上一次return和下一次borrow之间的间隔，所以这个跟业务停留多久没关系

**Comment by brettwooldridge** [comment]
Winflex是对的。
