### ISSUE TITLE
Getting HikariProxyConnection cannot be cast to oracle.jdbc.OracleConnection

### ISSUE THREAD

**Issue by krthiks** [brettwooldridge/HikariCP#1379]
#### Environment
```
HikariCP version: 3.3.1
JDK version     : 1.8.0_212
Database        : Oracle
Driver version  : ojdbc7 12.1.0.2
```
Hi,
I am using  SpringBoot 2.0.5, spring jdbc which to connect to oracle database and take advantage of HikariCP. Need to call stored procedure using SimpleJdbcCall
@Autowired
DataSource ds; //hikari ds
SimpleJdbcCall call = new SimpleJdbcCall(ds);
call.executeObject()

throws the below exception 
java.lang.ClassCastException: HikariProxyConnection cannot be cast to oracle.jdbc.OracleConnection
at orace.sql.TypeDescriptor.setPhysicalConnectionOf(TypeDescriptor.java:845)

**Comment by brettwooldridge** [comment]
@krthiks See #1172
