### ISSUE TITLE
Switching schema in a multi-tenant solution does not work with H2

### ISSUE THREAD

**Issue by ghost** [brettwooldridge/HikariCP#1382]
#### Environment
```
HikariCP version: 3.2.0 (default with latest Spring Boot)
JDK version     : 1.8.0_212
Database        : H2
Driver version  : 1.4.199
```
<sup>⚠️ Please verify that your issue still occurs on the latest version of HikariCP before reporting. </sup>

-----------------------------------------------------------------------------------------
Very related to #1323 but unable to solve this the same way.

I have a Spring Boot 2 and Hibernate application with a tenant-per-schema set up as described in this guide: https://dzone.com/articles/spring-boot-hibernate-multitenancy-implementation

I use PostgreSQL in production and H2 for development and testing. **The issue only occurs on H2**, leading me to think this is some weird interaction between HikariCP and H2 that I don't understand.

Even though I set the tenant correctly and early before the transaction is started, all queries go to the first schema set on the connection. For example, if I create a row for tenant `t1` and then for `t2`, they are both created for `t1`.

I get the connection and set the schema as follows, in my MultiTenantConnectionProvider implementation:

```
@Override
public Connection getConnection(String tenantIdentifier) throws SQLException {
    final Connection connection = getAnyConnection();
    connection.setSchema(tenantIdentifier);
    return connection;
}
@Override
public void releaseConnection(String tenantIdentifier, Connection connection) throws SQLException {
    connection.setSchema(DEFAULT_TENANT_ID);
    releaseAnyConnection(connection);
}
```

Using my debugger I stepped into `setSchema` and see it hit HikariCP's `ProxyConnection` first, before continuing to the delegate of H2's Connection implementation. Everything leads me to believe that the schema is being set correctly on all levels.

Yet, when Hibernate persists my object, it is still written to the schema of a connection that was used previous request.

Even weirder is that when I switch to PostgreSQL, the issue does not occur. 

Could there be a specific interaction between HikariCP and H2 causing this behavior?

**Comment by brettwooldridge** [comment]
@cdekker This sounds like an H2 issue to me, you might try reporting the issue to their issue tracker.  One other thing to check, is whether H2 uses ``ThreadLocal`` variables to maintain session state, and whether, within your application, connections are obtained by the same thread that ultimately executes queries.
