### ISSUE TITLE
Does the getIdleConnections() method under HikariPoolMXBean class brings the idle connections that are still valid connections?

### ISSUE THREAD

**Issue by amitbhanot** [brettwooldridge/HikariCP#1385]
#### Environment
```
HikariCP version: 3.2.0
JDK version     : 1.8.0_102
Database        : AS400
Driver version  : jt400-jdk8 v9.8
```
I am trying to switch the datasources from a primary AS400 to a secondary AS400 in case the primary AS400 is not online. To do this I am looking at the idle connections in the pool. Idle connections are still valid connections to the DB, correct?

**Comment by brettwooldridge** [comment]
@amitbhanot The idle count available through the MXBean may include connections that are not valid.  Connections are tested upon borrow, and therefore connections "sitting" in the pool may or may not be valid.

If, however, you have an ``idleTImeout`` configured, and a ``minimumIdle`` setting that is less than ``maximumPoolSize ``, you can be reasonable sure that the connections are alive.

If you are trying to detect that the primary AS400 has gone down, I suggest looking primarily at the total pool size.  When a database fails, the pool will quickly exhaust all of the connections.  When a new connection is requested, one will be selected, then tested, and upon failing, evicted from the pool -- and the process repeated very quickly for the remaining connections in the pool.

**Comment by amitbhanot** [comment]
@brettwooldridge That is in fact what I am doing. I am querying the DB which uses an available invalid connection from the pool. Since the connection is invalid, the query fails and I switch it to the secondary AS400 datasource. Thank you for that explanation.
