### ISSUE TITLE
a large number of close_waits using ClickHouse

### ISSUE THREAD

**Issue by liushunqiu** [brettwooldridge/HikariCP#1396]
#### Environment
```
HikariCP version: 2.7.9
JDK version     : 1.8.0_211
Database        : ClickHouse
Driver version  : x.x.x
```
Hello, when I am using dual data source (mysql+clickhouse), I find a large number of close_wait links for clickhouse, but mysql doesn't have this problem
```
@Configuration
@MapperScan(basePackages = {"com.xxxxxxx.clickhouse"},
        sqlSessionFactoryRef = "clickHouseSqlSessionFactory"
)
public class ClickHouseConfig {

    //@Bean(name = "clickHouseDataSource")
    @Bean
    @ConfigurationProperties(prefix = "spring.clickhouse")
    public DataSource clickHouseDataSource() {
        final DataSource dataSource =  DataSourceBuilder.create().driverClassName("ru.yandex.clickhouse.ClickHouseDriver").build();
        return dataSource;
    }
    @Bean(name = "clickHouseSqlSessionFactory")
    public SqlSessionFactory clickHouseSqlSessionFactory(@Qualifier("clickHouseDataSource") DataSource clickHouseDataSource) throws Exception {
        final SqlSessionFactoryBean sessionFactory = new SqlSessionFactoryBean();
        sessionFactory.setDataSource(clickHouseDataSource);
        sessionFactory.setMapperLocations(new PathMatchingResourcePatternResolver()
        .getResources("classpath:mapper/sys/*.xml"));

        org.apache.ibatis.session.Configuration configuration = new org.apache.ibatis.session.Configuration();
        configuration.setMapUnderscoreToCamelCase(true);
        sessionFactory.setConfiguration(configuration);
        return sessionFactory.getObject();
    }

}
```
Thank you for reply

**Comment by liushunqiu** [comment]
Driver version:
```
<dependency>
            <groupId>ru.yandex.clickhouse</groupId>
            <artifactId>clickhouse-jdbc</artifactId>
            <version>0.1.40</version>
</dependency>
```

**Comment by brettwooldridge** [comment]
@liushunqiu Please check this link:

https://www.thegeekdiary.com/high-number-of-connections-is-close_wait-state-in-netstat-command-output/

This would indicate that ``close()`` is not being called on the TCP connection.  This also implies that the clickhouse database *is* closing its side of the connection *pro-actively*.  This is not what you want typically.  You want HikariCP to be the one that initiates closing of the connection.

I would suggest setting an "aggressive" ``maxLifetime`` value -- the default is 30 minutes.  If you can find a clickhouse setting that controls connection timeout, you should set ``maxLifetime`` to slightly shorter than that value.  If you cannot find such a setting, you can try setting ``maxLifetime`` to various low values and observing if the close_wait connections start to disappear.
