### ISSUE TITLE
Temporary LOB segment in TEMP tablespace keep increasing

### ISSUE THREAD

**Issue by pavetok** [brettwooldridge/HikariCP#1399]
#### Environment
```
HikariCP version: 2.5.1
JDK version     : 1.8.0_111
Database        : Oracle
Driver version  : 12.1.0.2
```

> ⚠️ Please verify that your issue still occurs on the latest version of HikariCP before reporting.

Unfortunately we have a transitive dependency: akka-persistence-jdbc/3.5.0 -> slick-hikaricp_2.11/3.2.3 -> HikariCP/2.5.1

> Have you searched the CLOSED issues already?

Found nothing.

> How about checking [stackoverflow](https://stackoverflow.com/search?q=HikariCP)?

Found nothing.

#### Problem

When using HikariCP we encountered a problem with Oracle TEMP tablespace - it keeps on increasing at a rapid rate without any significant pattern. TEMP tablespace only reduced after restarting our application.

That problem is well-known, an example from Oracle documentation:
```
SYMPTOMS 
 The customer has recently started using the connection pool
and then the size of TEMP tablepsace keep increasing.
When we investigated v$tempseg_usage, the segment of the type of LOB_DATA increased.
...
The analysis of the issue is as follows
A Temp LOB was created when any SQL statement (or PLSQL statement) was executed on a Session.
After that, the corresponding session is returned to the connection pool after completion of the execution of the corresponding SQL statement.
However, because the session exit has not occurred, the Temp LOB used by the session still remains and is not released.
If the session is reassigned and new SQL statements that generate Temp LOBs are executed, the existing Temp LOB is not reused and new Temp LOB segments are created and used.
The temp LOB grows as the same cycle repeats over several sessions.
In this situation, Temp LOBs used in a specific session must be freed explicitly at the application level in order for the same session to reuse it.
Event 60025 was introduced to release Temp LOB segments used by one session for use by other sessions.
However, this is only possible if both the CACHE TEMP LOB and NOCACHE TEMP LOB counts are ZERO for the Temp LOB used.
Currently, although the event 60025 is set, the corresponding space is not released because the CACHE TEMP LOB count exists.
As a result, the solution of the issue is to perform the step of releasing Temp LOB explicitly after creating Temp LOB at the application level as long as the connection pool is used.
That will cause CACHE TEMP LOB not to exist.

SOLUTION 
 If the session exit does not occur using the connection pool, the generated temp lob must be explicitly cleaned up by calling FREETEMPORARY on DBMS_LOB or OCIDurationEnd on OCI on the application of the session that created the segment.
Oracle Document "Database PL/SQL Packages and Types Reference" is described as follow
http://docs.oracle.com/cd/E11882_01/appdev.112/e40758/d_lob.htm#ARPLS66616
A temporary LOB instance can only be destroyed by using OCI or the DBMS_LOB package by using the appropriate FREETEMPORARY or OCIDurationEnd statement. 
```

Some examples of issues that we found:
1. [Oracle TEMP Tablespace keeps on increasing on Oracle 11g and 12c](https://confluence.atlassian.com/confkb/oracle-temp-tablespace-keeps-on-increasing-on-oracle-11g-and-12c-899547856.html)
2. [TEMP tablespace not cleared for sessions in Web Logic connection pool](https://www.oracle.com/webfolder/community/middleware/4186645.html)

It looks like problem is not Hikari specific, but common for connection pools. Can you give me some advice how to deal with this problem in HikariCP? Maybe some parameters to tune, common recommendations for using pool, etc.

**Comment by brettwooldridge** [comment]
@pavetok I would suggest setting a very low ``maxLifetime`` value.  The default value is ``1800000ms`` (30 minutes).  The ``maxLifetime`` property can be set as low as 30 seconds (30000ms), but you may not need to set it so low.  It all depends on the rate of temp LOB creation in your application.

Basically, at least according to the Oracle documentations, temporary storage will not be released until "session exit" has occurred.  "Session exit" will only occur when the connection is retired from the pool.  Setting a ``maxLifetime`` to, for example, one minute (60000ms) will cause connections to be retired after one minute of residence in the pool.

Of course there is some overhead related to short lifetimes, as new connections must be established.  However, connection replacements occur in the background on a separate thread, so as long as your pool is not running with all connections constantly in-use, you may not experience any delays at all in connection acquisition from the pool.
