### ISSUE TITLE
Cannot specify username and password when connecting to PostgreSQL with jdbc-url

### ISSUE THREAD

**Issue by hden** [brettwooldridge/HikariCP#1402]
This works:
- `jdbc:postgresql://127.0.0.1:5432/postgres`

These doesn't
- `jdbc:postgresql://postgres@127.0.0.1:5432/postgres`
  - type: `java.net.UnknownHostException`
  - message: `postgres@127.0.0.1`
- `jdbc:postgresql://postgres:password@127.0.0.1/postgres`
  - type: `java.sql.SQLException`
  - `No suitable driver`
- `jdbc:postgresql://postgres:password@127.0.0.1:5432/postgres`
  - type: `java.net.UnknownHostException`
  - message: `postgres:password@127.0.0.1`

#### Environment
```
HikariCP version: 3.3.1
JDK version     : 1.8.0_192
Database        : PostgreSQL
Driver version  : 42.2.6
```

Ref: https://github.com/tomekw/hikari-cp/issues/84

**Comment by nunnrlc** [comment]
Hi, the format of the JDBC URL is entirely the choice of the database driver used, not HikariCP. PostgreSQL have theirs documented here: https://jdbc.postgresql.org/documentation/head/connect.html

The format is `jdbc:postgresql://host/database?user=fred&password=secret&...`

**Comment by hden** [comment]
Got it. Thanks!
