### ISSUE TITLE
Doc - misspelling: "relavent"

### ISSUE THREAD

**Issue by kolmant** [brettwooldridge/HikariCP#1417]
Hi,

This issue is related to this section on the wiki: [https://github.com/brettwooldridge/HikariCP/wiki/Rapid-Recovery](https://github.com/brettwooldridge/HikariCP/wiki/Rapid-Recovery). 

The wiki says: "See this page for relavent information" (multiple times), but the correct word is "relevant" instead of "relavent". I know it's a dumb issue but as you probably know, there is no way to make a PR for a wiki issue.

Greetings!

**Comment by lfbayer** [comment]
Fixed! Thanks for taking the time to point it out.
