### ISSUE TITLE
it seem HikariPool don't suport presto jdbc

### ISSUE THREAD

**Issue by qinzl1** [brettwooldridge/HikariCP#1424]
```
HikariCP version: 3.2.0
JDK version     : 1.8.0_111
Database        : presto
Driver version  : 0.223
```
com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Unrecognized connection property ''
![image](https://user-images.githubusercontent.com/20242930/62678203-61bcf900-b9e3-11e9-8405-57a1d3eb7511.png)

i use streamsets UI tool(https://streamsets.com) .This tool USES HikariCP as a connection pool，it look like HikariCP Unrecognized 'presto'

**Comment by kokosing** [comment]
What was the resolution?
