### ISSUE TITLE
(minor) outdated version on website (again)

### ISSUE THREAD

**Issue by itsTyrion** [brettwooldridge/HikariCP#1435]
#### Environment
```
HikariCP version: x.x.x
JDK version     : doesn't apply
Database        :  doesn't apply
Driver version  : x.x.x
```

The maven dependency blocks on the [HikariCP site](http://brettwooldridge.github.io/HikariCP/) still have 2.x in them. 
(duplicate of #860 but I didn't want to necropost on an issue from 2017)

**Comment by brettwooldridge** [comment]
I hate that page.  Deleted. 😠
