### ISSUE TITLE
No retries for hikari 3.3.1 with postgres

### ISSUE THREAD

**Issue by KineticCookie** [brettwooldridge/HikariCP#1437]
#### Environment
```
HikariCP version: 3.3.1
JDK version     : 1.8.0_111
Database        : PostgreSQL
Driver version  : 42.2.5
```
I have the following configuration:
```
HikariPool-1 - configuration:
allowPoolSuspension.............false
autoCommit......................true
catalog.........................none
connectionInitSql...............none
connectionTestQuery.............none
connectionTimeout...............30000
dataSource......................none
dataSourceClassName.............none
dataSourceJNDI..................none
dataSourceProperties............{password=<masked>}
driverClassName................."org.postgresql.Driver"
healthCheckProperties...........{}
healthCheckRegistry.............none
idleTimeout.....................600000
initializationFailTimeout.......200000
isolateInternalQueries..........false
jdbcUrl.........................jdbc:postgresql://127.0.0.1:5432/docker
leakDetectionThreshold..........0
maxLifetime.....................1800000
maximumPoolSize.................10
metricRegistry..................none
metricsTrackerFactory...........none
minimumIdle.....................10
password........................<masked>
poolName........................"HikariPool-1"
readOnly........................false
registerMbeans..................false
scheduledExecutor...............none
schema..........................none
threadFactory...................internal
transactionIsolation............default
username........................"docker"
validationTimeout...............5000
```
In Hikari 2.6.3 I had correctly working retry, which ensured that my application waits for database initialization.
Now, as I upgraded to Hikari 3.3.1 it fails instantly with
```
com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: The connection attempt failed.
   at com.zaxxer.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:597)
   at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:576)
   at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
   at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
   ...
   Cause: org.postgresql.util.PSQLException: The connection attempt failed.
   at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:292)
   at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
   at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:195)
   at org.postgresql.Driver.makeConnection(Driver.java:454)
   at org.postgresql.Driver.connect(Driver.java:256)
   at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
   at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:353)
   at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
   at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:473)
   at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:562)
   ...
   Cause: java.io.EOFException:
   at org.postgresql.core.PGStream.receiveChar(PGStream.java:308)
   at org.postgresql.core.v3.ConnectionFactoryImpl.enableSSL(ConnectionFactoryImpl.java:405)
   at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:94).
   at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:192)
[info]   at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
[info]   at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:195)
[info]   at org.postgresql.Driver.makeConnection(Driver.java:454)
[info]   at org.postgresql.Driver.connect(Driver.java:256)
[info]   at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
[info]   at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:353)
[info]   ...
```
README for `initializationFailTimeout` says 
> Any positive number is taken to be the number of milliseconds to attempt to acquire an initial connection; the application thread will be blocked during this period. If a connection cannot be acquired before this timeout occurs, an exception will be thrown. 
But in my experience this parameter is ignored.

I checked the pool creation code itself, and noticed that pool entry exception handling was changed. I think this could be the root of the issue.

-----------------------------------------------------------------------------------------
*Have you searched the CLOSED issues already? How about checking [stackoverflow](https://stackoverflow.com/search?q=HikariCP)?* yep

**Comment by KineticCookie** [comment]
I found that in `HikariPool` class `checkFailFast()` uses almost the same code, except for the following lines: https://github.com/brettwooldridge/HikariCP/blob/086bf18389282d1a7484e243d6af49890cec4fd7/src/main/java/com/zaxxer/hikari/pool/HikariPool.java#L491-L512

I suppose that when PostgresSQL driver throws an expection, it's handled there with `lastConnectionFailure.set(new ConnectionSetupException(e));` call. This leads to a successful check in https://github.com/brettwooldridge/HikariCP/blob/086bf18389282d1a7484e243d6af49890cec4fd7/src/main/java/com/zaxxer/hikari/pool/HikariPool.java#L575-L577

Which leads to fast failure, ignoring the `initializationFailTimeout` parameter.

But I'm not entirely familiar with Hikari code, and can't say for sure if it's a planned behaviour or not

**Comment by brettwooldridge** [comment]
@KineticCookie Maybe you can do some further investigation.  If this is indeed the code path you have observed, something strange is occurring.

That code path implies that a ``Connection`` *was* returned by the driver on PoolBase.java line 353, and *then* a failure occurred setting up the connection in the call to ``setupConnection(connection)`` on line 355:
https://github.com/brettwooldridge/HikariCP/blob/45912ebb570ff9d54c010da61d1f2c26cc5cd39b/src/main/java/com/zaxxer/hikari/pool/PoolBase.java#L344-L358

In this case, the error is treated differently.  The assumption is that all *future* setups will fail in the same way, and therefore the initialization is aborted.

The *expectation* is that *if* the driver returns a ``Connection`` object, it is in fact valid.  If it cannot return a valid ``Connection``, I expect an exception to be thrown from the ``dataSource.getConnection()`` call on line 353.

However, *if* you are seeing this behavior that implies that the driver is returning an invalid ``Connection`` which cannot be setup, which would be a *driver* issue, not a HikariCP issue.  If you determine that this is what is occurring, and open an issue against the PostgreSQL driver, please leave a comment here with a link to that issue.

Re-open if you have hard evidence that it is in fact an issue internal to HikariCP.
