### ISSUE TITLE
Is there a possibility to take 2000+ ms to timeout when the connectionTimeout is set to 1000ms?

### ISSUE THREAD

**Issue by Manuri** [brettwooldridge/HikariCP#1443]
#### Environment
```
HikariCP version: 3.3.1
JDK version     : jdk8u202-b08
Database        : HSQLDB
Driver version  : 2.4.0
```

Is there a possibility to take 2000+ ms to timeout when the connectionTimeout is set to 1000ms? I've noticed the log saying
```bash
Connection is not available, request timed out after 1012ms
```
When the timeout is 1000ms which I guess is OK, but following seems a bit off.

```bash
Connection is not available, request timed out after 2427ms
```

-----------------------------------------------------------------------------------------
*Have you searched the CLOSED issues already? How about checking [stackoverflow](https://stackoverflow.com/search?q=HikariCP)?*

**Comment by brettwooldridge** [comment]
@Manuri It is possible, maybe even likely, if the application server is under heavy load (like somewhere close to 100%).
