### ISSUE TITLE
Question: HikariCP write handling on failover

### ISSUE THREAD

**Issue by joehammerman** [brettwooldridge/HikariCP#1447]
#### Environment
```
HikariCP version: 2.4.7
JDK version     : 1.8.0_111
Database        : PostgreSQL
Driver version  : 9.4.1211
```

Good evening HIkariCP developers,

We have recently built some HA Postgres architectures for our users, and I am composing a best practices connection guide for them. I apologize if my questions are well tread - I did attempt to do some research on this issue before creating a request for information issue.

I am trying to determine the fate of in flight transactions during a crash or network partition. From what I can tell, it seems that all 08000 class exceptions are caught and retried for a specifiable loop retry count? Is the error code range explicitly published anywhere?

Thank you for testing connection liveness before trying to put the data on the wire!

Thanks in advance for any assistance anyone can provide.
Joseph Hammerman
-----------------------------------------------------------------------------------------
*Have you searched the CLOSED issues already? How about checking [stackoverflow](https://stackoverflow.com/search?q=HikariCP)?*

**Comment by brettwooldridge** [comment]
https://en.m.wikipedia.org/wiki/SQLSTATE

08000 class errors are all connectivity related.
