### ISSUE TITLE
Release notes/ Updates in Change file for 3.4.0

### ISSUE THREAD

**Issue by ravir2r91** [brettwooldridge/HikariCP#1451]
@brettwooldridge , It would be nice to have some release notes or the changes for 3.4.0 mentioned somewhere like this https://github.com/brettwooldridge/HikariCP/blob/dev/CHANGES.

It was also mentioned here : https://github.com/brettwooldridge/HikariCP/issues/184

Thanks.

**Comment by brettwooldridge** [comment]
Updated.
