### ISSUE TITLE
How to specify the size of a pool to be able to quiesce it to zero ?

### ISSUE THREAD

**Issue by przemolb** [brettwooldridge/HikariCP#1460]
For testing purposes and to save on cost (especially in testing environments) we can nowadays use serverless databases:
https://docs.microsoft.com/en-us/azure/sql-database/sql-database-serverless#autopausing-and-autoresuming
To be able to use it number of sessions has to drop to 0.
How to specify the hikari pool size to reduce number of connections to zero (when app is idle)  ?
Of course in this case we sacrifice performance for cost but let's assume we focus on cost.
Is setting `minimumIdle` to 0 enough to achieve it ?

**Comment by quaff** [comment]
You can achieve it with `ds.setMinimumIdle(0)`, please note the default `idleTimeout` is 10 minutes, you should shorten it.
