### ISSUE TITLE
 HikariConnectionPool - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@5145c183 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.

### ISSUE THREAD

**Issue by namjitharavind** [brettwooldridge/HikariCP#1483]
#### Environment
```
HikariCP version: 3.4.1
JDK version     : 11
Database        : MySQL
Driver version  : x.x.x

on a particular i am getting this on tomcat log. Because of this i am getting great delay often. Once this happen remaining request are super fast some other interval. I realising connection are closing after some time. So is there any option to avoid this failure and keep connection always open. I really need to open connections always. I am using springboot 2.2 , Please help

**Comment by namjitharavind** [comment]
I  have fixed this issue by giving maxLifeTime(20000) value less than wait_timeout(28800) in mysql

**Comment by ergamiri** [comment]
Hi, please, can you tell me in which configuration file should I put the maxLifeTime parameter? Thanks

**Comment by bulentozdil** [comment]
> Hi, please, can you tell me in which configuration file should I put the maxLifeTime parameter? Thanks

Actually you can add the following to your application.properties file where exists your project folder;

`spring.datasource.testOnBorrow=true`
`spring.datasource.validationQuery=SELECT 1`

more detail :  https://stackoverflow.com/questions/22684807/spring-boot-jpa-configuring-auto-reconnect

**Comment by csc365kl** [comment]
> I have fixed this issue by giving maxLifeTime(20000) value less than wait_timeout(28800) in mysql

20000 is millisecond 
28800 is second  
so  why   fixed ?

**Comment by jerry100chan** [comment]
@csc365kl agree with that, and i have a same question?Is that a bug or not?how shold i do?

**Comment by micobarac** [comment]
Is this issue solved? I am getting the same problem with `HikariCP v. 4.0.3` and `MariaDB`.
`maxLifetime` has default value (`30 minutes`), `MariaDB` has `wait_timeout` set to default `28800`.

**Comment by i5on9i** [comment]
how about check the GLOBAL variable instead of just variable ?

- https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_wait_timeout

```
SHOW global VARIABLES LIKE '%_timeout%';
```
> On thread startup, the session [wait_timeout](https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_wait_timeout) value is initialized from the **global** [wait_timeout](https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_wait_timeout) value or from the **global** [interactive_timeout](https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_interactive_timeout) value, depending on the type of client (as defined by the CLIENT_INTERACTIVE connect option to [mysql_real_connect()](https://dev.mysql.com/doc/c-api/8.0/en/mysql-real-connect.html)). See also [interactive_timeout](https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_interactive_timeout).

**Comment by nadirvishun** [comment]
The same issue occurs even though my MySQL's `wait_timeout` is set to `28800` (`8 hours`), while Hikari's `maxLifetime` default is `1800000` (`30 minutes`). However, still encountering this error, I don't have a local connection to the database, but instead connect remotely through port mapping. Therefore, it may be due to this reason.
In the latest version of the documentation, we can set the `keepaliveTime` parameter, by setting the `keepalive-time: 60000`, the issue has been resolved.
![image](https://github.com/brettwooldridge/HikariCP/assets/5761981/8c948ba2-f63b-401c-b7d5-4fffee98bad0)

my test environment: `springboot3.2.4`，`hikari5.0.1`，`mysql5.7`

**Comment by syj1990s** [comment]
It happens occasionally in prod environment，maxLifetime is 900000（15 minutes）,  wait_time is 28800（8 hours），any other reasons？
