### ISSUE TITLE
Warn: Failed to validate connection postgresql (This connection has been closed.).

### ISSUE THREAD

**Issue by ToxicMushroom** [brettwooldridge/HikariCP#1486]
#### Environment
```
HikariCP version: 3.4.1
JDK version     : 12.0.2
Database        : PostgreSQL
Driver version  : 42.2.8
```

I have been having errors in my scheduledServices
```04-11-2019 18:53:20 [Mute-Service]  PoolBase WARN HikariPool-1 - Failed to validate connection org.postgresql.jdbc.PgConnection@3b7e110 (This connection has been closed.). Possibly consider using a shorter maxLifetime value.```
This service executes a statement every second.
statement: ```"SELECT * FROM $table WHERE active = ? AND endTime < ?"```

The errors don't have a specific pattern as far as I know. It doesn't get spammed just every now and then. I also had these errors with mysql. My database is on the same lan as my application.

#### Hikaricp config (kotlin)
```Kotlin
    val config = HikariConfig()
    config.jdbcUrl = "jdbc:postgresql://${dbSettings.host}:${dbSettings.port}/${dbSettings.database}"
    config.username = dbSettings.user
    config.password = dbSettings.password
    config.maxLifetime = 30_000
    config.validationTimeout = 3_000
    config.connectionTimeout = 30_000
    config.addDataSourceProperty("autoReconnect", "true")
```

please let me know what's causing this, the maxLifetime is already on the lowest value. I wasn't able to find people that knew how to fix it.

**Comment by nunnrlc** [comment]
Does the scheduled service keep hold of the connection for a long time?

If it does, that may be the problem. Ideally the usage pattern is quite tight, like (sorry, in plain Java...):

```
try (Connection con = datasource.getConnection()) {
  con.execute...
}
```

With the connection getting "closed" - handed back to the pool in reality - after just a handful of statements.

Also, I think that autoReconnect type options are not recommended in conjunction with HikariCP.

**Comment by ToxicMushroom** [comment]
@nunnrlc Hm I'm using the .use method on closable resources in kotlin, which is the replacement for try with resources in java (I hope haha).
Connections are not leaking (I've tested this with the leakdetection option)

Thanks for the suggestion about autoReconnect though

**Comment by jzdayz** [comment]
No original exception throw? This log does not provide a substantial effect

**Comment by jzdayz** [comment]
Or you can provide specific code?

**Comment by ToxicMushroom** [comment]
@jzdayz https://github.com/ToxicMushroom/Melijn/blob/rewrite/src/main/kotlin/me/melijn/melijnbot/database/mute/MuteDao.kt#L30 
this is the query that was ran each second

I got these exceptions sometimes with the warning but not often (I didn't get these when I posted this)
https://hasteb.in/pezudehi.cs

I actually stopped getting these warnings and errors but I don't know what fixed it :/

**Comment by jzdayz** [comment]
> @jzdayz https://github.com/ToxicMushroom/Melijn/blob/rewrite/src/main/kotlin/me/melijn/melijnbot/database/mute/MuteDao.kt#L30
> 这是每秒运行的查询
> 
> 我有时会在警告中出现这些异常，但是却很少（在发布此消息时并没有得到这些异常）
> https://hasteb.in/pezudehi.cs
> 
> 我实际上停止收到这些警告和错误，但是我不知道该怎么解决：/

It looks like the sql execution time is too long (driver read time out), causing the connection to get timed out. I think you can monitor the length of time you execute sql on the client side.

**Comment by jzdayz** [comment]
> @jzdayz https://github.com/ToxicMushroom/Melijn/blob/rewrite/src/main/kotlin/me/melijn/melijnbot/database/mute/MuteDao.kt#L30
> this is the query that was ran each second
> 
> I got these exceptions sometimes with the warning but not often (I didn't get these when I posted this)
> https://hasteb.in/pezudehi.cs
> 
> I actually stopped getting these warnings and errors but I don't know what fixed it :/

It looks like the sql execution time is too long (driver read time out), causing the connection to get timed out. I think you can monitor the length of time you execute sql on the client side.

**Comment by jzdayz** [comment]
From getting the connection to executing sql until the connection is released

**Comment by ToxicMushroom** [comment]
@jzdayz okay, I'll monitor that

**Comment by ToxicMushroom** [comment]
It's mostly 0-2ms with some exceptions up to 10ms but I can't seem to replicate the warnings anymore

**Comment by jzdayz** [comment]
> It's mostly 0-2ms with some exceptions up to 10ms but I can't seem to replicate the warnings anymore

This is normal, from the log point of view, it is obvious that some connections execute sql too long, it seems to be a network problem, the read time out occurs, I suggest you do this for a while, then keep Monitor.

**Comment by ToxicMushroom** [comment]
I haven't gotten the warning again @jzdayz

**Comment by jzdayz** [comment]
> I haven't gotten the warning again @jzdayz

I think this may be caused by network jitter, because from the code point of view, the database operations performed by hikariCp are delegated to the actual driver. If the current monitoring does not affect the performance, then I recommend to keep it.
