### ISSUE TITLE
A link in the wiki is broken

### ISSUE THREAD

**Issue by rocboronat** [brettwooldridge/HikariCP#1487]
The one that says `If you are using MySQL, you really need to read this slide-stack` in this page https://github.com/brettwooldridge/HikariCP/wiki/MySQL-Configuration

**Comment by rocboronat** [comment]
It should point to `https://cdn.oreillystatic.com/en/assets/1/event/21/Connector_J%20Performance%20Gems%20Presentation.pdf`

(well, that's what I've found on Google :D )

**Comment by brettwooldridge** [comment]
fixed, thx.
