### ISSUE TITLE
Postgres network connection timeout is not set

### ISSUE THREAD

**Issue by deedarb** [brettwooldridge/HikariCP#1500]
#### Environment
```
HikariCP version: 3.4.1
JDK version     : AdoptOpenJDK (build 11.0.4+11)
Database        : PostgreSQL
Driver version  : org.postgresql:postgresql:42.2.8
```

minimal reproducer (prints "network timeout: 0")
```
import com.zaxxer.hikari.HikariConfig;
import com.zaxxer.hikari.HikariDataSource;

import java.sql.SQLException;
import java.time.Duration;

public class DebugHikari {

	public static void main(String[] args) throws SQLException {
		var ds = new HikariConfig();
		ds.setUsername("postgres");
		ds.setPassword("postgres");
		ds.setJdbcUrl("jdbc:postgresql://localhost:5432/postgres");
		ds.setValidationTimeout(5000);
		ds.setConnectionTestQuery("select current_date");
                ds.setConnectionTimeout(Duration.ofSeconds(30).toMillis());
		ds.setMaximumPoolSize(5);
		
		var dataSource = new HikariDataSource(ds);
		try (var con = dataSource.getConnection()) {
			System.out.println("network timeout: " + con.getNetworkTimeout());
		}

		System.out.println("finished");
	}
}
```
Possible method containing problem is https://github.com/brettwooldridge/HikariCP/blob/dev/src/main/java/com/zaxxer/hikari/pool/PoolBase.java#L388

getAndSet always returns 0 and afterwards setNetworkTimeout called with param 0

workaround for postgresql is to add 
```ds.addDataSourceProperty("socketTimeout", 5);//timeout in seconds```

**Comment by gdimitrov7** [comment]
This seems like correct behavior. HikariCP does not have property that can control the underlying TCP connection created by PostgreSQL JDBC driver. The default socketTimeout of PostgreSQL JDBC driver is 0. This is why getAndSetNetworkTimeout() returns 0. The idea of the getAndSetNetworkTimeout() is to preserve the original DB timeout and to set temporary validation timeout (which is usually shorter), and after the validation finish to return back the original value.

Setting the "socketTimeout" is correct way to configure the network timeout of the postgres JDBC DB connection.

**Comment by deedarb** [comment]
ok, thanks for explanation!
