### ISSUE TITLE
Doesnt acquire new connection even though max pool is not met and thread are waiting .

### ISSUE THREAD

**Issue by ramdevboddapu** [brettwooldridge/HikariCP#1511]
HikariPool-1 - Before cleanup stats (total=4, active=4, idle=0, waiting=6)
HikariPool-1 - After cleanup  stats (total=4, active=4, idle=0, waiting=6)
HikariPool-1 - Before cleanup stats (total=4, active=4, idle=0, waiting=1)
HikariPool-1 - After cleanup  stats (total=4, active=4, idle=0, waiting=1)
HikariPool-1 - Before cleanup stats (total=4, active=3, idle=1, waiting=0)
HikariPool-1 - After cleanup  stats (total=4, active=3, idle=1, waiting=0)
HikariPool-1 - Before cleanup stats (total=4, active=4, idle=0, waiting=7)
HikariPool-1 - After cleanup  stats (total=4, active=4, idle=0, waiting=7)
HikariPool-1 - Before cleanup stats (total=4, active=4, idle=0, waiting=7)
HikariPool-1 - After cleanup  stats (total=4, active=4, idle=0, waiting=7)
HikariPool-1 - Before cleanup stats (total=4, active=4, idle=0, waiting=9)
HikariPool-1 - After cleanup  stats (total=4, active=4, idle=0, waiting=9)
HikariPool-1 - Before cleanup stats (total=4, active=4, idle=0, waiting=10)
HikariPool-1 - After cleanup  stats (total=4, active=4, idle=0, waiting=10)
HikariPool-1 - Before cleanup stats (total=4, active=4, idle=0, waiting=9)
HikariPool-1 - After cleanup  stats (total=4, active=4, idle=0, waiting=9)
HikariPool-1 - Before cleanup stats (total=4, active=4, idle=0, waiting=11)
HikariPool-1 - After cleanup  stats (total=4, active=4, idle=0, waiting=11)
HikariPool-1 - Before cleanup stats (total=4, active=4, idle=0, waiting=8)
HikariPool-1 - After cleanup  stats (total=4, active=4, idle=0, waiting=8)
HikariPool-1 - Before cleanup stats (total=4, active=4, idle=0, waiting=12)
HikariPool-1 - After cleanup  stats (total=4, active=4, idle=0, waiting=12)
HikariPool-1 - Before cleanup stats (total=4, active=4, idle=0, waiting=2)
HikariPool-1 - After cleanup  stats (total=4, active=4, idle=0, waiting=2)
HikariPool-1 - Before cleanup stats (total=4, active=4, idle=0, waiting=7)
HikariPool-1 - After cleanup  stats (total=4, active=4, idle=0, waiting=7)
HikariPool-1 - Before cleanup stats (total=4, active=4, idle=0, waiting=3)
HikariPool-1 - After cleanup  stats (total=4, active=4, idle=0, waiting=3)

**Comment by ramdevboddapu** [comment]
i guess the default max pool size is 20 ..

**Comment by ramdevboddapu** [comment]
HikariPool-1 - Timeout failure stats (total=4, active=4, idle=0, waiting=17)
HikariPool-1 - Timeout failure stats (total=4, active=4, idle=0, waiting=16)

instead the request fail on meeting maxwaittime for getting a connection

**Comment by brettwooldridge** [comment]
@ramdevboddapu The default max pool size is 10 (read the docs).  This sounds like a connection leak.  Very likely a thread is borrowing a connection but never closing it (causing it to return to the pool).  I recommend enabling the ``leakDetectionThreshold`` and watching the log for reported leaks.  Also, as always, make sure you are on the latest version of HikariCP.

**Comment by ramdevboddapu** [comment]
@brettwooldridge 
i was using spring-cloud-service-connectors ..the connectors are setting to 4 as max pool size .. please close this as this is issue with spring cloud connectors.
