### ISSUE TITLE
[regression] f005a476 broke HikariConfig.initializationFailTimeout

### ISSUE THREAD

**Issue by ewirch** [brettwooldridge/HikariCP#1528]
`initializationFailTimeout` is documented to control "whether the pool will "fail fast"", but we actually use it to fail slow, but eagerly. Our connect timeout is set to 10s. We start our application and the database at the same time. Sometimes the database is slower than the application. Therefore we set `initializationFailTimeout` higher than connection timeout.

If database is slower than app, trying to connect to the database gives a `java.net.ConnectException: Connection refused`. Before 3.3.0 HikariCP would simply retry regardless of exception thrown during connection attempt:
```
      catch (Exception e) {
         if (poolState == POOL_NORMAL) { // we check POOL_NORMAL to avoid a flood of messages if shutdown() is running concurrently
            LOGGER.debug("{} - Cannot acquire connection from data source", poolName, (e instanceof ConnectionSetupException ? e.getCause() : e));
         }
         return null;
      }
```
Then, f005a476 changed this to record a `ConnectionSetupException`:
```
      catch (SQLException e) {
         if (poolState == POOL_NORMAL) { // we check POOL_NORMAL to avoid a flood of messages if shutdown() is running concurrently
            logger.debug("{} - Cannot acquire connection from data source", poolName, e);
            lastConnectionFailure.set(new ConnectionSetupException(e));
         }
         return null;
      }
      catch (Exception e) {
         if (poolState == POOL_NORMAL) { // we check POOL_NORMAL to avoid a flood of messages if shutdown() is running concurrently
            logger.error("{} - Error thrown while acquiring connection from data source", poolName, e);
            lastConnectionFailure.set(new ConnectionSetupException(e));
         }
         return null;
      }
```

...which in turn makes `checkFailFast()` fail immediately:
```
         if (getLastConnectionFailure() instanceof ConnectionSetupException) {
            throwPoolInitializationException(getLastConnectionFailure().getCause());
         }
```
...which in turn renders `initializationFailTimeout` useless. Any exception will result in a `ConnectionSetupException`. `checkFailFast()` will exit immediately, without even using the timeout.

**Comment by brettwooldridge** [comment]
Interesting.  I should have reviewed that "cleanup" pull request more carefully (it was *huge*).  I did not notice the change in behavior, which I agree is a regression.  Sigh.

**Comment by brettwooldridge** [comment]
Oh, it wasn't that commit, it was 74fa2a8.

**Comment by ewirch** [comment]
74fa2a8 catches `SQLException`, but does not add it to `lastConnectionFailure` - `checkFailFast()` would not know about the `SQLException` (`CoennectionException` is wrapped in `org.postgresql.util.PSQLException`, which is a `SQLException`). But it is true for other exceptions.
