### ISSUE TITLE
HikariCP MS SQL Server maxlifetime rejected connections

### ISSUE THREAD

**Issue by aw-think** [brettwooldridge/HikariCP#1535]
**Environment**
HikariCP: 3.4.2
Java: java version "1.8.0_141"
Java(TM) SE Runtime Environment (build 1.8.0_141-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.141-b15, mixed mode)
MS JDBC: 7.4.1
SQL Server: 12.0.5522.0

**HikariCP configuration** 
(inside ActiveMQ configuration file activemq.xml)
```  
<bean id="hikariConfig" class="com.zaxxer.hikari.HikariConfig">
    <property name="poolName" value="activemq-hikari-ds" />
    <property name="dataSourceClassName" value="com.microsoft.sqlserver.jdbc.SQLServerDataSource" />
    <property name="maxLifetime" value="30000" />
    <property name="registerMbeans" value="true" />
    <property name="dataSourceProperties">
        <props>
            <prop key="url">jdbc:sqlserver://sqlserver;databaseName=amqTest;instanceName=app</prop>
            <prop key="user">activemq</prop>
            <prop key="password">xxx</prop>
        </props>
    </property>
</bean>

<bean id="hikari-ds" class="com.zaxxer.hikari.HikariDataSource" destroy-method="close">
    <constructor-arg ref="hikariConfig" />
</bean>

```

**Error message** 
(in activemq.log)
```
Failed to validate connection ConnectionID:733 ClientConnectionId: a68fb7a5-47a6-4220-aac5-4208439cd5fd (Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@690fde36 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@552740dd[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]). Possibly consider using a shorter maxLifetime value. | com.zaxxer.hikari.pool.PoolBase | ActiveMQ Broker[AMQTest] Scheduler
```

**What I've tried so far**

1. As one suggested: set the maxLifetime property to 10000 using JMX. The error message still came.

The default connection timeout for our MS SQL Server is 15 seconds. So I wonder if maxLifetime could not be set to a lower value than 30000 miliseconds? But maybe this isn't the problem at all?

![JMX-properties](https://user-images.githubusercontent.com/2565578/73055655-94718580-3e8d-11ea-8550-e4a549fdc346.png)

**Comment by brettwooldridge** [comment]
@aw-think HikariCP does not support a ``maxLifetime`` below 30 seconds (30000ms).  But as you noted it is possible to force it lower via JMX.  But it should also be noted that once set with JMX, the change may not take effect for up to 30 seconds.

But none of that may matter, as the error implies that the pool, and therefore the internal ScheduledThreadPoolExecutor, has been shutdown!  See [this post](https://stackoverflow.com/questions/45182730/rejected-execution-exception).  Also, [similar issues](https://github.com/ReactiveX/RxJava/issues/3927) can be seen in entirely different libraries.  As to *what* is shutting down the pool only you can know.
