### ISSUE TITLE
Hikari Connection Pooling with JdbcTemplate batchupdate

### ISSUE THREAD

**Issue by dlakra96** [brettwooldridge/HikariCP#1537]
I am using hikari connection pooling in one of my projects. FYI, the project consists of many data processing jobs that either update or insert a lot of data in batches using JdbcTemplate batchupdate. 
I have set the following configuration properties for connection pooling :- 

hikariConfig.addDataSourceProperty("cachePrepStmts", "true");
hikariConfig.addDataSourceProperty("prepStmtCacheSize", "200");
hikariConfig.addDataSourceProperty("prepStmtCacheSqlLimit", "2048");
hikariConfig.setMaximumPoolSize(10);
hikariConfig.setMaxLifetime(1200000);

The batchSize for JdbcTemplate BatchUpdate is a global variable and is set to 1000 for all data processing jobs. 
The problem is that after few batches of update in one of the job, I am getting connection not found error after its set limit of 30 seconds and after series of the same error, the entire application shuts down abruptly and no longer becomes accessible.

I doubt that there is some problem with the batch size that I have chosen and the number of connections that I am setting for max pool size or with the cachePrepStmts datasource property value.

Please help me in getting out of this problem.

**Comment by dlakra96** [comment]
By debugging the project and using leakDetectionThreshold I found out places where the connection was leaking.

**Comment by bibarsov** [comment]
@dlakra96 what was the reason?
