### ISSUE TITLE
HikariPool-1 - Connection is not available, request timed out after 250ms.

### ISSUE THREAD

**Issue by jbaezml** [brettwooldridge/HikariCP#1538]
**Environment**

```
HikariCP version: 3.4.2
JDK version     : 1.8.0_111
Database        : MySQL
```
**Log on New Relic**

caused by java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 250ms.
…m.zaxxer.hikari.pool.HikariPool.createTimeoutException (HikariPool.java:689)
        com.zaxxer.hikari.pool.HikariPool.getConnection (HikariPool.java:196)
        com.zaxxer.hikari.pool.HikariPool.getConnection (HikariPool.java:161)
       com.zaxxer.hikari.HikariDataSource.getConnection (HikariDataSource.java:100)
….commons.dbutils.AbstractQueryRunner.prepareConnection (AbstractQueryRunner.java:319)
           org.apache.commons.dbutils.QueryRunner.query (QueryRunner.java:327)
…h.clean.repositories.AbstractDbRepository.executeQuery (AbstractDbRepository.java:37)

**The application has 14K rpm at the time of the error. It works by traffic gusts, can have drastic traffic changes.**

**Configuration of the pool (a singleton datasource)**

hikariConfig.setMaximumPoolSize(20);
hikariConfig.setMinimumIdle(3);
hikariConfig.setIdleTimeout(120000);
hikariConfig.setConnectionTimeout(250);

hikariConfig.addDataSourceProperty("cachePrepStmts", "true");
hikariConfig.addDataSourceProperty("prepStmtCacheSize", "250");
hikariConfig.addDataSourceProperty("prepStmtCacheSqlLimit", "2048");
hikariConfig.addDataSourceProperty("useServerPrepStmts", "true");

hikariConfig.addDataSourceProperty("useLocalSessionState", "true");
hikariConfig.addDataSourceProperty("rewriteBatchedStatements", "true");
hikariConfig.addDataSourceProperty("cacheResultSetMetadata", "true");
hikariConfig.addDataSourceProperty("cacheServerConfiguration", "true");
hikariConfig.addDataSourceProperty("elideSetAutoCommits", "true");
hikariConfig.addDataSourceProperty("maintainTimeStats", "false");

I cannot find the correct configuration for this application

**Comment by arisjramos** [comment]
250ms seems to be a quite short timeout if your database is under load, try to increase this timeout to some seconds... try this :
hikariConfig.setConnectionTimeout(3000); // 3 seconds of connection timout

**Comment by brettwooldridge** [comment]
@jbaezml The comment above regarding database load by @arisjramos is correct.  However, even if your database answers all queries in single-digit millisecond response times, at 14k request/min you are likely generating a TON of garbage.  My guess is that you are encountering GC stop-the-world (STW) pauses greater than 250ms.

On Java 8, for that kind of load, you need to be using the CMS garbage collector, and it needs to be tuned properly.

https://wikitech.wikimedia.org/wiki/JVM_Tuning

https://dzone.com/articles/how-to-reduce-long-gc-pause

And you probably want to set ``MaxGCPauseMillis`` to some reasonable value.  But setting this to something too low like 50ms is likely to jack-up your application.

You can also try, the G1 collector with ``MaxGCPauseMillis`` defined, but it should probably only be used if your heap is >= 4Gb.

UPDATE: You probably want to enable [garbage collection logging](https://wikitech.wikimedia.org/wiki/JVM_Tuning#Garbage_collection_logging) and examine the log for long pauses, as well has comparing the behavior with different experimental GC settings.
