### ISSUE TITLE
[Documentation] - Broken link in "About Pool Sizing"

### ISSUE THREAD

**Issue by supermacro** [brettwooldridge/HikariCP#1539]
In the [About Pool Sizing](https://github.com/brettwooldridge/HikariCP/wiki/About-Pool-Sizing) doc, the link to video from Oracle Real-World Performance group links to a non-existent video.

**Comment by billoneil** [comment]
You can find it here https://www.youtube.com/watch?v=xNDnVOCdvQ0

**Comment by johnou** [comment]
@brettwooldridge would you kindly update the link in the wiki? Seems it is not open to contributions.

**Comment by lfbayer** [comment]
Done

**Comment by johnou** [comment]
Thanks Leo.

**Comment by brettwooldridge** [comment]
Yeah, thanks @lfbayer !

**Comment by BeniaminK** [comment]
This video is not available again. Could you provide some details how to find it?
