### ISSUE TITLE
maxLifetime problem

### ISSUE THREAD

**Issue by xixincan** [brettwooldridge/HikariCP#1561]
I have a problem with the class **PoolBase's** property **maxLifetime**, when I set the value longer than **120000ms**, it's alway get a warnning log at regular intervals (maxLifetime) as follow: 
   "Failed to validate connection {xxxx} (No operation allowed after con is closed). Possibly consider using a shorter maxLifetime value."
I find the target connnection is **closed** though debuging, I don't figure it out why it's OK to set value to 120000ms, could anyone please help me?

PS: **MySQL** variable **wait_timeout** value is 600

**Comment by brettwooldridge** [comment]
I have seen MySQL close connections sooner than wait_timeout to conserve resources.  The best advice I can give is to find a stable value, and use that.

If you are truly curious, you can use wireshark and watch the traffic to see which side closes the connection (with a FIN tcp packet).  I can pretty much guarantee it is MySQL closing the connection.  Maybe ask on MySQL support forums about why MySQL might close connections before wait_timeout.

**Comment by xixincan** [comment]
> I have seen MySQL close connections sooner than wait_timeout to conserve resources. The best advice I can give is to find a stable value, and use that.
> 
> If you are truly curious, you can use wireshark and watch the traffic to see which side closes the connection (with a FIN tcp packet). I can pretty much guarantee it is MySQL closing the connection. Maybe ask on MySQL support forums about why MySQL might close connections before wait_timeout.

Thanks for your advice, as the pic,
![image](https://user-images.githubusercontent.com/31444683/77403396-2b55b200-6deb-11ea-82da-cc22d42f8804.png)
Is that means port-10309 side close the connection ?

**Comment by brettwooldridge** [comment]
You do not show IP addresses.  The question is: which IP sent [FIN, ACK], the MySQL server or the application?

**Comment by xixincan** [comment]
the application did. 61306 is MySQL server port.
