### ISSUE TITLE
Connection reset

### ISSUE THREAD

**Issue by wang-xu-huai** [brettwooldridge/HikariCP#1570]
**
Springboot  2.1.2.RELEASE
Oracle JDBC driver  is ojdbc6: 11.2.0.3 
HikariCp  3.2.0

datasource config 
      idle-timeout: 600000  
      max-lifetime: 1200000
      minimum-idle: 10
      maximum-pool-size: 20
      connection-timeout: 20000
      validationTimeout: 10000
      leak-detection-threshold: 50000
**

_During applicaiton startup, I get following warning::_
### com.zaxxer.hikari.pool.PoolBase - HikariPool-1 - Driver does not support get/set network timeout for connections. (oracle.jdbc.driver.T4CConnection.getNetworkTimeout()I)

_When my program runs for a period of time, an exception will be reported_

### java.sql.SQLRecoverableException: IO Error: Connection reset

Then the app always reports that the connection is reset and unavailable

What should I do?

**Comment by brettwooldridge** [comment]
I suggest enabling debug logging.   That's a pretty old driver.  I would also try setting idle-timeout to 120000, and max-lifetime to 300000 to proactively close connections.

**Comment by wang-xu-huai** [comment]
After I upgraded the driver to 12.1.0.2, there was no warning of not support, and then I raised the struct entropy_store of the host where the database is located, so there was no connection reset error reported. So far, everything is normal .  thank you .
