### ISSUE TITLE
Add module-info.java to Java9+ artifact

### ISSUE THREAD

**Issue by cowwoc** [brettwooldridge/HikariCP#1572]
Please add `module-info.java` to a Java9+ artifact so those of us using Java Modules can depend on this library without receiving compiler warnings.

What compiler warnings? My module exports a DataSource factory that exposes `com.zaxxer.hikari.HikariDataSource`. This requires me to `requires transitive` on Hikari. And using `requires transitive` on an automatic module results in a compiler warning.

**Comment by brettwooldridge** [comment]
@cowwoc I do not intend to build a Java 9+ in the near or medium term, so this is not currently a possibility.  One way to eliminate the warning is to add ``-Xlint:-requires-transitive-automatic`` during compilation.  The other may be an explicit "--add-module" (or "--add-open") parameter, though I think that is for jars without even a MANIFEST.INF entry.

**Comment by cowwoc** [comment]
@brettwooldridge Are you open to multi-release JAR (https://openjdk.java.net/jeps/238)? Meaning, you would still target JDK 8 but if the user is using JDK 9 and newer it would pick up `module-info.java`.

https://blog.codefx.org/tools/multi-release-jars-multiple-java-versions/ provides a practical guide for getting this done.

**Comment by brettwooldridge** [comment]
@cowwoc Yes.  👍   Please fix my pom. 😁  No seriously, send a pull request.

**Comment by cowwoc** [comment]
@brettwooldridge I am trying to create a pull request for this but honestly it would be much easier to generate a separate artifact for Java 9+. Are you okay with doing so if I provide a pull request? Or are you only open to a multi-release JAR?

Conceptually multi-release JARs only require you to add `META-INF/versions/9/module-info.class` to the bundle `Multi-Release: true` to the `MANIFEST.MF` file. But in practice, it's easier to publish and test separate artifacts in Maven: http://maven.apache.org/plugins/maven-compiler-plugin/multirelease.html

**Comment by cowwoc** [comment]
@brettwooldridge I've provided a multi-release JAR as you requested: https://github.com/brettwooldridge/HikariCP/pull/1573
