### ISSUE TITLE
HikariPool-1 Connection oracle.java.driver.T4CConnection@655ce28e marked as broken because of SQLSTATE(08006) ,ErrorCode(17002)

### ISSUE THREAD

**Issue by michael-z-x-chen** [brettwooldridge/HikariCP#1583]
someTime we saw in production where HikariCP throw the Exception 

HikariPool-1 Connection oracle.java.driver.T4CConnection@655ce28e marked as broken because of SQLSTATE(08006) .=,ErrorCode(17002)

**Comment by michael-z-x-chen** [comment]
version HikariCP 3.2.0

**Comment by brettwooldridge** [comment]
This indicates that the oracle service or the Windows service helper fell over.  I suggest that you google ``oracle 17002`` and pursue suggested troubleshooting that way,
