### ISSUE TITLE
maximum-pool-size can not work in springboot2.X application.yml

### ISSUE THREAD

**Issue by langlichong** [brettwooldridge/HikariCP#1590]
hikariCP default pool-size is 10, now ,i need to override the max pool size , i did like this: 
1)、application.yml ：
                hikari:
                    pool-name: XXX
                    maximum-pool-size: 25
2) 、ebale hikari debug log , then my app debug log  show still the default value 10 
 
 why ？ please help me

**Comment by brettwooldridge** [comment]
This is a spring boot question, ask there.  It is 100% configurable.
