### ISSUE TITLE
Statement parameter 1 not set

### ISSUE THREAD

**Issue by cpostlethwait** [brettwooldridge/HikariCP#1607]
Intermittently I get a SQL Exception 'Statement parameter 1 not set' during execution of the below code. I've logged the Prepared Statement prior to execution and always it has parameters for each value, but still occasionally get the error despite having the params set. Can't reproduce it on command, but see it often enough. Pretty frustrating.

EXCEPTION:
java.sql.SQLException: Statement parameter 1 not set. at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965) at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898) at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887) at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861) at com.mysql.jdbc.ServerPreparedStatement.serverExecute(ServerPreparedStatement.java:1175) at com.mysql.jdbc.ServerPreparedStatement.executeInternal(ServerPreparedStatement.java:788) at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2124) at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2058) at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5158) at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2043) at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61) at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java) at com.stormed.common.collection.CollectionSQL.insertDBDocumentAndUploadS3File(CollectionSQL.java:217) at com.stormed.common.collection.CollectionSQL.insertDBDocumentAndUploadS3File(CollectionSQL.java:100) at com.stormed.collection.utils.CallableIMAPS.call(CallableIMAPS.java:61) at co.elastic.apm.agent.impl.async.SpanInScopeCallableWrapper.call(SpanInScopeCallableWrapper.java:65) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:748)

CODE SAMPLE:

try (Connection connection = ConnectionPoolManager.getConnectionFromPool();) {
	connection.setAutoCommit(true);

	String sql = "INSERT INTO " + projectDBName + ".ProjectDocument(DocumentName, DocumentStateID, IsPromoted, SourceID, CustodianID, FamilyID, CreatedBy, FileExtension, CollectionJobID, FileName, InternalParentID, FilePath, OriginalPath, RecordType, MailboxName, FileHash, FileSize, ParentDocumentID, CreatedDate, ParentAttachment) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, NOW(), ?);";
	insertDocument = connection.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);
	insertDocument.setString(1, documentName); // DocumentName
	insertDocument.setInt(2, documentStateID); // DocumentStateID
	insertDocument.setBoolean(3, isPromoted); // IsPromoted
	insertDocument.setInt(4, sourceID); // SourceID
	insertDocument.setInt(5, custodianID); // custodianId
	insertDocument.setInt(6, familyID); // FamilyID
	insertDocument.setInt(7, userID); // CreatedBy
	insertDocument.setString(8, fileExtension); // FileExtension
	insertDocument.setInt(9, jobID); // CollectionJobID
	insertDocument.setNString(10, fileName); // FileName
	insertDocument.setInt(11, internalParentID); // InternalParentID
	insertDocument.setNString(12, "\\"); // FilePath
	insertDocument.setNString(13, "\\"); // OriginalPath
	insertDocument.setNString(14, recordType); // RecordType
	insertDocument.setNString(15, folderName); // folderName
	insertDocument.setString(16, fileHashValue); // FileHash
	insertDocument.setDouble(17, fileSize); // FileSize
	if (parentDocumentID != 0) {
		insertDocument.setInt(18, parentDocumentID); // ParentDocumentId
		insertDocument.setString(19, "A"); // ParentAttachment
	} else {
		insertDocument.setString(18, null);
		insertDocument.setString(19, "P"); // ParentAttachment
	}

	insertDocument.executeUpdate();

**Comment by lfbayer** [comment]
It is very unlikely that this is a hikaricp bug. That code path in HikariCP doesn't touch the parameter values at all, so it shouldn't be possible for HikariCP to cause this.

I recommend you do a little more debugging to isolate the issue. If you can create an isolated test case that reproduces the issue, then feel free to reopen this issue with the test case.
