### ISSUE TITLE
The code style doesn't like java,it looks like c/c++

### ISSUE THREAD

**Issue by NOVA-ME** [brettwooldridge/HikariCP#1610]
Can we change the code style to java?

**Comment by lfbayer** [comment]
Can you clarify what you mean by this? Which code looks like c/c++?

**Comment by NOVA-ME** [comment]
```java
public class MicrometerMetricsTracker implements IMetricsTracker
{
...
}
```
I usually like this
```java
public class MicrometerMetricsTracker implements IMetricsTracker {
...
}
```

**Comment by lfbayer** [comment]
Yea, we won't change this coding format. And the style isn't specifically a "c/c++" style. It is just a subjective choice.

Ironically, the style you are asking for is often referred to as the Kernighan and Ritchie style (old school C).
