### ISSUE TITLE
Apparent connection leak detected - after upgrading hibernate and spring to version 5

### ISSUE THREAD

**Issue by shaharco** [brettwooldridge/HikariCP#1614]
Hi, Seeing this error from the leak detector, which i enabled after had some transaction timeout exceptions and other jdbc connection errors. This is an existing application which started seeing those errors only after upgrading Hibernate and Spring from 4 to 5. We are using HikariCP version 3.3.1
[com.zaxxer.hikari.pool.ProxyLeakTask] - Connection leak detection triggered for org.postgresql.jdbc.PgConnection@444d9de1 on thread qtp2121551683-18, stack trace follows
java.lang.Exception: Apparent connection leak detected

The stack trace sometimes contains regular Spring wrapping - TransactionAspectSupport.invokeWithinTransaction
and sometimes by our code which calls: TransactionTemplate.execute

our hikari properties:
```
<bean id="hikariConfigDataSource" class="com.zaxxer.hikari.HikariConfig">
		<property name="poolName" value="***"/>
		<property name="maximumPoolSize" value="${c3p0.connections.max}"/>
		<property name="minimumIdle" value="${c3p0.connections.min}"/>
		<property name="jdbcUrl" value="${jdbc.url}"/>
		<property name="username" value="${jdbc.username}"/>
		<property name="password" value="${jdbc.password}"/>
		<property name="driverClassName" value="${jdbc.driver.classname}"/>
		<property name="registerMbeans" value="true"/>
		<property name="leakDetectionThreshold" value="240000"/>

		<property name="dataSourceProperties">
			<props>
				<prop key="characterEncoding">UTF-8</prop>
				<prop key="useUnicode">yes</prop>
				<prop key="rewriteBatchedStatements">true</prop>
			</props>
		</property>
	</bean>

```
Any help is appreciated

**Comment by brettwooldridge** [comment]
Please upgrade.  HikariCP now logs "unleaked" connections if they are eventually returned to the pool.  You should be able to count the number of leak and unleak logs, and if they are not equal there is a real leak.  But to be honest, this sounds like an issue outside of HikariCP, as it is the variable that *did not* change and Spring/Hibernate versions *did*.
