### ISSUE TITLE
Connection Leak in Hikari Pool via JDBC.

### ISSUE THREAD

**Issue by vedanshgargoyo** [brettwooldridge/HikariCP#1616]
When our service starts, it creates new connections to our Postgres DB via JDBC. But once HIKARI_MAX_POOL_SIZE limit is reached, the requests start getting queued because old connections are not released.

Our Config: 

```
HIKARI_AUTO_COMMIT: "true"
HIKARI_CONNECTION_TEST_QUERY: SELECT 1
HIKARI_CONNECTION_TIMEOUT: "300000"
HIKARI_IDLE_TIMEOUT: "10000"
HIKARI_LEAK_DETECTION_THRESHOLD: "10000"
HIKARI_MAX_LIFETIME: "180000"
HIKARI_MAX_POOL_SIZE: "15"
HIKARI_MIN_IDLE: "5" 
```

It's giving following error: 
`java.lang.Exception: Apparent connection leak detected`

There has been no changes in our service recently. This error has started appearing suddenly. 
What can be the possible reason & solution?

**Comment by fervid-cloud** [comment]
@vedanshgargoyo  What was the problem btw?
