### ISSUE TITLE
Connections remaining active after 500 hits

### ISSUE THREAD

**Issue by sabyasachi-mukherjie** [brettwooldridge/HikariCP#1622]
Hi,
I am facing a strange issue while working on spring JDBC. The issue is that once the application is started, I need to make rest calls to an endpoint which in turn queries a postgresql DB and returns the result to me as a JSON.
Now, for the first 500 hits, the app is working like a charm. I can see that after the 500th hit is served, the hikari CP status is:
After cleanup  stats (total=6, active=0, idle=6, waiting=0).
Now on the 501th hit, it queries the DB successfully (I can see in the log) but then the response never comes back to me. I believe since Spring JDBC is handling the connection, it's expecting the connection just borrowed from the CP to come back following which it'll go on for next steps like formatting the data and returning to me as a JSON. I'm getting a 504 Endpoint request time out error but in the app logs I can see the DB was queried and data was retrieved but since the data was not returned in 30 seconds (the gateway has a timeout), it returns 504 Endpoint request timed out error to me.

My application.yaml has following entries:

spring:
   jpa:
       hikari:
           maximumPoolSize: 20
           minimumIdle: 5
           poolName: ${member}-adapter
           maxLifetime: 900000
           connectionTimeout: 30000
           idleTimeout: 300000
           leakDetectionThreshold: 30000

**Comment by brettwooldridge** [comment]
Seems like a Spring or driver issue.  You could try getting a thread dump while it is hung to find where the issue lies.
