### ISSUE TITLE
HikariCP total number of connections exceeding maximumPoolSize & Connection close queries

### ISSUE THREAD

**Issue by vinaychand** [brettwooldridge/HikariCP#1623]
Hi,

I have 3 different queries.

1)
Could you please help me understand why the total number of connections is exceeding maximumPoolSize with all the default HikariCP config. 

08-07-2020 14:09:48.159 [DEBUG] [HikariPool-1 housekeeper] [] [/]  com.zaxxer.hikari.pool.HikariPool.logPoolState:417 - HikariPool-1 - After cleanup  stats (total=10, active=3, idle=7, waiting=0)
08-07-2020 14:09:48.171 [DEBUG] [HikariPool-1 connection adder] [] [/]  com.zaxxer.hikari.pool.HikariPool.call:730 - HikariPool-1 - Added connection com.mysql.cj.jdbc.ConnectionImpl@5a88bed6
08-07-2020 14:09:48.183 [DEBUG] [HikariPool-1 connection adder] [] [/]  com.zaxxer.hikari.pool.HikariPool.call:730 - HikariPool-1 - Added connection com.mysql.cj.jdbc.ConnectionImpl@1bb5b4ed
08-07-2020 14:10:18.160 [DEBUG] [HikariPool-1 housekeeper] [] [/]  com.zaxxer.hikari.pool.HikariPool.logPoolState:417 - HikariPool-1 - Before cleanup stats (total=12, active=2, idle=10, waiting=0)

2)
Also from our logs, I see two unusual cases when the connections were closed 
     (connection is dead) and (connection was evicted)

2.a) Dead Connections:  The error message recommends consider using a shorter maxLifetime value. In our case the maxLifeTime(default 30mins) is less than MySQL wait_timeout (28800 secs = 8 hours).  Could you explain the possible reasons for failing to validate the connection.

08-07-2020 14:28:51.152 [WARN ] [https-jsse-nio-8443-exec-9] [] [5f05ca0ecd9b0f2bc9500e89c459c81c/c9500e89c459c81c]  com.zaxxer.hikari.pool.PoolBase.isConnectionAlive:179 - HikariPool-2 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@15c6b86c (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.
08-07-2020 14:28:51.153 [DEBUG] [HikariPool-2 connection closer] [] [/]  com.zaxxer.hikari.pool.PoolBase.quietlyCloseConnection:129 - HikariPool-2 - Closing connection com.mysql.cj.jdbc.ConnectionImpl@15c6b86c: (connection is dead)

2.b) Evicted connections: Could you please explain in which cases the connections are  evicted from the pool.

08-07-2020 16:54:25.581 [DEBUG] [HikariPool-1 connection closer] [] [/]  com.zaxxer.hikari.pool.PoolBase.quietlyCloseConnection:129 - HikariPool-1 - Closing connection com.mysql.cj.jdbc.ConnectionImpl@1b72c14f: (connection was evicted)

Thanks!!!

**Comment by brettwooldridge** [comment]
The line numbers in the messages above do not match the current driver version.  Please upgrade.
