### ISSUE TITLE
Hikari to support Kerberos

### ISSUE THREAD

**Issue by ashishnegigithub** [brettwooldridge/HikariCP#1625]
Hi  I Need to quickly find solution of How hikari will support kerberos,  there is already open issue,  i need to use kerberos subject context to conntect backend DB, that is oracle , like below 
  @Override
    public Connection openConnection()
    {
        return Subject.doAs(kerberosAuthentication.getSubject(), (PrivilegedAction<Connection>) () -> {
            try {
                return hikarDataSource.getconnectin //  i need like this. 
            }
            catch (SQLException e) {
                throw new RuntimeException(ee);
            }
        });
    }

Note I can't use other connection pool mechanism, we have to use hikari only.  no other option, does any support here from hikari,. please update us as quickly as possible , .  how to customize hikari logic.  response will be appreciated.

**Comment by brettwooldridge** [comment]
Well, this is old, but I would say wrap a Java proxy around the Oracle datasource, intercept the getConnection(), and set the Kerberos context there before handing it over to HikariCP.
