### ISSUE TITLE
HikariDataSource shutdown unexpectedly

### ISSUE THREAD

**Issue by zhchen-zhchen** [brettwooldridge/HikariCP#1628]
Hi,

I use Hikari to connect my Oracle server and I found my server would shutdown the datasource sometimes, which caused `SQLException` The logs are as follows,

```
thread:SpringContextShutdownHook logger:com.zaxxer.hikari.HikariDataSource message:HikariPool-1 - Shutdown initiated...
```

```
java.sql.SQLException: HikariDataSource HikariDataSource (HikariPool-1) has been closed.
```

```
thread:SpringContextShutdownHook logger:com.zaxxer.hikari.HikariDataSource message:HikariPool-1 - Shutdown completed.
```

It seems that datasource shutdown due to some reasons. Could you provide some information of under what conditions such behaviors will happen?

#### Version
SpringBoot: 2.2.4
exposed: 0.14.1
Hikari: 3.3.1

**Comment by brettwooldridge** [comment]
No idea.  This is coming from outside of HikariCP.

**Comment by bettercallavi** [comment]
getting below error ,no logging info why Shutdown initiated 
hikari.HikariDataSource","message":"TxnMasterDB - Shutdown initiated.
