### ISSUE TITLE
Rapid Recovery wiki: link to SQL Server's SocketTimeout documentation incorrect

### ISSUE THREAD

**Issue by fransflippo** [brettwooldridge/HikariCP#1629]
The "this page" link under the SQL Server heading on https://github.com/brettwooldridge/HikariCP/wiki/Rapid-Recovery has a typo. It should be https://github.com/Microsoft/mssql-jdbc/wiki/SocketTimeout, not https://github.com/Microsoft/mssql-jdbc/wiki/SocketTimout (`SocketTimeout` vs `SocketTimout`).

The current link works, but redirects back to https://github.com/Microsoft/mssql-jdbc/wiki , which is not as useful.

**Comment by quaff** [comment]
Why not submit a PR?

**Comment by fransflippo** [comment]
Would be happy to. But if I fork the project, it doesn't fork the Wiki. How do I submit a PR on a Wiki page? Thanks!

**Comment by fransflippo** [comment]
Doesn't look like GitHub supports PRs on Wikis. But feel free to add this as a remote and merge; I've made the fix there: https://github.com/fransflippo/HikariCP.wiki.git .
