### ISSUE TITLE
Postgres schema gets reset to 'public' after releasing a connection

### ISSUE THREAD

**Issue by shorn** [brettwooldridge/HikariCP#1633]
### Context
HikariCP:3.4.5
postgres-jdbc:42.2.14
spring-boot:2.1.16
jooq:3.13.4

### Symptom
I wanted to change my Jooq configuration to not have to insert schema identifiers in the SQL it generates, so I told Jooq not to do that any more and added the `schema` property to my HikariConfig (I configure using code).

That seemed to work, but then intermittently, I would get postgres "relation ... does not exist" errors.

### Possible root cause
`com.zaxxer.hikari.pool.ProxyConnection.close()` is doing a rollback (because the connection `!isAutoCommit`) which is resetting the postgres `SESSION search_path` (see [PgConnection.setSchema(String)](https://github.com/pgjdbc/pgjdbc/blob/529e5dc3a8f071ad4946daf3bde1422c21a99524/pgjdbc/src/main/java/org/postgresql/jdbc/PgConnection.java#L1626)).
But, as shown below - the `close()` method is not setting the `DIRTY_BIT_SCHEMA`.  It appears the connection search path does not get reset the next time that connection is checked out.

### Evidence
I set a break-point in my IDE on the `delegate.rollback()` line in the `ProxyConnection.close()` method as given below.
Before call to `rollback()`, if I called `PgConnection.getSchema()` it would return my custom schema name, after the call, it returned `public` - so I'm assuming a postgres `rollback` statement also applies to the postgres `session` on the server that the JDBC connection is attached to.
 
com.zaxxer.hikari.pool.ProxyConnection:
```
   public final void close() throws SQLException
   {
      // Closing statements can cause connection eviction, so this must run before the conditional below
      closeStatements();

      if (delegate != ClosedConnection.CLOSED_CONNECTION) {
         leakTask.cancel();

         try {
            if (isCommitStateDirty && !isAutoCommit) {
               delegate.rollback();
               lastAccess = currentTime();
               LOGGER.debug("{} - Executed rollback on connection {} due to dirty commit state on close().", poolEntry.getPoolName(), delegate);
            }

            if (dirtyBits != 0) {
               poolEntry.resetConnectionState(this, dirtyBits);
               lastAccess = currentTime();
            }

            delegate.clearWarnings();
         }
         catch (SQLException e) {
            // when connections are aborted, exceptions are often thrown that should not reach the application
            if (!poolEntry.isMarkedEvicted()) {
               throw checkException(e);
            }
         }
         finally {
            delegate = ClosedConnection.CLOSED_CONNECTION;
            poolEntry.recycle(lastAccess);
         }
      }
   }
```

### Workaround
My current workaround is append the `currentSchema` param to my postgres jdbc url, as in: `jdbc:postgresql://localhost/postgres?currentSchema=api_svc`

I'm thinking I'm going to stick with this workaround since, given the underlying implementation of `PgConnection.setSchema()`, using the Hikari `schema` property results in the extra JDBC `executeUpdate()` to set the search path.

**Comment by brettwooldridge** [comment]
Interesting.  I had no idea that ``setSchema()`` on the driver merely executes ``SESSION search_path`` under the covers -- and further that that is considered state that can be rolled back.  Given that, I believe that your "workaround" is the only reasonable solution without injecting database specific logic into the pool.
