### ISSUE TITLE
HikariProxyResultSet cannot be cast to com.ibm.db2.jcc.DB2ResultSet

### ISSUE THREAD

**Issue by wanggewg** [brettwooldridge/HikariCP#1634]
I tried to cast result set to com.ibm.db2.jcc.DB2ResultSet . I got this error:  java.lang.ClassCastException: com.zaxxer.hikari.pool.HikariProxyResultSet cannot be cast to com.ibm.db2.jcc.DB2ResultSet

db2 server version 11.1
hikarcp version : 3.4.1
db2 driver : db2jcc4.jar 
Bundle-Name: IBM JCC JDBC 4 Driver
Created-By: pwa6470_27sr3fp10-20150708_01 (SR3 FP10) (IBM Corporation)
Version: 4.22.29

sample code : 
public String getStudiesJson( DataSource ds
			) throws Exception {
		
              HikariConfig config = new HikariConfig();
		config.setPoolName(dsName );
		config.setJdbcUrl(databaseUrl );
		config.setUsername(userName);
		config.setPassword(password);
	//	config.setDriverClassName("com.ibm.db2.jcc.DB2Driver");
		config.setDriverClassName("com.ibm.db2.jcc.DB2SimpleDataSource");
		config.setMaximumPoolSize(10);
		config.setRegisterMbeans(true);
  		HikariDataSource dataSource = new HikariDataSource(config); 
		 
		String query = "select * from example_table";
		System.out.println("sql[getCstmrImpctCmprsnRprt]=\n" + query);
		PreparedStatement pstmt = null;
		Connection con = null;
		ResultSet rs = null;
	 
		String jsondoc = null;
		long st = System.nanoTime();	
		
		try {
 
			con = dataSource.getConnection();
			pstmt = con.prepareStatement(query);
			rs = pstmt.executeQuery();
			
			long et = System.nanoTime();
			System.out.println("finish query takes: " + (et-st)/1_000_000);	
			
			DB2JSONResultSet jsonrs = ((DB2ResultSet) rs).toJSONResultSet(); 
			
			jsondoc = jsonrs.toJSONString();  
			jsonrs.close(); 
			
			et = System.nanoTime();
			System.out.println("finish dao takes: " + (et-st)/1_000_000);		
			
		} catch (SQLException sqlEx) {
			sqlEx.printStackTrace();
			throw new Exception("Error :t", sqlEx);
		} finally {
			if(rs!=null) rs.close();
			if(pstmt!=null) pstmt.close();
			if(con!=null) con.close();
 
		}
		System.out.println("jsondoc: " + jsondoc);
		return jsondoc;
	}

**Comment by quaff** [comment]
Please try this:
```java
DB2JSONResultSet jsonrs = rs.unwrap(DB2ResultSet.class).toJSONResultSet(); 
```

**Comment by wanggewg** [comment]
Thanks a lot , That works well.
