### ISSUE TITLE
Question about ConcurrentBag

### ISSUE THREAD

**Issue by hongjhhh** [brettwooldridge/HikariCP#1639]
The threadList cache connection is for improve effective,but if in spring project,spring will create a new thread for each request,so connectoin will get from sharedList(COW) by cas , but cas is low effective in high concurrency environment,and the threadList can't improve effective,looking forward to your reply,thx!

**Comment by brettwooldridge** [comment]
Why on earth would Spring create a new thread for each request, which is hugely expensive, rather than using a thread pool?  I don't believe it.  This sounds like a Spring (mis-)configuration issue.
