### ISSUE TITLE
DB DeadLock Recovery

### ISSUE THREAD

**Issue by malcolm-edgar** [brettwooldridge/HikariCP#164]
Thanks for the great library, very nice work.

I am having an issue with a transactional application which has database deadlock issues, and I want to closeout and remove connections from the pool which may be causing the deadlock.  I don't know the connection causing the issue, however setting a query timeout is helping identify this issue much more quickly.

I am setting the configuration property "maxLifetime", which I hoped would remove these error causing connection. I think however, this connection is being reused to frequently for it to get the opportunity to be purged.  Would this be correct ?  Are the connections obtained from the pool in a random order, or just the first item in the list ?  I could increase the size of the pool if it would help.

The config settings I am using are:

//  HikariCP default configuration:
//   connectionTimeout = 30000 (30 sec)
//   idleTimeout = 600000 (10 mins)
//    maxLifetime = 1800000  (30 mins)
//    leakDetectionThreshold = 0 (disabled)
//    isRecordMetrics = false (disabled)
//
driver = ...
jdbcUrl = ...
username = ...
password = ...
connectionTestQuery = ...
transactionIsolation = TRANSACTION_READ_COMMITTED
minimumIdle = 5
maximumPoolSize = 100
leakDetectionThreshold = 120000

Do you have any suggestions I can use with the Hikari Connection Pool ?

It would be great to have:

* configuration item for specifying the default JDBC Statement queryTimeout - currently I am wrapping the connections to do this

* enable removing closing and removing connections from the pool which have experienced an SQL error. I have tried the HikariDataSource method evictConnection() but this will often throw an IllegalStateException in the ConcurrentBag method remove().

* enable flushing all the connections out of the pool, so the DB can clear the deadlock. In our application, performing a restart resolves these issues, as the DB closed out the connection sessions

regards Malcolm

**Comment by brettwooldridge** [comment]
HikariCP 2.3.0 addresses most of these issues.  However, a configurable ``queryTimeout`` is not currently planned unless we see larger demand for it.
