### ISSUE TITLE
Question: prevent or detect "alter session"?

### ISSUE THREAD

**Issue by nkiesel** [brettwooldridge/HikariCP#1640]
My understanding is that an "alter session" command like `alter session set time_zone='0:00'` - when issued for a connection acquired via hikaricp - will affect all other connections as well.  Is that correct and can I somehow prevent or at least detect this?  

Note: Oracle does not allow to prevent such an "alter session" because anyone who can connect can also issue (most) "alter session" commands.

**Comment by brettwooldridge** [comment]
We're not going to engage in SQL parsing, or even string matching, on every query just to catch this.  In short: don't do that.
