### ISSUE TITLE
Lots of HikariPool-1 connection adder/closer threads

### ISSUE THREAD

**Issue by javadevmtl** [brettwooldridge/HikariCP#1642]
Hi I'm investigating an application that runs slower and slower over time. I'm using Your Kit to monitor the application. 

When the application starts it has 1 thread HikariPool-1 connection adder but as time goes on I have noticed lots of HikariPool-1 connection adder/closer threads created about 80 or so. 

So wondering if this is relevant or not?

I'm using vertx with Hikari 2.7.1 with the below settings.

```
    "provider_class": "io.vertx.ext.jdbc.spi.impl.HikariCPDataSourceProvider",
    "jdbcUrl": "...",
    "username": "...",
    "password": "...",
    "connectionTestQuery": "select 1;",
    "maximumPoolSize": 24
```
<img width="1389" alt="Screen Shot 2020-08-20 at 3 32 53 PM" src="https://user-images.githubusercontent.com/2964042/90816547-71f7fb80-e2fa-11ea-895c-cd0a16b75fc5.png">

**Comment by brettwooldridge** [comment]
v2.7.1?  Let's party like it's 2017 again! 🥳 

Upgrade.

**Comment by Zhanghailin1995** [comment]
the latest versionv3.4.5 also have this problem。After the program has been running for some time,lots of HikariPool-1 connection adder/closer threads created
