### ISSUE TITLE
Connection is not available on multiple Threads

### ISSUE THREAD

**Issue by rodriggoarantes** [brettwooldridge/HikariCP#1643]
I have a scheduler with jobs starting multiple threads on same time and before full the pool, the application received of hikari the message error "Connection is not available, request timed out after 5001ms."

Example, on a pool of 250 connections, 250 threads on the same time, the hikari open only 100 conections (active), and remaining 150 connection waiting.

Is there anything I can do to add a delay between hikari connections, or something to identify why the connections are waiting?

Hikari config:
spring.datasource.hikari.connectionTimeout=30000
spring.datasource.hikari.maximumPoolSize=250
spring.datasource.hikari.minimumIdle=20
spring.datasource.hikari.idleTimeout=20000
spring.datasource.hikari.poolName=SpringBootJdbcHikariCP
spring.datasource.hikari.initialization-fail-timeout=-1
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url= jdbc:oracle:thin:@//localhost:1521/local

Code Example: https://github.com/rodriggoarantes/java-training/tree/develop/connections

**Comment by lawrencewu** [comment]
Try to set spring.datasource.hikari.minimumIdle=250, the same value as spring.datasource.hikari.maximumPoolSize.

**Comment by rodriggoarantes** [comment]
I had tried, in this db has a delay in filling the pool, leading to believe in failure in the database.
I had to increase the connectionTimeout enough (8 minutes), to be able to fill the pool without fail

**Comment by brettwooldridge** [comment]
On what planet is 250 connections sane?  Does your database server have 128 CPU cores, not including hyperthreading?  [About Pool Sizing](https://github.com/brettwooldridge/HikariCP/wiki/About-Pool-Sizing).
