### ISSUE TITLE
Hikari 2.5.1..the minimul idle count is ignored when trying to refill the running pool amids db connection issues 

### ISSUE THREAD

**Issue by vallimayil** [brettwooldridge/HikariCP#1646]
hi Team

 We are using sybase and hikari 2.5.1 for our spring boot application in cloud.

  Its all fine everything is normal..but when there are issues like db unavailability or db account being locked, we see that our minimum idle count is not honoured.

The number of background threads to get a connection increased, specifically one thread between every 10 seconds.

And once the db becomes available or post db account unlock the number of connections get to a count equivalent to number of threads

However post creation in the next hikari house keeping thread clean up cycle the connections are brought back to a proper run.

But this intermediary or momentary spike in connection at times create issue as our connection pool is quiet huge.

Are we missing anything here?We thought the connectionTimeout is meant to fix this, but looks like it only updates the client from teh connection pool front.

Any advice would be much appreciated

**Comment by vallimayil** [comment]
we did tried the setlogin timeout with the hikari datasource but it doesnt seem to be honoured and the connection spikes till the maximumPoolSize

**Comment by vallimayil** [comment]
The expectation for us is post the DB  issue gets sorted the pool should be up with the minimum idle connection

**Comment by brettwooldridge** [comment]
"We are using sybase and hikari 2.5.1..."  Why on earth would you be running v2.5.1?  Do you have any idea how many dozens and dozens of issues have been fixed since then?  It's not an error unless it happens on the latest release, that is my support policy.
