### ISSUE TITLE
One more sleep process in database than before closing the connection after MaxLifeTime

### ISSUE THREAD

**Issue by lorvivien** [brettwooldridge/HikariCP#1649]
I'm using Spring Boot with Hikari. Please find my configuration below

**Environment**
HikariCP version: 2.7.9
JDK version     : 1.8
Database        : MySQL
Driver version  : 5.1.46

**Hikari**
connection-timeout: 15000
maximum-pool-size: 50
transaction-isolation: "TRANSACTION_READ_COMMITTED"
minimum-idle: 1

After MaxLifeTime, Hikari seems to close the connection :
01-09-2020 08:47:44.988 DEBUG com.zaxxer.hikari.pool.HikariPool.logPoolState - HikariPool-1 - After cleanup  stats (total=1, active=0, idle=1, waiting=0)
01-09-2020 08:48:07.228 DEBUG com.zaxxer.hikari.pool.PoolBase.quietlyCloseConnection - HikariPool-1 - Closing connection com.mysql.jdbc.JDBC4Connection@48c74c4f: (connection has passed maxLifetime)
01-09-2020 08:48:07.271 DEBUG com.zaxxer.hikari.pool.HikariPool.call - HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@1fb60b9a
01-09-2020 08:48:14.992 DEBUG com.zaxxer.hikari.pool.HikariPool.logPoolState - HikariPool-1 - Before cleanup stats (total=1, active=0, idle=1, waiting=0)
But when I look at the database, It's not the case. When I run the query **select * from INFORMATION_SCHEMA.PROCESSLIST where db = 'xxx';**, I have one more sleep process than before closing the connection.

What should I do to fix this problem?

**Comment by brettwooldridge** [comment]
v2.7.9 is older than my grandmother.  Try a newer version.
