### ISSUE TITLE
What is recommended Connection pool size HikariCP?

### ISSUE THREAD

**Issue by eugkhp** [brettwooldridge/HikariCP#1652]
As written in HikariCP docs the formula for counting connection pool size is connections = ((core_count * 2) + effective_spindle_count). But which core count is this: my app server or database server? For example: my is app running on 2 CPUs, but database is running on 16 CPUs.

**Comment by eugkhp** [comment]
Find out - server CPUs

**Comment by kamalhm** [comment]
what do you mean by server cpu? database CPU i assume?

**Comment by eugkhp** [comment]
Yeah, database cpu

**Comment by brettwooldridge** [comment]
Actually, whichever one is smaller. If your app server had 16 CPU’s and your db server had 2 CPU’s, and you used 16 as the value, that formula will result in way too many connections on which SQL can execute, overloading the db server.

**Comment by eugkhp** [comment]
@brettwooldridge Oh, thanks. But what if other way around? If my database has 16 CPUs and app only has 2? I thought there is a benefit of caching more connections on client side because it's take more time to establish new one. But now I have some doubts.

**Comment by kamalhm** [comment]
While we're at it, can you point me what I need to do to reproduce that benchmark on oracle performance video? @brettwooldridge I wish I could replicate it and somehow have a living proof of a project that everyone else can do to benchmark their connection pool size on their own server configuration
