### ISSUE TITLE
Cannot acquire connection from data source 

### ISSUE THREAD

**Issue by hermitcai** [brettwooldridge/HikariCP#1653]
![image](https://user-images.githubusercontent.com/45086633/92722343-05709980-f39a-11ea-9578-3d56138f944e.png)
total=89, active=75, idle=14, waiting=0
There are 14 idle connections, why can’t these 14 be reused?

**Comment by sumitchopra16** [comment]
Did you find any reason for this ? I also got the same issue

**Comment by brettwooldridge** [comment]
That exception was logged by the Connection Adder thread and did not prevent one of the idle connections from being used.  This exception would appear in your logs, but never reach your application.  I suspect that your maximum connections is set to something like 90, and if ``minimumIdle`` is not configured then minimum idle is also 90. So as soon as your pool dropped below 90, and therefore below ``minimumIdle``, then HikariCP attempted to add a connection.

Why did the socket timeout trying to obtain a connection?  Likely your database was too busy to service the request in a timely fashion.  90 connections, and 74 active, sure smells to me like a lot of inefficent, long running, queries.

Either way, this is not a problem with HikariCP.
