### ISSUE TITLE
Variable Maximum connection pool size

### ISSUE THREAD

**Issue by SriChetan** [brettwooldridge/HikariCP#1654]
JDK: 1.8
HirakiCP: HirakiCP-Java8: 3.4.6
Spring boot project

Our requirement is to have a variable maximum connection pool size. At runtime, we should be able to increment or decrement the maximum connection pool size. 
Please help me to understand how I can achieve this functionality.

Thanks in advance.

**Comment by norberto-enomoto** [comment]
Based on your requirements, you will need to use JMX protocol to connect to the MBean for management:
https://github.com/brettwooldridge/HikariCP/wiki/MBean-(JMX)-Monitoring-and-Management
https://java-source.net/open-source/jmx#:~:text=jManage%20is%20a%20open%20source%2C%20web%20and%20command-line,features%20like%20Alerts%2C%20Graphs%2C%20Security%2C%20SNMP%20support%2C%20etc.
