### ISSUE TITLE
[Docs] Please note hibernate-hikaricp library in wiki Hibernate4

### ISSUE THREAD

**Issue by DevDengChao** [brettwooldridge/HikariCP#1658]
I was not able to navigate to `org.hibernate.hikaricp.internal.HikariCPConnectionProvider` in IDEA until the moment I realized I might have missing some packages.

So please add 
```xml
<dependency>
    <groupId>org.hibernate</groupId>
    <artifactId>hibernate-hikaricp</artifactId>
    <version>${HIBERNATE_VERSION}</version>
</dependency>
```
to https://github.com/brettwooldridge/HikariCP/wiki/Hibernate4

**Comment by brettwooldridge** [comment]
Hibernate is not a dependency of HikariCP.  Many users do not use Hibernate.
