### ISSUE TITLE
HikariPool connection doesn't shutdown on application termination

### ISSUE THREAD

**Issue by KooKilluminated** [brettwooldridge/HikariCP#1666]
I am new to spring boot framework and I use default hikaricp pool  to make database connection.  I am able to connect to the database successfully and my application works fine. But when I shutdown the application, HikariPool doesn't shutdown. 

Also HikariPool is being created for each request I make... And the old pool created doesn't get suspended..

Also I need to know the impact of not initiating the shutdown of HikariPool on shutdown of application.

**Comment by KooKilluminated** [comment]
I use below dependency in my code

`<dependency>
<groupId>org.springframework.boot</groupId>
<artifactId>spring-boot-strater-jdbc</artifactId>
<version>2.3.1.RELEASE</version>
</dependency>`

**Comment by KooKilluminated** [comment]
Also HikariPool is being created for each request I make.. please suggest if I have to apply any changes

**Comment by brettwooldridge** [comment]
This is question for stackoverflow.
