### ISSUE TITLE
SLF4J: Class path contains multiple SLF4J bindings.

### ISSUE THREAD

**Issue by imyuyu** [brettwooldridge/HikariCP#1683]
Environment

```
HikariCP version: 3.2.0
JDK version     : 1.8.0_202-b08
Database        : PostgreSQL
```

I used `HikariCP` to configure JNDI data source in Tomcat. Now I want to see the log of data source. I know that `HikariCP` uses `slf4j`, so I added `slf4j-jdk14-1.7.9.jar` in `Tomcat/lib`.

Now my application uses `slf4j` + `logback`. When the application is started, the console will give a warning of `slf4j`:

```
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/xxx/WEB-INF/lib/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/apache-tomcat-9.0.36/lib/slf4j-jdk14-1.7.9.jar!/org/slf4j/impl/StaticLoggerBinder.class]
```

It doesn't affect use, but it always feels bad. Is there any good solution?

**Comment by imyuyu** [comment]
Maybe it's not a problem.

**Comment by THyyy** [comment]
You can exclude logback-classic-1.2.3.jar to fix it.

**Comment by imyuyu** [comment]
> You can exclude logback-classic-1.2.3.jar to fix it.

hi Thyyy:
    Thanks!  I'm afraid I can't because my application uses logback as the implementation of the log.

**Comment by lfbayer** [comment]
Marking as closed. This is not a HikariCP issue.
