### ISSUE TITLE
connectionTimeout also used as query timeout

### ISSUE THREAD

**Issue by timohirt** [brettwooldridge/HikariCP#170]
The documentation specifies the `connectionTimout` as follows:

> controls the maximum number of milliseconds that a client ... will wait for a connection from the pool. If this time is exceeded without a connection becoming available

At least in the [`HikariPool`](https://github.com/brettwooldridge/HikariCP/blob/dev/hikaricp-java6/src/main/java/com/zaxxer/hikari/pool/HikariPool.java#L492) this timeout is also used as query timeout. Is this intentional? 

After deploying HikariCP we experienced some str<nge exception from the Postgres DB. The error messages was link `Cancel statement due to user request`. After looking into that I found that one reason could be a query timed out. Couldn't find anything in out code and then when searching the HikariCP source I stumbled upon the `setQueryTimeout`. Setting the timeout to 10 seconds fixed the problem and we don't see have exceptions anymore.

EDIT: I would either expect the query timeout to be configurable separately or the documentation should be more clear about that the `connectionTimeout` is also used as query timeout.

**Comment by brettwooldridge** [comment]
What version are you running?  The 2.2.5 code looks like this:

**Comment by kgarn** [comment]
Thanks for the quick reply.  I looked through the H2 code and I think you are correct.  It looks like H2 is applying the setQueryTimeout() value to the connection and not limiting it to the statement.
