### ISSUE TITLE
Spring Cloud refresh configuration triggers the closing of the HikariDataSource Pool

### ISSUE THREAD

**Issue by binbin0325** [brettwooldridge/HikariCP#1701]
![image](https://user-images.githubusercontent.com/28588342/100312558-9f390180-2fed-11eb-981c-90a72d035088.png)
The Spring Cloud configuration update triggers the HikariDataSource Close ().This may result in an existing disconnect affecting business.

**Comment by nunnrlc** [comment]
Spring Cloud project have HikariDataSource excluded from config refresh events in the current version, see https://docs.spring.io/spring-cloud-commons/docs/current/reference/html/#refresh-scope

If you update your Spring Cloud version to the latest, the issue should be gone.

If you have the latest Spring Cloud version already, make sure to not override the default exclusion in your Spring config. The option is named `spring.cloud.refresh.never-refreshable`.

Just to note for anyone who does need to change HikariCP options during runtime: Some can be modified via JMX, see https://github.com/brettwooldridge/HikariCP/wiki/MBean-(JMX)-Monitoring-and-Management
