### ISSUE TITLE
Make HikariConfig able to retrieve passwords dynamically from a password supplier for Java 6

### ISSUE THREAD

**Issue by ankitpai** [brettwooldridge/HikariCP#1703]
Hi @brettwooldridge,

Can we get a latest build of HikariCP-java6 with latest fixes like the password supplier for IAM authentication with AWS RDS.

**Comment by nunnrlc** [comment]
The Java 6 version of HikariCP has not had a release since February 2016, almost 5 years! 

Even Oracle's extended support for Java 6 ended 2018.

The effort to backport code for an EOL platform is not sensible, so I don't think it will happen. Sorry.

**Comment by ankitpai** [comment]
Thanks for the update.
