### ISSUE TITLE
How to simulate flaky/slow connections with HikariCP?

### ISSUE THREAD

**Issue by AuroraLS3** [brettwooldridge/HikariCP#1724]
Hi.

I have a bug in my program that occurs when the MySQL suddenly stops working for a few seconds. This makes the issue a bit difficult to reproduce, so I would like to make a test that simulates the flaky connections to trigger the bug on in a unit test.

The bug occurs when [Connection#isValid](https://docs.oracle.com/javase/8/docs/api/java/sql/Connection.html#isValid-int-) returns `false`

I have a mock Connection that returns `false` for that method call, but the issue is getting this connection inside the connection pool.
How would I go about placing the connection inside the pool?  
Is there some other way to simulate flaky connections?

**Comment by brettwooldridge** [comment]
This is a good starting point: https://gist.github.com/brettwooldridge/7564827e45d67e1dc8dd
