### ISSUE TITLE
HikariCP 4 fails to be resolved in Gradle

### ISSUE THREAD

**Issue by zml2008** [brettwooldridge/HikariCP#1725]
It seems like HikariCP 4 is not properly resolved due to a missing `slf4j.version` property.

This has come up from a [renovate PR](https://github.com/PEXPlugins/PermissionsEx/pull/3165) bumping the HikariCP version to 4.0.0.

The relevant line in the build log is ([GH Actions log link](https://github.com/PEXPlugins/PermissionsEx/pull/3165/checks?check_run_id=1757674986#step:5:315)):

```
 * What went wrong:
Execution failed for task ':impl-blocks:hikari-config:compileJava'.
> Could not resolve all files for configuration ':impl-blocks:hikari-config:compileClasspath'.
   > Could not find org.slf4j:slf4j-api:${slf4j.version}.
     Required by:
         project :impl-blocks:hikari-config > com.zaxxer:HikariCP:4.0.0
```

This might be a limitation due to Gradle's pom resolution not supporting some of the more niche features of Maven's artifact descriptor (since it appears the `slf4j.version` property is defined only in profiles in the pom) -- unfortunately I don't have any maven projects left to test in.

**Comment by dharrigan** [comment]
Hi,

This is happening too when pulling in the updated dependency with `deps.edn` (used by `clj` to resolve dependencies within a Clojure project).

Switching to HikariCP `4.0.0` now results in:

```
user=> SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#noProviders for further details.
SLF4J: Class path contains SLF4J bindings targeting slf4j-api versions prior to 1.8.
SLF4J: Ignoring binding found at [jar:file:/home/david/.m2/repository/ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#ignoredBindings for an explanation.
```

Reverting back to HikariCP `3.4.5`, log messages are once again echoed out.

**Comment by brettwooldridge** [comment]
@dharrigan @zml2008 Fix coming momentarily.

**Comment by brettwooldridge** [comment]
Fixed, release publishing in ~30min.
