### ISSUE TITLE
Connection pool remained when tomcat restarted

### ISSUE THREAD

**Issue by CharlesNKim** [brettwooldridge/HikariCP#1740]
When i modify and save my code at Eclipse, codes are complied automatically and my tomcat is restarted also.

I usually use 15 of hikariCP data sources. But after that Auto Restart, my oracle connection's number increased double!

Below is session check oracle query
select count(*) from v$session where machine = 'MyMachineHostName';

I just tried two of hikariCP's config(maxlifetime, idleTimeout), but also connection isn't decreased.

Obviously turning off auto compile setting is the fast way solving the problem. but if i don't use that setting, it is so hard to check the result(back-end and front-end both!)

There are Any Special settings for me?

**Comment by Chris2018998** [comment]
Add a 'ServletContextListener' to your application

```
public class ServletContextLTest implements ServletContextListener{ 
     public void contextInitialized(ServletContextEvent sce) { }

     public void contextDestroyed(ServletContextEvent sce) { dataSouruce.close();  }
}

```

**Comment by CharlesNKim** [comment]
Hello Chris2018998

DataSource have not the method "close".

as your support, i add the ServletContextListener and find DataSource like below

`	@Autowired
	List<DataSource> datasources;
`

and then i can't access "close()" method..

how do i call "close" method?

**Comment by CharlesNKim** [comment]
hello!

i use below code but it is not work..

```
public class FWServletContextListener implements ServletContextListener {
	@Autowired
	List<HikariDataSource> datasources;
	
	@Override
	public void contextInitialized(ServletContextEvent sce) {
		
		
	}
	@Override
	public void contextDestroyed(ServletContextEvent sce) {
		for (int i = 0; i < datasources.size(); i++) {
			HikariDataSource ds = (HikariDataSource) datasources.get(i);
			ds.close(); 
		}
	}
}
```

**Comment by Chris2018998** [comment]
Here a tomcat hot deploy example(BeeCP),you can change it to HikariCP.

https://github.com/Chris2018998/BeeCP/blob/master/doc/example/TomcatRedeployTest.zip

**Comment by Chris2018998** [comment]
**1: Applcation startup**
![image](https://user-images.githubusercontent.com/32663325/114425891-16151680-9bec-11eb-8753-192518cb2cd9.png)

**2: Applcation  redeploy(when recompile java source )**
![image](https://user-images.githubusercontent.com/32663325/114426040-3e047a00-9bec-11eb-8178-d32d6ad1735f.png)

**3: DB connection show**
![image](https://user-images.githubusercontent.com/32663325/114426223-6ee4af00-9bec-11eb-8023-3a78991bbbd7.png)
