### ISSUE TITLE
Is there have the multiple databases handle by HikariCP?

### ISSUE THREAD

**Issue by xu20160924** [brettwooldridge/HikariCP#1747]
I want to use HikariCP to connects the database in my application. But here I have many databases in my application to be used. So I want to know whether there have some way or capsulation of code to handle multiple databases that can preserve multiple connection of databases in some time, instead of creating the DataSource repeatedly when which DataBase is needed. I tend to do that because I don't want to increase the new costs when change to connect database frequently.

**Comment by DarekDan** [comment]
This is not an issue IMHO. Should be closed. Your question belongs on StackOverflow. Having said that, you might want to create a Map<String,HikariDataSource> and spin them up at startup or as they are requested.
