### ISSUE TITLE
Smart(er) connection validation

### ISSUE THREAD

**Issue by pbarsotti-glovo** [brettwooldridge/HikariCP#1748]
There are some circumstances where we need a way to do a more complex validation than running a SELECT 1 to determine if a connection is still valid. For example, if you are working with something like Aurora or RDS and you do a failover, you may end having connections from a DS meant for R/W pointing to a DB node which just became readonly.

Allowing the execution of any arbitrary piece of code during this phase would help a lot to support this kind of customizations.

@brettwooldridge do you think that might be an interesting addition? I can contribute with a PR if you are OK to move forward.

Thanks!

**Comment by romapi** [comment]
@pbarsotti-glovo We are solving a sort of same issue with our active passive Postgres instances, replicated with londiste. Both instances are always up and ready to accept connections. Credentials are also identical. The only difference is that the replica is in ReadOnly mode. 

In a case of a failover we repoint the database DNS Alias record to ReadWrite database instance name. In this scenario, purely relying on a JDBC4 isValid() method might end up HikariCP to share out ReadOnly database connections to the application. Meaning that the application will get an exception when trying to write to the database.

The only option I see is to use connectionTestQuery with some sort of a basic and, performance wise, innocent Write query. 
This way we are forcing HikariCP to check every connection's ability to write to database just before giving that connection to the application.

**Comment by brettwooldridge** [comment]
@romapi @pbarsotti-glovo My suggestion would be to strive for a more coordinated approach to failover.  I think the DNS approach is correct, provided that DNS caching is handled correctly.  See [Rapid Recovery](https://github.com/brettwooldridge/HikariCP/wiki/Rapid-Recovery).

The coordination should extend to eviction from the pool either via the HikariDataSource API, or the JMX bean.  Note, even if you do not have JMX bean registration enabled, you can call ``getHikariPoolMXBean()`` on the ``HikariDataSource`` programatically and invoke on that instance.

The pattern would be:
- (rely on ``isValid()`` semantics)
- Invoke ``suspendPool()`` on ``HikariPoolMXBean``
- Update DNS to repoint to the R/W database
- Invoke ``softEvictConnections()`` on ``HikariPoolMXBean``
- Invoke ``resumePool()`` on ``HikariPoolMXBean``
