### ISSUE TITLE
First getConnection spend much time

### ISSUE THREAD

**Issue by raizoor** [brettwooldridge/HikariCP#1758]
Hi team,

I have a java springboot API running into a Kubernetes pods, that have an elevated requests per second. Using dynatrace introspection, I can see  getConnection cost between 1s and 10s **when a scale up a new POD**. But before some slowless seconds, my requisitions are finished in 40ms (median). 
My configurations:

- Java 11;
- Springboot 2.1.7;
- ojdbc8:12.2.0.1;
- Hikari configurations:
   -  driver-class-name: oracle.jdbc.OracleDriver
      hikari:
        minimum-idle: 3
        maximum-pool-size: 10
        connection-timeout: 8000
        idle-timeout: 30000
        implicitCachingEnabled: true
        maxStatements: 250
        max-lifetime: 0
- Expected total volume: 110 tps (6600 requests/min);
- Plataform: Kubernetes (microsservices);

Here, have an dynatrace evidence:
![hikari](https://user-images.githubusercontent.com/44624093/112881439-0cdf6200-90a2-11eb-8fba-bf3379e02b29.png)

Obs: I already have make a warm up with "fake" querys, before java startup.

Here, you can see cleary when a new pod scale up.
![image](https://user-images.githubusercontent.com/44624093/112882628-917eb000-90a3-11eb-97f9-09a765a7a2ad.png)

Anyone can help me decrease or at least understand this initial time?

Thank you !!

**Comment by brettwooldridge** [comment]
@raizoor With respect to the graph, what exactly is being measured? Response times for the new pod? Response times as measured from the front end?

When a new pod comes online, clearly there is a startup time, what is the trigger that says the pod is alive and ready to accept requests?

**Comment by raizoor** [comment]
@brettwooldridge The graph is about time to response to the all test, no only my new pods. It hit directly on backend (all in intranet).

Nowadays, we use the default spring actuator, so Kubernetes stay hit then until it response an 200 to consider " a live pod".
Basecly, when Java says "i'm up", Kubernetes send traffic to this pod too.

**Comment by brettwooldridge** [comment]
Set the system property ``com.zaxxer.hikari.blockUntilFilled=true``.
