### ISSUE TITLE
Is there a generic way to use HikariCP as a Generic Pool, like DBCP2?

### ISSUE THREAD

**Issue by guilt** [brettwooldridge/HikariCP#1769]
Hi,

I looked at `PoolBase` and I was wondering if there was a way we could use a minimal version of this code, so we
could try repurposing it in other projects, such as Jedis* - which uses DBCP2. Hikari certainly has better metrics support and
good instrumentability (JMXBean) so I was wondering if there was a way to do this.

Now, I understand this project is JDBC specific, but since I've used DBCP2 before, I was looking for a better pool replacement.

Any pointers/insights would be appreciated.

**Comment by brettwooldridge** [comment]
@guilt Sorry, not possible. Check out the StormPot project.
