### ISSUE TITLE
Avoid executing ROLLBACK() when no transaction is active

### ISSUE THREAD

**Issue by grypyrg** [brettwooldridge/HikariCP#177]
It would be good if HikariCP would not do a rollback() when there's no active transaction. In my test, the last executed statement was 'commit'. in MySQL, doing SET also does not start a transaction (even BEGIN doesn't).

Example:

```
SET autocommit=0;
select * from employees 
            where emp_no = 20000;
commit;
rollback; <<<< hikariCP executes this, but really should not.
```

**Comment by megaurav88** [comment]
@brettwooldridge  I didn't get any big difference between hikaricp & dbcp2. Kindly can you let me know how to get better performance 
jdk1.8
mysql  Ver 14.14 Distrib 5.6.27,

HikariPool-0 - configuration:
allowPoolSuspension.............false
autoCommit......................false
catalog.........................
connectionInitSql...............
connectionTestQuery.............
connectionTimeout...............30000
dataSource......................
dataSourceClassName.............com.mysql.jdbc.jdbc2.optional.MysqlDataSource
dataSourceJNDI..................
dataSourceProperties............{user=root, password=<masked>, url=jdbc:mysql://localhost:3306/db, prepStmtCacheSqlLimit=250, cachePrepStmts=true, prepStmtCacheSize=2048}
driverClassName.................
healthCheckProperties...........{}
healthCheckRegistry.............
idleTimeout.....................600000
initializationFailFast..........false
isolateInternalQueries..........false
jdbc4ConnectionTest.............false
jdbcUrl.........................
leakDetectionThreshold..........0
maxLifetime.....................1800000
maximumPoolSize.................100
metricRegistry..................
metricsTrackerFactory...........
minimumIdle.....................10
password........................<masked>
poolName........................HikariPool-0
readOnly........................false
registerMbeans..................false
scheduledExecutorService........
threadFactory...................
transactionIsolation............
username........................
validationTimeout...............5000
  
stats: 

HikariCP Performance 
                    Query/Connection -----------> 
Connection         | 100 | 10K | 100K 
                   | 1     |   73 | 843 | 6186
                   | 10   | 68 | 2607 | 25064
                   | 100  | 350 | 21777 | 223175 | 
DBCP Performance
                                  Query/Connection -----------> 
               Connection       | 100 | 10K | 100K 
                             | 1        |  274 | 881 | 6560
                             | 10      | 87 | 2811 | 24465
                             | 100    | 317 | 22945 | 229194 |
