### ISSUE TITLE
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after statement closed.

### ISSUE THREAD

**Issue by xiaolianghu** [brettwooldridge/HikariCP#1770]
Hi, great team!

The error stack is as follows
![image](https://user-images.githubusercontent.com/20347953/116426872-1234f580-a876-11eb-9219-fdb759ce5e20.png)

The HikariCP configuration information is as follows
![image](https://user-images.githubusercontent.com/20347953/116426896-16f9a980-a876-11eb-8c79-1a74d2d30472.png)

The mysql configuration is as follows
![image](https://user-images.githubusercontent.com/20347953/116427701-d64e6000-a876-11eb-92d9-175e594adfb6.png)

Version information
HikariCP 4.0.3
mysql-connector-java 5.1.29
Java 8
mysql 5.7

Where's the problem? Thanks！

**Comment by xiaolianghu** [comment]
This is a problem with running at 2 a.m！

**Comment by xiaolianghu** [comment]
@brettwooldridge

**Comment by brettwooldridge** [comment]
I can't tell you where the problem in you code is. This error only occurs when code has already called ``close()`` on the Connection object. I don't have a good recommendation for how to trace that. It may have to do with Hibernate session management. I recommend asking on Stackoverflow with the tag #hibernate.
