### ISSUE TITLE
Hikari Datasource Open Connection more than maximum pool size limit

### ISSUE THREAD

**Issue by BilgehanYildiz** [brettwooldridge/HikariCP#1773]
Hi I use spring 2.4
and hikari datasource for my jpa queries (version 3.4.5).My problem is I set my datasource maximum pool size property.Even though I set maximum pool size,I see more connection than my maximum poolsize at oracle.At this time when I checked my spring logs I seems connection limit is equal my maximumconnection pool size Is it possible to hikari datasource can open more connection than my maximum poolsize limit?

In my code side I set maximum connection like that

HikariDataSource dataSource = new HikariDataSource();
 dataSource.setMaximumPoolSize(5)

My Oracle Query(I see 7 connections at oracle)
Select * from v$session where where username='xxxxx'

My spring Log(I see 5 connections)
[HikariPool-3 housekeeper] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-3 - Pool stats (total=5, active=0, idle=5, waiting=0)

**Comment by BilgehanYildiz** [comment]
Hi,as I understand in my logs,my problem is hikaridatasource open too many hikaripool for that reason I see too much connection.But I dont understand root cause.If hikari open new pool,is it destroy old ones?Each pool seems under max pool but there are a lot of pool,I have only one datasource

03:34:14.572 [HikariPool-7 connection adder] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-7 - Added connection oracle.jdbc.driver.T4CConnection@47d5eab9
03:34:15.752 [HikariPool-18 housekeeper] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-18 - Pool stats (total=4, active=1, idle=3, waiting=0)
03:34:15.752 [HikariPool-18 housekeeper] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-18 - Fill pool skipped, pool is at sufficient level.
03:34:17.166 [HikariPool-19 housekeeper] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-19 - Pool stats (total=4, active=1, idle=3, waiting=0)

**Comment by Linzyoo** [comment]
It seems you create many HikariPool instances with the the setting "setMaximumPoolSize(5)".  Actually, if you just want to one Datasource Pool, you just need create one HikariDataSource instance, and use this everywhere.

**Comment by BilgehanYildiz** [comment]
you are right.In code there a bug in one case and create datasource each time
