### ISSUE TITLE
Is there a way to write code before and after statement.executeQuery(), like the Tomcat JDBC Interceptor?

### ISSUE THREAD

**Issue by nickevin** [brettwooldridge/HikariCP#1774]
We are using an internal monitoring system ([CAT](https://github.com/dianping/cat)) and need to send data in real time.

Is there a way to write code before and after ```statement.executeQuery()```, like the Tomcat JDBC Interceptor?

```
try (Connection connection = datasource.getConnection();
             PreparedStatement statement = connection.prepareStatement("select count(*) from test")
        ) {

           // before: my code
            ResultSet resultSet = statement.executeQuery();
           // after: my code

            resultSet.next();
            log.info("{}", resultSet.getInt(1));
        }
```

**Comment by brettwooldridge** [comment]
@nickevin You can investigate various ways to intercept method invocations, like ``executeQuery()``, to inject your own behaviors by looking at [these patterns](https://gist.github.com/brettwooldridge/dfd21934416fc2a3c865).
