### ISSUE TITLE
How to override default QueryTimeout from Springboot 2 application

### ISSUE THREAD

**Issue by mantushakti** [brettwooldridge/HikariCP#1776]
Hi,
I am using Spring boot and use Hikari data source by default provided by Springboot. 
My requirement is when a query runs more than  specific time i want the database to throw some timeout exception.

I am using Spring Jdbc template to connect to DB2 database using Hikkari CP, but it's not getting timeout though the query took long time.

I use to set timeout in Jdbc template and also @Transaction timeout but it's not overriding the query timeout in Hikari pool.
By default the querytimeout in Hikari pool is set to -1, it means it won't timeout.

Is there any way i can able to override the query timeout in Springboot using application.properties or any other mean ?
If yes, can i able to set query timeout in Transaction level instead of application level.

Please share the solution.

**Comment by brettwooldridge** [comment]
@mantushakti This is a question for Spring. Check stackoverflow or the Spring discord server. One thing you can investigate is setting a global DB2 timeout, for example ``blockingReadConnectionTimeout ``.  See all properties [here](https://www.ibm.com/docs/en/db2/9.7?topic=pdsdjs-common-data-server-driver-jdbc-sqlj-properties-all-database-products)

**Comment by darioseidl** [comment]
I was also wondering whether Hikari had an option for that until I realized Hikari is only responsible for the connections while Spring/JPA/Hibernate are responsible for the transactions.

For anyone else who happens to look here: in Spring Boot 2.x this can be set globally with the property `spring.transaction.default-timeout`, or for a single transaction with `@Transactional(timeout = seconds)`.
