### ISSUE TITLE
Hikari pool connection elided,and open new pools

### ISSUE THREAD

**Issue by BilgehanYildiz** [brettwooldridge/HikariCP#1779]
I have a spring boot(2.4) applicationUnder long running jpa transactions ,I see a lot connection more than my maximum pool size ,when I checked my logs,I see connection elided,and after than new HikariPools 2-3-4 etc... are opened.
I tried hikari 4.0.2 version but still same issue.In this scenario what is the meaning of giving maximum pool size(Each pools seems my maximul pool size but total connection count is more than my limit).Is there any configuration to limit opening pool counts?
Regards

HikariPool-1 - Add connection elided, waiting 3, queue 5

17:54:56.894 [restartedMain] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Added connection oracle.jdbc.driver.T4CConnection@4c6d3cfb
17:54:56.999 [HikariPool-1 housekeeper] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Pool stats (total=1, active=0, idle=1, waiting=0)
17:54:57.669 [HikariPool-1 connection adder] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Added connection oracle.jdbc.driver.T4CConnection@190a0b35
17:54:58.314 [HikariPool-1 connection adder] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Added connection oracle.jdbc.driver.T4CConnection@69a59932
17:54:58.314 [HikariPool-1 connection adder] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - After adding stats (total=3, active=0, idle=3, waiting=0)
17:56:57.005 [HikariPool-1 housekeeper] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Pool stats (total=5, active=0, idle=5, waiting=0)
17:56:57.005 [HikariPool-1 housekeeper] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Fill pool skipped, pool is at sufficient level.
17:57:27.006 [HikariPool-1 housekeeper] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Pool stats (total=5, active=0, idle=5, waiting=0)
17:57:27.006 [HikariPool-1 housekeeper] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Fill pool skipped, pool is at sufficient level.
18:15:03.114 [http-nio-8085-exec-2] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Add connection elided, waiting 4, queue 5
18:15:03.126 [http-nio-8085-exec-17] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Add connection elided, waiting 4, queue 5
18:15:03.130 [http-nio-8085-exec-18] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Add connection elided, waiting 3, queue 5
18:15:03.248 [http-nio-8085-exec-11] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Add connection elided, waiting 3, queue 5
18:15:03.254 [http-nio-8085-exec-8] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Add connection elided, waiting 3, queue 5
18:15:03.288 [http-nio-8085-exec-17] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Add connection elided, waiting 3, queue 5
18:15:03.289 [http-nio-8085-exec-8] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Add connection elided, waiting 2, queue 5
18:15:03.291 [http-nio-8085-exec-11] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Add connection elided, waiting 3, queue 5
18:15:03.326 [http-nio-8085-exec-8] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Add connection 
18:15:03.391 [http-nio-8085-exec-12] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-2 - Added connection oracle.jdbc.driver.T4CConnection@4f5ab95d
18:15:03.538 [HikariPool-2 housekeeper] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-2 - Pool stats (total=1, active=1, idle=0, waiting=1)
18:15:03.938 [http-nio-8085-exec-6] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-3 - Added connection oracle.jdbc.driver.T4CConnection@4e5ee0cc
18:15:04.040 [HikariPool-3 housekeeper] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-3 - Pool stats (total=1, active=1, idle=0, waiting=1)
18:15:04.167 [HikariPool-2 connection adder] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-2 - Added connection oracle.jdbc.driver.T4CConnection@317680ec
18:15:04.225 [http-nio-8085-exec-5] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-4 - Added connection oracle.jdbc.driver.T4CConnection@79d11005

**Comment by brettwooldridge** [comment]
@BilgehanYildiz If new pools are being created, that is indicative of a Spring configuration issue, not a HikariCP issue. HikariCP will never create new pools on its own. Please ask on stackoverflow or the Spring discord.
