### ISSUE TITLE
Question about multi catalog connection pools

### ISSUE THREAD

**Issue by FollowSteph** [brettwooldridge/HikariCP#1781]
I apologize if this is not the best venue to ask a question but I couldn't find another source other than asking a question in StackOverFlow which was already asked but probably outdated: https://stackoverflow.com/questions/43078796/connection-does-not-correctly-set-catalog-using-hikaricp

Specifically I'm interested in your comment Brett: "Users have reported successfully running thousands of pool instances in a single JVM" Do you have any more details on this? Are they just using a HashMap of pools? And if so what is the actual overhead? As in how memory does each pool use, etc? I'm interested in this option but would like to get more details. Thank you.,

**Comment by brettwooldridge** [comment]
The pool itself uses very little memory. A couple of kilobytes. How much memory is used by a driver is going to be hard to gauge.
