### ISSUE TITLE
No performance counters in HikariPoolMXBean.

### ISSUE THREAD

**Issue by ehud-eshet** [brettwooldridge/HikariCP#1788]
HikariPoolMXBean exposes only a snapshot of current state.
E.g. current idle connections, current active connections.

In order to tune pool parameters, administrators would appreciate counters such as:

1. Total getConnection() invocations.
2. How many of them reused an idle connection?
3. How many physical connections were opened?
3. How many individual physical connections were reused? more than 10 times? more than 100 times? more than 1000 times?
4. How many physical connections were closed due to: max lifetime? connection health check? idle timeout? 

It would be even better to have a counters object, which allows resetting all above counters at once.
Then, next calls will provide the value of the requested counter since the last reset.
Resetting one counters object should not affect other counters objects.

**Comment by brettwooldridge** [comment]
I'm not sure how any of these metrics are useful. Metrics collection has quite a bit of overhead. All of the third-party metrics frameworks supported have "good" performance, but not for this granulary of reporting.
