### ISSUE TITLE
What is effect of SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE=0?

### ISSUE THREAD

**Issue by brianmooremsft** [brettwooldridge/HikariCP#1791]
I have customer trying migrate to hybrid cloud, having issues with existing HikariCP configuration (from on-prem hosting environment), getting periodic errors org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection.

Customer has found that setting SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE=0 causes errors to subside, but claims they think this setting means they are or may opening new database session on every request.  

In docs, definition of MinimumIdle says recommendation is to NOT set the value for best performance, and it will default to match MaxPoolSize; it does not say anything about setting value to 0, or what effect that would be.

Can someone clarify?

**Comment by brettwooldridge** [comment]
Setting minimum idle to 0 will not cause a new connection per request. Connections will live for ``idleTimeout`` time. If the pool is reasonably active, it will generally keep the pool at a reasonably level number of connections.

You can enable debug logging to see all connection creation and retirement events. Debug logging is not particularly "noisey" and can be used safely in production.
