### ISSUE TITLE
Cannot acquire connection even all connections are idle

### ISSUE THREAD

**Issue by chanhlt12** [brettwooldridge/HikariCP#1803]
I am using Spring Boot 2.1.6 with HakariCP 3.2.0
I am trying to print out the connection pool status as below before executing queries.

![image](https://user-images.githubusercontent.com/65900176/124753442-333f5400-df53-11eb-819a-ba62a65a87b4.png)

As you can see there are 100 idle connections and zero active connections.
But the MyBatis still throws error which said: Connection is not available

![image](https://user-images.githubusercontent.com/65900176/124753647-71d50e80-df53-11eb-93bf-32e72ceb0ba9.png)

I am confusing about exactly what idle connections mean.

Can someone help me explain this?

Thank you.

**Comment by brettwooldridge** [comment]
Enable debug-level logging for ``com.zaxxer.hikari``.

**Comment by wangchaoforever** [comment]
I have the same issue. How to resolve this issue?

**Comment by lfbayer** [comment]
Without debug log information, there isn't much that we can do to investigate. And in fact we would prefer if you only open tickets here on github issues if you know specifically what the bug in HikariCP is and can explain how HikariCP is wrong.

If you are looking for help diagnosing a problem in your system, we recommend stackoverflow instead.
