### ISSUE TITLE
Do we really need graceful shutdown anymore?

### ISSUE THREAD

**Issue by unikzforce** [brettwooldridge/HikariCP#1805]
Hi @brettwooldridge,

Recently we had an incident in our company.
Initially, It seemed that MariaDB connections are not being released after each web application restart. Because DB didn't have any remaining capacity to accept new connections, and upon each restart of our web applications, the capacity shrank more, So we investigated.

at first, we thought that we need to add a graceful shutdown hook for the Hikaricp, but we found out that currently, spring boot would do the Hikaricp clean-up automatically in the end.

so we suspected that our spring boot applications are not being gracefully terminated, And we were right. We are using Kubernetes and in our Dockerfile instead of ENTRYPOINT, we were using CMD, so Spring applications wouldn't receive SIGTERM and eventually, it couldn't perform any graceful termination procedure and Kubernetes would kill the whole container after grace period (30 secs) with SIGKILL.

So for the sake of the test we created a fixed version and compared it with the unfixed version.

We monitored the MySQL connections count.
To our surprise, both of these tests resulted in an instant closing of DB connections.

I mean we forcefully killed a spring application without giving it the chance to clean up the connections and the connections count in MariaDB instantly dropped.

So if MariaDB is closing the connections instantly, why do we need to do a graceful termination procedure for Hikaricp at all (Like you mentioned in [210](https://github.com/brettwooldridge/HikariCP/issues/210) )? does it do anything other than closing the connections? does it try to do anything regarding current transactions that are being executed?

**Comment by brettwooldridge** [comment]
@unikzforce The shutdown code closes all idle connections. and then calls ``connection.abort()`` on all active connections.  I suggest taking a look at the code [here](https://github.com/brettwooldridge/HikariCP/blob/8f254ae32b6c2b48b3aff35f74c165e4e3dda094/src/main/java/com/zaxxer/hikari/pool/HikariPool.java#L198). Maybe we've run into a bug in the MariaDB driver.

**Comment by unikzforce** [comment]
How could it possibly be a bug? I mean connections are instantly closed themselves without any effort from hikaricp. It's more like an unwanted feature
