### ISSUE TITLE
Should we switch from `javax.*` to `jakarta.*`?

### ISSUE THREAD

**Issue by larsnaesbye** [brettwooldridge/HikariCP#1807]
As the namespace has changed in newer versions due to the transfer of JavaEE to Eclipse Foundation, we could update by replacing imports and references. I could make a PR if you so wish.

**Comment by froque** [comment]
I don't think this applies to HikariCP. 

The only javax.* usages I could find were `javax.sql`, `javax.management` and `javax.naming`, and these are [Unaffected (Non-EE) Packages](https://github.com/eclipse-ee4j/jakartaee-platform/blob/master/namespace/unaffected-packages.adoc)

There is a usage of `javax.inject` but in test scope only:
```
$ git grep -e javax --and --not -e javax.sql --and --not -e javax.management --and --not -e javax.naming 
pom.xml:189:         <groupId>javax.inject</groupId>
pom.xml:190:         <artifactId>javax.inject</artifactId>
src/test/java/com/zaxxer/hikari/osgi/OSGiBundleTest.java:30:import javax.inject.Inject;
```

**Comment by larsnaesbye** [comment]
Cool. I hadn't noticed that these were unaffected.
