### ISSUE TITLE
No available connection timeout - HOW TO DEBUG?

### ISSUE THREAD

**Issue by petemm123** [brettwooldridge/HikariCP#1809]
Hello, Hikari CP is very good. I have one question - in our larger project many threads are using HikariCP, sometimes application is unresponsive (waiting for connection) and sometimes it crashes due to timeouts.

Please is there any way to monitor number of active connections (how to switch on debug?) and ideally what commands are now is progress in individual connections? And is it possible to log it (via logger or get info from my function) when it it over threshold (e.g 5 active from 10)? 

So - methods for following will solve it:
- getting actual number of connections available (should exists, but don't know how to call it)
- enable logging (it is mentioned - but how exactly to switch on debug)
- getting actual queries in individual connections in pool (not available, will help to identify issue)

I need to debug why these errors occur. It may be just small limit of connection pool size (e.g. too many regular longer tasks that fast tasks need to wait), DB problem (maintenance/unavailability/long query time to some table) or some bug in code. 

Thanks a lot!

**Comment by brettwooldridge** [comment]
Investigate how to monitor through JMX (like jconsole or other):
https://github.com/brettwooldridge/HikariCP/wiki/MBean-(JMX)-Monitoring-and-Management

Investigate your logging library for how to enable logging for a specific package (``com.zaxxer.hikari``).

**Comment by zeimao77** [comment]
poolProxy. The getidleconnections () method throws'java lang.reflect. Undeclaredthrowableexception'exception.

**Comment by brettwooldridge** [comment]
@zeimao77 The method is [``getIdleConnections()``](https://github.com/brettwooldridge/HikariCP/blob/979c0ec64e6adb02ddb17cc0efb0dd68b6d8dd02/src/main/java/com/zaxxer/hikari/HikariPoolMXBean.java#L38), not ``getidleconnections()``.
