### ISSUE TITLE
Failover Functionality

### ISSUE THREAD

**Issue by grypyrg** [brettwooldridge/HikariCP#181]
It would be great if we could have the connection pool in helping make planned 'failover' more graceful.

The softEvictConnections() is a good solution for synchronous replication databases (active:active) such as Galera. Both can accept writes at the same time. We just need to wait until all connections are closed.

In MySQL world, many environments are using asynchronous replication.
- In order to avoid split-brain first the connections need to be closed/killed on the 'current master'. 
- Then the replication needs to be caught up
- the virtual IP address is moved to the new master
- the new master can now start accepting connections.

It would be good to have some JMX methods that can help make this more graceful:
- haltAllConnections() - to stop processing database queries, queueing it on connection pool level.
- getCurrentActiveConnections() - to have the external tool monitor and wait until all of them are idle
  (here the failover process would take place, which usually takes a couple of seconds)
- resumeAllConnections() - start processing database queries again

We can then write some plugins for percona-replication manager (https://github.com/percona/percona-pacemaker-agents) and other AH tools or more easily implement this orchestration with tools such as zookeeper.

**Comment by brettwooldridge** [comment]
@grypyrg Hi Kenny, its been a while and I wanted to circle back and give you an update.  Using your [Percona Live 2014 slide stack](http://www.percona.com/live/london-2014/sites/default/files/slides/Java%20MySQL%20Connector%20%26%20Connection%20Pool%20Features%20%26%20Optimization.pdf) as a guide...

Re: Slide 53 (Connection Pool - Resetting Status), HikariCP now tracks transaction state, and will only perform a rollback() if the transaction state is dirty (rather than always).

Re: Slide 75-76 (Connection Pool - TRX HikariCP), HikariCP now tracks *read-only*, *auto-commit*, *transaction-isolation*, and *catalog* independently, and will only reset them (individually) if they are dirty (modified explicitly by the user to other than the default).  Not sure how many "Calories" that is, but it shouldn't be theoretically possible to go lower.

Re: Slide 87 (Connection Pool - Graceful Failover), HikariCP now supports the following via JMX:
 * ``softEvictConnections()`` - close all idle connections, mark all in-use connections for eviction on return.
 * ``suspendPool()`` - block incoming calls to ``getConnection()``
 * ``resumePool()`` - unblock waiting threads in ``getConnection()``

A typical fail-over pattern would be:
 1. ``suspendPool()``
 2. ``softEvictConnections()``
 3. Wait until ``activeConnections`` goes to 0.
 4. ``resumePool()``

**Comment by grypyrg** [comment]
Thanks Brett! I actually will give this talk again in Percona Live MySQL Conference 2015 in 2 weeks. (http://www.percona.com/live/mysql-conference-2015/) 

I'll try all your modifications later this week/next week and include them in my new slidedeck!


Kenny

**Comment by brettwooldridge** [comment]
@grypyrg Any chance of getting a HikariCP mention on [this page](http://www.percona.com/live/mysql-conference-2015/sessions/java-mysql-connector-connection-pool-features-optimization)? :wink:  Commons-DBCP, really? :disappointed:

**Comment by grypyrg** [comment]
@brettwooldridge: Added HikariCP on the page :)

**Comment by brettwooldridge** [comment]
Great, thanks!  Actually, its not that we're into self-promotion, (ok, we are), *but* I actually ran across your original slideshare in a Google search, so we thought it would actually help ppl searching for "HikariCP" in the future.  That's a really great slide stack, I'd love to see the updated one after you present it.

**Comment by grypyrg** [comment]
I have uploaded my new slides. Not much has changed, but I included your new implementations and removed the stuff you optimized!

**Comment by brettwooldridge** [comment]
@grypyrg Hi Kenny, thanks for the new slides.  I do have some feedback on Slides 69-77, take it for what you will.

With all the pools you show how to 'slim them down' to "200 calories", and maybe you touch on it during the presentation, but I don't see the *downsides* of these configuration changes mentioned:

**C3P0**
``forceIgnoreUnresolvedTransactions=true``

Issue: Uncommitted transactions can "*bleed-over*" from one consumer of the pool to another, or leave locks held for extended periods of time by connections returned to the pool with open transactions.

**DBCP**
``testOnBorrow=false``
``rollbackOnReturn=false``
``enableAutoCommitOnReturn=false``

Issues:
 * ``testOnBorrow=false`` increases the likelihood of [broken connections](https://twitter.com/LopesFlorian/status/598248584446877696) given to your application
 * ``rollbackOnReturn=false`` + ``enableAutoCommitOnReturn=false``, like the C3P0 "remediation" above can bleed transactions between consumers or cause locks to be held for extended periods

**HikariCP Differentiators**
 * Tests connections with ``isValid()`` before returning them from the pool, with an optimization that bypasses the check if the connection was utilized within the last 1000ms
 * Tracks connection state (and transaction state), and performs ``rollback()`` only the the case of a non-autocommit connections with uncommitted changes

**Comment by brettwooldridge** [comment]
@grypyrg Also, I did find this MySQL bug related to 'useLocalTransactionState', which you guys might find interesting:

https://bugs.mysql.com/bug.php?id=75209

**Comment by grypyrg** [comment]
> On 13 May 2015, at 06:46, Brett Wooldridge <notifications@github.com> wrote:
> 
> @grypyrg <https://github.com/grypyrg> Hi Kenny, thanks for the new slides. I do have some feedback on Slides 69-77, take it for what you will.
> 
> With all the pools you show how to 'slim them down' to "200 calories", and maybe you touch on it during the presentation, but I don't see the downsides of these configuration changes mentioned
> 
Yes I do exactly, not quite enough the last time as I was running out of time (and the projector connection got lost :))
> C3P0
> forceIgnoreUnresolvedTransactions=true
> 
> Issue: Uncommitted transactions can "bleed-over" from one consumer of the pool to another, or leave locks held for extended periods of time by connections returned to the pool with open transactions.
> 
Correct. Fix your app! :)

> DBCP
> testOnBorrow=false
> rollbackOnReturn=false
> enableAutoCommitOnReturn=false
> 
> Issues:
> 
> testOnBorrow=false increases the likelihood of broken connections <https://twitter.com/LopesFlorian/status/598248584446877696> given to your application
> rollbackOnReturn=false + enableAutoCommitOnReturn=false, like the C3P0 "remediation" above can bleed transactions between consumers or cause locks to be held for extended periods
Indeed. Fix your app again! :)

> HikariCP Differentiators
> 
> Tests connections with isValid() before returning them from the pool, with an optimization that bypasses the check if the connection was utilized within the last 1000ms
> Tracks connection state (and transaction state), and performs rollback() only the the case of a non-autocommit connections with uncommitted changes
Yes exactly, that is good!




Also sidenote, Slideshare decided to remove my account for no reason. I tried to get it active again, but they are ignoring me. So presentation gone on the internet! (although still on percona.com <http://percona.com/>)

**Comment by grypyrg** [comment]
Waw, thanks for sharing this. That's quite bad!
And it’s quite bad the S1 issue is still not fixed.


Kenny
