### ISSUE TITLE
How to kill open connections and get back them to pool when we encounter below error

### ISSUE THREAD

**Issue by sivagtibco** [brettwooldridge/HikariCP#1821]
We got in to this error when firewall issue with database, java.sql.SQLTransientConnectionException: springHikariCP - Connection is not available, request timed out after 30000ms
Firewall issue is resolved in couple of min but these errors are keep coming in all of our services which required a manual restart. Instead of that is there any way we can heal it automatically by killing those open connections get them to pool?

**Comment by codehappy** [comment]
https://github.com/brettwooldridge/HikariCP/wiki/Bad-Behavior:-Handling-Database-Down

**Comment by brettwooldridge** [comment]
@sivagtibco This is probably most important to read regarding enabling proper recovery:

https://github.com/brettwooldridge/HikariCP/wiki/Rapid-Recovery

Also, make sure you are running the absolute latest version of your database JDBC driver. Postgresql, for example, fix several issues related to proper network timeout handling in just the past six-months or so.
