### ISSUE TITLE
Broken Video on "About Pool Sizing" wiki page

### ISSUE THREAD

**Issue by BeniaminK** [brettwooldridge/HikariCP#1829]
The video on the About Pool Sizing wiki page is broken: https://www.youtube.com/watch?v=xNDnVOCdvQ0

**Comment by oguzhancevik** [comment]
Hi @BeniaminK, you can access this [link](https://web.archive.org/web/20210216161049if_/https://www.youtube.com/watch?v=xNDnVOCdvQ0) 


Hi @brettwooldridge and @nitincchauhan , The video was removed from youtube, but it can be accessed via web archive. Please can you add the new link?

https://web.archive.org/web/20210216161049if_/https://www.youtube.com/watch?v=xNDnVOCdvQ0
