### ISSUE TITLE
Unknown system variable 'tx_isolation'

### ISSUE THREAD

**Issue by pedroagrs** [brettwooldridge/HikariCP#1831]
**MySQL Version:** 8.0.21
**JDK Version:** 11

`
com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Unknown system variable 'tx_isolation'
`

**Pom.xml dependency:**
```
<dependency>
 <groupId>com.zaxxer</groupId>
 <artifactId>HikariCP</artifactId>
 <version>5.0.0</version>
 <scope>compile</scope>
</dependency>
```

I understand this variable has been updated on MySQL 8.0
But HikariCP doesn't have support for this version?

**Comment by yakirgb** [comment]
Old client version?

**Comment by pedroagrs** [comment]
I believe the problem is because Hikari didn't check if I'm using a newer version of MySQL.

**Comment by pedroagrs** [comment]
Guys, The problem is on _"mysql server 8.0"._ I switched my database to _"mariadb 10.3.28"_  (mysql fork) & done! Everything working.
