### ISSUE TITLE
Connection pool for several clusters on databricks spark

### ISSUE THREAD

**Issue by fatagun** [brettwooldridge/HikariCP#1847]
We are using databricks on azure and have several spark clusters.

For each connection we are doing `connection = dataSource.getConnection();`. Is it possible to have a collection of connection pools to look up based on connection string?

Does it make sense to create a collection pool per cluster? store them in a `Map`? or is there a better way? 

Any recommendations?

btw: using SparkJDBC4.2, simbaspark.

**Comment by aman-pebicloud** [comment]
Is this requirement satisfied now? I'm trying to use Hikari for creating a DataSource on Databricks. If anyone has implemented, please share the steps here or refer to an example. Thanks in advance.
