### ISSUE TITLE
Youtube video is Unavailable in https://github.com/brettwooldridge/HikariCP/wiki/About-Pool-Sizing

### ISSUE THREAD

**Issue by rajanjha786** [brettwooldridge/HikariCP#1853]
Hello 
The youtube video embedded on page https://github.com/brettwooldridge/HikariCP/wiki/About-Pool-Sizing is deemed to be a private video.
It's Unavailable

**Comment by dneth** [comment]
I haven't seen the original video, but it seems like this might have similar contents: https://www.youtube.com/watch?v=XzN8Rp6glEo&ab_channel=OracleLearning

If so, it'd be nice if somebody with access could update the wiki.
