### ISSUE TITLE
Cannot override Hikari setting transaction isolation level

### ISSUE THREAD

**Issue by andygrove** [brettwooldridge/HikariCP#187]
Hi,

I'm new to HikariCP, so maybe I am missing something, but I cannot find a way to stop Hikari from attempting to set the transaction isolation level on the driver I am using. I want to use the default transaction isolation level of the driver. 

The issue is that in com.zaxxer.hikari.util.PoolUtilities#setupConnection, the isolation level is always set:

<code>public static void setupConnection(...)
   {
      connection.setAutoCommit(isAutoCommit);
      connection.setTransactionIsolation(transactionIsolation);
      connection.setReadOnly(isReadOnly);
</code>

The caller (com.zaxxer.hikari.pool.HikariPool#addConnection) does have code that seems to be designed to handle just using the default:

<code>transactionIsolation = (transactionIsolation < 0 ? connection.getTransactionIsolation() : transactionIsolation);</code>

However, as far as I can tell, transactionIsolation defaults to 0, so this code is never triggered.

<code>public int transactionIsolation;</code>

Should this variable be declared to default to -1?

Thanks,

Andy.

**Comment by zicjin** [comment]
My needs are the same as @andygrove's. But after so many version updates, a lot of code has changed dramatically. I was wondering if the current 5.1.0 version has an easy way to prevent the sql connection from executing any "TRANSACTION ISOLATION LEVEL" statements?

In addition, I also want to know whether it is the java.sql library or the HikariCP library or the hibernate library that decides to execute the "TRANSACTION ISOLATION LEVEL" statement? If I need to solve the problem myself, where do I start?

If anyone is curious:
I'm trying to connect to [clickhouse's postgresql interface](https://clickhouse.com/docs/en/interfaces/postgresql), which has no TRANSACTION statements at all.
