### ISSUE TITLE
After application deployment sudden increase in load resulting in slow connection creation 

### ISSUE THREAD

**Issue by mdtamim** [brettwooldridge/HikariCP#1875]
Hello,

I have a Spring Boot application with hikari connection pool. The application was deployed in two instances(Say pod A and pod B).After deployment 3-4 requests were executed in pod A for warmup and the application was able to process 84 concurrent requests efficiently with average response time in milliseconds. But Pod B where no prior requests were sent for warmup,43 requests came and all had huge latency and 3-4 seconds was being spent on average in Hikari.getConnection() method.My Hikari pool configuration is as below : 

    hikari:
      maximum-pool-size: 100
      max-lifetime: 30000
      minimum-idle: 10

Is this a expected behaviour without any warmup under load?

**Comment by mdtamim** [comment]
<img width="925" alt="HikariSlowness" src="https://user-images.githubusercontent.com/12379667/142590905-e81a1c43-90fa-444f-98fb-28b939977a5f.PNG">

Here is the screenshot of code level time consumed

**Comment by mdtamim** [comment]
@brettwooldridge kindly share your views.

Thanks in advance.

**Comment by rhys-saldanha** [comment]
This doesn't seem like an issue with Hikari. Why have you set your minimum connections to 0, when your application needs to deal with sudden spikes in activity? 

You should look into the database technology you're using to see what can be done to improve the time to create a connection.

Ultimately, creating new connections is an expensive operation, and you may find that a non-zero minimum pool size is necessary for your use.

**Comment by AnonymousVovus** [comment]
+1

**Comment by brettwooldridge** [comment]
@mdtamim Set ``initializationFailTimeout`` to some reasonable value, like 30000 (i.e. 30 seconds), and set system property ``com.zaxxer.hikari.blockUntilFilled=true``. This will block the application startup for 30 seconds or until ``minimumIdle`` connections are added to the pool, whichever comes first.
