### ISSUE TITLE
setMaxPoolSize is not working 

### ISSUE THREAD

**Issue by SK-Yang** [brettwooldridge/HikariCP#1878]
I'm using following way to share my Hikari datasource across multiple DAOs. But I got a ticket that my APP consumed too many DB connection which is many times more than my setting. For example, I have set my max connection amount to 30, but after a round of JMeter test, I could see my APP created 320 connection sessions on SSMS management tab which is beyond my setting. Is there something missing?

Hikaricp: 3.4.1
MSSQL JDBC: 7.2.2.jre8

```
public class Datasource {
	protected static HikariDataSource ds = null;

	public Datasource(String user, String passWD, String srvName, int srvPort, String dbName, int maxConn) {
		if(ds == null) {
			ds = new HikariDataSource();
			ds.setMaximumPoolSize(maxConn);
			ds.setDataSourceClassName("com.microsoft.sqlserver.jdbc.SQLServerDataSource");
			ds.addDataSourceProperty("url", "jdbc:sqlserver://" + srvName +":" + srvPort + ";databaseName=" + dbName);
			ds.addDataSourceProperty("user", user);
			ds.addDataSourceProperty("password", passWD);
		}
	}
	
}

public class DAO1 extends Datasource{
.....
}
```

**Comment by murtaza13** [comment]
Are you creating this DataSource class as a Bean? How are you initializing it? Is it singleton?

There are a lot of questions that need to be answered before anyone could help you out of this. Thanks.

**Comment by SK-Yang** [comment]
>murtaza13

Yeah, it's like singleton design. I could initialize it in my main class's constructor, then all child classes like DAO1 could just call ds.getConnection() to get their connection from that static datasource through inheritance.

Anything else that you wanna know?

**Comment by lfbayer** [comment]
With logging enabled you might find that `new HikariDataSource()` is being called by your application more than once. The reason you are seeing so many connections is very likely because you have created more than one instance of the pool, and each of those instances can consume up to the maximum pool size.
