### ISSUE TITLE
Video about connection pooling is private

### ISSUE THREAD

**Issue by kyle-tc** [brettwooldridge/HikariCP#1883]
https://github.com/brettwooldridge/HikariCP/wiki/About-Pool-Sizing

**Comment by kyle-tc** [comment]
looks like this one could be used instead:
https://www.youtube.com/watch?v=_C77sBcAtSQ

**Comment by lfbayer** [comment]
@kyle-tc, Thanks for finding the link, I've updated the page. It would be nice to have a link to an official oracle page or something instead. I suspect this link will be dead again in a year just like the last couple times we've updated the link :)
