### ISSUE TITLE
Issue with auto_increment translation in Hikari

### ISSUE THREAD

**Issue by AerWyn81** [brettwooldridge/HikariCP#1914]
Hi,

Having an issue that I can't figure out. 
I use Hikari as a dependency of a JAVA code. 

Version: HikariCP:4.0.3

I create a configuration for MySQL :
![](https://i.imgur.com/OOzR0nR.png)

For this request:
![](https://i.imgur.com/OOiNTvh.png)

The query interpreted by Hikari:
![](https://i.imgur.com/BaU3SMY.png)

I don't understand why the statement is translated as AUTOINCREMENT when the query is AUTO_INCREMENT. This is a problem because MySql only handles AUTO_INCREMENT.

I got this error: 

> [22:38:09 INFO]: Error while loading database: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AUTOINCREMENT,`pUUID` VARCHAR(36) UNIQUE NOT NULL,`pName` VARCHAR(16) NOT NULL)' at line 1

Am I missing something? I didn't find any doc or place with explanations related to this behavior

**Comment by lfbayer** [comment]
This is not an HikariCP since HikariCP does not modify SQL statements in any way.

Maybe you added the underscore after running the compile but you are running old code? I would put a breakpoint in the code an inspect the actual value passed into prepareStatement to see if it matches what you expect. If it does match, you can step deeper with the debugger into the JDBC driver to see where the value actually does change.

**Comment by AerWyn81** [comment]
Hi, thanks for your answer.

The things that made me openning an issue is that the "PreparedStatement" is from HikariProxyPreparedStatement. 
It's not related to old code or a later addition of the underscore. It is the correct SQL statement that is passed as a parameter and the debug shows me that the query is interpreted differently. If I copy paste the request string, passed in parameter of the PreparedStatement, in a sql runner, the request will create the table without problem.

![image](https://user-images.githubusercontent.com/22222045/158589504-f413a66b-66ac-4c3c-9138-bc125b351fe9.png)

But if you tell me it's not Hikari, I'll try to look at the jdbc.ClientPreparedStatement... which is wrapped in Hikari if I understand correctly... Thanks anyway
