### ISSUE TITLE
Could you please change slf4j to jul?

### ISSUE THREAD

**Issue by leonardwoo** [brettwooldridge/HikariCP#1928]
Could you please change slf4j to JUL (Java Util Logging) ?

**Comment by lfbayer** [comment]
Doing so would potentially be a breaking change for all users who already have logging configured. slf4j is fairly standard for libraries to use for logging and it provides more functionality than just plain java.util.logging.

I wouldn't expect HikariCP to change the logging framework anytime soon.

**Comment by leonardwoo** [comment]
I knew JUL doesn't provide enough functionality, but if I don't want to use slf4j ?
