### ISSUE TITLE
Published Maven POM should contain a valid SCM URL

### ISSUE THREAD

**Issue by spliffone** [brettwooldridge/HikariCP#1929]
The published Maven POM file should contain an valid URL string for the element `project.scm.url` element (see [pom.xml](https://github.com/spliffone/HikariCP/blob/a9147ee0f63f8e78fcd7bbed9152c32a5ad0ce5d/pom.xml#L51)).

This change is helpful to fix automation scripts to build a bill of material.

**Comment by brettwooldridge** [comment]
Merged.
