### ISSUE TITLE
Feature request: maxActiveTime parameter

### ISSUE THREAD

**Issue by SuperPat45** [brettwooldridge/HikariCP#1934]
Migrating from the old API proxool, one of its parameter that is missing on HikariCP: maximum-active-time.

It is very useful because it kills connections not returned after a certain time.

I have a problem in production when, after some network problem, the pool is full and connections are never closed despite other protections in place.

Can you add this?

**Comment by brettwooldridge** [comment]
This should literally be impossible in a properly configured system. Investigate your JDBC driver's ``socketTimeout`` option, and read [Rapid Recovery](https://github.com/brettwooldridge/HikariCP/wiki/Rapid-Recovery).
