### ISSUE TITLE
why getconnection from pool returns a dynamic wrapper

### ISSUE THREAD

**Issue by yyq2013** [brettwooldridge/HikariCP#1935]
Hi,

We use HikariCP 3.4.5 on porduction, but we got an issue that we cache the connection metadata by connection instance to avoid lower performance, but seems the cache can't take affect because HikariCP pool return a dynamic wrapper for same underlying connection every time. Is it an issue of the Pool library or we missed configuration? Does it impact JVM GC?

**Comment by brettwooldridge** [comment]
You can read the code. Most pools wrap connections for state management, and method interception. For example, ``conn.close()`` should return the connection to the pool, not actually close the connection.

The correct way to access the actual connection is ``conn.unwrap()``.
