### ISSUE TITLE
Excetion override does not work outside the predefined error codes / states

### ISSUE THREAD

**Issue by markwimpory** [brettwooldridge/HikariCP#1960]
Right now you cannot create an exception override when the sql state or error code falls outside the predefined values (that cannot be overridden). Suggestion in ProxyConnection:

         if (sqlState != null && sqlState.startsWith("08")
             || nse instanceof SQLTimeoutException
             || ERROR_STATES.contains(sqlState)
             || ERROR_CODES.contains(nse.getErrorCode())) {

            // broken connection
            evict = true;
            break;
         } else if (exceptionOverride != null && exceptionOverride.adjudicate(nse) == CONTINUE_EVICT) {
            evict = true;
            break;
         } else {
            nse = nse.getNextException();
         }

For example we are dealing with SQLState 25006 when database failover occurs and the read/write replicas are swapped.

**Comment by davemorrissey** [comment]
I'm having the same issue. Setting a short maxLifetime eventually results in these connections being recycled, but with a performance trade off. Allowing addition of codes to the ERROR_STATES set may be an alternative solution.

**Comment by patric-r** [comment]
+1

**Comment by brettwooldridge** [comment]
fixed by c6d1403e
