### ISSUE TITLE
Concurrent threads returned screwed up connection into Hikari pool

### ISSUE THREAD

**Issue by vganshin** [brettwooldridge/HikariCP#1970]
Hello. I found an interesting behaviour of Hicari, I didn't expect from. I'd like to ask if it's bug or not.

If two threads simultaneously use one connection, they may screw it up it and Hikari may return it to the pool with no fixes. I faced it on
```
com.zaxxer/HikariCP       "5.0.1"
org.postgresql/postgresql "42.4.2"
```

## My case

I had a transaction with changed isolation level and by accident the connection was passed to another thread, which just called few non-transactional selects and inserts. Time to time I had been catching `Unhandled org.postgresql.util.PSQLException: Cannot change transaction isolation level in the middle of a transaction`. It turned out, threads released the connection and Hikari accepted it as ready to use, while it was actually in the middle of transaction. And a new transaction unhappily recieved it and failed to change isolation level.

Thanks to this Hikari's I detected the bug in my code.

I understand, that connections are not thread safe, but I'm still curious, is this ok, that Hikari accepted screwed up one and shared it with other threads?

## Example

There is Clojure code, which demonstrates it. Real code, of course, has commit calls and wrapped with try/catch/finally blocks.

```clj
(ns user
  (:require [clojure.reflect :refer [reflect]]
            [clojure.string :as str])
  (:import java.sql.Connection
           org.postgresql.Driver
           [com.zaxxer.hikari HikariDataSource HikariConfig]
           (java.util Properties)))

(defn get-field
  "get private field"
  [obj fld-name]
  (let [fld (.getDeclaredField (.getClass obj) fld-name)]
    (.setAccessible fld true)
    (.get fld obj)))

(defn upcase [^String s]
  (str
   (.toUpperCase (.substring s 0 1))
   (.substring s 1)))

(defn propertize [k]
  (let [parts (str/split (name k) #"-")]
    (str (first parts) (str/join "" (map upcase (rest parts))))))

(defn create-pool [opts]
  (let [props (Properties.)]
    (.setProperty props "dataSourceClassName" "org.postgresql.ds.PGSimpleDataSource")
    (doseq [[k v] opts]
      (when (and k v)
        (.setProperty props (propertize k) (str v))))
    (-> props
        HikariConfig.
        HikariDataSource.)))

(defn pool-coonnections [ds]
  (let [pool (get-field ds "pool")
        bag (get-field pool "connectionBag")]
    (->> (.values bag)
         (mapv (fn [x] (get-field x "connection")))
         (mapv #(-> (bean %) (select-keys [:closed :transactionState :transactionIsolation :autoCommit]))))))

(def pool (create-pool
           {:connection-timeout  30000
            :idle-timeout        1000000
            :minimum-idle        0
            :maximum-pool-size   2
            :connection-init-sql "select 1"
            :data-source.url dburl}))

(def dburl "jdbc:postgresql://localhost:5436/postgres?user=postgres&password=postgres&stringtype=unspecified&")

(while true
  (let [con (.getConnection pool)]
    (try
      (println "isolation level:" (.getTransactionIsolation con))
      (.setTransactionIsolation con 4)
      (.setAutoCommit con false)

      (.executeQuery
       (.prepareStatement con "select 1"))

      ;; Run a query in another thread
      (future (.executeQuery (.prepareStatement con "select 1")))

      (Thread/yield)
      (.close con)))
  (let [con (.getConnection pool)]
    (println "isolation level:" (.getTransactionIsolation con))
    (.close con)))

(pool-coonnections pool)
;; => [{:closed false,
;;      :transactionState
;;      #object[org.postgresql.core.TransactionState 0x35f1a612 "OPEN"],
;;      :transactionIsolation 4,
;;      :autoCommit true}]
```

**Comment by nytro77** [comment]
@vganshin I think that this is not the responsibility of HikariCP to handle.
If one starts a transaction one must make sure to rollback or commit before closing it.
Not even the java.sqlConnection.close() API makes any promises to what will happen if you dont.

[Connection close](https://docs.oracle.com/en/java/javase/11/docs/api/java.sql/java/sql/Connection.html#close())

_It is **strongly recommended** that an application explicitly commits or rolls back an active transaction prior to calling the close method. If the close method is called and there is an active transaction, the results are implementation-defined._

**Comment by vganshin** [comment]
@nytro77 Agree. Thanks for your comment and for the link.
