### ISSUE TITLE
Connection is Closed - Springboot application in ECS

### ISSUE THREAD

**Issue by punithkumarko** [brettwooldridge/HikariCP#1981]
Hi,
We have deployed microservice springboot application into ECS fargate. There we are facing a issue where if the application is kept idle overnight, the sql connections are closed and hence receive an internal server error.  Would like to know where the issue persists and what the solution might be. Please help us with solution since we are in  the last leg of the project and would like to resolve this ASAP.

Also please find below the attachment of the error we are getting in the logs of our application.

![image](https://user-images.githubusercontent.com/108933177/192973742-0c1a2e02-b70d-489d-969a-d71ad1771d29.png)

**Comment by lfbayer** [comment]
Make sure that the maxLifetime configuration for HikariCP is set to shorter than the timeout that is configured on the database server.

If that isn't the issue, you should enable debug logging and also include your hikari configuration settings in this issue.
