### ISSUE TITLE
Unable to use Ephemeral Credentials providers  

### ISSUE THREAD

**Issue by ayushpateldev** [brettwooldridge/HikariCP#1994]
Products like hashicorp vault and others provide ephemeral credentials. These credentials are short lived and expire constantly. 

Credentials can be queried during application start up but its a bit of a pain to keep rotating using the mxbean

Making the username and password into Supplier <String> should fix the issue. As the cp will call the get method everytime a new username and password is required.

Credential providers can then be added to the HikariConfig.

**Comment by lfbayer** [comment]
This is a duplicate of #1196 #1442 and others.
