### ISSUE TITLE
HikariCP 5.0 support for Java 1.8

### ISSUE THREAD

**Issue by slfan1989** [brettwooldridge/HikariCP#1998]
Can we compile a separate HikariCP 5.0 for JDK1.8 ?

**Comment by slfan1989** [comment]
@brettwooldridge Can we upgrade a separate JDK1.8 version for 5.0.0, like Hadoop, currently does not support JDK11, but I think using a newer version(HikariCP) may help improve performance and get some new features.

**Comment by neoxpert** [comment]
As stated in the Hadoop wiki it does not support Java 11 at _compile time_ but at _runtime_. So as long as you do not want to recompile the Hadoop sources, using it / running it within a Java 11 project should be no problem.

**Comment by oucem00decat** [comment]
Why we can't see java upgrade in changelog?
