### ISSUE TITLE
Hikaripool equivalent of eviction configurations in dbcp2

### ISSUE THREAD

**Issue by voghbum** [brettwooldridge/HikariCP#2003]
I'm moving my dbcp2 project to hikariCP because it gives better performance. But I couldn't find the Hikaripool equivalent of the two configurations I made in dbcp2.

> **timeBetweenEvictionRunsMillis** -> _The number of milliseconds to sleep between runs of the idle object evictor thread. When non-positive, no idle object evictor thread will be run._
> 
> **minEvictableIdleTimeMillis** -> _The minimum amount of time an object may sit idle in the pool before it is eligible for eviction by the idle object evictor (if any)._

How can I meet these configurations in HikariCP?

**Comment by lfbayer** [comment]
HikariCP doesn't have a one-to-one equivalent for this feature (and doesn't need it). The `maxLifetime` and `idleTimeout` properties are likely sufficient to handle the underlying use case.

The HikariCP "HouseKeeper" thread runs every 30 seconds. (There is an undocumented and _internal_ system property that can be used to change this: `com.zaxxer.hikari.housekeeping.periodMs`)
