### ISSUE TITLE
Hikari not starting

### ISSUE THREAD

**Issue by Crspy2** [brettwooldridge/HikariCP#2008]
Does anyone know how to fix this issue?
```
INFO   HikariPool-1 - Starting...
DEBUG  HikariPool-1 - Failed to create/setup connection: FATAL: could not open file "global/pg_filenode.map": Operation not permitted
DEBUG  HikariPool-1 - Cannot acquire connection from data source

org.postgresql.util.PSQLException: FATAL: could not open file "global/pg_filenode.map": Operation not permitted
```
the file "global/pg_filenode.map" is not located on my computer, but I see it on my server where the database is hosted.

**Comment by lfbayer** [comment]
This is not a HikariCP issue. It sounds like you might have a permission issue on your postgres server. You might check that the user that postgres is running on has permission to read/write that file? Beyond that you might try searching the internet for the same error.
