### ISSUE TITLE
hikaricp unable to release connections after max-timeout

### ISSUE THREAD

**Issue by satyadeep-ih** [brettwooldridge/HikariCP#2061]
Hi,

I am using hikaricp in spring boot as default connection pool. However, the application fails to obtain a connection even when I specify 50 max connections, and I run a jmeter test plan to run 50 threads. I keep getting 504 Gateway Timeout Error.

My application.properties has:
```
spring.datasource.url=jdbc:mysql://localhost:3306/mydb?autoreconnect=true
spring.datasource.username=myuser
spring.datasource.password=mypassword
spring.datasource.hikari.driver-class-name=com.mysql.cj.jdbc.Driver
logging.level.reactor.netty.http.client=DEBUG
spring.jackson.default-property-inclusion=NON_NULL
spring.datasource.hikari.data-source-properties.cachePrepStmts=true
spring.datasource.hikari.data-source-properties.prepStmtCacheSize=250
spring.datasource.hikari.data-source-properties.prepStmtCacheSqlLimit=2048
spring.datasource.hikari.data-source-properties.useServerPrepStmts=true
spring.datasource.hikari.data-source-properties.useLocalSessionState=true
spring.datasource.hikari.data-source-properties.rewriteBatchedStatements=true
spring.datasource.hikari.data-source-properties.cacheResultSetMetadata=true
spring.datasource.hikari.data-source-properties.cacheServerConfiguration=true
spring.datasource.hikari.data-source-properties.maintainTimeStats=false
spring.datasource.hikari.connection-timeout=60000
spring.datasource.hikari.maximum-pool-size=50
spring.datasource.hikari.minimum-idle=20
spring.datasource.hikari.auto-commit=true
spring.datasource.hikari.idle-timeout=300000
spring.jpa.open-in-view=false
```
My code says:

```
try {

            Connection con = dataSource.getConnection();

            PreparedStatement pstmt = con.prepareStatement(USER_CREDS_QUERY);
            pstmt.setString(1, username);
            ResultSet rst = pstmt.executeQuery();
            rst.next();
            user.setUsername(rst.getString(1));
            user.setPassword(rst.getString(2));
            user.setSalt(rst.getString(3));
            rst.close();
            pstmt.close();
            con.close();


        } catch (SQLException e) {
            // TODO Auto-generated catch block
            LOG.error("Error in findUser ", e.getMessage());
        }
```

My jmeter test plan has **number of threads set to 50** and **romp-up period set to 15 seconds**.

This works well, when I **set the maximum pool size to 20, and request 20 threads**.

Any idea where am I missing?

My environment is : MySQL 5.7 Spring Boot 2.7.9 HikariCP 4.0.3

I am running this on a 2VCPU  ec2 instance.

Thanks

**Comment by svendiedrichsen** [comment]
Have you ever tried to use try-with-resources on the `Connection con = dataSource.getConnection()` statement? This way you are sure to close the connection at the end and thus return it to the pool. Otherwise any exception will prevent the return of the connection to the pool and you will leak connections. `con.close()` will be obsolete for this.

You can also set `leakDetectionThreshold` to see if there are any connection leaks.

**Comment by satyadeep-ih** [comment]
Hi @svendiedrichsen  
Thank you very much for the help. 
Try catch with resource helped clearing connection pool. 

Thanks again.
