### ISSUE TITLE
How can i start , debug and learn hikaricp

### ISSUE THREAD

**Issue by saiKumarGanji** [brettwooldridge/HikariCP#2063]
I want to learn and explore hikaricp in depth.

I can create a small app by importing hikaricp in pom and explore. But I can't edit in that case.
How can I edit hikaricp codebase and run the application at the same time.

How can I do It? Suggestions are appreciated

**Comment by UgoTran** [comment]
Hi saiKumarGanji,
You should clone hikariCP and edit source base. 
And then build and package source as jarfile
Config maven import custom-hikari as external library

---
I did other library easy-captcha to support java 17
Pics:
![image](https://user-images.githubusercontent.com/44249146/235073102-b42a1df0-2574-426b-8fa0-80a36e666dad.png)
- using maven
![image](https://user-images.githubusercontent.com/44249146/235073182-ef999c55-9782-4a53-b2d8-a2bf680fbc6a.png)
- using gradle
![image](https://user-images.githubusercontent.com/44249146/235073567-8a9479e6-f8e3-4afd-99a7-6b3f6bc4d918.png)

**Comment by gary258796** [comment]
Should close this issue since it's not a issue at all.
