### ISSUE TITLE
Use custom Connection Factory for new Connections?

### ISSUE THREAD

**Issue by brainbytes42** [brettwooldridge/HikariCP#2094]
Hi,
is there a way to use a custom Connection Factory with HikariCP? 
I have a preconfigured Factory to create single Connections (`java.sql.Connection`) in my existing code and I would like to be able to use pooled Connections, but I can only call the Factory to create a Connection. Is there any chance to inject the Factory in this Framework? 
I haven't found anything yet...
Thanks!

**Comment by lfbayer** [comment]
My pull request #2011 might address this concern. If you don't mind can you take a look and see if it satisfies your use-case?

**Comment by brainbytes42** [comment]
Thanks for your suggestion to have a look at #2011. 
As far as I can see, you proposed an interface to provide the Connection-creator's classname, but not an instance, right?
I'm not that deep into database optimization, that I'd get the following discussion about the reasons for that, but I'd suggest to just provide some kind of Supplier-Object, which in my case could just relay onto my existing connection factory like that: `() -> myExistingFactory.getConnection`. That supplier could then be called by Hikari anytime it needs a new connection.
If I'd be able to only provide the classname, but not the instance, this might be problematic, as there wouldn't be any chance to configure the Supplier instance...

**Comment by mrotteveel** [comment]
Make your custom factory implement `javax.sql.DataSource` (or wrap it in a custom `javax.sql.DataSource` implementation), and use the `dataSource` property.

**Comment by lfbayer** [comment]
I agree with @mrotteveel's recommendation.

I'm going to close this ticket as answered.
