### ISSUE TITLE
Broken link on a wiki page.

### ISSUE THREAD

**Issue by alpeshvas** [brettwooldridge/HikariCP#2098]
Link is broken on this page - https://github.com/brettwooldridge/HikariCP/wiki/Bad-Behavior:-Handling-Database-Down
![image](https://github.com/brettwooldridge/HikariCP/assets/10026648/12298ab1-517e-45ca-a416-83418bc1a916)

Link to be updated - https://www.cubrid.org/blog/3826470

**Comment by alpeshvas** [comment]
Can someone add #documentation label here.

**Comment by lfbayer** [comment]
Updated. Thanks!
