### ISSUE TITLE
broken link in wiki FAQ

### ISSUE THREAD

**Issue by shalk** [brettwooldridge/HikariCP#2121]
In page https://github.com/brettwooldridge/HikariCP/wiki/FAQ

> A: Configure your HikariCP idleTimeout and maxLifeTime settings to be one minute less than the wait_timeout of MySQL. See [this article](http://www.rackspace.com/knowledge_center/article/how-to-change-the-mysql-timeout-on-a-server) about setting MySQL timeout values.

http://www.rackspace.com/knowledge_center/article/how-to-change-the-mysql-timeout-on-a-server  is gone
 

use  https://docs.rackspace.com/docs/how-to-change-the-mysql-timeout-on-a-server instead

**Comment by lfbayer** [comment]
@shalk Done. Thanks!
