### ISSUE TITLE
No way to use MariaDB connector and MySql server

### ISSUE THREAD

**Issue by gangxie112** [brettwooldridge/HikariCP#2122]
The latest version of MariaDB connector has restricted the schema of mysql. Need add "permitMysqlScheme" for the acception of the url.
See https://mariadb.com/kb/en/about-mariadb-connector-j/#source-code.

We are using HikariCP, and want to switch to MariaDB driver. It's that there is no way to to config HikariCP to add "permitMysqlScheme". Not sure if I miss something, is there any other way to make the 3 guys (HikariCP, MariadDB Connector and the mysql server) work together?

Thanks,

**Comment by quaff** [comment]
Since `permitMysqlScheme` is param of jdbc url, It's not related to connection pool.

**Comment by lfbayer** [comment]
You would only have that problem if you are setting a `jdbcUrl`, and if you are setting a `jdbcUrl` then you have the ability to add that parameter to the `jdbcUrl`. So the answer is to just add that property to your `jdbcUrl`. 

I'm marking this as closed.
