### ISSUE TITLE
Very slow calling getConnection

### ISSUE THREAD

**Issue by nateww** [brettwooldridge/HikariCP#215]
This is a shot in the dark.  We recently (2 weeks ago) switched from the default pooling provider in Play 2.3 (BoneCP) to HikariCP.

Earlier today we had a huge spike in the application, and analysis revealed that getConnection() of HikariCP was taking ~7 seconds per invocation.

![screen shot 2014-12-09 at 3 05 09 pm](https://cloud.githubusercontent.com/assets/8377844/5367018/a71efbaa-7fb5-11e4-9036-78e7b8c89434.png)

Any ideas on what might cause this?  Analysis of the database shows the database running normal up to this point, and then once the spike occurred, the load average (and queries) went DOWN during this spike in behavior as no connections were being made, and thus no operations were being done.

[ Due to network configuration with the firewall, we have a very short TTL for connections of 2 mins ]

**Comment by brettwooldridge** [comment]
@nateww HikariCP 2.3.0-rc4 has been published to the sonatype staging repository.  Any chance you can give it a try?  This bug is pretty much the gate on the release now.

**Comment by nateww** [comment]
@brettwooldridge I won't be able to do it this week (traveling), but I'll see what I can do for next week.

**Comment by brettwooldridge** [comment]
@nateww any update on this?

**Comment by brettwooldridge** [comment]
We're going to go ahead and release HikariCP 2.3.0.  If this issue persists, it will be addressed in a future release.  Leaving this bug open for now.

**Comment by brettwooldridge** [comment]
@nateww If there is no further progress on this, we're going to go ahead and close this issue as resolved.

**Comment by nateww** [comment]
Sorry for not responding to this.  We haven't seen any issues since upgrading to the Play plugin that uses 2.0.5, so I consider it closed.

Thanks!
