### ISSUE TITLE
When I tested the throughput using JMH,found that hikaricp 5.0.0 was faster than version 5.0.1

### ISSUE THREAD

**Issue by herouu** [brettwooldridge/HikariCP#2159]
version 5.0.1
Benchmark                       (jdbcUrl)  (maxPoolSize)  (pool)   Mode  Cnt     Score     Error   Units
ConnectionBench.cycleCnnection  jdbc:stub             32  hikari  thrpt   80  8328.773 ± 102.548  ops/ms

version 5.0.0
Benchmark                       (jdbcUrl)  (maxPoolSize)  (pool)   Mode  Cnt     Score     Error   Units
ConnectionBench.cycleCnnection  jdbc:stub             32  hikari  thrpt   80  10421.351 ± 101.841  ops/ms

* jdk graalvm-19
* use https://github.com/brettwooldridge/HikariCP-benchmark.git and change hikari version

I don't know what happen between them!

**Comment by quaff** [comment]
Comparing: https://github.com/brettwooldridge/HikariCP/compare/HikariCP-5.0.0...HikariCP-5.0.1

Only one effective commit https://github.com/brettwooldridge/HikariCP/commit/ed2da5f1f4ef19f871fac12effc0b199706905dc
