### ISSUE TITLE
Developer experience: allow configuring HikariCP with `java.time.Duration` instead of millisecond / second parameters

### ISSUE THREAD

**Issue by hiddewie** [brettwooldridge/HikariCP#2191]
Currently, configuring the `idleTimeout` property of the connection pool will use the `setIdleTimeout` method on the `HikariConfig` configuration class. 

Similarly, many of the other configuration parameters are duration values. The values range from millisecond, to second, to minute. This difference in order of magnitude can make it error-prone to configure the connection pool correctly, and review the configured values.

It would be great to be able to configure the connection pool using `java.time.Duration` values, for example
```java
configuration.setIdleTimeout(Duration.ofMinutes(5))
configuration.setIdleTimeout(Duration.ofSeconds(10))
```
This makes the intent clear of the code more clear than the current
 ```java
configuration.setIdleTimeout(300000)
configuration.setIdleTimeout(5 * 60 * 1000)
configuration.setIdleTimeout(10000) // 10 seconds, or did I make a typo got a zero too much or too little?
```

I am willing to build a pull request if this feature is found to be useful.

Implementation seems to be extending the `HikariConfigMXBean` with extra setter methods, and extending the implementation `HikariConfig`. 

Furthermore, `PropertyElf` could be extended to take into account property values of the same syntax, for example:
```properties
# 5 minutes idle timeout, all properties are equivalent
idleTimeout = 300000 
idleTimeout = 300s
idleTimeout = 5m
```

**Comment by brettwooldridge** [comment]
I will consider a pull request change to the ``PropertyElf`` that allows HikariCP to accept properties of the form ``300s`` or ``5m``, for example.

I will not change the API of ``HikariConfig`` to accept ``Duration`` as this would be disruptive, and adding overridden methods with alternative signatures unnecessarily increases the surface area of the API. It is just as clear to write:
```java
import static java.util.concurrent.TimeUnit.*;
...
configuration.setIdleTimeout(MINUTES.toMillis(5))
configuration.setIdleTimeout(SECONDS.toMillis(10))
...
```

**Comment by hiddewie** [comment]
Thanks for the comment. I will try to prepare a pull request for parsing the properties from duration strings in `PropertyElf`.

 > It is just as clear to write:
```java
configuration.setIdleTimeout(MINUTES.toMillis(5))
```

Yes, for writing the code yes, but my point of this issue is that it is unclear which units the parameter of `setIdleTimeout` should accept (milliseconds).

It is just as easy as the snippet above to write
```java
configuration.setIdleTimeout(MINUTES.toSeconds(5))
```
which will give plain wrong results. 

And we have the capabilities in the standard library to have the compiler check this for us, by using a `Duration` instead of `long` parameter, where the value can be converted internally to the expected millisecond values.

**Comment by brettwooldridge** [comment]
> Yes, for writing the code yes, but my point of this issue is that it is unclear which units the parameter of setIdleTimeout should accept (milliseconds).

From the very top of the main page regarding configuration parameters:

<img width="1024" alt="Screenshot 2024-11-25 at 0 36 46" src="https://github.com/user-attachments/assets/6e873d3c-99f4-4e5b-8dc6-c2be8dca2ca3">

With respect to the API, the JavaDoc is equally clear:

<img width="1024" alt="Screenshot 2024-11-25 at 0 50 28" src="https://github.com/user-attachments/assets/5997feb2-4447-4375-b191-66fc249043e6">

HikariCP has been in use for over a decade now and the artifact is downloaded over 1.7 million times per month and this has never arisen as an issue. We're not changing the API.

**Comment by hiddewie** [comment]
Yes I understand, but not all developers read this documentation well enough unfortunately. Having a compiler guard against misconfiguration is always a good idea in my opinion (which is why I created this issue).

**Comment by hiddewie** [comment]
I have made a pull request in https://github.com/brettwooldridge/HikariCP/pull/2266 to implement the part into the `PropertyElf` class.

**Comment by hiddewie** [comment]
This can be closed, further changes cannot be implemented as decided in https://github.com/brettwooldridge/HikariCP/issues/2191#issuecomment-2496067977. 

https://github.com/brettwooldridge/HikariCP/pull/2266 got merged to improve the `PropertyElf` parsing.
