### ISSUE TITLE
A question of source code

### ISSUE THREAD

**Issue by ZPZP1** [brettwooldridge/HikariCP#2194]
Here's why not unify the code format, but instead show a LinkedBlockingQueue for declarations
`
  LinkedBlockingQueue<Runnable> addConnectionQueue = new LinkedBlockingQueue<>(maxPoolSize);
`
`
      this.addConnectionExecutor = createThreadPoolExecutor(addConnectionQueue, poolName + " connection adder", threadFactory, new CustomDiscardPolicy());
`
`
      this.closeConnectionExecutor = createThreadPoolExecutor(maxPoolSize, poolName + " connection closer", threadFactory, new ThreadPoolExecutor.CallerRunsPolicy());
`

**Comment by brettwooldridge** [comment]
This is probably an artifact of the ``addConnectionExecutor`` and ``closeConnectionExecutor`` having different queue sizes in the past. I'll take a look.
