### ISSUE TITLE
DB connections in the pool are getting closed with `08S01` error on high load

### ISSUE THREAD

**Issue by afeedhshaji** [brettwooldridge/HikariCP#2207]
Hello team,

The connections inside the pool for one of our applications are getting with the sqlstate `08S01` error. Do we know why this could be occurring? We have tried increasing the timeouts for the different parameters and it's still happening. Note that in our operations, we have a lot of parallel DB queries happening (~3000) and the max pool connection size if `50`.

**Comment by svendiedrichsen** [comment]
This suggests it is a network communication error: https://stackoverflow.com/questions/16459990/sql-error-0-sqlstate-08s01-communications-link-failure
