### ISSUE TITLE
Unit Test Case always reports  error during execution

### ISSUE THREAD

**Issue by 7A6B** [brettwooldridge/HikariCP#2212]
why always happens "NoClassDefFoundError such as com/zaxxer/hikari/HikariDataSource" or "You need to run the CLI build and you need target/classes in your classpath to run." when I run the unit test case;  I had compile the source code  by using mvn clean package as mentioned  issues #535.  how to solved it？   **hikaricp version 4.0.3**

**Comment by brettwooldridge** [comment]
I have no idea, v4.0.3 builds and runs fine on my computer with ``mvn clean package``.
