### ISSUE TITLE
Idle connections are not getting released when used with Try-with-resources 

### ISSUE THREAD

**Issue by VikChauhan20** [brettwooldridge/HikariCP#2215]
Facing issue where few select statements executed leaks connections in try with resource but code works for update and delete statements which too are in try with resource.
We are using postgresql DB - spring.datasource.driver-class-name=org.postgresql.Driver

**Code snippet:** PFA the code snippet.. few values changed for security purposes
<img width="553" alt="image" src="https://github.com/brettwooldridge/HikariCP/assets/174434121/993707ea-3df8-48b9-b9d3-aa588c2d2495">

**Hikari Properties being used:**
spring.datasource.hikari.minimumIdle=10
spring.datasource.hikari.maximumPoolSize=50
spring.datasource.hikari.idleTimeout=10000
spring.datasource.hikari.connectionTimeout=240000
spring.datasource.hikari.maxLifetime=300000

**Error Screenshot** -- Query in image is different but issue is same
<img width="357" alt="image" src="https://github.com/brettwooldridge/HikariCP/assets/174434121/cb053109-c387-4d90-9fac-dc85b8b3a7df">

Please help.

**Comment by JustOneSummer** [comment]
I also encountered this problem in jdk22, the connection would not be released. But I can just downgrade to jdk22. My springboot version is 3.3.0

**Comment by quaff** [comment]
`Connection` keep open for reusing, that's the purpose of pool, what's the problem here?

**Comment by VikChauhan20** [comment]
> `Connection` keep open for reusing, that's the purpose of pool, what's the problem here?

The problem is that they are not being reused as well.. Those connections are stuck in that idle stage and not utilized for other transactions. Thus our total pool connections get exhausted when these stuck connections number become huge.

**Comment by quaff** [comment]
> > `Connection` keep open for reusing, that's the purpose of pool, what's the problem here?
> 
> The problem is that they are not being reused as well.. Those connections are stuck in that idle stage and not utilized for other transactions. Thus our total pool connections get exhausted when these stuck connections number become huge.

What makes you think they are not reused? please note the default `minIdle` is 10.

**Comment by VikChauhan20** [comment]
> > > `Connection` keep open for reusing, that's the purpose of pool, what's the problem here?
> > 
> > 
> > The problem is that they are not being reused as well.. Those connections are stuck in that idle stage and not utilized for other transactions. Thus our total pool connections get exhausted when these stuck connections number become huge.
> 
> What makes you think they are not reused? please note the default `minIdle` is 10.


@quaff Basis of my understanding is presented by this screenshot as we have 4 pods running each with 10 minIdle... so total should be 40 but from yellow highlighted you can see it is 42 connections and also state change is more then 46 mins for these 2 connections.. Request help 

<img width="512" alt="image" src="https://github.com/user-attachments/assets/8a0a380d-9191-47e5-882f-733bf71929bb">

**Comment by quaff** [comment]
> so total should be 40

The total should be 40 to 200 because the `maximumPoolSize` is 50 if concurrency happens, and the total should be 40 after `idleTimeout` elapsed.

**Comment by VikChauhan20** [comment]
> > so total should be 40
> 
> The total should be 40 to 200 because the `maximumPoolSize` is 50 if concurrency happens, and the total should be 40 after `idleTimeout` elapsed.

@quaff 
Yes, the problem is that it is not coming to 40.... even when idleTimeout elapsed like here 2 idle connections have exceeded timeout but are not being released. Thus those 2 connections in idle state will remain until we restart the pods.
These idle connections keep on increasing and ultimately max pool size reaches 200 as these idle connections are not being released and our application start giving Exception "Connection Timeout Error" as no more connections are available in pool for allocation :(

**Comment by VikChauhan20** [comment]
Any suggestion is appreciated as issue still persists :(

**Comment by brettwooldridge** [comment]
@VikChauhan20 Have you enabled the ``leakDetectionThreshold`` and DEBUG level logging?
