### ISSUE TITLE
Can't connect to db url that has username + password

### ISSUE THREAD

**Issue by ColtonIdle** [brettwooldridge/HikariCP#2217]
New to backend dev, but im trying to use hikari and I can get a connection if I do

```
        val ds = HikariDataSource()
        ds.driverClassName = "org.postgresql.Driver"
        ds.jdbcUrl = "jdbc:postgresql://viaduct.proxy.rlwy.net:1234/railway"
        ds.username = "postgres"
        ds.password = "password"
```

But (im using railway as my host) railway has a env variable for the url and it comes through as a format of

`postgresql://postgres:password@viaduct.proxy.rlwy.net:1234/railway
`
so I tried doing

        val ds = HikariDataSource()
        ds.driverClassName = "org.postgresql.Driver"
        ds.jdbcUrl = "jdbc:"+ THE_ENV_VAR

but the connection fails. Any ideas if this is because hiraki can't handle both username and password in the jdbc url?

**Comment by Vladimir-Goncharov21** [comment]
I think u have extra "postgres" after "://"

**Comment by ColtonIdle** [comment]
postgres is the db username

**Comment by ColtonIdle** [comment]
@brettwooldridge any reason this was closed? Was it fixed or am I just a noob and I'm doing it wrong?

**Comment by brettwooldridge** [comment]
HikariCP does not parse or modify the connection URL in any way. It just passes it through to the driver. I would recommend enabling DEBUG logging, and if you cannot figure it out asking on stackoverflow.

**Comment by ColtonIdle** [comment]
cool. thanks!

**Comment by brettwooldridge** [comment]
Oh, looks like it the Java driver doesn't support that format?

https://github.com/brettwooldridge/HikariCP/issues/1402

**Comment by brettwooldridge** [comment]
Here a single line that will change the URL for you:

https://chatgpt.com/share/6740eb91-903c-800e-b833-ce6da335e7c8

**Comment by ColtonIdle** [comment]
thanks. im new to backend development. and railway (my backend that im using) gives me a url that i posted in the OP. hence i was just confused on whether or not that format should be supported or not. i wonder why railway gives me that formatted string. maybe they can change it.

**Comment by brettwooldridge** [comment]
Hard to say. It might be a valid format for MySQL, for example. Every driver determines its own valid format.

**Comment by ColtonIdle** [comment]
that makes sense. TIL. thanks for teaching!

**Comment by ColtonIdle** [comment]
if anyone finds this in the future and its helpful. i mistakenly thought I needed hikari to connect to a database in java. but seems like postgress does indeed have this built in and hikari is just delegating to it. (i got confused because the java library im using to learn to backend with mentions hikari by name and so i thought i needed hikari to connect to it)

**Comment by brettwooldridge** [comment]
Of course you don't need HikariCP for JDBC connectivity, but you should use it for performance. 😄
