### ISSUE TITLE
I tried to set the transaction isolation level, but it only took effect in poolEntry settings. The created connection object did not have the corresponding isolation level set

### ISSUE THREAD

**Issue by Headachy-FanFan** [brettwooldridge/HikariCP#2218]
![1311721633833_ pic](https://github.com/user-attachments/assets/27911bc1-aee8-4e8c-a48f-4af5bb828362)
![1321721633833_ pic](https://github.com/user-attachments/assets/3fdc04fa-1f66-4ed2-bb7c-c95451c4b1aa)
    public HikariConfig buildConfig(String poolName, DbAccount db) {
        HikariConfig config = new HikariConfig();
        config.setPoolName(poolName);
        config.setAutoCommit(false);
        config.setTransactionIsolation("TRANSACTION_SERIALIZABLE");
        config.setUsername(db.user);
        config.setPassword(db.password);
        config.setConnectionTestQuery("select 1;");
        config.setMaximumPoolSize(300);
        config.setMinimumIdle(1);
        config.setMaxLifetime(600000);// 10 minutes
        config.setConnectionTimeout(300000); // 5 minutes
        config.setIdleTimeout(600000); // 10 minutes
        config.setDriverClassName(db.type.getDriverClassName());
        return config;
    }This is the property I set, and you can see that poolEntry has set the transaction isolation level. When I use the connection, I still need to manually set the transaction isolation level of the connection
![image](https://github.com/user-attachments/assets/c3458592-1f63-4e55-9980-a0268c2161e5)

**Comment by brettwooldridge** [comment]
Whenever a connection is returned to the pool it will be reset to the default isolation level, in this case "TRANSACTION_SERIALIZABLE". There is no way to alter a connection's isolation level and have it persist across roundtrips in and out of the pool. When you call ``Connection.close()``, the isolation *will* be reset if it has been altered by ``Connection.setTransactionIsolation()``.
