### ISSUE TITLE
Race condition in addBagItem lambda

### ISSUE THREAD

**Issue by nomagic** [brettwooldridge/HikariCP#222]
Hello Brett,

In short, it is possible that the pool can end up in a situation where it's:
-well below maxPoolSize
-small minIdle (say 1)
-there are (say 10) resource-starved threads (because there are no free connections)
-those 10 threads block (in AQS)
-only 1 new connection gets added to the pool **
-the 10 resource-starved threads eventually are unparked from AQS
-only one can successfully obtain a Connection (since only one was added)
-repeat.

Now this takes a bit of unlucky timing (definition of a race condition), but is certainly possible; it seems unlikely that this is intentional?
The problem is the:
getIdleConnections() < minIdle condition in the lambda ==> this can result in "addConnection" tasks essentially being "swallowed", with resource-starved threads unnecessarily blocking/waiting when the pool is still well below saturation (i.e. maxSize not reached).
In the wild, I suspect this would reveal itself when the pool goes suddenly from a quiescent state to a burst of demand.

I'd be willing to discuss this further (as race conditions are notoriously difficult to explain/diagnose and nearly impossible to test), but it seems there is no way to send a private message and I'm not sure that filing a new issue is the best forum, but I thought I should bring it to your attention.

The good news is that the fix should be relatively straightforward.

-Thurston

**Comment by brettwooldridge** [comment]
Good find, thanks.
