### ISSUE TITLE
db connection with Eclipselink

### ISSUE THREAD

**Issue by rbdevopsx** [brettwooldridge/HikariCP#2221]
Hello, i want to use HikariCP with Eclipselink, but i can't find any settings for my persistence.xml
this is my file : 

<properties>
    
      <property name="eclipselink.canonicalmodel.subpackage" value="mysql"/>
      <property name="jakarta.persistence.jdbc.driver" value="com.mysql.cj.jdbc.Driver"/>
      
      
      <property name="jakarta.persistence.jdbc.url" value="jdbc:mysql://127.0.0.1:3306/boilerplatedb?useSSL=false"/>
      <property name="jakarta.persistence.jdbc.user" value="myuser"/>
      <property name="jakarta.persistence.jdbc.password" value="mypassword"/>
      <property name="eclipselink.jdbc.batch-writing" value="JDBC"/>
      <property name="eclipselink.jdbc.batch-writing.size" value="1000"/>
      <property name="eclipselink.jdbc.cache-statements" value="false"/>
      <property name="eclipselink.cache.shared.default" value="false"/>
      <property name="eclipselink.logging.level" value="OFF"/>

      
      <property name="eclipselink.connection-pool.default.initial" value="5" />
      <property name="eclipselink.connection-pool.default.min" value="8" />
      <property name="eclipselink.connection-pool.default.max" value="13" />
      
   
    </properties>

thanks!
Roberto

**Comment by brettwooldridge** [comment]
Ask on stackoverflow or ChatGPT, please.
