### ISSUE TITLE
is there any logging available to get the information for the thread activity ?

### ISSUE THREAD

**Issue by Masood312** [brettwooldridge/HikariCP#2224]
Looking for the information to get the thread logging on the event when the thread gets a connection and when they are returned to the pool. 

Any information apart form the logging would also help me. 

The intention for this activity is to know, if a thread can, at any point in time, be associated with more than one connection.

**Comment by IRus** [comment]
@Masood312 did you try implementing `com.zaxxer.hikari.metrics.IMetricsTracker`? It seems to get called when connection acquired and released

**Comment by brettwooldridge** [comment]
Either implement the IMetricsTracker as suggested or wrap the HikariDatasource with an implementation that logs.
