### ISSUE TITLE
Long running stream query connection being reallocated before it's done

### ISSUE THREAD

**Issue by dmitchell** [brettwooldridge/HikariCP#2228]
I have a long-running stream query (swag 10 minutes) on the stack  in many threads (one query per account fwiw). Under the consumer of those queries, there are other standard queries. For some reason, Hikari seems to be allocating still in use connections from the streaming queries to the downstack queries thus triggering

> java.sql.SQLException: Streaming result set com.mysql.cj.protocol.a.result.ResultsetRowsStreaming@6541fef9 is still active. No statements may be issued when any streaming result sets are open and in use on a given connection. Ensure that you have called .close() on any active streaming result sets before attempting more queries.

The error, of course, doesn't give enough information for me to know for certain that it isn't a query which my code thinks it finished; however, since the streaming query uses `use` I *believe* it will close the connection when it's done.
``` kotlin
        database.executeExpression(expression) { statement ->
            statement.fetchSize = Integer.MIN_VALUE
            statement.executeQuery().use { rs ->
                while (rs.next()) {
                    action(rs)
                }
            }
        }
```

Any contrary hypotheses? 

My gut is to create a one time connection outside the connection pool per streaming query as the overhead is dwarfed by the query run time (streaming on the order of a million rows). Any how-to for that or better ideas?

**Comment by dmitchell** [comment]
Ah, simple cause not so simple fix. 
Default behavior of Hikari or ktorm is reuse any open connection in the call stack rather than create a new connection (or get one from the pool). So, I need to have my streaming call basically forbid the reuse. It's not obvious how.

**Comment by IRus** [comment]
@dmitchell can you wrap a query in a transaction? Semantic of transaction is to forbid connection re-use while it's active.

**Comment by IRus** [comment]
I wonder if this is somehow related to the fact that `action` is a suspend function, and ktorm+hikairi release current connection at suspension point

**Comment by dmitchell** [comment]
Thank you @IRus for that explanation. It clarifies the cause. I've gotten around it by not using Hikari for the streaming query and making a connection per query. the overhead is minuscule compared to everything else.
