### ISSUE TITLE
java.sql.SQLNonTransientConnectionException: No operations allowed after connection closed.

### ISSUE THREAD

**Issue by Hamed0911** [brettwooldridge/HikariCP#2234]
I am working on a project for school which is creating a scheudling application(WGU C195) and keep facing this error when I try to log in
as far as I got the issue is in the DBConnection file

package main;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;

/**
 * The {@code DBConnection} class manages the database connection lifecycle,
 * including establishing and closing connections to the database.
 */
public class DBConnection {

    // Database connection details
    private static final String PROTOCOL = "jdbc";
    private static final String VENDOR_NAME = ":mysql:";
    private static final String IP_ADDRESS = "//45.63.69.84:3306/client_schedule";
    private static final String JDBC_URL = PROTOCOL + VENDOR_NAME + IP_ADDRESS + "?connectionTimeZone=SERVER";
    private static final String MYSQL_JDBC_DRIVER = "com.mysql.cj.jdbc.Driver";

    // Database credentials
    private static final String USERNAME = "sqlUser";
    private static final String PASSWORD = "Wjg5obl4K1heryz88GVlxeEc1EMW6Vi";

    // Database connection instance
    private static Connection conn = null;

    /**
     * Starts the database connection if it is not already active.
     *
     * @return the active database connection.
     */
    public static Connection startConnection() {
        if (conn == null) {  // Check if the connection is already established
            try {
                Class.forName(MYSQL_JDBC_DRIVER);  // Load the JDBC driver
                conn = DriverManager.getConnection(JDBC_URL, USERNAME, PASSWORD);  // Establish the connection
                logConnectionStatus("Database connection established.");  // Log successful connection
            } catch (ClassNotFoundException | SQLException e) {
                logConnectionStatus("Failed to connect to the database.");  // Log failure to connect
                e.printStackTrace();  // Print the stack trace for debugging
            }
        }
        return conn;  // Return the active connection
    }

    /**
     * Returns the current database connection. If no connection is active,
     * it attempts to start a new one.
     *
     * @return the active database connection.
     */
    public static Connection getConnection() {
        try {
            if (conn == null || conn.isClosed()) {  // Ensure a connection is available
                return startConnection();  // Start a new connection if none exists or if the existing one is closed
            }
        } catch (SQLException e) {
            logConnectionStatus("Error checking connection status.");  // Log the error
            e.printStackTrace();  // Print the stack trace for debugging
        }
        return conn;  // Return the existing connection
    }

    /**
     * Prepares a new {@code PreparedStatement} for a given SQL statement.
     *
     * @param sqlStatement the SQL statement to be prepared.
     * @return a {@code PreparedStatement} object for executing the SQL statement.
     * @throws SQLException if the SQL statement cannot be prepared or if the connection is null.
     */
    public static PreparedStatement createPreparedStatement(String sqlStatement) throws SQLException {
        Connection conn = getConnection();  // Ensure we have a valid connection
        if (conn != null && !conn.isClosed()) {
            return conn.prepareStatement(sqlStatement);  // Prepare and return a new PreparedStatement
        } else {
            throw new SQLException("Connection is null or closed. Cannot prepare statement.");  // Handle null or closed connection
        }
    }

    /**
     * Closes the database connection and any provided {@code PreparedStatement}.
     *
     * @param ps the {@code PreparedStatement} to close.
     */
    public static synchronized void closeConnection(PreparedStatement ps) {
        try {
            if (ps != null && !ps.isClosed()) {
                ps.close();  // Close the PreparedStatement
            }
            if (conn != null && !conn.isClosed()) {
                conn.close();  // Close the connection
                conn = null;
                logConnectionStatus("Database connection closed.");
            }
        } catch (SQLException e) {
            logConnectionStatus("Failed to close PreparedStatement or connection.");
            e.printStackTrace();
        }
    }

    /**
     * Overloaded method to close the database connection without needing a {@code PreparedStatement}.
     */
    public static synchronized void closeConnection() {
        closeConnection(null);  // Call the other closeConnection method with null
    }

    /**
     * Logs the connection status.
     *
     * @param message the message to log.
     */
    public static void logConnectionStatus(String message) {
        System.out.println(message);  // Print the message to the console
    }
}

**Comment by IRus** [comment]
@Hamed0911 could you format code using backticks? It's unreadable in this state

**Comment by brettwooldridge** [comment]
Ask this on stackoverflow or to ChatGPT.
