### ISSUE TITLE
Active connection not released

### ISSUE THREAD

**Issue by joveth1** [brettwooldridge/HikariCP#2236]
I'm using springboot 2.3.12 with HikariCP 3.4.5 and my databse is postgresql

My project runs well before. But one day it  throws exception:

`HikariPool-1 - Connection is not available, request timed out after 30001ms`

Then I restarted it, but after some hours or few days, the exception comes again.

I opend the hikari debug logs, and saw that,after some hours the active connections still not released, like this(I have observe two hours the active connections grews to 9):

`HikariPool-1 - Pool stats (total=30, active=9, idle=21, waiting=0)`

So I guess when all the  connections are actived, the exception comes.

My config was:
```
spring.datasource.hikari.minimum-idle=30
spring.datasource.hikari.maximum-pool-size=30
spring.datasource.hikari.keepalive-time=60000
spring.datasource.hikari.max-lifetime=900000
spring.datasource.hikari.connection-timeout=5000
spring.datasource.hikari.connection-test-query=SELECT 1

```

I don't why, or maybe there is something wrong in the network model.

**Comment by DmitryShabalin** [comment]
maybe it relates with https://github.com/brettwooldridge/HikariCP/issues/2253

**Comment by brettwooldridge** [comment]
Upgrade to v6, ensure ``socketTimeout`` is configured for the driver, and ensure that ``keepAlive`` is configured for the driver (not the same as the HikariCP keepAlive setting). See main page for setting ``keepAlive`` at the OS-level.
