### ISSUE TITLE
Return error quickly when database is down

### ISSUE THREAD

**Issue by denis-arruda** [brettwooldridge/HikariCP#2254]
Is it possible to configure Hikari to quickly return an error when Hikari knows that all connections are down? Looks like it always tries to open a new connection and the request has to wait until it gets a connection timeout.

**Comment by quaff** [comment]
What if the database is recovered at the time?

**Comment by denis-arruda** [comment]
If previous connections already failed. And we already have a thread trying to connect. Should we answer quickly an error message to other threads meanwhile?

**Comment by brettwooldridge** [comment]
It is not the pool's responsibility to determine if the database is never coming back. It is possible to reboot the database server, have it down for minutes, and have the pool recover.
