### ISSUE TITLE
Add option to fail immediately if the connection pool is fully exhausted and a connection is attempting to be retrieved

### ISSUE THREAD

**Issue by mickoallen** [brettwooldridge/HikariCP#2258]
We're in a scenario where, if the connection pool is fully exhausted, we don't want to wait around to see if we can get a connection within the timeout, we just want to fail immediately. There are a few ways we've been able to do this but i'm wondering if there is any appetite adding this functionality in to the library itself?

Thanks

**Comment by brettwooldridge** [comment]
Not much appetite. But I am curious about the usecase. Why not just set the connection timeout to something low?

**Comment by mickoallen** [comment]
Hey thanks for your interest.

We have many apps with sharded dbs. Some over 100 shards - which means 100 connection pools. We've had a couple of instances of:

1.  one shard getting hot
2.  the connection pool becoming exhausted
3. new inbound requests try to acquire a connection to that pool but are left spinning
4. this exhausts the inbound thread pool and then the whole host goes down

Multiple teams have come up with their own solutions that sit in front of hikari and fail fast if the connection pool is full exhausted, this at least protects the host.

Setting the connection timeout low is an improvement but we still want a way to fail fast in this scenario.

**Comment by mickoallen** [comment]
i'm happy to make a draft PR if you like?

**Comment by brettwooldridge** [comment]
Before you spend time on a PR, what would "failing" look like in a "fail fast" scenario? How would the pool "fail'? Just throw an exception from ``getConnection()``?

**Comment by mickoallen** [comment]
Yep, i think throwing an exception from getConnection() makes the most sense. There should come a time when the pool will have capacity again to return connections, but while it is fully exhausted we don't want to wait around and try.

**Comment by mickoallen** [comment]
I realized I can basically build this functionality by passing hibernate a custom connection provider that pulls the relevant data from the mxbean. Also thinking it might be less destructive to put a limit on the number of threads awaiting connections, and fail fast based on that.

**Comment by mickoallen** [comment]
Final update in case you were wondering - this works a treat using a custom connection provider.
