### ISSUE TITLE
Spring Boot CompletableFuture Fails to Release Connection to HikariPool

### ISSUE THREAD

**Issue by dungbv99** [brettwooldridge/HikariCP#2263]
Hi Brett,

I’m encountering an issue with a function that uses JPA in a multi-threaded environment. Here's the code:

```
  public void doSth() {
    List<Integer> arr = List.of(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18,19,20);

    arr.parallelStream().map(a -> CompletableFuture.supplyAsync(() -> this.serviceRepo.findAll(PageRequest.of(a, 10)), this.productExecutorService)
        .exceptionally(
            ex -> {
              log.error("err {}", ex, ex.getMessage());
              return null;
            }))
        .map(CompletableFuture::join)
        .collect(Collectors.toList());
  }
```
The Problem
When multiple API calls invoke this function concurrently, I observe the following issue:

Even though the CompletableFuture tasks complete, the database connections are not immediately returned to the HikariCP pool.

When inspecting the connection state in the database, all connections appear idle (see screenshot below):

<img width="1351" alt="Screenshot 2024-11-19 at 14 08 54" src="https://github.com/user-attachments/assets/066bbdec-f6fb-4462-820a-bd596fb9d485">

However, the application logs indicate these connections are still active:
<img width="1407" alt="Screenshot 2024-11-19 at 14 11 14" src="https://github.com/user-attachments/assets/4e96651b-c42c-4fd2-a86d-12fb57d29819">

This eventually leads to the error:
`Unable to acquire JDBC connection`

Could you help investigate why the connections aren’t being released promptly and suggest potential fixes?

**Comment by brettwooldridge** [comment]
Have you ensured that the ``hibernate.connection.release_mode`` is set to ``after_statement`` instead of ``after_transaction``? I'm not a Hibernate guy, but this seems to be the cause of a lot of unclosed connection issues.

Regarding the code, [here is what ChatGPT said](https://chatgpt.com/share/6740c8c8-e450-800e-920b-55099b3fa994).

**Comment by dungbv99** [comment]
@brettwooldridge 
I found the solution for this problem. we can enable: spring.jpa.open-in-view=true to make the connection can return after execute
