### ISSUE TITLE
Graceful shutdown or changing configuration at runtime?

### ISSUE THREAD

**Issue by terencez127** [brettwooldridge/HikariCP#228]
Hi,

I'm working on replacing BoneCP with HikariCP in our project since BoneCP has been deprecated. In our project we need the ability to change the connection pool's configuration at runtime, with BoneCP we were able to do it by shuting down the old pool and creating a new one, BoneCP pool can be shut down gracefully and it will monitor the active connections in the old pool and close them when they are done. But it seems HikariCP doesn't have similar option, it closes all connections when the pool is shut down. 

Anyone knows if there is some parameter in HikariCP for this purpose? I have gone through the source code and haven't found any, but just wanna make sure. HikariCP has been working well with our project, I really like the cleanliness of the code, I'm thinking of implementing this feature if it's not available, BoneCP could be a good reference.

Thanks

**Comment by brettwooldridge** [comment]
@terencez127 Some parameters of HikariCP can be changed via JMX while the pool is running, such as ``connectionTimeout``, ``idleTimeout``, ``leakDetectionThreshold``, ``maxLifetime``, ``maxPoolSize``, and ``minimumIdle``.

What configuration in particular are you trying to change?

**Comment by terencez127** [comment]
@brettwooldridge Thanks for the quick reply! 
JMX is the missing piece I didn't find : ). Most of the params you listed are what we need, besides them we need `dataSourceProperties` and `isAutoCommit` to be changed at runtime as well.

**Comment by brettwooldridge** [comment]
@terencez127 HikariCP does not support changing properties of the underlying datasource at runtime (this includes auto-commit and transaction isolation).  However, if you have your own wrapper DataSource that supports switching from an old pool to a new pool, I think that HikariCP can support that use case.

Using JMX you can invoke the ``softEvictConnections`` operation on the HikariCP pool MBean, which will close all idle connections and will mark all in-use connections to be closed when they return to the pool.

So basically, your DataSource would need to:
* Have a way to switch datasources (method or other trigger)
* Create a new HikariCP pool to be used for new callers to ``getConnection()`` (on your DataSource)
* Set ``minimumIdle`` to ``0`` on the "old" HikariCP pool (via the MBean)
* Call ``softEvictConnections`` on the "old" HikariCP pool (via the MBean)
* Optionally, spawn a thread to monitor the "old" HikariCP pool's ``totalConnections``  (via the MBean), and call ``shutdown`` on the HikariDataSource when it reaches ``0``.

**Comment by terencez127** [comment]
@brettwooldridge Thx for the detailed explanation of the approach. 

What I'm doing right now is most the same as you described, I create a new pool each time the config is changed, then set `maximumPoolSize` to pool's `ActiveConnections` (I tried `minimumIdle` but it didn't work as expected, but I just realize that it's likely because the `idleTimeout` value I set was so big that idle connections recycling process never got started, I will test it later), then use a [ScheduledThreadPoolExecutor](http://docs.oracle.com/javase/7/docs/api/java/util/concurrent/ScheduledThreadPoolExecutor.html) to check the old pools periodically and close them when they've done their jobs. 

I'm doing tests on my approach and it's been working well for me so far. Also good to know that I could use `softEvictConnections`.

**Comment by shashankcg** [comment]
> @terencez127 HikariCP does not support changing properties of the underlying datasource at runtime (this includes auto-commit and transaction isolation). However, if you have your own wrapper DataSource that supports switching from an old pool to a new pool, I think that HikariCP can support that use case.
> 
> Using JMX you can invoke the `softEvictConnections` operation on the HikariCP pool MBean, which will close all idle connections and will mark all in-use connections to be closed when they return to the pool.
> 
> So basically, your DataSource would need to:
> 
> * Have a way to switch datasources (method or other trigger)
> * Create a new HikariCP pool to be used for new callers to `getConnection()` (on your DataSource)
> * Set `minimumIdle` to `0` on the "old" HikariCP pool (via the MBean)
> * Call `softEvictConnections` on the "old" HikariCP pool (via the MBean)
> * Optionally, spawn a thread to monitor the "old" HikariCP pool's `totalConnections`  (via the MBean), and call `shutdown` on the HikariDataSource when it reaches `0`.

Is this still the recommended way to refresh configuration of a pool in 2021?

**Comment by Saiprakash9** [comment]
@brettwooldridge can you please answer the above question by @shashankcg I'm looking for same.
