### ISSUE TITLE
alibaba/druid pool analysis 

### ISSUE THREAD

**Issue by manikantag** [brettwooldridge/HikariCP#232]
Hi, I find your analysis on Java DB pools very informative. I happen to come across this 'druid' pool from Alibaba: https://github.com/alibaba/druid/wiki/FAQ (claims as the fastest DB pool in Java!).

From my very quick glance, seems it has some cool features. Any thoughts on this. Thanks.

**Comment by brettwooldridge** [comment]
A quick run of the benchmark on my desktop PC yielded the following:
```
Benchmark                                 (pool)   Mode  Samples       Score  Units
c.z.h.b.ConnectionBench.cycleCnnection    hikari  thrpt       16   21206.330  ops/ms
c.z.h.b.ConnectionBench.cycleCnnection    bone    thrpt       16   10389.139  ops/ms
c.z.h.b.ConnectionBench.cycleCnnection    vibur   thrpt       16    6764.233  ops/ms
c.z.h.b.ConnectionBench.cycleCnnection    tomcat  thrpt       16    2117.792  ops/ms
c.z.h.b.ConnectionBench.cycleCnnection    c3p0    thrpt       16     128.447  ops/ms
c.z.h.b.ConnectionBench.cycleCnnection    druid   thrpt       16     110.370  ops/ms

c.z.h.b.StatementBench.cycleStatement     hikari  thrpt       16  130426.003  ops/ms
c.z.h.b.StatementBench.cycleStatement     tomcat  thrpt       16   62071.180  ops/ms
c.z.h.b.StatementBench.cycleStatement     druid   thrpt       16   54845.335  ops/ms
c.z.h.b.StatementBench.cycleStatement     vibur   thrpt       16   33414.774  ops/ms
c.z.h.b.StatementBench.cycleStatement     bone    thrpt       16   26551.919  ops/ms
c.z.h.b.StatementBench.cycleStatement     c3p0    thrpt       16   15956.412  ops/ms
```
So, at least in our benchmark, Druid was the *slowest* for obtaining and returning connections, and the third fastest for creating and closing statements.

Druid was configured with similar settings to other pools in the benchmark:
```java
druid.setInitialSize(0);
druid.setMinIdle(0);
druid.setMaxActive(32);
druid.setMaxWait(5000);
druid.setValidationQuery("SELECT 1");
druid.setTestOnBorrow(true);
druid.setDefaultAutoCommit(false);
druid.setDefaultTransactionIsolation(Connection.TRANSACTION_READ_COMMITTED);
```
The benchmark page in their wiki does not show what settings they ran with, but I suspect that they disabled test-on-borrow.  While I won't say that is "cheating", it is not how I would run a production pool.  They also do not provide the source code to their test, as far as I can tell.

**Comment by bobwenx** [comment]
druid was designed to focus on monitor and data access behavior enhance(like automatically database slice). it provides an SQL parser to analyze user's SQL query and delegate most JDBC class to collect metrics. 
so if what you need is a JDBC monitor solution like newrelic, you may try Druid.

**Comment by brettwooldridge** [comment]
@bobwenx It is a valid point.  I will point out that New Relic is also supported by HikariCP through the DropWizard Metrics integration, but the metrics provided are "pool-level" metrics and not specific to query execution time, etc.

**Comment by wenshao** [comment]
If you configure maxWait property, druid pool use "fair mode ReentrantLock", it's bad performance.

https://github.com/alibaba/druid/blob/master/src/main/java/com/alibaba/druid/pool/DruidAbstractDataSource.java
```java
    public void setMaxWait(long maxWaitMillis) {
        if (maxWaitMillis == this.maxWait) {
            return;
        }

        if (maxWaitMillis > 0 && useUnfairLock == null && !this.inited) {
            final ReentrantLock lock = this.lock;
            lock.lock();
            try {
                if ((!this.inited) && (!lock.isFair())) {
                    this.lock = new ReentrantLock(true);
                    this.notEmpty = this.lock.newCondition();
                    this.empty = this.lock.newCondition();
                }
            } finally {
                lock.unlock();
            }
        }

        if (inited) {
            LOG.error("maxWait changed : " + this.maxWait + " -> " + maxWaitMillis);
        }

        this.maxWait = maxWaitMillis;
    }
```
This is by design, because we had some problems in the production environment. Here are the relevant documents, but I'm sorry, it is in Chinese.
https://github.com/alibaba/druid/wiki/Druid%E9%94%81%E7%9A%84%E5%85%AC%E5%B9%B3%E6%A8%A1%E5%BC%8F%E9%97%AE%E9%A2%98

Druid of PreparedStatementCache optimized, this is very important to enhance the mysql 5.5 & oracle & sqlserver & db2 performance.

Druid has very stable ExceptionSorter, including Oracle / MySql / Alibaba Oceanbase etc.

In [Taobao large-scale high concurrency environment](http://www.forbes.com/sites/jlim/2015/11/10/alibaba-group-sells-5bn-in-first-90-minutes-of-11-11-sale/#3de3850f1449), only two connection pools to work very well, [druid](https://github.com/alibaba/druid) and jboss connection pool.

Druid is not just a connection pool, he can do a very good extension, similar to Filter-Chain extension. Built-in Filter include [WallFilter](https://github.com/alibaba/druid/wiki/%E7%AE%80%E4%BB%8B_WallFilter), [StatFilter](https://github.com/alibaba/druid/wiki/%E9%85%8D%E7%BD%AE_StatFilter), [LogFilter](https://github.com/alibaba/druid/wiki/%E9%85%8D%E7%BD%AE_LogFilter). Which can WallFilter defense SQL injection, StatFilter can do performance monitoring, LogFilter can output SQL logs.

Druid built very strong monitoring support. demo: http://198.11.179.104/druid/index.html

**Comment by DR-YangLong** [comment]
温少不能忍了，哈哈哈

**Comment by hrchu** [comment]
Hmmm I only see it claims as the best DB pool in Java, instead of the fast... :confused:

**Comment by p0mp0k0** [comment]
Does wenshao or brettwooldridge can do the benchmark test according to druid characteristic and brettwooldridge's HikariCP benchmark source code? I think most people want to get a conclusion who is interesting in the performance of connection pool.

**Comment by ulfsar** [comment]
final result was???

**Comment by brettwooldridge** [comment]
Are you asking HikariCP?  Benchmark results  were in the first reply.

**Comment by iamybj** [comment]
@wenshao 
 connection  pool is connection pool ， 吓鸡巴添加你麻痹的没有用的功能啊。

**Comment by JackFish** [comment]
Benchmark                       (jdbcUrl)  (maxPoolSize)  (pool)   Mode  Cnt      Score      Error   Units
ConnectionBench.cycleCnnection  jdbc:stub             32   druid  thrpt   16   3144.688 ±  216.803  ops/ms
ConnectionBench.cycleCnnection  jdbc:stub             32  hikari  thrpt   16  42262.816 ± 1954.972  ops/ms
ConnectionBench.cycleCnnection  jdbc:stub             32   dbcp2  thrpt   16   1988.912 ±   29.686  ops/ms
ConnectionBench.cycleCnnection  jdbc:stub             32  tomcat  thrpt   16   1849.525 ±  213.140  ops/ms
ConnectionBench.cycleCnnection  jdbc:stub             32    c3p0  thrpt   16    642.396 ±   11.501  ops/ms
ConnectionBench.cycleCnnection  jdbc:stub             32   vibur  thrpt   16   4913.682 ±  400.545  ops/ms
StatementBench.cycleStatement   jdbc:stub             32   druid  thrpt   16  43187.450 ±  617.061  ops/ms
StatementBench.cycleStatement   jdbc:stub             32  hikari  thrpt   16  58916.066 ± 4954.865  ops/ms
StatementBench.cycleStatement   jdbc:stub             32   dbcp2  thrpt   14    540.265 ±  645.336  ops/ms
StatementBench.cycleStatement   jdbc:stub             32  tomcat  thrpt   16  78930.496 ± 2561.000  ops/ms
StatementBench.cycleStatement   jdbc:stub             32    c3p0  thrpt   16  13162.639 ±  728.747  ops/ms
StatementBench.cycleStatement   jdbc:stub             32   vibur  thrpt   16  26241.060 ± 1496.388  ops/ms

Seems tomcat got higher performace in StatementBench test

**Comment by FutureElement** [comment]
druid有阿里大数据量的验证，而HikariCP没有

**Comment by brettwooldridge** [comment]
What validation?

**Comment by FutureElement** [comment]
长期的使用，有阿里长期的大数据量的使用的验证

**Comment by brettwooldridge** [comment]
HikariCP is one of the most widely used connection pools in the world, used by some of the largest companies, serving literally billions of users per day.  Druid is rarely seen outside of China.

**Comment by FutureElement** [comment]
used by some of the largest companies？serving literally billions of users per day？
For example？

**Comment by brettwooldridge** [comment]
Wix.com by itself, for example hosts over 109 million websites and serves over 1 Billion requests per day.  Atlassian has millions of customers for its products -- no published numbers exists for daily usage.

HikariCP is the default pool for every application built with the Play framework, Slick, JOOS, and is now the default pool for Spring Boot.

HikariCP is resolved from the central maven repository over 300,000 times per month.

[Companies known to be using HikariCP](https://github.com/brettwooldridge/HikariCP/blob/dev/documents/Wall-of-Fame.md).

**Comment by william8188** [comment]
To be honest, I prefer HikariCP 👍

**Comment by DR-YangLong** [comment]
我认为2个组件专注的方向不一样，各有特色和优点，不是组件如何，要看使用组件的人如何考虑，综合自己的需求选用，druid非常大一部分是为了监控和运维

**Comment by pangding1987125** [comment]
it's very intersting druid and HikariCP are  competing with each other ,and useful for users to use better tools in the future.

**Comment by syukoushin** [comment]
一个印度小哥引发的口水战？

**Comment by lfbayer** [comment]
This issue was marked as closed over 3 years ago. GitHub is not the correct place for general discussion. If there are specific other issues, please open a new issue.

**Comment by IceMimosa** [comment]
😂好无聊的事情。
