### ISSUE TITLE
Allow separate maximum timeout for Jdbc4 connection isValid

### ISSUE THREAD

**Issue by fwi** [brettwooldridge/HikariCP#234]
I would like the option to specify a separate maximum timeout for the `connection.isValid(int)` call.

During database disaster-scenario testing, I came across broken database connections which do not report a "broken connection" error while waiting for a reply. Part of the disaster testing was moving an IP-address from one (database) machine to another, which resulted in threads waiting for a reply from the database server that would never arrive. This was especially nasty for threads that just fired a `commit`: there is no timeout on commit (MySQL connector J), so the only way to unstuck these threads was to set a `socketTimeout` (which has to be larger than your longest running query).

Now this can happen during an Jdbc4 Validation `isValid` call too and from what I can see this will wait a maximum of `connectionTimeout`. But I set `connectionTimeout` to a value that includes time for waiting for a connection to become available when all connections are in use, which is not the same as the time needed to check if a connection is valid. I would like HikariCP to flush out the broken connections (as with the disaster testing) rather quickly, e.g. within 5 seconds, but without affecting the `connectionTimeout` overall (e.g. set at 50 seconds).

Some background:

I came across the various timeouts while reading [issue 230](https://github.com/brettwooldridge/HikariCP/issues/230). 
I tracked the `isValid` timeout from [BaseHikariPool.java](https://github.com/brettwooldridge/HikariCP/blob/dev/hikaricp-common/src/main/java/com/zaxxer/hikari/pool/BaseHikariPool.java) which calls `isConnectionAlive` (line 186) with `connectionTimeout`

`isConnectionAlive` is implemented at [HikariPool.java](https://github.com/brettwooldridge/HikariCP/blob/dev/hikaricp/src/main/java/com/zaxxer/hikari/pool/HikariPool.java) (line 125) which calls `connection.isValid(timeoutSeconds)` if `isUseJdbc4Validation` is `true`.

In the MySQL driver `isValid` calls `sendCommand` with the timeout given to `isValid`.
The timeout is set via `socket.setSoTimeout` and reset to the previous value (if any) after the ping-command is done. See [MysqlIO.java](http://bazaar.launchpad.net/~mysql/connectorj/5.1/view/head:/src/com/mysql/jdbc/MysqlIO.java) `sendCommand` is at line 2329.

**Comment by brettwooldridge** [comment]
This is a reasonable enhancement request.

We will introduce a ``validationTimeout`` that is used for both ``isValid()`` and query-based validation (through ``setNetworkTimeout()`` if available).  We may impose the limitation that ``isValid()`` cannot be used if a ``validationTimeout`` of less than 1000ms is specified.

**Comment by fwi** [comment]
OK, thanks, that sounds good. In my view, this is a "minor" enhancement that can be implemented whenever the time is right. I also think the 1 second validation timeout is an absolute minimum: anything less could mark connections invalid incorrectly when the network is (temporary) slow.

**Comment by brettwooldridge** [comment]
This is implemented now in the ``dev`` branch if you want to test it.  Just do:
```
git clone https://github.com/brettwooldridge/HikariCP.git
cd HikariCP
git checkout dev
mvn install
```
Using Java 8 to build, and use ``2.3.1-SNAPSHOT`` as your maven dependency, or use the ``HikariCP-2.3.1-SNAPSHOT.jar`` or ``HikariCP-java6-2.3.1-SNAPSHOT.jar`` in the *target* directory directly.

**Comment by brettwooldridge** [comment]
You can test this enhancement using the 2.3.1-SNAPSHOT version in the Sonatype snapshots repository.

Add this to your ~/.m2/settings.xml:
```xml
<profiles>
  <profile>
     <id>allow-snapshots</id>
        <activation><activeByDefault>true</activeByDefault></activation>
     <repositories>
       <repository>
         <id>snapshots-repo</id>
         <url>https://oss.sonatype.org/content/repositories/snapshots</url>
         <releases><enabled>false</enabled></releases>
         <snapshots><enabled>true</enabled></snapshots>
       </repository>
     </repositories>
   </profile>
</profiles>
```

**Comment by fwi** [comment]
Enhancement more or less verified in release 2.3.1 and 2.3.2: the `validationTimeout` option is available, configurable (via JMX) and used when validating a connection. But it will take a while before I get a chance to replay the disaster recovery scenario (the real 'proof in the pudding' if you like).
