### ISSUE TITLE
add method which can detect dead DB

### ISSUE THREAD

**Issue by chaeyk** [brettwooldridge/HikariCP#235]
When DB is dead, HikariCP's getConnection() waits for connectionTimeout.
I think that is reasonable when I use single DB.
But, if I use multiple DB for high availity,
I should try getConnection() from next pool immediately
when getConnection() failed from one pool.

I think below two feature would be good for high availity implementation.
 * getConnection() fails immediately when DB is down.
 * add method to detect pool's DB is alive or dead.

**Comment by brettwooldridge** [comment]
HikariCP is not designed to provide high-availablity, fail-over, or load-balancing.  These are functions that should be and are provided by many JDBC drivers.  Their mechanism of action is transparent to HikariCP.

Eg. MySQL see:

[Configuring Load Balancing with Connector/J](http://dev.mysql.com/doc/connector-j/en/connector-j-usagenotes-j2ee-concepts-managing-load-balanced-connections.html)

[Configuring Failover with Connector/J](http://dev.mysql.com/doc/connector-j/en/connector-j-usagenotes-j2ee-concepts-load-balancing-failover.html)

Microsoft SQL also supports this via the following connection URL ``jdbcUrl="jdbc:sqlserver://mainserver:1433;failoverPartner=backupserver;``.  Oracle offers similar solutions, as does PostgreSQL (``jdbc:postgresql://masterHost:port,slaveHost:port/db_name``).
