### ISSUE TITLE
Improve error message for bad property name

### ISSUE THREAD

**Issue by fwi** [brettwooldridge/HikariCP#240]
I'm sorry to be nitpicking here, but this is one of the first error messages you can encounter when starting with HikariCP:

ERROR c.z.hikari.util.PropertyBeanSetter - Property initializeFailFast <b>is does</b> not exist on target <b>class class</b> com.zaxxer.hikari.HikariConfig

The other error message in [PropertyBeanSetter](https://github.com/brettwooldridge/HikariCP/blob/dev/hikaricp-common/src/main/java/com/zaxxer/hikari/util/PropertyBeanSetter.java) is also likely to print "class" twice.

**Comment by brettwooldridge** [comment]
HikariCP 2.3.2 has been released with a fix for this issue.

**Comment by fwi** [comment]
Fix verified in release :-)
