### ISSUE TITLE
Failure listener

### ISSUE THREAD

**Issue by voidmain** [brettwooldridge/HikariCP#241]
We have been using BoneCP for a while and are looking to switch off it to Hikari. The last feature that we need to migrate over is the ability to get notifications from the CP when it fails to connect to the database.  We need this because we have an API that provides health check information about various services in our application. This includes the connection to the database.

In BoneCP, we implemented their ConnectionHook interface and captured the onAcquireFail messages. We would like something similar in HikariCP to keep this information in our status check API.

I wanted to open this issue (feature request) to start the discussion. I'll also look at implementing this myself and sending in a pull request (today if I have time).

**Comment by brettwooldridge** [comment]
@voidmain I understand your use-case.  We do try to keep the "surface area" of the HikariCP configuration to a minimum; [somewhat fanatically] minimizing the number of properties that are exposed.  As HikariCP already supports [Dropwizard Metrics](https://dropwizard.github.io/metrics/3.1.0/), which is fairly trivial to configure.  And Metrics already includes a [HealthCheck](https://dropwizard.github.io/metrics/3.1.0/manual/healthchecks/) ([another example](https://dropwizard.github.io/metrics/3.1.0/getting-started/#health-checks)), we propose exposing not only connection failures but other "unhealthy" conditions of the pool through their interface.  Of course you have programmatic access to these.

As an added benefit, Metrics also exposes all of its monitoring information through JMX (if desired), HTTP/JSON, and integrations exist for monitoring systems like [New Relic](http://newrelic.com/server-monitoring).

**Comment by brettwooldridge** [comment]
The Health Check would of course be in addition to all the other [chocolatey goodness](https://github.com/brettwooldridge/HikariCP/wiki/Codahale-Metrics) that HikariCP currently exposes through Metrics.

**Comment by voidmain** [comment]
This might already be how it is implemented (haven't gotten into the code quite yet), but it seems to me that using a HikariCP interface for all of this instead of directly calling Dropwizard might help keep separation. The default implementation for this interface could be a bridge to DropWizard Metrics. You could discover the default implementation based on the classpath or allow an implementation to be passed into the pool directly. This would allow clients to not depend on Dropwizard Metrics. 

I'm guessing there are situations where people can't or don't want to pull in a 3rd party library like Dropwizard and would prefer to implement your interface instead.

I'll have to look more at Dropwizard, but if it is opening ports or starting servers, it probably won't work for us. I'm guessing all of that is configurable though.

**Comment by brettwooldridge** [comment]
Dropwizard is definitely configurable, and it won't start servers or open ports.  We will consider abstracting an interface, but Dropwizard (formerly Codahale Metrics) is pretty much synonymous with Java performance monitoring at this point.  Googling "java metrics" yields Dropwizard as the top three hits.

**Comment by voidmain** [comment]
Brett, I've successfully integrated Dropwizard through our entire stack and hooked it up to HikariCP as well. It works well for metrics but it doesn't appear to provide any "Health Checks". Hopefully this would be simple to provide if the classpath contains the metrics-healthchecks JAR.

Having a Health Check in HikariCP will help us generate alerts through Pingdom and other services we use. CleanSpeak contains an API that now uses Dropwizard Health Checks and returns either a **200** or **500** depending on whether or not all the checks pass. If HikariCP could use the `Connection.isValid()` method or something like that in a Health Check, I think we would be all set.

I'll go ahead and write this myself, but it might be nice to add to HikariCP.

**Comment by brettwooldridge** [comment]
@voidmain HikariCP currently does not support any Health Checks, doing so was our proposed solution to your initial request for a BoneCP-like ConnectionHook interface.  We are working on adding Health Checks as I write this, and you can expect a snapshot to be available in the repository in the next few days.

**Comment by voidmain** [comment]
Got it. I missed that you "propose" the health check. It was just a bit unclear.

**Comment by brettwooldridge** [comment]
@voidmain HikariCP 2.3.2 has been released.  Documentation for the health checks can be found here:

https://github.com/brettwooldridge/HikariCP/wiki/Dropwizard-HealthChecks

**Comment by voidmain** [comment]
Just wanted to update that we have upgraded and everything looks good. Thanks.
