### ISSUE TITLE
LeakTask Exception Message

### ISSUE THREAD

**Issue by mvieghofer** [brettwooldridge/HikariCP#242]
Using the LeakTask to detect possible connection leaks works perfectly. However, a lot of people think the logged stacktrace was produced by a NullPointerException. The reason for this is, that the LeakTask creates a new Exception without a message. Therefore the logged exception will look something like this:

    2015-01-15 16:07:41,953 Connection leak detection triggered, stack trace follows
    java.lang.Exception: null
	at     com.zaxxer.hikari.hibernate.HikariConnectionProvider.getConnection(HikariConnectionProvider.java:99) ~[HikariCP-java6-2.0.1.jar:na]
    ...

This is rather confusing especially for people who do not know a lot about the connection pool. It would be great if this could be changed, so that the message of the Exception isn't `null` anymore.

**Comment by brettwooldridge** [comment]
HikariCP 2.3.2 has been released with a fix for this issue.

**Comment by mvieghofer** [comment]
Thanks!

Brett Wooldridge <notifications@github.com> schrieb am Fr., 30. Jan. 2015
12:03:
