### ISSUE TITLE
Batch Insert and Updates not working with Hibernate4+HikariCP

### ISSUE THREAD

**Issue by zedomel** [brettwooldridge/HikariCP#243]
I could not have batch inserts/updates to work using HikariCP with Hibernate4. It works with C3P0 and BoneCP, but using the same configuration it does not work for HikariCP.
I analyzed MySQL general logs to see the queries been executed and when using HikariCP the insert statements are not batched. 
I can give mor information as requested: Hibernate configurations, java code, etc.

thnaks.

**Comment by brettwooldridge** [comment]
@zedomel As far as we know, there is nothing within HikariCP that should prevent batching in any way.  Any information you can provide, such as Hibernate configurations, will be helpful determining the cause of the observed behavior.

**Comment by zedomel** [comment]
@brettwooldridge I have attached some information about Hibernate configuration and MySQL general log when using C3P0 and HikariCP. 

Here the XML Hibernate configuration: http://pastebin.com/6UEQhxvT (note that I have included both configurations to save create a new pastebin. When I'm using HikariCP I commented out the lines of C3P0, and vice versa).

Here the MySQL general log using C3P0 and HikariCP:  http://pastebin.com/L0MDkDUT

In Java to do insertions I'm following the Hibernate manual: http://docs.jboss.org/hibernate/core/4.3/manual/en-US/html/ch15.html#batch-inserts

Using C3P0 I could reduce the execution time to half of the time using HikariCP, due the batch inserts. BoneCP also produces batch inserts, and now I'm testing its executon time.

thanks.

**Comment by brettwooldridge** [comment]
@zedomel Thanks for this assets.  I'll continue to look at them, but something jumps out immediately, so I'll point it out:
```xml
...
<property name="hibernate.hikari.dataSourceClassName">com.mysql.jdbc.jdbc2.optional.MysqlDataSource</property>
<property
name="hibernate.hikari.dataSource.url">jdbc:mysql://localhost/STINGRDB?rewriteBatchedStatements=true</property>
...
```
While the MysqlDataSource accepts a URL, I'm not sure that it fully parses it the same compared to its "driver-based" configuration.  I have two alternatives for you to try...

First, keeping with the MysqlDataSource, remove
```xml
<property
name="hibernate.hikari.dataSource.url">jdbc:mysql://localhost/STINGRDB?rewriteBatchedStatements=true</property>
```
and try:
```xml
<property
name="hibernate.hikari.dataSource.url">jdbc:mysql://localhost/STINGRDB</property>
<property name="hibernate.hikari.dataSource.rewriteBatchedStatements">true</property>
```
Second, if you want to go with "driver-based" configuration, drop some of the HikariCP-specific properties, and like C3P0 use the Hibernate equivalents.  Eliminate: ``hibernate.hikari.dataSourceClassName``, ``"hibernate.hikari.dataSource.url``, ``hibernate.hikari.dataSource.user``, and ``hibernate.hikari.dataSource.password``.  The connection provider knows how to pick-up those from ``connection.url``, ``connection.driver_class``, etc.

Lastly, if you are using Hibernate 4.3.6+ use their ``org.hibernate.hikaricp.internal.HikariCPConnectionProvider`` instead of the HikariCP provided one, it supercedes it.

**Comment by zedomel** [comment]
@brettwooldridge thanks for suggestions. Probably it is a miss configuration and not bug. I was using Hibernate 4.3.6, following your instructions I downloaded Hibernate 4.3.8, but hibernate does not come with hibernate-hikari jar built. So I'm building it as suggest by Hibernate wiki. I will try and come back with results soon.
thanks.

**Comment by brettwooldridge** [comment]
@zedomel I think in general, for your use-case, the HikariCP connection provider would actually probably work just fine, but at the same time it is probably good to run the "officially sanctioned" version from Hibernate.

**Comment by zedomel** [comment]
@brettwooldridge I migrated from Hibernate 4.3.6 to 4.3.8 and have implemented your suggestions, but batch insert/update's are not working yet. Now I'm using the following configuration:
```xml
<property name="hibernate.connection.provider_class">org.hibernate.hikaricp.internal.HikariCPConnectionProvider</property>
<property name="connection.url">jdbc:mysql://localhost/STINGRDB</property>
<property name='connection.driver_class'>com.mysql.jdbc.Driver</property>
<property name='connection.username'>sting</property>
<property name='connection.password'>sting</property>	
<property name="hibernate.jdbc.batch_size">100</property>
<property name="hibernate.order_inserts">true</property>
<property name="hibernate.order_updates">true</property>
```

I also have tried to used 
```xml
<property
name="hibernate.hikari.dataSource.url">jdbc:mysql://localhost/STINGRDB</property>
<property name="hibernate.hikari.dataSource.rewriteBatchedStatements">true</property>
```
Instead of "drived-based" configuration, but I got this error: 
```
com.zaxxer.hikari.HikariConfig : when specifying driverClassName, jdbcUrl must also be specified
```

**Comment by brettwooldridge** [comment]
@zedomel Using this configuration that you posted (it works without batching, right?):
```xml
<property name="hibernate.connection.provider_class">org.hibernate.hikaricp.internal.HikariCPConnectionProvider</property>
<property name="connection.url">jdbc:mysql://localhost/STINGRDB</property>
<property name='connection.driver_class'>com.mysql.jdbc.Driver</property>
<property name='connection.username'>sting</property>
<property name='connection.password'>sting</property>   
<property name="hibernate.jdbc.batch_size">100</property>
<property name="hibernate.order_inserts">true</property>
<property name="hibernate.order_updates">true</property>
```
Can you add ``rewriteBatchedStatements=true`` back to the ``connection.url``?  But actually, I didn't think that Hibernate needed ``rewriteBatchedStatements`` to employ batching.

Can you enable debug logging for Hibernate if batching is still not working and pastebin it (redacting any sensitive information)?

**Comment by fwi** [comment]
I just finished updating [HibHik](https://github.com/intercommit/hibhik) to include a batch-insert test. The test output (shown on main page, near the end) shows that batch-inserts are working (at least for HSQLDB).  A MySQL example configuration is available [here](https://github.com/intercommit/hibhik/blob/master/src/test/resources/db-mysql.properties). The `rewriteBatchedStatements` parameter is only needed to let MySQL bundle all individual insert statements into one insert statement.

One warning: using Maven artifact `hibernate-hikaricp` pulls in a very old version of HikariCP and Maven will not warn about version conflicts (took me an hour to discover this after encountering some strange errors).

**Comment by zedomel** [comment]
I will enable Hibernate debug and post the contents in pastebin. How do you compile hibernate-hikari? I changed the <code> libraries.gradle </code> provided with Hibernate 4.3.8 to pull the version 2.3.1 of HikariCP, but it does not compile any more using: <code> ./gradlew build </code>
```java
Execution failed for task ':hibernate-hikaricp:compileJava'.
> java.lang.IllegalArgumentException
```

**Comment by brettwooldridge** [comment]
@zedomel I've never compiled hibernate-hikari, it was written by the Hibernate team.  I'm going to investigate the HibHik example.  What happens if you remove ``hibernate.hikari.dataSource.useServerPrepStmts=true``?

**Comment by brettwooldridge** [comment]
Actually, if it works with C3P0, try removing all datasource options from HikariCP that are not also used by your C3P0 example.  For example, remove all of these and see if batching starts:
```xml
<property name="hibernate.hikari.dataSource.cachePrepStmts">true</property>
<property name="hibernate.hikari.dataSource.prepStmtCacheSize">250</property>
<property name="hibernate.hikari.dataSource.prepStmtCacheSqlLimit">2048</property>
<property name="hibernate.hikari.dataSource.useServerPrepStmts">true</property>
```

**Comment by zedomel** [comment]
@brettwooldridge thanks a lot for you help. I finally did it work. Initially I was using Hibernate4.3.6 and HikariCP 2.2.5. Perhaps Hibernate4.6 did not work well with Hikari, due it was only "integrated" in later versions (4.3.7 and 4.3.8), or forgive me, I have missed same thing. Now, batch inserts are working using follow configuration, but others configurations that I have used also have worked:

```xml
<property name="hibernate.connection.provider_class">com.zaxxer.hikari.hibernate.HikariConnectionProvider</property>
<property name="hibernate.hikari.maximumPoolSize">2</property>
<property name="hibernate.hikari.idleTimeout">30000</property>
<property name="hibernate.hikari.dataSource.rewriteBatchedStatements">true</property>
<property name="hibernate.hikari.dataSource.cachePrepStmts">true</property>
<property name="hibernate.hikari.dataSource.prepStmtCacheSize">250</property>

<property name="hibernate.hikari.dataSource.prepStmtCacheSqlLimit">2048</property>
<property name="hibernate.hikari.dataSource.useServerPrepStmts">true</property>
<property name="hibernate.hikari.transactionIsolation">TRANSACTION_READ_COMMITTED</property>
<property name="hibernate.hikari.autoCommit">false</property>
```

Now everything works fine and I could improved the speed of my program using this fast connection polling. 
Thanks for all.
and forgive for anything.

**Comment by brettwooldridge** [comment]
@zedomel There is absolutely no need to apologize.  Whenever there is an issue, however it is eventually resolved, we learn something new.  So it is never a waste of time.
