### ISSUE TITLE
Support for Oracle FAN Events & FCF

### ISSUE THREAD

**Issue by gchristiansen** [brettwooldridge/HikariCP#244]
Hi, this is more of a question/feature request.  Any chance Hikari supports now or plans to support advanced features like FAN/FCF against RAC (Clustered) database?

**Comment by brettwooldridge** [comment]
You can probably find it in our Google Group, but while we love HikariCP when it comes to Oracle we almost always recommend using the Oracle driver exclusively.  Oracle's JDBC driver contains a decent connection pool, and is tightly integrated with their fail-over and clustering at a level that is simply not possible from an external pool.

**Comment by gchristiansen** [comment]
Thanks Brett, appreciate your quick response.  I'll keep HikariCP in mind for future projects, it looks like a great framework, great job and thanks for contributing to the community.
