### ISSUE TITLE
Feature: Allow to set MaxLifetime lower than 120000ms

### ISSUE THREAD

**Issue by gabrielkiss** [brettwooldridge/HikariCP#245]
I'm trying to set the max life time setting in the HikariConfig object and it will not let me set it to 30 seconds like this `.setMaxLifetime(30*1000)`. But i get this warning then:

    WARN com.zaxxer.hikari.HikariConfig - maxLifetime is less than 120000ms, using default 1800000ms.

I know that you recommend not setting is that low as I am trying to. But Unfortunately due to circumstances that I can not change, every TCP connection that is open longer than 50 secods will be terminated in our production environment (supposedly it's a "feature" set by the admins).

**Comment by brettwooldridge** [comment]
Fixed in commit 6fd7b8a

**Comment by brettwooldridge** [comment]
HikariCP 2.3.2 has been released with a fix for this issue.

**Comment by gabrielkiss** [comment]
oh cool, this will be such a massive boost in performance. Thanks a lot!
