### ISSUE TITLE
javassist.NotFoundException: com.zaxxer.hikari.proxy.ConnectionProxy for HikariCP configured as JNDI datasource in Tomcat 8

### ISSUE THREAD

**Issue by vlad-aleksandrov** [brettwooldridge/HikariCP#251]
I configured HikariCP as JNDI datasource for Tomcat 8.0.18, and when I start Tomcat I'm gettting the following exception in Catalina log:

Caused by: java.lang.RuntimeException: Fatal exception during proxy generation
        at com.zaxxer.hikari.proxy.JavassistProxyFactory.<clinit>(JavassistProxyFactory.java:61)
        ... 26 more
Caused by: javassist.NotFoundException: com.zaxxer.hikari.proxy.ConnectionProxy
        at javassist.ClassPool.get(ClassPool.java:450)
        at javassist.ClassPool.getCtClass(ClassPool.java:515)
        at com.zaxxer.hikari.proxy.JavassistProxyFactory.generateProxyClass(JavassistProxyFactory.java:130)
        at com.zaxxer.hikari.proxy.JavassistProxyFactory.<init>(JavassistProxyFactory.java:85)
        at com.zaxxer.hikari.proxy.JavassistProxyFactory.<clinit>(JavassistProxyFactory.java:57)

Extra jars in "endorsed" directory for tomcat:

HikariCP-2.3.2.jar
javassist-3.19.0-GA.jar
log4j-1.2.16.jar
slf4j-api-1.7.2.jar
slf4j-log4j12-1.7.2.jar
ojdbc-6.jar

Java version
$ java -version
java version "1.8.0_05"
Java HotSpot(TM) 64-Bit Server VM (build 25.5-b02, mixed mode)

Resource definition in context.xml:

    <Resource name="jdbc/oracle"
            auth="Container"
            type="javax.sql.DataSource"
            registerMbeans="true"
            factory="com.zaxxer.hikari.HikariJNDIFactory"
            username="hidden"
            password="hidden"
            dataSourceClassName="oracle.jdbc.pool.OracleDataSource"
            poolName="dbpool"
            maximumPoolSize="20"
            leakDetectionThreshold="10000"
            dataSource.url="jdbc:oracle:thin:@hidden:1521/hidden"
            dataSource.implicitCachingEnabled="true"
            dataSource.statementCacheSize="512"
            />

**Comment by brettwooldridge** [comment]
Can you try moving the jars to the WAR's lib directory?

**Comment by vlad-aleksandrov** [comment]
Not really, because I want to configure database connection on webapp container (Tomcat) level and jars won't be visible there for tomcat classloader. Anyway, I think I figured out the reason and solution that works. 

Since I have HikariCP jars in `tomcat/endorsed` directory, they are loaded by bootstrap classloader. The `com.zaxxer.hikari.proxy.JavassistProxyFactory` class is trying to get it's classloader in line 55 to configure classpool in constructor (line 81):
```java
55: Thread.currentThread().setContextClassLoader(JavassistProxyFactory.class.getClassLoader());
...
81 : classPool.appendClassPath(new LoaderClassPath(this.getClass().getClassLoader()));
```
`JavassistProxyFactory.class.getClassLoader()` returns `null` to represent bootstrap classloader and it breaks all proxy classes installations later on.

As a workaround, I moving HikariCP jars in `tomcat/lib` directory.

**Comment by brettwooldridge** [comment]
Thanks for the update.  Can you think of a better way to get the classloader that would allow the jars to run in the endorsed directory?

**Comment by vlad-aleksandrov** [comment]
No prob. 

I would use thread context classloader directly in current line 81 like this
```
classPool.appendClassPath(new LoaderClassPath(Thread.currentThread().getContextClassLoader()));
```
removed static block completely and call `modifyProxyFactory()` in constructor.
