### ISSUE TITLE
Oracle Connection Timeout Polling High CPU

### ISSUE THREAD

**Issue by Ed42** [brettwooldridge/HikariCP#255]
I can't find a configuration for Oracle that doesn't result in very high timeout polling CPU usage. I tried setting a very large value, also zero (which the implementation converts to Integer.MAX_VALUE). In all cases it idles with extremely high CPU usage.

**Comment by Ed42** [comment]
I should have mentioned, this does not happen with other connection pools such as apache DBCP.

**Comment by brettwooldridge** [comment]
Can you clarify what you mean by "high timeout polling CPU usage"?  And can you post your current pool configuration?

**Comment by Ed42** [comment]
After the first query in the running application has completed, CPU meters show it idling at ~50%. Attaching a profiler to the running process shows that the Oracle timeout polling thread is using all the CPU.

Here's the Spring configuration for my data source. As mentioned, I've tried several different values for the connectionTimeout property, all with the same result.

<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans.xsd">

	
    <bean id="datasource" class="com.zaxxer.hikari.HikariDataSource">
        <property name="driverClassName" value="${jdbc.driver.className}"/>
        <property name="jdbcUrl" value="${jdbc.url}"/>
        <property name="username" value="${jdbc.username}"/>
        <property name="password" value="${jdbc.password}"/>
        <property name="connectionTimeout" value="0" />
        <property name="connectionTestQuery" value="select 1 from dual" />
        <property name="poolName" value="default_pool" />
        <property name="registerMbeans" value="true" />
    </bean>
</beans>

**Comment by brettwooldridge** [comment]
Try configuring the pool without a ``connectionTestQuery``, HikariCP will then use the JDBC 4.0 ``Connection.isValid()`` method to test connections.  If this does not address the issue, can you provide a thread-dump containing all HikariCP threads, as well as Oracle threads?

**Comment by brettwooldridge** [comment]
@Ed42 any update on this?
