### ISSUE TITLE
Q: Max connections/checkout timeouts stats 

### ISSUE THREAD

**Issue by hugebdu** [brettwooldridge/HikariCP#259]
Gentlemen, 

Please advise.
We @ Wix currently use c3p0, which comes with sort of listeners and wrappers you can use to implement your measures and we have stats collecting facility. 
We'd like to switch to HikariCP.

I've managed to implement most of our stats using Hikari's JMX/MetricsRegistry. What I'm missing is how to measure:
1. Max concurrent connections open (1h sliding window)
2. Number of checkout timeouts (1h sliding window)

C3P0 implementation we have uses connection object instrumentation, which is not available with HikariCP.
What would be the best way to have those? I can think of polling CodeHaleMetricsRegistry every n millis but that doesn't sound to me.

Thanks in advance.

D

**Comment by brettwooldridge** [comment]
With respect to "Max concurrent connections open", do you mean open between the pool and the database, or "in use" by the application?  If the former, what you want is "total connections".  If the later, what you want is "active connections".

Via Metrics, TotalConnections and ActiveConnections are ``CachedGuages`` with a refresh interval of 10 seconds, so calling it multiple times per second will not hurt performance but also won't yield differing values (until the next 10 second period).

However, accessing the pool [directly via JMX](https://github.com/brettwooldridge/HikariCP/wiki/JMX-Monitoring) and querying total connections etc. *will* yield "instantaneous" values.  Probably querying  every 250ms or so is relatively harmless.

In either of these cases, you might want to stuff the polled value into a Metrics [``Histogram``](https://dropwizard.github.io/metrics/3.1.0/apidocs/com/codahale/metrics/Histogram.html) that is backed by a [``SlidingTimeWindowReservoir``](https://dropwizard.github.io/metrics/3.1.0/apidocs/com/codahale/metrics/SlidingTimeWindowReservoir.html).

Whether this is something that we would consider doing internally in the future is an open question.  The amount of additional configuration adds "complications" and overhead that I'm not sure we're willing to impose.  For example, polling period, whether users want a ``SlidingTimeWindowReservoir`` or ``ExponentiallyDecayingReservoir`` or other, and if ``SlidingTimeWindowReservoir`` a configurable time-frame, and if a ``SlidingWindowReservoir`` how many samples, etc.

Now, the number of checkout timeouts *is* something we have considered tracking.  But we don't currently have a solution either in hand to offer you now, nor an implementation in mind.

**Comment by hugebdu** [comment]
Brett,

Thanks for your quick response!
Max connections - I meant between the pool and the DB.

I'll try polling the JMX as you've suggested and shall keep an eye on any future progress with the checkout timeouts.

Thanks again!

**Comment by brettwooldridge** [comment]
@hugebdu In the upcoming 2.4.0 release the DropWizard gauges (TotalConnections, IdleConnections, ... ) should yield updated values at 1000ms resolution.  Polling the gauges at a higher frequency will have no measurable (negative) performance impact, so poll as often as you like.

As before, JMX access for these values will yield an instantaneous value.

**Comment by hugebdu** [comment]
@brettwooldridge, thank you for the update!

**Comment by brettwooldridge** [comment]
HikariCP v2.6.0 includes a new DropWizard meter for connection timeouts.
