### ISSUE TITLE
Spring-Hibernate config example in wiki does not work

### ISSUE THREAD

**Issue by hrchu** [brettwooldridge/HikariCP#262]
In https://github.com/brettwooldridge/HikariCP/wiki/Spring-Hibernate ,

The config below does not work:

    
    <bean id="mainDataSource" class="com.zaxxer.hikari.HikariDataSource" destroy-method="shutdown">
        <property name="dataSourceClassName" value="com.mysql.jdbc.jdbc2.optional.MysqlDataSource" />
        <property name="connectionTestQuery" value="SELECT 1" />
        <property name="dataSource.user" value="${jdbc.username}" />
        <property name="dataSource.password" value="${jdbc.password}" />
        <property name="dataSource.url" value="${jdbc.url}" />
    </bean>

I use following config instead:

    <bean id="hikariConfig" class="com.zaxxer.hikari.HikariConfig">
        <property name="poolName" value="springHikariCP" />
        <property name="connectionTestQuery" value="SELECT 1" />
        <property name="dataSourceClassName"       value="com.mysql.jdbc.jdbc2.optional.MysqlDataSource" />
        <property name="dataSourceProperties">
            <props>
                <prop key="url">${jdbc.url}</prop>
                <prop key="user">${jdbc.username}</prop>
                <prop key="password">${jdbc.password}</prop>
            </props>
        </property>
    </bean>

    <bean id="dataSource" class="com.zaxxer.hikari.HikariDataSource" destroy-method="close">
        <constructor-arg ref="hikariConfig" />
    </bean>

**Comment by brettwooldridge** [comment]
Updated.  Thanks.
