### ISSUE TITLE
Connection attempt to database pool_name failed

### ISSUE THREAD

**Issue by Ajeeshreloaded** [brettwooldridge/HikariCP#266]
I tried with 2.3.2 version & I am getting an error like "java.lang.IllegalStateException: ConcurrentBag has been closed, ignoring add()" but my program works fine which gets connections & closes connection. I have attached the error log, hikaricp property file & java code.
![hikaricpconfig](https://cloud.githubusercontent.com/assets/11148389/6319523/ebcd76b8-bae4-11e4-81e5-32a701579911.jpg)
![error](https://cloud.githubusercontent.com/assets/11148389/6319522/ebc42b80-bae4-11e4-881b-e759c1d6c630.jpg)
![prog_1](https://cloud.githubusercontent.com/assets/11148389/6319521/ebbff01a-bae4-11e4-9f94-a401215430ab.jpg)
![prog_2](https://cloud.githubusercontent.com/assets/11148389/6319524/ebd48afc-bae4-11e4-903e-875e34016d31.jpg)
![prog_3](https://cloud.githubusercontent.com/assets/11148389/6319520/ebb194f2-bae4-11e4-8636-a15d34201e63.jpg)

**Comment by Ajeeshreloaded** [comment]
I am using Eclipse IDE, Java Project with Maven, connecting with MySQL database which resides in local machine.

**Comment by brettwooldridge** [comment]
This is a harmless log message.  You have ``maximumPoolSize=100`` (which is quite large), and no ``minimumIdle`` configured, so by default ``minimumIdle=maximumPoolSize``.

At startup HikariCP is attempting to fill the pool with 100 connections (asynchronously), but your code is running a single query and then shutting the pool down almost instantly.  The initial pool filler thread is still running, and tries to add a connection, causing this exception to be logged.

I have two possible suggestions.  1) set the ``minimumIdle`` to ``0``, or 2) set ``maximumPoolSize`` to a reasonable value like ``10`` (leaving ``minimumIdle`` unset) and give the initial pool filler thread 2-5 seconds to complete before shutting down the pool so quickly.

**Comment by Ajeeshreloaded** [comment]
Thank you Brett Wooldridge, I'll try this & let you know if the error persists.
