### ISSUE TITLE
nit: error generating maven dependencies report

### ISSUE THREAD

**Issue by eepstein** [brettwooldridge/HikariCP#267]
Running maven site on a project that uses HikariCP I get 3 warnings like the following.  Is the build non-standard in some way?

[WARNING] Unable to process class com/zaxxer/hikari/pool/HikariPool.class in JarAnalyzer File /Users/ezra/.m2/repository/com/zaxxer/HikariCP/2.3.2/HikariCP-2.3.2.jar
org.apache.bcel.classfile.ClassFormatException: Invalid byte tag in constant pool: 18

**Comment by brettwooldridge** [comment]
HikariCP-2.3.2.jar is a Java 8 jar, built in a standard fashion.  The issue seems to be with [JarAnalyzer](https://github.com/RichardWarburton/lambda-behave/issues/31) not HikariCP.  You might try using the HikariCP-java6-2.3.2.jar artifact instead if you need to run JarAnalyzer on it.
