### ISSUE TITLE
Fatal exception during proxy generation - Excelsior JET

### ISSUE THREAD

**Issue by kuikentjepiep** [brettwooldridge/HikariCP#268]
Hello,

Today I've encountered a strange error. I've compiled my project and the .JAR runs fine. When I make an .exe file using Excelsior it compiles fine though when ran it throws me the following exception:

<pre>[main] ERROR com.zaxxer.hikari.proxy.JavassistProxyFactory - Fatal exception during proxy generation

javassist.CannotCompileException: by java.lang.LinkageError: duplicate class definition
        at javassist.ClassPool.toClass(ClassPool.java:1099)
        at javassist.CtClass.toClass(CtClass.java:1265)
        at com.zaxxer.hikari.proxy.JavassistProxyFactory.modifyProxyFactory(JavassistProxyFactory.ja
va:121)
        at com.zaxxer.hikari.proxy.JavassistProxyFactory.<clinit>(JavassistProxyFactory.java:56)
        at com.zaxxer.hikari.proxy.JavassistProxyFactory.initialize(JavassistProxyFactory.java:74)
        at com.zaxxer.hikari.HikariConfig.<clinit>(HikariConfig.java:88)</pre>

I've tried making an empty application and just calling a new database pool. This works fine and compiles fine to an .exe file. This 'testing' application has no other dependencies except the sl4j api and javassist.

My 'main' application has the following dependencies:

<pre>
org.jboss.netty:netty:3.2.0.Fina
mysql:mysql-connector-java:5.1.31
org.slf4j:slf4j-simple:1.7.7
org.slf4j:slf4j-api:1.7.7
net.sf.trove4j:trove4j:3.0.3
com.zaxxer:HikariCP-java6:2.0.1
org.javassist:javassist:3.18.1-GA
</pre>

Here is how I instantiate a new database connection pool: http://pastebin.com/y3CkQ2Wf

Thanks.

**Comment by brettwooldridge** [comment]
I don't have any experience with Excelsior (this might be a question for them).  First, try upgrading to HikariCP 2.3.2, who knows what fixes between 2.0.1 and 2.3.2 might affect Excelsior?

Are you saying that the "empty" application that creates a new database pool compiles into and .exe and actually runs fine?  Including executing a simple query, for example?

**Comment by brettwooldridge** [comment]
Please re-open if you have more information or a status update.

**Comment by pjBooms** [comment]
Hi, I am from Excelsior. 

We have the same bug report recently. Actually, the way you inject the code into ProxyFactory is not Java SE compatible and fragile. According JVM specification a JVM can resolve class references as lazily (as HotSpot does) and eagerly (as we do, we do it ahead-of-time). So non-patched ProxyFactory class can be loaded before it becomes patched and when you patch it and try to load, it results to LinkageError that is actually required by the JVM specification in this case. So your code internally relies on lazy class resolution implemented in HotSpot. But this can be changed in the future. For instance, Java 9 modules linker also does some class reference resolution ahead-of-time and your code can stop working for Java 9 modules at some point.

So I would suggest you to rewrite your code making ProxyFactory abstract and generating a descendant of it and instantiating it at run-time.

Meanwhile we have to provide our users an option to exclude ProxyFactory from ahead-of-time compilation to make the things work.

Please re-open the issue if you think that my comment is reasonable.

**Comment by pjBooms** [comment]
BTW, if you follow my suggestion it will fix the #217 issue as well

**Comment by brettwooldridge** [comment]
@pjBooms Upgrade your version of HikariCP.  HikariCP no longer generates classes at runtime, classes are generated at build time.

**Comment by pjBooms** [comment]
Ok, I see :). 

Just curious, why is it still generated? The bodies are pretty static and can appear in the source directly.

**Comment by pjBooms** [comment]
BTW, from which version you generate classes at build time?

**Comment by brettwooldridge** [comment]
@pjBooms build time proxy generation started from 2.4.0.

As to why we generate proxies, we do so because interfaces like ``java.sql.Statement`` and ``java.sql.ResultSet`` have [dozens of methods](https://docs.oracle.com/javase/7/docs/api/java/sql/ResultSet.html), but we only need to intercept a few.  As a consequence, we can have an implementation class [that barely exceeds 100 lines](https://github.com/brettwooldridge/HikariCP/blob/dev/src/main/java/com/zaxxer/hikari/pool/ProxyResultSet.java), and generate the rest as boilerplate that simply delegates to the wrapped driver implementation: ``{ try { return delegate.method($$); } catch (SQLException e) { throw checkException(e); } }``.

**Comment by pjBooms** [comment]
Ok, but decompiled version of ProxyFactory looks exactly this way:

```java
package com.zaxxer.hikari.pool;

import com.zaxxer.hikari.util.FastList;
import java.sql.*;

public final class ProxyFactory
{

    private ProxyFactory()
    {
    }

    static ProxyConnection getProxyConnection(PoolEntry poolentry, Connection connection, FastList fastlist, ProxyLeakTask proxyleaktask, long l, boolean flag, boolean flag1)
    {
        return new HikariProxyConnection(poolentry, connection, fastlist, proxyleaktask, l, flag, flag1);
    }

    static Statement getProxyStatement(ProxyConnection proxyconnection, Statement statement)
    {
        return new HikariProxyStatement(proxyconnection, statement);
    }

    static CallableStatement getProxyCallableStatement(ProxyConnection proxyconnection, CallableStatement callablestatement)
    {
        return new HikariProxyCallableStatement(proxyconnection, callablestatement);
    }

    static PreparedStatement getProxyPreparedStatement(ProxyConnection proxyconnection, PreparedStatement preparedstatement)
    {
        return new HikariProxyPreparedStatement(proxyconnection, preparedstatement);
    }

    static ResultSet getProxyResultSet(ProxyConnection proxyconnection, ProxyStatement proxystatement, ResultSet resultset)
    {
        return new HikariProxyResultSet(proxyconnection, proxystatement, resultset);
    }
}

```
Why not just put that code directly to the source and remove JavassistProxyFactory as a result?

**Comment by pjBooms** [comment]
Ok, now I understand, thank you.
