### ISSUE TITLE
NullPointerException when closing connection

### ISSUE THREAD

**Issue by hvesalai** [brettwooldridge/HikariCP#270]
Hi,

we get this exception when running our code.

```
java.lang.NullPointerException: null
        at com.zaxxer.hikari.proxy.ConnectionProxy.close(ConnectionProxy.java:178)
```

My guess it that this is what happens:

- the are two threads
- thread 1 creates a statement from a connection object shared by the threads
- thread 2 closes the connection, entering line [ConnectionProxy#174](https://github.com/brettwooldridge/HikariCP/blob/2.3.x/hikaricp-common/src/main/java/com/zaxxer/hikari/proxy/ConnectionProxy.java#L174), where it reads the size of the openStatements list
- thread 1 closes the statement, resulting in the statement being removed from the openStatements list on line [ConnectionProxy#123](https://github.com/brettwooldridge/HikariCP/blob/2.3.x/hikaricp-common/src/main/java/com/zaxxer/hikari/proxy/ConnectionProxy.java#L123). This results in the openStatements list to be shrunk and a null to be inserted into the previously last position in line [FastList.java#L117](https://github.com/brettwooldridge/HikariCP/blob/2.3.x/hikaricp-common/src/main/java/com/zaxxer/hikari/util/FastList.java#L117)
- thread 2 advances to line [ConnectionProxy.java#L178](https://github.com/brettwooldridge/HikariCP/blob/2.3.x/hikaricp-common/src/main/java/com/zaxxer/hikari/proxy/ConnectionProxy.java#L178), where it get's `null` from the last `get(i)`

We have fixed our code so that it doesn't share connections between threads, so this is no longer an issue for us. JDBC specification doesn't say whether Connection should be thread safe, but at least psql jdbc driver is https://jdbc.postgresql.org/documentation/81/thread.html

Heikki

**Comment by brettwooldridge** [comment]
JDBC 1.0 (1997), if I remember correctly, required Connections to be threadsafe but support was not widely adopted.  Starting with JDBC 2.0, Sun added language that largely backed away from the requirement without conceiting failure:
```
"In practice we expect that most of the JDBC objects will only be accessed in a single threaded
way. However some multi-thread support is necessary, and our attempts in previous drafts to
specify some classes as MT safe and some as MT unsafe appeared to be adding more confusion
than light."
```
