### ISSUE TITLE
Unwrap in HikariConnectionProvider fails to unwrap to DataSource

### ISSUE THREAD

**Issue by tedeling** [brettwooldridge/HikariCP#273]
SessionFactoryUtils in Spring 4 calls the unwrap of a ConnectionProvider, expecting the connection provider to unwrap to a DataSource with `cp.unwrap(DataSource.class);`.  The unwrap method in HikariConnectionProvider just casts to itself, throwing a ClassCastException when trying to unwrap to a DataSource.

**Comment by brettwooldridge** [comment]
Will investigate merging.  If you are using Hibernate 4.3.6+, then there is a HikariCP connection provider created by the Hibernate project that is preferable.

**Comment by tedeling** [comment]
Thanks, found it it in org.hibernate:hibernate-hikaricp! You might want to have a reference to that artifact in your Hibernate documentation (https://github.com/brettwooldridge/HikariCP/wiki/Hibernate4). Cheers!

**Comment by brettwooldridge** [comment]
@tedeling I will leave this issue open until the wiki is updated.
