### ISSUE TITLE
Connect/socket timeouts for underlying JDBC drivers?

### ISSUE THREAD

**Issue by prb** [brettwooldridge/HikariCP#277]
Can't some of the issues with "infinite" wait in the event of database outage be addressed by configuring the socket-level timeouts on the underlying JDBC driver appropriately?

https://jdbc.postgresql.org/documentation/head/connect.html
http://dev.mysql.com/doc/connector-j/en/connector-j-reference-configuration-properties.html

etc.

**Comment by brettwooldridge** [comment]
@prb Certainly issues of *infinite* wait can be handled with driver-wide socket timeouts, and we do recommend that users set those to "reasonable" values for their specific application.  Maybe a web front-end should never have queries that run logger than 5 seconds, but a data warehouse query might run for hours.

HikariCP uses ``Connection.setNetworkTimeout()``, where supported by drivers, to limit "alive queries" to the pool configured timeouts.  Generally speaking ``Connection.setNetworkTimeout()`` is implemented by most drivers as a socket-level timeout.
