### ISSUE TITLE
log level is not respected?

### ISSUE THREAD

**Issue by goekay** [brettwooldridge/HikariCP#280]
Hi,
I was happily using the version 2.2.5 of the HikariCP-java6 artifact with the log level set to INFO. I'm using Slf4j with log4j. Then, I came upon a new version (2.3.3) and wanted to switch to it. But the pool clean up stats seem to be logged with the DEBUG level, even though I did not change any logging setting. Logger name I'm using is "com.zaxxer.hikari".

**Comment by dfex55** [comment]
Pool stats are logged with (just) "HikariPool". Add it to your log settings and you won't see debug messages any more.

**Comment by goekay** [comment]
Thank you. The logs are now as intended. After a closer look, I found out that after the introduction of  hikaricp-common, (https://github.com/brettwooldridge/HikariCP/blob/6febf0604b22cd67a1124f8b564b440348e56534/hikaricp/src/main/java/com/zaxxer/hikari/pool/HikariPool.java#L76) became (https://github.com/brettwooldridge/HikariCP/blob/2.3.x/hikaricp-common/src/main/java/com/zaxxer/hikari/pool/BaseHikariPool.java#L70). But I think that it's somewhat confusing to change this behoviour, since pool stats logging isn't bound to package context and therefore we need the extra setting. Maybe the sitation can be improved by using "LoggerFactory.getLogger(getClass())" or just prefixing with the package info?

**Comment by brettwooldridge** [comment]
@goekay Sorry for the change.  This change was in response to #237, but I actually prefer ``getClass()`` as noted in my comments there.  I think I'll revert to that.

**Comment by harsel** [comment]
I added a Pull Request. I do not use getClass() because the logger is a static field. It could be converted to an instance variable though.

**Comment by harsel** [comment]
Thank you for fixing the issue so fast. Can we expect a new version to be released soon?

**Comment by brettwooldridge** [comment]
Of course you can run from a snapshot now, and I can publish one if you wish (or you can build it).  Because our last release was just 12 days ago, we'll probably wait another week or so before cutting another release.  Beside this fix, there is only one other currently -- and one on-deck.

We prefer to wait until there are three or four meaningful bugs before cutting a release.

**Comment by brettwooldridge** [comment]
@harsel HikariCP 2.3.4 has been published to the maven central repository.
