### ISSUE TITLE
Hikari configured with incorrect credentials will infinitely retry

### ISSUE THREAD

**Issue by djerraballi** [brettwooldridge/HikariCP#282]
Im noticing some behavior in my application. Trying to wrap my head around it. When i configure the database credentials incorrectly (typo with password), when hikari tries to create the connection pool, it will timeout, and than retry forever. (Attempts to build the pool multiple times opening new connectiosn to the database, completely unbounded).  

Based on the docs, it looks like initializationFailFast is default to true. Wouldn't this mean that this shouldn't happen? Switching out hikari for another connection pool (c3p0) seemed to handle this situation better (stopped retrying after a few fails)

Here is what i am seeing in logs:

07:13:27,426 DEBUG [HikariPool] Connection attempt to database HikariPool-1 failed: Unknown database 'dbnamewithtypo'
07:14:07,332 DEBUG [HikariPool] Connection attempt to database HikariPool-7 failed: Unknown database 'dbnamewithtypo'

Then i saw the # of connections getting opened to the db:

user@host:~$ netstat -an | grep 3306 | wc -l
5001
(10 seconds later)
user@host:~$ netstat -an | grep 3306 | wc -l
5780

This can happen if the dbname is wrong, username/password as well. 

Am i just doing it wrong? Ideally i get credentials correct and this doesn't happen, but i'd like to be able to make a mistake and not dos the database.

**Comment by brettwooldridge** [comment]
Why is the connection timing out rather than throwing an exception?

**Comment by brettwooldridge** [comment]
@djerraballi Can you post your pool configuration here?

Looking at the [``initializeConnections()``](https://github.com/brettwooldridge/HikariCP/blob/2.3.x/hikaricp-common/src/main/java/com/zaxxer/hikari/pool/BaseHikariPool.java#L495) method, the logic basically goes like this:
```java
if (configuration.isInitializationFailFast()) {
   try {
      try {
         if (!addConnection()) {
            shutdown();
            throw new PoolInitializationException(lastConnectionFailure.getAndSet(null));
         }
...
```
So, if ``addConnection()`` returns ``false``, a ``PoolInitializationException`` will be thrown with the cause.  Looking at the [``addConnection()``](https://github.com/brettwooldridge/HikariCP/blob/2.3.x/hikaricp-common/src/main/java/com/zaxxer/hikari/pool/BaseHikariPool.java#L390) method, the code goes something like this:
```java
...
   try {
      connection = dataSource.getConnection(username, password);
      ...
      return true;
   }
   catch (Exception e) {
      lastConnectionFailure.set(e);
      poolUtils.quietlyCloseConnection(connection);
      LOGGER.debug("Connection attempt to database {} failed: {}", ...);
   }
return false;
```
So, if the DEBUG log that you see above appears, ``false`` is inevitably returned from ``addConnection()`` which will, as seen above, result in ``PoolInitializationException`` being thrown.

Looking at the log you provided, it seems that something outside of HikariCP is creating new pools, in spite of the ``PoolInitializationException``.  You can see this by the fact that the first log above is from ``HikariPool-1`` but the later log is from ``HikariCP-7``.  ``HikariCP-7`` would be the seventh instance created by your application.

**Comment by djerraballi** [comment]
I am using datanucleus so this is the code that is creating the pool: https://github.com/datanucleus/datanucleus-rdbms/blob/master/src/main/java/org/datanucleus/store/rdbms/connectionpool/HikariCPConnectionPoolFactory.java#L105

guessing that needs to be put in a try catch, and throw. Ill try and submit a pr today.

**Comment by brettwooldridge** [comment]
I suspect the handling needs to be handled higher up than that.  The exception that HikariCP is throwing is a subclass of RuntimeException.
