### ISSUE TITLE
Why is setConnectionInitSql deprecated?

### ISSUE THREAD

**Issue by fdummert** [brettwooldridge/HikariCP#283]
We are using this setting to change Oracle's default sorting behavior for a certain application:

ALTER SESSION SET NLS_SORT = XGERMAN_DIN

Shouldn't such use cases be supported in future, too?

**Comment by brettwooldridge** [comment]
The *connectionInit* property will be un-@deprecated in the next release.  You can read the thread in the Google Group if you want to.

**Comment by fdummert** [comment]
Thanks for the info and sorry, I should have checked the discussion before...

**Comment by brettwooldridge** [comment]
@fdummert No problem, I don't expect such a deep search.  Perfectly valid issue to open (and close :smile: )
