### ISSUE TITLE
NPE at com.zaxxer.hikari.pool.BaseHikariPool.initializeConnections(BaseHikariPool.java:498)

### ISSUE THREAD

**Issue by indyaah** [brettwooldridge/HikariCP#285]
Environment : 

Hikari (for java6) 2.3.2
Oracle JDK 8u40
Spring 4.1.5.RELEASE
Hibernate 4.3.8.Final
Mysql Connector 5.1.34

The problem was encountered while upgrading hikari from 2.0.1 to 2.3.2
If I stay on 2.0.1 everything works fine.

**EDIT : Full stack trace**
aused by: java.lang.NullPointerException
	at java.util.Hashtable.put(Hashtable.java:459)
	at java.util.Properties.setProperty(Properties.java:166)
	at com.mysql.jdbc.NonRegisteringDriver.parseURL(NonRegisteringDriver.java:805)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:316)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:57)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:63)
	at com.zaxxer.hikari.pool.BaseHikariPool.addConnection(BaseHikariPool.java:396)
	at com.zaxxer.hikari.pool.BaseHikariPool.initializeConnections(BaseHikariPool.java:498)
	... 67 more

**Comment by brettwooldridge** [comment]
Can you post your configuration?  This is likely a regression in the DriverDataSource class.

**Comment by indyaah** [comment]
Hikari bean config

    @Bean
    public DataSource dataSource() {
        HikariDataSource dataSource = new HikariDataSource();
        String jdbcUrl = env.getProperty("jdbc.url");
        String databaseName = env.getProperty("jdbc.databaseName");
        String jdbcParameters = env.getProperty("jdbc.parameters");
        dataSource.setDriverClassName(env.getProperty("jdbc.driverClassName"));
        dataSource.setJdbcUrl(jdbcUrl.concat(databaseName).concat("?").concat(jdbcParameters));
        dataSource.setUsername(env.getProperty("jdbc.username"));
        dataSource.setPassword(env.getProperty("jdbc.password"));

        /**
         * HikariCP specific. Remove if you move to other connection pooling library.
         **/
        dataSource.addDataSourceProperty("cachePrepStmts", true);
        dataSource.addDataSourceProperty("prepStmtCacheSize", 250);
        dataSource.addDataSourceProperty("prepStmtCacheSqlLimit", 2048);
        dataSource.addDataSourceProperty("useServerPrepStmts", true);
        dataSource.addDataSourceProperty("initializationFailFast", true);
        dataSource.setIdleTimeout(6000L);
        dataSource.setMaxLifetime(60000L);

        return dataSource;
    }

I verified the properties values being loaded correctly.

**Comment by brettwooldridge** [comment]
I found the problem.  It is related to [this pull request](https://github.com/openwide-java/HikariCP/commit/2b1e0f77bb9307212bf2f51221ab645d69abb894).  We changed the way that the DataSource Properties (``datasource.addDataSourceProperties()``) are copied and passed to the driver.  The issue is, in reality those properties should all be ``String`` values in the case of a *Driver-based* configuration.

We will make a change to guard against this, but for now change these lines to use ``String`` values:
```java
dataSource.addDataSourceProperty("cachePrepStmts", "true");
dataSource.addDataSourceProperty("prepStmtCacheSize", "250");
dataSource.addDataSourceProperty("prepStmtCacheSqlLimit", "2048");
dataSource.addDataSourceProperty("useServerPrepStmts", "true");
```
Note, this line is incorrect:
```java
dataSource.addDataSourceProperty("initializationFailFast", true);
```
``initializationFailFast`` is a property of HikariCP not MySQL, and so would be set like this:
```java
dataSource.setInitializationFailFast(true);
```
However, as this is now the default behavior in 2.3.x, you can eliminate this line completely.

**Comment by brettwooldridge** [comment]
@indyaah HikariCP 2.3.4 has been published to the maven central repository, and contains a fix that handles non-String values for DataSource properties correctly.

**Comment by indyaah** [comment]
@brettwooldridge  : Thanks, that was real quick.
