### ISSUE TITLE
Add better feedback for unsupported/mixed configuration

### ISSUE THREAD

**Issue by mwhipple** [brettwooldridge/HikariCP#290]
In `PoolUtilities` (at least) there is code that instantiates the datasource based on the provided configuration either based on the class name and properties *or* the jdbcUrl.  Since this is different from other CP libraries it could save frustration when trying to do a quick CP swap if appropriate log messages were added with maybe a WARN if both of those values are present.

**Comment by brettwooldridge** [comment]
@mwhipple this is fixed in 2.3.6+ (not yet released).  If the ``driveClassName`` is present, it will take precedence over resolving the driver by URL alone.
