### ISSUE TITLE
Prepared Statement Null Pointer Exception

### ISSUE THREAD

**Issue by zepernick** [brettwooldridge/HikariCP#296]
I had a situation where an old DB driver I was using for a proprietary DB was returning a NULL PreparedStatement to HikariCP.  Hikari returned the Proxied PreparedStatement so it appeared that everything was ok, until you tried to invoke a method on the object.  Hikari would throw an internal null pointer exception when it tried to interact with the null preparedstatement reference it was now holding.

The driver was returning a NULL whenever the auto generated keys parameter was sent.

```java
con.prepareStatement(sql, PreparedStatement.NO_GENERATED_KEYS)
```

I have not studied the spec, but this seems like a bug in the driver.  Thought I would let you guys know in case you wanted to put a check in for it.  I also had made a [post](http://stackoverflow.com/questions/29353363/hikaricp-prepared-statement-null-pointer-exception/29395736) on StackOverflow that has the stack trace and some other additional details.

**Comment by brettwooldridge** [comment]
Failure was due to JDBC driver bug.  The best HikariCP could do here is throw a different kind of exception, which is of questionable value.  Drivers have bugs, and allowing exceptions to rise to the application level unmodified helps identify the issue more quickly.
