### ISSUE TITLE
SLF4J Implementation in OSGi

### ISSUE THREAD

**Issue by joebrassi** [brettwooldridge/HikariCP#297]
The Hikari project is currently attached to a specific SLF4J implementation (artifact: `slf4j-simple-1.7.10.jar`). Hence, if the project using HikariCP uses a different SLF4J implementation then the artifact throws a warning `SLF4J: Class path contains multiple SLF4J bindings.` followed by the list of implementations found.

In the OSGi world, it is very common to replace one implementation by another, so if HikariCP could just use the available implementation rather that having a hard-coded implementation (`slf4j-simple-1.7.10.jar`), then that would be a major improvement for OSGi users.

**Comment by brettwooldridge** [comment]
Sure.  In my day job we're actually big OSGi users, but do be honest our product doesn't actually use HikariCP (we need JTA, and so use Bitronix, for which I'm also a developer).  I'll fixed up OSGi headers.

**Comment by joebrassi** [comment]
Ok, when you have it ready let us know in the release notes what release contains the fix. Thanks.

**Comment by brettwooldridge** [comment]
Now I'm confused.  At compile time HikariCP depends on slf4j 1.7.10, however the jar artifact produced does not have specific version dependency in the manifest.  The MANIFEST.MF contains this header:
```
Import-Package: org.slf4j;version="[1.6,2)"
```
which is a range of 1.6.2+ or greater.  If you are using a version older than that, either upgrade your dependency, or if you can demonstrate compatibility with older versions I can change the supported range.

**Comment by joebrassi** [comment]
I was receiving this warning message during some Unit Tests

```console
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/D:/projects/lib/maven-repo/org/slf4j/slf4j-simple/1.7.10/slf4j-simple-1.7.10.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/D:/projects/lib/maven-repo/org/slf4j/slf4j-log4j12/1.5.11/slf4j-log4j12-1.5.11.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.SimpleLoggerFactory]
```
but I am really not sure where that other implementation comes from because I use `log4j-1.2.17` and I don't have it (the `slf4j-log4j12`) declared in the project dependencies. I have excluded that artifact `slf4j-log4j12` from some dependencies but the warning keeps showing up. I'll investigate further and keep you posted.

**Comment by joebrassi** [comment]
Found the issue. It was this artifact `org.jboss.arquillian.container:arquillian-container-osgi:1.1.1.Final` which was causing the problem, it uses in a dependency of a dependency the artifact `slf4j-log4j12`, and causing a double `slf4j` implementation and the warning.

Just added an exclusion to the dependency and fixed the warning message:

```xml
<dependency>
  <groupId>org.jboss.arquillian.container</groupId>
  <artifactId>arquillian-container-felix-embedded</artifactId>
  <version>1.1.1.Final</version>
  <scope>test</scope>
  <exclusions>
    <exclusion>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-log4j12</artifactId>
    </exclusion>
  </exclusions>
</dependency>
```
