### ISSUE TITLE
Hikari Housekeeping Timer daemon seems cause jvm crash

### ISSUE THREAD

**Issue by hrchu** [brettwooldridge/HikariCP#301]
I cannot confirm the issue is caused by HikariCP, but fatal error log shows 

       Current thread (0x0000000002271000):  JavaThread "Hikari Housekeeping Timer (pool [master DB])" daemon [_thread_in_Java, id=18659, stack(0x00007f8a84e56000,0x00007f8a84e97000)]

here is my log: https://gist.github.com/hrchu/99aa835e973754df6baa

p.s. the crash seems happening when I monitor the application via JMX.

**Comment by brettwooldridge** [comment]
I recommend upgrading to JDK 1.8.0_40 (Java 8u40), to see if this JVM issue has been resolved.  No pure Java code should ever be able to cause a SIGSEGV crash -- it is a JVM bug if it is occurring.

**Comment by brettwooldridge** [comment]
@hrchu Any update on this issue?

**Comment by hrchu** [comment]
I have updated the JDK, and seems works well. I will do long term test in this weekend.

**Comment by PhillipTaylor** [comment]
@hrchu A long shot, but can you confirm if upgrading worked please (possibly from your sketchy memory given the tickets age)?

I'm running the same JDK version (as your old version) and seeing the same housekeeping thread crash

**Comment by hrchu** [comment]
@PhillipTaylor yeap, it works well on my 10 node cluster these years.
