### ISSUE TITLE
More informative toString() results for statements

### ISSUE THREAD

**Issue by frymaster** [brettwooldridge/HikariCP#302]
Feature request: When using the jdbc driver directly, if I call ``toString()`` on a ``PreparedStatement`` (or presumably any kind of ``Statement``) then the output includes the query being executed:

``com.mysql.jdbc.JDBC4PreparedStatement@6cc04df7: INSERT INTO `lb-sky-1` (date, playerid, replaced, type, data, x, y, z) VALUES(FROM_UNIXTIME(1427026449), 11, 0, 10, 9, 13581, -1, -11115)``

  However, when using Hikari, all I get back is ``com.zaxxer.hikari.proxy.PreparedStatementJavassistProxy@7e3c7cb1`` or similar

If I encounter an exception when executing a statement, knowing the query can be a useful thing to log - is it possible for the proxy to invoke the underlying statement's toString() method?

**Comment by brettwooldridge** [comment]
No problem, simple change.

**Comment by brettwooldridge** [comment]
This is committed in the *dev* branch and will be available with in the next major release (in a week or three).
