### ISSUE TITLE
Setting MetricRegistry at runtime

### ISSUE THREAD

**Issue by cemo** [brettwooldridge/HikariCP#303]
Hi @brettwooldridge, 

First of all thanks for the great library. 

I would like to set CodaHale MetricRegistry at runtime. This is required because I am not configuring datasource. But it seems that I am little bid late for setting it. Is it possible to propagate a change in HikariDataSource to track metrics?

**Comment by brettwooldridge** [comment]
You should be able to set it once, on the HikariDataSource, after the pool is started.  You'll need HikariCP 2.3.6.

**Comment by cemo** [comment]
Thanks for answer. It seems that I have taken some connections from pool and then setting MetricRegistry. In this case some of connections in pool don't have a MetricsContext with MetricRegistry. Do you think that setting a MetricRegistry should update existing connections as well?

**Comment by brettwooldridge** [comment]
Metrics will not be recorded for connections already taken from the pool, but very quickly whatever stats those connections would have provided will become statistical noise.  As soon as they are returned to the pool, they will start participating in metrics.

**Comment by cemo** [comment]
I am sorry @brettwooldridge. I somehow used an old dependency before and after your comment regarding 2.3.6 I have mischecked my configuration. It is working as expected.

**Comment by brettwooldridge** [comment]
Great.
