### ISSUE TITLE
Version 2.3.6 fails with: Driver with class name org.hsqldb.jdbcDriver was not found among registered drivers

### ISSUE THREAD

**Issue by ulfekstrom** [brettwooldridge/HikariCP#308]
Hi,

With version 2.3.4 everything works fine. But as soon as I upgrade to 2.3.6 the pool is unable to find the HSQLDB jdbc driver.

Thanks for looking into this.

Best regards,
Ulf Ekström

**Comment by brettwooldridge** [comment]
@ulfekstrom I assume you are using a ``jdbcUrl`` and ``driverClassName``?  If so, can you try using *just* a driver URL, and omitting the ``driverClassName``?  The only change I can think of is that in 2.3.4, if a ``jdbcUrl`` was specified we *always* used DriverManager.getDriver(jdbcUrl), but some users wanted to be able to skip DriverManager resolution and load the driver directly (Class.forName()) if the drvier class name was specified explicitly.  So, if the ``driverClassName`` is present, the resolution in 2.3.6 is different than 2.3.4.  We didn't expect this to affect anyone, but it appears it may for some drivers.

**Comment by ulfekstrom** [comment]
Thanks for the quick response. Yes, I'm using both the jdbcUrl and the driverClassName. I tried your suggestion and removed the driverClassName and then it works just fine with HSQLDB. However, when I remove the driverClassName the pool fails for the Microsoft JDBC Driver instead. In that case the url doesn't seem to be sufficient.

**Comment by brettwooldridge** [comment]
@ulfekstrom Yes, as our documentation for ``jdbcUrl`` states:
```
When using this property with "old" drivers, you may also need to set the 
driverClassName property, but try it first without.
```
What was a bit unexpected was for it to fail with a "modern" driver like HSQLDB in the case where both are specified.  I suspect this is more a classloader issue than anything else.  Still, we will investigate a way to make it more robust while still supporting all use-cases.

**Comment by ulfekstrom** [comment]
Ok, thanks!
