### ISSUE TITLE
Missing dependency in junit test

### ISSUE THREAD

**Issue by lrkwz** [brettwooldridge/HikariCP#309]
Hello
     I'm using version 2.2.5 in a springboot 1.2.3.RELEASE application.
I have defined:
* unit tests
* integration (rest) tests

The integration tests fire: 

    Caused by: java.lang.RuntimeException: HikariCP Codahale shim says: Codahale metrics library is required but was not found in the classpath

As a workaround I've added in pom.xml:

		<dependency>
			<groupId>com.codahale.metrics</groupId>
			<artifactId>metrics-core</artifactId>
			<version>3.0.2</version>
			<scope>test</scope>
		</dependency>

BTW This error happens if I run all the test; running only integration tests works fine (?!).

**Comment by brettwooldridge** [comment]
@lrkwz the next release after 2.2.5 was 2.3.0, the CHANGES file indicates:

* Fixed bug when using the HikariJNDIFactory that required the presence of Codahale metrics.

It is possible your tests are accessing HikariCP through JNDI?  If so, upgrading to 2.3.0 should fix it.
