### ISSUE TITLE
add option to deactivate validation of connections on check-out

### ISSUE THREAD

**Issue by PascalSchumacher** [brettwooldridge/HikariCP#311]
I guess it's heresy to suggest this ;), but would you consider adding a option to let users deactivate validation of connections on check-out?

I only asking because in our performance tests Hikari is slower that c3po with "testConnectionOnCheckout=false". c3po with "testConnectionOnCheckout=true" is much slower than Hikari.

Thanks for providing HikariCP and for the very informative wiki!

**Comment by brettwooldridge** [comment]
Let's discuss.

Unless you've studied the internals of HikariCP you may not know it, but under load HikariCP mostly bypasses the connection validation check.  If a connection has been used within the last 1000ms, HikariCP will bypass the validation check automatically in ``getConnection()``.

If connections are being used less frequently than that, it indicates one of two things:
 * The application is simply not that active in terms of transactions/sec, or
 * The pool is sized too large for the application, such that connections frequently sit in the pool unused for more than 1000ms before being reused

Having said that, with JDBC4 capable drivers, the cost of validation has largely dropped to sub-millisecond or single digit milliseconds.  Wherever possible, validation queries should be avoided, allowing HikariCP to use ``Connection.isValid()`` instead.

Lastly, if there truly are use-cases where speed is paramount (over reliability) and yet transaction rates are very low, there are several alternative pools such as C3P0 available.  We tend to think that either those use-cases are extremely rare, or can be effectively dealt with through driver and pool settings in their current form.

**Comment by PascalSchumacher** [comment]
Thanks for the information. :)

Taking this into consideration I agree that it is better not to add this feature to Hikari CP.

I guess in my case the connection pool is simply too big.

**Comment by brettwooldridge** [comment]
You'd be surprised how many applications can get great throughput, thousands of transactions/second,  with pools as small as 5 connections.  Somehow, in the Java-world, developers got the idea that they needed pools of 50, 100, or even 500 (!) connections.

Generally this is waay to big, and even hurts performance by overloading the DB with more queries than it can service at once.  Often this can be deceptively hard to diagnose, as the DB doesn't exhibit high CPU load (which developers monitor), but instead long I/O wait-times and long I/O queues (which developers often forget to monitor).

**Comment by marcolopes** [comment]
So, Hikari does the connection validation on checkout by DEFAULT?

**Comment by brettwooldridge** [comment]
@marcolopes HikariCP validates connections that have been idle in the pool for more than 500ms. If a connection has been used within the past 500ms, that is considered validation enough that the connection is still alive. This is called the alive bypass window. There is no way to disable validation, that would be insane.

**Comment by marcolopes** [comment]
> [@marcolopes](https://github.com/marcolopes) HikariCP validates connections that have been idle in the pool for more than 500ms. If a connection has been used within the past 500ms, that is considered validation enough that the connection is still alive. This is called the alive bypass window. There is no way to disable validation, that would be insane.

That's great!

I asked because i could not find any parameter to control the validation (DBCP and C3P0 have them, and they must be set).

Thanks!
