### ISSUE TITLE
Database Failover 

### ISSUE THREAD

**Issue by djerraballi** [brettwooldridge/HikariCP#314]
Hey just a question, 

If i configure my database as a VIP/CNAME, and i switch actual server behind the vip out, I notice that my application will still be pointing to the old server. Do i just have to wait till the maxLifeTime has run out, and the connections get re-established for the application to recover? Also is the IP of the server cached at pool creation time? In that case when the pool tries to get a new connection will it still try and make that connection with the old server (evne though a new dns lookup would reveal the ip to have changed)? 

Sorry don't have of hard data / logs for this question, just wondering what the behavior is.

**Comment by brettwooldridge** [comment]
I strongly suspect that you are running into the JVM cache of DNS lookups.  When Java performs a lookup of host ``xyz.com`` the default policy is to cache the resolved IP for the lifetime of the JVM.  This is no good, as you have found, for failover scenarios.

There is a system property that you need to set, ``networkaddress.cache.ttl=n``, where ``n`` is some number of seconds.  See the reference [here](http://docs.oracle.com/javase/6/docs/technotes/guides/net/properties.html).

For example:
```java
networkaddress.cache.ttl=10
```
would tell the JVM to only cache DNS lookups for a total of 10 seconds.  This is a reasonable value.

**Keep in mind though, there can be other caches involved!**

DNS lookup is a hierarchy:
```
JVM → OS → Local-DNS → ISP-DNS → Root-DNS
```
There *can* be caches anywhere along the way, *and likely are.*  The purpose of this is to distribute the load.  If every DNS request from every PC went directly to the Root-DNS those servers would be crushed like a giant distributed-denial-of-service attack.

That is why, when you change a CNAME at a domain hosting provider, you may be warned/informed that the changes may take 24 hours or more to "propagate" through the DNS hierarchy.

Generally, a DNS hosting provider allows you to specify a TTL (time to live) for each record (A, CNAME, MX, etc.).  In theory, DNS servers between the root and the end-user should honor the TTL and expire entries from their caches.  In reality, some intervening DNS servers may have their own "minimum TTL" (for example, 1 Hour), and reject any suggested TTL values below that minimum.

Keep all of this in mind as you experiment.

**Comment by djerraballi** [comment]
Thanks for the quick resposne!
You are awesome!
