### ISSUE TITLE
Newer version of Javassist breaks shading

### ISSUE THREAD

**Issue by ams2990** [brettwooldridge/HikariCP#317]
I know you've already rolled back from Javassist 3.19.0-GA to 3.18.2-GA, but I thought I would mention this since it took me a long time to track down. I shade HikariCP into my application. I cannot shade any version in [2.3.0, 2.3.7]. Specifically, any build between e3316e8618a1b00a180468041734a042738d161b and eadf8d1911da73bed9f96e5fa0d9feae11058328 causes the extremely helpful error

    [ERROR] Failed to execute goal org.apache.maven.plugins:maven-shade-plugin:2.3:shade (default) on project insight-sql: Error creating shaded jar: null: RuntimeException -> [Help 1]

Using 3.18.2-GA makes it work normally again. Any chance you can cut a 2.3.8 release soon?

**Comment by brettwooldridge** [comment]
Yes, I'll try to publish one tonight.

**Comment by brettwooldridge** [comment]
@ams2990 HikariCP 2.3.8 has been published to the maven central repository.  It should be visible in approximately 3 hours.

**Comment by guidomedina** [comment]
Will Javassist 3.20.0-GA recently released fix this?

**Comment by guidomedina** [comment]
Fixed issues: https://issues.jboss.org/browse/JASSIST/fixforversion/12326488/?selectedTab=com.atlassian.jira.jira-projects-plugin:version-summary-panel

**Comment by slyoldfox** [comment]
@guidomedina I guess it won't be relevant much anymore since hikari 2.4 won't have a Javassist dependency anymore. 

Check the "dev" branch for the specifics.

**Comment by guidomedina** [comment]
Nice, one less jar for the project :D

**Comment by brettwooldridge** [comment]
[![screen shot 2015-06-26 at 07 07 55](https://cloud.githubusercontent.com/assets/1538661/8366706/1e052254-1bd2-11e5-861c-65cf87722bea.png)](https://github.com/brettwooldridge/HikariCP/commit/dcaa5ac3f979dfe86698f10c3d9bc761e3a7170e)
