### ISSUE TITLE
HikariJNDIFactory Tomcat7 java version 1.7.0.80

### ISSUE THREAD

**Issue by pgtips** [brettwooldridge/HikariCP#319]
Ubuntu 14.04.2 LTS

/var/lib/tomcat7/conf/server.xml (basing off sample JNDI DataSource on wiki)

`<GlobalNamingResources>
<Resource name="jdbc/CORS" auth="Container" factory="com.zaxxer.hikari.HikariJNDIFactory" type="javax.sql.DataSource" 
              minimumIdle="2" maximumIdle="5" maximumPoolSize="40" connectionTimeout="300000" 
              jdbcUrl="jdbc:mysql://localhost:3306/CORS?zeroDateTimeBehaviour=convertToNull" dataSource.implicitCachingEnabled="true"
              dataSource.user="" dataSource.password="" /
</GlobalNamingResources>`

jars put in /usr/share/tomcat7/lib/ as want access globally.

Tried using Hikari 2.3.7 and got:

`Caused by: java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
        at com.zaxxer.hikari.util.PropertyBeanSetter.<clinit>(PropertyBeanSetter.java:41)
        at com.zaxxer.hikari.HikariJNDIFactory.getObjectInstance(HikariJNDIFactory.java:55)`

added slf4j-api-1.7.10.jar and got:

`Caused by: java.lang.NoClassDefFoundError: javassist/ClassPath
        at com.zaxxer.hikari.HikariConfig.<clinit>(HikariConfig.java:31)
        at com.zaxxer.hikari.HikariJNDIFactory.createDataSource(HikariJNDIFactory.java:76)
        at com.zaxxer.hikari.HikariJNDIFactory.getObjectInstance(HikariJNDIFactory.java:67)
        at org.apache.naming.factory.ResourceFactory.getObjectInstance(ResourceFactory.java:141)`

added javassist-3.12.1.GA.jar and got:

same error as before.

Tomcat7 has only the ROOT app under webapps.

Tried using Hikari 2.3.8 - no change.

Searched the issues (and Google) and tried suggestions or added libraries to match - no change. Asking here as it 'appears' it is HikariConfig that is causing the issue...

Thank you,

**Comment by brettwooldridge** [comment]
@pgtips Have you tried javassist-3.18.2-GA?

**Comment by pgtips** [comment]
Thank you for the prompt reply. I thought I had grabbed a recent version.

I just tried replacing with 3.18.2-GA - no change to error. (Tried 3.19.0 while I was at).

**Comment by pgtips** [comment]
Sorry - closed by mistake.

**Comment by brettwooldridge** [comment]
Coming up on 1am here in Tokyo, I'll have to take a look tomorrow.

**Comment by pgtips** [comment]
Understand - appreciate it. 

Will keep digging and see if I can help at all.

**Comment by pgtips** [comment]
I am an idiot - I hadn't checked permissions during transfer to /usr/share/java.

(No doubt I still needed 3.18.2-GA)

Thanks!
