### ISSUE TITLE
Support for other metrics libraries

### ISSUE THREAD

**Issue by arthurdandrea** [brettwooldridge/HikariCP#321]
Currently HikariCP codebase only provides support for one metric library, [Dropwizard Metrics](https://dropwizard.github.io/metrics/), but I need to measure some metrics out of HikariCP with [Prometheus](http://prometheus.io/) and there is no binding between Dropwizard Metrics and Prometheus, not that it would be impossible to create one, but the assumptions that Dropwizard does on metrics would severely limit Prometheus functionality.

Studying HikariCP code, I can picture a implementation where instead of a (type erased) MetricRegistry setter in the datasource/pool/config/etc a setter for some kind of MetricFactory, a new class or interface, responsible for creating the MetricTracker object already used in BaseHikariPool. As I can see this approach could easily maintain backwards compatibility.

If that is feasible, I would like to send a pull request soon.

**Comment by brettwooldridge** [comment]
You should be able to use the Prometheus JMX exporter (https://github.com/prometheus/jmx_exporter) to get any/all Dropwizard metrics you need into Prometheus.

**Comment by brettwooldridge** [comment]
We'll certainly consider any pull request.
