### ISSUE TITLE
Error with pool initialization

### ISSUE THREAD

**Issue by Ouizzo** [brettwooldridge/HikariCP#322]
Hi! This error confuses me:

Error in custom provider, com.zaxxer.hikari.pool.PoolInitializationException: Exception during pool initialization at com.dcsquare.hivemq.example.database.DatabaseExamplePluginModule.provideConnectionPool(DatabaseExamplePluginModule.java:40)
  at com.dcsquare.hivemq.example.database.DatabaseExamplePluginModule.provideConnectionPool(DatabaseExamplePluginModule.java:40)
  while locating com.zaxxer.hikari.HikariDataSource

 @Provides
    public Connection provideConnection(final HikariDataSource ds) throws SQLException {
        return ds.getConnection();
    }

    @Provides
    @Singleton
    public HikariDataSource provideConnectionPool() {

        //See https://github.com/brettwooldridge/HikariCP

        final HikariConfig config = new HikariConfig();
        config.setMaximumPoolSize(10);
        config.setDataSourceClassName("com.mysql.jdbc.jdbc2.optional.MysqlDataSource");
 //     config.addDataSourceProperty("url", "jdbc:mysql://127.0.0.1:3306/newdatabase");
        config.addDataSourceProperty("serverName", "localhost");
        config.addDataSourceProperty("port", "3306");
      	config.addDataSourceProperty("databaseName", "newdatabase");
        config.addDataSourceProperty("user", "root");
        config.addDataSourceProperty("password", "Beer");

        //See https://github.com/brettwooldridge/HikariCP/wiki/MySQL-Configuration

        config.addDataSourceProperty("cachePrepStmts", true);
        config.addDataSourceProperty("prepStmtCacheSize", 250);
        config.addDataSourceProperty("useServerPrepStmts", true);

        return new HikariDataSource(config);

    }

I cant see what could cause it. Dos anyone have any ideas?

**Comment by Ouizzo** [comment]
The error pointing at this line:   final HikariConfig config = new HikariConfig();

**Comment by brettwooldridge** [comment]
I don't know why the line number would point to the line ``HikariConfig config = new HikariConfig();`` because the that exception is only called from ``HikariDataSource.initializeConnections()`` which is only called from the ``HikariDataSource`` constructor.

Either way, the PoolInitializationException should include a full stacktrace all the way up from the driver, which should itself contain the reason for the failure to establish a connection.

**Comment by Ouizzo** [comment]
I got it working now. I just delete it and re build/run it again. And displays no error. So it was probebly something with the config of maven build/run. Tank you for your interest in the question!

regards
Niclas
