### ISSUE TITLE
Tomcat + JNDI strange behaviour

### ISSUE THREAD

**Issue by jollyblade** [brettwooldridge/HikariCP#324]
Hi, 

I have a strange problem that we could not solve until now, so we had to remove hikari from the configuration. (Using the latest hikari version).

We have two jndi datasources in the tomcat server.xml, as follows (I changed the usernames and passwords and all specific data):

    <Resource name="jdbc/firstDataSource" 
			auth="Container" 
			factory="com.zaxxer.hikari.HikariJNDIFactory" 
			type="javax.sql.DataSource"  
			dataSourceClassName="com.mysql.jdbc.jdbc2.optional.MysqlDataSource"         		  
			driverClass="com.mysql.jdbc.Driver"
			jdbcUrl="jdbc:mysql://localhost:3306/schema?autoReconnect=true" 
			minimumIdle="5" maximumPoolSize="50" connectionTimeout="300000"
			maxLifetime="1800000" connectionTestQuery="SELECT 1 FROM DUAL" 
			dataSource.user="user1" dataSource.password="pwd1" />

	<Resource name="jdbc/secondDataSource" 
			  auth="Container"
			  factory="com.zaxxer.hikari.HikariJNDIFactory"
			  type="javax.sql.DataSource"
			  dataSourceClassName="com.mysql.jdbc.jdbc2.optional.MysqlDataSource"         		  
			  driverClass="com.mysql.jdbc.Driver"
			  jdbcUrl="jdbc:mysql://url2:3306/schema?autoReconnect=true" 
			  dataSource.user="user2" 
			  dataSource.password="pwd2" 
			  minimumIdle="5" 
			  maximumPoolSize="50" 
			  connectionTimeout="300000" 
			  maxLifetime="1800000" 
			  connectionTestQuery="SELECT 1 FROM DUAL" />

First, it did never work without the dataSourceClassName and driverClass properties, I had to add both. We had all the necessary libs under the tomcat lib. 

To the real thing: it seems that the second connection pool definition overwrites the username/password for the first too. So it tries to connect to the first db using the username and password from the second definition, so I get the following error: 

access denied for user1@localhost using password YES. 

If i remove either one of the pool definitions, it works just nice. If I change the username/password to the same, then the other pool won't work, with the same error. 

So this is really strange. 

Did anyone face the same issue?

Tried with:
- HikariCP-2.2.5
- HikariCP-2.3.8
- javassist-3.18.1-GA
- slf4j-api-1.7.10

thanks, 
Marton

**Comment by brettwooldridge** [comment]
@jollyblade Any change you could make a simple example project (maven/gradle/ant) that demonstrates the problem?  I'm traveling on business the next few weeks and I don't have to time setup and configure Tomcat.  I'm not a Tomcat user, and I gave it a go for about an hour tonight, but ran out of steam.  A small  runnable demo project that let's me reproduce the issue should be enough to fix it rather quickly.

**Comment by brettwooldridge** [comment]
Regarding the issue of needing both ``dataSourceClassName`` and ``driverClass`` ... I'm not even sure
how the pool can start, because ``driverClass`` is not a valid property (``driverClassName`` would
be the correct property name).  HikariCP should throw an exception
([from this method](https://github.com/brettwooldridge/HikariCP/blob/2.3.x/hikaricp-common/src/main/java/com/zaxxer/hikari/util/PropertyBeanSetter.java#L120)) during startup.

Anyway, when using ``driverSourceClassName``, the ``jdbcUrl`` property is ignored.  What is happening is that both ``driverClass`` and ``dataSourceClassName`` are being ignored.  HikariCP is resolving the driver using the Java ``DriverManager`` based on the jdbcUrl alone.

**Comment by brettwooldridge** [comment]
Try this:
```xml
<Resource name="jdbc/firstDataSource" 
          auth="Container" 
          factory="com.zaxxer.hikari.HikariJNDIFactory" 
          type="javax.sql.DataSource"  
          jdbcUrl="jdbc:mysql://localhost:3306/schema" 
          username="user1"
          password="pwd1"
          minimumIdle="5" maximumPoolSize="50" connectionTimeout="300000" maxLifetime="1800000" 
          connectionTestQuery="SELECT 1 FROM DUAL"  />

<Resource name="jdbc/secondDataSource" 
          auth="Container"
          factory="com.zaxxer.hikari.HikariJNDIFactory"
          type="javax.sql.DataSource"
          jdbcUrl="jdbc:mysql://url2:3306/schema" 
          username="user2" 
          password="pwd2" 
          minimumIdle="5" maximumPoolSize="50" connectionTimeout="300000" maxLifetime="1800000" 
          connectionTestQuery="SELECT 1 FROM DUAL" />
```
Note the removal of ``?autoReconnect=true`` from the URL, and the removal of ``connectionTestQuery``.  Also note the use of ''username'' and ``password`` instead of ``dataSource.user`` and ``dataSource.password``.

Finally, I suggesting enabling **debug** level logging for the ``com.zaxxer.hikari`` package.

**Comment by brettwooldridge** [comment]
@jollyblade It seems that a user was having a similar issue back in 2008 (before HikariCP), unfortunately there is no answer posted for the question, but it makes me strongly suspect a configuration issue rather than a bug in HikariCP:

https://community.oracle.com/thread/634973

**Comment by jollyblade** [comment]
Hi Brett, 

Thank you for the answers. 
I was trying to reproduce the issue outside of our test server environments, without any success. 
On my localhost tomcat starts up without any problems, and both connection pools work just fine. 
I also managed to make one of the servers work with exactly the same configs I posted in the original question, maybe it is not even configuration... but on the two other servers it just doesn't work. 

I will do some more research, I will also enable the debug log, and post my results here. 

Thank you very much for the suggestions, I will also try the config you mentioned above.

**Comment by jollyblade** [comment]
Hi, 

Finally I could make it work, you were right, the following settings are valid:

    <Resource name="jdbc/myAProdDB" 
			  auth="Container" 
			  factory="com.zaxxer.hikari.HikariJNDIFactory" 
			  type="javax.sql.DataSource" 
			  driverClassName="com.mysql.jdbc.Driver"
			  jdbcUrl="jdbc:mysql://localhost:3306/a1" 
			  username="x" 
			  password="y" 
			  minimumIdle="5" maximumPoolSize="50" connectionTimeout="300000" maxLifetime="1800000" />
			  
	<Resource name="jdbc/myBProdDB" 
	          auth="Container"
			  factory="com.zaxxer.hikari.HikariJNDIFactory"
			  type="javax.sql.DataSource"
			  driverClassName="com.mysql.jdbc.Driver"
			  jdbcUrl="jdbc:mysql://abc:3306/y" 
			  username="x2" 
			  password="y2" 
			  minimumIdle="5" maximumPoolSize="50" connectionTimeout="300000"     maxLifetime="1800000" />

The driver class name is needed, I found the following on the tomcat site:

java.sql.DriverManager supports the service provider mechanism. This feature is that all the available JDBC drivers that announce themselves by providing a META-INF/services/java.sql.Driver file are automatically discovered, loaded and registered, relieving you from the need to load the database driver explicitly before you create a JDBC connection. **However, the implementation is fundamentally broken in all Java versions for a servlet container environment. The problem is that java.sql.DriverManager will scan for the drivers only once.**

So tomcat needs a driver class name defined, otherwise it can't locate the driver. 

Maybe this wiki page needs an update then:
https://github.com/brettwooldridge/HikariCP/wiki/JNDI-DataSource-Factory-(Tomcat,-etc.)

The dataSource.user and dataSource.password properties don't work. 

However, I have no idea how the original config worked on some systems, and why it did not on others. Just the daily magic.

Best regards, and thank you for your help once again, 
Marton

**Comment by jollyblade** [comment]
I guess we can close the issue :)

**Comment by brettwooldridge** [comment]
@jollyblade Thanks for the update.  I'll make an update to the JNDI wiki page.
