### ISSUE TITLE
Why hikaricp connection pool dies in Idle state ? Is it configurable ?

### ISSUE THREAD

**Issue by ankitmobolt** [brettwooldridge/HikariCP#325]
I am using HikariCp with my play application in Java. After few mins of idle state, it seems hikarcp connection pool dies, and when it gets new request it starts again. Sometime I have also seen Db persistence error with message that sessionfactory not available, which I believe is side-effect of this issue. Why hikaricp dies in idle state, and can I some how configure it to not do so ?

I get following logs, after every new requests in few mins of idle time -

[info] application - Application shutdown...
[info] application - Stopping HikariCP connection pool...
[info] application - Starting HikariCP connection pool...

**Comment by brettwooldridge** [comment]
This is a question for the Play forum.  HikariCP never stops all by itself.  Something is stopping and re-starting HikariCP.  And it seems from the messages above, something is shutting down your application.
