### ISSUE TITLE
jConnect Sybase driver java.lang.NoSuchMethodException

### ISSUE THREAD

**Issue by dimitrisli** [brettwooldridge/HikariCP#328]
Hi there,

while using the the jConnect driver (v.7.0) and also using the Driver datasource implementation as instructed in the HikariCP documentation (bottom of the page): com.sybase.jdbcx.SybDataSource

that is giving the following error:

Caused by: java.lang.InstantiationException: com.sybase.jdbcx.SybDataSource
	at java.lang.Class.newInstance(Class.java:418)
	at com.zaxxer.hikari.util.UtilityElf.createInstance(UtilityElf.java:117)
	... 62 more
Caused by: java.lang.NoSuchMethodException: com.sybase.jdbcx.SybDataSource.<init>()
	at java.lang.Class.getConstructor0(Class.java:3069)
	at java.lang.Class.newInstance(Class.java:403)
	... 63 more

Apparently HikariCP is looking for a default constructor that is not there.

There is another datasource implementation in the driver that has a default constructor:
com.sybase.jdbc4.jdbc.SybDataSource

Is the intended one to use?

thanks,
Dimitrios

**Comment by brettwooldridge** [comment]
Quite possibly.  That DataSource was reported by a user and I just added it to the table, but I had not way to verify it.  Please let me know if the other DataSource works.

**Comment by dstore-dbap** [comment]
I can confirm that jConnect 7.0.7 (latest) works with Hikari 2.3.8. 

Sample code to create the datasource:

```java
pool = new HikariDataSource();
pool.setDataSourceProperties(props);
pool.setJdbcUrl("jdbc:sybase:Tds:" + this.host + ":" + this.port);
pool.setUsername(this.username);
pool.setPassword(this.password);
pool.setConnectionInitSql("use " + this.dbname + " set quoted_identifier off");
 ```

These special driver properties helped us in some rare cases, but may be adjusted:

```java
Properties props = new Properties();
props.put("APPLICATIONNAME", applicationName);
props.put("USE_METADATA", "false");
props.put("TEXTSIZE", Integer.MAX_VALUE);
props.put("SUPPRESS_PARAM_FORMAT", "false");
props.put("HOMOGENEOUS_BATCH", "false");
props.put("CHARSET", "utf8");
```

When executing stored procedures via CallableStatements using "unwrap" is necessary to get to Sybase specific features (like named parameters):

```java
CallableStatement cst = connection.prepareCall(sqlString.toString());
SybCallableStatement sybCst = cst.unwrap(SybCallableStatement.class);
```

**Comment by brettwooldridge** [comment]
Thanks for the update.
