### ISSUE TITLE
Would it be possible to shade javassist to avoid conflicts with applications using it

### ISSUE THREAD

**Issue by roytmana** [brettwooldridge/HikariCP#332]
Javassist is a popular library and ideally it should be shaded into HikariCP jar using https://maven.apache.org/plugins/maven-shade-plugin/ to avoid any conflicts. Conflicts can arise when hikari jar reside in application WAR as well as when it is deployed on web server level (where web servers do not separate class loaders for server and contexts). Not only it could cause issues for an application it can cause issues for the pool itself if application supplies incompatible javassist version so shading makes it much safer and makes it one less dependency to deploy.

**Comment by brettwooldridge** [comment]
In the upcoming 2.4.0 release javassist has ben eliminated as a runtime dependency completely.
