### ISSUE TITLE
Network problems - No answer on query

### ISSUE THREAD

**Issue by stefuNz** [brettwooldridge/HikariCP#337]
Hi. I had a problem tonight with network problems which may appear.
At the time when the problems appeared i was sending a SELECT query but never received an answer - after 90 minutes i restarted the application.
This is my Config:

        config.setConnectionTimeout(3 * 60 * 1000);
        config.setAutoCommit(false);
        config.setIdleTimeout(30 * 1000);
        config.setConnectionTestQuery("SELECT 1");
        config.setMaximumPoolSize(10);

I didn't set a query timeout on the statement.
JDBC String had these options:

    ?rewriteBatchedStatements=true&autoReconnect=true&zeroDateTimeBehavior=convertToNull&dumpQueriesOnException=true

Could `setConnectionTimeout` have caused this?

**Comment by brettwooldridge** [comment]
I would recommend not using ``autoReconnect``.  As the MySQL documentation states:
```
The use of this feature is not recommended, because it has side effects related to
session state and data consistency when applications don't handle SQLExceptions
properly, and is only designed to be used when you are unable to configure your 
application to handle SQLExceptions resulting from dead and stale connections properly.
```
HikariCP can't help you once the connection as left the pool (been given to your application).  You should either set query timeouts on your ``Statement`` objects, or set the MySQL ``socketTimeout`` driver property to the maximum time you expect a query to take.

``socketTimeout`` is rather a blunt instrument, and will apply to all socket I/O for the connection but if setting query timeouts on all of your SQL statements is not an option it can be used.

 If, for example, you never expect a query to take longer than 2 minutes, setting ``socketTimeout`` to ``120000``(ms) should be safe.

Additionally, ``socketTimeout`` may be the only way to handle network partition events like you experienced.
