### ISSUE TITLE
SQLException loses SQLState

### ISSUE THREAD

**Issue by carymrobbins** [brettwooldridge/HikariCP#338]
When Hikari throws a `SQLException`, for instance, if we were unable to connect to the database, the underlying `SQLState` value is not set.  Given the following exception -

```scala
try { .. } catch {
  case e: java.sql.SQLException =>
    println(e.getSQLState) // null
    val cause = e.getCause.asInstanceOf[org.postgresql.util.PSQLException]
    println(cause.getSQLState) // 08001
}
```

The desired behavior would be for the `SQLException` to contain the underlying SQLState of its cause.

**Comment by brettwooldridge** [comment]
v2.3.9 is now available with this fix.
