### ISSUE TITLE
Mistake in documentation for configuration via java.util.Properties

### ISSUE THREAD

**Issue by Kamaruni** [brettwooldridge/HikariCP#339]
[Here](https://github.com/brettwooldridge/HikariCP#initialization) the documentation states that the LogWriter can be configured via java.util.Properties like this:

```java
Properties props = new Properties();
// ...
props.setProperty("dataSource.logWriter", new PrintWriter(System.out));
```

setProperty only accepts String as second parameter, though.

How can you actually configure the log writer via java.util.Properties?

**Comment by brettwooldridge** [comment]
You're right, it's a documentation error.  You can set it like so:
```java
Properties props = new Properties();
// ...
props.put("dataSource.logWriter", new PrintWriter(System.out));
```
