### ISSUE TITLE
Is this a defect about Synchronizer.releaseShared in Java6ConcurrentBag/Java8ConcurrentBag

### ISSUE THREAD

**Issue by atellwu** [brettwooldridge/HikariCP#343]
According to the code below, when "Synchronizer.releaseShared()" is called, all of the threads waiting on  method "borrow()" will be signalled. 

https://github.com/brettwooldridge/HikariCP/blob/2.3.x/hikaricp-java6/src/main/java/com/zaxxer/hikari/util/Java6ConcurrentBag.java#L111

      @Override
      protected long tryAcquireShared(final long seq)
      {
         return java67hasQueuedPredecessors() ? -1L : getState() - (seq + 1);
      }

Hope is like this: If only one (or N) entry is requited, it's better to signal only one (or N) thread, right?

**Comment by brettwooldridge** [comment]
@atellwu Similar to standard ``Object.wait()``, ``Object.notify()``, and ``Object.notifyAll()`` semantics, the options provided by ``java.util.concurrent.locks.AbstractQueuedLongSynchronizer`` are:
 * Do not notify (*return -1*)
 * Notify one thread (*return 0*)
 * Notify all threads (*return >0*)

The code above supports: signal none, signal one, and signal all.

#### Example
Assume the [sequence](https://github.com/brettwooldridge/HikariCP/blob/2.3.x/hikaricp-common/src/main/java/com/zaxxer/hikari/util/ConcurrentBag.java#L122) (``getState()``) is ``13`` when *Thread1* starts waiting.

*Thread2* also wants to acquire a connection, and sees the *sequence* at ``13``.

*Thread3* now releases one connection, and *sequence* becomes 14.  The ``AbstractQueuedLongSynchronizer`` will unpark (wake-up) the first queued thread (*Thread1*).

*Thread1* will call ``tryAcquiredShared(13)``.

The ``getState() - (seq + 1)`` calculation results in ``14 - (13 + 1)`` which equals ``0``.  When ``tryAcquiredShared()`` returns zero (0), that tells the ``AbstractQueuedLongSynchronizer`` *"don't unpark any more threads, there is only one resource available"*.  Only one thread was signaled.

---------------------------
If, in this example, two connections had been released quickly, *sequence* would have gone to ``15``. The calculation by *Thread1* would be ``15 - (13 + 1) = 1``.  A return value > 0 means *"continue to the next queued thread"*.  So, *Thread2* would also have called ``tryAcquiredShared()``.

The ability to notify (signal) *N threads specifically* only exists with higher-level constructs such as ``Semaphore``, but imposes an unacceptable performance tradeoff in real world benchmarks against the 
``AbstractQueuedLongSynchronizer``.

**Comment by atellwu** [comment]
Yes, you are right, thanks for your answer
