### ISSUE TITLE
Pool freezing when three times more users than connections in the pool

### ISSUE THREAD

**Issue by emickiewicz** [brettwooldridge/HikariCP#344]
Hi Brett,

I'm testing the Hikari connection pool with our application, and I noticed a strange behavior while performing load tests using JMeter.

#### Context
Our application is a webapp relying on a PostgreSQL 9.3 database. HikariCP is the last 2.3.8 maven artifact.
I use a detailled JMeter scenario imitating 100 very active users, and it performs well with our legacy connection pool.
Numerous connections are asked from the pool for each page requested by a user, but there is no connection leak at all (I double checked that, and nothing shows up with the `LeakDetectionThreshold` property set to 10000 while a small amount of users were running through this JMeter scenario).
When I set the `MaximumPoolSize` to 100 connections despite knowing it's a bad practice (as you described it in the Hikari wiki), all goes fine without any error. I reach 40-50 "in use" connections at the peak of the scenario (some SQL queries take a long time to complete, thus some connections are released after quite a while).
I'm monitoring the server holding Postgres using htop & pg_top to check the number of open connections, the global load of the server, the CPU usage, etc.
HikariCP debug level is set to `FINE`, the pool state and connection closings are displaying well. 
Postgres configuration is set to 200 max connections. The server is not swapping, ram usage is stable, cache is warmed up and stable too through the entire scenario.

#### Problem
When I set the `MaximumPoolSize` to a small size following the recommendations of your wiki, the pool tends to completely "freeze" when JMeter reach 3 times more users than the number of connections set with `MaximumPoolSize` (e.g. 50-60+ users in case the pool is set to 20).
By "freeze", I mean that the htop CPU usage drops to 0% on all cores, like when the application is idle, and all Postgres connection are idle too (no IORead or IOWrite, no CPU etc.).
LogPoolState reports 20 "in use" connections, 0 "available", and a lot more are "waiting".
Here is what happens when this situation shows up:
1. There is no connection in the "waiting" queue, as half of the available connections are idling with 60 users.
2. All activities stop on the PostgreSQL server (0% CPU usage and Postgres connections labeled as "Idle"). All new connections are added to the waiting queue.
3. Some connections start to time out.
4. When enough connections timed out, the pool come back to life and a very limited number of connections perform during a short amount of time (0.1 - 0.5 sec).
5. The pool freeze again, no more activity on the Postgres server.
6. Some connections start to time out... --> 3.

When I stop JMeter and after all the associated waiting connections time out, the application is working fine again, and the pool goes back to (total=20, inUse=0, avail=20, waiting=0).

#### Example
 `MaximumPoolSize` = 20
* JMeter users number increase to 55 - Hikari Log : (total=20, inUse=10, avail=10, waiting=0) // Everything works well
* JMeter users number increase to ~65 - Hikari Log : (total=20, inUse=20, avail=0, waiting=55) // Complete freeze
* The number of "waiting" connections matchs the exact number of logged users a dozen of seconds after the freeze. E.g. for 72 users : (total=20, inUse=20, avail=0, waiting=72)

The very strange thing is that the pool is reporting low usage before freezing at 60+ users, and the pg_top CPU usage is not very high too - which is usual with 60 JMeter users.
In case a pool is oversubscrided with long time running queries, `getConnection()` would time out but the "in use" connections should still be running. 

I tried to solve this issue with the different Postgres JDBC drivers (pgjdbc-ng and Postgres original driver), with a lot of different settings for the both the pool and the drivers.
I also tried to delay the time between two users starts in JMeter, but the issue is still the same. 

I am missing anything ? Should I try a particular pool configuration ?

I can't think of an option that could lead the pool to behave like this...

Thanks for your help,
Emmanuel.

EDIT : This situation happened too with only 30 concurrent JMeter users and a pool set to 20 connections. The scenario runs without issue for a while at 30 users but then the problem is the same. My guess is the following : if the pool reach 20 in use connections the freezing happens (I'll run more tests today to confirm this hypothesis).

**Comment by brettwooldridge** [comment]
@emickiewicz Can you get a thread dump of the application while it is in the "frozen" state?  I'm curious what those threads are doing ... what they are blocked on.

If there isn't turn over occuring in the pool, my working theory is lock contention in the database.  Can you obtain lock statistics as the load ramps and and freezes?

https://wiki.postgresql.org/wiki/Lock_Monitoring

**Comment by brettwooldridge** [comment]
@emickiewicz Just one point of clarification.  When you say, for example, "All new connections are added to the waiting queue", what the logged pool state is actually saying is that "N *application threads* are waiting for a connection", rather than "N new connections are waiting to be added".  The first three metrics (*total, inUse, avail*) reflect pool state, while the "waiting" value is really a metric of how many application threads are blocked in ``getConnection()``.

Speaking of metrics, if you can possibly throw [Dropwizard metrics](https://github.com/brettwooldridge/HikariCP/wiki/Dropwizard-Metrics) into the mix, HikariCP collects much more detail metrics.  Setting up a [slf4j or console](https://dropwizard.github.io/metrics/3.1.0/manual/core/#man-core-reporters-slf4j) reporter is simple (configured to log at 10-30 second intervals).

**Comment by emickiewicz** [comment]
@brettwooldridge Thanks for the clarification. That is indeed what I understood.

I'm still working on it, I'll provide you with more information and possibly the lock statistics as soon as I can.

**Comment by brettwooldridge** [comment]
@emickiewicz Any updates you can share?
