### ISSUE TITLE
A little confused about maxLifetime

### ISSUE THREAD

**Issue by nethibernate** [brettwooldridge/HikariCP#350]
I have a little confused about maxLifetime configuration. In hikari, there is a housekeeping to check idleTimeout of each connection periodically, so when should I use the maxLifetime?

**Comment by brettwooldridge** [comment]
In a busy pool, connections are likely to never reach their *idleTimeout*.  However, many firewalls and load-balancers, that often lie between an application and the database, impose socket lifetimes.  Often, when this lifetime is reached, the connection is cut regardless of current traffic.

However, probably the primary reason to cycle connections periodically is as a guard against memory leaks.  Databases often have resources (caches, file-handles, meta-data) attached to a connection, and if a connection is *never* retired then [resource leaks are magnified over time](https://www.percona.com/blog/2012/03/21/troubleshooting-mysql-memory-usage/).  And even JDBC drivers have been [known to leak](https://bugs.mysql.com/search.php?search_for=leak&bug_type%5B%5D=Connector%2FJ&status%5B%5D=Active&severity=&limit=30&order_by=&cmd=display&phpver=&os=0&os_details=&bug_age=0&tags=&similar=&target=&last_updated=0&defect_class=all&workaround_viability=all&impact=all&fix_risk=all&fix_effort=all&triageneeded=).
