### ISSUE TITLE
How do I import the source to IntelliJ IDEA?

### ISSUE THREAD

**Issue by diguage** [brettwooldridge/HikariCP#351]
I import the source to IntelliJ IDEA as maven project. But,  **`hikaricp-java6` module can not refer to the sources of  `hikaricp-common`.**

How do I import the source to IntelliJ IDEA and compile the source?

Thanks a lot.

**Comment by brettwooldridge** [comment]
It's a huge pain in the ass.  I recommend using the ``dev`` branch, it's much cleaner -- a single module.

**Comment by diguage** [comment]
@brettwooldridge Thanks again.
