### ISSUE TITLE
HikariDataSource.getConnection is slow under load

### ISSUE THREAD

**Issue by kpadmasola** [brettwooldridge/HikariCP#352]
Hi Brett,

I recompiled the application with 2.3.10-SNAPSHOT. I enabled coda hale metrics, set JVM argument -Dcom.zaxxer.hikari.aliveBypassWindow=5000. I ran 2 simulations, one with a pool size of 7 and another with a pool size of 22 on my laptop. The JMX metrics graphs are attached.

Please let me know if you need more details.

simulation details:
40 concurrent users, over 5 minutes

with poolsize of 7:
Summary statistics from gatling perf tool
![summary](https://cloud.githubusercontent.com/assets/1274758/8830977/ff534df4-30bc-11e5-8be4-776ddec699d9.PNG)

Wait
![wait](https://cloud.githubusercontent.com/assets/1274758/8830536/53ce692a-30ba-11e5-933a-567e68691530.PNG)
activeConnections
![activeconnections](https://cloud.githubusercontent.com/assets/1274758/8830538/53dcc13c-30ba-11e5-93d2-94ee19ec7e92.PNG)
idleconnections
![idleconnections](https://cloud.githubusercontent.com/assets/1274758/8830537/53dabd2e-30ba-11e5-9bea-5b9b7fd39f8c.PNG)
pendingconnections
![pendingconnections](https://cloud.githubusercontent.com/assets/1274758/8830539/53e1382a-30ba-11e5-82d2-c3d50848c2fb.PNG)
totalconnections
![totalconnections](https://cloud.githubusercontent.com/assets/1274758/8830540/53e19158-30ba-11e5-8535-96a11980a192.PNG)
usage
![usage](https://cloud.githubusercontent.com/assets/1274758/8830541/53e4ec7c-30ba-11e5-9b5a-22c1d91818bb.PNG)

with poolsize of 22:
Summary statistics from gatling perf tool
![summary](https://cloud.githubusercontent.com/assets/1274758/8831004/188ee76a-30bd-11e5-9a8d-112dd5ee74fd.PNG)

wait
![wait](https://cloud.githubusercontent.com/assets/1274758/8830621/cb181814-30ba-11e5-9797-361568d02664.PNG)
activeconnections
![activeconnections](https://cloud.githubusercontent.com/assets/1274758/8830622/cb1f4b52-30ba-11e5-98b5-d650a81c3cc8.PNG)
idleconnections
![idleconnections](https://cloud.githubusercontent.com/assets/1274758/8830623/cb211234-30ba-11e5-8cd6-90d6026f329b.PNG)
pendingconnections
![pendingconnections](https://cloud.githubusercontent.com/assets/1274758/8830625/cb256578-30ba-11e5-9143-596220687220.PNG)
totalconnections
![totalconnections](https://cloud.githubusercontent.com/assets/1274758/8830624/cb246a9c-30ba-11e5-9505-9fd831b52b0f.PNG)
usage
![usage](https://cloud.githubusercontent.com/assets/1274758/8830626/cb2b2af8-30ba-11e5-941e-4741ee5121f8.PNG)

thanks,
Krishna
PS: this thread is continued from HikariCP Google Groups thread https://groups.google.com/forum/#!topic/hikari-cp/lLabMIN6PEY

On Wednesday, July 22, 2015 at 1:26:11 PM UTC+5:30, Brett Wooldridge wrote:
Hi Krishna,

Even for the Java 6/7 jars you must use Java 8 to build.  You can use any version at runtime, but the build itself requires Java 8.

You can also download the 2.3.10-SNAPSHOT JAR file directly from here.

**Comment by brettwooldridge** [comment]
The *usage* metric -- how long on average a connection is out of the pool -- in both cases, looks to me like severe throttling on the database side.  Even when the load is just starting to ramp, *usage* times are already up into the seconds range.  Whereas under an ideally loaded server even at full load you would hope to see only double-digit millisecond times.

As a sanity check, it would be interesting to drop in another pool, like [Tomcat dbcp](http://search.maven.org/#artifactdetails%7Corg.apache.tomcat%7Ctomcat-dbcp%7C8.0.24%7Cjar).

We've added quite a bit of debug logging to 2.4.0 that could possibly shed light -- if indeed there is some bad interaction going on between the pool and the DB.

You can [get the latest snapshot here](https://oss.sonatype.org/content/repositories/snapshots/com/zaxxer/HikariCP/2.4.0-rc4-SNAPSHOT/HikariCP-2.4.0-rc4-20150723.140734-8.jar).  Or use the following dependency:
```xml
<dependency>
    <groupId>com.zaxxer</groupId>
    <artifactId>HikariCP</artifactId>
    <version>2.4.0-rc4-SNAPSHOT</version>
</dependency>
```

I'm particularly interested if you see any messages like:
```
07-21 21:15:56,681 ... HikariPool-0 - Reset autoCommit, isolation on connection ...
```

**Comment by kpadmasola** [comment]
Hi Brett,

I updated to 2.4.0-rc4-SNAPSHOT and ran the simulation again after turning off the cache completely. This is with 40 concurrent users and 22 pool connections.

I found a lot of these logs, not sure if they are a problem:
com.zaxxer.hikari.pool.PoolElf:259,resetConnectionState,a897725f-f7fb-442f-8a4f-9004eced131b,nothing - Reset com.mysql.jdbc.JDBC4Connection@6bfdaa4c on connection {}

I did not see the log that you mentioned above in your message.

The results are as follows:

Simulation Summary Statistics:
![simulationsummary](https://cloud.githubusercontent.com/assets/1274758/8959215/2dbd5ab2-3627-11e5-93a0-b79ca6a01a9e.PNG)

active connections:
![activeconnections](https://cloud.githubusercontent.com/assets/1274758/8959158/efa7ca0a-3626-11e5-8531-0152f7c9b8ff.PNG)

idle connections:
![idleconnections](https://cloud.githubusercontent.com/assets/1274758/8959164/f979224a-3626-11e5-9355-4e5731b12b2b.PNG)

Pending connections:
![pendingconnections](https://cloud.githubusercontent.com/assets/1274758/8959172/03b30456-3627-11e5-9c09-2ccd510f1465.PNG)

Total connections:
![totalconnections](https://cloud.githubusercontent.com/assets/1274758/8959185/1245a7a8-3627-11e5-8462-3501122b5b36.PNG)

Usage:
![usage](https://cloud.githubusercontent.com/assets/1274758/8959190/1903ec8a-3627-11e5-9999-04e69ce598cd.PNG)

Wait:
![wait](https://cloud.githubusercontent.com/assets/1274758/8959198/20a3a2b4-3627-11e5-9da7-f2587bc7fe4e.PNG)

Please let me know if you need more information.

thanks,
Krishna

**Comment by brettwooldridge** [comment]
@kpadmasola I actually put this log (and a few other logs) in just for troubleshooting your case, and the potential of other users needing insight into pool internals.

The fact the it reset *"nothing"* is a good thing, better would be that this call never occurs.  But it provides you a possible avenue of investigation.

(follow the links to understand what is going on)

Basically, when an application or framework "above" HikariCP alters connection state programmatically, for example [calling Connection.setAutoCommit()](https://github.com/brettwooldridge/HikariCP/blob/master/src/main/java/com/zaxxer/hikari/proxy/ConnectionProxy.java#L329), it marks the connection state as "dirty".  When the application/framework calls ``close()`` to return the connection to the pool, this state [is checked](https://github.com/brettwooldridge/HikariCP/blob/master/src/main/java/com/zaxxer/hikari/proxy/ConnectionProxy.java#L185), and if it is dirty then a call is made to reset it back to the default pool configuration.

In the [resetConnectionState()](https://github.com/brettwooldridge/HikariCP/blob/master/src/main/java/com/zaxxer/hikari/pool/PoolElf.java#L230) method, the current connection state is compared to the default state that pool connections should have.  If there are differences, then calls are made to the connection to restore proper state.

At the end of that method, we now log what reset actions were taken.  The resetting of any of these states could potentially involve a roundtrip to the database, and furthermore could be "expensive" on the database side.

*One* of the two things below is happening.  Your code, or a framework, is setting the connection state (which marks it dirty)...
 * ... but luckily it is setting the connection state to the same as pool defaults.  Therefore the actual cost of ``resetConnectionState()`` is likely only a few dozen nanoseconds.
 * ... but unfortunately what is actually happening is: the framework is querying connection settings after ``getConnection()``, altering them in some (expensive) way, and the returning them to their defaults before ``close()``.

As noted, the first is harmless.  But if the second is occurring, it could be a cause for concern.  For example, in many databases even querying the auto-commit or transaction isolation on a connection is "expensive", and altering it even more so.

**Comment by jnehlmeier** [comment]
In case you both didn't notice: The `usage` and `wait` metric are both showing the `count` value which is useless. Currently it just shows you that you have done 102256 requests. (Same with the post before which shows a count of 34850).

You want the percentile values of the `usage` and `wait` metrics instead.

**Comment by brettwooldridge** [comment]
@jnehimeier good point.

**Comment by jnehlmeier** [comment]
Well ok the count graph is not totally useless. You can see that the slope of the graph increases after some minutes. Once the slope is increased you also see much better pool stats as there are no pending connections anymore and Hikari has plenty of idle connections available. So at the beginning getConnection() is called less frequently as in the second half of the test.

To me it seems like that in the beginning of the stress test the application code / database acts slower as in the second half of the test. That causes Hikari to hand out all connections in the pool every now and then and finally block sometimes on getConnection() in the first half of the test. In the second half it probably never blocks on getConnection().

You should do longer stress tests and not just 5 minutes. To me it looks like a (slower) warmup phase in the beginning.

**Comment by kpadmasola** [comment]
@brettwooldridge I am using Spring and Hibernate, and calling LocalSessionFactoryBean.setDataSource(<HikariDataSource>), where hikariDataSource is created by passing in a HikariConfig instance.

I am not explicitly querying connection settings anywhere in my application. I went through HibernateTransactionManager code, but didn't see anything suspicious. Any ideas where I should look in the framework codebase?

**Comment by brettwooldridge** [comment]
@kpadmasola No ideas immediately off the top of my head, it will take some time to look into their sources.  If you have the ability to compile HikariCP, you might just want to insert your own log messages into the ``ConnectionProxy`` methods that set ``isConnectionStateDirty = true`` in order to see who is calling them.

You can do it like: ``LOGGER.debug("setAutoCommit(), new Exception())`` and you'll get a stacktrace that indicates who the caller is.

**Comment by kpadmasola** [comment]
Hi Brett,

I compiled the latest sources after adding debug statements as you suggested. Here's what I found:

- the application is trying to query the database in a (readonly) transaction.
- `HibernateTransactionManager.doBegin` results in calling `ConnectionProxy.setReadOnly`
- `JDBCTransaction.begin` results in `ConnectionProxy.setAutoCommit`
- `JDBCTransaction.commit` results in calling `ConnectionProxy.setAutoCommit`
- `HibernateTransactionManager.doCleanupAfterCompletion` calls `ConnectionProxy.setReadOnly`

Could this be causing the issue we are seeing? if so, how to avoid the perf hit?

Relevant log excerpt below:

```
2015-08-04 17:52:53.588,DEBUG,http-bio-8080-exec-4,com.zaxxer.hikari.proxy.ConnectionProxy:340,setReadOnly,75680971-fff7-49a8-96c8-db503cf99b6e,setReadOnly()
java.lang.Exception
	at com.zaxxer.hikari.proxy.ConnectionProxy.setReadOnly(ConnectionProxy.java:340)
	at com.zaxxer.hikari.proxy.HikariConnectionProxy.setReadOnly(HikariConnectionProxy.java)
	at sun.reflect.GeneratedMethodAccessor50.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.hibernate.jdbc.BorrowedConnectionProxy.invoke(BorrowedConnectionProxy.java:50)
	at com.sun.proxy.$Proxy115.setReadOnly(Unknown Source)
	at org.springframework.jdbc.datasource.DataSourceUtils.prepareConnectionForTransaction(DataSourceUtils.java:155)
	at org.springframework.orm.hibernate3.HibernateTransactionManager.doBegin(HibernateTransactionManager.java:513)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:373)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:130)
...
2015-08-04 17:52:53.589,DEBUG,http-bio-8080-exec-4,com.zaxxer.hikari.proxy.ConnectionProxy:330,setAutoCommit,75680971-fff7-49a8-96c8-db503cf99b6e,setAutoCommit()
java.lang.Exception
	at com.zaxxer.hikari.proxy.ConnectionProxy.setAutoCommit(ConnectionProxy.java:330)
	at com.zaxxer.hikari.proxy.HikariConnectionProxy.setAutoCommit(HikariConnectionProxy.java)
	at org.hibernate.transaction.JDBCTransaction.begin(JDBCTransaction.java:63)
	at org.hibernate.impl.SessionImpl.beginTransaction(SessionImpl.java:1326)
	at org.springframework.orm.hibernate3.HibernateTransactionManager.doBegin(HibernateTransactionManager.java:560)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:373)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:130)
...
2015-08-04 17:52:53.592,DEBUG,http-bio-8080-exec-4,com.zaxxer.hikari.proxy.ConnectionProxy:330,setAutoCommit,75680971-fff7-49a8-96c8-db503cf99b6e,setAutoCommit()
java.lang.Exception
	at com.zaxxer.hikari.proxy.ConnectionProxy.setAutoCommit(ConnectionProxy.java:330)
	at com.zaxxer.hikari.proxy.HikariConnectionProxy.setAutoCommit(HikariConnectionProxy.java)
	at org.hibernate.transaction.JDBCTransaction.toggleAutoCommit(JDBCTransaction.java:194)
	at org.hibernate.transaction.JDBCTransaction.commitAndResetAutoCommit(JDBCTransaction.java:142)
	at org.hibernate.transaction.JDBCTransaction.commit(JDBCTransaction.java:115)
	at org.springframework.orm.hibernate3.HibernateTransactionManager.doCommit(HibernateTransactionManager.java:661)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:757)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:726)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:150)
...
2015-08-04 17:52:53.593,DEBUG,http-bio-8080-exec-4,com.zaxxer.hikari.proxy.ConnectionProxy:340,setReadOnly,75680971-fff7-49a8-96c8-db503cf99b6e,setReadOnly()
java.lang.Exception
	at com.zaxxer.hikari.proxy.ConnectionProxy.setReadOnly(ConnectionProxy.java:340)
	at com.zaxxer.hikari.proxy.HikariConnectionProxy.setReadOnly(HikariConnectionProxy.java)
	at sun.reflect.GeneratedMethodAccessor50.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.hibernate.jdbc.BorrowedConnectionProxy.invoke(BorrowedConnectionProxy.java:50)
	at com.sun.proxy.$Proxy115.setReadOnly(Unknown Source)
	at org.springframework.jdbc.datasource.DataSourceUtils.resetConnectionAfterTransaction(DataSourceUtils.java:224)
	at org.springframework.orm.hibernate3.HibernateTransactionManager.doCleanupAfterCompletion(HibernateTransactionManager.java:731)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.cleanupAfterCompletion(AbstractPlatformTransactionManager.java:1012)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:807)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:726)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:150)
...
2015-08-04 17:52:53.594,DEBUG,http-bio-8080-exec-4,com.zaxxer.hikari.pool.PoolElf:259,resetConnectionState,75680971-fff7-49a8-96c8-db503cf99b6e,nothing - Reset (com.mysql.jdbc.JDBC4Connection@60660841) on connection {}

```

thanks,
Krishna

**Comment by brettwooldridge** [comment]
You might try setting the [MySQL properties](http://dev.mysql.com/doc/connector-j/en/connector-j-reference-configuration-properties.html) ``readOnlyPropagatesToServer=false``, ``useLocalSessionState =true``, and ``useLocalTransactionState=true``.

You might investigate ``elideSetAutoCommits=true``, but I think that ``useLocalSessionState=true`` should cover that.

Of course, those calls from Hibernate are still going to occur, but hopefully they won't involve any roundtrips to the DB.

**Comment by kpadmasola** [comment]
Brett,

I added `useLocalSessionState =true`, and `useLocalTransactionState=true`. When I added `readOnlyPropagatesToServer=false`, I got a `MethodNotFound` exception, so I removed it.

Still the `getConnection()` is taking ~50% of the response time under load. Anything else I should try?

thanks,
Krishna

**Comment by brettwooldridge** [comment]
Check your driver version and that MySQL page of properties I provided a link to.

**Comment by kpadmasola** [comment]
Hi Brett,

I upgraded to the latest driver and set the properties suggested by you, but there is no improvement. Here's the relevant section from a new relic profile snapshot which shows connection acquisition taking about 9% for one db transaction.  Does this provide a clue to where the bottleneck is and how it can be avoided?

![hikari-get-connection](https://cloud.githubusercontent.com/assets/1274758/9130982/eb3ab416-3d04-11e5-8165-41b5fdc5f61d.PNG)

thanks,
Krishna

**Comment by nitincchauhan** [comment]
Curious ! is 'connection test query' set ? what are min Idle, max connection, connection & validation timeout values ?

**Comment by brettwooldridge** [comment]
@kpadmasola At this point I am 99.9% convinced that the issue is not the pool.  I suggest dropping in another pool, like Tomcat DBCP (not Apache DBCP) or Vibur, and seeing if you get similar results.

**Comment by kpadmasola** [comment]
Brett,

I replaced the pool with Vibur, and like you said the issue does not seem to be pool dependent. The ViburDataSource.getConnection() is also consuming similar amount of time.

I'm looking into our application code for clues, meanwhile please share if yiou have any ideas where to start digging.

thanks,
Krishna

**Comment by brettwooldridge** [comment]
@kpadmasola I can only recommend that you start by looking at the MySQL side.  You need to get deep insight into where time is being spent *within* MySQL as it slows down -- for example, in lock contention, cache misses, etc.

Then figure out if there is something you can to change at the application-layer to remediate, or if there is something you can do in terms of MySQL tuning.  I have no doubt is there is a combination of both that will *improve* performance.

The question you also need to answer is what is the maximum performance that MySQL on that given hardware and your given query/schema mix can provide?  Pushing load past that peak will only degrade performance.  If you need load beyond that, you will have to look at horizontal scaling and/or middle-tier caching (memcached, redis, etc.).

All I can advise is to roll-up your sleeves.  First, read everything you can find about monitoring/profiling MySQL and understanding what all the metrics mean.  Second, read everything you can about tuning MySQL to address the issues you find (using profiling to measure the change).

**Comment by kpadmasola** [comment]
Hi Brett,

Just wanted to update you that I found the issue in the application couple of days ago. It is not related to HikariCP.

I modified the locally build HikariCP jar by adding additional debug statements to print out details of `active`, `idle`, and `total` connections in the pool, and also `waitingThreads`, whenever `getConnection` takes longer than a millisecond. With this, I ran the load test and the resulting output clearly identified that one of the pools (we are using multiple databases, each with its own pool) was having very few total connections configured, due to which `getConnection` requests were waiting on the pool.

I corrected the configuration of that pool, and now `getConnection` is no longer a bottleneck.

thanks for your help,
Krishna.

**Comment by brettwooldridge** [comment]
Thanks, I really appreciate the update!  So often when users resolve their problem, they never come back to let us know what the solution was.  Having that information might help future users observing similar symptoms.

**Comment by vking34** [comment]
@kpadmasola May I have a question? What is the configuration of pool exactly?

**Comment by kpadmasola** [comment]
@vking34 I am sorry, I cannot recall now, as this thread is from 2015. At the time I was working in a different company.
