### ISSUE TITLE
video on wiki is private

### ISSUE THREAD

**Issue by levinotik** [brettwooldridge/HikariCP#353]
the video here is private https://github.com/brettwooldridge/HikariCP/wiki/About-Pool-Sizing Is there another link that can replace what's currently there?

**Comment by brettwooldridge** [comment]
For some reason Oracle decided to remove it, but this video is nearly identical in content.

https://www.youtube.com/watch?v=XzN8Rp6glEo&list=PLKCk3OyNwIzvwEXdaubc6PQXwnQOAE9h2&index=17
