### ISSUE TITLE
Hikari might not recover from state "Unusual system clock change detected"

### ISSUE THREAD

**Issue by jnehlmeier** [brettwooldridge/HikariCP#354]
The Housekeeper checks  for unusual system clock changes. If such a change has been detected the `previous` variable is not updated because of the `return` statement. It could happen that Hikari does not recover from this state because the value `previous` has become too old. 

Currently we have a development VM which evicts connections every 30 seconds.

```java
final long now = clockSource.currentTime();
final long idleTimeout = config.getIdleTimeout();

// Detect retrograde time as well as forward leaps of unacceptable duration
if (now < previous || now > clockSource.plusMillis(previous, (2 * HOUSEKEEPING_PERIOD_MS))) {
      LOGGER.warn("{} - Unusual system clock change detected, soft-evicting connections from pool.", poolName);
      softEvictConnections();
      fillPool();
      return;
}

previous = now;
```

**Comment by brettwooldridge** [comment]
Nice catch.
