### ISSUE TITLE
Zipkin instrumentation

### ISSUE THREAD

**Issue by eirslett** [brettwooldridge/HikariCP#356]
We use the Tomcat JDBC pool today, and have an interceptor that instruments queries with [Zipkin tracing](https://github.com/openzipkin/zipkin). Moving to HikariCP would mean we need some way of injecting a hook to execute custom code before/after a query is executed. We log start time, end time and the SQL query itself.
Is that possible to do in HikariCP, with a custom hook?

**Comment by brettwooldridge** [comment]
You might want to read [this thread](https://groups.google.com/forum/#!searchin/hikari-cp/customizer/hikari-cp/9n-N5W0FIOI/642HGaP9jd8J).

With context leading up to [this post](https://groups.google.com/d/msg/hikari-cp/9n-N5W0FIOI/2pDiRaVtYFkJ), which is expresses more succintly in code [here](https://gist.github.com/brettwooldridge/dfd21934416fc2a3c865).

**Comment by eirslett** [comment]
Thanks for the hint! (Sorry for the delay, I have been away for a while)
I tried your approach, but while it's simple to proxy a DataSource (since it's at the "entry level" of the JDBC API) it's quite involved to proxy a statement's execute method; one must proxy the whole JDBC API, which means lots of boilerplate code.
It also has a performance impact, since Hikari already has proxies (using Javassist) and the data source would then be proxied twice.
Could we do any tricks with Javassist/ProxyFactory, or the proxies Hikari provides, so that it's possible (optionally) to inject a wrapper method?

**Comment by patric-r** [comment]
I agree with eirslett, I would also appreciate if HikariCP would expose some kind of basic hook APIs to minimize boilerplate in production. On the other hand, for development, Brett's suggestion using some kind of "hook providing jdbc driver wrapper" (is there already such an open-source project?" would also suffice.

**Comment by brettwooldridge** [comment]
@eirslett It is not difficult to proxy even Statements without requiring boilerplate.

I created this :gift:  just for you:

https://gist.github.com/brettwooldridge/7564827e45d67e1dc8dd

**Comment by eirslett** [comment]
Thanks! I'll add Zipkin support for HikariCP in return :beers:

**Comment by brettwooldridge** [comment]
@eirslett Cheers. :beers:  I added a [small addendum](https://gist.github.com/brettwooldridge/7564827e45d67e1dc8dd#gistcomment-1566596) to the gist.

**Comment by delitescere** [comment]
G'day! Did anything come of this?

**Comment by eirslett** [comment]
I think it landed in Brave https://github.com/openzipkin/brave but I'm not 100 % sure... it's a long time ago now, 2 years... really long time ago.

**Comment by delitescere** [comment]
I see there is https://github.com/openzipkin/brave/tree/master/instrumentation/p6spy but that's indirect given HikariCP already wraps the datasource. Maybe it's enough. Cheers!
