### ISSUE TITLE
Database change in runtime

### ISSUE THREAD

**Issue by lordofthejars** [brettwooldridge/HikariCP#357]
Hi, I don't know if you know about Vault. Vault is a new OOS from Hashicorp for managing secrets. One of the great additions in Vault is that you can create users and passwords dynamically and make them expirable. So after some time you need to recreate a new one. You can read here https://www.vaultproject.io/docs/secrets/mysql/index.html

And just because login and password is generated automatically, there is one problem. In my understandings the authentication occurs at start of the connection pool, so any change that occurs on database side regarding credentials it will not take effect on connection pool side. 

Of course this is something that we must deal on Java part outside connection pool, but some facilities will be much appreciated. For example if we could call a method that in a controlled way (I mean that current running connections are not closed) it can reauthenticate all connections to the new credentials.

WDYT? Any strategy to follow for supporting this use case?

Thank you very much.
Alex.

**Comment by brettwooldridge** [comment]
The ``dev`` branch [contains a change](https://github.com/brettwooldridge/HikariCP/commit/a4d1156d08dd89f4ea14d258b3b15b84b5880dac) to allow the modification of username/password at runtime through the ``HikariConfigMXBean``.

**Comment by lordofthejars** [comment]
Nice :) Last question it says that Changing this at runtime will apply to new connections only. So how we can force to create new connections right after the new password is set?

**Comment by brettwooldridge** [comment]
Using the ``HikariPoolMXBean`` you can call ``softEvictConnections()``, that will evict all idle connections from the pool, and will evict in-use connections as soon as they return to the pool.

**Comment by siepkes** [comment]
Found this thread via Google. For the record AFAIK passwords are only used during authentication with PostgreSQL and changing a password of a user does not invalidate the existing connections. So I don't think there is a reason to re-authenticate connections (idle or active).
