### ISSUE TITLE
forcing connections to die after a connection timeout

### ISSUE THREAD

**Issue by elennick** [brettwooldridge/HikariCP#358]
Brett,

We are running a Play 2.4 app that utilizes HikariCP. One of the mechanisms of our production environment is a db failover where if our primary database goes down, a secondary read-only database is promoted to the master position and then made both read and write available. A side effect of this is that sometimes what was previously the primary database comes back up very quickly (or it's connection becomes available again) and it gets changed over to be the new secondary database and made readonly. The way that this is seamless for our application is that we have a single dns entry that gets updated to the IP of the new master database when this failover situation happens.

Our problem right now is that any existing connections in the pool hang onto the old db IP that they had resolved our dns entry at the time of the connections creation. This means that if the primary db goes down and then comes back up again as a readonly secondary database quickly (within a minute or two) then the connections in the pool recover and keep hitting it.

What we WANT is for the connections to die off quickly in a situation where they fail to connect after retrying so that even if the database they were connecting to recovers quickly, they will still die out and allow new connections that can resolve to the new IP to be created. I've spent some time trying to figure out a reasonable configuration that will indicate this without any success. Do you have any suggestions/advice on what sort of configuration would make it so the hikari pool would behave this way?

**Comment by brettwooldridge** [comment]
It's easy, call softEvictConnections() through the JMX bean.  Better actually would be to suspend the pool, evict, and then resume.
