### ISSUE TITLE
Any possibility of seeing a java-6/7 port for v 2.4.0 

### ISSUE THREAD

**Issue by ramith** [brettwooldridge/HikariCP#364]
Hi Brett, 
 $subject. I only see 2.4.0 for java 8. 
- Ramith

**Comment by brettwooldridge** [comment]
The 2.4.0 JAR supports both Java 7 and Java 8.  Java 6 has entered maintenance mode and will continue to receive bug fixes and releases from the 2.3.x branch.

**Comment by ramith** [comment]
Excellent ! thanks for the info.
