### ISSUE TITLE
I happened an error when i run the test case 

### ISSUE THREAD

**Issue by xingyixun** [brettwooldridge/HikariCP#365]
I clone the master branch code from github,and run  JdbcDriverTest( I have add the mysql-connector-java-5.1.35.jar in my classpath), and I config the right url,user,password and JdbcUrl ,just like this

![image](https://cloud.githubusercontent.com/assets/5221570/9052373/71951240-3a99-11e5-95ea-0a957fe39acc.png)
the result is this 
![image](https://cloud.githubusercontent.com/assets/5221570/9052388/89f5a6e2-3a99-11e5-85f8-d65866bc2465.png)
but the junit said that 
![image](https://cloud.githubusercontent.com/assets/5221570/9052402/a19eb324-3a99-11e5-8fde-5caa49f17b31.png)
Did I config the run test catse

**Comment by brettwooldridge** [comment]
Make sure the MySQL jar is in the classpath, and enable debug logging.

**Comment by xingyixun** [comment]
I debug the code ,and found that it stepped in HikariPool.java  193 line 
![image](https://cloud.githubusercontent.com/assets/5221570/9056467/bb29f71e-3ac5-11e5-8d13-1a834c157107.png)

and it returned ProxyFactory.getProxyConnection(bagEntry, leakTask.start(bagEntry), now);
but I found that ProxyFactory.getProxyConnection return null

what else should I do,thank you

**Comment by brettwooldridge** [comment]
Ah, I forgot you are running in eclipse.  The command line build generates proxy classes into the target/classes directory.  Either in the eclipse launch configuration's classpath for the junit test, or the project classpath, you need to add that directory.

**Comment by xingyixun** [comment]
![image](https://cloud.githubusercontent.com/assets/5221570/9058583/daa1d940-3ad4-11e5-933f-6779e65e9b21.png)
my project build path just look like this, should I include the target folder in it ? I do not understand how to fix it,and which tool or ide do you usually use to develop? Please tell me ,thanks so much

**Comment by xingyixun** [comment]
what I just need to do is add target to my build path,just like this ?
![image](https://cloud.githubusercontent.com/assets/5221570/9062045/58236984-3af2-11e5-842c-579237cc7517.png)
I really want to contribute to HikariCP,thank you for your suggestion, and waiting for your reply

**Comment by brettwooldridge** [comment]
You can either add it on the Libraries tab (as a folder: target/classes), or add it to the classpath of the Launch Configuration Dialog for the junit test.

**Comment by xingyixun** [comment]
![image](https://cloud.githubusercontent.com/assets/5221570/9063905/6ff30574-3afc-11e5-966d-5f9102745812.png)
![image](https://cloud.githubusercontent.com/assets/5221570/9063986/e4490dd8-3afc-11e5-9c13-6818f467bad8.png)

I'd add it on the on the Libraries tab and the classpath of the Launch Configuration Dialog for the junit test ,but it did not work

**Comment by brettwooldridge** [comment]
You *will* have to run the maven command line build at least once to generate the proxy classes:

mvn package

That last screenshot looks correct (just like mine).  Except you will need to add the MySQL Connector/J jar to the Launch Configuration classpath as well.

**Comment by xingyixun** [comment]
thank you so much . It worked
