### ISSUE TITLE
HikariCP 2.4.0 HikariDataSource.getConnection(string, string) is not supported now

### ISSUE THREAD

**Issue by Yaro77** [brettwooldridge/HikariCP#367]
Spring's (version 4.0.2) UserCredentialsDataSourceAdapter fails to getConnection(username, password) now, but works with HikariCP 2.2.5

**Comment by brettwooldridge** [comment]
Support for this method was removed in 2.4.0.  You can read the drama here #231.

**Comment by nevot** [comment]
So , how can we pass user login credentials now ?
