### ISSUE TITLE
https://github.com/brettwooldridge/HikariCP/wiki/Hibernate4  wiki content error

### ISSUE THREAD

**Issue by chilly** [brettwooldridge/HikariCP#368]
when I follow with https://github.com/brettwooldridge/HikariCP/wiki/Hibernate4:
hibernate.connection.provider_class=com.zaxxer.hikari.hibernate.HikariConnectionProvider
hibernate.hikari.minimumPoolSize=20
hibernate.hikari.maximumPoolSize=100
hibernate.hikari.idleTimeout=30000
hibernate.hikari.dataSourceClassName=com.mysql.jdbc.jdbc2.optional.MysqlDataSource
hibernate.hikari.dataSource.url=jdbc:mysql://localhost/database
hibernate.hikari.dataSource.user=bart
hibernate.hikari.dataSource.password=51mp50n

here : 
hibernate.hikari.minimumPoolSize=20
there is "no method setMinimumPoolSize"  exception will throw.
remove it will success. 

change the wiki content please.

**Comment by brettwooldridge** [comment]
Fixed.
