### ISSUE TITLE
Query: ConcurrentBag.borrow is the top CPU consumer. is this normal?

### ISSUE THREAD

**Issue by mmrath** [brettwooldridge/HikariCP#377]
I was profiling an internal application and found the following. Is this usual?

![image](https://cloud.githubusercontent.com/assets/115767/9160839/5bebf700-3f81-11e5-8ce0-1a8d5b3f2ec9.png)

**Comment by mmrath** [comment]
This probably is only happening when I profile. Also there are few other exceptions in the logs. So I am happy for it to be closed. I can raise another issue in case I confirm this.

**Comment by chrisvest** [comment]
Profile with Java Mission Control (`jmc` on the command line) if you are worried about the profiler overhead skewing your results.

**Comment by brettwooldridge** [comment]
@mmrath @chrisvest I have seen many weird interactions between profilers and Javassist, as they both want to weave bytecode into methods.  In HikariCP 2.4.0 these issues should be gone, because Javassist is not longer a runtime requirement.
