### ISSUE TITLE
expose houseKeepingExecutorService for sharing

### ISSUE THREAD

**Issue by jaredstehler** [brettwooldridge/HikariCP#380]
Hikari 2.4.0 allows pools to share house keeping threadpools, which is great, but there's no way to actually create one for sharing, unless I'm missing something? And it's not really possible to create one which mimics what the default one does, since it uses a private task:

```
      if (config.getScheduledExecutorService() == null) {
         ThreadFactory threadFactory = config.getThreadFactory() != null ? config.getThreadFactory() : new DefaultThreadFactory("Hikari housekeeper (pool " + poolName + ")", true);
         this.houseKeepingExecutorService = new ScheduledThreadPoolExecutor(1, threadFactory, new ThreadPoolExecutor.DiscardPolicy());
         this.houseKeepingExecutorService.scheduleAtFixedRate(new HouseKeeper(), HOUSEKEEPING_PERIOD_MS, HOUSEKEEPING_PERIOD_MS, TimeUnit.MILLISECONDS);
```

**Comment by brettwooldridge** [comment]
Unless I'm overlooking somethiing, if you set the scheduled executor service on the config via setScheduledExecutorService(), it will be picked up here:

https://github.com/brettwooldridge/HikariCP/blob/dev/src/main/java/com/zaxxer/hikari/pool/HikariPool.java#L132

**Comment by jaredstehler** [comment]
right, but I can't actually create an executor service to be used here, since the housekeeper is private, etc.

**Comment by brettwooldridge** [comment]
Nvm.  I see it.

**Comment by brettwooldridge** [comment]
This line:
```java
this.houseKeepingExecutorService.scheduleAtFixedRate(new HouseKeeper(), HOUSEKEEPING_PERIOD_MS, HOUSEKEEPING_PERIOD_MS, TimeUnit.MILLISECONDS);
```
needs to come after the else.
