### ISSUE TITLE
Timeout after 20005ms of waiting for a connection

### ISSUE THREAD

**Issue by richfwebb** [brettwooldridge/HikariCP#381]
My project has been working well, but recently I changed the queueSize config variable to -1 (unlimited) to resolve a previous error, and I upgraded to java8. I am not sure why I am getting this timeout error recently, as it did not appear to be an immediate consequence of the changes I made.  Sometimes the timeout error resolves itself if I restart SBT.

Please let me know any further information I can provide for solving this issue.

My Configuration:

```
default_db {
  url = "jdbc:mysql://"${MYHOST}"/myproj"
  user = ...
  password = ...
  queueSize = -1
  numThreads = 16
  connectionPool = HikariCP
  connectionTimeout = 20000
  maxConnections = 40
}
```

```
"err":{"message":"Timeout after 20005ms of waiting for a connection.","stackTrace":[{"file":"BaseHikariPool.java","line":228,"className":"com.zaxxer.hikari.pool.BaseHikariPool","method":"getConnection"},{"file":"BaseHikariPool.java","line":183,"className":"com.zaxxer.hikari.pool.BaseHikariPool","method":"getConnection"},{"file":"HikariDataSource.java","line":91,"className":"com.zaxxer.hikari.HikariDataSource","method":"getConnection"},{"file":"JdbcDataSource.scala","line":131,"className":"scala.slick.jdbc.HikariCPJdbcDataSource","method":"createConnection"},{"file":"JdbcBackend.scala","line":362,"className":"scala.slick.jdbc.JdbcBackend$BaseSession","method":"conn$lzycompute"},{"file":"JdbcBackend.scala","line":362,"className":"scala.slick.jdbc.JdbcBackend$BaseSession","method":"conn"},{"file":"JdbcBackend.scala","line":241,"className":"scala.slick.jdbc.JdbcBackend$SessionDef$class","method":"prepareStatement"},{"file":"JdbcBackend.scala","line":354,"className":"scala.slick.jdbc.JdbcBackend$BaseSession","method":"prepareStatement"},{"file":"StatementInvoker.scala","line":32,"className":"scala.slick.jdbc.StatementInvoker","method":"results"},{"file":"StatementInvoker.scala","line":22,"className":"scala.slick.jdbc.StatementInvoker","method":"iteratorTo"},{"file":"Invoker.scala","line":15,"className":"scala.slick.jdbc.Invoker$class","method":"iterator"},{"file":"StatementInvoker.scala","line":16,"className":"scala.slick.jdbc.StatementInvoker","method":"iterator"},{"file":"Invoker.scala","line":57,"className":"scala.slick.jdbc.Invoker$class","method":"foreach"},{"file":"StatementInvoker.scala","line":16,"className":"scala.slick.jdbc.StatementInvoker","method":"foreach"},{"file":"JdbcActionComponent.scala","line":109,"className":"scala.slick.driver.JdbcActionComponent$StreamingResultAction","method":"run"},{"file":"DatabaseComponent.scala","line":193,"className":"scala.slick.backend.DatabaseComponent$DatabaseDef$$anon$2","method":"liftedTree1$1"},{"file":"DatabaseComponent.scala","line":193,"className":"scala.slick.backend.DatabaseComponent$DatabaseDef$$anon$2","method":"run"},{"file":"ThreadPoolExecutor.java","line":1142,"className":"java.util.concurrent.ThreadPoolExecutor","method":"runWorker"},{"file":"ThreadPoolExecutor.java","line":617,"className":"java.util.concurrent.ThreadPoolExecutor$Worker","method":"run"},{"file":"Thread.java","line":745,"className":"java.lang.Thread","method":"run"}]},"status":200}
```

**Comment by jnehlmeier** [comment]
Usually it means that maxConnections has been reached and no one returned a connection to the pool within 20 seconds. Thus the pool can not hand out a connection within 20 seconds and the exception is thrown. Its either a connection leak (enable leak detection in Hikari) or you simply throw too much work at your pool / database.

To understand what is going on in your app you have to collect metrics and analyze them. Maybe changing queueSize had more consequences than you thought. But you can only know that if you have metrics.

**Comment by richfwebb** [comment]
After more inspection, the connections continue to increase and it appears they are not being closed properly. I will close the issue.

**Comment by richfwebb** [comment]
Is it better practice to explicitly call db.close each time you instantiate a db variable, or would it be equally correct to set an idleTimeout in the config (with idleTimeout < connectionTimeout, so that the threads are returned or removed from the pool, before connectionTimeout throws an error). Is that correct?

**Comment by jnehlmeier** [comment]
You **must** call Connection.close(). Your "idleTimeout trick" would not work at all, because connections that you have retrieved from the pool/datasource are considered active and not idle. They will only be considered idle again if you call connection.close(). So if you never call it then you end up with 40 active connections, 0 idle connections and finally you get the exception above.

**Comment by richfwebb** [comment]
Thanks!
