### ISSUE TITLE
HikariConfig.minIdle, validate and HikariPool are subtly coupled

### ISSUE THREAD

**Issue by bturner** [brettwooldridge/HikariCP#382]
The default for [`HikariConfig.minIdle`](https://github.com/brettwooldridge/HikariCP/blob/dev/src/main/java/com/zaxxer/hikari/HikariConfig.java#L109) is -1, which looks like it's intended to mean "whatever `maxPoolSize` is" based on the `validateNumerics()` code.

Unfortunately, if one writes what I thought was pretty obvious code, the resulting pool is unusable:
```java
HikariConfig config = new HikariConfig();
config.setDriverClassName("org.h2.Driver");
config.setJdbcUrl("jdbc:h2:mem:example");
config.setPassword("secret");
config.setUser("example");

HikariPool pool = new HikariPool(config);
```

The problem here is that I didn't call `config.validate()`, and the `HikariPool` constructor doesn't call it either. That means the -1 default for `minIdle` is still the value in place, and the following code in [`HikariPool.addBagItem`](https://github.com/brettwooldridge/HikariCP/blob/dev/src/main/java/com/zaxxer/hikari/pool/HikariPool.java#L365) doesn't handle that:
```java
            final int minimumIdle = config.getMinimumIdle();
            final int maxPoolSize = config.getMaximumPoolSize();
            while (poolState == POOL_NORMAL && totalConnections.get() < maxPoolSize && getIdleConnections() <= minimumIdle && !addConnection()) {
               // If we got into the loop, addConnection() failed, so we sleep and retry
               quietlySleep(sleepBackoff);
               sleepBackoff = Math.min(connectionTimeout / 2, (long) ((double) sleepBackoff * 1.5));
            }
```

When this checks `&& getIdleConnections() <= minimumIdle`, even when there are _no idle connections_, 0 is not less than or equal to -1. As a result, the pool never adds any connections and all attempts to get one timeout and fail.

Except that it's even more subtle than that. Since I didn't set `isInitializationFailFast` to `false`, when the `HikariPool` constructor calls `initializeConnections` it will add a single connection. Since `config.getMinimumIdle()` isn't 0 (it's -1), that connection is left open. That means the pool has a single connection, but it will never grow. Since that one connection is there, as long as nothing tries to run concurrently, the pool appears to work. But as soon as there is a need for two connections at once, things start to fail.

I'm not sure what the "fix" here is, given that, strictly speaking, nothing in the above is "broken". The behavior is very subtle, though, and I don't see anything in the documentation that says I have to call `validate()` before I construct a pool. If anything, I would expect the _pool_ to call validate, rather than it relying on consumers to do it.

**Comment by brettwooldridge** [comment]
``HikariPool`` was never meant to be constructed by users.  The correct usage is creating a ``HikariConfig`` and passing that to a ``HikariDataSource``, or creating a ``HikariDataSource`` (which extends ``HikariConfig``) configuring it directly.

**Comment by bturner** [comment]
Unfortunately, the way `HikariDataSource` is designed prevents me from using it. Its API is so minimal as to make it impossible to get information I need. For example, when using `HikariDataSource` I can't even query for the number of open connections on the pool. I know that Hikari can publish that information via JMX, but it doesn't seem like I should have to go through that just to ask how many connections are open from inside the same process.

I just thought if the `HikariPool` constructor called `validate()` it would simplify `HikariDataSource` (because it wouldn't need that call in 2 codepaths), _and_ it would make using `HikariPool`, for those of us who need to, simpler.

**Comment by brettwooldridge** [comment]
It is unfortunate that three additional lines of code stands to prevent Atlassian from using HikariCP.

The statistics you are looking for are available programatically through both [JMX](https://github.com/brettwooldridge/HikariCP/wiki/MBean-(JMX)-Monitoring-and-Management) (the aforementioned three lines of code) and [Dropwizard Metrics](https://github.com/brettwooldridge/HikariCP/wiki/Dropwizard-Metrics).
