### ISSUE TITLE
Video in wiki page is broken - About Pool Sizing

### ISSUE THREAD

**Issue by rponte** [brettwooldridge/HikariCP#385]
Hi,

The video from "Oracle Real-World Performance group" in [About Pool Sizing](https://github.com/brettwooldridge/HikariCP/wiki/About-Pool-Sizing) wiki page is broken!

I tried to find this video on youtube inside of [Oracle Real-World Performance Video Series](https://www.youtube.com/playlist?list=PLKCk3OyNwIzvwEXdaubc6PQXwnQOAE9h2) but I couldn't. 

Could you fix the link?

**Comment by brettwooldridge** [comment]
Fixed.

**Comment by rponte** [comment]
thanks!

**Comment by nitincchauhan** [comment]
for me the new page throws '404 Not Found' for
http://www.tudou.com/programs/view/i-VI115gyik/

**Comment by brettwooldridge** [comment]
It just loaded for me.

**Comment by rponte** [comment]
It loaded for me too. But the streaming is very slow and japanese (or
chinese) is hard to understand.
On qua, 19 de ago de 2015 at 04:27 Brett Wooldridge <
notifications@github.com> wrote:

> It just loaded for me.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brettwooldridge/HikariCP/issues/385#issuecomment-132474617>
> .
>
-- 
Rafael Ponte
TriadWorks | Formação Java
http://cursos.triadworks.com.br

**Comment by brettwooldridge** [comment]
It is slow, and apparently Chinese.  For some reason Oracle took the original YouTube video down.  If anyone can find a version of the same video that streams well (and maybe isn't Chinese), I'd love to link to it.

**Comment by brettwooldridge** [comment]
@rponte @nitincchauhan I found a link to the video on DailyMotion... updated the wiki.

**Comment by nitincchauhan** [comment]
cool. it works :)
