### ISSUE TITLE
Impossible to pass connection specific properties

### ISSUE THREAD

**Issue by jammer76** [brettwooldridge/HikariCP#391]
On my particular Oracle CP on HikariCP (ds) theres no way to pass specific Connection parameters:

		HikariConfig conf = new HikariConfig("testCpConnection.properties");
		HikariDataSource ds = new HikariDataSource(conf);
		Properties pp = new Properties();
		pp.put("connectionProperties.defaultRowPrefetch", "10000");
		ds.setDataSourceProperties(pp);

with Orcle DataSource is possible to do this:

		OracleDataSource ds = new OracleDataSource();
		ds.setURL("jdbc:oracle:thin:@xxxxxxxxx");
		ds.setUser("user");
		ds.setPassword("password");

		Properties pp = new Properties();
		pp.put("defaultRowPrefetch", "10000");

		ds.setConnectionProperties(pp);

perhaps I'm wrong also because in some previous version was possible to implement an IConnectionCustomizer that isn't supported anymore.

Regards
    Antonio

**Comment by jnehlmeier** [comment]
I guess you can use 
```java
OracleDataSource oracleDs = new OracleDataSource();
Properties pp = new Properties();
pp.put("defaultRowPrefetch", "10000");
oracleDs.setConnectionProperties(pp);

HikariConfig conf = new HikariConfig("testCpConnection.properties");
conf.setDatasource(oracleDs);
HikariDataSource ds = new HikariDataSource(conf);
```
Then HikariCP should use the OracleDataSource for creating connections to fill the Hikari pool.

**Comment by brettwooldridge** [comment]
@jnehlmeier That is correct.

**Comment by jammer76** [comment]
Right, it works correctly, sorry for my mistake.

Thx a lot
   Antonio
