### ISSUE TITLE
Hibernate provider number connections bug

### ISSUE THREAD

**Issue by z0mb1ek** [brettwooldridge/HikariCP#392]
Hi. I use  org.hibernate:hibernate-hikaricp:4.3.11.Final and settings are:

    setProperty("hibernate.connection.provider_class", "org.hibernate.hikaricp.internal.HikariCPConnectionProvider");
    setProperty("hibernate.hikari.maximumPoolSize", 10);

But i see in postgresql that there is twice more connections - 20. Where can this bug be?

**Comment by z0mb1ek** [comment]
I check that hibernate create 2 pools

    Aug 21, 2015 7:02:43 PM org.hibernate.engine.jdbc.connections.internal.ConnectionProviderInitiator instantiateExplicitConnectionProvider
    INFO: HHH000130: Instantiating explicit connection provider: org.hibernate.hikaricp.internal.HikariCPConnectionProvider
    2015-08-21 19:02:43,705  INFO HikariDataSource - Hikari pool HikariPool-0 is starting.


    Aug 21, 2015 7:02:49 PM org.hibernate.engine.jdbc.connections.internal.ConnectionProviderInitiator instantiateExplicitConnectionProvider
    INFO: HHH000130: Instantiating explicit connection provider: org.hibernate.hikaricp.internal.HikariCPConnectionProvider
    2015-08-21 19:02:49,892  INFO HikariDataSource - Hikari pool HikariPool-1 is starting.

**Comment by brettwooldridge** [comment]
All I can say is this is definitely not a HikariCP bug. I recommend asking on stackoverflow.com.
