### ISSUE TITLE
Separate pools for reading and writing to SQL database

### ISSUE THREAD

**Issue by themoonraker13** [brettwooldridge/HikariCP#394]
I'm working on an spring-boot web application application using spring-boot-jpa (Spring Data JPA) to store and retrieve data in a relational database.
I have a brief idea about HikariCP and using it to manage multiple connection pools. But, I want to perform read operations (DQL) and write operations (DML) on the same database using separate connection pools respectively.

Is there a way to achieve the same??

**Comment by brettwooldridge** [comment]
This is primarily a Spring Data question.  HikariCP has not limitation that would prevent you from creating two pools in one application pointing to the same DB.  It's no different than many application servers connected to the same DB.  I suggesting asking on stackoverflow.com or over on the Spring Data forums.
