### ISSUE TITLE
Correct FAQ item on PostgreSQL's statement caching

### ISSUE THREAD

**Issue by vlsi** [brettwooldridge/HikariCP#397]
The following FAQ entry has invalid statement:
https://github.com/brettwooldridge/HikariCP/wiki/FAQ#q-how-to-i-properly-enable-preparedstatement-caching-for-postgresql

>The PostgreSQL JDBC driver from the PostgreSQL project does not support PreparedStatement caching

In fact official PostgreSQL driver does support prepared statement caching: https://jdbc.postgresql.org/documentation/changelog.html#version_9.4-1202

See preparedStatementCacheQueries and preparedStatementCacheSizeMiB parameters here: https://jdbc.postgresql.org/documentation/head/connect.html#connection-parameters

Please fix the wording to advice newer pgjdbc version or remove the item altogether.

**Comment by brettwooldridge** [comment]
Corrected.
