### ISSUE TITLE
Some connections throw an java.lang.AbstractMethodError when calling getSchema

### ISSUE THREAD

**Issue by plee-jda** [brettwooldridge/HikariCP#399]
I have seen this behavior using H2 and SQLServer.  The following code will throw a runtime exception.  I am using HikariCP 2.4.1, H2 1.4.182 and have tested it in java 7 and 8.

```java
public class Hikari {
    public static void main(String ... args) throws SQLException {
        HikariConfig config = new HikariConfig();
        config.setDataSourceClassName("org.h2.jdbcx.JdbcDataSource");
        config.addDataSourceProperty("URL", "jdbc:h2:~/test");
        HikariDataSource ds = new HikariDataSource(config);
        Connection c = ds.getConnection();
        c.getSchema();
    }
}
```

```
Exception in thread "main" java.lang.AbstractMethodError: org.h2.jdbc.JdbcConnection.getSchema()Ljava/lang/String;
	at com.zaxxer.hikari.proxy.HikariConnectionProxy.getSchema(HikariConnectionProxy.java)
	at Hikari.main(Hikari.java:14)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
```
I apologize for the inconvenience if this is some configuration issue.  It might have something to do with H2 being compiled against java 6 (getSchema is not apart of the Connection interface in 6).

**Comment by brettwooldridge** [comment]
If your driver is compiled against Java 6, you will have to try HikariCP-java6 v2.3.9.  Even then I'm not sure it will work.  If not we can treat this as a bug.

**Comment by plee-jda** [comment]
It didn't work against 2.3.9 either.  Since my runtime is Java 7 which has the newer Connection interface with `getSchema` everything compiles fine against either Hikari version.  

It really isn't too big of a hassle, currently I am just catching that exception and using null if the catch block is hit.

**Comment by brettwooldridge** [comment]
Ah, yes I see.  Yeah, nothing HikariCP can do about that.  We have to deal with [the same issue](https://github.com/brettwooldridge/HikariCP/blob/2.3.x/hikaricp/src/main/java/com/zaxxer/hikari/pool/HikariPool.java#L151) in places.

**Comment by plee-jda** [comment]
I understand that Hikari can't make it work at all.  Shouldn't  it never throw the AbstractMethodError ? If not is this at least documented somewhere?

**Comment by brettwooldridge** [comment]
@plee-jda You would get the same error running *without* a pool, against the plain H2 driver.

Your code compiles against the ``java.sql`` (``javax.sql``) interfaces provided by your SDK (Java 7), so *javac* is not going to give you a compile-time error.  HikariCP's ``ConnectionProxy`` is simply delegating to the real driver.

The real driver does not implement that method, and the therefore the JVM (not HikariCP) throws AbstractMethodError exception at runtime.  Again, even if you took HikariCP out of the middle between your application and the H2 driver, you would get the same exact exception.

**Comment by plee-jda** [comment]
Ah yeah that makes sense.  Thanks for the explaination.
