### ISSUE TITLE
UTF-8 character encoding

### ISSUE THREAD

**Issue by catalinfeier** [brettwooldridge/HikariCP#40]
I can't seem to be able to get data encoded in UTF-8 (cyrilic , arabic alphabets etc) from my MySQL database. Everything else works correctly and as expected.
Without HikariCP (no connection pooling) I used "useUnicode=true&characterEncoding=UTF-8" as a property for my connection and it worked.
With HikariCP i tried something similar for the configuration:
config.addDataSourceProperty("url", "jdbc:mysql://localhost:3306/db?useUnicode=true&characterEncoding=UTF-8");
I also tried using the following:
 config.addDataSourceProperty("characterEncoding",Charsets.UTF_8.name());
 config.addDataSourceProperty("useUnicode","true");
Neither worked, the cyrilic characters were shown as ???.
My MySQL version is 5.5.27, but like i said without using connection pooling the character were shown correctly.
Any suggestions/ideas?

**Comment by AyubOpen** [comment]
@brettwooldridge sorry for messaging on a closed thread, I am trying the same appoarch as you mentioned about config.add for utf-8, but I still see the issue of garbled characters. Code works if I use plain jdbc; below is my property file

//hikari.properties
driverClassName=oracle.jdbc.driver.OracleDriver
jdbcUrl=jdbc:oracle:thin:@localhost:1521/xe
maximumPoolSize=20
username=testdbapp
password=oracle
dataSource.cachePrepStmts=true 
dataSource.prepStmtCacheSize=250

@Configuration
public class AppConfig {

    @Bean(destroyMethod = "close")
    public DataSource dataSource() throws SQLException {
        HikariConfig config = new HikariConfig("/hikari.properties");
        config.addDataSourceProperty("characterEncoding","utf8"); //tried with UTF-8 as well
        config.addDataSourceProperty("useUnicode","true");
        HikariDataSource dataSource = new HikariDataSource(config);

        return dataSource;
    }
}

this is a spring boot application, please advise
