### ISSUE TITLE
PoolStats methods are protected - hard to build custom MetricTracker

### ISSUE THREAD

**Issue by brenuart** [brettwooldridge/HikariCP#400]
The introduction of the new `MetricsTrackerFactory` property seems to allow us to register custom implementation of `MetricsTracker` (other than the one provided for Codahale metrics).

Valuable metric information like total connections, idle connections, active connections, etc are made available through an instance of `PoolStats`. Unfortunately, the corresponding getter methods are all marked `protected` and are therefore not available to any MetricTracker implementation not in the Hikari packages...

Is it intended?
If so, how are we supposed to implement a custom metric tracker?

**Comment by brenuart** [comment]
Any thoughts on this? Maybe `PoolStats` is not intended to be used by external code...

**Comment by brettwooldridge** [comment]
@brenuart So far I think you are the one of the only ones using a custom MetricsTracker.  I wanted to give you a heads up that the ``MetricsTracker`` class is going to be @Deprecated and eventually removed and replaced by an ``IMetricsTracker``  interface.

**Comment by brenuart** [comment]
Ohh... Ok, thanks for the warning. As long as `IMetricsTracker` provides the same functionality I should be good.
Is that new interface already available? Do you want me to have a look before you release a new version?

**Comment by brettwooldridge** [comment]
Just committed.  Currently only applicable to Java 8.  The IMetricsTracker interface has the same signature as MetricsTracker and default methods.
