### ISSUE TITLE
Custom ThreadFactory from config does not allow for distinguishable thread names

### ISSUE THREAD

**Issue by brenuart** [brettwooldridge/HikariCP#402]
Hikari attempts to reuse its house keeping threads as much as it can. When used together with Logback, this sometimes leads to wrong/false MDC information (this is a well-known issue for most Logback users: Logbacks uses an `InheritableThreadLocal` to store the MDC information...)

As per Logback's documentation, to correct approach is to clear/setup the MDC prior to any task execution on a separate thread. This can be easily achieved in Hikari by setting a custom `ThreadFactory`. Threads are cached in multiple locations in HIkari, each pool having its own name - threads are therefore easily identifiable. However, since thread names are set by the factory, replacing the factory by a custom one leads to all threads having the same name (plus increment).

It would be nice if the call requesting a thread from the pool would set the thread name instead of letting the single factory do so. See what I mean?

**Comment by brettwooldridge** [comment]
Makes sense.

**Comment by brettwooldridge** [comment]
Actually, I'm not sure it makes sense.  By and large HikariCP uses Executors, and simply throws tasks into the queue, so it is not HikariCP that requests  thread creation, but rather the Executor based on its own internal logic.

And changing the thread name at the top of each task, which would potentially work around the issue,  sounds like a recipe for poor performance...

**Comment by brenuart** [comment]
Indeed.

If I register my own `ThreadFactory`, then all threads are created from a single place (where I could wrap the submitted runnable so as to properly configure loggacb's MDC). But then will all be named like "Hikari-[poolname]-[index]" - not a big issue though...

Currently, Hikari does create new threads from multiple place - there is no such concept of a single `ThreadFactory` by default.

In general, a better approach for my issue is to work at the task level, i.e. the `ExecutorService`: MDC is cleared/configured at every task execution. But I can live with the `ThreadFactory` approach ;-)

**Comment by brettwooldridge** [comment]
@brenuart What if HikariCP wrapped the user specified ``ThreadFactory``, delegated to it, and amended the thread name?
```java
public class DefaultThreadFactory implements ThreadFactory {
   ...
   public DefaultThreadFactory(ThreadFactory userFactory, String threadName) {
      this.userFactory = userFactory;
      this.threadName = threadName;
   }

   public Thread newThread(Runnable r) {
      Thread thread;
      if (userFactory != null) {
         thread = userFactory.newThread(r);
         thread.setName(thread.getName() + threadName);
      }
      else {
         thread = new Thread(r, threadName);
      }
      thread.setDaemon(daemon);
      return thread;
   }
```

**Comment by brenuart** [comment]
This could do the job, but I don't think the `ThreadFactory` is the right place to set the name.

If Hikari had used a single thread pool - threads would be named something like "Hikari-<seq>". The same thread could be reused for different things like connection closing, house keeping or else. The tread name wouldn't say anything about what the thread is currently doing.

The current approach is to have thread pools dedicated to well defined tasks - hence the thread name gives some more useful information. These pools are actually created by the `Executors` - it is up to them to ask for a new thread from the single factory and set its name to whatever is meaningful in their context. This is what you propose if you wrap the user supplied `ThreadFactory` for every `Executor`.

See what I mean?

In that context, I think you should simply override the thread's current name with anything Hikari finds appropriate (don't try to concatenate the current thread name with your desired value/prefix/suffix).


However, if you offer me to set my own custom ThreadFactory, I'm not sure I'll be glad to change the names I assigned... This may not be a very good "user" experience... I know this is the subject of my issue, but reading from your comments it doesn't seems to be a good idea anymore :-(

**Comment by brettwooldridge** [comment]
@brenuart Hehe.  I hesitate to go down the path of one well known framework, and introduce concepts like ``ThreadFactoryFactory``.  :grimacing:  Though in essence that would be one approach.  I just can't bring myself to do it without a really compelling use-case.

**Comment by brenuart** [comment]
Yeah.
So, leave the code asis for the moment. I can live with the current
approach. Maybe you will have another more interesting use case in the
future ;-)
