### ISSUE TITLE
Metrics: record time it takes to obtain a connection from the underlying datasource

### ISSUE THREAD

**Issue by brenuart** [brettwooldridge/HikariCP#404]
It would be nice if Hikari does record the time it takes to obtain a connection from the underlying datasource. This information could help to troubleshoot production issues and size the pool.

Most metrics reported by Hikari are related to the "user" side of the pool - but nothing is recorded for the "system" side (facing the underlying datasource).

It would also be nice to distinguish between failed and success attempts to acquire a connection from the underling datasource. Although this may look strange at first glance, we do have databases that sometimes make 30s to report a connection failure. With the current set of metrics, the only trace of such event is an increase in the "pool wait" metric - but no indication to tell it affects failures only.

**Comment by brettwooldridge** [comment]
@brenuart What would "distinguishing between failed and success attempts" look like?  You mean separate metrics?  Like how long successful attempts take, and how long failed attempts take?  Would these be exponential decay histrograms, N-minute sliding window histrograms, ... ?

**Comment by brettwooldridge** [comment]
Sounds reasonable.

**Comment by brettwooldridge** [comment]
Fixed in commit @1807776.
