### ISSUE TITLE
Consider logging failed attempts to obtain a connection in ERROR level

### ISSUE THREAD

**Issue by brenuart** [brettwooldridge/HikariCP#405]
Failed attempts to acquire a connection from the underlying datasource are currently logged at DEBUG level.

This information is vital to help troubleshoot connection issues in production environment. Setting HikariCP in DEBUG is far to verbose and is confusing for sysadmin. Hence the proposition to log connection issues in ERROR level.

**Comment by brettwooldridge** [comment]
We orginally were logging at error, but got complaints from users about the noise level.  One hurdle is that it is possible to start the pool when the database is in a known down condition (when ``initializationFailFast=false``.  In this configuration, HikariCP continues connection attempts, backing off to a maximum of 1.5 seconds, until it succeeds.  This creates a lot of noise when logging at error (or even info) that a lot of users don't want to see.

**Comment by brenuart** [comment]
I understand your concerns, but when connection failures happen at runtime - how can a sysadmin diagnose them? I mean, HikariCP just silently ignore the exceptions when attempting to acquire a connection from the underlying datasource and the application only gets a "PoolTimeoutException" without any further information...

If not appropriate to log every time Hikari fails to acquire a connection, may be we could remember the last received exception and attach it to the "PoolTimeoutException" sent back to the application? Applications could then log it themselves according to their needs...

PS: issue is closed, don't know how to reopen it, hope you will get the message and consider it ;-)

**Comment by brenuart** [comment]
Forget what I just said: the request feature is already implemented!

An `SQLTransientConnectionException` exception is thrown with the cause set to the last exception received from the underlying datasource. Didn't see it - our framework was ignoring the root cause :-(

Sorry for the noise - and thanks for your answers.

**Comment by brettwooldridge** [comment]
We're good like that ... we read users minds and implement before they ask. :grinning:
