### ISSUE TITLE
Recent connections are not validated (ALIVE_BYPASS_WINDOW)

### ISSUE THREAD

**Issue by brenuart** [brettwooldridge/HikariCP#406]
Hikari does validate pooled connections only if they are older than a given threshold. The default threshold is 1000ms, can be set via the `com.zaxxer.hikari.aliveBypassWindow` system property.

In effect, Hikari assumes that a just created connection is alive and does not need to be validated. Although this may seem a valid optimisation, it becomes confusing when the pool is configured with an _incorrect validation query_. In that case, the application will always obtain a brand new connection from the pool - already pooled connections older than the threshold are eligible for validation and will be (silently) discarded. The application is working but performs as if it had no pool at all (except for the limit on concurrent connections).

The worst is there is no way for sysadmin to detect and troubleshoot the issue (application is working and nothing in the logs) - not even with the metrics.

We decided to turn off this feature by setting the `com.zaxxer.hikari.aliveBypassWindow` property to '-1'. Changing this value through system properties is not very convenient. It would be more convenient if that property would be configurable through the `HikariConfig` just like the other. It would also allows for different settings per pool.

What's your opinion?

**Comment by brettwooldridge** [comment]
@brenuart Wow, very interesting failure mode!  I love it when users find issues like this.

Some background...

HikariCP tries to strike a balance between performance and reliability. One of the concessions to performance is the alive test bypass window. It was designed under the assumption that if a connection was known valid within the past few hundred milliseconds, it is still valid.  Forcing validation on every call to *getConnection()* is sure to be a performance killer.

The only reason it is configurable at all is for use by various unit tests.  One of HikariCP's basic tenants is that we won't provide a means by which the end user can construct an unreliable configuration.  Thus, the configurability of the bypass window is not exposed, lest a user set it to something like 30 minutes (or MAX_INTEGER), effectively disabling validation.

Luckily, there is a better solution to the issue of an invalid validation query. By default, the *initializationFailFast* setting is true. Which means the pool will fail to start and throw an exception if the initial connection to the database fails. If we add an execution of the validation query to that test, the user will be notified immediately.

**Comment by brenuart** [comment]
Glad you like it ;-)

Setting `initializationFailFast` to true is not an option as it requires the database to be accessible at startup - which is a requirement we'd like to avoid.

> It was designed under the assumption that if a connection was known valid within the past few hundred milliseconds, it is still valid.

The problem here is that a newly created connection is immediately _assumed_ valid once created without requiring the execution of the validation query. I would expect it to be validated at least once before being returned to the application. 

Suppose you configure your pool with _maximumPoolSize=minimumIdle=10_ connections and an invalid validation query and _failFast=false_. 10 connections are quickly created to satisfy the `minimumIdle` configuration property. Wait for at least the pre-configured bypass window and ask for a connection. The pool selects one of the idle connections and validate it. Since the validation query is incorrect, the validation fails and the connection is removed from the pool. The process iterates until all 10 idle connections are tried. The pool is now empty and a new connection is created. Since a newly created connection is assumed valid, no validation occurs for it and it is returned to the application. This wouldn't be the case if the connection ran at least once in its life through the validation process.

See what I mean?
According to me, assuming a connection is valid because successfully created is wrong - it has to go at least once through the validation process. This would solve the issue.

**Comment by brettwooldridge** [comment]
@brenuart Ok, I can see that.  I'll make the change such that, if a validation query is defined, it will be tried executed after connection creation.

As an optimization, I believe it safe to assume that successful execution of the query is proof enough that the query is valid, and as a result the "validation" of the "validation query" need only occur once (the first time a connection is created).

Because the pool unconditionally configures auto-commit and read-only state, as well as querying and possibly configuring transaction state on *new* connections, we are actually sure, even in the absence of query execution, that the connection is alive.  The only thing we are *not sure* of is whether the query is valid until it is executed once.

**Comment by brettwooldridge** [comment]
HikariCP 2.4.2 has been released, containing a fix for this issue.
