### ISSUE TITLE
HikariCP keeps all connection open, and holds it.

### ISSUE THREAD

**Issue by ameyjadiye** [brettwooldridge/HikariCP#407]
Hi,

I'm using hikariCP from the long time, and pretty much knows its behavioral advantages. i know that CP fills connections on startup and periodically refresh the CP by retiring old connection and filling with new one.

recently i used it with sybase, and the connection provided by servers are quite low, as the CP start it fills the connection directly to *maximumPoolSize* and hold it no matter what its getting used by application or not. my application is getting used only for 2 hours a day with huge requests but it must be keep running as few request comes any time. can there be a auto scaling feature or kinda timeout like if pool is not getting use for 10 min it will lower number of connection from the pool and if request keeps on coming it will fill it up to the max?

**Comment by jnehlmeier** [comment]
You can set `minimumIdle` to a lower value than `maximumPoolSize` or you can even set it to zero. Combine that with a shorter `idleTimeout` and the pool will adjust itself based on the app usage.

**Comment by ameyjadiye** [comment]
Thanks @jnehlmeier ,but this is not a default behavior, default connections are always to max. cant it be at auto-scaling by default settings?

**Comment by jnehlmeier** [comment]
No, HikariCP prefers a fixed sized pool as default. 

If you want auto-scaling you need to configure HikariCP to your needs using the properties I mentioned above.

**Comment by brettwooldridge** [comment]
The default (target) for HikariCP is optimal performance under constant load. Users with periodic workloads or capacity constraints will need to tune accordingly.
