### ISSUE TITLE
java.sql.SQLException: Catalog can not be null when closing a connection with explicit catalog

### ISSUE THREAD

**Issue by danrah** [brettwooldridge/HikariCP#410]
This is the question that I have posted on SO and I feel that it might be a HIkariCP issue :)

I'm trying to use HikariCP in a java app to implement connection pooling to MySQL.

Because of a DB design flaw, the app uses different databases and I have to explicitly call connection.setCatalog() to change the database when needed.

When I try to close the connection that uses the default database (with no call to setCatalog() ) everything is fine and the connection returns back to the pool. But If this is a connection to another database (using setCatalog()) I get the following exception when I call close() method:

java.sql.SQLException: Catalog can not be null
    at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1074)
    at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:988)
    at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:974)
    at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919)
    at com.mysql.jdbc.ConnectionImpl.setCatalog(ConnectionImpl.java:5324)
    at com.zaxxer.hikari.pool.PoolElf.resetConnectionState(PoolElf.java:263)
    at com.zaxxer.hikari.pool.PoolBagEntry.resetConnectionState(PoolBagEntry.java:122)
    at com.zaxxer.hikari.proxy.ConnectionProxy.close(ConnectionProxy.java:193)
    at someapp.repository.MySqlRepository.closeConnection(MySqlRepository.java:198)...
Needless to say that I have checked if the catalog is null:

public void closeConnection() throws SQLException{
        System.out.println("trying to close with catalog:"+connection.getCatalog());

        if(connection!=null){

        //connection.setCatalog("defaultdb");
            connection.close();

        }
        this.connection=null;
    }
If I uncomment the the connection.setCatalog("defaultdb") to set the catalog back to the default, the problem still persists.

The only situation where everything is fine is when I don't use setCatalog() method at all.

Is this an issue with hikaricp when the catalog is explicitly set? Is there a way to close the connection and send it back to the pool?

**Comment by brettwooldridge** [comment]
@danrah You shouldn't need to do this at all.  Set the ``catalog`` property in the configuration.

**Comment by danrah** [comment]
and how to change the catalog at runtime?

**Comment by brettwooldridge** [comment]
Just as you would normally, call ``setCatalog()``.  No matter what you set
the catalog to, when you close the Connection HikariCP will automatically
reset the catalog to the default defined in the configuration.
