### ISSUE TITLE
Useless call to DriverDataSource.shutdown() when HikariDataSource.close() 

### ISSUE THREAD

**Issue by brenuart** [brettwooldridge/HikariCP#413]
`HikariDataSource.close()` makes a call to `DriverDataSource.shutdown()` whose body is empty (noop). `DriverDataSource` being a final class - there is no chance anyone except the Hikari maintainers extend this class or change the method implementation.

Conclusion: code would be cleaner and easier to maintain if that useless call to `DriverDataSource.shutdown()'  is removed.

**Comment by brettwooldridge** [comment]
@brenuart Already covered. [refactor](https://github.com/brettwooldridge/HikariCP/commit/1973c3005e12a8679109b7ffdacb3b3a00895669).  Don't start reviewing the refactor, its still like clay. :grinning:

**Comment by brenuart** [comment]
Sorry - wasn't aware of any refactoring work in progress :-(
Just wanted to share my findings...

**Comment by brettwooldridge** [comment]
@brenuart I appreciate it the reviews.
