### ISSUE TITLE
Understanding test connection

### ISSUE THREAD

**Issue by oogifu** [brettwooldridge/HikariCP#414]
Hello,
I am trying to understand how to use setConnectionTestQuery and setValidationTimeout
I am testing this behaviour against Apache Derby and I set a simple test query as select count(1) from mytable and setValidationTimeout to 5000
When I kill Derby - nothing happens. 
What is the right way to detect a connection issue. Can I register a callback somehow so that I can act on a connection doing down and back up for ex?
Thanks v much :-)

**Comment by brettwooldridge** [comment]
There is no callback to inform you of a connection issue.  Your best bet would be to configure a [Dropwizard Healthcheck](https://github.com/brettwooldridge/HikariCP/wiki/Dropwizard-HealthChecks) and poll that at whatever interval is convenient.
