### ISSUE TITLE
Make java.beans optional (or not used)

### ISSUE THREAD

**Issue by adriancole** [brettwooldridge/HikariCP#415]
Zipkin uses a base docker image that derives `FROM delitescere/java:8`

This is a JRE, not a JDK, specifically Zulu JRE compact3 profile. That profile does not include the `java.beans` package. It looks like this is implicitly used by `HikariConfig` when debug logging is enabled. Can it not? :)

```
query_1     | ERR [20150910-12:42:31.819] ThriftQueryService: Caused by java.lang.NoClassDefFoundError: java/beans/IntrospectionException
query_1     | ERR [20150910-12:42:31.819] ThriftQueryService:     at com.zaxxer.hikari.HikariConfig.logConfiguration(HikariConfig.java:827)
query_1     | ERR [20150910-12:42:31.819] ThriftQueryService:     at com.zaxxer.hikari.HikariConfig.validate(HikariConfig.java:782)
query_1     | ERR [20150910-12:42:31.819] ThriftQueryService:     at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:94)
--snip--
```

**Comment by brettwooldridge** [comment]
@adriancole I'll take a look.

**Comment by adriancole** [comment]
thanks tons!

**Comment by brettwooldridge** [comment]
@adriancole It's actually the [PropertyElf](https://github.com/brettwooldridge/HikariCP/blob/dev/src/main/java/com/zaxxer/hikari/util/PropertyElf.java) class that is using the ``java.beans`` package.  The usage is fairly light, and can be replaced by standard Java reflection with a small amount of work.  I'll try to get to it this weekend.

**Comment by brettwooldridge** [comment]
This is fixed in the dev branch.  HikariCP no longer depends on ``java.beans``, and performs all operations by direct reflection.

**Comment by adriancole** [comment]
great news. I'll lookout for a release, as I've some commits to revert!

**Comment by adriancole** [comment]
I noticed PropertyElf is still in the dev branch. Is it just no longer used?

https://github.com/brettwooldridge/HikariCP/blob/dev/src/main/java/com/zaxxer/hikari/util/PropertyElf.java

**Comment by adriancole** [comment]
any chance of a release soon? I'd love to use this.

**Comment by brettwooldridge** [comment]
HikariCP 2.4.2 has been released, containing a fix for this issue.

**Comment by adriancole** [comment]
Great!
