### ISSUE TITLE
Why does HikariCP throw java.lang.reflect.UndeclaredThrowableException?

### ISSUE THREAD

**Issue by patric-r** [brettwooldridge/HikariCP#416]
Hi,
this is more a question than a bug report:
Why does HikariCP wrap SQLException (which may originate from Statement execution for example) into the java.lang.reflect.UndeclaredThrowableException type?

When replacing other pools by HikariCP, this might cause additional integration effort, because some existing code might expect and catch SQLException (e.g. to check error codes), as defined in the java.sql java docs).
With HikariCP, these catch blocks are now always missed which potentially changes behavior.

**Comment by brettwooldridge** [comment]
Do you have a specific stacktrace?  Searching the code, I find no direct reference to ``UndeclaredThrowableException``, so I am curious where this is coming from.

**Comment by brettwooldridge** [comment]
Additionally, we do have [tests](https://github.com/brettwooldridge/HikariCP/blob/dev/src/test/java/com/zaxxer/hikari/ExceptionTest.java) which validate that ``SQLException`` is in fact thrown and caught.  I tend to believe that what you encountered is an edge case, as tens and thousands of users have run HikariCP over the past few years and I've never had such a report.

**Comment by patric-r** [comment]
Brett, thank you for your quick response.

After looking at the stacktrace, I realized that this exception is not originating from HikariCP at all.
It's coming from a DataSource wrapper, which is inspired by your gist snippet "MoreInterceptors.java",
so this question can be closed.

I'm sorry for wasting your time.
