### ISSUE TITLE
NPE in setLoginTimeout with 2.4.1 release

### ISSUE THREAD

**Issue by prakashgs** [brettwooldridge/HikariCP#417]
Hi,

I was using 2.3.7 and upgraded to 2.4.1 and ran into an NPE.
It appears there is a circular dependency ( not necessarily a bad thing ) in the HikariDataSource class.
Maybe some null checks are needed for the "pool" reference.

Here is the relevant trace:
Caused by: java.lang.NullPointerException
	at com.zaxxer.hikari.HikariDataSource.setLoginTimeout(HikariDataSource.java:131)
	at org.springframework.jdbc.datasource.DelegatingDataSource.setLoginTimeout(DelegatingDataSource.java:104)
	at com.zaxxer.hikari.pool.PoolElf.setLoginTimeout(PoolElf.java:504)
	at com.zaxxer.hikari.pool.PoolElf.initializeDataSource(PoolElf.java:161)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:113)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:96)

In 2.3.7, the HikariDataSource uses a map in the setLoginTimeout() and so does not encounter this problem. ( 2.3.7 implementation below ).

   public void setLoginTimeout(int seconds) throws SQLException
   {
      for (HikariPool hikariPool : multiPool.values()) {
         hikariPool.getDataSource().setLoginTimeout(seconds);
      }
   }

Thanks,
Prakash

**Comment by brettwooldridge** [comment]
... wait, what?  How is it that ``HikariDataSource`` is wrapping a ``DelegatingDataSource`` that itself wraps a ``HikariDataSource``?

**Comment by prakashgs** [comment]
Brett, I think you are right about this being a Spring config issue. I will investigate more. Will close this for now.

**Comment by danjee** [comment]
I got the same error with 2.4.1 and the following xml configuration:

```xml
<bean id="hikariConfig" class="com.zaxxer.hikari.HikariConfig">
		<property name="poolName" value="springHikariCP" />
		<property name="dataSourceClassName" value="com.zaxxer.hikari.HikariDataSource" />
		<property name="maximumPoolSize" value="2" />
		<property name="idleTimeout" value="600000" />
		<property name="connectionTimeout" value="20000" />
		<property name="dataSourceProperties">
			<props>
				<prop key="jdbcUrl">jdbc:oracle:thin:@vs1706.intranet.asf.ro:1521:CAPONE</prop>
				<prop key="username">capagency</prop>
				<prop key="password">capone</prop>
			</props>
		</property>
</bean>

	<!-- HikariCP configuration -->
<bean id="dataSource" class="com.zaxxer.hikari.HikariDataSource" destroy-method="close">
		<constructor-arg ref="hikariConfig" />
</bean>
```

When downgrading to 2.3.7 it worked well.

The configuration from java code works well:

```java
	@Bean(destroyMethod = "close")
	public DataSource dataSource() {
		final HikariDataSource dataSource = new HikariDataSource();
		dataSource.setDriverClassName("oracle.jdbc.driver.OracleDriver");
		dataSource.setJdbcUrl("jdbc:oracle:thin:@vs1706.intranet.asf.ro:1521:CAPONE");
		dataSource.setUsername("capagency");
		dataSource.setPassword("capone");
		dataSource.setIdleTimeout(600000);
		dataSource.setMinimumIdle(0);
		dataSource.setMaximumPoolSize(2);
		dataSource.setConnectionTimeout(180000);
		return dataSource;
	}
```
I think the issue should be reopened.

Thank you

**Comment by nitincchauhan** [comment]
@danjee try latest 2.4.6 and if it does not work, please post more info like stack trace if any exception or 'debug' logs.
