### ISSUE TITLE
Delegate toString() for proxied objects

### ISSUE THREAD

**Issue by electrum** [brettwooldridge/HikariCP#420]
MySQL's `Statement.toString()` is quite useful because it shows the full SQL that will be sent to the database, but unfortunately, the proxied statements hide this (without hacking around using `unwrap()`).

**Comment by brettwooldridge** [comment]
What version of HikariCP are you using?  The MySQL ``Statement.toString()`` should still be available, [albeit wrapped](https://github.com/brettwooldridge/HikariCP/blob/dev/src/main/java/com/zaxxer/hikari/proxy/StatementProxy.java#L52).

**Comment by electrum** [comment]
Sorry, we were using 1.3.8. I updated to the latest version. Thanks!
