### ISSUE TITLE
AS400JDBCDriver not working

### ISSUE THREAD

**Issue by lauhin** [brettwooldridge/HikariCP#421]
On the documentation page is the DataSource 'com.ibm.as400.access.AS400JDBCDriver' added for IBM AS400.
When I add this as dataSource, I got an error Could not cast com.ibm.as400.access.AS400JDBCDriver to javax.sql.DataSource.
When I saw that error, I know it was not the driver we have to add but the DataSource: com.ibm.as400.access.AS400JDBCDataSource.
But when I added that, I got an error Method not found: setUrl.
Any solution? Thx

**Comment by nitincchauhan** [comment]
In docs it is:
com.ibm.as400.access.AS400JDBCDriver
Not:
com.ibm.as400.access.AS400JDBCDataDriver

Please post your configuration and stack trace, preferably debug logs.

**Comment by lauhin** [comment]
Sorry, I meant AS400JDBCDriver indeed. I used Spring. and added the following config like documented:

<bean id="dataSource" class="com.zaxxer.hikari.HikariDataSource" destroy-method="close">
    <property name="poolName" value="as400" />
    <property name="connectionTestQuery" value="SELECT 1" />
    <property name="dataSourceClassName" value="com.ibm.as400.access.AS400JDBCDriver" />
    <property name="dataSourceProperties">
        <props>
            <prop key="url">${jdbc.url}</prop>
            <prop key="user">${jdbc.username}</prop>
            <prop key="password">${jdbc.password}</prop>
        </props>
    </property>
</bean>

When I use this, I got an error: com.ibm.as400.access.AS400JDBCDriver could not be cast to javax.sql.DataSource.

I solved it by using the old config using jdbcUrl, but the documentation says that using the dataSourceClassName is preferred:

<bean id="dataSource" class="com.zaxxer.hikari.HikariDataSource" destroy-method="close">
        <property name="poolName" value="as400" />
        <property name="connectionTestQuery" value="select 1" />
        <property name="jdbcUrl" value="${jdbc.url}" />
        <property name="driverClassName" value="com.ibm.as400.access.AS400JDBCDriver" />
        <property name="username" value="${jdbc.username}" />
        <property name="password" value="${jdbc.password}" />
    </bean>
![stacktrace](https://cloud.githubusercontent.com/assets/3474229/9903629/2dbb9174-5c78-11e5-91fa-5f27fb0860c6.PNG)

**Comment by brettwooldridge** [comment]
I'm not sure what AS400 JDBC driver version you are using.  The [docs here](http://publib.boulder.ibm.com/iseries/v5r2/ic2924/info/rzahh/javadoc/com/ibm/as400/access/AS400JDBCDataSource.html) indicate that ``com.ibm.as400.access.AS400JDBCDataSource`` is correct.

I do not see a setter for a URL (``setUrl()``) on the DataSource class, so that would explain why you got the method not found error.

If you use the *dataSourceClassName*, instead of the *driverClassName``, you will need to stick to the setters available on that class.

**Comment by Sanal567** [comment]
static DataSource dataSource() {
                    HikariConfig dataSourceConfig = new HikariConfig();
                     dataSourceConfig.setDriverClassName("com.ibm.as400.access.AS400JDBCDriver");
                    dataSourceConfig.setJdbcUrl("jdbc:as400://+serverIP+;prompt=false");
                    dataSourceConfig.setUsername(username);
                    dataSourceConfig.setPassword(password);
                    return new HikariDataSource(dataSourceConfig);
                }

    In main method:

         DataSource dataSource =  dataSource();
         conn = dataSource.getConnection();


Use above or below 

        AS400JDBCDataSource AS400DataSource = new AS400JDBCDataSource();
        AS400DataSource.setUser(userName);
        AS400DataSource.setPassword(password);
        AS400DataSource.setServerName(host);

    DataSource dataSource = AS400DataSource ;
         conn = dataSource.getConnection();
