### ISSUE TITLE
Should ProxyStatement.getResultSet() always return the same instance?

### ISSUE THREAD

**Issue by patric-r** [brettwooldridge/HikariCP#425]
Hi,
currently ProxyStatement.getResultSet() returns a new (proxy) instance for each call.
However, JDBC drivers seem to usually return the same instance. 

For code which rely on object identity on Statement.getResultSet(), behavior might be altered.
I know that relying on ResultSet identiy is usually a bad thing - but there might be valid use cases, e.g. when using further (development-time) jdbc proxy instances which wrap the ones from HikariCP.

I could not find a statement within the JDBC's javadoc/spec regarding this.
So this is more a question (than a bug report) if this can be changed that way to minimize artifacts introduced by HikariCP.

**Comment by brettwooldridge** [comment]
@patric-r It is an interesting question.  While theoretically there good be an issue, it is interesting/important to note what the [JavaDoc](http://docs.oracle.com/javase/7/docs/api/java/sql/Statement.html#getResultSet()) says for ``Statement.getResultSet()``:
```
Retrieves the current result as a ResultSet object. This method should be called
only once per result.
```

**Comment by brettwooldridge** [comment]
... so, while HikariCP *could* endevour to return the same instance, in doing to -- and explicitly guaranteeing that behavior -- would it be encouraging a usage model which is inherently fragile according to the JavaDoc?

Doing so *would* entail additional state tracking in the form of necessarily overriding ``getMoreResults()`` and ``getMoreResults(int)`` and "invalidating/discarding" the instance held in the ProxyStatement.

**Comment by brettwooldridge** [comment]
... thinking further.  If HikariCP did theoretically return the same result, what would the correct behavior be if the underlying *delegate* returned different instances?  Would HikariCP need to track whether the *delegate* returned the same or difference instance, and then itself mirror that behavior?  I.e. returning a new *ProxyResultSet* if ``getResultSet()`` is called and returns a different ResultSet than the previous call?

**Comment by patric-r** [comment]
@brettwooldridge I also noticed the javadoc which you cited and wondered about the reason and the relaxed "should"-wording for this. Unfortunately, the JDBC spec remains silent about this.

The javadoc for this method is also stating:
```
Returns:
the current result as a ResultSet object or null if the result is an update count or there are no more results
```
Someone can speculate that "`the current result`"  *could* be an hint that the authors intended that implementations should always return the same instance on consecutive calls.

I can understand your points regarding the cost-value ratio, especially because `getResultSet()` seems to be rarely used.
I'm unsure, too - nevertheless I decided to tell you about my finding to hear your opinion.

Your further questions are comprehensible. 
Interestingly, I was faced by the same question within my jdbc wrapper implementation. I decided to do it exactly as you proposed:
I am mirroring the delegate's behavior which seemed to be the most safest solution - which resulted in filing this question after I realized that *my* delegate (HikariCP) is always returning a different instance.

**Comment by brettwooldridge** [comment]
Some internet sleuthing shows that at least Firebird/Jaybird, Sybase, and Informix will throw if ``getResultSet()`` (and ``getUpdateCount()`` in the case of Sybase) if called multiple times.

**Comment by patric-r** [comment]
Interesting, however your link to Sybase doesn't document this for `getResultSet()` rather than `getUpdateCount()`

Some more:
Oracle (tested), [PostgreSQL](https://github.com/pgjdbc/pgjdbc/blob/master/org/postgresql/jdbc2/AbstractJdbc2Statement.java#L871) and [Derby](http://svn.apache.org/repos/asf/db/derby/code/trunk/java/client/org/apache/derby/client/am/ClientStatement.java) returns the same instance.

**Comment by patric-r** [comment]
...DB2 and MySQL also seem to return the same instance.

**Comment by nitincchauhan** [comment]
interesting read.
IMO, ResultSet is an interface. one should NOT rely on its identity (implementation detail).
If you do, your solution may not work if vendor changes implementation.
