### ISSUE TITLE
Pooled connection couldn't be reused.

### ISSUE THREAD

**Issue by fansgit** [brettwooldridge/HikariCP#434]
Failed to test reusing the pooled connection on `HikariCP 2.4.1` below,

```java

import java.sql.Connection;
import com.zaxxer.hikari.HikariDataSource;

public class Main {

	public static void main(String[] args) throws Exception {

		HikariDataSource ds = new HikariDataSource();
		ds.setJdbcUrl("jdbc:mysql:///test");
		ds.setAutoCommit(false);
		ds.setMaximumPoolSize(1);

		Connection conn = ds.getConnection();
		conn.createStatement().executeQuery("select 1");

		new Thread(() -> {
			try {
/*   
  The following line caused java.sql.SQLTransientConnectionException: 
  HikariPool-0 - Connection is not available, request timed out after 30000ms.
*/
				Connection conn2 = ds.getConnection(); 
                conn2.createStatement().executeQuery("select 2");
				conn2.commit();
			} catch (Exception e) {
				e.printStackTrace();
			}
		}).start();

		conn.commit();
	}
}

```

**Comment by chrisvest** [comment]
You never close the first connection you grab, so it never returns to the pool.

**Comment by fansgit** [comment]
@chrisvest How to check if the connection returns to the pool after it's closed?

**Comment by chrisvest** [comment]
It returns to the pool if you can `ds.getConnection()` again. But first, you have to `conn.close()` it.

**Comment by fansgit** [comment]
Connection conn = ds.getConnection();
conn.close();
assertEqual(conn, ds.getConnection()); // Why does it fail if the connection returns to the pool?

**Comment by brettwooldridge** [comment]
@fansgit That assert fails because the proxy object returned by each call to ``getConnection()`` is unique.

This would work:
```java
Connection connection = ds.getConnection();
Connection unwrap = connection.unwrap(Connection.class);
Assert.assertNotNull(connection);

connection.close();
connection =  ds.getConnection();
Connection unwrap2 = connection.unwrap(Connection.class);

assertEqual(unwrap, unwrap2);
```
The ``unwrap()`` call gets the underlying actual Connection object to the DB which the proxy (delegator) class returned by ``getConnection()`` is wrapping.

**Comment by fansgit** [comment]
@brettwooldridge thanks. I overlooked `unwrap`. Proxy makes perfect sense here.
