### ISSUE TITLE
HikariCP is not serializable

### ISSUE THREAD

**Issue by endian675** [brettwooldridge/HikariCP#435]
I would very much like to use HikariCP with Apache Ignite, but to do so I need at least the HikariDataSource class (and the classes of all of its fields) to implement java.io.Serializable.  Is there any particular reason why HikariCP does not implement Serializable?

**Comment by brettwooldridge** [comment]
How would this make sense?  *Serialization* implies *deserialization*, and what is the point of *deserialization* if the deserialized object is non-functional?

The ``java.io.Serializable`` contract is, every object reference in the graph of objects, starting from the object instance being serialized, must also be serializable (*unless declared transient*).  

``java.sql.Connection`` is itself is not serializable, nor are the ``java.net.Socket`` connections that they hold, and neither is ``javax.sql.DataSource``, so I am not sure what "serializing" a ``HikariDataSource`` would even mean.

Whatever kung-fu was performed after declaring HikariDataSource as serializable would be merely hand-waving, as the deserialized instance would in no way reflect the actual state of the original serialized instance.

You are welcome to perform your own hand-waving kung-fu like so:
```java
public class MyDataSource implements DataSource, Serializable {
   private transient HikariDataSource delegate;

   @Override
   public Connection getConnection() throws SQLException {
      if (delegate == null) {
         // instantiate one
      }
      return delegate.getConnection();
   }

   // 8 other delegated methods
   ...
}
```
Tada!  A serializable HikariDataSource.
