### ISSUE TITLE
HikariCP thread creation / destruction cycles

### ISSUE THREAD

**Issue by patric-r** [brettwooldridge/HikariCP#439]
This is a question, not a bug report.

HikariCP creates several threads in regular intervals, does some work and destroys them a little bit later.
Someone may argue that thread creation might be an expensive task and ask why HikariCP doesn't reuse them, at least for some cycles to reduce effort.

I can imagine that the reason for this is part of HikariCP security/hardening concept, ensuring that possible ThreadLocal references hold by JDBC driver objects will be cleared in any case to prevent any leak situations.
However, it would be interesting to hear the developer's opinion/view of this design decision.

Thank you.

**Comment by brettwooldridge** [comment]
@patric-r HikariCP basically has three execution threads: A House-keeping thread, add connection thread, and close connection thread.

The house-keeping thread runs every 30 seconds, and is therefore *persistent* (never dies).

Both the add connection and close connection threads are *transient*.  Connection creation and retirement should be relatively are (that is the purpose of a pool), and tend to occur in "groups" or "clusters".  Connections are added in groups when there is a traffic spike, and connections are retired in groups when they reach idle.

The add and close connection threads "hang around" for 5 seconds after running, in case there is more work to do -- in which case they will again wait 5 seconds afterwards.  Then they terminate.

Thread creation is not cheap, but running threads, even if idle, are not free either.  The default thread stack is 1MB, so two idle threads consume 2MB of memory.

HikariCP tries to find a balance of responsiveness and resource preservation.

**Comment by patric-r** [comment]
Thanks for your explanation, Brett.

`Thread creation is not cheap, but running threads, even if idle, are not free either.`
You're right, but IMHO investing 2*2MB per pool seems to be a good (and pretty cheap) investment if we can save cpu time (and reduce latency) for the whole application running time. We should not forget that the current approach also increases the amount of work for the garbage collector.

Most probably it would be necessary to profile and/or micro-benchmark this but you're right it all depends on how often the pool needs to create those two threads. It's non-trivial to determine which design approach is better in average. 

However, if I'd need to make a rough guess, I would assume that the persistent thread approach wins in average (and with a faster response on the first connection acquirement if all connections are borrowed as a bonus).

**Comment by jnehlmeier** [comment]
@patric-r The RAM can quickly add up if you have lots of pools per JVM instance. So I would be careful with saying "pretty cheap" as it could end up in gigabyte range just for keeping idle threads alive. 

Personally I prefer the current model of having transient threads for adding and closing connections as they are rarely active if your pool is configured correctly depending on your work load.

**Comment by patric-r** [comment]
@jnehlmeier
It's an edge case to have hundreds of pools running in a single jvm (otherwise I don't see the "gigabytes" magnitude).
In this case "pretty cheap" indeed needs to be relativized from an absolute meaning, however compared to the amount of heap your jvm would probably require to hold all the jdbc objects (if you actually use the pools), it's still negligible.
However, I agree that 1000 persistent alive pool threads seem to be inadequate.

I also agree with you if most of the pools rarely need to open/close connections, persistent threads would really be a drawback compared to the current design where thread creation would rarely happen in such a case.

What about sharing (possibly persistent) add/close connection threads between pools?

**Comment by brettwooldridge** [comment]
@patric-r Also keep in mind there are actually users running HikariCP on Android!  One flip side we have customers that are running [thousands of pools](https://github.com/brettwooldridge/HikariCP/issues/215#issuecomment-67822692) in a single JVM instance.

I may consider a heuristic based on ``minimumIdle``, ``idleTimeout``, and ``maxLifetime`` to determine the survivability time of the threads.  If a certain pool configuration is likely to "churn" threads, it is worth optimizing.  However, one or two threads spinning up once or twice a minute does not justify doing so.

@patric-r can you put some hard numbers, like a VisualVM or JConsole graph showing an adherent pattern?

**Comment by brettwooldridge** [comment]
@jnehlmeier Because you can set a ``ThreadFactory`` on the ``HikariConfig`` the user should be able to provide an implementation that always returns a shared thread.  Though I've never tried it.

**Comment by jnehlmeier** [comment]
@brettwooldridge I am pretty sure things will break badly if you start to return a shared, singleton Thread instance using a custom ThreadFactory. The JavaDoc pretty clearly states that the factory creates new threads and you also use the same factory for two executors. So suddenly two executors will use the same Thread instance and I am pretty sure they will not expect that.

Imagine adding and closing a connection collides and one executor suddenly has a busy thread even though that executor never executed a task (but the other executor did). Sounds like IllegalStateException.

The same might also happen if you ever decide to use more than one thread in your add/close executors in the future for whatever reasons. Then the executor would think that he can run X tasks using X threads but in reality he just has a single thread instance which is busy as soon as the first task is executed. Also sounds like IllegalStateException.

Maybe I am wrong but I could imagine that it won't work at all.

**Comment by brettwooldridge** [comment]
@jnehlmeier Basically, you're right, but not for the expected reasons.  It would work fine, with the caveat that not only is the Thread shared between ThreadPoolExecutors but also the Queue of tasks.  From looking at the code of ThreadPoolExecutor, provided that the Queue was shared, it appears that it would work.  However, HikariCP does not allow the user to specify a Queue, so rather a moot point.

**Comment by brettwooldridge** [comment]
Again, whether or not this is a problem is all rather theoretical at this point.  I just used JMH to measure thread creation time (on my iMac) at ~90 microseconds.

That is as measured from T<sup>1</sup> calling ``Thread.start()``, to some action within T<sup>2</sup> that is started.
