### ISSUE TITLE
Performance : Hikari vs high concurrency tcServer ?

### ISSUE THREAD

**Issue by abhiv1311** [brettwooldridge/HikariCP#443]
We were trying to figure which CP should we go with ? We compared tomcat vs tcServer vs Hikari CP and we saw that HIkari CP performed much better than tomcat but when we compared the following transactions of HIkari CP against tcServer - 
1) getConnection
2) getConnection, stored proc execution , connection.close

The average response times were every similar ,  with tcServer giving a more stable set of response times . The standard deviation of Hikari CP was more as compared to tcServer - with lesser number of spikes(min and max) over a period of time.
![image](https://cloud.githubusercontent.com/assets/14974606/10280418/ba81033e-6b8a-11e5-9e2f-5270f8e1eded.png)

Any thoughts ?

**Comment by brettwooldridge** [comment]
Cross-pool comparisons are always difficult, because so much comes down to internal implementation details.

I don't have any experience with tcServer, but here is what I can say with respect to Tomcat or other pools in general: Make sure you are comparing apples-to-apples.

For example, [here is the HikariCP pool configuration](https://github.com/brettwooldridge/HikariCP-benchmark/blob/master/src/main/java/com/zaxxer/hikari/benchmark/BenchBase.java#L201) used in our benchmark.  And [here is the *equivalent* Tomcat configuration](https://github.com/brettwooldridge/HikariCP-benchmark/blob/master/src/main/java/com/zaxxer/hikari/benchmark/BenchBase.java#L124).

What does "equivalent" mean?  It means, as closely as possible we tried to configure Tomcat with the same reliability guarantees that HikariCP provides by default.

 * Rollback of uncommitted transactions on close
 * Disposable facades<sup>1</sup>
 * Test connection on borrow
 * Track Statements and close them upon connection return

<sup><sup>1</sup> Disposable facades prevent one thread from using a connection, closing it, and then accidently continuing to use it after it is given to another thread.<sup>

Tomcat defaults, and possibly tcServer defaults, make tradeoffs of performance over reliability.  HikariCP does not do that.

However, the two (Tomcat and HikariCP) are still not equivalent (and cannot be made so).  HikariCP performs timeout boxing at the socket level (where supported by the driver), which allows it to handle network partition events instead of hanging your application.

I would be interested to see how tcServer handles [database down](https://github.com/brettwooldridge/HikariCP/wiki/Bad-Behavior:-Handling-Database-Down) network partition events.

**Comment by nitincchauhan** [comment]
@brettwooldridge  Maybe you should also put this answer under good heading in https://github.com/brettwooldridge/HikariCP-benchmark

**Comment by brettwooldridge** [comment]
@nitincchauhan What I really need to do is finish [this write-up](https://github.com/brettwooldridge/HikariCP/wiki/%22My-benchmark-doesn't-show-a-difference.%22)...

**Comment by nitincchauhan** [comment]
@nitincchauhan that is better. may be write one liner link to it in benchmark page.

**Comment by abhiv1311** [comment]
Thanks Brent for the quick response .

We ran the tests with the following config for tcServer and HIkari respectively.Hope it makes sense -

<Resource name="******"
		              auth="Container"
		              type="javax.sql.DataSource"
		              driverClassName="oracle.jdbc.OracleDriver"
		              removeAbandoned="true"
		              removeAbandonedTimeout="10"
		              logAbandoned="true"
		              maxActive="25"
		              initialSize="25"
		              minIdle="25"
		              maxIdle="25"
		              maxWait="10000"
		              maxAge="900000"
		              testOnBorrow="true"  
		              timeBetweenEvictionRunsMillis="180000"
		              minEvictableIdleTimeMillis="600000"
		              validationQuery="SELECT 1 FROM DUAL"
            /-->

<Resource name="******"  
	      		              auth="Container"
	      		              factory="com.zaxxer.hikari.HikariJNDIFactory"
	      		              type="javax.sql.DataSource"
	      		              driverClassName="oracle.jdbc.OracleDriver"
	      		              removeAbandoned="true"
	      		              idleTimeout="10000"
	      		              logAbandoned="true"
	      		              maxActive="25"
	      		              minimumIdle="25"
	      		              maximumPoolSize="25"
	      		              connectionTimeout="10000"
	      		              maxLifetime="900000"
	      		              timeBetweenEvictionRunsMillis="180000"
	      		              minEvictableIdleTimeMillis="600000" 
            />

**Comment by brettwooldridge** [comment]
@abhiv1311 Thanks for that.  I'll note a couple of things.

HikariCP does not have the following parameters, so they will be ignored by *HikariJNDIFactory*: ``removeAbandoned``, ``logAbandoned``, ``maxActive``, ``timeBetweenEvictionRunsMillis``, ``minEvictableIdleTimeMillis``.

In order to configure tcServer with the same reliability guarantees as HikariCP, you would need to add:
```
rollbackOnReturn="true"
useDisposableConnectionFacade="true"
jdbcInterceptors="org.apache.tomcat.jdbc.pool.interceptor.ConnectionState;org.apache.tomcat.jdbc.pool.interceptor.StatementFinalizer"
```
If you do so, and you have a way of monitoring network traffic between the application and the database, you are likely to find that the network traffic is now substantially higher for tcServer than HikariCP at the same reliability level.  You may also find that tcServer performance has dropped a bit.

**Comment by abhiv1311** [comment]
Thanks Brett . I am still working with the permutations to get the best fit .

For Db down testing we ran two use cases . To simulate db down - pulled out the network wire  
1) Just  get a  connection without any statement execute - Hikari didnt detect a network outage , but tcServer did.
2) When i introduced a statement execute - HIkari seemed to recover and lost lesser number of requests possibly due to the way tcServer does validations based on time .
My question is , maybe something was wrong from the way we tested , or Hikari works in a way that only when a statement  execute needs to be done that it does a validation ?

**Comment by brettwooldridge** [comment]
@abhiv1311 HikariCP contains an optimization that basically says, if a Connection has been used within the past 999ms, it is considered "alive" and does not need to be tested for aliveness.

However, doing so *can* have an unintended side-effect in a DB down scenario, if connections are frequently used.  For example, if many connections have been active within the past second, at the instant that the DB goes down they can be given out by the pool.  Unless the application itself is using query timeouts, or has set the network timeout (``Connection.setNetworkTimeout()`` available only in JDBC4 drivers), then queries by the application can hang for up to the operating system's default TCP timeout.

I am actually suprised that tcServer recoved from the cable-disconnection scenario quickly (or more quickly than HikariCP).  From everything that I could see they are using the vanilla Tomcat DBCP pool, which does not support network timeouts.  I would be interested to hear if you can observe the same behavior in two or three runs.

The guys over at Wix.com (one of the world's largest hosting providers) [ran a similar](http://engineering.wix.com/2015/04/28/how-does-hikaricp-compare-to-other-connection-pools/) DB down test with different results that what you are observing.  Granted they are using MySQL, not Oracle, as far as I know.

**Comment by nitincchauhan** [comment]
tcServer is using tomcat-jdbc-pool by default. may be testOnBorrow="true" did the job

**Comment by brettwooldridge** [comment]
@nitincchauhan This is probably true.

Which leads to another point, with 25 connections in the pool, and a total load of only 35 req/sec there will probably be very little difference in performance between *any* of the pools (HikariCP, Tomcat DBCP, C3P0, Vibur...).

If you enable ``testOnBorrow`` in Tomcat DBCP and you try to handle 500 req/sec, even just calling ``getConnection()/close()`` with no SQL execution at all will generate ~500KB-1MB of traffic to the database.  This can be mitigated, like HikariCP, by setting ``validationInterval=1000``.  However, if you enable ``rollbackOnReturn``, Tomcat DBCP will again generate increasing traffic load on the DB as req/sec increases.

**Comment by abhimanyuvarma** [comment]
Yes . tcServer(tomcat jdbc pool) tests the connection with a default validation interval of 30 seconds  with testOnBorrow set to true.

Hey Brett/Nitin  ,
I was hoping you would be able to help me with these -  maybe a little too much to ask - :) 
How has been the adoption rate of HIkari CP in production systems ? 
Any major production systems using HIkari CP if you could name a few ?

**Comment by brettwooldridge** [comment]
@abhimanyuvarma The heaviest use customer we are aware of is Wix.com.  Some statistics from a [recent Wix presentation](https://youtu.be/rBX67gbJhYo?t=1m33s):
 * Over 60M users
 * Static storage is > 2 Petabytes
 * 3 data centers + 3 clouds (Google, Amazon, Azure)
 * 1.5 Billion HTTP requests/day

As I pointed out before, Wix ran a [benchmark](http://engineering.wix.com/2015/04/28/how-does-hikaricp-compare-to-other-connection-pools/) and decided to switch from [DBCP](http://engineering.wix.com/2013/06/12/how-many-threads-does-it-take-to-fill-a-pool/) to HikariCP.

Another "major production system" using HikariCP includes Twitter ([Zipkin](https://github.com/openzipkin/zipkin)).  Other than that, I don't know.  But we're getting over 50,000 downloads/month so I suspect there are some other large customers in there somewhere.

**Comment by mahendya** [comment]
@brettwooldridge would like to know how Hikari make use of JDBC4  isValid(int) api for connection validation.How can we verify weather validation is through or not? just for testing purpose how can we disable isValid call.

**Comment by brettwooldridge** [comment]
@mahendya Every driver that supports ``isValid()`` implements it differently.  For example, the MySQL and MariaDB drivers send a [raw ping packet over the socket](http://bazaar.launchpad.net/~massimo-siani/mariadb-java-client/CONJ-120/view/head:/src/main/java/org/mariadb/jdbc/internal/mysql/MySQLProtocol.java#L883).  PostgreSQL [sends an empty query](https://github.com/pgjdbc/pgjdbc/blob/master/org/postgresql/jdbc4/AbstractJdbc4Connection.java#L138).  As I said, every database is different.  If you want to verify what your driver is doing, I suggest wireshark.

If you want to disable ``isValid()`` in HikariCP, simply set a ``connectionTestQuery`` ... that will be used instead.  There is no way to disable connection testing completely, so either ``isValid()`` or the ``connectionTestQuery`` will be used.

**Comment by mahendya** [comment]
thanks for the useful information @brettwooldridge. 
We are using Oracle driver ,i tried googling but not successful. 
So it will great help if you can answer some of my doubts.
1.)How Oracle Driver(ojdbc6) implements isValid api .

2.)As it is not recommend to use connectionTestQuery, will it affect performance if we use connection query in place of isValid api.

3.) does hikari supports jdbc4ConnectionTest boolean value ?

Thanks in advance.

**Comment by brettwooldridge** [comment]
@mahendya I have no idea how Oracle implements ``isValid()``, but if I were to guess it would be that they send a ping packet of some sort.  A test query can be nearly as performant as the ``isValid()`` test, depending on the database.  I wouldn't worry too much about the performance.

The ``jdbc4ConnectionTest`` property is deprecated.  If no ``connectionTestQuery`` is set, HikariCP will automatically detect whether ``isValid()`` is supported, and if so it will use it.  If there is no ``connectionTestQuery`` configured and the driver does not support ``isValid()``, HikariCP will log warning messages and fail to start.

**Comment by mahendya** [comment]
thanks @brettwooldridge . thanks a lot.

**Comment by slyoldfox** [comment]
@mahendya @brettwooldridge I had wondered the same thing with oracle. At the moment we have oracle.connectionTestQuery=SELECT 1 FROM DUAL.

I have been looking around oracle.jdbc.driver.PhysicalConnection::doPingDatabase, you will see:

```java
                stmt = this.createStatement();
                ((oracle.jdbc.OracleStatement)stmt).defineColumnType(1, 12, 1);
                stmt.executeQuery("SELECT \'x\' FROM DUAL");
```
However doPingDatabase is overriden by oracle.jdbc.driver.T4CConnection (which it the one you possibly are using). This has some more magic. It is also synchronized:

```java
synchronized int doPingDatabase() throws SQLException {
}
```

The decompiled java also shows a check on versionNumber (I have no real clue which version that is). But I  suppose Oracle > v10
```java
if(this.versionNumber >= 10102) {
                    try {
                        this.needLine();
                        this.oping.doOPING();
                    } catch (IOException var143) {
...
                    }
}
```

If you further look at this.oping.doOPING(); you will see:

```java
    void doOPING() throws IOException, SQLException {
        this.doRPC();
    }
```

In the end, seeing the synchronized block and the word RPC made me conclude that keeping it to a simple connectionTestQuery, would be best. But well, I would be curious if anyone does happen to do a performance test.

**Comment by mahendya** [comment]
@brettwooldridge just want know when hikari connection pool will be created in tcServer.
1.)pool is created upon Tomcat startup ?
2.)or  when it's first looked up in JNDI ?

I am defining my resource in context.xml({CATALINA-BASE}/conf/Localhost/).
If it is during startup then is there any way to stop any resource loading/deployment during startup?
Actually i have two data source resources with two different connection pooling.
want to enable one at a time. please help.

**Comment by brettwooldridge** [comment]
@mahendya I am not clear on how the Tomcat lifecycle works, particularly with JNDI configurations.  You'll need to ask this question on stackoverflow.

**Comment by mahendya** [comment]
thanks @brettwooldridge. i have posted there.
