### ISSUE TITLE
Why does Hikari depend on hibernate-core?

### ISSUE THREAD

**Issue by donaldquixote** [brettwooldridge/HikariCP#447]
That's a heavy dependency to pull in when a project just wants to use JDBC with a pooling impl. I'm curious why it is necessary. If it's only there to aid Hibernate projects, couldn't it be split into a separate library?

**Comment by brettwooldridge** [comment]
I just built a project that depends on HikariCP and it did not pull in Hibernate as a dependency.  The dependency is declared as:
```xml
      <dependency>
         <groupId>org.hibernate</groupId>
         <artifactId>hibernate-core</artifactId>
         <version>${hibernate.version}</version>
         <scope>provided</scope>
         <optional>true</optional>
      </dependency>
```
Which should not result in it being pulled in, unless you are building HikariCP itself.

**Comment by donaldquixote** [comment]
Apologies for the noise, missed the scope piece. Thanks for your reply.
