### ISSUE TITLE
Race condition while adding threads

### ISSUE THREAD

**Issue by mtambara** [brettwooldridge/HikariCP#452]
I'm opening issue to notify you about and provide a potential solution for a bug in your code. There is a race condition when 2 threads call `HikariPool.getConnection()` while there are no idle connections available and `minimumIdle` is set to 0. Both threads will go into `ConcurrentBag.borrow(long, TimeUnit)`, see that there are no available threads to borrow, and create new worker threads to add one connection each in `HikariPool.addBagItem()`. The borrowing threads will then wait until signalled, at which point they will wake up and check for available connections again. The workers will execute sequentially and each try to create a new connection. This is the execution that leads to the race condition:

Worker 1 adds a connection as usual, signalling the borrow threads to wake up. 

Worker 1 finishes (`isDone()`)

Before the borrow threads can check for new connections, worker 2 tries to add a new connection.

Worker 2 checks if `getIdleConnections() <= minimumIdle`, sees the connection worker 1 added, and skips the `addConnection` call.

Borrow thread 1 sucessfully borrows a connection.

Borrow thread 2 cannot borrow a connection and goes to sleep waiting for Worker 2 to signal.

Worker 2 finishes (`isDone()`)

I have included a potential solution to this problem (signal at the end of the worker thread no matter what) and a test to reproduce this race condition (`AddConnectionRaceConditionTest`).

I have already sent you a pull here: brettwooldridge#451

Let me know if you have any questions.

(cc @shuyangzhou)

**Comment by brettwooldridge** [comment]
@mtambara @shuyangzhou HikariCP 2.4.2 has been released, containing a fix for this issue.

**Comment by shuyangzhou** [comment]
Awesome! Thanks @brettwooldridge !
