### ISSUE TITLE
eclipse-4.5 importing err

### ISSUE THREAD

**Issue by fjjiaboming** [brettwooldridge/HikariCP#455]
![importing-err](https://cloud.githubusercontent.com/assets/951124/10408410/4193abea-6f2f-11e5-8088-2efab966cd5c.png)

![pom-err](https://cloud.githubusercontent.com/assets/951124/10408412/5776d068-6f2f-11e5-835f-b633fb491f4e.png)

**Comment by fjjiaboming** [comment]
How do I fix it ?

**Comment by brettwooldridge** [comment]
Right-click on plugin no covered error...Quick fix.  Then choose ignore.

**Comment by fjjiaboming** [comment]
ignore... 

OK . *_*

**Comment by brettwooldridge** [comment]
Did you figure it out?

**Comment by fjjiaboming** [comment]
@brettwooldridge  Yes. Do it by ignoring. I read the code except package the project.
