### ISSUE TITLE
When the ResultSet is retrieved by java.sql.Statement.getResultSet(), ResultSet throws exception with method next() 

### ISSUE THREAD

**Issue by migdus** [brettwooldridge/HikariCP#457]
When I try to run a select query and then try to work with the resultSet, I got an exception.

This is what I'm doing:
```java
connection = getConnection();
Statement preparedStatement = connection.createStatement();
ResultSet resultSet = preparedStatement.executeQuery(query);
resultSet.next();
```
This is the exception:
```
java.sql.SQLException: Closed Resultset: next
	at oracle.jdbc.driver.InsensitiveScrollableResultSet.next(InsensitiveScrollableResultSet.java:558)
	at com.zaxxer.hikari.proxy.HikariResultSetProxy.next(HikariResultSetProxy.java)
...
```

I'm migrating from BoneCP to HikariCP 2.4.1. I'm using Oracle thin client v.6 and it seems to be configured correctly.

Maybe this is related with [issue 221](https://github.com/brettwooldridge/HikariCP/issues/221).

Thank you

**Comment by brettwooldridge** [comment]
@migdus I don't think it is the same issues as #221 was.  If you catch the exception, and call ``sqle.getSQLState `` does it provide an additional error code?

Also, are you sure that you're not closing the Statement before the ResultSet, or that the Connection/Statement is not being used between multiple threads?

**Comment by migdus** [comment]
@brettwooldridge I'm catching the exception, ```getSQLState()``` provides error code 99999. Also ```getErrorCode()``` provides error code 17010.

I think I've found the problem. The code I've pasted above is a simplification of what I'm doing. This is the actual code:

- I've a method that encapsulates the connection pool library (It's called ```ConnectionPool```; How original!). This has a method to get a connection from HikariCP:
```java
public Connection getConnection() {
		try {
			return connectionPool.getConnection(); // Gets the connection
		} catch (SQLException e) {
			logger.error("An error...", e);
			return null;
		}
	}
```
- I've written a method (in the encapsulated class ```ConnectionPool```) to run a query that returns a result set:

```java
public ResultSet runRawSelectQuery(String query) {
		Connection connection = null;
		try {
				connection = getConnection();
				Statement preparedStatement = connection.createStatement();
				return preparedStatement.executeQuery(query);
		} catch (SQLException e) {
				logger.error("there is an error...", e);
				return null;
		} finally {
			try {
				connection.close();
			} catch (SQLException e) {
				logger.error("problems closing...", e);
			}
		}
	}
```
- The method ```ConnectionPool.runRawSelectQuery(query)``` is run from other methods. They get the  ```ResultSet```object and do some work with it. 

***The problem I've found and how I've solved it:*** I'm closing the connection before using the ```ResultSet```object. If I remove ```connection.close()```from ```ConnectionPool.runRawSelectQuery(query)``` the problem is solved.

 ***The question I have is:***  Why did it work with BoneCP? It has a wrong implementation?

Thank you.

**Comment by nitincchauhan** [comment]
@migdus
if runRawSelectQuery code is actual, you may still get exceptions.
I recommend using try..autoclose:
try (Connection connection = getConnection(),
     Statement preparedStatement = connection.createStatement() ) { ..... }
would be clutter and most importantly error free

**Comment by brettwooldridge** [comment]
@migdus BoneCP worked because it does not track open Statements, and therefore does not close them when you call ``connection.close()``.  The same is true for most other pools, unless you explicltly enable Statement tracking.

HikariCP *does* track open Statements, and will close all of them when you call ``connection.close()``.  Closing the Statements also causes the ResultSets to be closed.

As per [the JavaDoc](http://docs.oracle.com/javase/7/docs/api/java/sql/Statement.html#close()) for ``Statement``:
```
When a Statement object is closed, its current ResultSet object, if one exists, is also closed.
```

**Comment by migdus** [comment]
@brettwooldridge I appreciate your clarification.
@nitincchauhan Thanks for the tip.
