### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by ggaulard** [brettwooldridge/HikariCP#46]
I don't think the main issue is from you but actually that what append:

I run some tests from Maven 3.2.1 that use your lib v1.3.3 on centos 6.5 64b.
I got a Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.zaxxer.hikari.HikariConfig. Classpath look fine with debug mode enable to maven.
It work fine on Windows and even at runtime on centos.

Do you have any clue? The only thing different is the maven lib name that start with an uppercase and everything else with a lowercase. 

Maybe did you know how to force a lib to maven.

Thanks

**Comment by theresajayne** [comment]
I am getting the same issue, but i am wondering, the MVN repos what version of java is it compiled with i and the op are compiling with Java 1.7 and if the repo is compiled with 1.8 that may cause the issue.
