### ISSUE TITLE
Question regarding "Down-the-Rabbit-Hole"

### ISSUE THREAD

**Issue by doom369** [brettwooldridge/HikariCP#464]
In your article https://github.com/brettwooldridge/HikariCP/wiki/Down-the-Rabbit-Hole you are saying  

 > The invokevirtual call is replaced with a invokestatic call that is more easily optimized by the JVM. 

Could you please point to some documentation regarding "more easily optimized by the JVM"?

**Comment by brettwooldridge** [comment]
You can read this article from the excellent [Mechanical Symphathy](http://mechanical-sympathy.blogspot.com) blog, [Invoke Interface Optimisations](http://mechanical-sympathy.blogspot.com/2012/04/invoke-interface-optimisations.html), to understand more.  Or Google "invokevirtual" and "on-stack replacement".

**Comment by brettwooldridge** [comment]
@doom369 In short, even if the JVM assumes a *monomorphic* callsite and inlines the invocation (which it probably will), it still must install a trap in case another implementation shows up and transforms the callsite to *bimorphic* or *megamorphic*.  This trap setting and clearing adds slightly more overhead to the invocation.

Additionally, a static invocation will require one less stack slot and therefore one less push/pop operation at runtime, which further boosts performance.

**Comment by doom369** [comment]
Thanks for reply. I read it before, but it seems a bit outdated. Also have a look here - http://stackoverflow.com/questions/30454904/large-difference-in-speed-of-equivalent-static-and-non-static-methods

**Comment by brettwooldridge** [comment]
@doom369 Hi Dmitriy, I assume you are participating in [this discussion](http://habrahabr.ru/post/269023/).  I registered on the site, but I am still "read-only" so I was not able to reply directly.

First I would like to comment on @odnoklassniki comment that their pool is 4x faster.  I have added their pool to the [JMH benchmark](https://github.com/brettwooldridge/HikariCP-benchmark) and committed the changes for *anyone* to run.  Here is the result vs. HikariCP:

```sh
./benchmark.sh clean quick -p pool=one,hikari ".*Connection.*"

Benchmark                       (pool)   Mode  Cnt      Score      Error   Units
ConnectionBench.cycleCnnection     one  thrpt   16   4991.293 ±   62.821  ops/ms
ConnectionBench.cycleCnnection  hikari  thrpt   16  39660.123 ± 1314.967  ops/ms
```
This is showing HikariCP at 8x faster than [one-datasource](https://github.com/odnoklassniki/one-datasource).

Keep in mind that not only has HikariCP changed since that wiki page was written, but the JMH test harness itself has changed.  In order to recreate the results I got at that time, I checked out HikariCP source with that specific commit, and checked out the source just before that commit.  I ran both using the benchmark harness available at that time:

Before static proxy factory methods:
```
Benchmark                             (pool)   Mode   Samples         Mean   Mean error    Units
ConnectionBench.testConnectionCycle   hikari  thrpt        16     9303.741       67.747   ops/ms
```

After static proxy factory methods:
```
Benchmark                             (pool)   Mode   Samples         Mean   Mean error    Units
ConnectionBench.testConnectionCycle   hikari  thrpt        16     9436.699       71.268   ops/ms
```
It shows a minor improvement after the change that is above the mean error.

Typically, every change is checked with the benchmark before being committed, so it is doubtful that we would have committed that change unless the benchmark showed improvement.

**Comment by doom369** [comment]
@brettwooldridge Exactly =). Thank you for detailed answer. I'll repost on our topic, until we find invitation.

**Comment by brettwooldridge** [comment]
@doom369 I don't know why I'm even commenting on [one-datasource], because it looks horrible, but I'll note these things, just looking at the source:
 * Does not track ``Statement`` objects.  So calling ``Connection.close()`` does not close open statements.
 * Does not test connections for validity at all.
 * Closes idle connections when ``getConnection()`` is called, rather than asynchronously.
 * Has no concept of maximum lifetime, which will cause problems with MySQL, or stateful firewalls between the server and database.
 * Reuses connection proxies, so if Thread A calls ``Connection.close()``, but then continues to use the Connection it will corrupt transactions of another thread (Thread B) which has borrowed the connection.
 * Does not reset any connection state.  So, if Thread A calls ``setTransactionIsolation(READ_UNCOMMITTED)``, then closes the connection, another thread will be given the connection in READ_UNCOMMITTED isolation mode -- rather than the default isolation mode.  The same is true for ``setReadOnly()``, ``setAutoCommit()``, ``setNetworkTimeout()``, and ``setCatalog()``.
 * Provides no timeout guarantees.  If a call to ``DataSourceImpl.getConnection()`` needs to create a new connection, and the ``getConnection()`` call to the real driver blocks, the user's thread will be blocked indefinitely until that call returns.
 * Calling ``Statement.getConnection()`` returns the real connection rather than the proxy Connection.  The same is true for ``ResultSet.getConnection()``.
 * Too many more ... I'm tired.

**Comment by doom369** [comment]
=))). Thank you very much for your time and great product! I updated post accordingly. 
So let's see what author of one-datasource will reply.

**Comment by nitincchauhan** [comment]
@doom369 
@brettwooldridge
give that project sometime. It is not even a day old on github :) compare when it matures in stability and features

**Comment by brettwooldridge** [comment]
@doom369 @odnoklassniki

Hi Dmitriy

I added a new [microbenchmark repo](https://github.com/brettwooldridge/microbenches).  I was curious myself about the claim that using the *try-catch* was slower than using a conditional.  I remembered benchmarking that when I wrote it, but lost the benchmark.

Here is the interesting result.  I have [two identical](https://github.com/brettwooldridge/microbenches/tree/master/src/main/java/com/zaxxer/microbench) *FastList* classes, except [one uses the *try-catch*](https://github.com/brettwooldridge/microbenches/blob/master/src/main/java/com/zaxxer/microbench/FastList.java#L73) in the ``add()`` method, and [the other](https://github.com/brettwooldridge/microbenches/blob/master/src/main/java/com/zaxxer/microbench/FastList2.java#L71) uses a conventional conditional.

On Java 7 (jdk1.7.0_60):
```
java -jar target/benchmarks.jar -p listImpl=new,orig

Benchmark               (listImpl)   Mode  Cnt      Score    Error   Units
FastListBench.testList  new          thrpt   18  39662.960 ± 54.309  ops/ms
FastListBench.testList  orig         thrpt   18  14180.402 ± 78.944  ops/ms
```

On Java 8 (jdk1.8.0_60):
```
java -jar target/benchmarks.jar -p listImpl=new,orig

Benchmark               (listImpl)   Mode  Cnt      Score     Error   Units
FastListBench.testList  new          thrpt   18  25961.563 ±  90.275  ops/ms
FastListBench.testList  orig         thrpt   18  25448.721 ± 561.764  ops/ms
```
Clearly, the code with the *try-catch* is much faster on Java 7.  On Java 8 it seems to be a tie (and interestingly lower than Java 7).

**Comment by xhumanoid** [comment]
I disagree with you.

1. I repeated tests on MacBook

java 8
```
Benchmark               (initCapacity)  (listImpl)   Mode  Cnt      Score     Error   Units
FastListBench.testList              32         new  thrpt   18  24749,979 ± 376,647  ops/ms
FastListBench.testList              32        orig  thrpt   18  24520,606 ± 158,518  ops/ms
```

java 7
```
Benchmark               (initCapacity)  (listImpl)   Mode  Cnt      Score      Error   Units
FastListBench.testList              32         new  thrpt   18  20756,450 ± 1053,567  ops/ms
FastListBench.testList              32        orig  thrpt   18  22265,491 ±  206,853  ops/ms
```

if we try look in asm the code (cut for describe only general path when all work without exception):

FastList
```assembler
  0x000000010552b3c0: mov    %eax,-0x14000(%rsp)
  0x000000010552b3c7: push   %rbp
  0x000000010552b3c8: sub    $0x30,%rsp         ;*synchronization entry
                                                ; - com.zaxxer.microbench.FastList::add@-1 (line 76)

  0x000000010552b3cc: mov    %rsi,%r9
  0x000000010552b3cf: mov    0x18(%rsi),%r10d   ;*getfield size
                                                ; - com.zaxxer.microbench.FastList::add@6 (line 76)

  0x000000010552b3d3: mov    0x20(%rsi),%r11d   ;*getfield elementData
                                                ; - com.zaxxer.microbench.FastList::add@1 (line 76)

  0x000000010552b3d7: mov    %r10d,%r8d
  0x000000010552b3da: inc    %r8d
  0x000000010552b3dd: mov    %r8d,0x18(%rsi)    ;*putfield size
                                                ; - com.zaxxer.microbench.FastList::add@12 (line 76)

;  implicit range check on array for prevent overflow
  0x000000010552b3e1: mov    0xc(%r12,%r11,8),%r8d  ; implicit exception: dispatches to 0x000000010552b4d1
  0x000000010552b3e6: cmp    %r8d,%r10d
  0x000000010552b3e9: jae    0x000000010552b4ad
  0x000000010552b3ef: mov    0x8(%rdx),%r8d     ; implicit exception: dispatches to 0x000000010552b4ed
  0x000000010552b3f3: mov    0x8(%r12,%r11,8),%ecx
  0x000000010552b3f8: movabs $0x0,%rsi
  0x000000010552b402: lea    (%rsi,%r8,8),%rsi
  0x000000010552b406: movabs $0x0,%r8
  0x000000010552b410: lea    (%r8,%rcx,8),%r8
  0x000000010552b414: mov    0xe8(%r8),%rax
  0x000000010552b41b: mov    0xc(%rax),%ecx
  0x000000010552b41e: movslq %ecx,%r8
  0x000000010552b421: mov    (%rsi,%r8,1),%r8
  0x000000010552b425: cmp    %r8,%rax
  0x000000010552b428: jne    0x000000010552b460
  0x000000010552b42a: mov    %rdx,%r9
  0x000000010552b42d: shr    $0x3,%r9           ;*aastore
                                                ; - com.zaxxer.microbench.FastList::add@16 (line 76)

  0x000000010552b431: shl    $0x3,%r11          ;*getfield elementData
                                                ; - com.zaxxer.microbench.FastList::add@1 (line 76)

  0x000000010552b435: lea    0x10(%r11,%r10,4),%r10
  0x000000010552b43a: mov    %r9d,(%r10)
  0x000000010552b43d: shr    $0x9,%r10
  0x000000010552b441: mov    $0x1,%eax
  0x000000010552b446: movabs $0x111149000,%r11
  0x000000010552b450: mov    %r12b,(%r11,%r10,1)  ;*putfield size
                                                ; - com.zaxxer.microbench.FastList::add@12 (line 76)

  0x000000010552b454: add    $0x30,%rsp
  0x000000010552b458: pop    %rbp
  0x000000010552b459: test   %eax,-0x214945f(%rip)        # 0x00000001033e2000
                                                ;   {poll_return}
  0x000000010552b45f: retq
```

FastList2
```
  0x000000010a561dc0: mov    %eax,-0x14000(%rsp)
  0x000000010a561dc7: push   %rbp
  0x000000010a561dc8: sub    $0x30,%rsp         ;*synchronization entry
                                                ; - com.zaxxer.microbench.FastList2::add@-1 (line 73)

  0x000000010a561dcc: mov    0x20(%rsi),%ebx    ;*getfield elementData
                                                ; - com.zaxxer.microbench.FastList2::add@5 (line 73)

  0x000000010a561dcf: mov    0xc(%r12,%rbx,8),%r11d  ;*arraylength
                                                ; - com.zaxxer.microbench.FastList2::add@8 (line 73)
                                                ; implicit exception: dispatches to 0x000000010a561ee5
  0x000000010a561dd4: mov    0x18(%rsi),%ebp    ;*getfield size
                                                ; - com.zaxxer.microbench.FastList2::add@1 (line 73)

;  explicit range check on array for prevent overflow
  0x000000010a561dd7: cmp    %r11d,%ebp
  0x000000010a561dda: jge    0x000000010a561ec5  ;*if_icmpge
                                                ; - com.zaxxer.microbench.FastList2::add@9 (line 73)

  0x000000010a561de0: mov    %ebp,%r8d
  0x000000010a561de3: inc    %r8d
  0x000000010a561de6: mov    %r8d,0x18(%rsi)    ;*putfield size
                                                ; - com.zaxxer.microbench.FastList2::add@24 (line 74)

  0x000000010a561dea: cmp    %r11d,%ebp
  0x000000010a561ded: jae    0x000000010a561ead
  0x000000010a561df3: mov    0x8(%rdx),%r10d    ; implicit exception: dispatches to 0x000000010a561ef5
  0x000000010a561df7: mov    0x8(%r12,%rbx,8),%r11d
  0x000000010a561dfc: movabs $0x0,%rsi
  0x000000010a561e06: lea    (%rsi,%r10,8),%rsi
  0x000000010a561e0a: movabs $0x0,%r10
  0x000000010a561e14: lea    (%r10,%r11,8),%r10
  0x000000010a561e18: mov    0xe8(%r10),%rax
  0x000000010a561e1f: mov    0xc(%rax),%r11d
  0x000000010a561e23: movslq %r11d,%r10
  0x000000010a561e26: mov    (%rsi,%r10,1),%r10
  0x000000010a561e2a: cmp    %r10,%rax
  0x000000010a561e2d: jne    0x000000010a561e68
  0x000000010a561e2f: mov    %rdx,%r10
  0x000000010a561e32: shr    $0x3,%r10          ;*aastore
                                                ; - com.zaxxer.microbench.FastList2::add@28 (line 74)

  0x000000010a561e36: lea    (%r12,%rbx,8),%r11  ;*getfield elementData
                                                ; - com.zaxxer.microbench.FastList2::add@5 (line 73)

  0x000000010a561e3a: lea    0x10(%r11,%rbp,4),%r11
  0x000000010a561e3f: mov    %r10d,(%r11)
  0x000000010a561e42: mov    %r11,%r10
  0x000000010a561e45: shr    $0x9,%r10
  0x000000010a561e49: mov    $0x1,%eax
  0x000000010a561e4e: movabs $0x11617e000,%r11
  0x000000010a561e58: mov    %r12b,(%r11,%r10,1)  ;*synchronization entry
                                                ; - com.zaxxer.microbench.FastList2::add@-1 (line 73)

  0x000000010a561e5c: add    $0x30,%rsp
  0x000000010a561e60: pop    %rbp
  0x000000010a561e61: test   %eax,-0x217ce67(%rip)        # 0x00000001083e5000
                                                ;   {poll_return}
  0x000000010a561e67: retq
```

as you see we always have range check in main path, other code equivalent

**Comment by xhumanoid** [comment]
and YES, code incorrect

```java
      if (size < elementData.length) {
         elementData[size++] = element;
      }
```
because after increment we can create ArrayIndexOutOfBoundsException, it's reason why in array version we keep second range check

**Comment by brettwooldridge** [comment]
Alexey,

I'm not sure how you got your results, but I have tested on 3 different
Macs now (2012 iMac i7, 2013 MacBook Pro i7, 2014 iMac i5).  All produce
similar results for Java 7 and Java 8.

Here is a video of two of them:

https://youtu.be/xY-MLjSJvaY

**Comment by brettwooldridge** [comment]
On Tue, Oct 20, 2015 at 5:39 AM, Alexey <notifications@github.com> wrote:

> and YES, code incorrect
>
>       if (size < elementData.length) {
>          elementData[size++] = element;
>       }
>
> because after increment we can create ArrayIndexOutOfBoundsException, it's
> reason why in array version we keep second range check
>

I don't think you are reading that code correctly.  For example, suppose:

size=4
elementData.length=5

Then ``if (size < elementData.length)`` evaluates to ``true``.

``elementData[size++]`` is equivalent to ``elementData[4]``, with ``size``
incremented to 5 *after* the array dereference.

Now, adding another element...

size=5
elementData.length=5

Then ``if (size < elementData.length)`` evaluates to ``false``, so flow
continues in the ``else``.

There is no ArrayIndexOutOfBoundsException after the increment.  FastList
is well covered by a junit test in the main HikariCP repository, and all
edge cases are handled.

**Comment by brettwooldridge** [comment]
I don't think you are reading that code correctly.  For example, suppose:

size=4
elementData.length=5

Then ``if (size < elementData.length)`` evaluates to ``true``.

``elementData[size++]`` is equivalent to ``elementData[4]``, with ``size`` incremented to 5 *after* the array dereference.

Now, adding another element...

size=5
elementData.length=5

Then ``if (size < elementData.length)`` evaluates to ``false``, so flow continues in the ``else``.

There is no ArrayIndexOutOfBoundsException after the increment.  FastList is well covered by a junit test in the main HikariCP repository, and all edge cases are handled.

**Comment by xhumanoid** [comment]
yes, sorry, it's my mistake

**Comment by xhumanoid** [comment]
we used different version of java 7, I repeated tests with your version of java (1.7.0_55)

```
java version "1.7.0_80"
Benchmark               (initCapacity)  (listImpl)   Mode  Cnt      Score      Error   Units
FastListBench.testList              32         new  thrpt   18  22236,544 ±  224,159  ops/ms
FastListBench.testList              32        orig  thrpt   18  21034,102 ± 1354,033  ops/ms

java version "1.7.0_55"
Benchmark               (initCapacity)  (listImpl)   Mode  Cnt      Score     Error   Units
FastListBench.testList              32         new  thrpt   18  37570,587 ± 340,437  ops/ms
FastListBench.testList              32        orig  thrpt   18  13698,785 ±  90,650  ops/ms
```

**Comment by brettwooldridge** [comment]
@doom369 

Hi Dmitriy,

This is my last comment on the matter of FastList ... I still cannot comment on the website.

HikariCP has thousands of users with Java 6 and Java <7u80.
7u80 is not even publicly available from Oracle.  For Java 6
and Java < 7u80 FastList with try-catch logic is 2.5x faster.
For Java 7u80+ and Java 8 they are equal over the common range
of use.

FastList is optimized specifically for HikariCP, it is not a
replacement for any other purpose.  The default size of 32 means
that a single thread/connection can have 32 open Statements before
the list is expanded.  99.9% (or more) of applications never exceed
this limit.  If the limit is exceeded, it expands to 64 and remains
so for the life of the connection.

Trying to compare FastList for uses other than Statement tracking
is a pointless exercise.  I'll say it again, it is 2.5x faster for all
publicly available Oracle versions of Java 6 and Java 7, and equal
in performance on Java 8 -- for the range of use for which it was
designed.

HikariCP тысячи пользователей с Java 6 и Java <7u80. 7u80 даже не доступны из Oracle. Для Java 6 и Java <7u80 FastList с логикой Try-Catch является 2.5x быстрее. Для Java 7u80 + и Java 8 они равны по общему диапазоне использования. 

FastList оптимизирован специально для HikariCP, это не является заменой для других целей. По умолчанию размер 32 означает, что один поток / соединение может иметь 32 открытых заявлений, прежде чем список расширяется. 99,9% (или более) из приложений не превышает этот предел. Если лимит превышен, то расширяется до 64 и остается таким по жизни соединения. 

Попытка сравнить FastList для других, чем себе отслеживания использования является бессмысленным занятием. Я скажу это снова, это в 2,5 раза быстрее, для всех общедоступных Oracle версий Java 6 и Java 7, и равными в производительности на Java 8 - для диапазона использования, для которого он был разработан.

**Comment by doom369** [comment]
@brettwooldridge no problem. Thank you for your time. For me your decision is totally clear. I suppose @xhumanoid had some concerns. But for Hickary use cases it is not a case.

**Comment by xhumanoid** [comment]
1)
1.7.0_80 public available
http://www.oracle.com/technetwork/java/javase/downloads/java-archive-downloads-javase7-521261.html#jdk-7u80-oth-JPR

2) main problem on Java <7u80 it's not inlining add method, in other cases all work the same

Some changes of benchmark, delete .remove() invocation and change setup code for prevent realloc on invocation

```java
   @Setup(Level.Invocation)
   public void setupIter(){
      switch (listImpl) {
         case "base":
            this.fastList = new ArrayList<>(initCapacity);
            break;
         case "new":
            this.fastList = new FastList<>(String.class, initCapacity);
            break;
         case "orig":
            this.fastList = new FastList2<>(String.class, initCapacity);
            break;
      }
   }

   @Setup(Level.Trial)
   public void setup()
   {
      this.strings = new String[31];
      for (int i = 0; i < strings.length; i++) {
         strings[i] = String.valueOf(i);
      }
   }
```

```
7 (update 55)
Benchmark               (initCapacity)  (listImpl)   Mode  Cnt      Score     Error   Units
FastListBench.testList              32         new  thrpt   18  19143,115 ± 288,729  ops/ms
FastListBench.testList              32        orig  thrpt   18  10785,437 ±  83,438  ops/ms

8
Benchmark               (initCapacity)  (listImpl)   Mode  Cnt      Score     Error   Units
FastListBench.testList              32         new  thrpt   18  17699,308 ± 168,998  ops/ms
FastListBench.testList              32        orig  thrpt   18  16591,881 ± 654,025  ops/ms
```

by asm code we can see than FastListBench.testList (origin) slow because they don't did inlining.
I can say more, if you try run with 
```
java -XX:+UnlockDiagnosticVMOptions -XX:+PrintInlining -jar target/benchmarks.jar -p listImpl=new,orig
```

you will crash your JVM with error  ;)
```
#  Internal Error (compile.hpp:420), pid=11015, tid=18947
#  Error: ShouldNotReachHere()
```

on 1.7u80 & 1.8u60 all work correct without crash.

@doom369  =) no, main problem it's benchmark, not a code, because benchmark incorrect and not cover why problem happens. benchmark without explanations what happens it's crap

**Comment by brettwooldridge** [comment]
@xhumanoid Are you suggesting using ``@Invocation``?  That is not recommended.  [According to Alexsey Shipilev](http://stackoverflow.com/a/20054778/431356), "Level.Invocation is usually a bad idea as well, as stated in its Javadoc."

Using ``@Trial`` provides the lowest overhead.  Given that ``remove()`` is identical between both FastList.java and FastList2.java it provides an identical baseline.

If you are testing FastList without ``remove()`` you are inserting tens of thousands of elements, which as I commented before, is *way* outside of the intended use-case.  Connections with more than 32 *active unclosed* statements are extremely rare, so testing FastList with thousands of items is unrealistic compared to how it is used in HikariCP.

**Comment by xhumanoid** [comment]
yes, remove() identical, but what we test?
1) difference between try-catch vs explicit range check
2) difference of fully implementation.

if we do first point then we must localize work in add(), if we test second point then we cat keep remove().

```
Given that remove() is identical between both FastList.java and FastList2.java 
it provides an identical baseline.
```

baseline maybe identical, but real world disagree with you =(
because on java < 1.7.0_80 we have not very correct JIT optimization, as result:
1) FastList (new) have  inline add() and inline remove()
2) FastList2 (origin) have invocation add() and invocation remove()

as result we have fully incorrect results. 

p.s. my claim not in hikaricp code, i disagree with benchmark, because he work incorrectly and we can't use his for make decisions

**Comment by brettwooldridge** [comment]
@xhumanoid Ok, I can accept that reasoning.

I have committed my best shot at a fair JMH benchmark ([in github now](https://github.com/brettwooldridge/microbenches))

The benchmark uses the ``SingleShotTime`` mode with a large batchSize (100k) to get the most accurate result possible.  100k items will be inserted, but the FastList will be expanded during the warmup iterations.
```java
@State(Scope.Benchmark)
@Warmup(iterations=6, batchSize=10_000)
@Measurement(iterations=20, batchSize=100_000)
@BenchmarkMode(Mode.SingleShotTime)
@OutputTimeUnit(TimeUnit.NANOSECONDS)
```
And the core of the code:
```java
@Benchmark
public boolean testList() {
   return fastList.add(listImpl);
}
   
@Setup(Level.Trial)
public void trialSetup() {
   switch (listImpl) {
   case "base":
      this.fastList = new ArrayList<>(initCapacity);
      break;
   case "new":
      this.fastList = new FastList<>(String.class, initCapacity);
      break;
   case "orig":
      this.fastList = new FastList2<>(String.class, initCapacity);
      break;
   }
}

@Setup(Level.Iteration)
public void iterationSetup() {
   fastList.clear();
}
```
The result is nano-seconds per operation (*ns/op*), but the displayed result must be divided by the *batchSize* (100k).  I used a large block of memory to avoid too much garbage collection affecting the test.

Java 7 (7u60):
```
java -Xms1024m -Xmx1024m -jar target/benchmarks.jar -p listImpl=orig,new

Benchmark               (listImpl)  Mode  Cnt       Score       Error  Units
FastListBench.testList        orig    ss  200  529150.000 ± 25414.297  ns/op
FastListBench.testList         new    ss  200  508435.000 ± 24569.995  ns/op```

new  = 5.08 ns/op
orig = 5.29 ns/op
```
Java 8 (8u60):
```
java -Xms1024m -Xmx1024m -jar target/benchmarks.jar -p listImpl=orig,new

Benchmark               (listImpl)  Mode  Cnt        Score        Error  Units
FastListBench.testList        orig    ss  200   911417.670 ± 126689.301  ns/op
FastListBench.testList         new    ss  200   965170.075 ± 123119.717  ns/op

new  = 9.65 ns/op
orig = 9.11 ns/op
```
If this bencmark is to be trusted, and I believe it is the closest I can get, the *try-catch* is faster < 7u80, and the straight conditional is faster on > 7u80.

**Comment by xhumanoid** [comment]
Yes, in this version of benchmark I'm not see any mistakes and I agree with result.
Also results very similar on real numbers.
