### ISSUE TITLE
All hikaricp connection are in use and never recovery util restart

### ISSUE THREAD

**Issue by jilen** [brettwooldridge/HikariCP#467]
- HikariCP Version: 2.3.7
- Slick: 3.1.0
- mysql-connector-j: 5.1.30

[StackOverflow Link](http://stackoverflow.com/questions/33296016/all-hikaricp-connection-are-in-use)
Full log https://gist.github.com/jilen/f4edf44f4013ffe7a1eb

**Comment by brettwooldridge** [comment]
@jilen Did you get an answer for this in the Slick discussion group?

**Comment by jilen** [comment]
@brettwooldridge  No

**Comment by jilen** [comment]
Seems related to https://github.com/slick/slick/issues/1274

**Comment by kosakriszi** [comment]
I have this exact issue, but I am not using slick.

HikariCP: 2.4.3
mysql-connector-j: 5.1.14 (I have no control over this)

Hikari Debug Log: https://gist.github.com/kosakriszi/7bfca3f844bb6f4d7a47

What's interesting to me is that this issue only occurs when executing an SQL insert statement. All other cases seem to be functioning properly.

**Comment by jnehlmeier** [comment]
@kosakriszi are you sure your code closes connections correctly? AFAICT in HikariCP `active` means a connection is handed out of the pool and not yet returned to the pool by calling connection.close(). So `active` does not necessarily mean that SQL statements are currently executed on all these connections.

You can use the leakDetectionThreshold parameter to get stack traces in the log when a connection has been handed out too long compared to your average query duration. That way you can investigate your code to make sure it behaves correctly.

**Comment by kosakriszi** [comment]
@jnehlmeier Thanks for the reply! I am always sure to close my connections after each query, so I do not believe that that is the issue.

I will try out the leakDetectionThreshold parameter, and see what more information I can gather.

**Comment by kosakriszi** [comment]
I actually had a rouge connection that I wasn't closing, so my issue is invalidated.
