### ISSUE TITLE
spring boot HikariConfig->setJdbcUrl is not working

### ISSUE THREAD

**Issue by vitaliy-kuzmich** [brettwooldridge/HikariCP#469]
Hi 
url is null in mysql config
thanks

**Comment by vitaliy-kuzmich** [comment]
com.zaxxer:HikariCP:2.4.1
mysql:mysql-connector-java:5.1.37

**Comment by vitaliy-kuzmich** [comment]
it seems you forget to set url in addConnection in HikariPool

**Comment by brettwooldridge** [comment]
@vitaliy-kuzmich If you are using ``dataSourceClassName``-style configuration, you should not use ``setJdbcUrl()`` ... see the example [here](https://github.com/brettwooldridge/HikariCP/wiki/MySQL-Configuration).
