### ISSUE TITLE
How to get MySQL Percona Mariadb concrete version?

### ISSUE THREAD

**Issue by fjjiaboming** [brettwooldridge/HikariCP#470]
Do distinguish among them of all branches.

**Comment by brettwooldridge** [comment]
@fjjiaboming I don't understand the question.  This sounds more like a question for Percona, or on stackoverflow Re: MySQL.

**Comment by fjjiaboming** [comment]
I want to know which the app runs on MySQL by programming way .
Is it mysql-community , percona  or  mariadb ?

**Comment by brettwooldridge** [comment]
@fjjiaboming You're probably looking for the ``Connection.getMetadata()`` method.

**Comment by fjjiaboming** [comment]
Tomorrow, I will have a try.
