### ISSUE TITLE
Serialization issue when upgrade the version

### ISSUE THREAD

**Issue by chenrui333** [brettwooldridge/HikariCP#478]
We used HakariCP version 2.3.7 before, but since we used Java 8 in the app, so we did the upgrade to 2.4.1 for the app. And we also did upgrade for the Hibernate from 4.2.5 to 4.2.20 (due to javassist version, 4.2.20 use 3.18.1 javassist). 

But it turns out we have a bean serialization issue when talk to the server (server does use Hibernate 4.2.5, so do the other apps). 

HTTP Status 500 - Could not deserialize result from HTTP invoker remote service http://xxxx/xx/remoting/UserService; nested exception is java.io.InvalidClassException: org.hibernate.collection.internal.AbstractPersistentCollection; local class incompatible: stream classdesc serialVersionUID = -7238232378593030571, local class serialVersionUID = -8914173462748164853

Not sure what the reason behind, but we rollback to 2.3.7 for HikariCP and 4.2.5 for Hibernate for now.

**Comment by brettwooldridge** [comment]
@chenrui333 if you run HikariCP 2.4.1 with Hibernate 4.2.20.  I suspect the issue is the javassist version.  HikariCP no longer depends on javassist at runtime, so I doubt the issue is on HikariCP's side.

**Comment by chenrui333** [comment]
@brettwooldridge What info do you need me to provide? Thanks, Rui

**Comment by jnehlmeier** [comment]
Isn't that a typical Java serialization error? Basically the class `org.hibernate.collection.internal.AbstractPersistentCollection` has changed between Hibernate 4.2.5 and 4.2.20. As the app now uses Hibernate 4.2.20 and the server still uses Hibernate 4.2.5 (de)serialization will fail as the class has different serialVersionUID between app and server.

Since you do not need javassist for Hikari 2.4.x there is no need to update Hibernate in your app just to fulfill the javassist dependency. Just stay on 4.2.5 and it should work. If you want to upgrade Hibernate then you must upgrade your server too or use a serialization mechanism that is not based on Java's standard serialization.

**Comment by chenrui333** [comment]
@jnehlmeier OK, I will try to only upgrade HakariCP to see if it works. 
What changes cause this exception if there is Hibernate version difference between server and client?
Do you have some link reference? Really appreciate!

**Comment by brettwooldridge** [comment]
@chenrui333 The answer from @jnehlmeier is correct.  You cannot mix HIbernate 4.2.5 clients with Hibernate 4.2.20 servers.  All pieces on either side of the serialisation/deserialisation boundary must be on the same version of Hibernate.  This has nothing to do with HikariCP.

**Comment by chenrui333** [comment]
If we simply upgrade the HikariCP version, it leads to error:
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.persistence.EntityManagerFactory]: Factory method 'entityManagerFactory' threw exception; nested exception is java.lang.RuntimeException: error trying to scan <jar-file>: file:/xx/build/classes/main/
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189) ~[na:na]

Caused by: java.io.IOException: invalid constant type: 18
	at javassist.bytecode.ConstPool.readOne(ConstPool.java:1113) ~[na:na]
	at javassist.bytecode.ConstPool.read(ConstPool.java:1056) ~[na:na]
	at javassist.bytecode.ConstPool.<init>(ConstPool.java:150) ~[na:na]

Dependencies below:
+--- org.hibernate:hibernate-entitymanager:4.2.5.Final
|    +--- org.jboss.logging:jboss-logging:3.1.0.GA -> 3.1.1.GA
|    +--- dom4j:dom4j:1.6.1
|    +--- org.hibernate:hibernate-core:4.2.5.Final
|    |    +--- antlr:antlr:2.7.7
|    |    +--- org.jboss.logging:jboss-logging:3.1.0.GA -> 3.1.1.GA
|    |    +--- dom4j:dom4j:1.6.1
|    |    +--- org.jboss.spec.javax.transaction:jboss-transaction-api_1.1_spec:1.0.1.Final
|    |    +--- org.hibernate.javax.persistence:hibernate-jpa-2.0-api:1.0.1.Final
|    |    +--- org.hibernate.common:hibernate-commons-annotations:4.0.2.Final
|    |    |    \--- org.jboss.logging:jboss-logging:3.1.0.CR2 -> 3.1.1.GA
|    |    \--- org.javassist:javassist:3.15.0-GA
|    +--- org.jboss.spec.javax.transaction:jboss-transaction-api_1.1_spec:1.0.1.Final
|    +--- org.hibernate.javax.persistence:hibernate-jpa-2.0-api:1.0.1.Final
|    +--- org.hibernate.common:hibernate-commons-annotations:4.0.2.Final (*)
|    \--- org.javassist:javassist:3.15.0-GA

+--- com.zaxxer:HikariCP:2.4.1
|    \--- org.slf4j:slf4j-api:1.7.12

**Comment by brettwooldridge** [comment]
@chenrui333 This is a strange one.  HikariCP no longer needs javassist at runtime, so the Hibernate dependency on javassist 3.15.0-GA is being used for Hibernate.  In the older version of HikariCP, there was a dependency on javassist 3.18.0-GA, so probably that version of javassist was being used.

Make sure there is no older version of the HikariCP jar in the classpath, and if necessary add your own dependency on javassist 3.18.0-GA to your pom file to force Hibernate to use a newer version.

**Comment by chenrui333** [comment]
@brettwooldridge With manually enforce the javassist version, that resolves the issue. 
Thanks a lot.
