### ISSUE TITLE
proxy connection close and isClosed should be safer for multi threading

### ISSUE THREAD

**Issue by nitincchauhan** [brettwooldridge/HikariCP#481]
primary purpose of ClosedConnection was to protect method invocation on closed connection.
but it is also used as check if connection is closed or not.
Normally it is ok if check and set can happen as very first statement in close but unfortunately delegate can not be set as it is required later in method.
It would be better to separate by introducing volatile flag or atomic boolean for closed

**Comment by brettwooldridge** [comment]
Like #270 HikariCP does not support multithreaded access to a connection, and I do not wish to start doing so.  It is a slippery slope, and in truth the "fix" for #362 should probably be rolled back.

**Comment by nitincchauhan** [comment]
While you are correct technically, Users report it because the 'code' in 270 and 362 runs OK without HikariPool :) and this is likely to happen more with framework like Play with Scala (async operations) and it would take time to fix before user finds this or some well informed resource :)
