### ISSUE TITLE
Do I misunderstand minimumIdle ?

### ISSUE THREAD

**Issue by fjjiaboming** [brettwooldridge/HikariCP#483]
I set minimumIdle = 100 for pool .  But I found only 10 connections . 
I expect HikariCP keeps 100 idle connections so that I can see them by "show processlist".

version : 2.4.1
        <dependency>
            <groupId>com.zaxxer</groupId>
            <artifactId>HikariCP</artifactId>
            <version>2.4.1</version>
        </dependency>

**Comment by nitincchauhan** [comment]
if you set minimumIdle, you also need to set maximumPoolSize.

**Comment by fjjiaboming** [comment]
maximumPoolSize : How to do set it infinite?

**Comment by nitincchauhan** [comment]
presently, you can not set maximumPoolSize as infinite.
are you sure you need 100 'idle connections' ready to be served ?
It would be interesting to know your requirement: max number of concurrent users, hardware and database etc

**Comment by fjjiaboming** [comment]
so : 
   <property name="minimumIdle" value="100" />
   <property name="maximumPoolSize" value="0" />

100 'idle connections'  and maximumPoolSize is infinite.

**Comment by nitincchauhan** [comment]
set maximumPoolSize =100 too

**Comment by nitincchauhan** [comment]
I suggest you read https://github.com/brettwooldridge/HikariCP/wiki/About-Pool-Sizing

**Comment by fjjiaboming** [comment]
I know that . I understand the concepts about Concurrency vs Parallelism.
I have one special requirement . 100 idle conns pool is as killing-conn-pool when high flow and slow query as one pool with 10 idle conns .  
So killing-conn-pool can kill slow query very fast. The actions are immediate.

**Comment by fjjiaboming** [comment]
@nitincchauhan 

set maximumPoolSize =100 too , 

so it cann't have 101 conns in the pool ?

**Comment by nitincchauhan** [comment]
right. you will not have 101 connection in pool.

**Comment by fjjiaboming** [comment]
ok

**Comment by fjjiaboming** [comment]
I found 100 idle were gone after 300 seconds.  Why does not exist 100 idle conns appeared at MySQL-Server ?

**Comment by nitincchauhan** [comment]
pls post your configuration. better if you send few seconds of debug level log from hikaricp

**Comment by nitincchauhan** [comment]
if you can, pls test against 2.4.2.RC2

**Comment by fjjiaboming** [comment]
minimumIdle && maximumPoolSize  
Adding two options is OK.
