### ISSUE TITLE
Where is connection idleTimeout?

### ISSUE THREAD

**Issue by fjjiaboming** [brettwooldridge/HikariCP#485]
```
    <bean id="dataSource" class="com.zaxxer.hikari.HikariDataSource">
        <property name="jdbcUrl" value="jdbc:mysql://${db.ip}:${db.port}" />
        <property name="username" value="${db.username}" />
        <property name="password" value="${db.password}" />
        <property name="autoCommit" value="true" />
        <property name="connectionTimeout" value="${pool.connectionTimeout}" />
        <property name="validationTimeout" value="${pool.validationTimeout}" />
        <property name="idleTimeout" value="${pool.idleTimeout}" />
        <property name="minimumIdle" value="${pool.minimumIdle}" />
        <property name="maximumPoolSize" value="5000" />
        <property name="initializationFailFast" value="${pool.initializationFailFast}" />
        <property name="leakDetectionThreshold" value="${pool.leakDetectionThreshold}" />
    </bean>
```

```
pool.connectionTimeout=3000
pool.validationTimeout=1000
pool.idleTimeout=90000
pool.minimumIdle=100
pool.initializationFailFast=false
pool.leakDetectionThreshold=${mvn.pool.leakDetectionThreshold}
```

But I found connection idleTimeout is 300 seconds. Why not 90 seconds ?

**Comment by fjjiaboming** [comment]
After 300 seconds, I can not found idle connections in MySQL-Server....
Why?

**Comment by nitincchauhan** [comment]
Please read https://github.com/brettwooldridge/HikariCP/wiki/Configuration#frequently-used

**Comment by fjjiaboming** [comment]
@nitincchauhan  Yes, I have read it. 
But I can not find something about 300 seconds in the document. 
I configurate  idleTimeout= 90000 ms

**Comment by nitincchauhan** [comment]
pls post your configuration. better if you send few seconds of debug level log from hikaricp.
if you can, pls test against 2.4.2.RC2

**Comment by fjjiaboming** [comment]
```
        <dependency>
            <groupId>com.zaxxer</groupId>
            <artifactId>HikariCP</artifactId>
            <version>2.4.1</version>
        </dependency>
```

my configuration see the earliest comment.

**Comment by nitincchauhan** [comment]
1 test against 2.4.2.RC2
2 send debug level log of some 300+ seconds from hikaricp.
3 check time out values in mysql

**Comment by fjjiaboming** [comment]
I found both idleTimeout and maxLifetime is ok. 

maxLifetime > idleTimeout

**Comment by nitincchauhan** [comment]
wondering what changes you made to have expected behavior (300 vs 90 sec) ?

from your config:
idleTimeout is 90 seconds
and default maxLifetime is 30 minutes

**Comment by fjjiaboming** [comment]
Now :  
idleTimeout=90000
maxLifetime=123000

so that it keeps 100 connections forever in MySQL-Server.

**Comment by fjjiaboming** [comment]
I want 90 sec idle-timeout connections.

**Comment by nitincchauhan** [comment]
you mean you got 90 sec idle timeout with setting idleTimeout=90000 and maxLifetime=123000 and no other change?

**Comment by fjjiaboming** [comment]
you mean you got 90 sec idle timeout with setting idleTimeout=90000 and maxLifetime=123000 .

yes.

**Comment by nitincchauhan** [comment]
I think you are misinformed.
idleTimeout is to close connection if not borrowed (staying idle in pool) till this duration
maxLifetime is to close connection after this duration

**Comment by fjjiaboming** [comment]
I know what you said.

**Comment by brettwooldridge** [comment]
@fjjiaboming Without a debug log covering ~130 seconds, it is impossible to tell if this is an error by the pool.  If the application is active, an idle connection that is retired may be quickly replaced.  The status logged by the housekeeper thread every 30 seconds is not accurate enough to show what is occuring between the housekeeper runs.

However, debug logging in current versions of HikariCP should log everytime a connection is retired, and the reason.

Again, if the application has some background activity, then connection may never reach idle state for long enough to be retired *as idle*.  However, they surely will be retired before they reach maxLifetime.  The maxLifetime is not an exact number, because some random variance is added to ensure that too many connections are not retired at one time.
