### ISSUE TITLE
Tomcat JNDI Configuration too many connections

### ISSUE THREAD

**Issue by wesoos** [brettwooldridge/HikariCP#487]
When setting this up as a tomcat jndi resource, the minimum number of pool connections are created for every webapp in tomcat.  For instance, if I set the minimum number of connections property to 5, and I have 10 webapps, it will create 50 connections on startup.  I actually have 3 jndi resources to 3 different databases on the same mysql server, with 16 webapps.  So on startup, it creates 3 x 5 x 16 = 240 connections.  I have my max_connections setting in MySQL set to 200, so the last few webapps fails to load...

**Comment by brettwooldridge** [comment]
@wesoos Then you'll need to set ``minimumIdle`` to a lower number, even 0.  We have users with literally thousands of pool instances pointed at the same DB who use this configuration.

**Comment by wfairc** [comment]
You might consider setting up a shared pool. See item 6 here: https://examples.javacodegeeks.com/enterprise-java/tomcat/tomcat-connection-pool-configuration-example/
