### ISSUE TITLE
Please enlighten me about connection close and sizes

### ISSUE THREAD

**Issue by cinlung** [brettwooldridge/HikariCP#490]
Dear Brett

I am a newbie in connection pool. I want to ask about Connection close() method. I read from your other posting that calling the close() is actually only disconnect the logical reference to the real Connection inside the pool.

Do I need to set the conn reference I used to null to make sure it does not have any hidden overhead?

For example: 
HikariDataSource ds = ...... (codes here);
Connection c = ds.getConnection();
c.close();
c = null; //--> Does this help do anything? or the c.close() is enough?

Also, one nice thing I used to use in other DB Pool is that I am able to find out number of leased connections and idle connections in the pool. Is there a way to do this with HikariCP?

Thank you

**Comment by brettwooldridge** [comment]
You don't need to set the connection reference to null.  Java will handle the reference garbage collection like any other object.  The reference is only a reference to HikariCP's ConnectionProxy object anyway, not the true Connection.

If you want to monitor pool statistics, see the [JMX page](https://github.com/brettwooldridge/HikariCP/wiki/MBean-(JMX)-Monitoring-and-Management) and/or the [Dropwizard Metrics](https://github.com/brettwooldridge/HikariCP/wiki/Dropwizard-Metrics) page.

**Comment by cinlung** [comment]
Thank you for your Info Brett
