### ISSUE TITLE
Postgresql stringtype property

### ISSUE THREAD

**Issue by niquola** [brettwooldridge/HikariCP#494]
Hi,

How can i set `stringtype` property of PostgreSQL connection?

https://jdbc.postgresql.org/documentation/83/connect.html

**Comment by brettwooldridge** [comment]
Should be as simple as using ``addDataSourceProperty("stringtype", "varchar")`` if using programmatic configuration, or using ``dataSource.stringtype=varchar`` if using property file-based configuration.
