### ISSUE TITLE
Hibernate + HikariCP + JNDI

### ISSUE THREAD

**Issue by wesoos** [brettwooldridge/HikariCP#498]
Yesterday my system froze up and I found the following error in the logs:

Caused by: java.sql.SQLTransientConnectionException: HikariPool-0 - Connection is not available, request timed out after 303060ms.
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:213)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:163)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:85)
	at org.hibernate.ejb.connection.InjectedDataSourceConnectionProvider.getConnection(InjectedDataSourceConnectionProvider.java:70)
	at org.hibernate.internal.AbstractSessionImpl$NonContextualJdbcConnectionAccess.obtainConnection(AbstractSessionImpl.java:301)
	at org.hibernate.engine.jdbc.internal.LogicalConnectionImpl.obtainConnection(LogicalConnectionImpl.java:214)
	... 174 more

I use hibernate with a jndi configuration.  The following is my tomcat jndi configuration:

   <Resource name="jdbc/datasource"
        auth="Container" 
	factory="com.zaxxer.hikari.HikariJNDIFactory" 
        type="javax.sql.DataSource" 
        maximumPoolSize="20"
        connectionTimeout="300000"
        dataSourceClassName="com.mysql.jdbc.jdbc2.optional.MysqlDataSource"
        dataSource.url="jdbc:mysql://mysqlurl"
        dataSource.user="user" 
        dataSource.password="pwd" 
/>

So I started reading your wiki and found I have to set the following in my hibernate configuration:

hibernate.connection.provider_class=org.hibernate.hikaricp.internal.HikariCPConnectionProvider

So I added that as well as change my hibernate version to 4.3.11 and I added the hibernate-hikaricp dependency.

Now I get the following error in the logs on tomcat start:

Caused by: java.lang.IllegalArgumentException: one of either dataSource or dataSourceClassName must be specified
        at com.zaxxer.hikari.AbstractHikariConfig.validate(AbstractHikariConfig.java:777)
        at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:73)
        at org.hibernate.hikaricp.internal.HikariCPConnectionProvider.configure(HikariCPConnectionProvider.java:71)
        ... 44 more

Can you please let me know what I am doing wrong or what I should change?  Is hikaricp+hibernate+jndi not supposed to be used?

Wessel

**Comment by wesoos** [comment]
Brett, any thoughts on this?

**Comment by brettwooldridge** [comment]
Sorry for the delay on this, it's the middle of the night here (Tokyo), so I'll have to take a look at this tomorrow.  I know that Hibernate and the HikariCPConnectionProvider map some hibernate properties (likely the datasource class name) into HikariCP properties ... rather than using the HikariCP properties directly.

When you throw JNDI into the mix, it gets trickier.  I think you would configure HikariCP through JNDI, and then somehow tell Hibernate to lookup the datasource (in JNDI) rather than specifying a similar or duplicate configuration.

Take a look [at this page](http://www.journaldev.com/2905/hibernate-tomcat-jndi-datasource-example-tutorial).  This bit seems like a critical part of the Hibernate configuration (looking up the datasource):
```xml
<property name="hibernate.connection.datasource">java:comp/env/jdbc/MyLocalDB</property>
```

**Comment by wesoos** [comment]
Thanks Brett,

I have it all working with JNDI by simply setting the factory to HikariCP.  But I am concerned that not all properties are being set for hibernate with HikariCP with that approach.  So that's why I tried the HikariCPConnectionProvider approach and upgraded my Hibernate version.  But with setting that property I get the errors above.  Is it not advisable to use JNDI?

Wessel

**Comment by brettwooldridge** [comment]
I think your original configuration (using JNDI) is fine.  I would suggest configuring the ``leakDetectionThreshold``.  And enabling DEBUG level logging.  HikariCP is not noisy at DEBUG, but you can get quite a bit more data about what is going on.

**Comment by wesoos** [comment]
Thanks Brett,

That was another question I had.  What do I need to include for HikariCP logging?

Wessel

**Comment by brettwooldridge** [comment]
@wesoos That is going to depend on your logging framework (log4j, slf4j, etc).  Basically, you want to enable DEBUG level logging for the ``com.zaxxer.hikari`` package.

**Comment by wesoos** [comment]
Great thx!

**Comment by wesoos** [comment]
Hi Brett, did you have a chance to look into my original question some more?

Also, I can't figure out how to configure the logging, with the HikariCP being set with jndi.  At what level of tomcat do I need to change which log properties file?

**Comment by brettwooldridge** [comment]
Sorry, after your "Great thx" I thought you had figured it out.  This is really a Tomcat question.  HikariCP itself has no logging properties, it depends on slf4j.  There are slf4j bindings for every major logging framework.

Basically, wherever Tomcat logging is configured (for Tomcat) would be the same file where you would enable logging for HikariCP.

**Comment by calvernaz** [comment]
I had the same issue (I think) but I end up solving it.

Scenario
=
  - Tomcat
  - Spring
  - Hibernate

Configuration
=
In server.xml:
```
<Resource name="jdbc/xxxDataSource"                                                               
              type="javax.sql.DataSource"                                                               
              factory="com.zaxxer.hikari.HikariJNDIFactory"                                             
              auth="Container"                                                                          
              username="xxx"                                                                            
              password="xxxxxxx"                                                                       
              jdbcUrl="jdbc:oracle:thin:@ip_address:1521:pbdev"                                      
              driverClassName="oracle.jdbc.driver.OracleDriver"                                         
              minimumIdle="10"                                                                            
              maximumPoolSize="10"    
/>
```
In context.xml:
```
<ResourceLink name="jdbc/xxxDataSource"                                                            
                global="jdbc/accessDataSource"                                                          
                auth="Container"                                                                        
                type="javax.sql.DataSource" />
```
Without the configuration above, in separate files, the connection pool size was being ignored and end up using all connections available and timing out after that. I could prove it querying database for open sessions.

```
 SELECT USERNAME, count(USERNAME)
  FROM v$session where OSUSER = 'myuser' GROUP BY USERNAME;
```

At this stage, I got 20 open/inactive connections as expected.

Needless to say, your Spring bean configuration should point to the JNDI declared above.

```
  <bean id="dataSource" class="org.springframework.jndi.JndiObjectFactoryBean">
    <property name="jndiName" value="java:/comp/env/jdbc/prizeBondsDataSource"/>
  </bean>
```
