### ISSUE TITLE
Running custom statement on connection returning to pool

### ISSUE THREAD

**Issue by Tostino** [brettwooldridge/HikariCP#503]
Was wondering if there was a way to run a certain statement when returning a connection to the pool?  I was wanting to run the Postgres DISCARD ALL: http://www.postgresql.org/docs/9.4/static/sql-discard.html because I have a need for advisory locks in my application, and would love for this to be handled by the connection pool rather than having a layer inbetween do it.

**Comment by brettwooldridge** [comment]
@Tostino What about using the ``InterceptorDataSource`` and ``InterceptorConnection`` classes from [this gist](https://gist.github.com/brettwooldridge/7564827e45d67e1dc8dd).  You would change the ``InterceptorConnection`` to only trap the ``close()`` method, rather than ``createStatement()`` and ``prepareStatement()``, and could invoke your DISCARD ALL there.

**Comment by jhatcher9999** [comment]
FYI....I tried this and it worked:
```
   public Object invoke(Object proxy, Method method, Object[] args) throws Throwable {
        switch (method.getName()) {
//            case "createStatement": {
//            //Statement stmt = (Statement) method.invoke(delegate, args);
//            return InterceptorStatement.wrapInterceptor(stmt, Statement.class);
//            }
//            case "prepareStatement": {
//                // First argument is always SQL
//                PreparedStatement stmt = (PreparedStatement) method.invoke(delegate, args);
//                return InterceptorStatement.wrapInterceptor(stmt, (String) args[0], PreparedStatement.class);
//            }
            case "close": {
                Statement stmtReset = delegate.createStatement();
                stmtReset.execute("DISCARD ALL;");
                return method.invoke(delegate, args);
            }
            default: {
                return method.invoke(delegate, args);
            }
        }
    }
```
