### ISSUE TITLE
turn off logging

### ISSUE THREAD

**Issue by vicApakau** [brettwooldridge/HikariCP#505]
Hi, the default is to log a lot. 
How do I make it less?
Something like:
log4j.logger.com.zaxxer.hikari=ERROR

**Comment by brettwooldridge** [comment]
@vicApakau Are you saying even at INFO level HikariCP is logging too much?

**Comment by awildturtok** [comment]
I'm facing a similar problem currently, as any logging by HikariCP interfers with data parsing in R. And I don't seem to manage to deactivate it, neither with a properties file, nor by forcing it in code.

Is there any other way around that?

**Comment by brettwooldridge** [comment]
How you configure logging has nothing to do with HikariCP.  Some users use java.util.logging, some log4j, some log4j2, some logback, etc.  Each as a different way of configuring log levels.  If for some reason you cannot suppress HikariCP logs, it is absolulely a logging configuration issue, not a HikariCP issue.
