### ISSUE TITLE
Not getting big diff between hikaricp & dbcp2.

### ISSUE THREAD

**Issue by megaurav88** [brettwooldridge/HikariCP#508]
@brettwooldridge I didn't get any big difference between hikaricp & dbcp2. Kindly can you let me know how to get better performance 
jdk1.8
mysql Ver 14.14 Distrib 5.6.27,
hikaricp version 2.4
HikariPool-0 - configuration:
allowPoolSuspension.............false
autoCommit......................false
catalog.........................
connectionInitSql...............
connectionTestQuery.............
connectionTimeout...............30000
dataSource......................
dataSourceClassName.............com.mysql.jdbc.jdbc2.optional.MysqlDataSource
dataSourceJNDI..................
dataSourceProperties............{user=root, password=, url=jdbc:mysql://localhost:3306/db, prepStmtCacheSqlLimit=250, cachePrepStmts=true, prepStmtCacheSize=2048}
driverClassName.................
healthCheckProperties...........{}
healthCheckRegistry.............
idleTimeout.....................600000
initializationFailFast..........false
isolateInternalQueries..........false
jdbc4ConnectionTest.............false
jdbcUrl.........................
leakDetectionThreshold..........0
maxLifetime.....................1800000
maximumPoolSize.................100
metricRegistry..................
metricsTrackerFactory...........
minimumIdle.....................10
password........................
poolName........................HikariPool-0
readOnly........................false
registerMbeans..................false
scheduledExecutorService........
threadFactory...................
transactionIsolation............
username........................
validationTimeout...............5000

stats:

HikariCP Performance 
Query/Connection ----------->  in ms time
Connection | 100 | 10K | 100K 
| 1 | 73 | 843 | 6186
| 10 | 68 | 2607 | 25064
| 100 | 350 | 21777 | 223175 | 
DBCP Performance
Query/Connection ----------->  in ms time
Connection | 100 | 10K | 100K 
| 1 | 274 | 881 | 6560
| 10 | 87 | 2811 | 24465 ms
| 100 | 317 | 22945 | 229194 ms

**Comment by nitincchauhan** [comment]
@megaurav88 probably you missed reading this: https://github.com/brettwooldridge/HikariCP/wiki/%22My-benchmark-doesn't-show-a-difference.%22
also, for comparison, specify configuration of both.
