### ISSUE TITLE
Connection not available for jdbc ResultSetMetaData

### ISSUE THREAD

**Issue by danjee** [brettwooldridge/HikariCP#510]
I am using the Hikari connection pool in my application. Some collections I used are loaded from the resultset metada (the column names of some tables). Here the Hikari datasource fails in releasing the connection for other services to use it. 
Example:
```java
public List<String> getColumnsOfTable(final String table) throws AppException {
		final List<String> retval = new ArrayList<String>();
		final String sql = "SELECT * FROM " + table + " WHERE 1=2";
		try (Connection con = getConnection();
				PreparedStatement stm = con.prepareStatement(sql);
				ResultSet rs = stm.executeQuery()) {
			final ResultSetMetaData rsMeta = rs.getMetaData();
			for (int i = 1; i <= rsMeta.getColumnCount(); i++) {
				retval.add(rsMeta.getColumnName(i));
			}
		} catch (final Exception e) {
			throw new AppException(e);
		}
		return retval;
	}
```
```xml
<dependency>
	<groupId>com.zaxxer</groupId>
	<artifactId>HikariCP</artifactId>
	<version>2.4.1</version>
</dependency>
```
I've tried this code with BoneCP with the same ojdbc driver and this seems to work there, so I guess it's not a driver issue.

**Comment by danjee** [comment]
The strange thing is that this happens when I use `dataSource.setMaximumPoolSize(1);` property. If I set it to 2 the sql runs OK and it runs many times not just once. Also I still see the connection as active even after one minute of idle time. `dataSource.setIdleTimeout(60000);`

**Comment by brettwooldridge** [comment]
If ``minimumIdle`` is not set, then it defaults to ``maximumPoolSize``.   So, even if ``idleTimeout`` is set to 1 minute, as soon as the connection is closed it will be replaced in the pool.

If you want the pool to shrink, you need to set ``minimumIdle`` to something below ``maximumPoolSize``.

I recommend turning on DEBUG level logging, so you can see exactly what is happening in the pool regarding connections.
