### ISSUE TITLE
performance degragation - too many getAutoCommit calls

### ISSUE THREAD

**Issue by avishayh** [brettwooldridge/HikariCP#512]
Hi, we switch to Hikari in production and received a performance degragation in out application , 
the DB server's cpu jumped by 15% for the same application/same sql's.
Our DB is sybase 15 and we are using a jdbc jconnect driver.
After investigating all the sql/packets (using Wireshark) that the AS sends to DB
,we saw major increase in 'select @@trancount' statements which comes from the Connection.getAutoCommit() calls.
After looking inside the source codeof hikari , we saw the you have a com.zaxxer.hikari.proxy.ConnectionProxy class which wraps all connections to the DB and on every close() method it check's if the underline (delegate) connection has an open transaction using getAutoCommit() incase it is left open and then rollback
code snippet:
 try {
            if (isCommitStateDirty && !delegate.getAutoCommit()) {
               delegate.rollback();
            }

So we think the CPU change has something to do with the overhead of the new statements. 
Is it possible to override/change the behavior of this code (maybe a flag which can disable this check) ?

from what I understand this code is a "saver hook" in-case someone left a transaction opened.
but in our case all transaction are opened/close via transacionManager via AOP and not by application open/close transaction calls, so this code is irelevant but expensive.

**Comment by billoneil** [comment]
This may not answer your exact question but take a look here https://github.com/brettwooldridge/HikariCP/wiki/%22My-benchmark-doesn't-show-a-difference.%22

specifically https://github.com/brettwooldridge/HikariCP/wiki/%22My-benchmark-doesn't-show-a-difference.%22#what-does-correctness-and-reliability-mean

**Comment by brettwooldridge** [comment]
@avishayh If ``autoCommit=false`` then HikariCP is going to track "dirty commit state".  If your code executes SQL (of any kind), but does not call ``Connection.commit()`` or ``Connection.rollback()`` then HikariCP is going to consider that the connection transaction state is dirty.  Therefore, when the connection is closed, *if* the state is still dirty, it will execute a rollback operation.

I'm not sure what version you are using, but in release 2.4.x the implementation changed.  The latest release (2.4.2) looks [like this](https://github.com/brettwooldridge/HikariCP/blob/HikariCP-2.4.2/src/main/java/com/zaxxer/hikari/pool/ProxyConnection.java#L231), which should be considerably more efficient and avoid a roundtrip to the database.

**Comment by avishayh** [comment]
I was using the 2.3.X version because of several java 6 run-time servers.
but I will look at the 2.4 version as well, it looks like the latest release solves the overhead of getAutoCommit() calls.
Is it possible to use it on a java 6 runtime ?

**Comment by brettwooldridge** [comment]
@avishayh I have back-ported the change to 2.3.x.  Can you checkout the ``2.3.x`` branch, build and test the Java 6 artifact and let me know if it addresses the performance issue?  If so, I can make a 2.3.13 release.

**Comment by avishayh** [comment]
Tks, I haven't tested it yet, but it looks OK  (no calls to getAutoCommit)
2.3.13 will be great !

BTW, you can think about an extended feature which overrides the getAutoCommit method and instead of using the underline getAutoCommit which creates a DB request (select @@trancount) 
just return a cached value (you already know who "setAutoCommit").

In our case we started monitoring this calls (because of the performance issues in prod), and realized hibernate (old 3.6.2 version) use this method ALLOT on every query/criteria call - even few times per query (you can see it in hibernate classes JDBCContext & ConnectionManager) . This also caused a bump in the CPU (few extra million calls to DB per day in our case)

**Comment by brettwooldridge** [comment]
@avishayh We will take it under consideration.  In general we have a policy of not interfering with calls made by the user to the driver.  However some drivers, like MySQL, themselves have an option to cache the auto-commit state and avoid the DB roundtrip.  You may wish to check your driver and/or request such a feature, pointing out its availablity in competing databases.
