### ISSUE TITLE
How to disable any data source resource during startup in tomcat or tcServer

### ISSUE THREAD

**Issue by mahendya** [brettwooldridge/HikariCP#515]
In TcServer or Tomcat, The resources which we create are loaded during started. is there any way to stop any resource during startup.
Actually i have two data source resources with two different connection pooling.
want to enable one at a time. please help.

Thanks in advance.

**Comment by brettwooldridge** [comment]
@mahendya This is a question better asked on stackoverflow.com

**Comment by ozkanpakdil** [comment]
@mahendya did you ask it in SO ? I am also looking for same thing.
