### ISSUE TITLE
metrics: total borrowed/created connections

### ISSUE THREAD

**Issue by abiacco** [brettwooldridge/HikariCP#518]
I'm testing a move from dbcp2 to hikari. Thanks for writing another alternative for pooling.
In dbcp2 i've been monitoring my pools via JMX for borrowedCount (the amount of times connections have been borrowed/used) and createdCount (the amount of times a connection is created).
These are running counts, and i do deltas on the counts for my monitoring.
I'm wondering if we can get something like this in Hikari.
Thanks.

**Comment by brettwooldridge** [comment]
@abiacco What does the delta of these two values tell you?  I.e. how is that metric informative?

**Comment by brettwooldridge** [comment]
@abiacco You can get *one* of those values, the number of times connections have been used.  If you enable [Dropwizard Metrics](https://github.com/brettwooldridge/HikariCP/wiki/Dropwizard-Metrics), the "pool.Usage" metric is a ``com.codahale.metrics.Histogram``, which has a ``count`` value indicating the number of borrow/return pairs.

We don't track the number of connection creation events.  I am still curious how the delta of these two values is useful for monitoring.

**Comment by samhendley** [comment]
+1 for number of creation events. By monitoring that counter I am able to determine that we are creating and dropping more connections than I expect.  It is a hugely useful counter to have.

**Comment by samhendley** [comment]
Are you opposed to this being added? I am working on a PR that will fix the pool overfill issue and this is really the metric I need to verify that the fix is working correctly

**Comment by brettwooldridge** [comment]
Send a pull and we'll take a look.

**Comment by brettwooldridge** [comment]
@abiacco @samhendley In HikariCP v2.6.0 there is a new DropWizard/Prometheus metric for connection creation.  In DropWizard, the metric is called ``<poolname>.pool.ConnectionCreation``. In Prometheus, the metric is ``hikaricp_connection_creation_millis``.
