### ISSUE TITLE
Is it possible to force return/reset of all borrowed connections

### ISSUE THREAD

**Issue by patric-r** [brettwooldridge/HikariCP#520]
Question:
Is it possible to force return/reset of all borrowed connections back to the pool?
This could be useful in some unit test scenarios, e.g. executed after each test.

**Comment by brettwooldridge** [comment]
@patric-r You have two options.  One is to try soft-eviction [through the MBean](https://github.com/brettwooldridge/HikariCP/wiki/MBean-(JMX)-Monitoring-and-Management).  The other is to simply shutdown the pool at the end of each test.  HikariCP's own unit tests startup and shutdown the pool many dozens of times during a test run.
