### ISSUE TITLE
release/close active oracle connection after broken query

### ISSUE THREAD

**Issue by guidobonerz** [brettwooldridge/HikariCP#521]
Hi, i've the following problem.

In my application i have to use the following code:
EntityManagerFactory emf = Persistence.createEntityManagerFactory("persistenceUnit");
EntityManager em = emf.createEntityManager();
Session  session = em.unwrap(Session.class);
SessionFactoryImplementor sfi = (SessionFactoryImplementor) session.getSessionFactory();
ConnectionProvider cp = sfi.getConnectionProvider();
Connection connection = cp.getConnection();

When i execute an invalid sql-statement an exception is thrown.
so far so good.

But after executing
connection.close();
session.close();

the connection still remains active in the pool and will never been cleaned up.

When i use
session.doWork(new Work
{
execute(Connection connection)
{
// some code
}
}
);
session.close();

everything works fine. but in this special case i can't go this way.

í'm using hikaricp 2.4.2 ,spring 4.0.7, hibernate 4.3.11 final
Any ideas?

**Comment by brettwooldridge** [comment]
@guidobonerz Can you enable debug logging and post the section of the log here?  This sounds like a Hibernate setting issue to me.  I also recommend asking this on stackoverflow.com, you'll probably get a faster solution.  Trust me, HikariCP doesn't have such trivial bugs, so it is almost certainly a Hibernate configuration issue.

**Comment by brettwooldridge** [comment]
@guidobonerz Any update on this issue?
