### ISSUE TITLE
Leak detection error? 

### ISSUE THREAD

**Issue by TrpkGod** [brettwooldridge/HikariCP#522]
Recently we've switched over to using HikariCP and it's alot better than our previous connection pool; however when I was setting up the config I've ran into this error and can't seem to figure out the problem.

Error we are receiving (if you need the full stacktrace, let me know): 
```
[21:03:02] [Hikari housekeeper (pool Archyric - Pool #1)/WARN]: Connection leak detection triggered for connection com.mysql.jdbc.JDBC4Connection@5fb33dc0, stack trace follows
java.lang.Exception: Apparent connection leak detected
```

Our configuration:
```java
HikariConfig config = new HikariConfig();

config.setJdbcUrl("jdbc:mysql://" + host + ":" + port + "/" + name);
config.setDriverClassName("com.mysql.jdbc.Driver");
config.setUsername(user);
config.setPassword(pass);

config.setConnectionTimeout(30000);
config.setAutoCommit(true);
config.setInitializationFailFast(true);
config.setIdleTimeout(180000);
config.setMaxLifetime(1800000);
config.setLeakDetectionThreshold(15000);
config.setMaximumPoolSize(20);
config.setPoolName("Archyric - Pool #1");

source = new HikariDataSource(config);
```

Thanks,
  TrpkGod

**Comment by nitincchauhan** [comment]
@TrpkGod it is warning that says client have not returned borrowed connection within set time for 'leak detection threshold'. (in your case it is set to 15000ms). you may have genuine leak that is connection is not closed 'properly'. or method / sql executed by connection  takes longer than threshold. stack trace leads you to connection having problem.

**Comment by TrpkGod** [comment]
@nitincchauhan Ah yes, thank you very much. We have fixed the problem with this issue, we forgot to close the connection with one our methods.
