### ISSUE TITLE
Add the ability for a connection customizer

### ISSUE THREAD

**Issue by jeremymefford** [brettwooldridge/HikariCP#523]
I really would like to enable the JDBC driver layer of statement caching for Oracle.  The only issue is that according to https://docs.oracle.com/cd/E18283_01/java.112/e16548/stmtcach.htm i have to set the statementCacheSize on the physical connection object checked out.  On the dataSourceClass i can enable implicit caching, but it does no good if i cannot set the size of the cache on each connection checked out.

```Java
((OracleConnection)conn).setStatementCacheSize(10);
```

I looked at doing a subclass of the HikariDataSource, but this seems inefficient since that will be returning the same connections over and over.  What i am looking for is a connection initializer that can be run once on each connection checkout.  This would behave very similar to how c3p0 does ConnectionCustomizer classes (see http://www.mchange.com/projects/c3p0/).

I would need access to the raw connection dataSourceClass since i need to set the properties directly on that connection (another problem with a subclass of HikariDataSource since it is proxied).

I would like the ability to pass in an instance of the ConnectionInitializer (or Customizer) interface to the HikariConfig class. 

My rough thought of an implementation could be as simple as this:

```Java
public interface ConnectionInitializer {
    void initialize(Connection conn);
}
```

**Comment by jnehlmeier** [comment]
You can use HikariConfig.setDataSource() to give Hikari a custom datasource that will be used to obtain connections to fill the pool. In that custom datasource you can configure the connection, before it is managed by the pool.

**Comment by jeremymefford** [comment]
@jnehlmeier Managing that dataSource is one of the major reasons for my using a connection pool.  maybe i'm missing something, but wouldn't that require quite a bit of work?

**Comment by jnehlmeier** [comment]
Well normally the JDBC driver provides a simple datasource implementation that you can wrap to intercept the getConnection() call. So it should only be a few lines of code to configure your connections before Hikari manages them.

**Comment by jeremymefford** [comment]
@jnehlmeier okay, after looking into this more, i stand corrected.  this is what i have settled on that appears to be working well:

This is a Spring Boot 1.3.0.RELEASE project 
### DataSourceConfig.java
```Java
    @Primary
    @Bean(destroyMethod = "close", name = "dataSource")
    public HikariDataSource dataSource() throws SQLException {
        OracleStatementCachingDataSource dataSource = new OracleStatementCachingDataSource(statementCacheSize);
        dataSource.setImplicitCachingEnabled(true);
        dataSource.setUser(jdbcUser);
        dataSource.setPassword(jdbcPassword);
        dataSource.setURL(jdbcUrl);

        HikariConfig config = new HikariConfig();
        config.setDataSource(dataSource);
        config.setPoolName("MY_POOL");
        config.setConnectionTimeout(checkOutTimeout);
        config.setMaximumPoolSize(maxPoolSize);
        return new HikariDataSource(config);
    }
```
### OracleStatementCachingDataSource.java
```Java
public class OracleStatementCachingDataSource extends OracleDataSource {
    private final int statementCacheSize;

    public OracleStatementCachingDataSource(int statementCacheSize) throws SQLException {
        this.statementCacheSize = statementCacheSize;
    }

    @Override
    public Connection getConnection() throws SQLException {
        Connection conn = super.getConnection();
        ((OracleConnection) conn).setStatementCacheSize(statementCacheSize);
        return conn;
    }

    @Override
    public Connection getConnection(String user, String pass) throws SQLException {
        Connection conn = super.getConnection(user, pass);
        ((OracleConnection) conn).setStatementCacheSize(statementCacheSize);
        return conn;
    }
}
```
