### ISSUE TITLE
Logging support for OSGi through LogService

### ISSUE THREAD

**Issue by joebrassi** [brettwooldridge/HikariCP#524]
Currently HikariCP uses explicitly the library **slf4j** to send log information to the console. But under OSGi we use the service **LogService** from the OSGi Framework to send all logs.

This non-use of **LogService** causes problems under OSGi applications where all log information is routed through **LogService**, because all those logs that are not sent through that service are simply ignored for LogFile and DatabaseLog outputs and only processed by the console.

A feasible solution for this small issue would be to create a small _Activator_ class (used for all OSGi bundles) where the HikariCP bundle checks the OSGi framework for the availability of the **LogService** implementation and use it if found. In case it is not found, there is no need to check whether the **LogService** instance is null or not, because this service in particular does not throw exceptions for service implementation not found.

**Comment by brettwooldridge** [comment]
We have quite a lot of experience with OSGi containers.  It is quite easy to provide a bundle that exports slf4j APIs.  And equally simple for that bundle to bridge slf4j to LogService.  In fact I would be willing to bet such a bridge already exists.

**Comment by joebrassi** [comment]
Yes, there are some bridges around from Slf4j to LogService, but that is more like a workaround, don't you think? wouldn't it be better to have a sort of **hirakicp-bundle-2.4.3.jar** file to solve it. This way we avoid the overhead of having the log to travel through multiple Log Frameworks to finally get to the LogService, and of course to also avoid the addition of the slf4j bundle to the OSGi Framework which is not necessary.

Anyways, if you need any help with the task, I am willing to help you with it if you can publish a hirakicp bundle for osgi and get rid of the slf4j.

**Comment by jnehlmeier** [comment]
@joebrassi The whole point of using SLF4J in a library is to actually not get rid of it but to allow anyone to use a SLF4J binding that fits their needs. In your case it would be a binding to LogService. Also what do you do if you start using a second library using SLF4J? And then a third? A binding will fix your issue for any library.

**Comment by joebrassi** [comment]
Currently I have about 50 libraries in my OSGi compilation (database drivers, webserver, jaxws, etc, etc.) and happens that HikariCP is the only one that uses explicit dependency to SLF4J. All other modules use LogService or they log directly to _java.util.logging.Logger_ which forwards the log to SLF4J or LOG4J _if available_. This way they don't keep any dependency to any specific Logging framework and let the developer choose what Logging framework to use and this is what I am looking for, that HikariCP can let me choose the Logging framework or better said to OSGi-fy HikariCP.

**Comment by brettwooldridge** [comment]
The problem with choosing jul is that it is no better than choosing log4j ... it locks the user into a single framework. The point of slf4j is to provide a neutral framework that allows the user to choose the binding.  slf4j provides much nicer source level features like variable substitution without string concatenation.  I have no interest in creating two jar distros just to remove the slf4j requirement, particularly when it already has bindings for every major (and some minor) loggers.

**Comment by joebrassi** [comment]
Yes, perhaps creating two jar distros may not be the solution, but have you considered in using java.util.logging.Logger instead of SLF4J?

**Comment by brettwooldridge** [comment]
@joebrassi I have not considered it.  SLF4j provides too many conveniences, such as removing the need to bracket debug logging with ``if (logger.isDebugEnabled())`` statements all over the code, and more powerful string substitution semantics that avoid a bunch of concatenation in the code.
