### ISSUE TITLE
evict broken connection instead of release to pool

### ISSUE THREAD

**Issue by ChinaXing** [brettwooldridge/HikariCP#528]
I'm use Hikari jdbc connection pool.

when execute statement witch produce an exception ( for example by network is broken). as following:

```
try{
   Connection con = pool.getConnection();
   con.executeQuery("....");
}catch(Exception e){
   con.close();
}
```
does con.close will evict the broken connection, instead of release it to the pool.

if the broken connection is released to pool. it maybe got by following request of getConnection.

https://github.com/brettwooldridge/HikariCP/blob/dev/src/main/java/com/zaxxer/hikari/pool/HikariPool.java#L171

the code linked here,  have a alive check when getConnection:

but if lastAccess - now < 1s, the alive check will not be done.

does this a bug ?

**Comment by slyoldfox** [comment]
Apart from your question, shouldn't you consider using a try-with-resources block (if you have a recent java). Or at least con.close() in the finally {} block?

**Comment by ChinaXing** [comment]
@slyoldfox my question is not leaking the con.close() action. 

I means if the con.close() called, the broken connection will still be release to the Pool. which will be got by next getConnection() call.

**Comment by brettwooldridge** [comment]
@ChinaXing HikariCP checks exceptions for disconnection codes ([here](https://github.com/brettwooldridge/HikariCP/blob/dev/src/main/java/com/zaxxer/hikari/pool/ProxyConnection.java#L146)).  If a disconnected connection is returned to the pool, or a connection is disconnected while idle in the pool, it will generally be tested before being given to a user.

**Comment by ChinaXing** [comment]
I think it was not what you said.  the checkException only be called when SQLException was threw in the con.close().

if a disconnected connection is returned to the pool. when given to a user, test only occurred at : 

`clockSource.elapsedMillis(poolEntry.lastAccessed, now) > ALIVE_BYPASS_WINDOW_MS`

**Comment by nitincchauhan** [comment]
@ChinaXing I think someone also replied to your same question on so, you should be closing connection 'correctly' and let pool do its job (of closing or recycling). Hope your doubt is 'clear' now.
If not and you think HikariCP is not doing what 'you' are expecting, post the test code as evidence for investigation. Looking at piece of hikariCP code will not give you 'complete' picture.

**Comment by ChinaXing** [comment]
@brettwooldridge the following commit change the `ALIVE_BYPASS_WINDOW_MS`, in this window, a given back broken connection make be got again from the pool.
https://github.com/brettwooldridge/HikariCP/commit/23c1b80bfd7ffa4df21365b6f5d6a80bcdc8f32d

**Comment by nitincchauhan** [comment]
@ChinaXing similar to ALIVE_BYPASS_WINDOW_MS, ...even if pool is ALWAYS returning connection after validating, it is possible that connection gets 'disconnected' when 'client' needs to use it.
'you' need to write 'client' considering such possibilities if required.
