### ISSUE TITLE
DropWizard Metric Pool Usage, grows endlessly.

### ISSUE THREAD

**Issue by joebrassi** [brettwooldridge/HikariCP#529]
If you set an instance of MetricsRegistry to HikariCP it will start collecting statistical information about the performance of the Datasource. Nevertheless, the metric **pool.Usage** which uses an histogram to measure the distribution of values grows its reservoir endlessly. This is a problem if you plan to deploy Hikari in a web-server with instrumentation because that reservoir will continue growing and growing with no stop for every connection opened and closed (on every hit to the server).

The same [DropWizard Metrics](https://dropwizard.github.io/metrics/3.1.0/manual/core/) webpage recommends to use **UniformReservoirs** for long-term measurements and use only Histograms for short data sets.

**Comment by brettwooldridge** [comment]
@joebrassi As far as I know that is incorrect.  The default histogram uses an [Exponentially Decaying Reservoir](http://dimacs.rutgers.edu/~graham/pubs/papers/fwddecay.pdf):

> To compute a simple decayed aggregate exactly, such as decayed sum, can require
> revisiting every input item to compute the contribution of that item (***an exception is 
> exponentially decayed sum and counts***, which can be tracked in ***constant space*** due
> to properties of the decay function).

Uniform Reservoirs on the other hand are not very useful for pool monitoring:

> Don’t use one where you’d want to know if the distribution of the underlying data stream
> has changed recently.

Most users are interested in recent data.  If the server has been running for three months, recent but highly abnormal pool behavior will be completely "smoothed over" by the uniform median function.

**Comment by joebrassi** [comment]
Yes, you're definitely right. Somehow missed to see the class type of the reservoir during the tests. It actually uses an Exponentially Decaying Reservoir.
