### ISSUE TITLE
PoolBase.registerMBeans fails when multiple wars in same container

### ISSUE THREAD

**Issue by victropolis** [brettwooldridge/HikariCP#533]
If I have two wars deployed to the same Tomcat container, each war with one or more connection pools, PoolBase.registerMBeans fails when the pool names happen to coincide.  This happens if I set the poolName myself or if I rely on the Hikari generated pool names.  See example below.

HikariPool-0 - You cannot use the same pool name for separate pool instances.
HikariPool-0 - You cannot use the same pool name for separate pool instances.

**Comment by brettwooldridge** [comment]
Are multiple pools using the same configuration?  It seems they must be, in which case, even if HikariCP automatically detected a collision and augmented the pool name (eg. HikariPool-1) how would you distinguish which pool belongs to which war instance?  It seems like each war, or each pool in each war,  needs its own unique configuration.

**Comment by victropolis** [comment]
If I have a spring bean defined as follows in an application context, that
application context can be included by any war that needs it and it's
possible for those wars to be deployed to the same tomcat container.  In
this case, each war will have it's own connection pool, because objects in
each war are independent of objects in other wars.

    <bean id="analyticsDataSource"
class="com.zaxxer.hikari.HikariDataSource" destroy-method="close">
        <constructor-arg index="0">
            <bean class="com.zaxxer.hikari.HikariConfig">
                <property name="registerMbeans" value="true"/>
                <property name="maximumPoolSize"
value="${services.common.analytics.db.maxConnections}"/>
                <property name="driverClassName"
value="${services.common.analytics.db.driver}"/>
                <property name="jdbcUrl"
value="${services.common.analytics.db.driverUrl}"/>
                <property name="username"
value="${services.common.analytics.db.user}"/>
                <property name="password">
                    <bean factory-bean="decryptor"
factory-method="decryptString">
                        <constructor-arg
value="${services.common.analytics.db.password}"/>
                        <constructor-arg>
                            <bean factory-bean="decryptor"
factory-method="getSecretKeyFromFile"/>
                        </constructor-arg>
                    </bean>
                </property>
            </bean>
        </constructor-arg>
    </bean>

**Comment by brettwooldridge** [comment]
You'll probably have to define some sort of custom factory bean that computes a pool name, possibly based on timestamp or an AtomicInteger stored in a system property (therefore global to the VM).

**Comment by brettwooldridge** [comment]
Another possiblity is using a [PropertyPlaceholderConfigurer](http://docs.spring.io/spring/docs/current/spring-framework-reference/html/beans.html#beans-factory-placeholderconfigurer) to allow war-specific property files.

**Comment by brettwooldridge** [comment]
@victropolis If you are curious to try it, the ``dev`` branch contains a change to make the automatic pool number generation global to the *JVM* rather than being scoped to by the WAR classloader.

**Comment by victropolis** [comment]
Thanks Brett!  I'll give it a shot.

**Comment by victropolis** [comment]
Brett, this is what I ended up doing:

```
    <bean id="analyticsDataSource" class="com.zaxxer.hikari.HikariDataSource" destroy-method="close">
        <constructor-arg index="0">
            <bean class="com.zaxxer.hikari.HikariConfig">
                <property name="registerMbeans" value="true"/>
                <property name="poolName">
                    <bean class="com.digitalglobe.util.PoolNumberPrepender" factory-method="prependPoolNumber">
                        <constructor-arg index="0" type="java.lang.String" value="${services.common.analytics.db.poolName}"/>
                    </bean>
                </property>
                <property name="validationTimeout" value="${services.common.analytics.db.validationTimeout}"/>
                <property name="leakDetectionThreshold" value="${services.common.analytics.db.leakDetectionThreshold}"/>
                <property name="maxLifetime" value="${services.common.analytics.db.maxLifetime}"/>
                <property name="idleTimeout" value="${services.common.analytics.db.idleTimeout}"/>
                <property name="connectionTimeout" value="${services.common.analytics.db.connectionTimeout}"/>
                <property name="minimumIdle" value="${services.common.analytics.db.mininumPoolSize}"/>
                <property name="maximumPoolSize" value="${services.common.analytics.db.maximumPoolSize}"/>
                <property name="driverClassName" value="${services.common.analytics.db.driver}"/>
                <property name="jdbcUrl" value="${services.common.analytics.db.jdbcUrl}"/>
                <property name="username" value="${services.common.analytics.db.user}"/>
                <property name="password">
                    <bean factory-bean="decryptor" factory-method="decryptString">
                        <constructor-arg value="${services.common.analytics.db.password}"/>
                        <constructor-arg>
                            <bean factory-bean="decryptor" factory-method="getSecretKeyFromFile"/>
                        </constructor-arg>
                    </bean>
                </property>
            </bean>
        </constructor-arg>
    </bean>
```

And then in PoolNumberPrepender, I do something similar to what you're doing with the generic pool names.  You should be able to do something similar with the provided pool names and then I wouldn't have to do the above.  Keep me posted.

Thansk in advance!

**Comment by brettwooldridge** [comment]
I am going to mark this as closed.  While it theoretically possible for HikariCP to try to guarantee pool name uniqueness across classloader containers with user-specified pool names, this seems like something better left to the user of the pool, as @victropolis has done above.
