### ISSUE TITLE
Unable to get driver instance

### ISSUE THREAD

**Issue by victropolis** [brettwooldridge/HikariCP#540]
Brett, getting this error.  Doesn't automatic driver detection work for postresql?

Unable to get driver instance for jdbcUrl=<jdbc:postgresql://iu00gcsdbs003:5434/dgcs>

**Comment by nitincchauhan** [comment]
iu00gcsdbs003 is that instance id? is this working without pool or other pool?
can not find url with mention of instance like this in doc: https://jdbc.postgresql.org/documentation/head/connect.html

**Comment by victropolis** [comment]
that's a hostname.  I read that "HikariCP will attempt to resolve a driver through the DriverManager based solely on the jdbcUrl, but for some older drivers the driverClassName must also be specified. Omit this property unless you get an obvious error message indicating that the driver was not found" so I tried omitting the driverClassName and then I started getting the error above.  Everything works fine with the driverClassName provided.

**Comment by brettwooldridge** [comment]
@victropolis I don't know whether the postgresql driver self-registers.  If you look inside the JAR for a file, ``META-INF/services/java.sql.Driver``.  If it is there, the DriverManager is supposed to interrogate it.  However, some containers have classloaders that can thwart the process, in which case you end up needing to specify the driverClassName.

**Comment by mleonhard** [comment]
I solved this by calling `HikariConfig.setDriverClassName()`:
```java
HikariConfig config = new HikariConfig();
config.setDriverClassName(org.postgresql.Driver.class.getName());
config.setJdbcUrl(jdbcUrl);
config.setUsername(username);
config.setPassword(password);
this.hikariDataSource = new HikariDataSource(config);
```

My `build.gradle` file has:
```gradle
repositories { mavenCentral() }
dependencies {
  compile 'org.postgresql:postgresql:42.2.5'
  ...
}
```

**Comment by unschikov** [comment]
this it helped me
config.setDriverClassName(org.postgresql.Driver.class.getName());
