### ISSUE TITLE
QUESTION: connectionTimeout, idleTimeout, and maxLifetime

### ISSUE THREAD

**Issue by victropolis** [brettwooldridge/HikariCP#541]
maxLifetime says that "An in-use connection will never be retired, only when it is closed will it then be removed"  Does this mean that a long running query will always be allowed to complete?  In other words, is there a knob I need to tweak to ensure that my long running queries complete or not?  Thanks!

**Comment by nitincchauhan** [comment]
correct. no knob required, just close connection 'properly' when done.

**Comment by victropolis** [comment]
so HikariCP sill never kill a running query.  the only possibility is the database itself killing it or network connectivity issues.  correct?

**Comment by jnehlmeier** [comment]
Your JDBC driver most likely have connection configuration properties to define a query timeout or more general a read timeout from the database. Check your JDBC driver documentation. For PostgreSQL its "socketTimeout" which defines the read timeout from the DB (and thus can also act as a global query timeout).

**Comment by brettwooldridge** [comment]
@victropolis HikariCP will never kill an in-use Connection unless the pool itself is shutting down.
