### ISSUE TITLE
Why HikariCP creates new connection for every web app in Tomcat on startup

### ISSUE THREAD

**Issue by alqershi** [brettwooldridge/HikariCP#542]
When I define HikariCP with Tomcat 7 as JNDI inside context.xml like the below, every time I deploy new web application, it opens new connections. For example, if I have 5 Apps in Tomcat, it will open 50 connections, 10 for each App. However, in C3p0, using the same settings and the same tomcat instance, it only creates a pool with 10 connections and share this pool with All Apps. I mean, in C3P0, the pool doesn't open new connection per APP while in HikariCP, it does. Was this done for a reason and is there anyway to change it? 
```javascript
<Resource name="jdbc/testDatasource" 
          auth="Container" 
          factory="com.zaxxer.hikari.HikariJNDIFactory" 
          type="javax.sql.DataSource" 
          driverClassName="com.mysql.jdbc.Driver"
          jdbcUrl="jdbc:mysql://localhost:3306/football" 
          username="xxx" 
          password="xxx" 
          minimumIdle="3" maximumPoolSize="10" connectionTimeout="300000" maxLifetime="1800000" />
```

**Comment by brettwooldridge** [comment]
@alqershi If simply swapping out the ``factory`` method works for C3P0, they are doing it wrong.  The purpose of the factory, by default, is specifically to generate a new instance for each WAR that performs a JNDI lookup.

If you want to share a pool across WARs, from my reading of the Tomcat docs, what you need is the ``singleton="false"`` attribute.

You *may* also need to...

Define the resource in the ``conf/server.xml`` file:
```xml
<GlobalNamingResources>
  <Resource name="jdbc/testDatasource" 
            auth="Container" 
            factory="com.zaxxer.hikari.HikariJNDIFactory"
            singleton="true"
            type="javax.sql.DataSource" 
            driverClassName="com.mysql.jdbc.Driver"
            jdbcUrl="jdbc:mysql://localhost:3306/football" 
            username="xxx" 
            password="xxx" 
            minimumIdle="3" maximumPoolSize="10" connectionTimeout="300000" maxLifetime="1800000"
  />
</GlobalNamingResources>
```
And subsequently define the WAR ``web.xml`` with the following:
```xml
<Context>
    <WatchedResource>WEB-INF/web.xml</WatchedResource>
    <ResourceLink global="jdbc/testDatasource"
                  name="jdbc/testDatasource"
                  type="javax.sql.DataSource"/>
</Context>
```
If that's not it, it's really close.  Read the internets.
