### ISSUE TITLE
HikariCP as JNDI Datasource in Weblogic

### ISSUE THREAD

**Issue by psyuhen** [brettwooldridge/HikariCP#543]
HikariCP as JNDI Datasource #8

I have trying to test HikariCP as jndi datasource, but i cannot find the way to add it as jndi datasource in weblogic.
If it's possible can you provide the configuration or if not can you add this feature ?

**Comment by brettwooldridge** [comment]
Please ask this question on stackoverflow.  HikariCP supports JNDI deployment, but we have no experience with WebLogic configuration.
