### ISSUE TITLE
Embedded Firebird ??

### ISSUE THREAD

**Issue by tJeyhun** [brettwooldridge/HikariCP#544]
Hi,

Does HikariCP works with embedded Firebird? As much as I know (mentioned in Jaybird Documentation) "only one jvm" can connect to embedded database. Does this mean that one jvm can create any count of connections to embedded database? If yes, is there any configuration for setup.

**Comment by brettwooldridge** [comment]
Should work fine.  Configuration should be as simple as the correct connection URL.
