### ISSUE TITLE
Only one active connection?

### ISSUE THREAD

**Issue by maudewest** [brettwooldridge/HikariCP#545]
We're testing HikariCP at the client and have had great initial success - an application loading 1 million records over multiple HTTP threads and putting them in the DB had it's run time cut by 70% after moving from Tomcat CP to Hikari CP!

Now we are having an issue with a new application.  The application is a batch process that launches N threads.  Each thread starts a transaction and ETLs some data from a few tables to some other tables.  This application slowed down markedly after changing the connection pool to Hikari from Tomcat.

Looking in JMX Metrics, it appears that only one active connection is ever requested out of a maximumPoolSize=10.  The pool is a fixed-size pool.  Changing the connection pool back to TomcatCP seems to speed up the application several times.

Perhaps someone has seen this before?  Any suggestions?

**Comment by maudewest** [comment]
Oracle 11g, running Groovy 2.3 on Java 8.

**Comment by brettwooldridge** [comment]
Can you get a thread dump when you think all threads should be running but think they aren't?  If they're running, they must be blocked *somewhere*.

**Comment by maudewest** [comment]
This was a bug in our side, using some unrelated non-threadsafe code.  No issue.

After fixing the bug, the code runs about 2x faster using HikariCP than Tomcat CP.
