### ISSUE TITLE
Why set autoCommit every time?

### ISSUE THREAD

**Issue by j256** [brettwooldridge/HikariCP#546]
First off.  Thanks so much for HikariCP.

I'm working on transactions and query performance.  I'm curious why when someone calls setAutoCommit(...) on the proxy connection why it doesn't see if the connection is already in that mode?

All of my database calls start with `SET autocommit=0` and end with `SET.autocommit=1` even though I configure the pool with default autocommit set to false.  Each one of these calls generates (I think) a synchronous JDBC back and forth.

This seems wasteful.  Is there be a setting that was smarter than that?

**Comment by j256** [comment]
I'm going to close this because it might have been fixed in 2.4.1.  Sorry to bother.

**Comment by j256** [comment]
Yeah.  The auto-commit is not at least seeing what the default value is.  I still think that it should interrogate both the auto-commit, read-only, and transaction-isolation values of the current connection and then making a decision to change or not based on current status.

**Comment by brettwooldridge** [comment]
This is not a decision that should be left to HikariCP.  Many drivers *already* do this "short-circuit" internally, or like MySQL can be configured to do so.  For example, MySQL [has a property](https://dev.mysql.com/doc/connector-j/en/connector-j-reference-configuration-properties.html) ``useLocalSessionState``:
```
Should the driver refer to the internal values of autocommit and transaction isolation that are
set by Connection.setAutoCommit() and Connection.setTransactionIsolation() and 
transaction state as maintained by the protocol, rather than querying the database or blindly
sending commands to the database for commit() or rollback() method calls?
```
MySQL also has a property to elide commit/rollback, ``useLocalTransactionState``:
```
Should the driver use the in-transaction state provided by the MySQL protocol to determine
if a commit() or rollback() should actually be sent to the database?
```
Drivers that either do not short-circuit internally, or do not provide such an option should have feature requests opened against them.  Again, this is not a decision that should be made at the pooling level.

**Comment by j256** [comment]
Good points Brett.  Didn't know about the driver settings.  Very cool.  I also wrote a `ReadOnlyDetectingPooledDataSource.java` that wraps 2 HikariCP pools, one for read-only connections and one for read-write.  That also was a big win.  Thanks again.  Here's my write up of it with the source at the bottom: http://256.com/gray/docs/misc/performance_optimizing_spring_hibernate_transactions/

**Comment by brettwooldridge** [comment]
@j256 Don't take this feedback the wrong way, your solution is very clever.  My major concern is that it is *fragile*.  One small change to Hibernate's behavior -- calling ``setAutoCommit()`` before ``setReadOnly()``, for example, would completely bypass your detection code.  Basically, any reordering of method invocation order would be detrimental to detection schemes.

If I had to *maintain* this solution, and come in and figure out why the application suddenly slowed down, years after you have moved on to greener pastures, I'd be cursing your name when I finally figured it out. :angry:   The current code, clever though it is, is performing "magic" behind the curtain, and [hopefully] should be raising mental flags.

Might I suggest a possible configuration-based solution that provides much higher visibility to both you and maintainers from the future?

Your two DataSource solution is on the right track.  Consider using [multiple transaction managers](http://docs.spring.io/spring/docs/current/spring-framework-reference/html/transaction.html#tx-multiple-tx-mgrs-with-attransactional).  One that specifies a read-only DataSource and the other an ordinary DataSource.

If you name the ordinary Transaction Manager "transactionManager" it will used by default ``@Transactional`` annotations.  And then you can specify the read-only tm explicitly (or visa-versa if read-only is more common).  Eg. ``@Transactional("read-only", readOnly=true)``.

Just my $0.02.

**Comment by j256** [comment]
Ha!  Mostly agreed @brettwooldridge.  Didn't know about the `@Transactional` value which maybe be a better solution given that I have to educate the other programmers to use it instead of the even more fragile name mappings in the spring config.  That said I've also documented it heavily in code and spring XML for the reasons you mention.  Appreciate the feedback.  Cheers.
