### ISSUE TITLE
Get pgconnection from pool

### ISSUE THREAD

**Issue by Tostino** [brettwooldridge/HikariCP#549]
I have an application using HikariCP, it's currently running version 2.4.1 and everything is working fine, but I would like to upgrade to the current version (2.4.3).

I use the Postgres LISTEN / NOTIFY system in my app, so I need to get the base PGConnection object from the connection returned by HikariCP.
I was previously doing: this.pgConnection = PGConnection.class.cast(ConnectionProxy.class.cast(connection).getPoolBagEntry().connection);
This no longer works as of 2.4.1, as you renamed that class ProxyConnection, and made the getPoolEntry() method package local.

What alternative methods do I have to get the PGConnection so I can get all of my notifications from the connection?

**Comment by brettwooldridge** [comment]
@Tostino Use ``PGConnection pgConn = connection.unwrap(PGConnection.class)``.
