### ISSUE TITLE
(Question) Using metrics in junit tests

### ISSUE THREAD

**Issue by benduke** [brettwooldridge/HikariCP#551]
I am trying to use the metrics in my junit tests to detect active connections that were not closed. When i put break points in my code the active connections show up (as expected) but if I let the code run without breakpoints it does not catch the active connections.

The pool is aware of the active connections when the test is finished...

DEBUG Thread-3 com.zaxxer.hikari.pool.HikariPool - Before closing	pool springHikariCP stats (total=10, active=2, idle=8, waiting=0)

Im assuming I'm missing some kind of forced update of the metrics in my junit?

**Comment by benduke** [comment]
I think i've already figured a way around this. I set the validationTimeout property to 1 second and put the thread to sleep for a second before grabbing the metrics. So far it seems dependable but of course I'm open to any recommendations.

**Comment by brettwooldridge** [comment]
@benduke If you use JMX to get these counts, the pool MBean provides instantaneous status.  The Dropwizard metrics are on a 1 second refresh cycle.

See the wiki for programmatic JMX access.

**Comment by benduke** [comment]
Thanks much for the feedback !
