### ISSUE TITLE
stream error

### ISSUE THREAD

**Issue by fjjiaboming** [brettwooldridge/HikariCP#553]
Connection org.mariadb.jdbc.MySQLConnection@5aa2b592 failed alive test with exception Could not read resultset: unexpected end of stream, read 0 bytes from 4

version: 2.4.1

pool.connectionTimeout=3000
pool.validationTimeout=1000
pool.idleTimeout=90000
pool.maxLifetime=123000
pool.minimumIdle=400
pool.initializationFailFast=false
mvn.pool.leakDetectionThreshold=10000

**Comment by nitincchauhan** [comment]
minimumIdle value looks suspicious. probably mysql or the machine is not capable/configured to handle such load. If you missed, https://github.com/brettwooldridge/HikariCP/wiki/About-Pool-Sizing may help you decide pool size.
Please also upgrade to release 2.4.3

**Comment by brettwooldridge** [comment]
Agreed. Unless you have 200+ CPU cores, 400 connections is insane.  This error looks like an out of memory error in MySQL.  Either way, the origin of this error is not HikariCP.

**Comment by fjjiaboming** [comment]
OK

**Comment by fjjiaboming** [comment]
Our use case is not OLTP and normal scenario. My application needs more connections to kill query of OLTP , that slow-query. 

> Agreed. Unless you have 200+ CPU cores, 400 connections is insane.
>

**Comment by fjjiaboming** [comment]
![timeout](https://cloud.githubusercontent.com/assets/951124/12437940/3da322bc-bf5d-11e5-8ffc-97b74815d29e.png)

> EDIT: check and if required set "wait_time" in mysql to minute or two more than maxLifetime

**Comment by fjjiaboming** [comment]
@brettwooldridge  
idleTimeout > maxLifetime is right ? 
or
idleTimeout < maxLifetime is right ?

**Comment by brettwooldridge** [comment]
idleTimeout should be less than maxLifetime.

**Comment by fjjiaboming** [comment]
@brettwooldridge  Thanks
