### ISSUE TITLE
After query broken, generate new ID for an existing record

### ISSUE THREAD

**Issue by elesdoar** [brettwooldridge/HikariCP#554]
After broken SQL query, generate new records after edit.

Example:
```json
// One record in table USER:
{
  "id": 1,
  "name": "userx",
  "email": "userx@mail.com",
  "age": 30,
  "username": "userx",
  "password": "xxxxxxxx"
}
```
After edit:
```json
// One record in table USER:
{
  "id": 2,
  "name": "userx",
  "email": "userx@mail.com",
  "age": 30,
  "username": "userx",
  "password": "xxxxxxxx"
}
```

Server is:
* JBOSS 6.2 EAP
* Hibernate 4.2 Final
* Spring framework 4.x
* Oracle 11g

**Comment by brettwooldridge** [comment]
What does this have to do with HikariCP?

**Comment by elesdoar** [comment]
Create a copy of the record when it's edited. Solve changing HikariCP datasource for standard spring datasource.

**Comment by brettwooldridge** [comment]
I still have no idea what that means.  The sounds like an issue of the connection not being committed or rolled back.

The difference with the standard Spring DataSource is that two sets of getConnection()/close() calls are likely to get two separate Connections.  HikariCP is likely to give the same (previously used) connection to the thread.

I suggest asking this question on stackoverflow.com.

**Comment by elesdoar** [comment]
@brettwooldridge thanks,

I think that the problem is with HikariCP datasource, I have some entities mapped with auto generated ID, while there is no SQL errors, all is alright, but, after SQL errors, when edit some entity, HikariCP datasource duplicates the editing record in a new record with new generated ID, only happens with HikariCP datasource. Somehow send null ID to database, generating a new record.
