### ISSUE TITLE
HikariProxyCallableStatement is missing overriden default method causing SQLFeatureNotSupportedException

### ISSUE THREAD

**Issue by kazuhiro** [brettwooldridge/HikariCP#555]
Hi,

When running HikariCP on Java8, `HikariProxyCallableStatement` class is missing overriden definition of  methods from `CallableStatement` interface: 
* `registerOutParameter(String parameterName, SQLType sqlType)`
* `registerOutParameter(String parameterName, SQLType sqlType, int scale)`
* `registerOutParameter (String parameterName, SQLType sqlType, String typeName)`

All of them are marked as default, hence are not generated by `JavassistProxyFactory`. 

This is causing a ```SQLFeatureNotSupportedException``` if any one of the methods is called on HikaruCP prepared statement despite the fact that method itself is implemented in particular `CallableStatement`.

**Comment by brettwooldridge** [comment]
@kazuhiro HikariCP 2.4.4 RC1 [is available](https://groups.google.com/forum/#!topic/hikari-cp/Hp9D-Q8IVtg) for testing.
