### ISSUE TITLE
Another NoClassDefFoundError

### ISSUE THREAD

**Issue by morfie78** [brettwooldridge/HikariCP#558]
Sorry.  I know that other tickets exist for this issue, and I promise I read them all. :)

<pre>
[12:20:35 ERROR]: Error occurred while enabling ChestShopStats v1.0 (Is it up to
 date?)
java.lang.NoClassDefFoundError: com/zaxxer/hikari/HikariConfig
...
</pre>

I'm using eclipse, and I'm not using mvn, and I'm on Windows 8.1 x64.
I am using the latest HikariCP-2.4.4-SNAPSHOT.jar from the dev branch, compiled with mvn.

My Java Version is jre1.8.0_51.
I compiled HikariCP using Apache Maven 3.3.3.

I'm linking in the HikariCP jar by adding it as a Library in the Project Properties build path via "Add External JARs...".

Eclipse sees the library, and the class names resolve in the code, but at runtime, I get the NoClassDefFoundError for HikariConfig.

Any ideas?  Any additional information I can give you?
Thanks again.

**Comment by brettwooldridge** [comment]
@morfie78 Are you running the application under Eclipse?  If you you need to add the library to the launch configuration's "Classpath" tab.

**Comment by morfie78** [comment]
No. I'm not running it in Eclipse.  I'm running it in a Spigot server. https://www.spigotmc.org/
