### ISSUE TITLE
No property available on HikariDataSource for databaseName

### ISSUE THREAD

**Issue by rocketraman** [brettwooldridge/HikariCP#560]
There is no property available on HikariDataSource for `databaseName` when using the recommended `dataSourceClassName` approach rather than a JDBC URL.

With Postgres, this results in:

```
Caused by: org.postgresql.util.PSQLException: FATAL: database "null" does not exist
```

It can be injected via datasourceProperties but it would be nice if it could have its own property.

**Comment by victropolis** [comment]
put it at the end of your jdbc url:

```
jdbc:postgresql://hostname:port/database
```

**Comment by victropolis** [comment]
oh, what do you mean when using the recommended dataSourceClassName approach rather than a JDBC URL.

**Comment by rocketraman** [comment]
> oh, what do you mean when using the recommended dataSourceClassName approach rather than a JDBC URL

From the README:

"We recommended using dataSourceClassName instead of jdbcUrl, but both are acceptable."

and

"We feel that DataSource-based configuration (above) is superior for a variety of reasons (see below)"

**Comment by brettwooldridge** [comment]
DataSource-based configuration is more readable, in our opinion.

However, to address the original idea that HikariCP could have a global property, ``databaseName``, it is simply not feasible.  Datasources are configured by setters on the DataSource implementation class.  Every driver is different.  One driver might have ``setDatabaseName()`` (MySQL), H2 and OrientDB have none, Firebird has ``setDatabase`` but it takes a URL, SQLServer additionally requires an instance name.

Having a global property that does not work across all databases is more likely to lead to confusion.  Furthermore, where does it end?  What about hostname and port?

These are database specific options and it is no more possible to make a universal global property than it is to have a universal JDBC URL.  Databases are too different.

**Comment by rocketraman** [comment]
> Datasources are configured by setters on the DataSource implementation class. Every driver is different.

Thanks for the explanation Brett!
