### ISSUE TITLE
2 Questions Only

### ISSUE THREAD

**Issue by DavidMont** [brettwooldridge/HikariCP#561]
1. Does hikari takes care of the connections {in the connection pool} when cpu {About machine} max out to 100% ?
2. In-relation to question 1, If no then will it issue a log that there is a connection leak?

thanks,
Dave

**Comment by brettwooldridge** [comment]
I don't understand question #1.  If a connection is out of the pool for longer than the leak detection threshold it will be logged, regardless of *why* it was out of the pool.  If the CPU is pegged at 100% the timer thread that logs the leak might itself be starved, and therefore be delayed from reporting the leak.

**Comment by DavidMont** [comment]
Ah i see, thanks for your time.
