### ISSUE TITLE
Incorrect housekeeper reports

### ISSUE THREAD

**Issue by dannygu** [brettwooldridge/HikariCP#562]
Hi,

I'm looking into Hikari logs and comparing them to actual DB connections i am seeing false information reported, i.e: 

Hikari reports:

2016-01-27 11:21:18,969 [Hikari housekeeper (pool HikariPool-0)] DEBUG com.zaxxer.hikari.pool.HikariPool - After cleanup        pool HikariPool-0 stats (total=90, active=90, idle=0, waiting=1)

But actual DB connections during that time specific time are 67.

[~]# date
Wed Jan 27 11:21:21 EST 2016
[~]# mysql -BNe "show processlist" | | wc -l
67

I'm using MySQL and Hikari 2.4.2, as you can see Hikari reports its out of connections yet MySQL has only 67 connections open.

Any idea what could be wrong ? my configuration is:

maximumPoolSize=90
minimumIdle=10
idleTimeout=60000
maxLifetime=1800000
leakDetectionThreshold=220000

By the way, this seems to happen only after a few days of running, after a restart all the stats are reported correctly...

Thanks.

**Comment by nitincchauhan** [comment]
@dannygu make sure wait_timeout defined in my.cnf or in url is few seconds MORE than maxLifetime you defined for hikaricp. ie. 1800+15

**Comment by brettwooldridge** [comment]
@dannygu Do what @nitincchauhan said, additionally this will give you better information.
```
mysql> show status like '%onn%';
+--------------------------+-------+
| Variable_name            | Value |
+--------------------------+-------+
| Aborted_connects         | 0     | 
| Connections              | 8     | 
| Max_used_connections     | 4     | 
| Ssl_client_connects      | 0     | 
| Ssl_connect_renegotiates | 0     | 
| Ssl_finished_connects    | 0     | 
| Threads_connected        | 4     | 
+--------------------------+-------+
7 rows in set (0.00 sec)
```
Finally, ``leakDetectionThreshold`` should be less than ``maxLifetime``, and should typically be said 30-50% longer than your longest running query.

**Comment by dannygu** [comment]
Hi,

I verified our settings again, our wait_timeout is in indeed higher then maxLifetime, also looking into Aborted_connects shows 0.

| Aborted_connects                              | 0       |
| Connection_errors_accept                      | 0       |
| Connection_errors_internal                    | 0       |
| Connection_errors_max_connections             | 0       |
| Connection_errors_peer_address                | 0       |
| Connection_errors_select                      | 0       |
| Connection_errors_tcpwrap                     | 0       |
| Connections                                   | 3344329 |
| Max_used_connections                          | 409     |
| Performance_schema_session_connect_attrs_lost | 0       |
| Ssl_client_connects                           | 0       |
| Ssl_connect_renegotiates                      | 0       |
| Ssl_finished_connects                         | 0       |
| Threads_connected                             | 112     |

**Comment by brettwooldridge** [comment]
@dannygu Can you enable debug logging?  You should be able to count the number of added connections, minus the number of retired connections.

**Comment by brettwooldridge** [comment]
@dannygu You can also run this command on the MySQL server to determine the number of open connections from the host where HikariCP is running:
```
netstat -a | grep ESTABLISHED | grep <ip address>
```
where &lt;ip address> is the address of the HikariCP host.

**Comment by brettwooldridge** [comment]
@dannygu I just ran across a post I made 2 years ago.  Basically, I said then ``Threads_connected`` is the value you want to be watching.

**Comment by dannygu** [comment]
Sorry for my delayed response, but I've only now had the chance to dig into this manner again, it seems this issue only occurs when a leak is detected and terminated HikariCP, i.e only after a leak was detected Hikari starts reporting incorrect stats for total/active/idle.

If it makes any difference we are using HAProxy in the middle i.e Tomat > HaProxy > MySQL.

**Comment by brettwooldridge** [comment]
@dannygu That is indeed strange, because while HikariCP will log a leaked connection, it does not terminate leaked connections.  Do you have any debug-level logs you can share (attach)?

**Comment by dannygu** [comment]
now it makes sense, even though its closed on MySQL due to wait_timeout since my code had a leak and it was never returned back to Hikari the stats are reported incorrectly, though they actually aren't , a connection was taken and never returned to Hikari so its thinking its still 'alive' but it really isn't.

Obviously i have to fix my code.

One last question - "We strongly recommend setting this value, and it should be at least 30 seconds less than any database-level connection timeout. " you mean wait_timeout on MySQL and not idletimeout in Hikari , correct ? 

Thanks!

**Comment by nitincchauhan** [comment]
@dannygu 

Ideally, wait_timeout < leakDetectionThreshold < maxLifetime
eg:
wait_timeout =  leakDetectionThreshold - 30 seconds
leakDetectionThreshold  =  maxLifetime - 5 seconds

idleTimeout:  controls the maximum amount of time that a connection is allowed to sit idle in the pool.

**Comment by nitincchauhan** [comment]
@dannygu
Ideally, wait_timeout > maxLifetime > leakDetectionThreshold
eg:
wait_timeout =  maxLifetime + 30 seconds
maxLifetime = leakDetectionThreshold +5 seconds

idleTimeout: controls the maximum amount of time that a connection is allowed to sit idle in the pool.

after you fix connection leaks, you should remove leakDetectionThreshold from production config.

**Comment by nitincchauhan** [comment]
@dannygu
Ideally, wait_timeout > maxLifetime > leakDetectionThreshold
eg:
wait_timeout =  maxLifetime + 30 seconds
maxLifetime = leakDetectionThreshold +5 seconds

idleTimeout: controls the maximum amount of time that a connection is allowed to sit idle in the pool.

after you fix connection leaks, you should remove leakDetectionThreshold from production config.

**Comment by nitincchauhan** [comment]
@dannygu
Ideally, wait_timeout > maxLifetime > leakDetectionThreshold
eg:
wait_timeout =  maxLifetime + 30 seconds
maxLifetime = leakDetectionThreshold +5 seconds

idleTimeout: controls the maximum amount of time that a connection is allowed to sit idle in the pool.

after you fix connection leaks, you should remove leakDetectionThreshold from production config.

**Comment by nitincchauhan** [comment]
@dannygu
Ideally, wait_timeout > maxLifetime > leakDetectionThreshold
eg:
wait_timeout =  maxLifetime + 30 seconds
maxLifetime = leakDetectionThreshold +5 seconds

idleTimeout: controls the maximum amount of time that a connection is allowed to sit idle in the pool.

after you fix connection leaks, you should remove leakDetectionThreshold from production config.

**Comment by nitincchauhan** [comment]
@dannygu
Ideally, wait_timeout > maxLifetime > leakDetectionThreshold
eg:
wait_timeout =  maxLifetime + 30 seconds
maxLifetime = leakDetectionThreshold +5 seconds

idleTimeout: controls the maximum amount of time that a connection is allowed to sit idle in the pool.

after you fix connection leaks, you should remove leakDetectionThreshold from production config.

**Comment by nitincchauhan** [comment]
@dannygu
Ideally, wait_timeout > maxLifetime > leakDetectionThreshold
eg:
wait_timeout =  maxLifetime + 30 seconds
maxLifetime = leakDetectionThreshold +5 seconds

idleTimeout: controls the maximum amount of time that a connection is allowed to sit idle in the pool.

after you fix connection leaks, you should remove leakDetectionThreshold from production config.

**Comment by nitincchauhan** [comment]
@dannygu
Ideally, wait_timeout > maxLifetime > leakDetectionThreshold
eg:
wait_timeout =  maxLifetime + 30 seconds
maxLifetime = leakDetectionThreshold +5 seconds

idleTimeout: controls the maximum amount of time that a connection is allowed to sit idle in the pool.

after you fix connection leaks, you should remove leakDetectionThreshold from production config.

**Comment by nitincchauhan** [comment]
@dannygu
Ideally, wait_timeout > maxLifetime > leakDetectionThreshold
eg:
wait_timeout =  maxLifetime + 30 seconds
maxLifetime = leakDetectionThreshold +5 seconds

idleTimeout: controls the maximum amount of time that a connection is allowed to sit idle in the pool.

after you fix connection leaks, you should remove leakDetectionThreshold from production config.
