### ISSUE TITLE
Configure Connection Pool for WebSphere + Oracle

### ISSUE THREAD

**Issue by rajkumarpb** [brettwooldridge/HikariCP#568]
Can someone please tell me how to have HikarCP configuration in spring with JNDI. I'm using WebSphere Server + Oracle and my spring-context.xml is like this!

    <bean id="dataSource" class="org.springframework.jndi.JndiObjectFactoryBean"> 
		<property name="jndiName" value="jdbc/OracleDS"/> 
	</bean>

Can someone help me?

**Comment by brettwooldridge** [comment]
Try asking on stackoverflow.com.
