### ISSUE TITLE
Disable logging

### ISSUE THREAD

**Issue by Cissoid44** [brettwooldridge/HikariCP#575]
Hey, is there any way to disable HikariCP's outputs in console like that?
`[01:37:23 WARN]: [Server thread] INFO com.zaxxer.hikari.HikariDataSource - Hikar
iCP pool HikariPool-0 is starting.`

**Comment by brettwooldridge** [comment]
I don't know what logger framework you are using, but in most loggers you can suppress logs by package name, so you can set ``com.zaxxer.hikari`` to log at level ``NONE``.

**Comment by PascalSchumacher** [comment]
@Cissoid44 HikariCP uses slf4j, which is a logging facade. If you do not have any binding defined you get 

>SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
>SLF4J: Defaulting to no-operation (NOP) logger implementation
>SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

on start-up and messages for warn and above a logged to the console.

Add a binding for a log implementation. For details see: http://www.slf4j.org/manual.html#swapping If you want to disable logging completely you can use the slf4j-nop.jar,
