### ISSUE TITLE
Unregister driver on shutdown

### ISSUE THREAD

**Issue by danilcha** [brettwooldridge/HikariCP#584]
I am not sure this is an issue (or an issue in HikariCP), but maybe. I am using it with MySQL driver that is in my application lib folder. When I do redeploy of the application, Tomcat writes in the log:

> WARNING org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesJdbc The web application [*] registered the JDBC driver [com.mysql.jdbc.Driver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.

Probably it is HikariCP, who registers the driver. Would it be correct to unregister it on shutdown?

**Comment by brettwooldridge** [comment]
HikariCP does not register the driver.
