### ISSUE TITLE
JMX doc

### ISSUE THREAD

**Issue by nitincchauhan** [brettwooldridge/HikariCP#586]
mention setting and use of isRegisterMbeans, set/isRegisterMbeans(boolean register) in https://github.com/brettwooldridge/HikariCP/wiki/MBean-(JMX)-Monitoring-and-Management

**Comment by nitincchauhan** [comment]
also, In description for leakDetectionThreshold
It would be better to clearly state that setting this property does NOT close connection reported as leak. as its name suggests it is connection leak 'detection' only.

**Comment by asafm** [comment]
Just fell there and wasted 30 minutes. It's 10 seconds edit of the wiki page - if there was a way of suggesting pull request of wiki pages I would my self

**Comment by brettwooldridge** [comment]
Fixed.
