### ISSUE TITLE
ConnectionTimeout ignored at certain times

### ISSUE THREAD

**Issue by norbertpotocki** [brettwooldridge/HikariCP#588]
At times HikariCP ignores the connectionTimeout setting. Not sure what the reason is or how to diagnose this.  I'm using version 2.4.3 and have connectionTimeout set to 2000ms. This is what happens from time to time:

```
Caused by:
 java.sql.SQLTransientConnectionException: UserShardPool:jdbc:mysql://dbuser.mydomain.com:3306/UserShard - Connection is not available, request timed out after 38104ms.
at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:195)
at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:147)
at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:83)
```

Any guidelines on how to diagnose this?

**Comment by nitincchauhan** [comment]
Many possibilities for this, gathered from issued reported and resolved over time. in no particular older :)

1. it can be stupid mistake and instantiate the data source multiple times.
2. properties are not passed 'correctly' to hikaricp, usually by framework layer.
3  older driver and or hikaricp, use latest stable release.
4. apparent connection leak.
5. driver does not correctly implement or support Connection.setNetworkTimeout()
   check value of wait_timeout on the mysql server.
   socketTimeout
   enable tcpKeepAlive
6. driver does not 'correctly' implement Connection.isValid()
   use efficient connectionTestQuery

Hope this hels

**Comment by norbertpotocki** [comment]
Thanks for feedback Nitin. The problem we faced proved to be more subtle.

When thread starvation occurs HikariCP 2.4.3 will report "Unusual clock change" and evict all connections from a pool. It will then start re-creating those connections. It can take a while. Since the system is under heavy load there is a time window when all connections have been removed and none have been added yet. If a getConnection() comes in that window you can get "Connection is not available, request timed out" exception. **Version 2.4.4-SNAPSHOT seem to improve handling of this scenario significantly.**

I'm still going through 2.4.4-SNAPSHOT's code to see if this scenario (emptying pool and filling it up again) can occur in any other execution path.

For future reference, here's a setup that we used (in a form of answer to Nitin's questions):
1 + 3. We used latest versions of Spring Boot (1.3.4), HikariCP (2.4.3), Mysql driver (5.1.38) and Hibernate. Connection pool is instantiated once and held as a singleton inside DI container.
2. Double checked that - HikariCP reports settings as they should be (found one bizarre setting value that turned out to be deprecated field [see Issue #587])
4. Switched leak detection on - no issues here
5. Used latest mysql driver with latest version of mysql 5.5 branch - since this is a large scale system (range sharding implemented over 100 db clusters [one  connection pool per cluster]) we have quite efficient monitoring in place.My team validated that this was not an effect of networking issues nor db-side problems.
6. Latest mysql driver seems to use work well.
7. No issues here so far (timeouts work as expected [connectionTimeout aside] and there's always a large amount of spare connections in the pool at any time).

**Comment by brettwooldridge** [comment]
HikariCP 2.4.4 has been released.  It contains a fix explicitly for the issue of thread starvation triggering the clock shift detection, and subsequent eviction. Let us know if you observe any additional unusual behavior.
