### ISSUE TITLE
Connection is not available when ConnectionTestQuery is not set

### ISSUE THREAD

**Issue by stefandroog** [brettwooldridge/HikariCP#589]
JTDS v1.2.5 (SQL Server)
Hikari 2.4.3

Without setting a connection test query I get the following error:

`com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Exception during pool initialization: hot - Connection is not available, request timed out after 59999ms.
	at com.zaxxer.hikari.pool.HikariPool.initializeConnections(HikariPool.java:526) ~[HikariCP-2.4.3.jar:na]
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:136) ~[HikariCP-2.4.3.jar:na]
`

When I set the connection test query it is working properly.
`dataSource.setConnectionTestQuery("SELECT 1");`

Is this 'as designed' or is it a bug?

Config:
`11:56:20.354 [localhost-startStop-1] DEBUG org.hibernate.cfg.Configuration - Preparing to build session factory with filters : {}
11:56:20.594 [localhost-startStop-1] DEBUG com.zaxxer.hikari.HikariConfig - hot - configuration:
11:56:20.599 [localhost-startStop-1] DEBUG com.zaxxer.hikari.HikariConfig - allowPoolSuspension.............false
11:56:20.599 [localhost-startStop-1] DEBUG com.zaxxer.hikari.HikariConfig - autoCommit......................true
11:56:20.599 [localhost-startStop-1] DEBUG com.zaxxer.hikari.HikariConfig - catalog.........................
11:56:20.599 [localhost-startStop-1] DEBUG com.zaxxer.hikari.HikariConfig - connectionInitSql...............
11:56:20.599 [localhost-startStop-1] DEBUG com.zaxxer.hikari.HikariConfig - connectionTestQuery.............
11:56:20.599 [localhost-startStop-1] DEBUG com.zaxxer.hikari.HikariConfig - connectionTimeout...............60000
11:56:20.599 [localhost-startStop-1] DEBUG com.zaxxer.hikari.HikariConfig - dataSource......................
11:56:20.600 [localhost-startStop-1] DEBUG com.zaxxer.hikari.HikariConfig - dataSourceClassName.............
11:56:20.600 [localhost-startStop-1] DEBUG com.zaxxer.hikari.HikariConfig - dataSourceJNDI..................
11:56:20.600 [localhost-startStop-1] DEBUG com.zaxxer.hikari.HikariConfig - dataSourceProperties............{password=<masked>}
11:56:20.600 [localhost-startStop-1] DEBUG com.zaxxer.hikari.HikariConfig - driverClassName.................
11:56:20.600 [localhost-startStop-1] DEBUG com.zaxxer.hikari.HikariConfig - healthCheckProperties...........{}
11:56:20.600 [localhost-startStop-1] DEBUG com.zaxxer.hikari.HikariConfig - healthCheckRegistry.............
11:56:20.600 [localhost-startStop-1] DEBUG com.zaxxer.hikari.HikariConfig - idleTimeout.....................600000
11:56:20.600 [localhost-startStop-1] DEBUG com.zaxxer.hikari.HikariConfig - initializationFailFast..........true
11:56:20.600 [localhost-startStop-1] DEBUG com.zaxxer.hikari.HikariConfig - isolateInternalQueries..........false
11:56:20.600 [localhost-startStop-1] DEBUG com.zaxxer.hikari.HikariConfig - jdbc4ConnectionTest.............false
11:56:20.600 [localhost-startStop-1] DEBUG com.zaxxer.hikari.HikariConfig - jdbcUrl.........................jdbc:jtds:sqlserver://myserver/mydb;maxStatements=0
11:56:20.600 [localhost-startStop-1] DEBUG com.zaxxer.hikari.HikariConfig - leakDetectionThreshold..........60000
11:56:20.600 [localhost-startStop-1] DEBUG com.zaxxer.hikari.HikariConfig - maxLifetime.....................1800000
11:56:20.600 [localhost-startStop-1] DEBUG com.zaxxer.hikari.HikariConfig - maximumPoolSize.................10
11:56:20.600 [localhost-startStop-1] DEBUG com.zaxxer.hikari.HikariConfig - metricRegistry..................
11:56:20.600 [localhost-startStop-1] DEBUG com.zaxxer.hikari.HikariConfig - metricsTrackerFactory...........
11:56:20.600 [localhost-startStop-1] DEBUG com.zaxxer.hikari.HikariConfig - minimumIdle.....................10
11:56:20.600 [localhost-startStop-1] DEBUG com.zaxxer.hikari.HikariConfig - password........................<masked>
11:56:20.600 [localhost-startStop-1] DEBUG com.zaxxer.hikari.HikariConfig - poolName........................hot
11:56:20.601 [localhost-startStop-1] DEBUG com.zaxxer.hikari.HikariConfig - readOnly........................false
11:56:20.601 [localhost-startStop-1] DEBUG com.zaxxer.hikari.HikariConfig - registerMbeans..................true
11:56:20.601 [localhost-startStop-1] DEBUG com.zaxxer.hikari.HikariConfig - scheduledExecutorService........
11:56:20.601 [localhost-startStop-1] DEBUG com.zaxxer.hikari.HikariConfig - threadFactory...................
11:56:20.601 [localhost-startStop-1] DEBUG com.zaxxer.hikari.HikariConfig - transactionIsolation............
11:56:20.601 [localhost-startStop-1] DEBUG com.zaxxer.hikari.HikariConfig - username........................myuser
11:56:20.601 [localhost-startStop-1] DEBUG com.zaxxer.hikari.HikariConfig - validationTimeout...............5000
11:56:20.601 [localhost-startStop-1] INFO  com.zaxxer.hikari.HikariDataSource - hot - is starting.
11:56:20.672 [Hikari connection adder (pool hot)] DEBUG com.zaxxer.hikari.pool.PoolBase - hot - Connection.setNetworkTimeout() is not supported (net.sourceforge.jtds.jdbc.ConnectionJDBC3.getNetworkTimeout()I)
11:56:20.674 [Hikari connection adder (pool hot)] DEBUG com.zaxxer.hikari.pool.PoolBase - hot - Connection.isValid() is not supported, configure connection test query. (null)
`

**Comment by brettwooldridge** [comment]
It is expected, as reported by the message:

Connection.isValid() is not supported, configure connection test query. (null)
