### ISSUE TITLE
2.4.4 not in maven central?

### ISSUE THREAD

**Issue by PascalSchumacher** [brettwooldridge/HikariCP#592]
Hi Brett,

I know it takes some time until artifacts are in maven central, but I guess 2.4.4 should be available by now (two days since 0b485eb91a90dc6646c819d3bef5009b046bbcf1)?

**Comment by brettwooldridge** [comment]
It is published and announced.

**Comment by PascalSchumacher** [comment]
I know, but it's not available: http://search.maven.org/#search|gav|1|g%3A%22com.zaxxer%22%20AND%20a%3A%22HikariCP%22 still shows 2.4.3 as latest version. I guess something went wrong with publishing.

**Comment by brettwooldridge** [comment]
Try now.  It may not show up in the search engine yet, but it should resolve from sonatype.

**Comment by PascalSchumacher** [comment]
It's downloadable now. Yesterday it was not. I was to impatient. Sorry.
