### ISSUE TITLE
minimumIdle = 0 without setting maximumPoolSize doesn't work

### ISSUE THREAD

**Issue by TuomasKiviaho** [brettwooldridge/HikariCP#596]
I'm getting the following when `minIdle` is preset to zero and `maxIdle` is not set at all. 
```
java.lang.IllegalArgumentException
at java.util.concurrent.LinkedBlockingQueue.<init>(LinkedBlockingQueue.java:261)
at com.zaxxer.hikari.util.UtilityElf.createThreadPoolExecutor(UtilityElf.java:108)
at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:121)
at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:71)
```

The `HikariConfig.validate` seems to adjust `maxIdle` to zero and this in turn is not acceptable value for `LinkedBlockingQueue` queue size.

``` java
      if (maxPoolSize < 0) {
         if (minIdle < 0) {
            minIdle = 10;
         }
         maxPoolSize = minIdle;
      }
      else if (minIdle < 0 || minIdle > maxPoolSize) {
         minIdle = maxPoolSize;
      }
```

The configuration knobs section only mentions the adjustment scenario where `minIdle` is missing but `maxIdle`is preset but I assume that in this case the `maxPoolSize` should be 10 and `minIdle`shouldn't been tampered with.

``` java
      if (maxPoolSize < 0) {
         maxPoolSize = minIdle <= 0 ? 10 : minIdle;
      }
      if (minIdle < 0 || minIdle > maxPoolSize) {
         minIdle = maxPoolSize;
      }
```

**Comment by nitincchauhan** [comment]
@TuomasKiviaho good catch.

however, the fix should look:

    if (maxPoolSize < 1) {
       maxPoolSize = minIdle <= 0 ? 10 : minIdle;
    }
    if (minIdle < 0 || minIdle > maxPoolSize) {
       minIdle = maxPoolSize;
    }

as zero is valid for minIdle, not for maxPoolSize.
Thanks

**Comment by brettwooldridge** [comment]
HikariCP 2.4.5 was been released with a fix for this issue.
