### ISSUE TITLE
HikariConfig in 2.4.4 violates java.util.Properties contract 

### ISSUE THREAD

**Issue by andrewtaylor** [brettwooldridge/HikariCP#597]
Getting some problems with other libraries when using HikariCP 2.4.4 due to an AtomicInteger being written to the System properties in the HikariConfig static initializer. While the java.util.Properties lets you set objects via the 'put' method due to extending Hashtable, the JavaDoc (at least up to JDK 8) states that "Each key and its corresponding value in the property list is a string". I assume it couldn't be enforced with generics due to compatibility. 

Only noticed this because org.apache.commons.lang3.text.StrLookup.copyProperties() fails when trying to read back the value using getProperty. 

Sadly I think another approach will be required.

**Comment by prettynatty** [comment]
Same problem here. https://github.com/spray/spray fails with new HikariCP in runtime.

**Comment by brettwooldridge** [comment]
Already fixed. #594

**Comment by brettwooldridge** [comment]
HikariCP 2.4.5 was been released with a fix for this issue.
