### ISSUE TITLE
Could not integrate Spark-Streaming with HikariCP

### ISSUE THREAD

**Issue by Deric1111** [brettwooldridge/HikariCP#598]
Hi ,

I am trying to use HikariCP with spark Streaming to perform CRUD operations since spark sql just support part of it. I had come across errors like HikariDataSource is not serializable. Is it possible to extend HikariDataSource with Serializable in order to integrate with Spark Streaming?

**Comment by brettwooldridge** [comment]
@Deric1111 Unfortunately, it is likely not possible to serialize the datasource.  I'm not even sure what that would mean.  Connections certainly aren't Serializable.  We would have to mark so many members transient, it wouldn't have any meaning.
