### ISSUE TITLE
Intermittent Pool Exhaustion when using a Spring LazyConnectionDataSourceProxy

### ISSUE THREAD

**Issue by liamchristopher** [brettwooldridge/HikariCP#602]
We have a custom class: ReadOnlyAwareDataSourceProxy, which implements LazyConnectionDataSourceProxy. 
It instantiates with 2 connection pools (Read-Write / Read-Only)
Basically, we use @Transaction(readOnly=true), and it picks up and delegates to the RO connection if the whole Transaction is read-only.
This class has been in place (and in use across several teams) for several years at this point, and generally works. 
Recently, we re-worked our config setup from the legacy XML to @Configuration beans, and we've been getting some semi-regular failures only on the Read-Only connection.

Our current Versions:
> java 1.8
> SPRING_VERSION = "4.0.5.RELEASE"
> SPRING_SECURITY_VERSION = "3.2.4.RELEASE"
> HIBERNATE_VERSION = "4.2.0.Final"
> 'com.zaxxer:HikariCP:jar:2.4.5',
> "mysql:mysql-connector-java:jar:5.1.38",

The startup configs for the 2 pools (as reported by Hikari):
`
DEBUG com.zaxxer.hikari.HikariConfig - Read-Only-Pool - configuration:
DEBUG com.zaxxer.hikari.HikariConfig - allowPoolSuspension.............false
DEBUG com.zaxxer.hikari.HikariConfig - autoCommit......................true
DEBUG com.zaxxer.hikari.HikariConfig - catalog.........................null
DEBUG com.zaxxer.hikari.HikariConfig - connectionInitSql...............null
DEBUG com.zaxxer.hikari.HikariConfig - connectionTestQuery.............null
DEBUG com.zaxxer.hikari.HikariConfig - connectionTimeout...............10000
DEBUG com.zaxxer.hikari.HikariConfig - dataSource......................com.mysql.jdbc.jdbc2.optional.MysqlDataSource@5a8a5957
DEBUG com.zaxxer.hikari.HikariConfig - dataSourceClassName.............null
DEBUG com.zaxxer.hikari.HikariConfig - dataSourceJNDI..................null
DEBUG com.zaxxer.hikari.HikariConfig - dataSourceProperties............{password=<masked>}
DEBUG com.zaxxer.hikari.HikariConfig - driverClassName.................null
DEBUG com.zaxxer.hikari.HikariConfig - healthCheckProperties...........{}
DEBUG com.zaxxer.hikari.HikariConfig - healthCheckRegistry.............null
DEBUG com.zaxxer.hikari.HikariConfig - idleTimeout.....................600000
DEBUG com.zaxxer.hikari.HikariConfig - initializationFailFast..........true
DEBUG com.zaxxer.hikari.HikariConfig - isolateInternalQueries..........false
DEBUG com.zaxxer.hikari.HikariConfig - jdbc4ConnectionTest.............false
DEBUG com.zaxxer.hikari.HikariConfig - jdbcUrl.........................null
DEBUG com.zaxxer.hikari.HikariConfig - leakDetectionThreshold..........30000
DEBUG com.zaxxer.hikari.HikariConfig - maxLifetime.....................1800000
DEBUG com.zaxxer.hikari.HikariConfig - maximumPoolSize.................50
DEBUG com.zaxxer.hikari.HikariConfig - metricRegistry..................null
DEBUG com.zaxxer.hikari.HikariConfig - metricsTrackerFactory...........null
DEBUG com.zaxxer.hikari.HikariConfig - minimumIdle.....................10
DEBUG com.zaxxer.hikari.HikariConfig - password........................<masked>
DEBUG com.zaxxer.hikari.HikariConfig - poolName........................"Read-Only-Pool"
DEBUG com.zaxxer.hikari.HikariConfig - readOnly........................false
DEBUG com.zaxxer.hikari.HikariConfig - registerMbeans..................true
DEBUG com.zaxxer.hikari.HikariConfig - scheduledExecutorService........null
DEBUG com.zaxxer.hikari.HikariConfig - threadFactory...................null
DEBUG com.zaxxer.hikari.HikariConfig - transactionIsolation............null
DEBUG com.zaxxer.hikari.HikariConfig - username........................null
DEBUG com.zaxxer.hikari.HikariConfig - validationTimeout...............5000
2016-03-28 15:32:32,293 [localhost-startStop-1] INFO  com.zaxxer.hikari.HikariDataSource - Read-Only-Pool - Started.
`
Read-Write:
`
DEBUG com.zaxxer.hikari.HikariConfig - Read-Write-Pool - configuration:
DEBUG com.zaxxer.hikari.HikariConfig - allowPoolSuspension.............false
DEBUG com.zaxxer.hikari.HikariConfig - autoCommit......................true
DEBUG com.zaxxer.hikari.HikariConfig - catalog.........................null
DEBUG com.zaxxer.hikari.HikariConfig - connectionInitSql...............null
DEBUG com.zaxxer.hikari.HikariConfig - connectionTestQuery.............null
DEBUG com.zaxxer.hikari.HikariConfig - connectionTimeout...............10000
DEBUG com.zaxxer.hikari.HikariConfig - dataSource......................com.mysql.jdbc.jdbc2.optional.MysqlDataSource@52c9c4b
DEBUG com.zaxxer.hikari.HikariConfig - dataSourceClassName.............null
DEBUG com.zaxxer.hikari.HikariConfig - dataSourceJNDI..................null
DEBUG com.zaxxer.hikari.HikariConfig - dataSourceProperties............{password=<masked>}
DEBUG com.zaxxer.hikari.HikariConfig - driverClassName.................null
DEBUG com.zaxxer.hikari.HikariConfig - healthCheckProperties...........{}
DEBUG com.zaxxer.hikari.HikariConfig - healthCheckRegistry.............null
DEBUG com.zaxxer.hikari.HikariConfig - idleTimeout.....................600000
DEBUG com.zaxxer.hikari.HikariConfig - initializationFailFast..........true
DEBUG com.zaxxer.hikari.HikariConfig - isolateInternalQueries..........false
DEBUG com.zaxxer.hikari.HikariConfig - jdbc4ConnectionTest.............false
DEBUG com.zaxxer.hikari.HikariConfig - jdbcUrl.........................null
DEBUG com.zaxxer.hikari.HikariConfig - leakDetectionThreshold..........30000
DEBUG com.zaxxer.hikari.HikariConfig - maxLifetime.....................1800000
DEBUG com.zaxxer.hikari.HikariConfig - maximumPoolSize.................50
DEBUG com.zaxxer.hikari.HikariConfig - metricRegistry..................null
DEBUG com.zaxxer.hikari.HikariConfig - metricsTrackerFactory...........null
DEBUG com.zaxxer.hikari.HikariConfig - minimumIdle.....................10
DEBUG com.zaxxer.hikari.HikariConfig - password........................<masked>
DEBUG com.zaxxer.hikari.HikariConfig - poolName........................"Read-Write-Pool"
DEBUG com.zaxxer.hikari.HikariConfig - readOnly........................false
DEBUG com.zaxxer.hikari.HikariConfig - registerMbeans..................true
DEBUG com.zaxxer.hikari.HikariConfig - scheduledExecutorService........null
DEBUG com.zaxxer.hikari.HikariConfig - threadFactory...................null
DEBUG com.zaxxer.hikari.HikariConfig - transactionIsolation............null
DEBUG com.zaxxer.hikari.HikariConfig - username........................null
DEBUG com.zaxxer.hikari.HikariConfig - validationTimeout...............5000
2016-03-28 15:32:32,957 [localhost-startStop-1] INFO  com.zaxxer.hikari.HikariDataSource - Read-Write-Pool - Started.
`
ReadOnly is not explicitly set at the connection startup since it was spamming the Reset (readOnly) so I couldn't quite suss out the issues.

So here is what is interesting, after _some_ event we start getting "can not prepare statements".
What I'm seeing watching the logs is this:
`
2016-03-28 12:29:31,895 [Read-Write-Pool housekeeper] DEBUG com.zaxxer.hikari.pool.HikariPool - Read-Write-Pool - Pool stats (total=10, active=1, idle=9, waiting=0)
2016-03-28 12:30:01,895 [Read-Write-Pool housekeeper] DEBUG com.zaxxer.hikari.pool.HikariPool - Read-Write-Pool - Before cleanup stats (total=11, active=0, idle=11, waiting=0)
2016-03-28 12:30:01,896 [Read-Write-Pool housekeeper] DEBUG com.zaxxer.hikari.pool.HikariPool - Read-Write-Pool - After cleanup  stats (total=10, active=0, idle=10, waiting=0)
2016-03-28 12:30:31,896 [Read-Write-Pool housekeeper] DEBUG com.zaxxer.hikari.pool.HikariPool - Read-Write-Pool - Pool stats (total=10, active=0, idle=10, waiting=0)
`

So far, so good, right? But we NEVER see those for the read-only pool.
`
[www:api ~]$ grep -i housekee /var/log/tomcat7/catalina.out | grep -i Read-Write | wc -l
1919
[www:api ~]$ grep -i housekee /var/log/tomcat7/catalina.out | grep -i Read-Only | wc -l
1
`
That line is 
`
SEVERE: The web application [/api] appears to have started a thread named [Read-Only-Pool housekeeper] but has failed to stop it. This is very likely to create a memory leak.
Mar 28, 2016 3:31:52 PM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [/api] appears to have started a thread named [Read-Write-Pool housekeeper] but has failed to stop it. This is very likely to create a memory leak.
Mar 28, 2016 3:31:52 PM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
`
These are printed at shutdown along with other external clients we have, that happen on a restart.

So, what we ARE seeing is when the DB connection disappears is this:
`
[Read-Only-Pool connection closer] DEBUG com.zaxxer.hikari.pool.PoolBase - Read-Only-Pool - Closing connection com.mysql.jdbc.JDBC4Connection@29c2d615: (conne
ction has passed maxLifetime)
[Read-Write-Pool housekeeper] DEBUG com.zaxxer.hikari.pool.HikariPool - Read-Write-Pool - Pool stats (total=10, active=0, idle=10, waiting=0)
DEBUG com.zaxxer.hikari.pool.HikariPool - Read-Only-Pool - Timeout failure stats (total=0, active=0, idle=0, waiting=255)
WARN  org.hibernate.engine.jdbc.spi.SqlExceptionHelper - SQL Error: 0, SQLState: null
ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper - Read-Only-Pool - Connection is not available, request timed out after 10058m
s.
ERROR com.xxx.service.authentication.UserDeviceServiceImpl - Cannot Get Device: 
org.hibernate.exception.JDBCConnectionException: could not prepare statement
`

The waiting connections _eventually_ recover. But there are no active or idle connections available and this starts triggering monitoring, etc.
I've enabled the LeakDetection trigger, and occasionally get a method that goes over 30k.
`wait_time` on both slaves and master are not set, so I believe that's the default of 90s.

This seems to be where stuff is happening, but its looking like Hikari is closing all the idle connections after timing out, and then not properly-re-adding them. Again, I'm not seeing this on the almost identically configured Read-Write connection.

Any ideas?

**Comment by brettwooldridge** [comment]
@liamchristopher I know it might be large, but can you attach (not post) a thread-dump here, when the Read-Only-Pool goes to zero?

**Comment by liamchristopher** [comment]
Sorry it took so long to respond. The problem died down for a while, but we're still getting this about once a week, but we were able to get a thread dump over the weekend. I've redacted company information, but otherwise it is intact.

[thread_dump_redacted.txt](https://github.com/brettwooldridge/HikariCP/files/267113/thread_dump_redacted.txt)

Thanks! Very impressed with this project.

**Comment by georgeangeletos** [comment]
We have just experienced the same behavior when upgraded to 2.4.5 from 2.4.3. There haven't been a change of the pool configuration. Downgrading back to 2.4.3 resolved the issue.

Java 8, Spring 3.2.x, PostgresSQL JDBC 9.4.1208
 
Thank you.

**Comment by nitincchauhan** [comment]
@georgeangeletos can you please check with 2.4.6 too and confirm ?

**Comment by eugene-kamenev** [comment]
We are using HikariCP 2.4.3 and same situation. Once a week this situation occurs, nothing strange at database logs. 

Environment:

Java 8, Spring 4.2.5, PostgresSQL JDBC 9.4.1207

**Comment by brettwooldridge** [comment]
@everybody Please upgrade to 2.4.6, 2.4.5 had a serious issue regarding connection retirement and replacement.

If you still see errors on 2.4.6, we are willing to investigate, but too many times we've spent many hours investigating an issue only to discover that it was already fixed.

**Comment by georgeangeletos** [comment]
@brettwooldridge We have been using 2.4.6 for the last two weeks in dev and uat and the issue seems fixed. Thanks you.

**Comment by liamchristopher** [comment]
@brettwooldridge We're still getting this issue with 2.4.7, but I think I have a little more insight:

In an isolated load test the pool acts properly. This is using ab to hit a URL doing a single DB lookup, and running hundreds of thousands of requests with a high concurrency.

However, in larger load tests, we see Tomcat choke, and several of our apps clients (http, sql, hbase) all start having connection issues. I suspect its an issue of socket exhaustion, and we're working on fixing why certain boxes get overloaded.

When this happens, the other services recover, but each connection then gets these:

> 2016-07-26 20:21:30,200 [http-apr-7305-exec-488] DEBUG com.zaxxer.hikari.pool.HikariPool - Read-Only-Pool - Timeout failure stats (total=0, active=0, idle=0, waiting=2)
>2016-07-26 20:21:30,201 [http-apr-7305-exec-488] WARN  org.hibernate.engine.jdbc.spi.SqlExceptionHelper - SQL Error: 0, SQLState: null
>2016-07-26 20:21:30,201 [http-apr-7305-exec-488] ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper - Read-Only-Pool - Connection is not available, request timed out after 10000ms.

So, the DB is fine. Other boxes are hitting it fine, and the other clients and apps have all recovered, but the pool now continuously times out trying to get new connections. These expire, and the pool tries to add more than timeout, and so forth, but the connections don't seem to ever go outbound.

This is a pool size 10 going to a VIP fronting a small cluster of Read-Only slaves. We have another pool that goes to a single master and does not exhibit this behavior, but is configured identically.

I turned the timeouts to lower levels, and this just makes the box fail more quickly. After they timeout or are closed they just never re-attach.

So again, to stress, this happens under heavy load, but not necessarily under heavy DB calls.
It seems like once it fails getting a socket out, that no more connections can be created. 

I know this is different from the title line, but its the same behavior. Any ideas why this would happen under mysql?

**Comment by liamchristopher** [comment]
Closing this. The issue is that the Adder thread is getting blocked during heavy events and it looks like our LB is holding the connection and not timing out. This blocks the adder thread from creating a  new pool entry and then the rest of the pool expires with MaxLifetime, leaving the pool empty. I have a more concise thread dump and will open a new issue if we can't tune this one away.
