### ISSUE TITLE
Question : is the connection handed out by the pool wrapped with a wrapper class?

### ISSUE THREAD

**Issue by mhisoft** [brettwooldridge/HikariCP#605]
is the connection handed out by the pool wrapped with a wrapper class? if so what is that wrapper?
thanks,
Tony

**Comment by brettwooldridge** [comment]
Connections are wrapped with a class called HikariProxyConnection.  But your code shouldn't need to know that.  You can call the Connection.unwrap() method with the real connection class to gat a reference to the underlying instance.

**Comment by mhisoft** [comment]
Thanks. 
sorry a following up question, are the PrepareStatement, ResultSet etc also wrapped? the  reason I am asking is we current also wrap the connections and some times in the code it check whether the "statement instanceof xx" so would like to know some details.  And there are cases we need to unwrap to get to the delegate.

**Comment by brettwooldridge** [comment]
Yes, Statement (and subclasses), and ResultSet are also wrapped.
