### ISSUE TITLE
Connection timeout not honored when connection close hangs and caller runs

### ISSUE THREAD

**Issue by dannypurcell** [brettwooldridge/HikariCP#607]
First off, thank you so much for creating and open sourcing this project! It is a joy to see something so well thought out and optimized!
When we switched from Oracle's UCP to Hikari it was was pretty much a drop in replacement with immediate performance and stability improvements.

I logged this to get your opinion on a possible change to the connection closing strategy.
Using `ojdbc6:11.2.0.4` and `HikariCP:2.4.3` with the default `connectionTimeout` set we found that the [closeConnection](https://github.com/brettwooldridge/HikariCP/blob/dev/src/main/java/com/zaxxer/hikari/pool/HikariPool.java#L172) call in `getConnection` can cause the caller to wait longer than the `connectionTimeout` if the close is [run by the caller](https://github.com/brettwooldridge/HikariCP/blob/dev/src/main/java/com/zaxxer/hikari/pool/HikariPool.java#L122) and hangs.
In our usage this happened whenever Hikari noticed a time change on the box and soft evicted all connections.

To get around this for now we decided to reflect on `HikariPool` and set `setMaximumPoolSize` for `closeConnectionExecutor` to `maximumPoolSize` or greater.
What do you think of adding a configuration slot to control the pool/queue size of the `closeConnectionExecutor` or having the built in value set to `maximumPoolSize`?

Thanks again!

**Comment by nitincchauhan** [comment]
@dannypurcell 
please upgrade to 2.4.5 it contains fix for time change and other related issues

**Comment by brettwooldridge** [comment]
@dannypurcell As @nitincchauhan said, this issue was likely fixed in 2.4.5, please reopen this issue if you are still experiencing issues.

**Comment by dannypurcell** [comment]
Thanks for the tip @nitincchauhan, the time change issue is resolved in the new version.
 
@brettwooldridge  I would still like to get your thoughts on the configuration for `closeConnectionExecutor`. We would like to be able to rely on the `getConnection` timeout even when `connection.close` is hanging for a long time. 

We traced our issue back to a firewall that was dropping the connection without saying anything to either side. When coupled with a really long default tcpKeepAlive setting in RedHat (2hr), this behavior from the firewall resulted in our oracle driver blocking for 2hrs while trying to send the close request. 

Since the close request can end up running on a thread that is calling `getConnection`, that thread will be the one to hang past the connectionTimeout any time there is a network hang and the pool has evicted more than 5 connections.

**Comment by skjolber** [comment]
@dannypurcell were you able to resolve the firewall drop scenario?

**Comment by dannypurcell** [comment]
@skjolber we were able to mitigate the issue by enabling tcp keep alive probes in the Oracle connection string, and setting the tcp keep alive config for the os to something more reasonable for this use case. We also continue to force the Hikari pool to allow enough closing threads so we can further guarantee that 'getConnection' will not hang in case we missed something. 
@willgorman if you guys don't mind, can you post the snippets showing our Hikari pool initialization hack, the tcp keep alive settings for redhat, and the setting you found for tcp keep alive in the Oracle connection string?
