### ISSUE TITLE
Authentication error leads to very frequent re-connection attempts

### ISSUE THREAD

**Issue by sudheerit** [brettwooldridge/HikariCP#608]
This is in reference to issue raised by Timm, we too faced this issue in our production environment.

(https://groups.google.com/forum/#!topic/hikari-cp/YeweOvoTPOU)

HIkariCP pool is started and we used it for several days in our application. But other DBA changed the passwords of oracle, and which they don't know our application is using this. And it is trying to connect with old credentials very frequently which is causing connection locked (ORA-28000).

Is there a way to shutdown the pool based on exception or if number of times that it hit the database which results error? Or a filter which give us the control so that we will do what ever based on the requirements?

If a user using any screen which calls getConnection(), then we can shutdown the pool based on exception? But now in this case, no one is using the application and application keep on trying to get connection where we don't have handle of it.

**Comment by brettwooldridge** [comment]
This sounds like a pretty severe business process issue.  How is it that a production application is using a database without the DBAs being aware of it?  There are several solutions for this that do not involve modifications to HikariCP, the simplest of which is log file monitoring.
