### ISSUE TITLE
Low level error.  

### ISSUE THREAD

**Issue by raymorehead** [brettwooldridge/HikariCP#609]
This is with HikariCP 4.5, Oracle java 8.77.  postgres 9.5, jdbc 9.4.1208.jre7

[info] Update0 defined at Location.scala:38
[info]   insert into Locations (location_identifier,slot)
[info]   values
[info]   (?, ?)
[error]   x SQL Compiles and Typechecks
[error]    x Illegal type at constant pool entry 169 in class
[error]      com.zaxxer.hikari.proxy.PreparedStatementJavassistProxy
[error]    Exception Details:
[error]    
[error]      Location:
[error]    
[error]      com/zaxxer/hikari/proxy/PreparedStatementJavassistProxy.getLargeUpdateCount()J
[error]      @1: invokespecial
[error]     Reason:
[error]     Constant pool index 169 is invalid
[error]     Bytecode:
[error]    
[error]      0x0000000: 2ab7 00a9 ad4c 2a2b b600 1bbf 
[error]     Exception Handler Table:
[error]     bci [0, 5]
[error]      => handler: 5
[error]     Stackmap Table:
[error]     same_locals_1_stack_item_frame(@5,Object[#17]) (specs2.scala:64)
[info] 
[info] 
[info] Total for specification LocationTest
[info] Finished in 8 ms
[info] 1 example, 1 failure, 0 error

**Comment by brettwooldridge** [comment]
@raymorehead What version of HikariCP?  The ``PreparedStatementJavassistProxy`` class no longer exists in 2.4.5, there may be an extraneous JAR file or another dependency pulling in an older version of HikariCP.

**Comment by raymorehead** [comment]
Thanks ever so much.  That makes total sense.  I did think of that (looks
like this bug was floating around a year or two ago).  I tried to clean out
old versions, but I guess not ha ha.

Ray



On Tue, Apr 12, 2016 at 10:14 AM, Brett Wooldridge <notifications@github.com

**Comment by brettwooldridge** [comment]
@raymorehead Glad you got it working.
