### ISSUE TITLE
How to connect to Oracle Database using Schema(Alias)? 

### ISSUE THREAD

**Issue by dornala** [brettwooldridge/HikariCP#617]
Hi fellow dev's,

This can me listed as Question!

   I came across this issue most recently. I am not sure it's from HikariCP or Oracle or Spring Boot. When I try to use schema from datasource.schema I am getting an error. HikariCP starts but fails immediatly saying property schema doesn't exist. Now how are we supposed to use schema in oracle databases?
driver class name : oracle.jdbc.pool.OracleDataSource

>main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Started.

>  main] com.zaxxer.hikari.util.PropertyElf       : Property schema does not exist on target class oracle.jdbc.pool.OracleDataSource
(I know I can't set up schema for HikariCP! How now?)

Is it at all possible to connect to oracle database using schema(alias) using HikariCP?

**Comment by nitincchauhan** [comment]
set hikariCP property:
connectionInitSql=alter session set current_schema=<xyz>

**Comment by dornala** [comment]
wow cool. That worked out. Thank you @nitincchauhan
