### ISSUE TITLE
Missing housekeeping debug.

### ISSUE THREAD

**Issue by cunningb** [brettwooldridge/HikariCP#622]
I first noticed that after letting my application idle, with no calls to the database, that my next call to getConnection would be quite slow, ~15 seconds. After I enabled debug logging using:

```
		<dependency>
			<groupId>ch.qos.logback</groupId>
			<artifactId>logback-classic</artifactId>
			<version>1.1.7</version>
			<scope>compile</scope>
		</dependency>
```
```
((Logger) LoggerFactory.getLogger(Logger.ROOT_LOGGER_NAME)).setLevel(Level.ALL);
```

I noticed that I was getting no house keeping debug. Running version 2.4.5 my logs looked like:
http://pastebin.com/PD7LeP18

When I pull/build the dev branch, version 2.4.6-SNAPSHOT, and then change my project dependency to that, my logs change to:
http://pastebin.com/J9qm17sJ

My connection timeout is quite low in these logs because I was trying to debug my issue earlier.
I'm running Java 1.8.0 update 11, and I also tried pulling the HikariCP 2.4.5 tagged commit so I could build that, but I received the same lack of debug as the 2.4.5 in the maven repo.

I have also checked using 2.4.4 and 2.4.3
2.4.4 still does not show up in the logs
2.4.3 does have logs

**Comment by brettwooldridge** [comment]
@cunningb In 2.4.5 we completely broke the housekeeper.  Yesterday 2.4.6 was published, and should contain a fix for this issue. Can you try it?

**Comment by cunningb** [comment]
I just tried 2.4.6 and it does work.

Thank you for your time

**Comment by simran66** [comment]
@brettwooldridge : Similar issue : https://github.com/brettwooldridge/HikariCP/issues/1364 Could you have a look please?
