### ISSUE TITLE
Connection reuse when read only query

### ISSUE THREAD

**Issue by bhuvangu** [brettwooldridge/HikariCP#623]
https://github.com/swaldman/c3p0/issues/70
Is there something  in hikaricp world for the problem/suggestion mentioned in link

**Comment by brettwooldridge** [comment]
@bhuvangu If you are using Hibernate, investigate [Multi-tenancy](https://docs.jboss.org/hibernate/orm/4.3/devguide/en-US/html/ch16.html) support.  Configure one "tenant" to use a DataSource that is readOnly, and another to use a read/write DataSource.
