### ISSUE TITLE
Turning On/Off and monitoring Leak Detection via JMX

### ISSUE THREAD

**Issue by roytmana** [brettwooldridge/HikariCP#626]
This is a nice to have and could be unnecessary but i think it may be very useful for the following reasons:

1. Have not actually measured if but, unless it changed in the newer JVMs, getting a stack trace was fairly expensive operation. So capturing stack trace at a place where connection is obtained could add a non trivial overhead to it making having detection always ON a costly option 
2. More importantly because there is no way to marking a specific connection as "long running" to avoid false positives, I would not want to have leak monitoring to be turned on by default but only in Development/QA or if I have issues in production

So I propose

Test if getting stack trace adds an appreciable overhead and if so:
1. have a separate config option to enable/disable it so that stuck connection would be reported but without stack trace if desired
2. Have a JMX method to set leakDetectionThreshold value and thus turn detection ON and OFF

For production monitoring, alerting and debugging:
1 Add JMX attribute for number of leaked connections and optionally JMX call to re-set it to zero
2. Add JMX attribute that returns list (text) of leaked connections with stack trace

This would allow monitoring for leaks and troubleshooting without having to mine logs 

thanks
alex

**Comment by brettwooldridge** [comment]
The leak detection threshold is already settable via JMX see [HikariConfigMXBean](https://github.com/brettwooldridge/HikariCP/blob/dev/src/main/java/com/zaxxer/hikari/HikariConfigMXBean.java).
