### ISSUE TITLE
It's throwing IllegalStateException. I am confused where/what am I doing wrong?

### ISSUE THREAD

**Issue by niraj315** [brettwooldridge/HikariCP#633]
2:04:53.561 [HikariPool-16 housekeeper] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-16 - Pool stats (total=20, active=1, idle=19, waiting=0)
12:05:23.562 [HikariPool-16 housekeeper] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-16 - Pool stats (total=20, active=1, idle=19, waiting=0)
12:05:53.562 [HikariPool-16 housekeeper] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-16 - Pool stats (total=20, active=1, idle=19, waiting=0)
12:06:23.563 [HikariPool-16 housekeeper] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-16 - Pool stats (total=20, active=1, idle=19, waiting=0)
12:06:53.563 [HikariPool-16 housekeeper] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-16 - Pool stats (total=20, active=1, idle=19, waiting=0)
12:07:23.564 [HikariPool-16 housekeeper] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-16 - Pool stats (total=20, active=1, idle=19, waiting=0)
May 26, 2016 12:07:26 PM org.apache.catalina.loader.WebappClassLoader loadClass
INFO: Illegal access: this web application instance has been stopped already.  Could not load com.zaxxer.hikari.pool.HikariPool$1.  The eventual following stack trace is caused by an error thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access, and has no functional impact.
java.lang.IllegalStateException
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1566)
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1526)
	at com.zaxxer.hikari.pool.HikariPool.closeConnection(HikariPool.java:424)
	at com.zaxxer.hikari.pool.HikariPool.softEvictConnection(HikariPool.java:537)
	at com.zaxxer.hikari.pool.HikariPool.access$200(HikariPool.java:66)
	at com.zaxxer.hikari.pool.HikariPool$2.run(HikariPool.java:453)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

12:07:53.564 [HikariPool-16 housekeeper] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-16 - Pool stats (total=20, active=1, idle=19, waiting=0)
12:08:23.565 [HikariPool-16 housekeeper] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-16 - Pool stats (total=20, active=1, idle=19, waiting=0)
12:08:53.565 [HikariPool-16 housekeeper] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-16 - Pool stats (total=20, active=1, idle=19, waiting=0)
12:09:23.566 [HikariPool-16 housekeeper] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-16 - Pool stats (total=20, active=1, idle=19, waiting=0)
12:09:53.567 [HikariPool-16 housekeeper] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-16 - Pool stats (total=20, active=1, idle=19, waiting=0)
12:10:23.567 [HikariPool-16 housekeeper] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-16 - Pool stats (total=20, active=1, idle=19, waiting=0)
12:10:53.568 [HikariPool-16 housekeeper] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-16 - Pool stats (total=20, active=1, idle=19, waiting=0)
12:11:23.568 [HikariPool-16 housekeeper] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-16 - Pool stats (total=20, active=1, idle=19, waiting=0)
12:11:53.569 [HikariPool-16 housekeeper] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-16 - Pool stats (total=20, active=1, idle=19, waiting=0)
12:12:23.569 [HikariPool-16 housekeeper] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-16 - Pool stats (total=20, active=1, idle=19, waiting=0)
12:12:53.570 [HikariPool-16 housekeeper] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-16 - Pool stats (total=20, active=1, idle=19, waiting=0)
12:13:23.570 [HikariPool-16 housekeeper] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-16 - Pool stats (total=20, active=1, idle=19, waiting=0)
12:13:53.571 [HikariPool-16 housekeeper] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-16 - Pool stats (total=20, active=1, idle=19, waiting=0)
12:14:23.572 [HikariPool-16 housekeeper] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-16 - Pool stats (total=20, active=1, idle=19, waiting=0)
12:14:53.572 [HikariPool-16 housekeeper] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-16 - Pool stats (total=20, active=1, idle=19, waiting=0)

**Comment by brettwooldridge** [comment]
You need to investigate how to shutdown HikariCP (call close() on the HikariDataSource) when you web app undeploys.
