### ISSUE TITLE
About hikaricp multiple data sources

### ISSUE THREAD

**Issue by molele2** [brettwooldridge/HikariCP#635]
I have some code:

       <bean id="hikariConfig" class="com.zaxxer.hikari.HikariConfig">
              <property name="poolName" value="springHikariCP"/>
              <property name="connectionTestQuery" value="SELECT 1"/>
              <property name="dataSourceClassName" value="com.mysql.jdbc.jdbc2.optional.MysqlDataSource"/>
              <property name="maximumPoolSize" value="50"/>
              <property name="idleTimeout" value="30000"/>
              
              
              allowMultiQueries=true"/>-->
              
              <property name="dataSourceProperties">
                     <props>
                            <prop key="url">jdbc:mysql://192.168.0.153:3306/warunion?allowMultiQueries=true</prop>
                            <prop key="user">root</prop>
                            <prop key="password">198456</prop>
                     </props>
              </property>
       </bean>

       <bean id="mallConfig" class="com.zaxxer.hikari.HikariConfig">
              <property name="poolName" value="springHikariCP"/>
              <property name="connectionTestQuery" value="SELECT 1"/>
              <property name="dataSourceClassName" value="com.mysql.jdbc.jdbc2.optional.MysqlDataSource"/>
              <property name="maximumPoolSize" value="50"/>
              <property name="idleTimeout" value="30000"/>

              <property name="dataSourceProperties">
                     <props>
                            
                            <prop key="url">jdbc:mysql://192.168.0.152:3306/gomall?allowMultiQueries=true</prop>
                            <prop key="user">root</prop>
                            <prop key="password">198456</prop>
                     </props>
              </property>
       </bean>

       <bean id="dataSource" class="com.zaxxer.hikari.HikariDataSource">
              <constructor-arg ref="hikariConfig"/>
       </bean>

       <bean id="mallDataSource" class="com.zaxxer.hikari.HikariDataSource">
              <constructor-arg ref="mallConfig"/>
       </bean>

       <bean name="jdbcQuery1" class="com.union.talksocket.jdbc.JdbcQuery">
              <property name="dataSource" ref="mallDataSource" />
       </bean>

 <bean name="jdbcQuery" class="com.union.talksocket.jdbc.JdbcQuery">
              <property name="dataSource" ref="dataSource" />
       </bean>

it should connection difference datasource，but connection same datasource，I don't know this why

**Comment by brettwooldridge** [comment]
@molele2 Please enable debug logging, if after seeing the logs you cannot determine the problem, please post the log here.
