### ISSUE TITLE
waitUntilSequenceExceeded blocks

### ISSUE THREAD

**Issue by gitbalaji** [brettwooldridge/HikariCP#636]
Class: com.zaxxer.hikari.util.QueuedSequenceSynchronizerMethod: waitUntilSequenceExceeded

Blocks and waits for 20 seconds before it gives database connection,this is happening when using Hikari CP in cloud foundry have you guys encountered any issue like this ?.

**Comment by brettwooldridge** [comment]
@gitbalaji Can you enable debug logging, and post the log here?

**Comment by ItsHarry** [comment]
Experienced the same issue I think, profiling showing 20% of CPU Time spent on waitUntilSequenceExceeded during a lag spike.

**Comment by brettwooldridge** [comment]
@ItsHarry 20% of CPU time, and %20 of wall-clock time are very different.  If 20% of the CPU is truly being spend in ``tryAcquireSharedNanos()`` that would be a bug in the JVM (read: unlikely).  20% of *wall-clock* time is not unexpected, as the thread(s) are blocked waiting for connections to either be created or freed.

If there are *available idle* connections, and code is still spinning in waitUntilSequenceExceeded / tryAcquireSharedNanos, that would constitute a bug in HikariCP.

**Comment by ItsHarry** [comment]
You're probably right, I'm going to try increasing connection pool size. Thanks

**Comment by johnou** [comment]
@gitbalaji thread dump would be interesting too.

**Comment by brettwooldridge** [comment]
@gitbalaji @ItsHarry Can you try the snapshot build [referenced here](https://github.com/brettwooldridge/HikariCP/issues/714#issuecomment-246758716) to see if the behavior changes?

**Comment by ItsHarry** [comment]
Sorry I'm not monitoring my application anymore since the performance stabilized, so I don't know if the waits are still happening. Perhaps @gitbalaji does?
