### ISSUE TITLE
Can we add multiple DS in hikari

### ISSUE THREAD

**Issue by sandeepan** [brettwooldridge/HikariCP#637]
possible use will be that, If I want to use two database instances for failover purpose

**Comment by brettwooldridge** [comment]
@sandeepan HikariCP itself does not support two datasources.  If you are using MySQL it has support for failover configuration in the MySQL driver itself.  If you are using PostgreSQL, there are high availablity drivers available as well.

**Comment by sandeepan** [comment]
Thank you Brent. There are middlewares like pgpool and pgbouncer. But I wanted to avoid another layer because you have one more system to monitor.

Anyways, thanks. Huge Fan. Started using hikari and it's already kicking butt :+1:
