### ISSUE TITLE
Periodical connection alive validation by using a standalone thread 

### ISSUE THREAD

**Issue by kenny319** [brettwooldridge/HikariCP#638]
Some of the connection pools such as dbcp or c3p0 use  a separate thread to validate pooled connections, but HikariCP doesn't. Usually the databases in production will set a connection timeout(i.e. 120 seconds), for some applications having burst traffic might have high response time or even time out, because before the traffic comes in all the pooled connections have been closed by database due to 120 seconds timeout and all the requests have to be queued to wait for the new connections.

So the question is why HikariCP doesn't support the periodical connection alive validation and how we can solve the timeout  or high response time issue when we use HikariCP?

thanks
Kenny

**Comment by brettwooldridge** [comment]
There are two possible approaches with HikariCP.

One is to set maxLifetime to 120 seconds.  This would ensure that connections are retired and replaced before the database timeout.

it is unclear in your scenario whether the 120 seconds is an idle timeout or a maximum lifetime on the database side.

If it is an idle timeout, DBCP and c3p0 would seem to defeat the intent, as they will artificially keep connections from ever going idle but running periodic validation queries.

If it is a maximum lifetime setting, there is no point to running validation queries before then.  Whether the timeout is 120 seconds or 8 hours (the MySQL default) the maxLifetime in HikariCP should be set just shorter than that by 30 seconds or so.

**Comment by kenny319** [comment]
On database(mysql) side we set wait_timeout to 120 seconds. It seems like the maximum lifetime setting cannot solve the issue, because it will close a connection when it reaches its lifetime even if the application is busy in handling database transactions, which will result in open and close connections too frequently and some of the requests' response time will be impacted. 

Actually I am verify curious about why Hikaricp give up the connection liveness test method using in C3P0 or DBCP and how to solve our issue in the above senario.

Looking forward your feedback.
