### ISSUE TITLE
Question about mysql useServerPrepStmts 

### ISSUE THREAD

**Issue by hrchu** [brettwooldridge/HikariCP#640]
The [wiki ](https://github.com/brettwooldridge/HikariCP/wiki/MySQL-Configuration) page says that 

> No longer recommended due to MySQL stability issues...Newer versions of MySQL support server-side prepared statements, this can provide a substantial performance boost.

What does it mean? I should not use this option with any version mysql, or should use the option with specific version mysql, e.g., 5.6 or 5.7 only?

**Comment by brettwooldridge** [comment]
Updated wiki.  MySQL seems to have addressed most of the known issues in recent drivers.

**Comment by hrchu** [comment]
Is there any specific mysql server/dirver version information about this issue?
