### ISSUE TITLE
PropertyBeanSetter Language Problem

### ISSUE THREAD

**Issue by sukrucakmak** [brettwooldridge/HikariCP#641]
Hi,

com.zaxxer.hikari.util.PropertyBeanSetter provides setProperty(Object target, String propName, Object propValue) method.
Line 122 says that "String capitalized = "set" + propName.substring(0, 1).toUpperCase() + propName.substring(1);"

But toUpperCase works according to Locale settings, for example if your computer locale is Turkish, "idleTimeout" property turns into "setİdleTime" beacuse upper "i" is "İ" in Turkish.

You have to change this line according to English locale.

Hikari CP version: 2.3.9

**Comment by brettwooldridge** [comment]
Thanks for the report, issues like this are often missed by English-centric coders.
