### ISSUE TITLE
HikariCP PoolInitializationException missing method

### ISSUE THREAD

**Issue by Zealar** [brettwooldridge/HikariCP#646]
When try to connect to database i pass current server IP, user, pass
`	public final void connect()
	{
		config.setJdbcUrl("jdbc:mysql://" + SERVER + ":3306/" + DATA_BASE);
		config.setUsername(USER);
		config.setPassword(PASS);
		try
		{
			ds = new HikariDataSource(config);
		}
`
Problem here is if connection fail constructor throw PoolInitializationException but that class don't contains "getErrorCode()" in that case need to parse strings to see what happen what is not so cool.

**Comment by brettwooldridge** [comment]
If you call ``getCause()`` on the ``PoolInitializationException`` it should give you the SQLException that caused the failure.
