### ISSUE TITLE
MySQL Connection/DataSource memory leak related to classloading issue

### ISSUE THREAD

**Issue by brmeyer** [brettwooldridge/HikariCP#647]
Hey @brettwooldridge!  It's been a while!  Still a big fan of HikariCP and am using it frequently...

Hit one tricky issue, recently.  Say you have 5 WARs, all of them nearly identical, running in Tomcat 7.  All 5 WARs share identical libraries, so those JARs have been moved out of the WARs and instead solely placed in Tomcat's /lib.

Originally, I was using `setDataSourceName("com.mysql.jdbc.jdbc2.optional.MysqlDataSource")`.  But, since `UtilityElf#createInstance` uses `UtilityElf.class.getClassLoader().loadClass(className)`, that appears to be wrecking havoc and causing the connection/memory leak.  My best guess is HikariCP's JAR residing in Tomcat's /lib results in this call using the server container's ClassLoader, rather than the WAR.  I suspect moving the library JARs back into the WARs would correct things and allow GC to kick in, but this setup is helpful to conserve memory.

Unless I'm missing something, suggestions:

1. In docs (perhaps https://github.com/brettwooldridge/HikariCP/wiki/Configuration), mention that using HikariCP as a shared library, it's recommended to manually build the specific JDBC `DataSource` and provide that to `setDataSource`.
2. Consider adding a `setClassLoader` argument to `HikariConfig`, which would be used in `UtilityElf.class.getClassLoader().loadClass(className)`.  This is entirely optional and, arguably, not necessary...

**Comment by brmeyer** [comment]
Actually, it looks like I may be mistaken.  Still experiencing a leak and am trying to nail it down.  Feel free to reject...

**Comment by brettwooldridge** [comment]
@brmeyer ``UtilityElf.class.getClassLoader()`` should get the primary Tomcat classloader, if the HikariCP jar is indeed in the /lib folder.  Let me know where your investigation leads.

**Comment by brmeyer** [comment]
@brettwooldridge, believe I was misunderstanding a few fundamental things about the Tomcat CL vs. WAR CL...

Our specific issue, of course, ended up being caused by the app (Spring Security).  Carry on ;)
