### ISSUE TITLE
Property minimumIdle seems didn't work

### ISSUE THREAD

**Issue by littlepoem** [brettwooldridge/HikariCP#649]
I'm trying to configure hikari by Spring xml,as following.

<bean id="hikariConfigDevelop" class="com.zaxxer.hikari.HikariConfig">

    <property name="driverClassName" value="com.mysql.jdbc.Driver" />
    ...
    <property name="maximumPoolSize" value="100" />
    <property name="minimumIdle" value="20"/>
</bean>

However when I used "show processlist" in mysql command line, there's only one process rather than 20 (the minimumIdle).

I am looking forward to your early reply.
Thank you！

**Comment by brettwooldridge** [comment]
What version of HikariCP?  A similar problem was fixed in 2.4.6.

**Comment by littlepoem** [comment]
@brettwooldridge version 2.4.5  
I switch to 2.4.6 and it's ok now!
Thank you very much!
