### ISSUE TITLE
timeout metric does not seem to be working

### ISSUE THREAD

**Issue by jgangemi** [brettwooldridge/HikariCP#652]
i've seen a couple exceptions thrown in my logs stating a connection could not be obtained due to a timeout, but the metric does not seem to reflect that happening.

**Comment by brettwooldridge** [comment]
@jgangemi Can you provide more specific details, such as log entries and corresponding metrics?  In the case of dropwizard metrics, timeouts are recorded in a ``Meter`` using ``Meter.mark()``.
