### ISSUE TITLE
HikariCP vs redis.

### ISSUE THREAD

**Issue by camdenorrb** [brettwooldridge/HikariCP#658]
How does HikariCP stack up against Redis? What's the speed difference? :3

**Comment by camdenorrb** [comment]
Can someone please change the label, I forgot to :P

**Comment by billoneil** [comment]
HikariCP is a JDBC connection pool. Redis is an in memory datastore / database / cache they are not comparable. Completely different things. Not sure what you are comparing here.

**Comment by camdenorrb** [comment]
Redis can also store persistent data.

**Comment by billoneil** [comment]
HikariCP manages a pool of JDBC database connections. It is not a database itself.

**Comment by camdenorrb** [comment]
Does that provide any performance boost to inserting values into the table?

**Comment by billoneil** [comment]
Read through the [Wiki](https://github.com/brettwooldridge/HikariCP/wiki). Database connection pools in general are made to reduce the overhead of constantly opening / closing database connections by leaving them open and reusing them. HikariCP is highly optimized for this task so if used correctly it could increase performance of inserting to a table by reducing the overhead of opening / closing connections but it depends on your use case.

If you have a single threaded application that opens a db connection and inserts data then closes the connection it won't help you.

If you have a multi threaded application that is constantly reading / writing from the database AND the pool is configured correctly it would improve performance. However the performance strictly comes from managing the connections and utilizing jdbc statement caching (if configured). Making a pool with a bad configuration such as an incorrect pool size could hurt performance.

I'd recommend reading the articles on the Wiki.

**Comment by camdenorrb** [comment]
Thank you I will check it out :)
