### ISSUE TITLE
Request for idle threads to either be validated or recycled given a configured timeout

### ISSUE THREAD

**Issue by stottpaul** [brettwooldridge/HikariCP#659]
As things stand the idleTimeout config does not guarantee to close the connection, i.e. if that would cause the total idle connections in the pool to drop below that specified in minimumIdle.

Would it be possible to alter the behaviour so that it will guarantee to either close or recycle (close and reopen) those idle connections that have timed out?

If that is not possible then could we have a testWhenIdle config, which would run the validation query periodically on idle connections.   This would prevent network devices, or the DB from killing idle connections.

**Comment by brettwooldridge** [comment]
I would suggest setting a lower ``maxLifetime`` in that case.  Both the ``idleTimeout`` and ``maxLifetime`` should be set to a time lower than the database's native timeouts.  If properly configured in that way, HikariCP should never encounter a timed-out connection.
