### ISSUE TITLE
[Postgresql] relation "xxx" does not exist

### ISSUE THREAD

**Issue by Sel8616** [brettwooldridge/HikariCP#660]
org.postgresql.ds.PGSimpleDataSource was used in my project.

The query always fail with the following exception:

> org.springframework.jdbc.BadSqlGrammarException: StatementCallback; bad SQL grammar [SELECT * FROM xxxxxx]; nested exception is org.postgresql.util.PSQLException: ERROR: relation "xxxxxx" does not exist

But it works correctly with bonecp.

**Comment by brettwooldridge** [comment]
That makes no sense.  HikariCP does not parse SQL grammar in any way.

**Comment by Sel8616** [comment]
Thank you for reply.

Maybe that exception was caused by PGAdmin3.
