### ISSUE TITLE
HikariCP treats failed row locking attempt as broken connection

### ISSUE THREAD

**Issue by patric-r** [brettwooldridge/HikariCP#661]
When using an Oracle JDBC driver 12.1.0.2.0 and when trying to lock an (already locked) record using `SELECT .. FOR UPDATE NOWAIT`
HikariCP 2.4.6 now fails with:

```
WARN  (com.zaxxer.hikari.pool.ProxyConnection:150) HikariPool-3 - Connection oracle.jdbc.driver.T4CConnection@16c96c9 marked as broken because of SQLSTATE(61000), ErrorCode(54)
java.sql.SQLException: ORA-00054: resource busy and acquire with NOWAIT specified or timeout expired
```

and evicts the connection:

`DEBUG (com.zaxxer.hikari.pool.PoolBase)  Closing connection oracle.jdbc.driver.T4CConnection@16c96c9 : (connection is broken)`

However, it should be up to the application to deal with failed locking attempts.
HikariCP should neither catch these nor evict the connection from the pool.

Treating SQLState 61000 as a "broken connection" seems to be too broad.
Regression has been introduced within commit 7377726 (HikariCP 2.4.6)

**Comment by brettwooldridge** [comment]
@patric-r I'm not an Oracle guy, maybe you should battle it out with @emiliolg over #611

**Comment by brettwooldridge** [comment]
@patric-r 
```
ORA-02399: exceeded maximum connect time, you are being logged off 

Cause: As stated

Action: none
```
If there is a more specific SQLState or Error Code associated with ORA-02399 we can try to add detection for it.

**Comment by patric-r** [comment]
I vote for treating SQLState 61000 AND error code 2399 as a broken connection and for all other error codes of this SQLState, pass the exception to the application.

**Comment by emiliolg** [comment]
Sounds reasonable

**Comment by brettwooldridge** [comment]
The question is whether error code 2399 is available through ``SQLException.getErrorCode()``.  I have no way of confirming this, maybe one of you does?

**Comment by patric-r** [comment]
I have no experience with error code 2399 but for every other ORA errors I saw the ORA error code matches `getErrorCode()` (so for an ORA-00054 SQLException, getErrorCode() returns 54). Just tested this with ORA-00955 and it works.

**Comment by brettwooldridge** [comment]
@patric-r Great. I'll try to get this change in tomorrow.

**Comment by patric-r** [comment]
@brettwooldridge Thank you.
