### ISSUE TITLE
NPE due to null PoolEntry connection

### ISSUE THREAD

**Issue by AmlingPalantir** [brettwooldridge/HikariCP#664]
We're using Hikari 2.4.5 and while it's mostly been great we did find this
exciting error:

> Caused by: java.lang.NullPointerException
>       at com.zaxxer.hikari.pool.PoolBase.setNetworkTimeout(PoolBase.java:464)
>       at com.zaxxer.hikari.pool.PoolBase.isConnectionAlive(PoolBase.java:131)
>       at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:171)
>       at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:147)
>       at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:83)
> ...

I set out to read the code very closely and my best guess is as follows:

A thread acquires a connection via getConnection.  The same thread close()s the
connection.  Somewhere in the middle of the ProxyConnection.close() try an
SQLException is thrown that will match the check in checkException.  The catch
block in ProxyConnection.close() calls checkException which ultimately calls
PoolEntry.evict -> HikariPool.closeConnection (remove()s the PoolEntry) ->
PoolEntry.close (nulls PoolEntry.connection).  Then the finally block in
ProxyConnection.close() calls PoolEntry.recycle -> HikariPool.releaseConnection
(requite()s the pool entry).  This (remove then requite) seems like a violation
of the ConcurrentBag contract and ultimately the entry is available for the
same thread to check out again.  The thread ultimately eats the SQLException
thrown from close() and ends up calling getConnection again at least 500ms
later.  Now HikariPool.getConnection borrows the null connection pool entry,
and blows the chunks above.

I say "best guess" in that I can produce it almost exactly using H2 and a
little connection intercepting trickery to fake a failure right in the middle.
The only difference from what I produced and the above is that exact fireworks
of null connection in isConnectionAlive() are different for H2 (doesn't support
network timeout).

For stupid reasons it is not trivial for me to repeat the testing with the
latest Hikari but the code as of 21eedd550258 doesn't seem to be altered in any
way obviously relevant to this bug.

**Comment by nitincchauhan** [comment]
same stack trace was reported sometime back on [SO](http://stackoverflow.com/questions/35840631/hikaricp-nullpointerexception)

**Comment by brettwooldridge** [comment]
@AmlingPalantir Thanks for the thorough assessment.

**Comment by nitincchauhan** [comment]
@brettwooldridge IMHO null check would hide the actual problem and degrade performance.
proper fix would have been ...call to markEvicted() from PoolEntry#evict().

**Comment by brettwooldridge** [comment]
@nitincchauhan That is incorrect.  If a thread has ownership of a connection (and associated PoolEntry) it should evict definitively rather that merely marking for eviction.

**Comment by AmlingPalantir** [comment]
Bleh, that SO post.  Anyway, thanks for the quick turnaround.
