### ISSUE TITLE
Source files without license headers

### ISSUE THREAD

**Issue by puntogil** [brettwooldridge/HikariCP#665]
Hi

The following source files are without license headers:

./src/main/java/com/zaxxer/hikari/metrics/prometheus/HikariCPCollector.java
./src/main/java/com/zaxxer/hikari/metrics/prometheus/PrometheusMetricsTracker.java
./src/main/java/com/zaxxer/hikari/metrics/prometheus/PrometheusMetricsTrackerFactory.java
./src/main/java/com/zaxxer/hikari/pool/PoolBase.java

./src/test/java/com/zaxxer/hikari/metrics/prometheus/HikariCPCollectorTest.java
./src/test/java/com/zaxxer/hikari/metrics/prometheus/PrometheusMetricsTrackerTest.java
./src/test/java/com/zaxxer/hikari/mocks/StubBaseConnection.java
./src/test/java/com/zaxxer/hikari/pool/ConcurrentCloseConnectionTest.java
./src/test/java/com/zaxxer/hikari/pool/ConnectionRaceConditionTest.java
./src/test/java/com/zaxxer/hikari/pool/ConnectionStateTest.java
./src/test/java/com/zaxxer/hikari/pool/ExceptionTest.java
./src/test/java/com/zaxxer/hikari/pool/IsolationTest.java
./src/test/java/com/zaxxer/hikari/pool/RampUpDown.java
./src/test/java/com/zaxxer/hikari/pool/StatementTest.java
./src/test/java/com/zaxxer/hikari/pool/TestConnectionCloseBlocking.java
./src/test/java/com/zaxxer/hikari/pool/TestConnectionTimeoutRetry.java
./src/test/java/com/zaxxer/hikari/pool/TestFastList.java
./src/test/java/com/zaxxer/hikari/pool/TestHibernate.java
./src/test/java/com/zaxxer/hikari/pool/TestPropertySetter.java
./src/test/java/com/zaxxer/hikari/pool/TestProxies.java

Please, confirm the licensing of code and/or content/s, and add license headers
https://fedoraproject.org/wiki/Packaging:LicensingGuidelines?rd=Packaging/LicensingGuidelines#License_Clarification

Thanks in advance
Regards

**Comment by brettwooldridge** [comment]
Pull requests welcome.
