### ISSUE TITLE
I have a problem named ：Unknown database 'none'

### ISSUE THREAD

**Issue by zw231212** [brettwooldridge/HikariCP#667]
##### I use mybatis and spring 。My spring config is:

```
<bean id="dataConfig" class="com.zaxxer.hikari.HikariConfig">
    	<!-- <property name="driverClassName" value="${jdbc.driver}"/> -->
		<property name="jdbcUrl" value="${jdbc.url}"/>
		<property name="username" value="${jdbc.username}"/>
		<property name="password" value="${jdbc.password}"/> 
    </bean>
    <bean id="dataSource" class="com.zaxxer.hikari.HikariDataSource" destroy-method="close">
    	<constructor-arg ref="dataConfig"/>
    </bean>
```

##### my db.properties is :
> jdbc.url=jdbc:mysql://127.0.0.1:3306/sharecup?useUnicode=true&characterEncoding=UTF-8
> jdbc.username=root
> jdbc.password=tiger

##### Then I wrote a test:
```
public class UserServiceTest extends TestCase {    
@Autowired
    private UserService userService;

    @Test
    public void testFind() throws Exception {
        User user = userService.find(12);
        System.out.println(user.getId()+"  "+user.getQuestion());
    }

    @Test
    public void testFindAll() throws Exception {
        List<User> users = userService.findAll();
        System.out.println(users.size());
        for (User user :users){
            System.out.println(user.getId());
            System.out.println(user.getUsername());
        }

    }
}
```
##### Then I got an exception :Unknown database 'none',where can I set the database in spring ? how can I fix It ?

**Comment by liester** [comment]
I'm pretty new to the HikairCP library but I would have expected a driverClass to have been defined in the xml configuration of the HikariConfig object.  
In the documentation: https://github.com/brettwooldridge/HikariCP/wiki/Configuration
it seems as through you need to set either the 'dataSourceClassName', or for older drivers the 'driverClassName'.  I am user Oracle and had to use the 'driverClassName' property.

Its possible mySQL just magically works but since it is listed at the bottom of the same article as popular driver classes it might be work a try.

Hope this helps

**Comment by billoneil** [comment]
Enable debug logging for the com.zaxxer.hikari package (in slf4j or
whatever your logging framework is). Then post the content of the config
when the pool initializes.

**Comment by zw231212** [comment]
Thanks gays! I tried another config below ，and it worked。I have tested  the dataSource and  data from mysql，it worked ：
```
    <bean id="dataConfig" class="com.zaxxer.hikari.HikariConfig">
    	<property name="dataSourceClassName" value="com.mysql.jdbc.jdbc2.optional.MysqlDataSource"/>
		<property name="dataSourceProperties">
		    <props>
		    	<prop key="serverName">127.0.0.1</prop>
		    	<prop key="port">3306</prop>
		    	<prop key="databaseName">sharecup</prop>
		    	<prop key="user">${jdbc.username}</prop>
		    	<prop key="password">${jdbc.password}</prop>
		    </props>
		 </property>
    </bean>
    <bean id="dataSource" class="com.zaxxer.hikari.HikariDataSource" destroy-method="close">
    	<constructor-arg name="configuration" ref="dataConfig"/>
    </bean>
```
 I do not know why The first config is not good ! And I will try more later!
