### ISSUE TITLE
Thread starvation or clock leap detected

### ISSUE THREAD

**Issue by svipben** [brettwooldridge/HikariCP#668]
Hello,

using HikariCP 2.4.6 with MariaDB, today got this one:

[HikariPool-1 housekeeper] WARN com.zaxxer.hikari.pool.HikariPool - 1m5s204ms948μs145ns - Thread starvation or clock leap detected (housekeeper delta=HikariPool-1).

**Configs:**
CachePrepStmts: true
PrepStmtCacheSize: 250
PrepStmtCacheSqlLimit: 2048
Maximum DB Connections: 100
Connection Timeout: 30000
Idle Timeout: 600000
Max Lifetime: 1800000

**Comment by brettwooldridge** [comment]
Not really anything to worry about if this rarely occurs.  Basically it indicates a certain amount of CPU starvation. The housekeeper thread is scheduled to run every 30 seconds, but there was over a minute that elapsed between runs.  I wouldn't be too worried unless you see this several times per hour.

**Comment by svipben** [comment]
Thank you very much!

**Comment by svipben** [comment]
I get it again:

[HikariPool-1 housekeeper] WARN com.zaxxer.hikari.pool.HikariPool - 52s6ms871μs872ns - Thread starvation or clock leap detected (housekeeper delta=HikariPool-1).

And I saw after getting this, I get some lag spike for about 2-5s. I mean there was freeze.

**Comment by jgangemi** [comment]
double check and make sure your application is configured w/ the proper amounts. i started seeing this same thing occur in one of my applications and then i realized i had configured `-Xmx` to be higher the the amount of memory on the box.

adjusting those values put everything back to normal.

**Comment by svipben** [comment]
Thanks, I will try edit -Xmx, but I have 8GB VPS and my -Xmx is 6GB, used 'htop' and usage was from everything in RAM category 3,7GB.

**Comment by brettwooldridge** [comment]
If you are on a VPS the thread starvation probably has nothing to do with Java.  Odds are good that the host is over provisioned and another VPS user is periodically saturating all of the CPUs.

I suggest monitoring the memory, CPU, and network (ping) externally, from another host, and looking for starvation periods that correspond to those logged by HikariCP.

**Comment by syamlakkepogu** [comment]
2025-02-28T17:38:47.957+05:30  WARN 16980 --- [l-1 housekeeper] com.zaxxer.hikari.pool.HikariPool        : HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=1h49m4s668ms147µs200ns).
 My application also getting like this. when i was put my pc  "sleep mood" after after "1 hour or 30 mins" open my application . it taken Lot time are and also docker console also stop automatically

**Comment by brettwooldridge** [comment]
@syamlakkepogu This is correct behavior, I'm not sure what you were expecting.
