### ISSUE TITLE
Implementation detail: Why does FastList extend ArrayList?

### ISSUE THREAD

**Issue by DerEineDa** [brettwooldridge/HikariCP#672]
At first glance, it seems like a waste of space that com.zaxxer.hikari.util.FastList extends java.util.ArrayList, as you don't reuse any fields or methods from ArrayList. 

The implementation of an empty ArrayList by Oracle may not use a lot of space, but this is implementation dependant and the fields are using heap space nonetheless.  Why not just extending AbstractList or implementing List directly? Seems like a low hanging fruit to save a few Bytes.

Also, having an instance of ArrayList that is actually a FastList may lead to surprising behaviour, as FastList does not support many operations that are supported by ArrayList.

**Comment by brettwooldridge** [comment]
Pull request welcomed. 😀
