### ISSUE TITLE
PSQLException: Cannot change transaction read-only property in the middle of a transaction.

### ISSUE THREAD

**Issue by uwolfer** [brettwooldridge/HikariCP#674]
After updating from 2.4.1, I get the following exception. After some bisect search, I have found out that the issue got introduced with 2.4.2.

```
Caused by: org.postgresql.util.PSQLException: Cannot change transaction read-only property in the middle of a transaction.
	at org.postgresql.jdbc.PgConnection.setReadOnly(PgConnection.java:724)
	at com.zaxxer.hikari.pool.ProxyConnection.setReadOnly(ProxyConnection.java:388)
	at com.zaxxer.hikari.pool.HikariProxyConnection.setReadOnly(HikariProxyConnection.java)
	at x.y.JdbcBackend.prepareCommit(JdbcBackend.java:135)
```

Some details: I use `readOnly=true` in config, and explicitly disable read-only in specific use-cases where I need write access:

```java
try (Connection conn = ds.getConnection()) {
    conn.setReadOnly(false);
    ...
}
```

I think https://github.com/brettwooldridge/HikariCP/commit/bcde774078e553c363d9e31c0022ace87ca62f71 by @nitincchauhan could have introduced this issue, but I have not verified it. Most probably even reading data with PG JDBC sets the connection transaction state to "unclean".

**Comment by uwolfer** [comment]
@nitincchauhan: Do you remember why you have done the change in commit https://github.com/brettwooldridge/HikariCP/commit/bcde774078e553c363d9e31c0022ace87ca62f71?

**Comment by brettwooldridge** [comment]
@uwolfer Can you try ``IsolateInternalQueries=true``?

**Comment by uwolfer** [comment]
@brettwooldridge: This does not help in my case. The problem is that it fails before committing the "internal" query - it fails when it tries to execute the internal query already when it re-uses a connection which has been used read-only before.

**Comment by uwolfer** [comment]
Interesting part in Postgres JDBC: https://github.com/pgjdbc/pgjdbc/blob/ab2a6d89081fc2c1fdb2a8600f413db33669022c/pgjdbc/src/main/java/org/postgresql/core/v3/ConnectionFactoryImpl.java#L690

This sets the transaction state to open. When no rollback (or commit) is done, it will fail later on here: https://github.com/pgjdbc/pgjdbc/blob/893c1a41bedf56017473194113d335d280992851/pgjdbc/src/main/java/org/postgresql/jdbc/PgConnection.java#L732.

**Comment by brettwooldridge** [comment]
@uwolfer What happens if you set ``connectionInitSql=COMMIT``?

**Comment by uwolfer** [comment]
@brettwooldridge: This does not help. In my case, not newly created connections are the problem - I think only recycled connections are not "clean".

**Comment by nitincchauhan** [comment]
@uwolfer Please write small test case which exhibits same behavior. It would help to resolve issue quicker better.

**Comment by uwolfer** [comment]
@nitincchauhan: Something like [BasicPoolTest.java](https://github.com/brettwooldridge/HikariCP/blob/dev/src/test/java/com/zaxxer/hikari/db/BasicPoolTest.java)? Or is there a better example how you prefer such a test?

**Comment by uwolfer** [comment]
@nitincchauhan: The test below can be used to reproduce this issue.

```java
package test.hikaricp;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Properties;

import com.zaxxer.hikari.HikariConfig;
import com.zaxxer.hikari.HikariDataSource;
import org.junit.Before;
import org.junit.Test;

/**
 * @author Urs Wolfer
 */
public class PgReadOnlyPoolTest {
    private Properties getProperties() {
        Properties properties = new Properties();
        properties.put("dataSourceClassName", "org.postgresql.ds.PGSimpleDataSource");
        properties.put("dataSource.serverName", "postgres");
        properties.put("dataSource.databaseName", "db");
        properties.put("dataSource.user", "user");
        properties.put("dataSource.password", "pw");
        properties.put("maximumPoolSize", "1");
        properties.put("autoCommit", "false");
        properties.put("isolateInternalQueries", "true");
        properties.put("readOnly", "true");
        properties.put("connectionInitSql", "COMMIT");
        return properties;
    }

    @Before
    public void setup() throws SQLException {
        HikariConfig config = new HikariConfig(getProperties());
        try (HikariDataSource ds = new HikariDataSource(config);
             Connection conn = ds.getConnection()) {
            conn.setReadOnly(false);
            try (Statement stmt = conn.createStatement()) {
                stmt.executeUpdate("DROP TABLE IF EXISTS basic_pool_test");
                stmt.executeUpdate("CREATE TABLE basic_pool_test ("
                    + "id BIGSERIAL NOT NULL PRIMARY KEY, "
                    + "timestamp TIMESTAMP, "
                    + "string VARCHAR(128), "
                    + "string_from_number NUMERIC "
                    + ")");
                conn.commit();
            }
        }
    }

    @Test
    public void testSelectFollowedByInsert() throws SQLException {
        HikariConfig config = new HikariConfig(getProperties());
        try (HikariDataSource ds = new HikariDataSource(config)) {
            try (Connection conn = ds.getConnection();
                 Statement stmt = conn.createStatement()) {
                stmt.executeQuery("SELECT * FROM basic_pool_test");
            }
            try (Connection conn = ds.getConnection();
                 Statement stmt = conn.createStatement()) {
                conn.setReadOnly(false); // FAILS: org.postgresql.util.PSQLException: Cannot change transaction read-only property in the middle of a transaction.
                stmt.execute("INSERT INTO basic_pool_test (string) VALUES('foot')");
                conn.commit();
            }
        }
    }
}
```

**Comment by nitincchauhan** [comment]
with setAutocommit( false ), try CLOSE result set too. ie. always cover 'query' in try with resource ....stmt.executeQuery("SELECT * FROM basic_pool_test");
read second bullet https://docs.oracle.com/javase/7/docs/api/java/sql/Connection.html#setAutoCommit(boolean)

**Comment by brettwooldridge** [comment]
@uwolfer I have commited a fix for this.  Ultimately, if you have a read-only connection, you probably should also set ``autoCommit=false``, especially on PostgreSQL.  If you don't set ``autoCommit=false``, with this fix you will still need ``isolateInternalQueries=true``.  You will not need the ``connectionInitSql``.

**Comment by uwolfer** [comment]
@nitincchauhan: Thanks for the hint about closing `ResultSet`. This is of course better handling. Though it still doesn't fix this issue.

@brettwooldridge: Thanks for fixing it. Please note that I'm using `autoCommit=false` in both my example above and my real world code.
