### ISSUE TITLE
Where can I add ThreadContext.put to hit all pool threads for Log42j?

### ISSUE THREAD

**Issue by ToddHoff** [brettwooldridge/HikariCP#675]
Hi,

I'm trying to add a custom parameter to syslog in Log42j. The problem is for this to work I must add ThreadContext.put("NAME", "VALUE") in all the threads that use the logger.

I've tried System.setProperty("isThreadContextMapInheritable", "true") and that doesn't seem to cover all the threads, namely in pools GMS_DB_POOL.pool.PendingConnections, GMS_DB_POOL.pool.ActiveConnections, and GMS_DB_POOL.pool.TotalConnections.

I've tried placing ThreadContext.put() in a few places to no avail. 

Where would I place ThreadContext.put() to make sure all the pool threads have the correct value so when they log using log42j they'll have access to the custom value?

thanks

**Comment by brettwooldridge** [comment]
@ToddHoff Set a custom [threadFactory](https://github.com/brettwooldridge/HikariCP/blob/dev/src/main/java/com/zaxxer/hikari/HikariConfig.java#L737).
