### ISSUE TITLE
CodaHaleMetricsTracker errors if metric exists

### ISSUE THREAD

**Issue by michaelbraun** [brettwooldridge/HikariCP#676]
Was attempting to switch to HikariCP in our project and I'm setting the pool name to be the JDBC URL so we can distinguish between the pools. As a result when I use HikariCP in test code, where the metrics registry in our project is a singleton and the tests are creating multiple pools with the same underlying url in later tests, it errors - 

The crux of the problem comes from com.zaxxer.hikari.metrics.dropwizard.CodaHaleMetricsTracker.java - 

```java
registry.register(MetricRegistry.name(poolName, "pool", "TotalConnections"),
                        new Gauge<Integer>() {
                           @Override
                           public Integer getValue() {
                              return poolStats.getTotalConnections();
                           }
                        });
``` 
(and similar lines)

.register will always through an IllegalArgumentException if the metric already exists. The usage to allow create-or-use-existing is using the meter, counter, histogram, timer, etc functions, which will get or add as needed. On the flip side, changing to accommodate this may allow multiple pools with the same pool name...

**Comment by jnehlmeier** [comment]
IMHO: Refactor your code slightly so you can choose to use a non-singleton during tests.

**Comment by brettwooldridge** [comment]
@jnehlmeier Agreed.  Remove singleton use from tests, [it is an anti-pattern](http://stackoverflow.com/a/2085988/6441113).

**Comment by michaelbraun** [comment]
Will look at untangling. Thanks for your help!
