### ISSUE TITLE
How to enable debug?

### ISSUE THREAD

**Issue by ItsHarry** [brettwooldridge/HikariCP#682]
I compiled my plugin with slf4j-simple and added -Dorg.slf4j.simpleLogger.defaultLogLevel=debug to startup arguments, but the debug messages are not shown?

Am I doing it wrong?

**Comment by brettwooldridge** [comment]
@ItsHarry There is nothing intrinsically wrong with that, if logging is not occurring you are likely running into a separate issue (eg. runtime classpath).  Either way this is a slf4j question, so please check stackoverflow.com.
