### ISSUE TITLE
Connection remains active and active connection count gradually increasing till the maxConnection

### ISSUE THREAD

**Issue by sandeep27st** [brettwooldridge/HikariCP#686]
Recently I made decision to move to HikariCP.  I have done the following set configuration for the pooling.

		HikariConfig config = new HikariConfig();
		Properties properties = new Properties();
		properties.put("MYConnectionMetaData", connectionProperties);
		config.setDataSourceProperties(properties);

		if(Integer.parseInt(name) == 0 || Integer.parseInt(name) == -1){
			config.setConnectionTestQuery(getTestQuery()+name);
		}
		
		config.setPoolName(name);
		
		config.setDataSourceClassName(MyDataSource.class.getName());
		config.setAutoCommit(false);
		config.setMinimumIdle(1);
		config.setMaximumPoolSize(100);
		config.setInitializationFailFast(true);
		config.setConnectionTimeout(0);//client request
		config.setMaxLifetime(9000);//timeout connection evicted
		
		config.setIdleTimeout(9000);// idle time`
		config.setRegisterMbeans(true);
		config.setReadOnly(false);
		config.setValidationTimeout(1200000);
		config.setDataSourceClassName(MyDataSource.class.getName());
		
		setMXBeanContext(config);
		
		helthCheckRegistry(config);
		
		config.validate();
		return new HikariDataSource(config);

After start connection pooling I do nothing with the connection still active connection count gradually increasing till the maxConnection. And the every thing get stuck in between.

Health[Connection Pool= 1,  Healthy Pool, Idle Connection = 4, Active Connection = 0, Total Connection = 4]
Health[Connection Pool= 0,  Healthy Pool, Idle Connection = 1, Active Connection = 56, Total Connection = 57]
....
Health[Connection Pool= -1,  Healthy Pool, Idle Connection = 1, Active Connection = 0, Total Connection = 1]
Health[Connection Pool= 1,  Healthy Pool, Idle Connection = 4, Active Connection = 0, Total Connection = 4]
Health[Connection Pool= 0,  Healthy Pool, Idle Connection = 1, Active Connection = 60, Total Connection = 61]
....
Health[Connection Pool= -1,  Healthy Pool, Idle Connection = 1, Active Connection = 0, Total Connection = 1]
Health[Connection Pool = 1,  Healthy Pool, Idle Connection = 4, Active Connection = 0, Total Connection = 4]
Health[Connection Pool= 0,  Healthy Pool, Idle Connection = 1, Active Connection = 100, Total Connection = 100]

See the connection ConnectionPool 0.

**Comment by brettwooldridge** [comment]
This look like a connection leak.  Can you enable the ``leakDetectionThreshold``?

Plus, this looks weird:
```java
setMaxLifetime(9000);//timeout connection evicted
```
This is not "timeout connection evicted", this is the maximum lifetime of a connection in the pool -- which you have set to 9 seconds.  That is an extraordinarily short lifetime.
