### ISSUE TITLE
Update LICENSE please

### ISSUE THREAD

**Issue by attritionorg** [brettwooldridge/HikariCP#687]
https://github.com/brettwooldridge/HikariCP/blob/dev/LICENSE

From the license:

To apply the Apache License to your work, attach the following boilerplate
notice, with the fields enclosed by brackets "[]" replaced with your own
identifying information. 

Currently says:

Copyright [yyyy] [name of copyright owner]

**Comment by johnou** [comment]
That's the appendix of the license explaining how to apply it to your work, not something that needs to be filled out.

**Comment by attritionorg** [comment]
Where can one find the copyright / vendor name / etc?

**Comment by johnou** [comment]
In each file that the license has been applied eg. https://github.com/brettwooldridge/HikariCP/blob/dev/src/main/java/com/zaxxer/hikari/HikariConfig.java
