### ISSUE TITLE
An error in the wiki page 'Down-the-Rabbit-Hole'

### ISSUE THREAD

**Issue by kenny319** [brettwooldridge/HikariCP#695]
Just noticed the size of the optimised 'checkException' method is still greater than 35 bytes. The correct bytecodes should be as below:

> 0: aload_1
         1: invokevirtual #168                // Method java/sql/SQLException.getSQLState:()Ljava/lang/String;
         4: astore_2
         5: aload_2
         6: ifnull        34
         9: aload_0
        10: dup
        11: getfield      #173                // Field _forceClose:Z
        14: aload_2
        15: ldc           #175                // String 08
        17: invokevirtual #177                // Method java/lang/String.startsWith:(Ljava/lang/String;)Z
        20: getstatic     #69                 // Field SQL_ERRORS:Ljava/util/Set;
        23: aload_2
        24: invokeinterface #183,  2          // InterfaceMethod java/util/Set.contains:(Ljava/lang/Object;)Z
        29: ior
        30: ior
        31: putfield      #173                // Field _forceClose:Z
        34: aload_1
        35: areturn

Another error is the last byte code should be 'areturn' instead of 'return' since the 'checkException' method is not a void method. The return type might be adjusted  from SQLException to VOID in order to demonstrate the great work you do to make HikariCP fast.
(I just found some articles introducing JIT are referencing this wiki page as a great example, so I try to let you know.)

**Comment by brettwooldridge** [comment]
I whacked a lot of the content on that page ... it was written in reference to the Java 7 JIT circa 2013 and some of analysis no longer holds true for Java 8.
