### ISSUE TITLE
utf8mb4 error

### ISSUE THREAD

**Issue by GitDov** [brettwooldridge/HikariCP#699]
I'm trying to set the config.addDataSourceProperty("characterEncoding", "utf8mb4"); but its not working.
Any idea of how to use utf8mb4 on hikari???

**Comment by brettwooldridge** [comment]
@GitDov How is it "not working"?  Is an exception thrown?  If not, it is an issue with the MySQL configuration or database schema.

**Comment by GitDov** [comment]
I received the following error:
com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Unsupported character encoding 'utf8mb4'.

**Comment by goughy000** [comment]
You probably want to read this article
https://dev.mysql.com/doc/connector-j/5.1/en/connector-j-reference-charsets.html

**Comment by alexeyOnGitHub** [comment]
@GitDov I had the same problem with Hikari in my Scala app.
I'm using Scala, JDK8, Mysql JConnector 5.1.40, HikariCP-java6 2.0.1.
the server is set to latin1 by default and ONLY the table I'm interested in is in utf8mb4.
I cannot change the server settings, so I have to configure my client instead.

when I request utf8mb4  in the jdbc URL I get:

>21:01:57.862 [HikariCP connection filler] DEBUG com.zaxxer.hikari.pool.HikariPool - Connection attempt to database HikariPool-0 failed: Unsupported character encoding 'utf8mb4'.
> java.sql.SQLException: Unsupported character encoding 'utf8mb4'.
> 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:964) ~[mysql-connector-java-5.1.40.jar:5.1.40]
 
I found a solution|workaround:

`    hikariConfig.setConnectionInitSql("SET NAMES utf8mb4")
`

**Comment by VitorHugoDS** [comment]
I had done some SQL adjusts to support utf8mb4. But that wasn't enough.
@alexeyOnGitHub 's solution just ended a 45min quest for answers here.
Thanks!

**Comment by amanullah92** [comment]
This will not work with certain versions of MySQL/driver combinations. If the connection sets the charset first before initSQL is fired, it will not do anything.

https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-reference-charsets.html

I ended up setting datasource property: characterEncoding=UTF-8 to get it to work.

**Comment by amanullah92** [comment]
> I'm trying to set the config.addDataSourceProperty("characterEncoding", "utf8mb4"); but its not working.
> Any idea of how to use utf8mb4 on hikari???
characterEncoding=UTF-8 

https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-reference-charsets.html

As mentioned in the doc. use the Java name convention for utf8, which is UTF-8
