### ISSUE TITLE
Track number of conections opened

### ISSUE THREAD

**Issue by GitDov** [brettwooldridge/HikariCP#700]
Is any way to track how many conections of the pool is being used at the same time?

**Comment by brettwooldridge** [comment]
@GitDov With either [JMX](https://github.com/brettwooldridge/HikariCP/wiki/MBean-(JMX)-Monitoring-and-Management) or [Dropwizard](https://github.com/brettwooldridge/HikariCP/wiki/Dropwizard-Metrics).
