### ISSUE TITLE
Consider relaxing the check between dataSourceClassName and driverClassName

### ISSUE THREAD

**Issue by snicoll** [brettwooldridge/HikariCP#701]
If one sets both these properties, they'll get:

```
Caused by: java.lang.IllegalArgumentException: cannot use driverClassName and dataSourceClassName together.
    at com.zaxxer.hikari.HikariConfig.validate(HikariConfig.java:770) ~[HikariCP-2.4.7.jar:na]
```

See https://github.com/spring-projects/spring-boot/issues/6568

As you are aware already, Spring Boot will automatically set the `driverClassName` value. This is a convenience for the user: we detect the driver based on the jdbc url. Once Spring Boot has initialized the `HikariDataSource`, it can further be tuned via our `spring.datasource.hikari` configuration namespace.

Considering it makes sense that someone set url/driver/user/pass and then after changes his mind and set `dataSourceClassName`, how about relaxing that check so that the last set wins? If the user defines a `spring.datasource.hikari.data-source-class-name`, that value will be used rather than the driver class name that was set automatically.

The reason I am asking here rather than trying to fix that on our side is that I have no guarantee that this will happen: as a user you could create a custom `HikariDataSource` on whatever namespace you want (e.g. `app.my-datasource`) or no namespace at all. So I couldn't look for `spring.datasource.hikari.data-source-class-name` in the environment because a user may have customized that so that `app.my-datasource.data-source-class-name` should be used instead. There's no way for me to know that; I shouldn't really.

**Comment by brettwooldridge** [comment]
@snicoll There are two problems that arise in trying to implement this.

HikariCP does not impose any order on calls to ``HikariConfig``, and does not validate the properties until the ``HikariDataSource`` is constructed (or ``getConnection()`` is called when ``HikariConfig`` is not used).

This is for two reasons.  One, user's should be able to call ``HikariConfig.setMinimumIdle()`` before calling ``HikariConfig.setMaximumPoolSize()``.  The constraint is that minimumIdle must be less than maximumPoolSize, but that can temporarily not be the case during configuration.

Two, if the user constructs a configuration with the ``HikariConfig(Properties properties)`` constructor or uses ``HikariConfig. setDataSourceProperties(Properties properties)``, the order of iteration over the properties is non-deterministic.  In this case, there is no "last set wins" that is meaningful to the user.

The reason the constraint exists, and causes a failure, is that for many drivers there is not a one-to-one mapping between properties honored by the Driver and setters on the DataSource.

For example, when using a Driver the setting might be:
```java
hikariConfig.addDataSourceProperty("auto-commit", "true");
```
but when configuring a DataSource for the same driver might be:
```java
hikariConfig.addDataSourceProperty("autoCommit", "true");
```
If the former is used with a DataSource a Runtime exception would be thrown ("Property X does not exist on target Y").

You say:
> Considering it makes sense that someone set url/driver/user/pass and then after changes his mind and set dataSourceClassName, how about relaxing that check so that the last set wins?

I'm not sure that does make sense.  What is the harm in failing in this case?  Given that Spring Boot automatically sets the driver URL, why not disallow *"spring.datasource.hikari.data-source-class-name"* across the board?

**Comment by snicoll** [comment]
Thanks for the explanation!

> Given that Spring Boot automatically sets the driver URL, why not disallow "spring.datasource.hikari.data-source-class-name" across the board?

I already explained why:

> I have no guarantee that this will happen: as a user you could create a custom HikariDataSource on whatever namespace you want (e.g. app.my-datasource) or no namespace at all. So I couldn't look for spring.datasource.hikari.data-source-class-name in the environment because a user may have customized that so that app.my-datasource.data-source-class-name should be used instead. There's no way for me to know that;

OK, how about changing the error message so that you indicate the values that have been set? It would help users figuring out that the other value isn't set in their configuration, giving them a chance to get Spring Boot did.

**Comment by brettwooldridge** [comment]
@snicoll We can clarify the message, but I'm still not sure that it will help a Spring Boot user figure out the configuration issue, because they never explicitly specify a *driverClassName*.

I will say that I find the Spring Boot auto-detection to be a bit too clever by half.  The ``driverClassName`` is actually optional in HikariCP, as the JDBC driver manager is capable of resolving the driver based on the JDBC URL for nearly all modern drivers though the ``META-INF/services/java.sql.Driver`` mechanism:
```java
Driver driver = DriverManager.getDriver(jdbcUrl);
```
The issue that auto-detecting the driver class presents is that there are alternate drivers for databases that accept the same JDBC URL.  For example, the [MariaDB JDBC driver](https://mariadb.com/kb/en/mariadb/about-mariadb-connector-j/#connection-strings) will happily handle URLs of the form *jdbc:mysql://database...*  But if Spring Boot is going to automatically resolve URLs of that form to a driverClassName of ``com.mysql.jdbc.Driver`` instead, it will fail.

**Comment by snicoll** [comment]
I am not sure either but I think it would be better than the current situation. I've created an issue for your suggestion, thank you for that. Not sure it has any relationship with my request, though :)

**Comment by brettwooldridge** [comment]
@snicoll I will change the message to, eg
``cannot use driverClassName (com.mysql.jdbc.Driver) and dataSourceClassName (com.mysql.jdbc.jdbc2.optional.MysqlDataSource) together``.

If I were to formalize my suggestions to Spring Boot it would be:

1. Make ``url`` optional.
2. If ``url`` is present and HikariCP is the pool, do not set the ``driverClassName``.  Let HikariCP figure it out.  If HikariCP cannot, it will fail with an exception ``Failed to get driver instance for jdbcUrl=...``.
3. The user should be able to specify a ``driverClassName`` explictly, bypassing detection (both HikariCP's and Spring Boot's).

**Comment by brettwooldridge** [comment]
@snicoll Hey Stephane, I was just watching you on youtube at Spring IO.  Just before you came on stage, Phil was presenting about how Spring Boot 1.4 can classify exception stacktraces and present the user with human readable suggestions.  Why not write a classifier for this particular exception?  Or if you'd like, point me at where I can contribute it.

**Comment by snicoll** [comment]
Hehe. I did showcase that in the demo as well with some live explanations. Funnily enough, I was considering doing that actually. If you want to contribute it, you're more than welcome. See https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc

**Comment by snicoll** [comment]
> If I were to formalize my suggestions to Spring Boot it would be:

Life is complicated. `url` is optional. We use the lack of an explicit url to look for an embedded database. So the deal with boot is that if you set an explicit url we're going to use that to connect to the database. If you don't, we'll start looking for an embedded database on the classpath and configure that. This behaviour is well known and works very well in scenario where you're happy to just have an embedded database (i.e. for testing).

I am afraid the failure analyzer is the only thing left at this point. Maybe @wilkinsona has another idea?

**Comment by brettwooldridge** [comment]
@snicoll What about the idea of not setting the driverClassName in the case when HikariCP is the pool?

**Comment by snicoll** [comment]
We don't like that idea, sorry. The `FailureAnalyzer` looks like a good candidate even though I am not sure that it is that frequent to warrant it.

**Comment by brettwooldridge** [comment]
@snicoll That is understandable, HikariCP also allows ``jdbcUrl`` and ``driverClassName`` to be specified at the same time.  Of course, in that case we load the driver class and [test whether it accepts](https://github.com/brettwooldridge/HikariCP/blob/dev/src/main/java/com/zaxxer/hikari/util/DriverDataSource.java#L83) the URL.  Is there a way for Spring Boot to detect when the a ``dataSourceClass`` has been specified, and omit the setting of the ``jdbcUrl`` in that case?

**Comment by snicoll** [comment]
> Is there a way for Spring Boot to detect when the a dataSourceClassName has been specified

We had that conversation before. The answer is no, per:

> The reason I am asking here rather than trying to fix that on our side is that I have no guarantee that this will happen: as a user you could create a custom HikariDataSource on whatever namespace you want (e.g. app.my-datasource) or no namespace at all. So I couldn't look for spring.datasource.hikari.data-source-class-name in the environment because a user may have customized that so that app.my-datasource.data-source-class-name should be used instead. There's no way for me to know that;

**Comment by brettwooldridge** [comment]
@snicoll Ah, right, sorry.  I'm more than happy to contribute a FailureAnalyzer if you think it will help avoid support issues on your end.

**Comment by snicoll** [comment]
@brettwooldridge since you're about to modify the error message and the error message is key in the `FailureAnalyzer` it would be a good exercise to contribute an implementation. Thank you so much!

**Comment by brettwooldridge** [comment]
Leaving this one open.  Anyone interested in contributing a FailureAnalyzer for this issue to the Spring Boot project, a protypical implementation is available [here](https://github.com/brettwooldridge/spring-boot/commit/c40d1ca26bc0e5415d57ed2d66ac23297f391c44).  It still needs a unit test before submission to Spring Boot.

**Comment by snicoll** [comment]
I am actually going to take over Brett. Thank you.

**Comment by brettwooldridge** [comment]
@snicoll Thanks, Stephan.

Sorry about the CLA.  I am well versed in CLA's and their *raison d'être*, but even the often referenced ["In Defense of Contributor License Agreements"](https://julien.ponge.org/blog/in-defense-of-contributor-license-agreements/) acknowledges that the Apache License, version 2.0 (and only the Apache License v2.0) covers the legal aspects that make a CLA necessary when other licenses are employed.

I guess Pivotal's lawyers have to justify their billables.

**Comment by brettwooldridge** [comment]
@snicoll I noticed you guys are depending on HikariCP-java6-2.3.13.  That's fine, no problem.  But I wanted to point out that the message changed between [2.3.x](https://github.com/brettwooldridge/HikariCP/blob/2.3.x/hikaricp-common/src/main/java/com/zaxxer/hikari/AbstractHikariConfig.java#L772) and [2.4.x](https://github.com/brettwooldridge/HikariCP/blob/dev/src/main/java/com/zaxxer/hikari/HikariConfig.java#L770).  You might want to cover both in the analyzer in case the user independently upgrades their dependency.

**Comment by snicoll** [comment]
That's the reason why I wanted you to do the analyzer. Maybe you'd have changed your code to make that a tad easier 😃  - I'll manage I guess

**Comment by brettwooldridge** [comment]
@snicoll Absolutely willing to make accomodating changes on our side.  My first thought was throwing a HikariCP specific exception class, possibly containing the offending ``driverClassName`` and ``dataSourceClassName`` property values.

We haven't put out a release of the HikariCP-java6 artifact in 2+ years (I think), but no reason we couldn't.  In that case, we could normalize the message between 2.3.x and 2.4.x.

Does that help?

**Comment by snicoll** [comment]
I am working on the `FailureAnalyzer` and the version we use throws an `IllegalStateException` and your PR and your link refers to an `IllegalArgumentException`. Please don't change the exception type. I am ok to check for two error messages according to the version but changing the version is a major pain. 

Also, if you've changed the error message just to make us happy, please revert. The failure analyzer is taking care of that now. Thanks.

**Comment by snicoll** [comment]
I am confused. Can someone give me a legit use case of configuring `datasourceClassName` with Spring Boot? I am trying to remove the driver when that property is set and what I get in return is:

```
com.zaxxer.hikari.pool.PoolInitializationException: Exception during pool initialization

	at com.zaxxer.hikari.pool.BaseHikariPool.initializeConnections(BaseHikariPool.java:550)
	at com.zaxxer.hikari.pool.BaseHikariPool.<init>(BaseHikariPool.java:172)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:60)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:48)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:104)
	at org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfigurationTests.hikariCanConfigureDataSourceClassName(DataSourceAutoConfigurationTests.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.sql.SQLException: Invalid argument in JDBC call: url: null
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCUtil.nullArgument(Unknown Source)
	at org.hsqldb.jdbc.JDBCDataSource.getConnection(Unknown Source)
	at com.zaxxer.hikari.pool.BaseHikariPool.addConnection(BaseHikariPool.java:444)
	at com.zaxxer.hikari.pool.BaseHikariPool.initializeConnections(BaseHikariPool.java:548)
	... 34 more
Caused by: org.hsqldb.HsqlException: Invalid argument in JDBC call: url: null
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.error.Error.error(Unknown Source)
	... 39 more
```

@brettwooldridge can you show me a legit configuration for Hikari with `dataSourceClassName` and how we could integrate that with boot?

**Comment by brettwooldridge** [comment]
@snicoll Maybe you can extrapolate a correct Spring Boot configuration [from here](https://github.com/brettwooldridge/HikariCP/blob/dev/src/test/java/com/zaxxer/hikari/db/BasicPoolTest.java#L42)?

**Comment by snicoll** [comment]
Yeah ok, we're back at square one. If I support `data-source-class-name` now, the settings aren't applied anyway (for the reason you've already explained above). 

If boot is auto-configuring the `datasource` what is the use case to specify a dataSource since the settings should be specified in a different way?

**Comment by brettwooldridge** [comment]
@snicoll Maybe there is no use case in the case of auto-configuration?  I assume there is no issue of auto-configuration of the datasource is disabled, right?

Oracle [extolls the virtues](https://docs.oracle.com/javase/tutorial/jdbc/basics/sqldatasources.html) of DataSource based access vs. Driver based access.  For example, the variety of DataSources available (XADataSource, PooledDataSource, ConnectionPoolDataSource), the register-ability of DataSources in JNDI, etc. vs. a simple driver which must be wrapped by a faux DataSource but cannot truly provide things like XA semantics.

Whether Spring Boot users want/need these capabilities or care about the distinctions, and whether it is already possible in Spring Boot, just not with auto-configuration, I am not in a position to answer.

In my opinion, if using a DataSource is already possible by disabling auto-configuration, I don't feel like there is any issue to be resolved.  If the FailureAnalyzer covers the case when the user attempts to use a DataSource along with auto-configuration, it feels like boot has done enough.

Some "magic" is good if it removes a burden from the user, but maybe trying to cover the DataSource case for auto-configuration, across pool implementations, would simply require *too much* "magic", and explicit knowledge of pools, and could introduce corner cases and strange failure modes...?

**Comment by snicoll** [comment]
We're definitely not going to do that. I've added a `FailureAnalyzer` (see https://github.com/spring-projects/spring-boot/commit/86757efcdf9ef62a44f6f19991cfbac414dc6d7e). I'd appreciate if you could keep the same exception type in 2.4 (I think I've seen an `IllegalArgumentException` somewhere instead of the current `IllegalStateException`). Thanks.

**Comment by brettwooldridge** [comment]
I didn't think so.
