### ISSUE TITLE
maxLifetime = 0 and idleTimeout = 0

### ISSUE THREAD

**Issue by calippo** [brettwooldridge/HikariCP#709]
Running performance tests on a postgres instance, we (me and my team) noticed a spike in response time during the very first requests, after the boot of the app.

The resulting plot was something like this (this is just meant to give you an idea, don't take it too seriously :)):
<img width="1317" alt="screen shot 2016-08-30 at 18 39 33" src="https://cloud.githubusercontent.com/assets/2476080/18098152/3e7559ce-6ee1-11e6-8a35-bb2a153798b7.png">

It shows the response time of our app under a load of 5/6 requests per second.

Setting both `maxLifeTime` and `idleTimeout` to zero, we were able to get rid of the initial spike.
Our take on that, is that creating all the connections together when the application starts up (we are using `minConnection == maxConnection == 25`) causes the spike.

My questions are:
- Is it reasonable that creating 25 connections cause such a problem (first requests really took about 2 seconds to get back to us)? I would expect the creation of few connections to take a few milliseconds.
- Is it bad to have connections open forever? (consider that my application is the only process using that database)

Exploring the history of the source code of hikari, I found this condition (that is not there anymore):
```java
if (maxLifetime == 0 && idleTimeout == 0) {
  logger.warn("setting idleTimeout to {}ms.", IDLE_TIMEOUT);
  idleTimeout = IDLE_TIMEOUT;
}
```
I guess you went through this very problem :), and you decided that you didn't really like `maxLifetime == 0 && idleTimeout == 0`.

**Comment by brettwooldridge** [comment]
@calippo First question is, what version of HikariCP?

It is strange that either ``maxLifeTime`` or ``idleTimeout`` would eliminate the spike.  Neither should come into play during the first few minutes of startup.

``idleTimeout`` is [actually ignored](https://github.com/brettwooldridge/HikariCP/blob/dev/src/main/java/com/zaxxer/hikari/pool/HikariPool.java#L622) when ``minimumIdle == maxConnections``.

``maxLifeTime`` similarly [should not come into play](https://github.com/brettwooldridge/HikariCP/blob/dev/src/main/java/com/zaxxer/hikari/pool/HikariPool.java#L433) until 30 minutes after startup.

[``ThreadLocalRandom``](https://github.com/brettwooldridge/HikariCP/blob/dev/src/main/java/com/zaxxer/hikari/pool/HikariPool.java#L435) can block the acquisition thread if enough entroy is not available.  On Linux this can be mitigated with ``-Djava.security.egd=file:/dev/./urandom"`` (yes, the /./ is necessary).

Connection creation speed varies quite a lot by database.  MySQL can typically setup a new connection in single-digit milliseconds.  Oracle over SSL can sometimes take 20-30 seconds per-connection.

I am curious why and if the spike is truly mitigated by either of the two variables you mentioned.  Certainly, setting a low ``minimumIdle`` would increase startup time -- but not if load immediately ramps up.

What does the database CPU and disk I/O look like during the spike?

**Comment by calippo** [comment]
> Q1: First question is, what version of HikariCP?

A1: We are using slick 3.1.1, that uses hikari 2.3.7

> Q2: It is strange that either maxLifeTime or idleTimeout would eliminate the spike. Neither should come into play during the first few minutes of startup.

A2: The reason why they came into play (in our opinion) is because we didn't shutdown the test setup between consecutive tests. With `maxLifeTime == 0 && idleTimeout == 0`, we only had the spike in the first test run 'since the connection was already opened' (at least this was our guess). The JVM was appropriately warmed up by the testing framework.

> idleTimeout is actually ignored when minimumIdle == maxConnections.

:+1: I read about it but didn't manage to find it in the actual code

> Connection creation speed varies quite a lot by database. MySQL can typically setup a new connection in single-digit milliseconds. Oracle over SSL can sometimes take 20-30 seconds per-connection.

Woah, didn't know about this. You have a similar estimate for postgres?

> Lastly, it's not great to have connections "open forever" because something usually kills them eventually -- often databases have a maxLifeTime of their own. Better for the pool to retire and replace them in an orderly fashion rather than discovering a dead connection at the time that the application needs one.

Ok, I see your point is: "it's better to control connections rather then being controlled by connections" :)

Recap:
- `idleTimeout` is completely ignored in our configuration. What we're doing is completely configured by `maxLifeTime = 0`
- `maxLifeTime = 0` is not a great configuration
- beware connections create can take seconds
- a possible solution for the problem would be `-Djava.security.egd=file:/dev/./urandom"`

Fortunately it looks that the performances of our app are good enough for our use case. I'm not sure we're going to test performances again (I'm likely going to set `maxLifeTime` to a reasonable amount of time).

The configuration consequences are now clear to me, I think you can close this issue. In case we go back testing the connection pool I'll update this with details (i.e. disk I/O CPU etc).

**Comment by pkgonan** [comment]
@brettwooldridge 
hi, brettwooldridge.

I have a question about maxLifeTime and connection eviction.

My production database has 60s of wait_timeout.
HikariCP recommands maxLifeTime = wait_timeout - 30s.

so, I set up maxLifeTime 30s.
Every 30 seconds, i can get logs 'connection was evicted'.

2018-04-25 17:16:27.529 DEBUG 5501 --- [onnection adder] com.zaxxer.hikari.pool.HikariPool        : hikariPool - Added connection org.mariadb.jdbc.MariaDbConnection@4c17abf9
2018-04-25 17:16:27.938 DEBUG 5501 --- [nnection closer] com.zaxxer.hikari.pool.PoolBase          : hikariPool - Closing connection org.mariadb.jdbc.MariaDbConnection@316bf091: (connection was evicted)
2018-04-25 17:16:27.968 DEBUG 5501 --- [onnection adder] com.zaxxer.hikari.pool.HikariPool        : hikariPool - Added connection org.mariadb.jdbc.MariaDbConnection@517ba0b8
2018-04-25 17:16:27.970 DEBUG 5501 --- [onnection adder] com.zaxxer.hikari.pool.HikariPool        : hikariPool - After adding stats (total=10, active=10, idle=0, waiting=0)
2018-04-25 17:16:28.646 DEBUG 5501 --- [nnection closer] com.zaxxer.hikari.pool.PoolBase          : hikariPool - Closing connection org.mariadb.jdbc.MariaDbConnection@4a4f19a0: (connection was evicted)
2018-04-25 17:16:28.656 DEBUG 5501 --- [onnection adder] com.zaxxer.hikari.pool.HikariPool        : hikariPool - Added connection org.mariadb.jdbc.MariaDbConnection@3db7055e
2018-04-25 17:16:29.258 DEBUG 5501 --- [ool housekeeper] com.zaxxer.hikari.pool.HikariPool        : hikariPool - Pool stats (total=30, active=15, idle=15, waiting=0)


Every 30 seconds!

Would not the load on the database?

**Comment by pkgonan** [comment]
@brettwooldridge 
Thank you for your reply.!!

How much more efficient is it to create connections than the test-while-idle method?
Is there anything I can refer to?

if constantly making new connections is not expensive, there seems to be no reason to use DBCP...
Does HikariCP use a special way to create a connection?

😃
