### ISSUE TITLE
MBean in Jboss 4.3 EAP

### ISSUE THREAD

**Issue by ramchris** [brettwooldridge/HikariCP#710]
Brett,
    I couldn't find mbean in jboss jmx-console page for one of the mysql datasources I configured. One of them is below.

``
<bean id="auxDataSource" class="com.zaxxer.hikari.HikariDataSource" destroy-method="close" autowire="no">
    <property name="dataSourceClassName" value="com.mysql.jdbc.jdbc2.optional.MysqlDataSource"/>
    <property name="registerMbeans"      value="true"                                         />
    <property name="poolName"            value="auxDSHikariCP"                                />
    <property name="allowPoolSuspension" value="true"                                         />
    <property name="minimumIdle"         value="1"                                            />
    <property name="maximumPoolSize"     value="50"                                           />
    <property name="maxLifetime"         value="1800000"                                      />
    <property name="idleTimeout"         value="600000"                                       />
    <property name="leakDetectionThreshold"   value="2000"                                    />
    <property name="dataSourceProperties">
      <props>
        <prop key="url">jdbc:mysql://dbapp.dev.monstersecurities.com/dev_aux</prop>
        <prop key="user">ramkumar</prop>
        <prop key="password">Dream33On</prop>
        <prop key="prepStmtCacheSize">250</prop>
        <prop key="prepStmtCacheSqlLimit">2048</prop>
        <prop key="cachePrepStmts">true</prop>
        <prop key="useServerPrepStmts">true</prop>
      </props>
    </property>
  </bean>
``

It did show up in hawtio when I deployed the same war in tomcat 8.0.30. Do we need to do anything else apart from setting registerMbeans to true in spring xml context files?

**Comment by brettwooldridge** [comment]
This is probably a question for the Spring guys.  Maybe they create separate JMX contexts for web apps?  Or intercept registrations an prefix names with a unique identifier?  Anyway, the HikariCP code is very simple, so it seems likely that it is a configuration issue.
