### ISSUE TITLE
Reconnect on io exceptions

### ISSUE THREAD

**Issue by fedotxxl** [brettwooldridge/HikariCP#711]
Is it possible to configure HikariCP to reconnect to DB in case of IO exceptions (e.g. db server was not available for few seconds/minutes) (repeats count / timeout)?

**Comment by brettwooldridge** [comment]
@fedotxxl It should do so already.

If it did not close and re-open connections, can you enable debug logging for the ``com.zaxxer.hikari`` package and simulate the failure again?  We would like to know what the SQLState code was in the SQLException thrown by the driver.

**Comment by fedotxxl** [comment]
We got an exception
```
WARN  c.z.hikari.proxy.ConnectionProxy - Connection org.postgresql.jdbc4.Jdbc4Connection@778ded48 (HikariPool-0) marked as broken because of SQLSTATE(57P01), ErrorCode(
0).
org.postgresql.util.PSQLException: FATAL: terminating connection due to administrator command
```

Is it possible to configure how many times HikariCP will try to reconnect / delay between tries (in millis)?

**Comment by fedotxxl** [comment]
@brettwooldridge Can you comment it? Is it possible to configure repeats count / delays between tries?

**Comment by brettwooldridge** [comment]
@fedotxxl HikariCP is designed to retry forever (in an independent thread).  The delay between retries will slowly increase from 250ms up to ``connectionTimeout`` (30 seconds by default).
