### ISSUE TITLE
connection pool w/ jvm dns cache 

### ISSUE THREAD

**Issue by djerraballi** [brettwooldridge/HikariCP#715]
We use a proximity / round-robin dns for our database servers. 

If our application servers have a 10s DNS cache, and each server has a pool w/ a jdbc url to our dns. Is it possible that the pool could fill up w/ connections to a single DB server? I know that there is some delay between when the pool harvests and enters a new connection, but is it at a greater interval than the 10s dns cache? 

Just a question as i am wondering whether we should be dropping the dns cache ttl to avoid a homogenous pool.

**Comment by brettwooldridge** [comment]
Yes, entirely possible.  Retired connections are likely to be replaced almost immediately.  A round robin DNS is not going to do a very good job of spreading load.

**Comment by djerraballi** [comment]
good to know, would you ever recommend disabling dns caching at jvm layer entirely to get around this?

**Comment by brettwooldridge** [comment]
That would depend how frequently other components resolve hosts.  In HikariCP 's case, resolution is infrequent, but you would want to ensure that other libraries aren't affected.
