### ISSUE TITLE
retain NextException

### ISSUE THREAD

**Issue by nitincchauhan** [brettwooldridge/HikariCP#719]
two changes:
1. in getLastConnectionFailure() it should be just get() and not getAndSet(null)
2. nullify it after successful isValid()

see http://stackoverflow.com/questions/39479345/how-do-i-know-if-my-hikaricp-pool-is-really-exhausted-when-sqltransientconnectio

**Comment by brettwooldridge** [comment]
@nitincchauhan Agreed on ``getAndSet(null)``, but resetting in ``isValid()`` is not correct.  The current reset in [newConnection()](https://github.com/brettwooldridge/HikariCP/blob/dev/src/main/java/com/zaxxer/hikari/pool/PoolBase.java#L347) is sufficient.

**Comment by nitincchauhan** [comment]
please nullify after successful isConnectionAlive too,  just like newConnection(). otherwise getConnection() may report 'stale' exception and it can not be used to distinguish as pool exhausted or db problem

once set in isConnectionAlive() for one bad connection, even if pool is exhausted, it would carry same exception till pool adds new connection.

Also, probably setting nextException is redundant. it is polluting log as 'nextException is cause' and printing exception also prints cause, as ...caused by...
