### ISSUE TITLE
Lower-case the maven artifactId to "hikariCP"?

### ISSUE THREAD

**Issue by bphilipnyc** [brettwooldridge/HikariCP#720]
Super low priority, but can we change the maven artifactId to start with a lower-case H?  When I go to look for the jar, I expect to find it under h, not H (a capital H sorts it to the top in linux).

    <dependency>
        <groupId>com.zaxxer</groupId>
        <artifactId>HikariCP</artifactId>
        <version>2.5.0</version>
    </dependency>

![screen shot 2016-09-14 at 12 18 47 pm](https://cloud.githubusercontent.com/assets/5893811/18522395/821c3eaa-7a75-11e6-9645-47fab11fc6a3.png)

**Comment by johnou** [comment]
:-1: for changing artifactId case, not sure what distro you are running but that is not the behaviour of mine.

tmp]$ ls -l
total 0
-rw-r--r-- 1 johno johno 0 Sep 15 00:16 a
-rw-r--r-- 1 johno johno 0 Sep 15 00:16 b
-rw-r--r-- 1 johno johno 0 Sep 15 00:16 C
-rw-r--r-- 1 johno johno 0 Sep 15 00:16 d
-rw-r--r-- 1 johno johno 0 Sep 15 00:16 H

**Comment by bphilipnyc** [comment]
Sorry - shows up this way in MacOS, not Linux

**Comment by jnehlmeier** [comment]
@bphilipnyc Thats a Mac OS issue. You can use `ls -f` on Mac OS to get more natural sorted results (HFS sorts itself).

**Comment by brettwooldridge** [comment]
@bphilipnyc Changing the artifact name would cause havoc, as many projects (HikariCP included [use variables](https://github.com/brettwooldridge/HikariCP/blob/dev/pom.xml#L45) for versions but leave the dependency itself unchanged.

**Comment by bphilipnyc** [comment]
fair enough
