### ISSUE TITLE
PoolConfig MBean shows different value comparing to tomcat config 

### ISSUE THREAD

**Issue by ujohnny** [brettwooldridge/HikariCP#721]
I was playing today with HikariCP as a replacement for tomcat-jdbc and noticed that idle transactions are not being closed and kept for a about 2-3 minutes, when idleTimeout is set to 1000.

I connected with JMX to my tomcat instance and:

Found 9 pools instead of one pool

![image](https://cloud.githubusercontent.com/assets/759709/18562730/b2cfa8ac-7b8d-11e6-917a-1cc9f0aac184.png)

In server.xml config I specified idleTimeout to 1000

`<Resource name="jdbc/hidden"
    auth="Container"
    registerMbeans="true"
    minimumIdle="1"
    maximumPoolSize="32"
    idleTimeout="1000"
    factory="com.zaxxer.hikari.HikariJNDIFactory"
    type="javax.sql.DataSource"
    connectionTimeout="300000"
    jdbcUrl="jdbc:postgresql://localhost:5432/hidden"
    dataSourceClassName="org.postgresql.ds.PGSimpleDataSource"
    dataSource.serverName="localhost"
    dataSource.databaseName="uemcpdb"
    dataSource.portNumber="5432"
    dataSource.user="hidden"
    dataSource.password=""/>`

I checked all PoolConfig beans and idleTimeout everywhere is set to default 600000
![image](https://cloud.githubusercontent.com/assets/759709/18562958/6fea282c-7b8e-11e6-8f3b-b8bd1c870b7d.png)

I changed it there to 1000 and noticed that connection become freed quite faster neither without change. Could you please comment here, if there's an actual issue in 2.5.0 version, or my expectations from idleTimeout parameter are incorrect?

**Comment by ujohnny** [comment]
I guess I should look at code first where values less than 10 seconds are ignored. Would you mind if I add this info to wiki? 

https://github.com/brettwooldridge/HikariCP/blob/a8a926be0964ff0fd5cb072805c21e6800f8deba/src/main/java/com/zaxxer/hikari/HikariConfig.java#L809

**Comment by brettwooldridge** [comment]
@ujohnny I added the minimum value to the main documentation:

https://github.com/brettwooldridge/HikariCP/commit/166d791f628bfdc4110ff198d3d939d8eb809d1e
