### ISSUE TITLE
How do I initialize MBean in the spring container?

### ISSUE THREAD

**Issue by ramchris** [brettwooldridge/HikariCP#730]
Brett,
    Since turning on the registerMBeans flag is not getting MBean registered with the Jboss 4.2.3, I am thinking of creating MBean in the spring container using the injected HikariPool object. How do I get the handle to HikariPool object which is used in HikariDataSource class? This will resolve the issue I am facing and we can move it to PROD with monitoring.

**Comment by ramchris** [comment]
I couldn't even get the MBeans getting registered with the server!!!. So I don't think we can use HikariCP with Jboss 4.2.3. Looks like we may need to wait for a month or two and push Hikari along with Tomcat upgrade

**Comment by brettwooldridge** [comment]
Does the [last answer here](http://stackoverflow.com/questions/27440985/unable-to-register-mbean-hikaridatasource-hikaripool-0-with-key-datasource) help?  What kind of error are you getting when HikariCP tries to register?  Can you enable debug logging, maybe it would shed some light?

**Comment by brettwooldridge** [comment]
Wait, Jboss 4.2.3?  The one released in 2008?

**Comment by ramchris** [comment]
Yeah we are moving to tomcat where Mbean works but for now we want it in jboss 4.2.3 until we move to tomcat 8. 

Get Outlook for iOS




On Fri, Sep 23, 2016 at 10:23 PM -0500, "Brett Wooldridge" <notifications@github.com> wrote:












Wait, Jboss 4.2.3?  The one released in 2008?

**Comment by ramchris** [comment]
Brett,
  This is what I see when I enabled the debug log and I don't have any duplicate datasource pool names.

> Sep 09 10:42:11,288 INFO [main] [] [] hikari.HikariDataSource:281 - dwHikariCP - Started. Sep 09 10:42:11,289 WARN [main] [] [] pool.PoolBase:399 - dwHikariCP - Failed to register management beans. javax.management.NotCompliantMBeanException: Class does not expose a management interface: java.lang.Object at org.jboss.mx.metadata.MBeanCapability.of(MBeanCapability.java:102) at org.jboss.mx.metadata.MBeanCapability.of(MBeanCapability.java:100) at org.jboss.mx.metadata.MBeanCapability.of(MBeanCapability.java:100) at org.jboss.mx.server.registry.BasicMBeanRegistry.registerMBean(BasicMBeanRegistry.java:182) at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:606) at org.jboss.mx.interceptor.ReflectedDispatcher.invoke(ReflectedDispatcher.java:155) at org.jboss.mx.server.Invocation.dispatch(Invocation.java:94) at org.jboss.mx.interceptor.AbstractInterceptor.invoke(AbstractInterceptor.java:133) at org.jboss.mx.server.Invocation.invoke(Invocation.java:88) at org.jboss.mx.interceptor.ModelMBeanOperationInterceptor.invoke(ModelMBeanOperationInterceptor.java:142) at org.jboss.mx.server.Invocation.invoke(Invocation.java:88) at org.jboss.mx.server.AbstractMBeanInvoker.invoke(AbstractMBeanInvoker.java:264) at org.jboss.mx.server.MBeanServerImpl.invoke(MBeanServerImpl.java:659) at org.jboss.mx.server.MBeanServerImpl$3.run(MBeanServerImpl.java:1422) at java.security.AccessController.doPrivileged(Native Method) at org.jboss.mx.server.MBeanServerImpl.registerMBean(MBeanServerImpl.java:1417) at org.jboss.mx.server.MBeanServerImpl.registerMBean(MBeanServerImpl.java:376) at com.zaxxer.hikari.pool.PoolBase.registerMBeans(PoolBase.java:238) at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:116) at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:94) at org.springframework.orm.hibernate3.LocalDataSourceConnectionProvider.getConnection(LocalDataSourceConnectionProvider.java:82) at org.hibernate.cfg.SettingsFactory.buildSettings(SettingsFactory.java:111) at org.hibernate.cfg.Configuration.buildSettings(Configuration.java:2101) at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1325) at org.hibernate.cfg.AnnotationConfiguration.buildSessionFactory(AnnotationConfiguration.java:867) at org.springframework.orm.hibernate3.LocalSessionFactoryBean.newSessionFactory(LocalSessionFactoryBean.java:814) at org.springframework.orm.hibernate3.LocalSessionFactoryBean.buildSessionFactory(LocalSessionFactoryBean.java:732) at org.springframework.orm.hibernate3.AbstractSessionFactoryBean.afterPropertiesSet(AbstractSessionFactoryBean.java:211) at com.om.dh.util.EnhancedAnnotationSessionFactoryBean.afterPropertiesSet(EnhancedAnnotationSessionFactoryBean.java:185) at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1369) at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1335) at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:473) at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory$1.run(AbstractAutowireCapableBeanFactory.java:409) at java.security.AccessController.doPrivileged(Native Method) at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:380) at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:264) at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:261) at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:185) at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:164) at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:269) at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:104) at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1245) at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1010) at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:472) at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory$1.run(AbstractAutowireCapableBeanFactory.java:409) 

>

**Comment by johnou** [comment]
Jboss 4.2.3 has issues registering mbeans, see https://developer.jboss.org/message/536859#536859 .

**Comment by johnou** [comment]
@brettwooldridge something like this, wdyt? https://github.com/brettwooldridge/HikariCP/compare/dev...johnou:jboss_mbeans?expand=1

**Comment by brettwooldridge** [comment]
@johnou That cannot be done.

> The MXBean concept provides a simple way to code an MBean that only references a predefined set of types, the ones defined by javax.management.openmbean. In this way, you can be sure that your MBean will be usable by any client, including remote clients, without any requirement that the client have access to model-specific classes representing the types of your MBeans.

This quote refers to a specific example ([which you can read here](http://docs.oracle.com/javase/7/docs/api/javax/management/MXBean.html) but you get the idea:
> With Standard MBeans, a client of the MBean Server cannot access the Usage attribute if it does not know the class MemoryUsage. Suppose the client is a generic console based on JMX technology. Then the console would have to be configured with the model-specific classes of every application it might connect to. The problem is even worse for clients that are not written in the Java language.

> This is where MXBeans differ from Standard MBeans. Although we define the management interface in almost exactly the same way, the MXBean framework converts model-specific classes into standard classes from the Java platform.

**Comment by ramchris** [comment]
Brett, 
   I would like to try this approach locally on 2.4.9 tag. I just want this to work in production for 2 months and then we will upgrade to Java 8 and Tomcat 8. I checked out the code but not compiling in JDK 1.7. Which branch I should use locally to make this change and see if it works or not?

**Comment by brettwooldridge** [comment]
The code must be compiled with Java 8, even in the case of creating the Java 7 artifact.

**Comment by ramchris** [comment]
Brett, Workaround provided by @johnou above fixes the issue I see in Jboss 4.2.3 in the below link
https://github.com/brettwooldridge/HikariCP/compare/dev...johnou:jboss_mbeans?expand=1. Thanks @johnou and @brettwooldridge
