### ISSUE TITLE
Pool Sizing on OSIV

### ISSUE THREAD

**Issue by drabiter** [brettwooldridge/HikariCP#734]
I read wiki page about the [pool sizing](https://github.com/brettwooldridge/HikariCP/wiki/About-Pool-Sizing), and also on other place it suggested to use (proper) small number of connections. How about the usage in OSIV? as the number will be linear with number of the requests. Is there any tips to keep number of total hold connections low in this pattern?

**Comment by brettwooldridge** [comment]
@drabiter I am not familiar with OSIV.  Is that Open Session in View, related to Hibernate?  This is a question better asked on stackoverflow.

**Comment by drabiter** [comment]
Got it. Thanks for the response.
