### ISSUE TITLE
Override HikariJNDIFactory to use with decrypted password

### ISSUE THREAD

**Issue by ramizuddin-360Training** [brettwooldridge/HikariCP#736]
I have defined a resource with type **HikariJNDIFactory**, like this in `server.xml` -

 ```
<Resource name="jdbc/myapp"
      factory="com.tomcat.secured.EncryptedHikariJNDIFactory"
      auth="Container"
      type="javax.sql.DataSource"
      maxActive="100"
      maxIdle="30"
      maxWait="10000"
      maximumPoolSize="10"
      dataSourceClassName="com.microsoft.sqlserver.jdbc.SQLServerDriver"
      dataSource.implicitCachingEnabled="true" 
      dataSource.url=".."
      dataSource.username=".." 
      dataSource.password="{encryptedpassword}"
    />
```

I have written a class to encrypt and decrypt plain string based on AES algorithm. Now, I want to override the Hikari JNDI Factory and use this class to decrypt the password.

Please guide how can I do it?

**Comment by brettwooldridge** [comment]
@ramizuddin-360Training I would recommend just copying ``HikariJNDIFactory``, and [modifying the existing code](https://github.com/brettwooldridge/HikariCP/blob/dev/src/main/java/com/zaxxer/hikari/HikariJNDIFactory.java#L63) to recognize the ``password`` or ``dataSource.password`` properties, perform the decryption and setting that value as the property.

**Comment by ramizuddin-360Training** [comment]
Thanks :+1:

**Comment by ramizuddin-360Training** [comment]
BTW, I'd love to contribute to next roadmap/release. Please count me in if there is anyway I can be part of it. Love it!
