### ISSUE TITLE
How do I use the HikariCPConnectionProvider to set the metrics in Hibernate 5?

### ISSUE THREAD

**Issue by ReaperUnreal** [brettwooldridge/HikariCP#740]
I've searched through the internet but can't find my answer. The previous version of this question:
https://github.com/brettwooldridge/HikariCP/issues/511
only has answers that work with Hibernate 3.5. I'm not using spring and the HikariCPConnectionProvider doesn't seem to have a way for me to get the HikariDataSource out of it.

**Comment by brettwooldridge** [comment]
You need to work on your Google-fu.  The HikariCPConnectionProvider appears to have an unwrap() function:

https://github.com/hibernate/hibernate-orm/blob/master/hibernate-hikaricp/src/main/java/org/hibernate/hikaricp/internal/HikariCPConnectionProvider.java
