### ISSUE TITLE
Hikari for Oracle warning

### ISSUE THREAD

**Issue by dapengdevs** [brettwooldridge/HikariCP#743]
I am using spring boot 1.4.1 with managed Hikari version 2.4.7.

The Oracle JDBC driver version is 11.2.0.3.

During applicaiton startup, I get following warning:

com.zaxxer.hikari.pool.PoolBase          : HikariPool-1 - Driver does not support get/set network timeout for connections. (oracle.jdbc.driver.T4CConnection.getNetworkTimeout()I)

Is there anything I need to worry about?

**Comment by nitincchauhan** [comment]
Network time out helps in closing broken connections (within specified time) in case of network outage. If not supported, connection may not be notified and removed from pool for 'longer' time (typically os or db level socket time)

upgrade hikaricp to 2.4.9 and If you can not upgrade driver,
you may set following as datasource properties:
config.addDataSourceProperty("oracle.net.CONNECT_TIMEOUT",  N );
config.addDataSourceProperty("oracle.jdbc.ReadTimeout",  N );
specify N in millis and 10 seconds more than maxLifetime

HTH

**Comment by shakuzen** [comment]
@dapengdevs Just FYI, I am not seeing that log output when using the Oracle JDBC driver version 12.1.0.2, so it seems to be a limitation with the Oracle JDBC driver version 11.x. I would suggest upgrading the driver.

**Comment by aconte76** [comment]
I've done some perf test with different oracle jdbc clients thin mode on both tcp/sdp modes and...
11.2.0.3 is faster one
11.2.0.3 is -5%
12.1.2.0.1 is -10%
Please consider also that usually X.1 versions of oracle are something like beta... 
since my 7.0... was always same history :))
