### ISSUE TITLE
Find optimum pool size for Hikari

### ISSUE THREAD

**Issue by buremba** [brettwooldridge/HikariCP#744]
Is there any way for Hikari to adjust the pool size for efficiently using the connections? If we do not set the maximum pool size, Hikari eventually causes "Too many connections" on Mysql so we usually have to set a maximum pool size but we're not sure which value is best since out application doesn't know the hardware of the server that is running Mysql process.

It would be great if Hikari could understand "Too many connections" exceptions that are thrown from the databases and adjust the pool size accordingly.

**Comment by brettwooldridge** [comment]
Maybe look at flexy-pool.
