### ISSUE TITLE
No connections available when constantly resetting pool as a result of system clock changes

### ISSUE THREAD

**Issue by lrmills12** [brettwooldridge/HikariCP#745]
Using: HikariCP-java7-2.4.9

I've run into an interesting issue on a customer VM where the system time is continually reset back a few minutes and then begins to drift forward. This frequent time change seems to cause hikari to churn:
-- it appears as though hikari will detect the time change, close the connections and re-open
-- next time the house keeper runs, the system time change has jumped forward another minute and hikari resets the pool again
-- Eventually all connections time out

We have been able to reproduce this very reliably in the customer environment. The time jumps seem to be an issue with their hypervisor under load. We have no issues with hikari when running in other environments but I wanted to bring this to your attention as it seems to cause the entire pool to be blocked. 
We also observed a potential memory leak when hikari starts to churn. I will be making another post about that.

In the log file you can observe the time jumping from 13:23:51,265 to 13:15:54,180, at which point connections start timing out. 

[hikari-log-time-jump-1.txt](https://github.com/brettwooldridge/HikariCP/files/525798/hikari-log-time-jump-1.txt)

I have attached some graphs from JMX of the pool size as well: 
![jmx1](https://cloud.githubusercontent.com/assets/3262755/19330489/5504426a-90a4-11e6-8382-a34e486f7807.png)
![jmx2](https://cloud.githubusercontent.com/assets/3262755/19330493/573b335e-90a4-11e6-8a3f-a41ea6f2214d.png)

I realize that the screenshots show a pool size of 100 (huuuge)...that was from an early configuration which has since been changed to 24. We can reproduce this behavior reliably with a pool size of 24. 

Hikari config we are using:
idleTimeout=10000
maxLifetime=30000
maximumPoolSize=24
registerMbeans=true

Let me know if there's any additional information I can provide.

**Comment by brettwooldridge** [comment]
I'll take a look.  I will say that you absolutely cannot rely on the VM host (outside) to keep proper time inside the container.

It is strongly recommended on physical hardware and basically a requirement for virtual machines to sync with an NTP server.  I'll add something to the FAQ.

Basically the option to have the VM synced to the host clock should be disabled, and the VM itself should run either NTP or w32time.

**Comment by ninhnv-runsystem** [comment]
My project get happen too, No connection..... Everything is good in Window operating system to connect remote Oracle database. But when i change to Ubuntu is wrong, i can not connect.
`Please help me`

**Comment by brettwooldridge** [comment]
@ninhnv-runsystem How is this the same issue?  Changing from Windows to Ubuntu has nothing to do with the pool resetting due to clock changes.

**Comment by ninhnv-runsystem** [comment]
Sorry i post wrong location, my problem is lik this http://stackoverflow.com/questions/32968530/hikaricp-connection-is-not-available

**Comment by brettwooldridge** [comment]
@ninhnv-runsystem If you are having that issue, enable the ``leakDetectionThreshold`` then find an fix your leaks.
