### ISSUE TITLE
Memory leak when constantly resetting pool as a result of system time changes

### ISSUE THREAD

**Issue by lrmills12** [brettwooldridge/HikariCP#746]
Using: HikariCP-java7-2.4.9
Related to another issue: https://github.com/brettwooldridge/HikariCP/issues/745

As described in the related issue, we have a customer environment which seems to be suffering from frequent system clock changes which cause hikari to enter a state where it is constantly resetting the pool. We have observed what appears to be a memory leak when hikari gets stuck resetting the pool:

[hikari-log-time-jump-oom.txt](https://github.com/brettwooldridge/HikariCP/files/525809/hikari-log-time-jump-oom.txt)

These logs were captured right before the heap was blown ~ 2:11
At this point, all activity had been stopped in the system. The only thing going on was hikari detecting the time change.

I haven't analyzed the heap dump yet. I should have some further details available tomorrow when I'm able to dig through the heap dump.

**Comment by brettwooldridge** [comment]
@lrmills12 None of the clock motion in that log was backward, so [eviction would not occur](https://github.com/brettwooldridge/HikariCP/blob/dev/src/main/java/com/zaxxer/hikari/pool/HikariPool.java#L620).  Eviction only occurs for [retrograde (backwards) clock motion](https://github.com/brettwooldridge/HikariCP/blob/dev/src/main/java/com/zaxxer/hikari/pool/HikariPool.java#L611).

Of course, if you have a short ``idleTimeout`` then a clock leap could cause premature retirement.

Your other issue (#745) shows that you have extremely short timeouts... ``idleTimeout=10000`` (10 seconds) and ``maxLifetime=30000`` (30 seconds).  Those are *extremely* aggressive timeouts.  The default ``maxLifetime`` is 30 *minutes*.  If your clock leaps forward by even 1 minute then HikariCP will think that those timeouts are exceeded for all connections -- causing a mass closure and re-connection.

You can avoid this by setting longer timeouts.  What is the purpose for such short timeouts?

As stated in #745, it is *imperative* to enable timeserver synchronization *inside* the VM.  Not only HikariCP, but *anything* in Java (transaction managers, etc.) can suffer from premature lock timeout and timer expiration.
