### ISSUE TITLE
Tutorials on setting up HikariCP for beginner

### ISSUE THREAD

**Issue by AlfredChiew** [brettwooldridge/HikariCP#752]
Hi @brettwooldridge , I'm great to see the great performance of your HikariCP. I'm a beginner to JavaWeb and I wish to use HikariCP as the connection pool in my project. Is there any video about the step by step to setup the HikariCP on windows platform using eclipse, mysql and tomcat 7 ?

**Comment by brettwooldridge** [comment]
Sorry, there is no such tutorial.  But if you google "eclipse tomcat HikariCP" you might find something.  I seem to remember seeing a blog or stackoverflow post.

**Comment by AlfredChiew** [comment]
Thank u, @brettwooldridge. I would try it out.
