### ISSUE TITLE
Improper Exception Handling

### ISSUE THREAD

**Issue by Noks2808** [brettwooldridge/HikariCP#756]
When we are able to get a connection from the Connection Pool but it is actually dead, the exception that's thrown is similar to the one thrown on Connection Pool Exhaustion - "**Connection is not available, request timed out after 10029ms**" . This made us think we had a connection leak , but that was not the case. 

I think connectionBag.borrow()  - [here](https://github.com/brettwooldridge/HikariCP/blob/1bd23423b94e8b7ba49c363d10281f869197e52e/src/main/java/com/zaxxer/hikari/pool/HikariPool.java#L162) should check whether connection is alive and then return it?

We noticed this in our system with below HikariCP artifact 

`<dependency>
            <groupId>com.zaxxer</groupId>
            <artifactId>HikariCP</artifactId>
            <version>2.4.7</version>
        </dependency>`

**Comment by brettwooldridge** [comment]
@Noks2808 Are you still seeing this issue?  I do recommend upgrading to the latest version; 2.5.1 if you are on Java 8, or 2.4.9 if you are on Java 7 (artifact ``HikariCP-java7``).

**Comment by Noks2808** [comment]
Hi 

Did you get a chance to see the code link that i pointed out..It seems to be a code issue. So unless its fixed in these new versions, i am not sure how would it be fixed..

**Comment by Noks2808** [comment]
I took a closer look at the code, it does check if a connection is live before returning it. 
But the issue is  about what should be the error message when all connections are already being used vs when the connectivity to db is lost, i.e the existing ones are dead and you cannot make new ones.
They aren't the same situations, and can lead to think that there's a connection leak even uf its a connectivity issue.

So if in high load situations this happens intermittently, people might be mislead to think that its a leak rather than connectivity issue.

Perhaps, we could throw a different exception when we timeout waiting for borrowing from a pool(all connections being used)?

**Comment by Noks2808** [comment]
@brettwooldridge  : Tagging so that a conclusion can be reached on this one...

**Comment by brettwooldridge** [comment]
All calls to the pool that fail to obtain a connection within the connectionTimeout exception will receive a [SQLTransientConnectionException](https://github.com/brettwooldridge/HikariCP/blob/dev/src/main/java/com/zaxxer/hikari/pool/HikariPool.java#L578).  The exception will contain a *cause*.

In the case that you cite, if all connections are dead and creation of new ones is also failing, the exception returned by *getCause()* will be the exception thrown by the driver.
