### ISSUE TITLE
Prometheus fails to parse metrics if more then one connection pool is in use

### ISSUE THREAD

**Issue by anverus** [brettwooldridge/HikariCP#757]
Metrics are exposed OK(ish)

> \# HELP hikaricp_connection_acquired_nanos Connection acquired time
> \# TYPE hikaricp_connection_acquired_nanos summary
> hikaricp_connection_acquired_nanos_count{pool="MAIN",} 28.0
> hikaricp_connection_acquired_nanos_sum{pool="MAIN",} 4251108.0
> \# HELP hikaricp_connection_acquired_nanos Connection acquired time
> \# TYPE hikaricp_connection_acquired_nanos summary
> hikaricp_connection_acquired_nanos_count{pool="PERSONAL",} 0.0
> hikaricp_connection_acquired_nanos_sum{pool="PERSONAL",} 0.0

but prometheus does not expect multiple type / help lines for same metric name
<prometheus>:9090/status reports 

> text format parsing error in line 5: second HELP line for metric name "hikaricp_connection_acquired_nanos"

For reference using prometheus 1.2.1 and hikariCP 2.4.7

**Comment by brettwooldridge** [comment]
@anverus We would consider this a bug in Prometheus, please open an issue on that project.
