### ISSUE TITLE
Define Unwrap in an interface, 

### ISSUE THREAD

**Issue by devzer01** [brettwooldridge/HikariCP#762]
so that when writing mock tests the proxy statement can be mocked for improved functionality

given the nature of `unWrap` function being final, its impossible to mock the behaviour for unit-testing. 

I am willing to submit a PR if this is a reasonable request.

**Comment by brettwooldridge** [comment]
It's not so simple.  HikariCP generates classes that extend the proxy classes at build time.  The generation uses the finality of methods to skip generation of delegating call for those methods.

**Comment by devzer01** [comment]
sorry i didn't realise unwrap was defined java.sql.Wrapper consider this is non-issue
