### ISSUE TITLE
Support multiple connections at startup

### ISSUE THREAD

**Issue by polpot78** [brettwooldridge/HikariCP#770]
USE CASE
When we start our environment, we often start the database server on a different machine, than the application server. And then it is practically impossible to ensure that the application starts after the database.

The property initializationFailFast  will not help us, as it will return with a connection-pool that does not work. If for example Ebean og Hibernate starts afterwards, they will fail as they can not fetch a Connection. 

PROPOSED SOLUTION
We set a parameter:
   initializationMaxAttempts

Which should default to 1 (todays functionality). 
This should say how many attempts HikariCP should perform to get the initial connections.
If connection is not retrieved, then it should log clearly that connection is not coming up. (ERROR?)

**Comment by billoneil** [comment]
I feel like this can be easily handled in application logic and should not be introduced into HikariCP itself. Can't you just wrap your initialization logic with the retries?

**Comment by polpot78** [comment]
It would be easy to add it to one application, but we have approx 100 applications, and we really would like to control this in the connection pool, where this logic should be.

I will create a pull request, and you can consider if it is right for HikariCP, and if the code is ok.
