### ISSUE TITLE
Number of Connections vs Thread Count

### ISSUE THREAD

**Issue by samhendley** [brettwooldridge/HikariCP#774]
I have been really impressed with Hikari in general, much better than the other pools we have tried. 

We have been trying to characterize the behavior of the pool in regards to how many connections it makes to the database. In our case we notice that the pool hits our maxPoolSize limit of 100 connections when the processing is very fast. I did an experiment where I tried different thread counts vs. simulated operation time vs. idle time between operations to try to understand how many connections are made to the database. Full Test code is here https://gist.github.com/samhendley/d51b8ebba59e348ee10d13e6c16d2820 but core of the test is this loop run by many threads.

```java
while (running.get()) {
    final Connection connection = hikariDataSource.getConnection();
    if (operationTime > 0) {
        Thread.sleep(operationTime);
    }
    connection.close();
    if (idleTime > 0) {
        Thread.sleep(idleTime);
    }
}
```

What we find is that if the operationTime is short and the idle time is short (simulating a busy and fast process) we will quickly spawn our max of 100 connections even with only 8 threads. 

![image](https://cloud.githubusercontent.com/assets/36385/20720634/f05782a0-b62d-11e6-8899-87061d7e059b.png)

This was a bit of a surprise to me. I was expecting the pool to be end up maxing out at around the same number of threads we have but it looks like there must be some "housekeeping" I wasn't aware of that lets the pool grow too large. I know I could change the maxPoolSize to match the thread count but that can be tricky to "plumb" and if we try to be too exact we can create deadlock type failures. Notice that when the either the operations or idleTime are "slow" the pool stays at about the expected size. We only noticed this when we had optimized the performance of our process so all of it's calls fell into the <10ms range.

So two questions: 

* Can you explain what is happening after the connection.close() so that it isn't immediately ready for reuse. (is the housekeeping thread running the connectionQuery?)

* Any settings other than maxPoolSize I can change to keep this growth in check?

**Comment by brettwooldridge** [comment]
@samhendley Your issue was an inspiration for a [new write-up](https://github.com/brettwooldridge/HikariCP/blob/dev/documents/Welcome-To-The-Jungle.md) to be published when v2.6.0 is released.

**Comment by samhendley** [comment]
Awesome write up and thank you for the help. If you can, you might want to change the color of "waiting threads" or "total connections". They were really difficult to tell apart on my monitor and phone so it took a while to understand what they are showing me.

In my similar tests I would expect hikari to end that test with **6** connections (at the 150ms mark). Since the connection adder thread starts making the 6th connection at the beginning of the spike it should end up adding that one extra entry to the pool (well after we needed it in this case). I had been thinking of how to avoid this issue but can't come up with anything that doesn't introduce a delay in the normal rampup scenario.

**Comment by brettwooldridge** [comment]
Thanks for the feedback on the graph color, I'll see what I can come up with.  Because I want to use translucency it is surprisingly hard to find readable combinations.

Regarding the 6th connection (mentioned at the end of the write up), I'm thinking about an additional call to *shouldCreateAnotherConnection()* **after** actual acquisition and immediate closing if no longer needed ...

**Comment by brettwooldridge** [comment]
Better?

![](https://raw.githubusercontent.com/wiki/brettwooldridge/HikariCP/Spike-Hikari.png)

**Comment by samhendley** [comment]
Much better. 

I think immediately dropping the connection is a bit aggressive, we've already paid the cost of creating the connection seems wasteful to toss it. It will get dropped on the idle timeout anyways, and if there is another spike we'll have 6 connections instead of 5 and handle it a bit better. But this does mean every spike will cause another connection to be created but if there are enough spikes to keep building connections then that is approximating a steady state workload anyways.
