### ISSUE TITLE
Connection not closing

### ISSUE THREAD

**Issue by udownuser** [brettwooldridge/HikariCP#775]
Hi,

I'm using Hikari with spring batch process. My job runs every 30 minutes and complete in 5 mins. After the job is completed I would expect the connection to be closed and returned to the pool for the next job. When I tried to do that, the 3rd or the 4th job usually throws out an error saying could not get connection. So I tried to create a new pool for every job and reduced the number of connections. But now, the connections just keeps growing and never gets killed. I can see there are many inactive connections but are not getting killed.

Here is the config:
```
<bean id="dataSource" class="com.zaxxer.hikari.HikariDataSource"
		destroy-method="close" abstract="true" scope="prototype">
		<property name="maximumPoolSize" value="5" />
		<property name="idleTimeout" value="150000" />
		<property name="connectionTimeout" value="150000" />
		<property name="maxLifetime" value="300000"></property>
		<property name="driverClassName" value="oracle.jdbc.driver.OracleDriver" />
		<property name="validationTimeout" value="10000"></property>
		<property name="username" value="user" />
		<property name="password" value="password" />
                <property name="jdbcUrl" value="url" />
	</bean>
```
Am I missing something here? Any help is greatly appreciated.

**Comment by samhendley** [comment]
It is most likely that the processing isn't closing the database connection when it is done with it. Try enabling JMX and then look at the number of "ActiveConnections" when the batch is complete. I would guess that it will go up by 1 and stay there for each batch run.

**Comment by brettwooldridge** [comment]
Enable *leakDetectionThreshold*, it sounds like a connection leak.
