### ISSUE TITLE
Hikari Logging Ignores Root Logger in Defined in JSON Configration File

### ISSUE THREAD

**Issue by eric-aldinger** [brettwooldridge/HikariCP#777]
Thank you for your work on HikariCP. I have a logging request. I would expect HikariCP to log connection information with the root appender defined in my Log4J2 configuration, given the following conditions are met.
* The project is using Log4j2 or SLF4J as a dependency
* The logging level is defined as either DEBUG or INFO
* Logging is in a Log4J2 supported JSON format
* The file name is one of the following expected names: log4j.json, log4j2.json, log4j2-test.json, log4j2-test.jsn

I am getting appender not found warnings, and no logging
```
log4j:WARN No appenders could be found for logger (com.zaxxer.hikari.HikariConfig).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
```
With the following log4j2-test.json file
```
{
  "configuration": {
    "name": "Default",
    "properties": {
      "property": [
        {
          "name": "log-pattern",
          "value": "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
        }
      ]
    },
    "appenders": {
      "Console": {
        "name": "Console-Appender",
        "target": "SYSTEM_OUT",
        "PatternLayout": {
          "pattern": "${log-pattern}"
        }
      }
    },
    "loggers": {
      "root": {
        "level": "INFO",
        "appender-ref": { "ref": "Console-Appender" }
      }
    }
  }
```
My logging is working fine for Akka and Scala classes with this format. I can enable HikariCP logging if I add a duplicate root appender using a log4j.properties file
```
log4j.rootLogger=INFO, stdout
log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.Target=System.out
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n
```

I would prefer not to have two configuration files nor do I want my logging configuration file format dictated by my connection pool manager.

**Comment by brettwooldridge** [comment]
@eric-aldinger This sounds like you are [missing the log4j2 binding for slf4j](http://stackoverflow.com/questions/25386651/slf4j-log4j2-maven-setup-query):
```xml
<dependency>
    <groupId>org.apache.logging.log4j</groupId>
    <artifactId>log4j-slf4j-impl</artifactId>
    <version>2.0.1</version>
</dependency>
```
