### ISSUE TITLE
[help][2.3.8] - JMX MBean expose HikariCP Poll without values(Zero)

### ISSUE THREAD

**Issue by rgarbin** [brettwooldridge/HikariCP#780]
I am trying expose HikariCP Poll but my jmx response always return zero values for Mbean. Are there some special hikari config property to enable?

URL: 

```json
http://host:port/jmx/read/com.zaxxer.hikari:type=Pool%20(hirakiConnectionPool)
```
JMX Response: 

```json
{
  "value": {
    "IdleConnections": 0,
    "ActiveConnections": 0,
    "ThreadsAwaitingConnection": 0,
    "TotalConnections": 0
  },
  "request": {
    "type": "read",
    "mbean": "com.zaxxer.hikari:type=Pool (hirakiConnectionPool)"
  },
  "status": 200,
  "timestamp": 1480954660
}
```

Using:
```java
<dependency>
	<groupId>com.zaxxer</groupId>
	<artifactId>HikariCP-java6</artifactId>
	<version>2.3.8</version>
</dependency>
```

Wiki reference:
https://github.com/brettwooldridge/HikariCP/wiki/MBean-(JMX)-Monitoring-and-Management

**Comment by brettwooldridge** [comment]
@rgarbin That is very strange.  The MBean methods are [here](https://github.com/brettwooldridge/HikariCP/blob/dev/src/main/java/com/zaxxer/hikari/pool/HikariPool.java#L310), and they are used by the debug level [pool state log](https://github.com/brettwooldridge/HikariCP/blob/dev/src/main/java/com/zaxxer/hikari/pool/HikariPool.java#L386).  If you enable debug logging, do you see messages like this periodically?
```
Pool stats (total=7, active=7, idle=0, waiting=0)
```

If you connect with a JMX console (like the built-in java ``jconsole``), do you see statistics?

Also, that is a pretty old version of HikariCP.  Are you on Java 6?

**Comment by rgarbin** [comment]
Sorry, I found the problem. 

I have a generic bean with default hikari config and every datasources extends this base beans, but I didn't overide the pool name property for each datasource =/

Now, working as expected:

http://host:port/jmx/read/com.zaxxer.hikari:type=Pool%20(**hirakiConnectionPoolA**)
http://host:port/jmx/read/com.zaxxer.hikari:type=Pool%20(**hirakiConnectionPoolB**)
http://host:port/jmx/read/com.zaxxer.hikari:type=Pool%20(**hirakiConnectionPoolC**)

Thks for help @brettwooldridge and sorry again!
