### ISSUE TITLE
The ludicrous page layout is broken

### ISSUE THREAD

**Issue by DidierLoiseau** [brettwooldridge/HikariCP#783]
The [Ludicrous Speed, GO!](http://brettwooldridge.github.io/HikariCP/ludicrous.html) page seems to intend to use some `fixed-font` for rendering technical names, however those are rendered as code in tables with line numbers. This completely breaks the layout of the page and makes it unreadable.

This is a bit unfortunate since it has a highly visible link on the repository home page.

**Comment by brettwooldridge** [comment]
WTF?!  This is the page from May 2016:

https://web.archive.org/web/20160502154826/http://brettwooldridge.github.io/HikariCP/ludicrous.html

And there have been no commits since June 2015.  Github or one of their dependencies must have broken the rendering.  I'll look into it.

**Comment by brettwooldridge** [comment]
Fixed.
