### ISSUE TITLE
Feature request: Metrics for failed number of getConnection calls

### ISSUE THREAD

**Issue by SuperPat45** [brettwooldridge/HikariCP#784]
Hi,

Please, add metrics for failed number of getConnection calls
 (and eventually the connection successful and failed number for the last second).

My old connection pool (proxool) had this features built-in.

**Comment by brettwooldridge** [comment]
@SuperPat45 While we likely will not offer an exact match to proxool, there is a [Dropwizard Meter](http://metrics.dropwizard.io/3.1.0/getting-started/#meters) registered as ``MetricRegistry.name(poolName, "pool", "ConnectionTimeoutRate")``, if you configure HikariCP with a ``metricRegistry``.  The Dropwizard ``Meter`` provides a total count, as well as [1-, 5-, and 15-minute exponentially-weighted moving averages](http://metrics.dropwizard.io/3.1.0/apidocs/com/codahale/metrics/Meter.html)

**Comment by SuperPat45** [comment]
OK
