### ISSUE TITLE
Design of the HikariCP

### ISSUE THREAD

**Issue by sandeep27st** [brettwooldridge/HikariCP#785]
Hello, 
I am new in Hikari and currently I am understanding the basic library working. I am bit confused how hikari manage the thread to achieve the pooling. It would be beneficial if you provide design diagram or state diagrams of Thread management.

**Comment by brettwooldridge** [comment]
@sandeep27st HikariCP does not manage threads per-se.

You can visualize HikariCP as a simple [``BlockingQueue``](https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/BlockingQueue.html).  It actually does not use a ``BlockingQueue`` it uses a specialized collection called a [``ConcurrentBag``](https://github.com/brettwooldridge/HikariCP/blob/dev/src/main/java/com/zaxxer/hikari/util/ConcurrentBag.java), but the behavior is conceptually the same.

In the ``BlockingQueue`` model, you can imagine that a client (your code) that invokes ``HikariDataSource.getConnection()`` is doing the following:
```java
public Connection getConnection() throws SQLException {
   return connectionQueue.poll(timeout);
}
```
There is obviously a little more going on, throwing timeout exceptions etc. but that is the basic idea.  Calling ``Connection.close()`` essentially returns the connection to the pool.  Conceptually:
```java
public void close() throws SQLException {
   connectionQueue.put(this);
}
```
Again, there is more going on implementation-wise, but the concept is the same.

HikariCP *does* have several threads of its own.  There is a "housekeeping" thread that runs periodically to retire idle connections.  There is a scheduler thread that retires connections that reach ``maxLifetime``.   There is a thread for adding connections, and a thread for closing them.
