### ISSUE TITLE
[question] - timeout error trying get connection but poll has a lot free connections to open(maximumPoolSize)

### ISSUE THREAD

**Issue by rgarbin** [brettwooldridge/HikariCP#787]
I verified on my application some Timeout Exception waiting for pool connection but checking my metrics(iddle, max, active), the pool has a lot free connections that pool could open, but fail throwing this exception.

maximumPoolSize value: 400

![image](https://cloud.githubusercontent.com/assets/1133657/21059828/7a5b9f86-be2b-11e6-86d8-dc33c49a03a9.png)

I didn't understand this behavior and I would like some protip / help =)

HikariCP-java6: 2.3.13

**Comment by brettwooldridge** [comment]
@rgarbin Are you stuck on Java 6?  The Java 7 and Java 8 distributions are significantly ahead of Java 6, with many (many) issues addressed.

**Comment by rgarbin** [comment]
I adjusted some configs and timeout exception stop.

- connectionTimeout: from 10s to 30s
- maxLifetime:  from 15m to 30m

I just read docs and all resolved \o/
https://github.com/brettwooldridge/HikariCP/wiki/Configuration

We are working to upgrade all applications to Java 8
