### ISSUE TITLE
java.lang.IllegalArgumentException: one of either dataSource or dataSourceClassName must be specified

### ISSUE THREAD

**Issue by alias1** [brettwooldridge/HikariCP#788]
```
java.lang.IllegalArgumentException: one of either dataSource or dataSourceClassName must be specified
	at com.zaxxer.hikari.AbstractHikariConfig.validate(AbstractHikariConfig.java:779)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:75)
```

So was getting this recently, and took me a while to figure out. I had `dataSourceClassName` set correctly in my config file. But what it was actually expecting to be there was `dataSourceClass`. 

Updating the error message to match expected behaviour would be useful.

**Comment by brettwooldridge** [comment]
@alias1 This must be on a very old version of HikariCP.  The messages and validation [have changed significantly](https://github.com/brettwooldridge/HikariCP/blob/dev/src/main/java/com/zaxxer/hikari/HikariConfig.java#L809).

**Comment by alias1** [comment]
This was using the latest version of slick-hikaricp (3.1.1), which seems to be pulling in 2.3.7.

For reference, the relevant bits of the dependency tree:

```
[info]   +-com.typesafe.slick:slick-hikaricp_2.11:3.1.1 [S]
[info]   | +-com.typesafe.slick:slick_2.11:3.1.1 [S]
..snip..
[info]   | +-com.zaxxer:HikariCP-java6:2.3.7
```

So yeah, definitely linked to an old version.

**Comment by alias1** [comment]
For future reference, solved (updated) by https://github.com/slick/slick/pull/1677

**Comment by zmsoft** [comment]
Hi @0xdevalias ,

I had the same problem as you when configuring multiple data sources.
Could you please tell me how to solve this issue?

Thank you
