### ISSUE TITLE
I can't for the life of me get this to work

### ISSUE THREAD

**Issue by Incrementing** [brettwooldridge/HikariCP#789]
Version: 2.5.1

When using this code:
`
hikari = new HikariDataSource();
hikari.setMaximumPoolSize(10);
hikari.setDriverClassName("com.mysql.jdbc.Driver");
hikari.setJdbcUrl("jdbc:mysql://localhost:3306/db_name");
hikari.setUsername("root");
hikari.setPassword("password");`

I get this error:
INFO com.zaxxer.hikari.HikariDataSource - HikariPool-6 - Started.
INFO com.zaxxer.hikari.pool.PoolBase - HikariPool-6 - Driver does not support get/set 
network timeout for connections. (com.mysql.jdbc.JDBC4Connection.getNetworkTimeout()I)>

So I then used this code:
`
hikari = new HikariDataSource();
hikari.setMaximumPoolSize(10);
hikari.setDataSourceClassName("com.mysql.jdbc.jdbc2.optional.MysqlDataSource");
hikari.addDataSourceProperty("serverName", "localhost");
hikari.addDataSourceProperty("port", "3306");
hikari.addDataSourceProperty("databaseName", "db_name");
hikari.addDataSourceProperty("user", "root");
hikari.addDataSourceProperty("password", "password");`

Which throws the same error.

This code used to work for me but for some reason I can't get it to work anymroe. I'm probably being an idiot but any help would be appreciated.

**Comment by shakuzen** [comment]
As the log message indicates, the MySQL driver you are using does not support setting the network timeout. Perhaps a newer version of the driver does.

**Comment by Incrementing** [comment]
Don't suppose you know any supported MySQL drivers?

**Comment by brettwooldridge** [comment]
@Incrementing The ``Driver does not support get/set
network timeout`` message is informational, it does not affect basic pool functionality (but does affect recovery from network outages).

**Comment by Incrementing** [comment]
@brettwooldridge Thanks for the info... I'll have to update the driver at some point.
