### ISSUE TITLE
Interrupts Not Propagated in getConnection

### ISSUE THREAD

**Issue by kevinconaway** [brettwooldridge/HikariCP#791]
@brettwooldridge 

If the thread is interrupted while in [`HikariPool#getConnection()`](https://github.com/brettwooldridge/HikariCP/blob/fbe1006486dc096f327d11fb02775768cc666e90/src/main/java/com/zaxxer/hikari/pool/HikariPool.java#L180), the interrupted exception is rethrown as a `SQLException` but the interrupt status on the thread is not reset.

I believe the pool should be calling `Thread.currentThread().interrupt()` before rethrowing the exception.

I'm happy to submit a PR for this if you wish.

**Comment by brettwooldridge** [comment]
@kevinconaway Interesting catch.  Not only that, but an ``InterruptedConnection`` could cause a connection to leak from the pool.  That is fixed as well.
