### ISSUE TITLE
Initial connection in the connection pool

### ISSUE THREAD

**Issue by XABCY** [brettwooldridge/HikariCP#797]
Thank you for the wonderful library. I am planning to switch from DBCP to HikariCP. I hope this would be the very good decision to switch. HikariCP comes up with very cool features, which I really like. It will improve the huge performance. 
In our application, we use to integrate the large amount of data from source system. To integrating we connect with application(source system) where connection creation time is very huge. 
Our requirement is, we need to integrate the data only at the first time(means huge spike demand occurs first time only), after that our application needs connection around 20% of the first spike demands. This kind of systems needs the initial connections to be created in the pool upfront. 
I had option of initial connection in DBCP. But in HikariCP there is not an initial connection option.  I know HikariCP contains minimum idle connection which is better than the initial connection. But minimum idle connection some time wast our memory usage. 
Lets take example.
Consider, 
Maximum connection= 100, 
Minimum Idle connection  = 45,
Initially, pool contains 45 connection as per my initial demand. after allocating 45 connection pool will create the another 45 connection, but after first batch I need only 5-10 connection. So remaining 30 connection memory will get wasted.
To keeping minimum idle low will increase the connection creation time, as I mention connection creation time is very huge for the application where we are connect.

Can you please suggest the best option. I wanted to go with the initial connection and minimum idle(very cool feature of HikariCP) both option. How can I configure the pool so that my requirement gets fulfill.

**Comment by billoneil** [comment]
First read https://github.com/brettwooldridge/HikariCP/wiki/About-Pool-Sizing 100 or even 45 connections seems like a lot.

Either way you have to open the connections whether or not they are opened initially or ondemand. You might save a tiny amount of time but I would think of it being negligible. I would just let the pool do its job.

If you really need this type of feature what about using two different pools or shutting down and restarting the pool with a different config after the initial load is done?

**Comment by brettwooldridge** [comment]
@XABCY Yours is a fairly unusual use-case, and HikariCP is not able to support what you need out-of-the-box with standard system properties.

However, much of HikariCP's configuration can be altered after the pool is started and running.  I would suggest using the [``HikariConfigMXBean``](https://github.com/brettwooldridge/HikariCP/blob/dev/src/main/java/com/zaxxer/hikari/HikariConfigMXBean.java) via the [programmatic interface](https://github.com/brettwooldridge/HikariCP/wiki/MBean-(JMX)-Monitoring-and-Management) to alter the ``minimumIdle`` after your spike load is complete.

**Comment by XABCY** [comment]
So has there any performance imact or reason behind, not to maintaining such parameter, rather all other connection pool has this kind of sizing  parameter just like in dbcp has initialconnnection, in viburCP has poolInitSize and in bonecp has minimumConnection.

**Comment by brettwooldridge** [comment]
@XABCY HikariCP has ``minimumIdle``, roughly equivalent to BoneCP's ``minConnectionsPerPartition`` parameter.  We strongly resist adding additional configuration parameters to the pool.  It complicates the code and complicates the configuration decisions that users must consider to properly "tune" their pool.

Apache DBCP has more than 40 pool properties, and I would estimate that 90% of DBCP deployments are not correctly tuned for performance, and worse, are definitely not corrected tuned for reliability.
