### ISSUE TITLE
release 2.4.8 and 2.4.9 not available on maven

### ISSUE THREAD

**Issue by rusher** [brettwooldridge/HikariCP#798]
Hi, 
The title say all, maven central doesn't have 2.4.8 and 2.4.9 version :
http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.zaxxer%22%20AND%20a%3A%22HikariCP%22

**Comment by brettwooldridge** [comment]
@rusher You're looking in the wrong place:

http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.zaxxer%22%20AND%20a%3A%22HikariCP-java7%22

HikariCP 2.4.8 started a Java 7 only release train, with a new artifact ``HikariCP-java7``.
