### ISSUE TITLE
Current pool size

### ISSUE THREAD

**Issue by Syed-SnapLogic** [brettwooldridge/HikariCP#799]
Hi friends,
  I have created a connection pool with min size 1 and max size 20.  How can I know at a given time, how many connections are present in the pool?  I couldn't find any method to fetch the current pool size.  Would be a great help.  Thanks.

**Comment by brettwooldridge** [comment]
@Syed-SnapLogic Use the JMX programmatic interface.

https://github.com/brettwooldridge/HikariCP/wiki/MBean-(JMX)-Monitoring-and-Management

**Comment by Syed-SnapLogic** [comment]
I used the code snippet available on the link you gave.  I am getting this error with that code: 

Failed: com/zaxxer/hikari/pool/HikariPoolMXBean
Resolution: Driver loading possibly failed, please ensure the driver is correctly configured
Reason: com/zaxxer/hikari/pool/HikariPoolMXBean

What can I do next?

**Comment by brettwooldridge** [comment]
@Syed-SnapLogic Is the ``registerMbeans`` pool property set to ``true``?  Is the ObjectName correct, including whitespace, case, and pool name?  If so, I don't know what else to say.  At that point it is a JMX issue and you will need to ask on stackoverflow.com.

**Comment by Syed-SnapLogic** [comment]
@brettwooldridge: I have my database running on Machine A.  My Java application (that uses HikariCP for connection pooling) is running on Machine B.  The code snippet you gave in https://github.com/brettwooldridge/HikariCP/wiki/MBean-(JMX)-Monitoring-and-Management should be run on which machine?  I am running it on Machine B.  Can you advise?

**Comment by Syed-SnapLogic** [comment]
Ok, that was class not found error.  I fixed that and now I am getting this error:
java.lang.reflect.UndeclaredThrowableException
	at com.sun.proxy.$Proxy170.getIdleConnections(Unknown Source)

caused by javax.management.InstanceNotFoundException: com.zaxxer.hikari:type=Pool (SyedsPool0)

I am sure I gave the correct pool name.  case, whitespace, etc.  Any help?

**Comment by Syed-SnapLogic** [comment]
Sorry, my bad.  The pool name was not set correctly.  I am able to fetch the data source properties now.  Thanks so much.
