### ISSUE TITLE
Hikari changes query timeout to validation timeout

### ISSUE THREAD

**Issue by mi-st** [brettwooldridge/HikariCP#800]
I'm using H2 DB with default query timeout (0 means no timeout), but I still got timeouts from JDBC connection.   I noticed that query timeout was altered by Hikari   in metohd  PoolBase#isConnectionAlive .  It looks like Hikari uses query timeout if isNetworkTimeoutSupported  = false, but it doesn't  set it back to the original one. As result clients gets connection with query timeout set to validation timeout instead of default one.

**Comment by brettwooldridge** [comment]
@mi-st That would be a bug in the H2 driver, I recommend reporting it to them, they are fairly responsive.  The JDBC specification is fairly clear that the timeout specified to the ``Statement.setQueryTimeout()`` method should only be applied to the ``Statement`` instance on which it was called.  HikariCP closes the Statement.  If H2 is applying that to all ``Statements`` on the ``Connection`` that is a bug.  There is no such thing as ``Connection.setQueryTimeout()``.

**Comment by mi-st** [comment]
You're right - H2 JDBC driver applies this timeout to the whole  session (org.h2.jdbc.JdbcConnection).  Call Statement,setQueryTimeout delegates to JdbcConnection#setQueryTimeout 
Thanks!

**Comment by brettwooldridge** [comment]
@mi-st Looks like you are not the first one to encounter this.  Unfortunately, from the sound of their response, it does not sound like they intend to fix it.

https://groups.google.com/forum/#!topic/h2-database/gXF73w00Hx4

Funnily enough, you are apparently not the first HikariCP user to encounter this, I just have a bad memory:

https://github.com/brettwooldridge/HikariCP/issues/170#issuecomment-68457628

Sounds like you can remove the connection test query, in which case HikariCP will use the ``isValid()`` method instead, which seemed to work for that H2 user.

**Comment by mi-st** [comment]
Removing validation query  solves the problem. Thanks
