### ISSUE TITLE
Add pool name to PoolInitializationException to facilitate troubleshooting.

### ISSUE THREAD

**Issue by pasfilip** [brettwooldridge/HikariCP#802]
Would it be possible to add the name of the pool that failed to initialize in the exception?
If you have several pools configured it's not always clear which pool is affected...

**Comment by brettwooldridge** [comment]
@pasfilip Pull requests appreciated.

**Comment by brettwooldridge** [comment]
@pasfilip Opps, I didn't notice, this is already fixed in v2.5.2 (not yet released).
