### ISSUE TITLE
Add an option to configure jmx mbean name

### ISSUE THREAD

**Issue by pasfilip** [brettwooldridge/HikariCP#804]
Looks like when I deploy 2 applications into a single container (In my case tomcat) which use the same definition for the datasource that they interfere with each other on jmx level.
Would it be possible to provide some kind of customization facility like prefixing or suffixing the jmx bean name or providing a callback to customize the jmx bean name?
That way I could customize the bean name by for example adding the application name.

**Comment by brettwooldridge** [comment]
Just set the pool name configuration property to name each pool uniquely.  The pool name is part of the JMX name.

**Comment by pasfilip** [comment]
Yep that should do the trick!
Didn't think of the most obvious solution.
Thanks for the feedback!
