### ISSUE TITLE
How to configure Play to being able to configure HikariCP via the hikaricp.properties file

### ISSUE THREAD

**Issue by benelot** [brettwooldridge/HikariCP#807]
Hello,

I ported our application using play to the newest version and learned that it now uses the HikariCP. We have been configuring jdbc in a specific manner and I see that HikariCP can configure jdbc via a properties file. It seems that for a certain old Hikari plugin for play it was possible to set the file using the following setting in the application.conf:

       db.default.hikaricp.file="conf/hikaricp.properties"

How can this be achieved now that HikariCP is the default connection pool and the plugin is not necessary anymore?

**Comment by brettwooldridge** [comment]
@benelot This is a question for Play, we have no idea.

**Comment by benelot** [comment]
Thanks for the quick answer. I thought you would probably know since I expected that they asked you how to do it best. Good work, keep it up!
