### ISSUE TITLE
Debug mode to store stacktrace referencing call stack of getConnection()

### ISSUE THREAD

**Issue by HaraldKi** [brettwooldridge/HikariCP#808]
We are most likely facing a resource leak where after several hours we run out of connections with
```
2017-01-13T20:54:19,616+0100    ERROR   com.raytion.connector.windream.dbutil.WindreamSqlConnectionUtil pool-4-thread-1 Could not retrieve connection to db jdbc:sqlserver://xxxx:1433;databaseName=yyyy: HikariPool-1 - Connection is not available, request timed out after 30000ms.
 |java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30000ms.
 |      at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:550)
 |      at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:188)
 |      at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:147)
 |      at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:83)
 ```

despite the fact that we should not be using more than the configured maximum. We already checked all getConnection() to be paired with a close() on the connection and all looks good.

Feature suggestion: it would be great if, in a debug mode, the full stack trace would be stored in a connection object whenever getConnection() is called. This would allow to grab a heap dump and see in the eclipse memory analyzer (or similar) where each connection was actually created.

**Comment by brettwooldridge** [comment]
@HaraldKi If you enable the ``leakDetectionThreshold`` this is done.

Calling ``getConnection()`` will [create a leak task](https://github.com/brettwooldridge/HikariCP/blob/dev/src/main/java/com/zaxxer/hikari/pool/HikariPool.java#L178), the leak task will [capture the stacktrace](https://github.com/brettwooldridge/HikariCP/blob/dev/src/main/java/com/zaxxer/hikari/pool/ProxyLeakTask.java#L60) and schedule itself, and a reference to the leak task [will be stored](https://github.com/brettwooldridge/HikariCP/blob/dev/src/main/java/com/zaxxer/hikari/pool/ProxyConnection.java#L94) in the ``ProxyConnection`` instance returned from ``getConnection()``.

Therefore, all threads holding connections from the pool, through a chain of references have access to the stack trace where the connection was obtained.
