### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by Emperor88** [brettwooldridge/HikariCP#81]
This exception gets thrown on quite frequently:
Exception in thread "Thread-20" java.lang.RuntimeException: java.lang.NullPointerException
    at com.mysql.jdbc.JDBC4Connection$1$1.run(JDBC4Connection.java:106)
Caused by: java.lang.NullPointerException
    at com.mysql.jdbc.ConnectionImpl.abortInternal(ConnectionImpl.java:1229)
    at com.mysql.jdbc.JDBC4Connection$1$1.run(JDBC4Connection.java:104)

I'm configuring HikariCP like this:
            HikariConfig config = new HikariConfig();
            config.setMinimumPoolSize(1);
            config.setMaximumPoolSize(3);
            config.setInitializationFailFast(true);
            config.setDriverClassName("com.mysql.jdbc.Driver");
            config.setJdbcUrl("jdbc:mysql://" + URL);
            config.setUsername(USERNAME);
            config.setPassword(PASSWORD);
            config.setJdbc4ConnectionTest(true);
            pool = new HikariDataSource(config); 

Changing idle timeout value seems to influence the exception being thrown (but doesn't stop it from happening).
I'm probably doing something wrong, as I couldn't find simular problems when searching on google.

**Comment by MMuzaffar** [comment]
What Connector version you are using now?

**Comment by MMuzaffar** [comment]
I replaced com.mysql.jdbc_5.1.5.jar file with  mysql-connector-java-8.0.11.jar in \WebContent\WEB-INF\lib folder and these exceptions gone.

**Comment by MMuzaffar** [comment]
> This thread indicates that it is a bug with the MySQL JDBC driver implementation of the `Connection.isValid()` method -- which is what HikariCP uses by default. I would recommend two things: first, make sure you are using the latest MySQL Connector/J version, and second change HikariCP to use query-based connection testing like this:
> 
> ```java
> config.setJdbc4ConnectionTest(false);
> config.setConnectionTestQuery("/* ping */ SELECT 1");
> ```

I don't know where are these configs?
