### ISSUE TITLE
Hikari is prone to not being able to create filler/adder threads

### ISSUE THREAD

**Issue by guven** [brettwooldridge/HikariCP#810]
Please see this post for details:

https://github.com/kimchy/kimchy.github.com/blob/master/_posts/2008-11-23-juc-executorservice-gotcha.textile

**Comment by brettwooldridge** [comment]
@guven We are aware of the behaviors of ``ThreadPoolExecutor``, and HikariCP is subject to none of these issues.

All HikariCP ``ThreadPoolExecutor`` instances consist of a single thread (i.e. core = max = 1), and a bounded queue:
```java
LinkedBlockingQueue<Runnable> queue = new LinkedBlockingQueue<>(queueSize);
ThreadPoolExecutor executor = new ThreadPoolExecutor(1 /*core*/, 1 /*max*/, 5 /*keepalive*/, SECONDS, queue, threadFactory, policy);
```
None of the issues described on the referenced page apply to HikariCP usage.
