### ISSUE TITLE
minIdle set to -1 not to 10 by default

### ISSUE THREAD

**Issue by tomekw** [brettwooldridge/HikariCP#812]
I've noticed this when working on a wrapper to HikariCP in JRuby - when `maximumPoolSize` is not set (and it should default to 10) then `minimumIdle` is set to `-1` (as it's initialized with this value) instead of `10`.

I suspect this https://github.com/brettwooldridge/HikariCP/blob/dev/src/main/java/com/zaxxer/hikari/HikariConfig.java#L898-L904 is done too late and the getter can be called earlier leaking the invalid value.

Does it make sense?

**Comment by tomekw** [comment]
In fact the same applies to `maxPoolSize`

**Comment by brettwooldridge** [comment]
@tomekw Validation is not applied until the pool is started.  And then once it is, it cannot be changed.  Before pool start, values can be changed in any order.

**Comment by brettwooldridge** [comment]
No validation is done until the pool is started.  You can call ``HikariConfig.validate()`` directly if you want.

**Comment by tomekw** [comment]
Makes sense! Thanks!
