### ISSUE TITLE
How to configure the datasource properties in the configuration file

### ISSUE THREAD

**Issue by benelot** [brettwooldridge/HikariCP#814]
Hello,

I am trying to configure the datasource properties as they are here:
https://github.com/brettwooldridge/HikariCP#initialization

However, I can not find a way to configure them within the configuration file. Is there a possibility to do this?

**Comment by billoneil** [comment]
The link you listed shows an example of using a `.properties` file. see under `Example property file:` Is this not what you were looking for? If you want to use some other configuration framework just pass the config to some helper method and construct the datasource yourself.

**Comment by benelot** [comment]
I am sorry, I was not clear enough. I mean that I can not find a way to configure properties that are then configurations for jdbc such as:
     
     config.addDataSourceProperty("cachePrepStmts", "true");
     config.addDataSourceProperty("prepStmtCacheSize", "250");
     config.addDataSourceProperty("prepStmtCacheSqlLimit", "2048");

Can they not be configured via the properties file?

**Comment by billoneil** [comment]
Take a look at https://github.com/brettwooldridge/HikariCP/blob/dev/src/main/java/com/zaxxer/hikari/util/PropertyElf.java#L45

Looks like you should be able to do
`dataSource.cachePrepStmts=true`

**Comment by benelot** [comment]
Alright! Thanks for sorting this out for me!

**Comment by brettwooldridge** [comment]
@billoneil Thanks!

**Comment by benelot** [comment]
I took this a little further since we are using HikariCP with the PlayFramework:
(https://groups.google.com/d/msg/play-framework/kdFEqPMgqFk/k22DTkc8AQAJ)

In the play framework, the options can be passed to the hikaricp using the application.conf like this:

	db {
	  default {
		driver=com.mysql.jdbc.Driver
		url="jdbc:mysql://localhost/some_database"
		username=someuser
		password="a strong password"
		hikaricp {
		  dataSource {
			cachePrepStmts=true
			prepStmtCacheSize=250
			prepStmtCacheSqlLimit=2048
		  }
		}
	  }
	}

I hope this helps people that come across the same problems as I did.
