### ISSUE TITLE
Discrepancy between resource-based config and java-based config

### ISSUE THREAD

**Issue by icey502** [brettwooldridge/HikariCP#815]
Hi All,

I'm in the midst of a legacy Java (Tomcat 8, non-Spring) backend that I am attempting to move from the old tomcat + context.xml database configuration to something a bit more dynamic.  As such, I have the Hikari pool working normally with a context resource like this (sensitive parts cut):

```
<Resource auth="Container"
             closeMethod="close"
             driverClassName="org.postgresql.Driver"
             factory="com.zaxxer.hikari.HikariJNDIFactory"
             maximumPoolSize="30"
             connectionTimeout="30000"
             dataSource.implicitCachingEnabled="true"
             username=“~~~~”
             password=“~~~~”
             poolName=“~~~~~~~~”
             name="jdbc/….”
             jdbcUrl="jdbc:postgresql://localhost:5432/….”
             type="javax.sql.DataSource"
             />
```

However, when I attempt to do the same with a purely manual config like this:

```
HikariConfig config = new HikariConfig();
 config.setDriverClassName("org.postgresql.Driver");
config.setJdbcUrl("jdbc:postgresql://localhost:5432/….”); 
config.setUsername("~~~~"); 
config.setPassword("~~~~");
 config.setPoolName("~~~~");
 config.setMaximumPoolSize(30); 
config.setConnectionTimeout(30000);
DataSource ds = new HikariDataSource(config);
Connection con = ds.getConnection();
```

....I immediately get the following exception:

```com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: FATAL: sorry, too many clients already```

Since I can make this exception happen - or not - purely by switching between the manual method and the Resource/context approach, with zero database config changes between the scenarios, I suspect that either I am doing something daft, or there is some other trickery around the manual config.  Any ideas, or known issues perhaps?

**Comment by billoneil** [comment]
Try looking here. http://stackoverflow.com/questions/2757549/org-postgresql-util-psqlexception-fatal-sorry-too-many-clients-already

It appears you are hitting the max connections to the server itself. This is not a HikariCP issue.

**Comment by icey502** [comment]
I'll dig deeper, thanks.
