### ISSUE TITLE
switch user on existing connection

### ISSUE THREAD

**Issue by qinfchen** [brettwooldridge/HikariCP#816]
Does HIkariCP support on something like https://www.postgresql.org/docs/9.6/static/sql-set-session-authorization.html?

EDIT: I think it can be done vi a query statement.

**Comment by brettwooldridge** [comment]
HikariCP does not support it inherently.  You can extend the HikariDataSource and surround the getConnection() with SET SESSION AUTHORIZATION and RESET AUTHORIZATION.

Or [use a proxy](https://gist.github.com/brettwooldridge/7564827e45d67e1dc8dd) to perform the interception.
