### ISSUE TITLE
Mysql connection keep on increasing even after maxpoolsize

### ISSUE THREAD

**Issue by AnshulJain1985** [brettwooldridge/HikariCP#818]
Hi
I have below configuration for Hikari for mysql server using from Java:
maxPoolSize = 5
idleTimeout = 600000
checkConnection = Select 1

But still mysql connection keep on increasing and not just limiting to defined maxPoolSize.
I have stopped all the processes on the server and just my application is running to make sure it connections are not been created from somewhere else.
Can you please help me out here.

**Comment by brettwooldridge** [comment]
@AnshulJain1985 Please enable debug logging for the package ``com.zaxxer.hikari``, you should see a log entry for every created connection.

If HikariCP was so broken as to exceed the maxPoolSize limit then nobody would use it; something else is going on in your application.

Also, ``checkConnection`` is not a valid property, I don't know where you got that from.

**Comment by AnshulJain1985** [comment]
Sorry its connectionInitSql. We have named it checkConnection.
I will enable debug logs and provide you the details. I was also wondering the same but I was trying to debug since morning but not able to find anything.
Thanks for your response.

**Comment by brettwooldridge** [comment]
@AnshulJain1985 Can you provide an update on this issue?

**Comment by AnshulJain1985** [comment]
You can close this issue. I am not able to find the issue even after digging for a week. Atlast I recreate my server and yesterday and now it is working fine. I have even compare the mysql parameters its exactly same. Thanks for followup.
