### ISSUE TITLE
HikariPool$PoolInitializationException is not a SQLException, intended?

### ISSUE THREAD

**Issue by ktschmidt** [brettwooldridge/HikariCP#824]
Using 2.5.1 with MySQL, if the JDBC URL is configured incorrectly pointing to a non-existent database/schema, the MySQL driver throws a MySQLSyntaxErrorException which is a SQLException.  HikariCP wraps this in a HikariPool$PoolInitializationException which is not an SQLException.

This means that code I have that calls DataSource.getConnection() and catches SQLException that works just fine using MySQL directly fails when using HikariCP as the exception is not caught.

Was there a reason HikariCP's pool init exception isn't a SQLException?  Or should it be for this reason?

**Comment by brettwooldridge** [comment]
@ktschmidt I realized this is [already fixed](https://github.com/brettwooldridge/HikariCP/blob/dev/src/main/java/com/zaxxer/hikari/HikariDataSource.java#L100) in v2.6.0.

**Comment by ktschmidt** [comment]
Good to hear.  Thanks!
