### ISSUE TITLE
Default constructor specific hikaricp.configurationFile

### ISSUE THREAD

**Issue by aetelani** [brettwooldridge/HikariCP#826]
According the documentation the _hikaricp.configurationFile_ property is read only when default, ie empty constructor is called. I interpreted that configurationFile is not read when property argument is used.

Would it be possible to read the configurationFile as well and for example combine the given parameters and the file parameters? 

Lets think use case where passwords are stored in encrypted partition while other parameters are are given in configuration. There could be multiple databases so same configurationFile might not be enough for all _DataSources_.

**Comment by brettwooldridge** [comment]
@aetelani Even when the constructor *with* the ``Properties`` argument [is used](https://github.com/brettwooldridge/HikariCP/blob/dev/src/main/java/com/zaxxer/hikari/HikariConfig.java#L129), the default constructor is called first and the properties file indicated by *hikaricp.configurationFile* [is read](https://github.com/brettwooldridge/HikariCP/blob/dev/src/main/java/com/zaxxer/hikari/HikariConfig.java#L116).
