### ISSUE TITLE
Connection is not available Error

### ISSUE THREAD

**Issue by chinmaya** [brettwooldridge/HikariCP#830]
HikariCP is reporting "Connection is not available" error, and this is failing all the following database calls. After a closer look on database server, I did not see any active connection, however the HickariCP housekeep is reporting all the connections are active.

Looks like under certain conditions, the HikariPool reports active connections although there are none.

Has this issue been reported before? Any thoughts on what could be wrong?

-- Chinmaya

Some debug info

> 
> Caused by: org.hibernate.exception.JDBCConnectionException: Could not open connection
> 	at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:65)
> 	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:49)
> 	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:126)
> 	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:112)
> 	at org.hibernate.engine.jdbc.internal.LogicalConnectionImpl.obtainConnection(LogicalConnectionImpl.java:235)
> 	at org.hibernate.engine.jdbc.internal.LogicalConnectionImpl.getConnection(LogicalConnectionImpl.java:171)
> 	at org.hibernate.internal.SessionImpl.connection(SessionImpl.java:450)
> 	at org.springframework.orm.hibernate4.HibernateTransactionManager.doBegin(HibernateTransactionManager.java:450)
> 	... 41 common frames omitted
> Caused by: java.sql.SQLTransientConnectionException: HikariPool-0 - Connection is not available, request timed out after 600000ms.
> 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:213)
> 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:163)
> 	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:85)
> 	at org.springframework.jdbc.datasource.lookup.AbstractRoutingDataSource.getConnection(AbstractRoutingDataSource.java:164)
> 	at org.hibernate.engine.jdbc.connections.internal.DatasourceConnectionProviderImpl.getConnection(DatasourceConnectionProviderImpl.java:139)
> 	at org.hibernate.internal.AbstractSessionImpl$NonContextualJdbcConnectionAccess.obtainConnection(AbstractSessionImpl.java:380)
> 	at org.hibernate.engine.jdbc.internal.LogicalConnectionImpl.obtainConnection(LogicalConnectionImpl.java:228)
> 	... 44 common frames omitted
> 
> 2017-02-21 12:14:38.582 [Hikari housekeeper (pool HikariPool-0)] DEBUG com.zaxxer.hikari.pool.HikariPool - Before cleanup	pool HikariPool-0 stats (total=100, active=100, idle=0, waiting=69)
> 2017-02-21 12:14:38.582 [Hikari housekeeper (pool HikariPool-0)] DEBUG com.zaxxer.hikari.pool.HikariPool - After cleanup	pool HikariPool-0 stats (total=100, active=100, idle=0, waiting=69)
> 
> 
> java.sql.SQLTransientConnectionException: HikariPool-0 - Connection is not available, request timed out after 600000ms.
> 	at org.quartz.impl.jdbcjobstore.JobStoreCMT.getNonManagedTXConnection(JobStoreCMT.java:168)
> 	at org.quartz.impl.jdbcjobstore.JobStoreSupport.doCheckin(JobStoreSupport.java:3245)
> 	at org.quartz.impl.jdbcjobstore.JobStoreSupport$ClusterManager.manage(JobStoreSupport.java:3858)
> 	at org.quartz.impl.jdbcjobstore.JobStoreSupport$ClusterManager.run(JobStoreSupport.java:3895)
> Caused by: java.sql.SQLTransientConnectionException: HikariPool-0 - Connection is not available, request timed out after 600000ms.
> 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:213)
> 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:163)
> 	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:85)
> 	at org.springframework.jdbc.datasource.lookup.AbstractRoutingDataSource.getConnection(AbstractRoutingDataSource.java:164)
> 	at org.springframework.scheduling.quartz.LocalDataSourceJobStore$2.getConnection(LocalDataSourceJobStore.java:135)
> 	at org.quartz.utils.DBConnectionManager.getConnection(DBConnectionManager.java:108)
> 	at org.quartz.impl.jdbcjobstore.JobStoreCMT.getNonManagedTXConnection(JobStoreCMT.java:165)
> 	... 3 common frames omitted

**Comment by brettwooldridge** [comment]
It's a connection leak.  Enable the leakDetectionThreshold.  Also, unless your DB server has 64-cores, 100 connections is insane.

**Comment by chinmaya** [comment]
Pretty interesting conclusion. Couple of questions ... how do you figure this is a connection leak? We didn't see this issue until system was under huge loads. Also what's the correlation between connection and cores?

**Comment by chinmaya** [comment]
One more note that: leakDetectionThreshold was enabled... I did not see any warnings or errors. I'm on 2.4.1. Could there be a bug in pool management, or in ConcurrentBag.

**Comment by brettwooldridge** [comment]
The fact this occurs only under "huge load" is something you might have mentioned in your initial report.  99% of the time a pool stuck at maxPoolSize is a

I am not aware of any previous issue that exhibits the behavior you describe, though 2.4.1 was released over 2 years ago and is 10 releases behind current.  If you can reproduce this issue on the current release we will be happy to reopen this issue and investigate.

**Comment by roytmana** [comment]
I actually observed similar behaviour under load but I am not 100% sure as I did not have time to investigate deeply. Under stress with Hikari 2.6.0 my active connections number hit the ceiling (20) and the application seized. I stopped the load  and it took 3-5 minutes to recover without single Connection Leak stack trace  and without doing anything useful during that time (I was watching activity log). As I said no connection leaks were logged and active count returned to zero after a while. I was able to get to the same load level when ramping up my load gradually and in steady state it used 3-5 active connections on average but if i turned full load at once it went up to 20 active connections and locked after 15-20 seconds with the app logging errors that connection was not available  after 30 sec timeout. Sorry I could not offer any more specifics details

**Comment by brettwooldridge** [comment]
@roytmana Thanks for the valuble feedback.  Every bit in information helps.  In your "full load", how many threads/clients are hitting the pool?

**Comment by brettwooldridge** [comment]
@roytmana Any chance you can re-run the load test with debug logging enabled for ``com.zaxxer.hikari`` and capture the log up to the point where the timeouts start occurring?

**Comment by brettwooldridge** [comment]
Thanks!  I'll try to come up with a synthetic test based on your feedback.

**Comment by brettwooldridge** [comment]
@roytmana I created a [synthetic test](https://github.com/brettwooldridge/HikariCP/blob/dev/src/test/java/com/zaxxer/hikari/pool/SaturatedPoolTest830.java), but if there is an issue it was not surfaced by that test.

The test sets up a HikariCP pool with ``minimumIdle=5``, ``maximumPoolSize=10``, and ``connectionTimeout=1000ms``.  The test creates an Executor with a pool of 50 threads.  Each submitted Runnable executes a simulated query that takes 1000ms (1 sec) to complete.

The test starts with an immediate spike of 50 threads, each doing:
```java
try (Connection conn = ds.getConnection();
     Statement stmt = conn.createStatement()) {
   stmt.execute("SELECT bogus FROM imaginary");
}
catch (SQLException e) {
   LOGGER.info(e.getMessage());
}
```
The first log in the test shows:
```
saturatedPoolTest - Before cleanup stats (total=1, active=1, idle=0, waiting=49)
```
Immediately after starting the 50 threads, the test continues to submit new requests:
```
Active threads 50, submissions per second 12, waiting threads 49
```
With a pool of 10 connections, at 1000ms (1 sec) per request, the maximum thoughput of the pool is 10 req/sec.  However, the test starts out at 12 req/sec, and then after 6 seconds it drops the submission rate to 11 req/sec, and then finally after 12 seconds it drops the submission rate to 10 req/sec.

The first "drop" is logged as ``Switching to 90ms sleep`` (11 req/sec), and the second "drop" is logged as "Switching to 100ms sleep" (10 req/sec).

Of course, timeouts are flying left and right, but at some point not too long after the new request submission rate drops to 10 req/sec we expect to come into balance.  This does occur at roughly 24 seconds into the run and is logged as ``Timeouts have subsided.``

The [full log is here](https://gist.github.com/brettwooldridge/788be8842eceeabc84d0f2adce31790c).

**Comment by roytmana** [comment]
@brettwooldridge than you very much for the test and your detailed description. I feel much better :-)
