### ISSUE TITLE
Why recommended using dataSourceClassName instead of jdbcUrl?   QUESTION

### ISSUE THREAD

**Issue by Yaytay** [brettwooldridge/HikariCP#834]
Hi,

In the readme you say: We recommended using dataSourceClassName instead of jdbcUrl, but either is acceptable.
I can't find any reason for the recommendation.

I'm starting on a new project using Hikari, which I haven't used before.
This project will use H2 in test and MS SQL in live (other projects might use MySQL in live).
In the past I've always configured datasources using JDBC URL, so I'd like to understand what the benefit of changing would be, even if it's marginal.

Thanks

Jim

**Comment by brettwooldridge** [comment]
There is a tendency for users to add configuration properties to the URL.  MySQL itself supports over 100 properties, so you can imagine what a nightmare understanding or maintaining that is.

Users can of course use a Properties set, which is much better, but still has the problem that a minor typo in a key results in a property being ignored.

Using a DataSource results in setters being called, so a typo will result in an exception, which is much better.  Additionally, setters tend to provide value validation.

Having said that, both MySQL and MariaDB DataSource implementations are broken with respect to HikariCP's use of network timeouts, so ultimately there is no alternative for those databases.

**Comment by Yaytay** [comment]
Thank you.
