### ISSUE TITLE
Add scylladb support?

### ISSUE THREAD

**Issue by 120011676** [brettwooldridge/HikariCP#837]
#### Environment
```
HikariCP version: x.x.x
JDK version     : 1.8.0_111
Database        : scylladb
Driver version  : x.x.x
```
-----------------------------------------------------------------------------------------

Add scylladb support?

**Comment by brettwooldridge** [comment]
What is scylladb, and why don't it work now?  If it has a compliant JDBC driver it should work.

**Comment by brettwooldridge** [comment]
@120011676 Ah, I see ... http://www.scylladb.com ... if they have a JDBC driver it should work.

**Comment by 120011676** [comment]
@brettwooldridge Good,Yes,My fault.
