### ISSUE TITLE
HikariCP+Spring Boot+PostgreSql

### ISSUE THREAD

**Issue by 18807600203** [brettwooldridge/HikariCP#839]
#### Environment
```
HikariCP version: 2.6.1
JDK version     : 1.8.0_66
Database        : PostgreSQL 9.6.2
Driver version  : org.postgresql.Driver 42.0.0
```
application.properties
```
spring.datasource.type=com.zaxxer.hikari.HikariDataSource
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc\:postgresql\://127.0.0.1\:5432/um_w?zeroDateTimeBehavior\=convertToNull&useUnicode\=true&characterEncoding\=utf-8&useSSL\=false&autoReconnect\=true&autoReconnectForPools\=true&rewriteBatchedStatements\=true
spring.datasource.username=postgres
spring.datasource.password=Admin@123
spring.datasource.hikari.connectionTimeout=30000
spring.datasource.hikari.idleTimeout=30000
spring.datasource.hikari.maximumPoolSize=20
spring.datasource.hikari.maxLifetime=0
spring.datasource.hikari.connectionTestQuery=SELECT 1
spring.datasource.hikari.autoCommit=false
```
-----------------------------------------------------------------------------------------
when I run my spring boot app , The console will print this message
`HikariPool-1 - Driver does not support get/set network timeout for connections. (这个 org.postgresql.jdbc.PgConnection.getNetworkTimeout() 方法尚未被实作。)`

Does this have any impact on the program?

**Comment by brettwooldridge** [comment]
That message is merely informational, it does not affect the function of you program.  It does limit the ability of HikariCP to mitigate the effects of a [network partition](https://en.m.wikipedia.org/wiki/Network_partition) event. If you are in an environment where recovery from failures are out of your control, for example in a PaaS environment, you may wish to investigate the pgjdbc-ng driver.
