### ISSUE TITLE
[question] Why HikariCP doesn't forcefully close abandoned connections?

### ISSUE THREAD

**Issue by mohsen** [brettwooldridge/HikariCP#843]
```
#### Environment
HikariCP version: HikariCP-2.4.6.jar
JDK version     : 1.8.0_121
Database        : MariaDB 10.1.21
Driver version  : mysql-connector-java-5.1.38.jar
-----------------------------------------------------------------------------------------
```
I have a web application with the following configuration. I'm going out of connection on average every two weeks in a medium-traffic website.

    <bean id="internalDataSource" class="com.mysql.jdbc.jdbc2.optional.MysqlDataSource">
        <property name="user" value="${db.username}" />
        <property name="password" value="${db.password}" />
        <property name="URL" value="${db.url}" />
        <property name="cachePrepStmts" value="true" />
        <property name="prepStmtCacheSize" value="250" />
        <property name="prepStmtCacheSqlLimit" value="2048" />
        <property name="autoSlowLog" value="false" />
        <property name="logSlowQueries" value="true" />
        <property name="slowQueryThresholdMillis" value="10000" />
        <property name="dumpQueriesOnException" value="true" />
    </bean>

    <bean id="dataSource" class="com.zaxxer.hikari.HikariDataSource" destroy-method="close">
        <property name="dataSource" ref="internalDataSource" />
        <property name="metricRegistry" ref="metricRegistry" />
        <property name="maxLifetime" value="1800000" /> 
        <property name="minimumIdle" value="1" />
        <property name="maximumPoolSize" value="10" />
        <property name="connectionTimeout" value="30000" />
        <property name="poolName" value="myConnPool" />
        <property name="leakDetectionThreshold" value="45000" />
        <property name="registerMbeans" value="true" />
    </bean>

Here is the related exception part:
```
    Caused by: java.sql.SQLTransientConnectionException: myConnPool - Connection is not available, request timed out after 15765ms.
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:196)
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:147)
        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:99)
        at org.hibernate.engine.jdbc.connections.internal.DatasourceConnectionProviderImpl.getConnection(DatasourceConnectionProviderImpl.java:122)
        at org.hibernate.internal.AbstractSessionImpl$NonContextualJdbcConnectionAccess.obtainConnection(AbstractSessionImpl.java:386)
        at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.acquireConnectionIfNeeded(LogicalConnectionManagedImpl.java:84)
```

When this happens, no open connection can be seen on MySQL/MariaDB process list. Is there any chance to either forcefully close abandoned connections (and return them to the pool), or log the full stacktrace of the leaked connection (without DEBUG log level enabled)?

**Comment by billoneil** [comment]
Why can't you enable debug logging?

**Comment by brettwooldridge** [comment]
If you enable the leakDetectionThreshold HikariCP will log the leak at WARN level, so you shouldn't need DEBUG logging for that.

However, debug logging is not particularly noisy, and will give you logs showing connection acquisition and retirement.  You can even configure you logging to send com.zaxxer.hikari to a separate log file, if you do find it generates too many logs.

**Comment by mohsen** [comment]
> If you enable the leakDetectionThreshold HikariCP will log the leak at WARN level, so you shouldn't need DEBUG logging for that.

Thanks for the answer. Seems to be a configuration issue in my logback config file. I added HikariCP package to the logback config file and I can see some INFO and WARN logs now.

Can HikariCP auto-close abandoned connections and return them to the pool? I can see nothing related to closing connetion in `ProxyLeakTask`.

**Comment by brettwooldridge** [comment]
@mohsen HikariCP does not close abandoned connections; to do so would be to cover up an application bug.  If you need a pool that wipes your b*tt for you, you can try Tomcat. 😛  HikariCP can point out the source of the leak for you, but it won't sweep it under the rug.

**Comment by mohsen** [comment]
@brettwooldridge 
Sorry to bring up this issue again. I'm a bit confused about the meaning of a leaked connection. According to documentation, setting `leakDetectionThreshold` causes to log (WARN) stacktrace of the leaked connection, after threshold is passed and connection is not closed (returned back to the pool).

If I'm correct, a leaked connection is the source of going out of connection issue. Someone gets a connection and holds it too much and and do not return it back to the pool. Tomcat CP will close this connection (according to your comment) and HikariCP will just prints stacktrace of the current state of thread holding the connection.

Confusion here is that when I'm going out of connection, all logged leaked connection stack traces are just waiting for a connection from the pool:

```
org.hibernate.engine.jdbc.connections.internal.DatasourceConnectionProviderImpl.getConnection(DatasourceConnectionProviderImpl.java:122)
        at org.hibernate.internal.NonContextualJdbcConnectionAccess.obtainConnection(NonContextualJdbcConnectionAccess.java:35)
        at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.acquireConnectionIfNeeded(LogicalConnectionManagedImpl.java:115)
        at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.getPhysicalConnection(LogicalConnectionManagedImpl.java:145)
        at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.getConnectionForTransactionManagement(LogicalConnectionManagedImpl.java:263)
        at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.begin(LogicalConnectionManagedImpl.java:271)
        at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl.begin(JdbcResourceLocalTransactionCoordinatorImpl.java:203)
        at org.hibernate.engine.transaction.internal.TransactionImpl.begin(TransactionImpl.java:56)

```

And here is the code for `org.hibernate.engine.jdbc.connections.internal.DatasourceConnectionProviderImpl.getConnection()`:

	public Connection getConnection() throws SQLException {
		if ( !available ) {
			throw new HibernateException( "Provider is closed!" );
		}
		return useCredentials ? dataSource.getConnection( user, pass ) : dataSource.getConnection();
	}

the last line of the method (source of exception) is just trying to acquire a connection from the pool. What does it mean? A leaked connection means a thread which cannot get a new connection or a thread which held a connection too much?

**Comment by jnehlmeier** [comment]
@mohsen The stack traces tells you who has obtained the connection that now has been leaked. Basically when any thread calls getConnection() and leak detection is enabled then HikariCP will create a new exception to capture the stack trace to the getConnection() call and remembers it. Once the leak detection threshold is reached that remembered exception will be logged.

So your stack trace means that Hibernate has obtained a connection from your pool but that connection has not been closed by Hibernate within the time you have specified for the leak detection threshold. Maybe you forgot to close the Hibernate session / EntityManager once your application code is done?

**Comment by xBurnsed** [comment]
> @mohsen HikariCP does not close abandoned connections; to do so would be to cover up an application bug. If you need a pool that wipes your b*tt for you, you can try Tomcat. 😛 HikariCP can point out the source of the leak for you, but it won't sweep it under the rug.

I understand this point, but sometimes this is not our choice.
For example, I am in a company right now which is migrating some legacy code made from another company and we have detected that there are many leaks and analyzing the full application to start manually closing the connections is just not feasible. We still wanted to use Hikari for the performance boost but it doesn't seem it is going to be a fit in this scenario.

**Comment by jnehlmeier** [comment]
> I understand this point, but sometimes this is not our choice. For example, I am in a company right now which is migrating some legacy code made from another company and we have detected that there are many leaks and analyzing the full application to start manually closing the connections is just not feasible. We still wanted to use Hikari for the performance boost but it doesn't seem it is going to be a fit in this scenario.

You could implement a delegating `DataSource` that wraps `HikariDataSource` and delegates all methods to it. In the same way you can implement a delegating `Connection` implementation that tracks time after creation and closes the underlying connection if a threshold is reached. That delegating connection then wraps the connection that Hikari has handed out. So after each `autoCloseConnectionDataSource.getConnection()` call the connection closes itself after some time and will return to the pool.

**Comment by xBurnsed** [comment]
> > I understand this point, but sometimes this is not our choice. For example, I am in a company right now which is migrating some legacy code made from another company and we have detected that there are many leaks and analyzing the full application to start manually closing the connections is just not feasible. We still wanted to use Hikari for the performance boost but it doesn't seem it is going to be a fit in this scenario.
> 
> You could implement a delegating `DataSource` that wraps `HikariDataSource` and delegates all methods to it. In the same way you can implement a delegating `Connection` implementation that tracks time after creation and closes the underlying connection if a threshold is reached. That delegating connection then wraps the connection that Hikari has handed out. So after each `autoCloseConnectionDataSource.getConnection()` call the connection closes itself after some time and will return to the pool.

This seems like a really good approach.
1. Create a connection wrapper that extends from the connection implementation and autocloses itself.
2. Search and replace all the Connection classes for the wrapper.

With this, I believe I could just use the normal Hikari Connection Pool without any issues.

**Comment by jnehlmeier** [comment]
> This seems like a really good approach.
> 
> 1. Create a connection wrapper that extends from the connection implementation and autocloses itself.
> 2. Search and replace all the Connection classes for the wrapper.
> 
> With this, I believe I could just use the normal Hikari Connection Pool without any issues.

You don't have to search all connection usages. See:

```java
class DelegatingConnection implements Connection {

  protected final Connection delegate;

  public DelegatingConnection(Connection delegate) {
    this.delegate = delegate;
  }

  // implement all methods by delegating to this.delegate
}

class DelegatingDataSource implements DataSource {

  protected final DataSource delegate;

  public DelegatingDataSource(DataSource delegate) {
    this.delegate = delegate;
  }

  // implement all methods by delegating to this.delegate
}

// Now your auto close implementations
class AutoClosingConnection extends DelegatingConnection {

  public AutoClosingConnection(Connection delegate, long autoCloseThreshold) {
    super(delegate);
    // implement your logic and call close() once threshold is reached
  } 

}

class AutoClosingConnectionDataSource extends DelegatingDataSource {

  public AutoClosingConnectionDataSource(DataSource delegate, long autoCloseThreshold) {
    super(delegate);
    // store threshold
  } 

  @Override
  public Connection getConnection() {
    return new AutoClosingConnection(delegate.getConnection(), threshold);
  }

}

// Then in your application just wrap hikari and use the pool as normal. 
// All connections will auto close now.
var autoClosingPool = new AutoClosingConnectionDataSource(hikariDataSource, threshold);
```

**Comment by xBurnsed** [comment]
> > This seems like a really good approach.
> > 
> > 1. Create a connection wrapper that extends from the connection implementation and autocloses itself.
> > 2. Search and replace all the Connection classes for the wrapper.
> > 
> > With this, I believe I could just use the normal Hikari Connection Pool without any issues.
> 
> You don't have to search all connection usages. See:
> 
> ```java
> class DelegatingConnection implements Connection {
> 
>   protected final Connection delegate;
> 
>   public DelegatingConnection(Connection delegate) {
>     this.delegate = delegate;
>   }
> 
>   // implement all methods by delegating to this.delegate
> }
> 
> class DelegatingDataSource implements DataSource {
> 
>   protected final DataSource delegate;
> 
>   public DelegatingDataSource(DataSource delegate) {
>     this.delegate = delegate;
>   }
> 
>   // implement all methods by delegating to this.delegate
> }
> 
> // Now your auto close implementations
> class AutoClosingConnection extends DelegatingConnection {
> 
>   public AutoClosingConnection(Connection delegate, long autoCloseThreshold) {
>     super(delegate);
>     // implement your logic and call close() once threshold is reached
>   } 
> 
> }
> 
> class AutoClosingConnectionDataSource extends DelegatingDataSource {
> 
>   public AutoClosingConnectionDataSource(DataSource delegate, long autoCloseThreshold) {
>     super(delegate);
>     // store threshold
>   } 
> 
>   @Override
>   public Connection getConnection() {
>     return new AutoClosingConnection(delegate.getConnection(), threshold);
>   }
> 
> }
> 
> // Then in your application just wrap hikari and use the pool as normal. 
> // All connections will auto close now.
> var autoClosingPool = new AutoClosingDataSource(hikariDataSource);
> ```

Thank you! I see what you mean now!

Do you have discord by any chance in case I have some doubts about this so we can continue this discussion?
I'd probably hit you up tomorrow!

Thanks once again
