### ISSUE TITLE
Implementation of HikariCP

### ISSUE THREAD

**Issue by JensVD** [brettwooldridge/HikariCP#847]
#### Environment = None
```
HikariCP version: x.x.x
JDK version     : 1.8.0_111
Database        : PostgreSQL|MySQL|...
Driver version  : x.x.x
```
-----------------------------------------------------------------------------------------
Hello

I'm an intern at an IT company in Belgium and they've asked me to research HikariCP thoroughly.
Now from all what I've read and studied I can see that it's a very performant and reliable connection pool but I don't know what the advantages would be for our platform.

Our application is a medical platform and because of this there is a lot of data. Now from what I can gather from JavaMelody and your comparisons between C3p0 (currently used) and HikariCp our connection pool is definitely fast enough but our sql queries take much longer.
We also never had any problems with the reliability or stability of C3p0 so far.

Considering all this will a change to HikariCP have any significant advantages for us?

Jens

**Comment by brettwooldridge** [comment]
@JensVD It is always hard to argue against a solution that is stable.  If C3P0 is reliable in your application, that is harder to argue against.  Other users of C3P0 have different experiences; just within the past 24h someone tweeted me:

![screen shot 2017-03-23 at 21 17 57](https://cloud.githubusercontent.com/assets/1538661/24247270/578ae6c6-100e-11e7-8d77-2f559311cb2f.png)

I guess one question is, do you have a suite of automated tests?  And do you have a suite of performance tests?

While I have no doubt that you will not find a more reliable pool, and in terms of strict adherence to JDBC compliance, than HikariCP.  There are cases of users upgrading to HikariCP only to uncover application coding errors that were allowed by another pool lax adherence to standards.  For that reason it is important to have some way, preferably automated, of putting the application through its paces if you switch to HikariCP.

Performance improvements are highly application specific, but in general I would still expect to see measurable improvements in performance.  Again, having either application monitoring metrics or, better, a suite of performance (load) tests can help quantify them.

**Comment by JensVD** [comment]
I'll use this information in my report and to pass along.

Thanks for the quick answer
