### ISSUE TITLE
Hikari spits out plaintext password into log

### ISSUE THREAD

**Issue by lucian303** [brettwooldridge/HikariCP#850]
From log: `DEBUG com.zaxxer.hikari.HikariConfig - jdbcUrl......................... URL_WITH_PLAIN_TEXT_PASSWORD`

Not sure if this is only when using a url/jdbc url. I did see the `DEBUG com.zaxxer.hikari.HikariConfig - dataSourceProperties............{password=<masked>}` line so I'm certain this is unintended. 

#### Environment
```
HikariCP version: 1.7.5
JDK version     : 1.8.0_111
Database        :MySQL
Driver version  : 0.6.1
```
-----------------------------------------------------------------------------------------

**Comment by brettwooldridge** [comment]
@lucian303 Don't put your password in the URL.  Set it as a datasource property, e.g.:
```
dataSource.user=test
dataSource.password=test
```
dataSource properties work even when URL-based configuration is used.

**Comment by lucian303** [comment]
I don't think I have an option with the Clojure wrapper library I'm using but I will see if it's possible. The password, however, should never be leaked into logs regardless of the way the user chooses the configure the software.

**Comment by brettwooldridge** [comment]
@lucian303 The username and password is available in the Clojure wrapper.  The URL is not logged by default, so it *does* require administrative action.  Presumably anyone who can alter the logging properties file can just as easily look in the pool configuration.

We can certainly take it as an enhancement request to *try* to filter the URL for the most common strings ("pass" or "password") but given the variety of drivers and authentication methods (straight password, LDAP, token, etc) it can only ever be a best effort.  The same is true with simple properties as well actually, if some driver used "auth" or "login" as a password it would not be filtered today.
