### ISSUE TITLE
Failed to validate connection org.mariadb.jdbc.MariaDbConnection, Could not read packet: Read timed out

### ISSUE THREAD

**Issue by pawel-kaminski-krk** [brettwooldridge/HikariCP#856]
#### Environment
```
HikariCP version: 2.6.1
JDK version     : 1.8.0_111
Database        : Amazon MariaDb
Driver version  : mariadb-java-client 1.5.7
```
-----------------------------------------------------------------------------------------
hi, 
we have a problem with HikariDataSource that after a while all connection from a pool are idle and Hikari is not recreating valid connection that can be used by incoming requests.

```
HikariConfig config = new HikariConfig();
config.setDriverClassName("org.mariadb.jdbc.Driver");
config.setJdbcUrl(format("jdbc:mariadb://%1s/space", dbUrl));
config.setConnectionTestQuery("SELECT 1");
config.setReadOnly(true);
config.setUsername(${user});
config.setPassword(${password});
config.setMetricRegistry(metricRegistry);
config.setMinimumIdle(poolSize); // set to 50
config.setMaximumPoolSize(poolSize); // set to 50
config.setConnectionTimeout(connectionTimeout); // set to 2000
// config.setIdleTimeout(); <- should be ignored as MinimumIdle == MaximumPoolSize
// config.setMaxLifetime(); <- 30 min should be enough

return new HikariDataSource(config);
```
on our test env after ~ 10 minutes (idle timeout?) from deployment we see that none of test passes, but it is enough to restart app or change (via JMX) poolSize and it will magically create proper connection and tests are passing. 

```
12:42:02.260 [jdbc-worker-7] DEBUG MDC[] com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Timeout failure stats (total=49, active=5, idle=44, waiting=0)
12:42:02.279 [HikariPool-1 connection adder] DEBUG MDC[] com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Added connection org.mariadb.jdbc.MariaDbConnection@6432d50d
12:42:02.279 [HikariPool-1 connection adder] DEBUG MDC[] com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - After adding stats (total=50, active=5, idle=45, waiting=0)
12:42:03.681 [jdbc-worker-3] WARN  MDC[] com.zaxxer.hikari.pool.PoolBase - HikariPool-1 - Failed to validate connection org.mariadb.jdbc.MariaDbConnection@14c193d7 ((conn:66687) Could not read packet: Read timed out. Query is : SELECT 1)
...
12:42:25.000 [jdbc-worker-8] DEBUG MDC[] com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Timeout failure stats (total=49, active=1, idle=48, waiting=0)
12:42:25.003 [HikariPool-1 connection adder] DEBUG MDC[] com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Added connection org.mariadb.jdbc.MariaDbConnection@546f71b4
12:42:25.003 [HikariPool-1 connection adder] DEBUG MDC[] com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - After adding stats (total=50, active=1, idle=49, waiting=0)
12:42:26.237 [jdbc-worker-3] WARN  MDC[] com.zaxxer.hikari.pool.PoolBase - HikariPool-1 - Failed to validate connection org.mariadb.jdbc.MariaDbConnection@79bc1518 ((conn:66696) Could not read packet: Read timed out. Query is : SELECT 1)
...
12:42:47.677 [HikariPool-1 housekeeper] DEBUG MDC[] com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Pool stats (total=50, active=0, idle=50, waiting=0)
12:43:17.677 [HikariPool-1 housekeeper] DEBUG MDC[] com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Pool stats (total=50, active=0, idle=50, waiting=0)
12:43:47.677 [HikariPool-1 housekeeper] DEBUG MDC[] com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Pool stats (total=50, active=0, idle=50, waiting=0)
12:44:17.678 [HikariPool-1 housekeeper] DEBUG MDC[] com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Before cleanup stats (total=50, active=0, idle=50, waiting=0)
12:44:17.688 [HikariPool-1 housekeeper] DEBUG MDC[] com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - After cleanup  stats (total=5, active=0, idle=5, waiting=0)
12:44:47.688 [HikariPool-1 housekeeper] DEBUG MDC[] com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Before cleanup stats (total=5, active=0, idle=5, waiting=0)
12:44:47.688 [HikariPool-1 housekeeper] DEBUG MDC[] com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - After cleanup  stats (total=5, active=0, idle=5, waiting=0)
12:44:47.720 [HikariPool-1 connection adder] DEBUG MDC[] com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Added connection org.mariadb.jdbc.MariaDbConnection@2a701693
12:44:47.723 [HikariPool-1 connection adder] DEBUG MDC[] com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Added connection org.mariadb.jdbc.MariaDbConnection@24b7edad
12:44:47.728 [HikariPool-1 connection adder] DEBUG MDC[] com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Added connection org.mariadb.jdbc.MariaDbConnection@20887de3
12:44:47.732 [HikariPool-1 connection adder] DEBUG MDC[] com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Added connection org.mariadb.jdbc.MariaDbConnection@658ae796
12:44:47.735 [HikariPool-1 connection adder] DEBUG MDC[] com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Added connection org.mariadb.jdbc.MariaDbConnection@4fe4b13a

12:47:47.692 [HikariPool-1 housekeeper] DEBUG MDC[] com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Pool stats (total=5, active=0, idle=5, waiting=0)
```
after ~10 minutes our db shows 0 connection but changing poolSize via JMX forces Hikari to regenerate connection and everything works.

we can work around this by setting min ```setMinimumIdle``` to poolSize - 1 and Hikari will recreate at least one connection every idleTimeout or we can change ```setMaxLifetime``` to get same behavior. 

Is there something we overlooked? I understand that Hikari is unaware of connection being closed by DB and thinks everything is all right. But if so, first request should fail but following request should use recreated connection.

**Comment by brettwooldridge** [comment]
I'm a bit confused by the log.  You said that *minimumIdle*=*maximumPoolSize* but the fact that there are "before" and "after" logs [indicates otherwise](https://github.com/brettwooldridge/HikariCP/blob/dev/src/main/java/com/zaxxer/hikari/pool/HikariPool.java#L694).  Can we get a clean log from startup to pool size reaching 0?  If the log is large, you can zip it and attach it here.  I would prefer an unedited log; you eliminate any non-HikariCP logs or you can configure a log appender to send HikariCP logs to a separate file.

**Comment by pawel-kaminski-krk** [comment]
so the confusion may come from the fact (which I ve already described) that we changed pool size on the fly via JMX - this helped to recreate valid connection without restarting app.

after this weekend (and reviewing all properties we put to configuration) we think it works as it should (but we expected some other behavior).

1. connections in pool may become invalid, as for example db closes connection on its side.
2. we had maxLifetTime = 30 min, idleTimeout = 10 min, db closed connection around 5 min.
2a. documentation says that idleTimeout is not used if minimumIdle = poolSize
3. with such big maxLifeTime and no incoming request, HCP was not able to detect that connections was invalid. Once request came in, HCP tried to validate connection, it took too long, and request was aborted on higher level and tests failed.

so what we did.
1. change mLT = 5 min and each 5 minutes connection that sit in pool will be invalidated and recreated.

what we expected is that, HCP is pinging db behind the scene using validation query and keeping all connection from pool alive - rater than killing and recreating connection. This way, mLT could be 30 min or more.

**Comment by brettwooldridge** [comment]
I actually guessed that the DB timeout was substantially shorter than the maxLifetime, but I didn't mention it because I was concerned about the pool not refilling after connections were detected as closed. :)

So, you are correct, the solution is to set maxLifetime equal to or less than the DB timeout.

HikariCP does not keep connections alive with background queries.  The reason is that we respect DBAs.  If the DBA sets a DB level timeout, we don't want to undermine that by artificially keeping connections alive. Of course you can bribe the DBA with beer if you feel your application needs longer timeouts.

But in general, a maxLifetime of 5 minutes will probably show no measurable difference in performance.  HikariCP injects random variation into the lifetimes, which over time will result in an even distribution of retirement -- avoid mass extinctions.

**Comment by pawel-kaminski-krk** [comment]
and how you decide whether connection is idle in order to kill it and recreate, once connection's max lifetime was reached? I didn't look into code but I guess it checks lifeTime once connection is returned to pool and then it is killed?

**Comment by pawel-kaminski-krk** [comment]
anyway thanks for fast reaction!

**Comment by brettwooldridge** [comment]
@pawel-kaminski-krk The ``maxLifetime`` and ``idleTimeout`` are handled differently.  But as noted, when ``minimumIdle=maxLifetime`` the idle timeout is not applied.

In the case of ``maxLifetime``, each connection has an independent associated timer task that will fire exactly at the designated time (+/- a few milliseconds).  If the connection is not in use when the timer task fires, the connection will be closed at that instant.  If the connection is currently in use when the timer fires, it will be marked for eviction and will be closed as soon as it is returned to the pool.

Idle connections are checked every 30 seconds by a house-keeping thread, and retired if they have been unused for a time exceeding the ``idleTimeout``.

**Comment by drenda** [comment]
Hi,
I'm facing the same problem after I switched from Tomcat pool to Hikari.

I've the classic message:

`SpringBootJPAHikariCP - Failed to validate connection org.mariadb.jdbc.MariaDbConnection@37fb7df7 (Connection.setNetworkTimeout cannot be called on a closed connection)`

I'm using MariaDb 10.2.14-MariaDB-10.2.14 on a Ubuntu Linux machine.

This is my pool configuration:

```
spring.datasource.hikari.minimumIdle=5
spring.datasource.hikari.maximumPoolSize=100
spring.datasource.hikari.idleTimeout=30000
spring.datasource.hikari.poolName=SpringBootJPAHikariCP
spring.datasource.hikari.maxLifetime=2000000
spring.datasource.hikari.data-source-properties.cachePrepStmts=true
spring.datasource.hikari.data-source-properties.prepStmtCacheSize=250
spring.datasource.hikari.data-source-properties.prepStmtCacheSqlLimit=2048
spring.datasource.hikari.data-source-properties.useServerPrepStmts=true
spring.datasource.hikari.data-source-properties.useLocalSessionState=true
spring.datasource.hikari.data-source-properties.useLocalTransactionState=true
spring.datasource.hikari.data-source-properties.rewriteBatchedStatements=true
spring.datasource.hikari.data-source-properties.cacheResultSetMetadata=true
spring.datasource.hikari.data-source-properties.cacheServerConfiguration=true
spring.datasource.hikari.data-source-properties.elideSetAutoCommits=true
spring.datasource.hikari.data-source-properties.maintainTimeStats=false
```
Do you have some advice? Thanks

**Comment by brettwooldridge** [comment]
@drenda My advise would be the same as above.  It seems likely that MariaDB is closing connections, for whatever reason, before the ``maxLifetime`` of 2000000ms (~33 minutes).  You can either figure out why MariaDB is doing that, possibly ``wait_timeout`` or other, or you can just shorten the ``maxLifetime`` until the warning goes away.

However, it would be useful to know exactly what the MariaDB threshold is for killing connections.  By knowing the specific value, you can appropriately set the ``maxLifetime`` to reduce unnecessarily early retirement of connections.

Unrelated, but I couldn't help notice the size of your pool.  Obviously, you know your application and I don't, but I would suggest reading [About Pool Sizing](https://github.com/brettwooldridge/HikariCP/wiki/About-Pool-Sizing) to make ensure you are getting maximum performance out of both HikariCP and MariaDB.

**Comment by drenda** [comment]
@brettwooldridge sorry to write here. I would like your opinion about the question I posted [here](https://stackoverflow.com/questions/52728639/connection-pooling-in-multi-tenant-app-shared-pool-vs-pool-per-tenant) that is related to the article  About Pool Sizing you mentioned. Thanks

**Comment by sanwancoder** [comment]
> Hi,
> I'm facing the same problem after I switched from Tomcat pool to Hikari.
> 
> I've the classic message:
> 
> ```
> 24/04/2018 18:16:28,083  WARN pool-3-thread-7 PoolBase: - SpringBootJPAHikariCP - Failed to validate connection org.mariadb.jdbc.MariaDbConnection@e938ea7 (Connection.setNetworkTimeout cannot be called on a closed connection)
> 24/04/2018 18:30:00,003  WARN pool-3-thread-7 PoolBase: - SpringBootJPAHikariCP - Failed to validate connection org.mariadb.jdbc.MariaDbConnection@2daa9777 (Connection.setNetworkTimeout cannot be called on a closed connection)
> 24/04/2018 18:30:00,015  WARN pool-3-thread-7 PoolBase: - SpringBootJPAHikariCP - Failed to validate connection org.mariadb.jdbc.MariaDbConnection@37fb7df7 (Connection.setNetworkTimeout cannot be called on a closed connection)
> ```
> 
> I'm using MariaDb 10.2.14-MariaDB-10.2.14 on a Ubuntu Linux machine.
> 
> This is my pool configuration:
> 
> ```
> spring.datasource.hikari.minimumIdle=5
> spring.datasource.hikari.maximumPoolSize=100
> spring.datasource.hikari.idleTimeout=30000
> spring.datasource.hikari.poolName=SpringBootJPAHikariCP
> spring.datasource.hikari.maxLifetime=2000000
> spring.datasource.hikari.data-source-properties.cachePrepStmts=true
> spring.datasource.hikari.data-source-properties.prepStmtCacheSize=250
> spring.datasource.hikari.data-source-properties.prepStmtCacheSqlLimit=2048
> spring.datasource.hikari.data-source-properties.useServerPrepStmts=true
> spring.datasource.hikari.data-source-properties.useLocalSessionState=true
> spring.datasource.hikari.data-source-properties.useLocalTransactionState=true
> spring.datasource.hikari.data-source-properties.rewriteBatchedStatements=true
> spring.datasource.hikari.data-source-properties.cacheResultSetMetadata=true
> spring.datasource.hikari.data-source-properties.cacheServerConfiguration=true
> spring.datasource.hikari.data-source-properties.elideSetAutoCommits=true
> spring.datasource.hikari.data-source-properties.maintainTimeStats=false
> ```
> 
> Do you have some advice? Thanks

thanks
