### ISSUE TITLE
Trying to achieve minimum idle connections leads to lock the database user.

### ISSUE THREAD

**Issue by sandeep27st** [brettwooldridge/HikariCP#857]
#### Environment
```
HikariCP version: 2.4.11
JDK version     : 1.7.0_25
Database        : Oracle
Driver version  : x.x.x
```
-----------------------------------------------------------------------------------------
Hello Brettwooldridge,

While using the HikariCP, it is observed that, to maintain the minimum idle connection in the pool, HikariCP continuously poll the database to create the connection. In case of wrong password continuous poll leads to lock the user account. To poll continuously is very good feature in case of incomplete configuration or booting of database is in-process. After complete the connection configuration or database has boot process completed connection automatically gets created.

In our implementation, we used to create multiple pools for different users. These pools will be created dynamically when there is a request for connection with different user( if pool is not available for requested user, if the pool already available for requested user then request can be served by available pool). 

In case if requested user enters the wrong password ( We can not identify user only by using username because user may enter wrong password and he/she could get the connection from available pool), different pool will be created for the wrong password user and that pool continuously poll database to create the connection with one pending request. Continuous poll locks the user account, if pool already exist for same user than there are chances of connection gets inconsistent in pool.

In case of initial fail-fast we can not predict fail-fast timeout upfront, pool might be lock the user account within that fail-fast timeout. 

Do you have any solution for this kind of situation? and Can you please mention the polling interval, after how long it will try to create connection?

Thanks...

**Comment by brettwooldridge** [comment]
The retry period is 1000ms.

The initializationFailTimeout is checked *after* a connection attempt.  The initializationFailTimeout does not limit the duration of the connection attempt itself, that is determined by the connectionTimeout.

 The default initializationFailTimeout of 1ms means that only one connection attempt will be made.  I'm pretty sure that is the behavior you are looking for.

**Comment by sandeep27st** [comment]
It will not help somehow, see poll continuously with incomplete configuration behavior will not help then. If user wanted to configure (initialFailFast) which check one attempt then can test the connection before creating pool.

Other than InitialFailFast do you have any work-around so that I can overcome this problem?

**Comment by brettwooldridge** [comment]
HikariCP has no way of knowing whether the configuration is correct or not.  As you said, the user is free to test the connection before creating the pool.  If there is a possibility that the configuration is incorrect or incomplete, I would recommend validating a connection attempt before creating the pool.

So, consider an existing functional pool for user "joe" (previous successful login).  Now, "joe" logs in again. You can create a temporary pool to validate his password. For example, a pool with maximumPoolSize=1, connectionTimeout=3000,  and initializationFailTimeout=1 (default). This should make 1 (possibly 2) attempt and then fail with an exception if the password is incorrect.  If it succeeds, the temporary pool can be destroyed.

**Comment by brettwooldridge** [comment]
Alternatively you can validate the connection before creating the pool.

**Comment by sandeep27st** [comment]
Thanks for your reply, we really appreciate your solution and we are doing the same, we'll test connection before creating connection pool. If connection test fails because of wrong credentials, then pool will not be created. To identify authentication failure reasons, we have created one XML which contains the error codes, if error codes matches with the failed reason, then we will not create the connection pool for the that pool configuration. 

Since we control this process only at the time of pool creation, but afterwards we have no control on this process. Let say, after pool gets created successfully and after sometime suddenly issue occurs like **network failure**/ **user's password expires**, **etc**. `getConnection()` api request waits until request timeout. The user will not get connection and not able to find out the reason. This process confuses the user, so user needs immediate response if something has gone wrong with the data source, user is fine with the reason if there are no connection available( if active connection equal to max connection) in the pool. But if no connection is active and still not getting connection, then there is no other way to see the log and not able to do anything until the connection request timeout over.

Is there any way to return request immediately, if any error happens with the connection creation other than active connection scenario?

**Comment by brettwooldridge** [comment]
The timeout exception contains a cause exception, which should be the exception thrown by the driver.  By inspecting the exception you should have enough information to take appropriate action.

**Comment by sandeep27st** [comment]
Is there any other getConnection API which will return back immediately, if anything wrong happen with the connection creation.
