### ISSUE TITLE
MBean server

### ISSUE THREAD

**Issue by LashaGureshidze** [brettwooldridge/HikariCP#858]
#### Environment
```
HikariCP version: 2.5.1
JDK version     : 1.8.0_111
Database        : ORacle
Driver version  : x.x.x
```
-----------------------------------------------------------------------------------------

Hello.
I have one issue about Mbeans.
I am using Spring+jpa+Hibernate 5 + HikariCP 2.51

My hikari configuration looks like this: 
```
hikariCP :
    pool_name : "name"
    pool_size : "10"
    register_Mbeans : "true"
```
 When I look at JMC Mbean, there activeConnectionsCount is always 0.
then I put Thread.sleep block into transaction(method, to busy connection). and call concurrently. There was error log messages : Connection is not available, request timed out after 30000ms. 

As I guess, this means that all connection from pool (all of 10) are busy. Then why MBean server shows that activeConnectionsCount is 0?

**Comment by brettwooldridge** [comment]
@LashaGureshidze I am unable to reproduce your problem.  I connected JMC to our server which is running HikariCP, then set the JMC polling interval to 1 second (1000ms), and I could see the ActiveConnections changing as I expected.

I've also added [an additional MBean test](https://github.com/brettwooldridge/HikariCP/blob/dev/src/test/java/com/zaxxer/hikari/pool/TestMBean.java#L53) which also validates that it is working properly.
