### ISSUE TITLE
Will the pool offer invalid connection to users and will it automatically reconnect?

### ISSUE THREAD

**Issue by gggllm** [brettwooldridge/HikariCP#859]
In my project I always receive a "Connection is not available, request timed out after" error,I'm not sure if it is because the pool offered me a invalid connection even after the check. And I am also not sure what the pool will do with an invalid connection

**Comment by brettwooldridge** [comment]
@gggllm The *"Connection is not available, request timed out after..."* error indicates that the pool is at maximum capacity, and all connections are in-use, at the time that a thread called ``getConnection()``.  Not only that, it indicates that the thread waited in ``getConnection()`` for the ``connectionTimeout`` period, hoping that a connection would be returned to the pool, but no connection became available.

 It does not indicate that HikariCP offered you an invalid connection; that should be nearly impossible for HikariCP to do.

There are two common conditions that are responsible for that error:

One is a connection leak.  In that case, connections are being borrowed but never returned.  Eventually the pool will run out of connections and your application will be stuck forever.  I recommend enabling the ``leakDetectionThreshold`` and setting it to 2x the value of ``connectionTimeout``.  If you see leak warnings in your log, it should provide a stacktrace pointing to the source of the leak.

The other common cause of that error is simply long-running queries -- queries that execute for longer than the ``connectionTimeout`` period.  In that case, it is possible to have all connections occupied with such queries, preventing a new thread from acquiring a connection from the pool before ``connectionTimeout`` is reached.

**Comment by gggllm** [comment]
Thank you very much！

**Comment by brettwooldridge** [comment]
@gggllm You're welcome.
