### ISSUE TITLE
Connection.getMetaData() causes Hikari to return dirty connections

### ISSUE THREAD

**Issue by cowwoc** [brettwooldridge/HikariCP#866]
#### Environment
```
HikariCP version: 2.6.1
JDK version     : 1.8.0_121
Database        : PostgreSQL 9.5.5
Driver version  : 42.0.0.jre7
```
-----------------------------------------------------------------------------------------

`ProxyConnection.markCommitStateDirty()` is not getting invoked when `Connection.getMetaData()` methods are invoked. As a result, dirty connections (in mid-transaction) are being handed over to unrelated threads and causing runtime failures.

Repro steps:

1. Get a connection from the pool. Set `autoCommit` to false and invoke `Connection.getMetaData().getTables(null, "PUBLIC", "%", null)`. Under the hood, this fires the following SQL query:
```
SELECT NULL AS TABLE_CAT, n.nspname AS TABLE_SCHEM, c.relname AS TABLE_NAME,  CASE n.nspname ~ '^pg_' OR n.nspname = 'information_schema'  WHEN true THEN CASE  WHEN n.nspname = 'pg_catalog' OR n.nspname = 'information_schema' THEN CASE c.relkind   WHEN 'r' THEN 'SYSTEM TABLE'   WHEN 'v' THEN 'SYSTEM VIEW'   WHEN 'i' THEN 'SYSTEM INDEX'   ELSE NULL   END  WHEN n.nspname = 'pg_toast' THEN CASE c.relkind   WHEN 'r' THEN 'SYSTEM TOAST TABLE'   WHEN 'i' THEN 'SYSTEM TOAST INDEX'   ELSE NULL   END  ELSE CASE c.relkind   WHEN 'r' THEN 'TEMPORARY TABLE'   WHEN 'i' THEN 'TEMPORARY INDEX'   WHEN 'S' THEN 'TEMPORARY SEQUENCE'   WHEN 'v' THEN 'TEMPORARY VIEW'   ELSE NULL   END  END  WHEN false THEN CASE c.relkind  WHEN 'r' THEN 'TABLE'  WHEN 'i' THEN 'INDEX'  WHEN 'S' THEN 'SEQUENCE'  WHEN 'v' THEN 'VIEW'  WHEN 'c' THEN 'TYPE'  WHEN 'f' THEN 'FOREIGN TABLE'  WHEN 'm' THEN 'MATERIALIZED VIEW'  ELSE NULL  END  ELSE NULL  END  AS TABLE_TYPE, d.description AS REMARKS  FROM pg_catalog.pg_namespace n, pg_catalog.pg_class c  LEFT JOIN pg_catalog.pg_description d ON (c.oid = d.objoid AND d.objsubid = 0)  LEFT JOIN pg_catalog.pg_class dc ON (d.classoid=dc.oid AND dc.relname='pg_class')  LEFT JOIN pg_catalog.pg_namespace dn ON (dn.oid=dc.relnamespace AND dn.nspname='pg_catalog')  WHERE c.relnamespace = n.oid  AND n.nspname LIKE 'PUBLIC' AND c.relname LIKE '%' ORDER BY TABLE_TYPE,TABLE_SCHEM,TABLE_NAME 
```

2. Close the connection and notice that when `ProxyConnection.close()` runs `isCommitStateDirty` evaluates to `false`.
3. Request a connection from the pool. You should get the connection returned by step 2.
4. Invoke `Connection.setReadOnly(true)` on it.
5. You will get an exception:
```
org.postgresql.util.PSQLException: Cannot change transaction read-only property in the middle of a transaction.
	at org.postgresql.jdbc.PgConnection.setReadOnly(PgConnection.java:691)
```

Expected behavior: queries fired by `Connection.getMetaData()` should mark the connection as dirty.

**Comment by tomAndJetty** [comment]
i have got a problem that rollback was called when only use Connection.getMetaData and "select..." SQL  due to this commit.
as query operation, why did getMetaData need to set markCommitStateDirty true?
can you commit previous transaction manually before you call setReadOnly

**Comment by cowwoc** [comment]
@tomAndJetty As far as I'm aware, nothing in the JDBC specification implies that one must commit a connection prior to invoking `getMetaData()`. The only time an exception is expected is when the underlying connection is closed or a database error occurs. Neither of these cases apply here.

It would probably help if you elaborated on the problem you are seeing.
