### ISSUE TITLE
Artifact for Java 9 too.

### ISSUE THREAD

**Issue by aadrian** [brettwooldridge/HikariCP#868]
Please add an artifact (release) for Java 9 too.

Thank you.

**Comment by brettwooldridge** [comment]
@aadrian The ``dev`` branch builds under Java 9 now.  I'll work on a early access release this week.

**Comment by brettwooldridge** [comment]
@aadrian Done.

**Comment by aadrian** [comment]
@brettwooldridge Thank you !
