### ISSUE TITLE
Connections more than maximumPoolSize created

### ISSUE THREAD

**Issue by sanaulla123** [brettwooldridge/HikariCP#869]
#### Environment
```
HikariCP version: 2.4.11
JDK version     : openjdk version "1.8.0_121"
Database        : Oracle
Driver version  : 11.2
```
-----------------------------------------------------------------------------------------

We have the following properties configured for HikariCP
```
spring.datasource.hikari.maximumPoolSize 5
spring.datasource.hikari.minimumIdle 4

```
But we see that there are more than 5 i.e around 12 connections established to the DB. 

We are running RHEL 7 which uses `chrony` to sync with NTP time
```
Reference ID    : 51.211.170.41 (51.211.170.41)
Stratum         : 2
Ref time (UTC)  : Mon Apr 17 06:09:18 2017
System time     : 0.000036245 seconds slow of NTP time
Last offset     : -0.000049425 seconds
RMS offset      : 0.001551040 seconds
Frequency       : 9.721 ppm slow
Residual freq   : -0.003 ppm
Skew            : 0.705 ppm
Root delay      : 0.006208 seconds
Root dispersion : 0.005149 seconds
Update interval : 778.9 seconds
Leap status     : Normal

```

But the same application with the same configuration on RHEL 6 works fine i.e it doesn't create more than 5 connections. 

One of the log messages seen:
`WARN 8852 --- [HikariPool-1 housekeeper] com.zaxxer.hikari.pool.HikariPool        : HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=15m59s115ms143?s997ns).`

Also gets hung at: `HikariPool-1 - Close initiated...` when we stop the spring boot service

**Comment by brettwooldridge** [comment]
@sanaulla123 It is hard to tell exactly what is happening, but I can take a guess.  For some reason, Connection.close() is taking an inordinate (unexpectedly) long time.

The housekeeper thread closes idle connections.  It generally uses an executor to close Connections asynchronously, but the size of the executor queue is equal to the maximumPoolSize.  This means that after that queue fills up, the executor will run new requests on the caller thread -- in this case the housekeeper.

The clock leap reported by the housekeeper indicates that 5 close requests were already in the queue, and so the housekeeper thread itself was used -- *and it took +15 minutes to close that single connection*.

The hang at shutdown also indicates that close is taking an excessively long time.

Why is it taking so long?  I have no idea.  You might try enabling debug logging to see if it reveals anything, but honestly I don't expect it will.  I'm not sure how to troubleshoot the issue other than something like tcpdump/wireshark.

**Comment by sanaulla123** [comment]
I guess the hang during the shutdown is related to the number of SQL connections established by CP. As I mentioned in my original issue - the number of connections created are crossing the maximumPoolSize. So due to this few other connections are being closed in the housekeeper thread. 

The last two paragraphs of the issue were just for providing more information. My original issue is: "But we see that there are more than 5 i.e around 12 connections established to the DB."

And I have seen the same library running in the same app on RHEL 6 using JDK 7 has so far created only 4 connections which is our minimumIdle. But the same application on RHEL 7 using JDK 8 created around 13 connections.

**Comment by brettwooldridge** [comment]
@sanaulla123 As soon as a ``Connection`` is enters into the close connection phase, it is removed from the pool immediately -- but still has an active connection to the DB until ``Connection.close()`` completes.  So, if Connections are taking minutes to close, you could have (in theory):

 * 5 connections in the close queue (but not yet closed)
 * 5 live connections in the pool (immediately replacing those in the close queue)
 * 1 connection still alive but being closed by the housekeeper
 * ... and in theory up to 5 more being close by user threads if evictions are occurring due to 08xxx SQLState exceptions.

**Comment by eluchsinger** [comment]
As of today, I am having the problem that I get more open connections than the allowed maximum. My PostgreSQL Database has got by default 100 connections available and Hikari's `maximumPoolSize=10`. Soon I run out of DB-connections. My statistics show that the limit of 100 connections was reached and I get the following exception:

```
[error] Caused by: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: FATAL: tut mir leid, schon zu viele Verbindungen
[error]   Ort: Datei: proc.c, Routine: InitProcess, Zeile: 340.
[error]   Server SQLState: 53300
[error]     at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:512)
[error]     at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:105)
[error]     at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:71)
[error]     at play.api.db.HikariCPConnectionPool$$anonfun$1.apply(HikariCPModule.scala:58)
[error]     at play.api.db.HikariCPConnectionPool$$anonfun$1.apply(HikariCPModule.scala:54)
[error]     at scala.util.Try$.apply(Try.scala:192)
[error]     at play.api.db.HikariCPConnectionPool.create(HikariCPModule.scala:54)
[error]     ... 83 more
```

I think this might be related. I am pretty sure, I release all connections when I finish using them. They are being handled by the Play Framework.

**Comment by brettwooldridge** [comment]
@eluchsinger It looks like the pool is being recreated and destroyed frequently.  I feel like I've seen this somewhere before with Play.  I recommend enabling debug logging.  You might also try asking on stackoverflow.
