### ISSUE TITLE
HikariCP not releasing connections on close() - Question?

### ISSUE THREAD

**Issue by itsvisher** [brettwooldridge/HikariCP#870]
#### Environment
```
HikariCP version: 2.6.1
JDK version     : 1.8.0_121
Database        : PostgreSQL 9.6.2
Driver          : pgjdbc-ng
Driver version  : 0.7.1
```
-----------------------------------------------------------------------------------------
Hi,

I am doing a Web Socket programming where I need to get instant update from DB insert and pass it to web socket. Therefore using the above JDBC driver for PostgreSQL.

I chose to use HikariCP for connection pooling. Something seems to be wrong. Calling close() to connection doesn't release the connection. The pool seems to quickly fill up and get stuck after that.

Here is some code to give an idea:

Singleton Connection Code:

```
import java.io.PrintWriter;
import java.sql.SQLException;
import java.util.Properties;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.impossibl.postgres.api.jdbc.PGConnection;
import com.zaxxer.hikari.HikariConfig;
import com.zaxxer.hikari.HikariDataSource;
import com.zaxxer.hikari.pool.HikariProxyConnection;

public class DBConnection {
	public PGConnection pgConnection;
	private static HikariDataSource ds;
	private static Logger logger = LoggerFactory.getLogger(DBConnection.class);

	private static HikariDataSource getDatasource(String database) {
		if (ds == null || ds.isClosed()) {
			Properties props = new Properties();
			props.setProperty("dataSourceClassName", "com.impossibl.postgres.jdbc.PGDataSource");
			props.setProperty("dataSource.user", "username");
			props.setProperty("dataSource.password", "password");
			props.setProperty("dataSource.database", database);
			props.setProperty("dataSource.port", "5432");
			props.setProperty("dataSource.host", "localhost");
			props.setProperty("maximumPoolSize", "100");
			props.setProperty("minimumIdle", "20");
			props.setProperty("maxLifetime", "30000");
			props.put("dataSource.logWriter", new PrintWriter(System.out));

			HikariConfig config = new HikariConfig(props);
			ds = new HikariDataSource(config);
		}

		return ds;
	}

	public PGConnection getConnection(String database) throws Exception {
		ds = getDatasource(database);
		HikariProxyConnection connection = (HikariProxyConnection) ds.getConnection();
		if (connection.isWrapperFor(PGConnection.class)) {
			pgConnection = connection.unwrap(PGConnection.class);
		}

		return pgConnection;
	}

	public static void closeDataSource() {
		logger.debug("Trying to close datasource.");
		ds.close();
	}

	public void closeConnection() {
		try {
			logger.debug("Trying to close connection.");
			if (pgConnection != null) {
				ds.evictConnection(pgConnection);
				pgConnection.close();
				pgConnection = null;
				logger.debug("DB Connection closed.");
			} else {
				logger.error("Connection attempted to close was null");
			}
		} catch (SQLException sqle) {
			logger.error("Error closing connection...");
			sqle.printStackTrace(new PrintWriter(System.out));
		}
	}
}
```

And here is how I am using it in my Web Socket code:

```
@ServerEndpoint("/getdata/{client-id}")
public class WebSocket {
	private static Set<Session> sessions = java.util.Collections.synchronizedSet(new HashSet<Session>());
	private static Map<Session, String> clientIds = new ConcurrentHashMap<Session, String>();
	private Session currentSession;
	private PGConnection pgConnection;
	private static DBConnection dbConnection;

	@OnMessage
	public synchronized void onMessage(String message, @PathParam("client-id") String clientId) {
		String output = "";
		try {
			do {
				pgConnection = dbConnection.getConnection("cdp");
				//perform some db query
				Thread.sleep(250);
			} while (output != null && output.length() > 4);
			clientIds.put(currentSession, clientId);
		} catch (Exception e) {
			e.printStackTrace(new PrintWriter(System.out));
		}
	}

	@OnOpen
	public synchronized void onOpen(Session session) {
		sessions.add(session);
		this.currentSession = session;
		session.setMaxIdleTimeout(720000);
		if (dbConnection == null) {
			dbConnection = new DBConnection();
		}
	}

	@OnClose
	public synchronized void onClose(Session session) {
		try {
			if (currentSession.isOpen()) {
				sessions.remove(currentSession);
				currentSession.close();
				if (dbConnection != null) {
					dbConnection.closeConnection();
				}
			} else {
				if (dbConnection != null) {
					dbConnection.closeConnection();
				}
			}
		} catch (Exception e) {
			e.printStackTrace(new PrintWriter(System.out));
		}
	}

	@OnError
	public synchronized void onError(Session session, Throwable e) {
		if (currentSession.isOpen()) {
			try {
				currentSession.close();
				if (dbConnection != null) {
					dbConnection.closeConnection();
				}
			} catch (Exception e1) {
				if (dbConnection != null) {
					dbConnection.closeConnection();
				}

				e1.printStackTrace(new PrintWriter(System.out));
			}
		}
	}
}
```

I understand that this is not a platform to raise these type of questions, and there can seems to be something wrong about my code as well, but just want to understand, that the HikariCP keeps on adding connections when idle < 20, but never releases active connections. Result of which is total = active connections with idle and waiting = 0.

And then the server stops taking multiple connections. Connections are never closed on close() call and this is making me crazy!!

**Comment by jnehlmeier** [comment]
You are unwrapping the connection returned by HikariCP which gives your the raw `PGConnection`. When you close this raw `PGConnection` then HikariCP can not detect it and its internal data structure will still consider the connection as active. Thus at some point HikariCP will not give you any new connection anymore. 

You must call `close()` on the connection instance that HikariCP gives you. Also as a side note: `ds.evictConnection(pgConnection);` will do nothing as you do not pass in a connection instance that has been returned by `ds.getConnection()`. You should never work with the specific, underlying JDBC connection directly because you by-pass the connection pool logic that way.

Finally if your code does not use a custom `ServerEndpoint` `Configurator` then your implementation has quite some other issues as well. Most notably the `synchronized` keyword pretty much does nothing as it locks on the instance but the [websocket 1.1 spec](http://download.oracle.com/otndocs/jcp/websocket-1_1-mrel-eval-spec/index.html) says that a new instance of your `WebSocket` class will be created for each client that connects to your server (the behavior of the default `Configurator`). If each client talks to its own `WebSocket` instance then parallel calls to `DBConnection` and its API will happen which will cause quite some trouble in your code.

**Comment by itsvisher** [comment]
@jnehlmeier Thanks for the insights. Knew there was something wrong about my code. Never thought of the unwrapped connection object not to be identified by HikariCP.

Will work on this, and surely get back over here to update.

**Comment by brettwooldridge** [comment]
@jnehlmeier Thanks, Jens.  You have no idea how helpful it is when you jump in on issues.

**Comment by itsvisher** [comment]
@jnehlmeier @brettwooldridge It worked. Thanks a lot.
