### ISSUE TITLE
Connection Leaks from SQL Failover

### ISSUE THREAD

**Issue by abroederdorf** [brettwooldridge/HikariCP#871]
#### Environment
```
HikariCP version: 2.6.1
JDK version     : 1.8.0_121
Database        : SQL Server
Driver version  : JDBC 6.0
Scalalikejdbc   : 2.5.1
```

#### HikariCP Configuration
```
Max Pool Size  : 10
Leak Detection Threshold  : 10000
Connection Timeout  : 5000
Max Lifetime   : 1800000
```
-----------------------------------------------------------------------------------------

We’re having a connection leak issue during failover. During failover some number of connections will break, with the log showing ```marked as broken because of SQLSTATE(08S01)```. These connections are closed and new connections are added, so that’s good. However, the remaining connections eventually trigger a leak detection with the following trace: 

```
[0m[[0minfo[0m] [0m09:55:43.116 [db housekeeper] [31mWARN [0;39m [36mcom.zaxxer.hikari.pool.ProxyLeakTask[0;39m - Connection leak detection triggered for ConnectionID:7 ClientConnectionId: bb481e93, stack trace follows[0m
[0m[[0minfo[0m] [0mjava.lang.Exception: Apparent connection leak detected[0m
[0m[[0minfo[0m] [0m	at com.example.database.HikariCPConnectionPool.borrow(HikariCP.scala:44)[0m
```

This appears to be pointing to the borrow function in HikariCP. Any ideas on how to fix this? I did one test where I set the max lifetime to 3 minutes. After a failover, none of the connections that triggered the leak detection were ever closed. There were other connections that were added and then closed due to the max lifetime threshold, so that doesn’t appear to be helping in our situation.

Thanks for the help!

**Comment by brettwooldridge** [comment]
The stacktrace points to the scala method (borrow) where HikariDataSource.getConnection() was called. There are two possibilities.  One is that the scala code actually leaked the Connection, i.e. has never called close and never will.  The other is that there are threads stuck in SQL on those Connections awaiting a TCP timeout.

A simple thread dump should tell you which one it is.

If a "leaked" connection is ever returned to the pool, you will see an "unleaked" log entry.
