### ISSUE TITLE
Documentation - IdleTimeout specifies maximumPoolSize not maxLifetime

### ISSUE THREAD

**Issue by Techcadia** [brettwooldridge/HikariCP#872]
In the Documentation for ⌚idleTimeout it states

> This setting only applies when `minimumIdle` is defined to be less than `maximumPoolSize`

But I think you mean
> This setting only applies when `minimumIdle` is defined to be less than `maxLifetime`

Based on this code
https://github.com/brettwooldridge/HikariCP/blob/dev/src/main/java/com/zaxxer/hikari/HikariConfig.java#L880-L883

**Comment by brettwooldridge** [comment]
@Techcadia LOL, well thanks for reading the code.  😁 However, that log message is orthogonal to the behavior in question.  The rubber meets the road [here](https://github.com/brettwooldridge/HikariCP/blob/dev/src/main/java/com/zaxxer/hikari/pool/HikariPool.java#L693) -- i.e. the second part of the conditional.
