### ISSUE TITLE
HikariCP Pool makes Logback's insertFromJNDI configuration stop working

### ISSUE THREAD

**Issue by betler** [brettwooldridge/HikariCP#873]
#### Environment
```
HikariCP version: 2.6.1
JDK version     : 1.8.0_121
Database        : SQL Server 2014
Driver version  : com.microsoft.sqlserver.jdbc.SQLServerDataSource / sqljdbc42-6.0.jar
Server version: Apache Tomcat/8.0.38
```
-----------------------------------------------------------------------------------------

I have two `Spring MVC` applications that share a commons.jar library. This library includes Logback logging library (logback 1.2.3 and slf4j 1.7.25) and the logback.xml file.

Both wars include this line in their _web.xml_ file:

    <env-entry>
        <env-entry-name>applicationName</env-entry-name>
        <env-entry-type>java.lang.String</env-entry-type>
        <env-entry-value>nameOfApplicationA|nameOfApplicationB</env-entry-value>
    </env-entry>

Each application generates its own log file including hostname, for example: "HOST1-nameOfApplicationA.log". Logback configuration is as follows:

    <insertFromJNDI env-entry-name="java:comp/env/applicationName" as="APP_NAME" />
    <appender name="ROLLING_FILE" class="ch.qos.logback.core.rolling.RollingFileAppender">
        <file>${LOG_PATH}/${HOSTNAME}-${APP_NAME}.log</file>
         ...
     </appender>

Everything was working OK (Spring MVC 4.3.7.RELEASE, Hibernate 4.x, C3P0 latest), but we decided to upgrade to Hibernate 5.2.10 and change to HikariCP 2.6.1. After that, logback was no longer able to resolve "java:comp/env/applicationName":

    ERROR in ch.qos.logback.classic.joran.action.InsertFromJNDIAction - [java:comp/env/applicationName] has null or empty value

Resulting in both applications using the same file name "HOST1-APP_NAME_IS_UNDEFINED.log".

As we changed at the same time Hibernate and HikariCP we went back to C3P0 to check the root cause, and can confirm that the new version of Hibernate has nothing to do. The change was developed in its own branch so no other change seems to affect (anyway, when returning to C3P0 it works).

I've been doing some tracing in Hikari's and Logback's code but I'm not able to see anything. I'm stuck, no idea about what to look at.

Plan B is inserting in each war its own logback.xml but I would like to avoid it and understand the problem as it may affect other parts of the application.

Both wars are deployed together in an Apache Tomcat/8.0.38 server. Tried also 8.5.12. It also happens if only one of the wars is deployed alone.

Hikari is configured via _context.xml_ file as follows:

    <Resource name="jdbc/postulantesDS" auth="Container" 
        factory="com.zaxxer.hikari.HikariJNDIFactory"
        type="javax.sql.DataSource" 
        dataSourceClassName="com.microsoft.sqlserver.jdbc.SQLServerDataSource"
        dataSource.user="xxx" dataSource.password="yyy"
        dataSource.url="jdbc:sqlserver://1.1.1.1:1433;databaseName=xxx;"
        cacheMetaData="true"
        poolName="appAPool"
        autoCommit="false"
        connectionTimeout="10000" idleTimeout="120000" maxLifetime="1800000"
        minimumIdle="2" maximumPoolSize="4"
        connectionInitSql="SELECT * FROM TEST_TABLE"
        transactionIsolation="TRANSACTION_READ_UNCOMMITTED"
    />

**Comment by brettwooldridge** [comment]
@betler Thanks for opening the issue here.  Unfortunately, as I said in my last comment on stackoverflow:

>The more I look at this, the more certain I am that it has nothing to do with HikariCP. HikariCP has nothing to do with JNDI. The important factor here is that HikariCP depends on slf4j and C3P0 does not. Which points to a similar, if not identical, cause as the issue mentioned in my previous comment. You need to grep all of the jars involved for "slf4j" -- Spring's jars, Tomcat's jars, third-party jars, your jars. The slf4j classes need to exist in exactly one of those jars, no more. If they are in more then one jar, you need to sort our your classpath. 

Even with one WAR deployed, there are still lots of possibilities for problems.  For example, if there is a ``slf4j`` jar in the Tomcat/lib folder, as well as one in the WAR.  Or if there is are two jars (either in the tomcat/lib or in the WAR) that have shaded versions of ``slf4j`` that would be a problem.

I don't know if you are on Windows or Linux/MacOS, but on Linux/MacOS you should be able to run this command from the tomcat base directory to find all jars containing slf4j classes:
```
find . -name "*.jar" -type f -exec grep -l slf4j {} \;
```

**Comment by betler** [comment]
Executed in a Tomcat with all applications deployed:

    ./webapps/appC/WEB-INF/lib/logback-classic-1.1.7.jar
    ./webapps/appC/WEB-INF/lib/jcl-over-slf4j-1.7.21.jar
    ./webapps/appC/WEB-INF/lib/log4j-over-slf4j-1.7.21.jar
    ./webapps/appC/WEB-INF/lib/jul-to-slf4j-1.7.21.jar
    ./webapps/appC/WEB-INF/lib/slf4j-api-1.7.21.jar
    
    ./webapps/appB/WEB-INF/lib/jul-to-slf4j-1.7.21.jar
    ./webapps/appB/WEB-INF/lib/log4j-over-slf4j-1.7.21.jar
    ./webapps/appB/WEB-INF/lib/slf4j-api-1.7.21.jar
    ./webapps/appB/WEB-INF/lib/jcl-over-slf4j-1.7.21.jar
    ./webapps/appB/WEB-INF/lib/logback-classic-1.1.7.jar
    
    ./webapps/ROOT/WEB-INF/lib/jcl-over-slf4j-1.7.21.jar
    ./webapps/ROOT/WEB-INF/lib/slf4j-api-1.7.21.jar
    ./webapps/ROOT/WEB-INF/lib/jul-to-slf4j-1.7.21.jar
    ./webapps/ROOT/WEB-INF/lib/log4j-over-slf4j-1.7.21.jar
    ./webapps/ROOT/WEB-INF/lib/logback-classic-1.1.7.jar
    
    ./webapps/static/WEB-INF/lib/slf4j-api-1.7.21.jar
    ./webapps/static/WEB-INF/lib/logback-classic-1.1.7.jar


_appC_ is another application that shares the same jar, but it is not deployed during development.

**Comment by brettwooldridge** [comment]
@betler Where is the aforementioned ``commons.jar``?  You said *"This library includes Logback logging library (logback 1.2.3 and slf4j 1.7.25) and the logback.xml file."*  If that is the case, and ``commons.jar`` co-exists with the jars above, you're going to have an problem.

**Comment by betler** [comment]
Wrongly explained from my part. Logback dependency is in the war and logback configuration file is in common.jar. After extracting contents of commons jar:

    # find . -name "*.xml" -type f -exec grep -l log {} \;
    ./META-INF/maven/com.xxx.yyy/CommonLibs/pom.xml
    ./logback.xml

    # find . -name "*.jar" -type f -exec grep -l slf4j {} \;
    -- No results

**Comment by brettwooldridge** [comment]
@betler In the case of the extracted jar, the ``find . -name "*.xml" -type f -exec grep -l log {} \;`` is fine, but I would like to see the output of ``find . -name "*slf*.class" -type f``.  Meaning, what slf4j classes are in that jar?

**Comment by brettwooldridge** [comment]
@betler If you run your *original* application (Spring MVC 4.3.7.RELEASE, Hibernate 4.x) and swap in the HikariCP pool, what happens?  You've got too many variables changing to draw any conclusions at this point.

**Comment by brettwooldridge** [comment]
@betler I am wondering whether the classloading order is different when HikariCP is used vs. C3P0?

For example, because HikariCP depends on ``slf4j``, and HikariCP is *also* being initialized and registered into JNDI, is that causing ``logback`` to initialize *before* the ``<env-entry>`` entries have registered?  If that were the case ``insertFromJNDI`` would not be able to resolve the application name at ``logback`` instantiation time.

What happens if you move the ``<env-entry>`` from *web.xml* into the same *context.xml* as the HikariCP ``<resource>`` declaration ... ***before*** the HikariCP ``<resource>`` declaration ... like this?
```
<Context>
  <Environment
     name="applicationName" 
     value="nameOfApplicationA|nameOfApplicationB"
     type="java.lang.String"
     override="false" />

  <Resource name="jdbc/postulantesDS" auth="Container"
     ...
</Context>
```

**Comment by betler** [comment]
Good shot. Must be something like that. I changed _context.xml_ file's _factory_ and _type_ variables to:

    factory="org.apache.naming.factory.BeanFactory"
    type="com.zaxxer.hikari.HikariDataSource"

Application does not start (the rest of the resource must be changed as variables are no longer the same), but the logs are correctly created. Even with _applicationName_ env value in the web.xml file.

I guess this is not related to HikariCP but to the class loading order. We will evaluate the trades of changing to _org.apache.naming.factory.BeanFactory_ and decide wether we maintain that or we move logback.xml file to each of the wars.

Thank you very much for your help.

**Comment by jnehlmeier** [comment]
Hm at work we do it a little different and maybe it is also an option for you if I read that you share a single logback.xml file between war projects.

Basically we configured jetty (I am pretty sure the same can be done with Tomcat) to use SLF4J + logback itself and also publish SLF4J API to any deployed war. That way our projects just depend on SLF4J API with provided scope so it does not end up in WEB-INF/lib. We have a single logback.xml file for Jetty which creates all the different log files by looking at MDC values of SLF4J. These values are filled by each app using a common servlet filter (It can use system properties, servlet information like the deployed context path as app name, session id, anything you might have stored in the session like the logged in user account, cookies, ... ). Depending on the MDC values you can also create a log file covering multiple deployed war files in case your users might switch between these apps.

Works pretty well for us.
