### ISSUE TITLE
HikariCP has been closed occured when change the properties

### ISSUE THREAD

**Issue by calmking** [brettwooldridge/HikariCP#877]
#### Environment
```
HikariCP version: 2.5.1
JDK version     : 1.8.0_111
Database        :MySQL
Driver version  : mysql-connector-java.jar 5.1.40
```
-----------------------------------------------------------------------------------------

Hi,
when i write code like : 
`hikariDataSource.setJdbcUrl(dataSourceInfo.connUrl);
            hikariDataSource.setUsername(dataSourceInfo.userName);
            hikariDataSource.setPassword(dataSourceInfo.password);
`
then i use jdbcTemplate todo some sql 
the  exception -"HikariCP has been closed" occured 
how can i fix it ? 

error like 

`org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get
JDBC Connection; nested exception is java.sql.SQLException:
HikariDataSource HikariDataSource (HikariPool-7) has been closed.
   at
org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:80)
   at
org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:394)
   at
org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:474)
   at
org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:484)
   at
org.springframework.jdbc.core.JdbcTemplate.queryForObject(JdbcTemplate.java:494)
   at
org.springframework.jdbc.core.JdbcTemplate.queryForMap(JdbcTemplate.java:489)
   at
com.shhxzq.arch.data.encrypt.offline.job.sourcejob.SourceTableJob.initSelectSql(SourceTableJob.java:100)
   at
com.shhxzq.arch.data.encrypt.offline.job.sourcejob.SourceTableJob.<init>(SourceTableJob.java:74)
   at
com.shhxzq.arch.data.encrypt.offline.job.JobServer.loadJob(JobServer.java:95)
   at
com.shhxzq.arch.data.encrypt.offline.job.JobServer.run(JobServer.java:192)
   at java.lang.Thread.run(Thread.java:745)
Caused by: java.sql.SQLException: HikariDataSource HikariDataSource
(HikariPool-7) has been closed.
   at
com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:79)
   at
org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:111)
   at
org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:77)
   ... 10 more`

**Comment by brettwooldridge** [comment]
Something about your spring configuration is destroying/closing the pool.  You might try to enable DEBUG logging for the package ``com.zaxxer.hikari`` to see if it provides more diagnostic information.  Other than that, I recommend asking on the Spring forums or stackoverflow.com.

**Comment by calmking** [comment]
Thanks ,I will check the debug logging.

**Comment by prithvirajv** [comment]
Any solution? i am facing the same issue
