### ISSUE TITLE
Support for Driver classes present in Thread Context Class Loader

### ISSUE THREAD

**Issue by udayshnk** [brettwooldridge/HikariCP#878]
#### Environment
```

Getting "Failed to load class of driverClassName {}" when hikari jar is present in parent classloader(tomcat shared lib) and the driver class is present in Thread context class loader(individual webapps) when the pool is initialized.

Looks like the problem is in setDriverClassName of HikariConfig, it is expecting the driver class to be present in the same classloader from which hikari classes are loaded.


HikariCP version: x.x.x
```
-----------------------------------------------------------------------------------------

**Comment by brettwooldridge** [comment]
@udayshnk Looks like it should try the thread context classloader in the catch block.  Can to give me a pull request?

**Comment by udayshnk** [comment]
@brettwooldridge unfortunately my machine doesn't have java8 installed to work on dev branch. We were using 2.4.x release in our project.

**Comment by brettwooldridge** [comment]
@udayshnk Sorry about that, we usually build the Java 7 artifact with Java 8 (using a 1.7 compilation target).  I just pushed a change to the 2.4.x branch to build on Java 7.

**Comment by brettwooldridge** [comment]
Fixed.

**Comment by udayshnk** [comment]
@brettwooldridge sorry i am bit new to github environment. I cannot find the commit in 2.4.x branch, are there any review comments or is the commit fine for you. 

Also if the commit is merged into 2.4.x branch, i think it can be cherry picked to dev branch as well and when could i expect the next 2.4.x public release.

**Comment by brettwooldridge** [comment]
@udayshnk [This is the commit](https://github.com/udayshnk/HikariCP/commit/66a826ca7e3de00be9bf563cd8f357479acf7cd4) (also linked above).  I'll try to cut a release in the next few days.

**Comment by udayshnk** [comment]
Hi @brettwooldridge could you please cut the 2.4.12 release

**Comment by brettwooldridge** [comment]
@udayshnk Ok.  It is 5:00am now here in Tokyo, so I'm going to bed, but I will do so sometime tomorrow.

**Comment by udayshnk** [comment]
Hi @brettwooldridge request you to please cut the 2.4.12 release. Sorry for the inconvenience caused we are in need of the fix in our setup

**Comment by brettwooldridge** [comment]
Oh wait, I don't know why this was closed.  Your code was never merged.  [I have a number of comments on your pull request](https://github.com/brettwooldridge/HikariCP/pull/881) that were never addressed.  If you correct those issue, then squash the commits into a single commit, I can merge the change and release a 2.4.12 build.

**Comment by udayshnk** [comment]
Hi @brettwooldridge, i don't see any review comments can you please help me. Here is the screenshot of what i see in the pull request
![image](https://cloud.githubusercontent.com/assets/1115428/26444778/66aef09c-415b-11e7-9486-c3828b999d78.png)

**Comment by brettwooldridge** [comment]
Did you follow the linked text in my comment?  Comments are on the pull request.

**Comment by shakuzen** [comment]
For what it's worth, I also see no comments on the pull request linked above (#881). It's the only open pull request with no comments, according to the [pull request tab](https://github.com/brettwooldridge/HikariCP/pulls).

**Comment by udayshnk** [comment]
@brettwooldridge i did follow the link, i don't see any comments

**Comment by brettwooldridge** [comment]
@udayshnk You must be signed into github to see comments:

![github](https://cloud.githubusercontent.com/assets/1538661/26490927/558329ee-4248-11e7-999a-27e3ceda0d55.png)

**Comment by brettwooldridge** [comment]
@udayshnk Try it now.  The review comments were not "submitted".

**Comment by udayshnk** [comment]
Thanks @brettwooldridge, i am able to see the comments now, will fix them and send you the updated patch

**Comment by udayshnk** [comment]
Hi @brettwooldridge when can we expect 2.4.12 release. Also pushed the commit to dev branch too,it can be merged if needed

**Comment by brettwooldridge** [comment]
@udayshnk HikariCP v2.4.12 has been released.

**Comment by udayshnk** [comment]
Thanks a lot @brettwooldridge, was eagerly waiting for this release
