### ISSUE TITLE
Update Password at Runtime via MBeans

### ISSUE THREAD

**Issue by joelk111** [brettwooldridge/HikariCP#879]
We have the need to update the password for our Hikari pool at runtime via MBeans.  The code we have developed does not show any error upon execution, however, it does not change the password. Two questions:

1. Does Hikari support the changing of passwords in a pool that is spring bean configured like the below?

2. If the code provided is not the correct approach, can you please post a sample of how this is to be done?

The original config via spring looks like this:

   <spring:beans>
              <spring:bean id="hikariConfig" class="com.zaxxer.hikari.HikariConfig">
                     <spring:property name="jdbcUrl"value="jdbc:as400://${host}" />
                     <spring:property name="username" value= "${username}"/>       
                     <spring:property name="password" value="${password}" /><
                     <spring:property name="connectionTestQuery" value="SELECT test from test" />
                     <spring:property name="autoCommit" value="${autocommit}" />
                     <spring:property name="readOnly" value="${readonly}" />
                     <spring:property name="maximumPoolSize" value="${maxpool}" />
                     <spring:property name="maxLifetime" value="${maxlifetime}" />
                     <spring:property name="isolateInternalQueries" value="${isolateinternalqueries}" />
                     <spring:property name="transactionIsolation" value="${transactionisolation}" />
                     <spring:property name="initializationFailFast" value="${initializationFailFast}"/>
                     <spring:property name="idleTimeout" value="${idletimeout}" />
                      <spring:property name="LeakDetectionThreshold" value="2000" />
                      <spring:property name="registerMbeans" value= "true" />
      				<spring:property name="minimumIdle" value="${minimumidle}" />
              </spring:bean>
              <spring:bean id="hikaridataSource" class="com.zaxxer.hikari.HikariDataSource">
                     <spring:constructor-arg ref="hikariConfig" />
              </spring:bean>
       </spring:beans

The methods used to change the password at runtime are based on: https://github.com/fwi/fwutil-jdbc/blob/f95cf7d7921aefae6e9216102645bbe34dd745f5/src/main/java/nl/fw/util/jdbc/hikari/HikariPoolJmx.java and include:

	public HikariPoolJmx(final String poolName) {
		this.poolName = poolName;
		try {
			mBeanServer = ManagementFactory.getPlatformMBeanServer();
			poolAccessor = new ObjectName("com.zaxxer.hikari:type=Pool (" + poolName + ")");
			poolConfigAccessor = new ObjectName("com.zaxxer.hikari:type=PoolConfig (" + poolName + ")");
		} catch (MalformedObjectNameException e) {
			throw new RuntimeException("Pool " + poolName + " could not be found", e);
		}
	}

	@Override
	public void setPassword(String password) {
		setConfigString("Password", password);
	}

	protected void setConfigString(String attributeName, String value) {
		try {
			mBeanServer.setAttribute(poolConfigAccessor, new Attribute(attributeName, value));
		} catch (RuntimeException e) {
			throw e;
		} catch (Exception e) {
			throw new RuntimeException(e);
		}
	}

	@Override
	public void setPassword(String password) {
		setConfigString("Password", password);
	}

And the following code calls this method that is based on: 

		HikariPoolJmx jmx = new HikariPoolJmx("HikariPool-1");
		jmx.setMinimumIdle(0);
		jmx.setPassword("test");
		jmx.softEvictConnections();

The softEvictConnections  method works and we can see the results in DEBUG, however, the change password does not.

#### Environment
```
HikariCP version: 2.4.5
JDK version     : 1.8.0_111
Database        : DB2|Oracle
Driver version  : x.x.x
```
-----------------------------------------------------------------------------------------

**Comment by brettwooldridge** [comment]
@joelk111 In general, HikariCP tries to protect itself from configuration modifications after pool start, except for those exposed through the MBean interface.

You can however hack around it under certain circumstances.  The HikariDataSource constructor that takes a ``HikariConfig`` clones the configuration, and therefore it cannot be modified after the fact.

However, if you construct the HikariDataSource directly and perform configuration against it, it should work (though unsupported officially).

To do that, get rid of the HikariConfig spring configuration, and move the ``<spring:property>`` markup into the ``<spring:bean id="hikaridataSource" ...>`` configuration.  If you do that, the ``HikariPoolJmx`` helper class should probably work.
