### ISSUE TITLE
Can't understand "connection leaks"

### ISSUE THREAD

**Issue by mikebell90** [brettwooldridge/HikariCP#883]
#### Environment
```
HikariCP version: 2.6.1
JDK version     : (build 1.8.0_121-b13
Database        : 5.1.138
Driver version  : x.x.x
```
-----------------------------------------------------------------------------------------

So I deployed a test build to staging here, switching our connection pool from an old grody horrible home grown implementation.

The connections immediately PEGGED the MySQL server, and stayed pegged (according to AWS metrics) for two days until we turned it off. It grew to 2000 connections split among about 10 servers. (max = 200 apiece)

Now, initially things were pretty much "default" - here is the code building the pool

```java
private static ConnectionPool buildModernPool(String server, int port, String user, String pass, String database, int maxCons, String label) {
            String url = "jdbc:mysql://"+server+":"+port;
            if (!StringUtils.isNull(database)) {
                url += "/"+ database;
            }
            url += "?useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&zeroDateTimeBehavior=convertToNull";
            try {
                Class.forName("com.mysql.jdbc.Driver").newInstance();
            } catch (Exception e) {
                throw new SQLRuntimeException(e);
            }
            HikariConfig config = new HikariConfig();
            // DB Server not checked at pool creation, failure isn't fatal to pool
            config.setInitializationFailTimeout(-1);
            config.setJdbcUrl(url);
            config.setUsername(user);
            config.setPassword(pass);
            config.setPoolName(label);
            config.setRegisterMbeans(true);
            config.setMaximumPoolSize(maxCons);
            if (Props.getBoolProperty("connection.pool.leak.detect")) {
                logger.info("Leak detection enabled");
                config.setLeakDetectionThreshold(LEAK_DETECTION);
            }
      
            config.addDataSourceProperty("cachePrepStmts", "true");           
            config.addDataSourceProperty("prepStmtCacheSize", "250");
            config.addDataSourceProperty("prepStmtCacheSqlLimit", "2048");
            config.addDataSourceProperty("useServerPrepStmts","true");
            return new HikariConnectionPool(config,label);
````

Note the idle, lifetime were default.

A simple test locally with maxCons=60 and basically grabbing connections and immediately dropping them confirmed the following

- In at least a few minutes time waiting, the connections remained pegged at 60
- They went away when the test was ended.
- adding maxLifeTime = 30000L made no difference, at least over the next few minutes.
- removing maxLifeTime, but adding idleTimeout = 30000L, and minimimIdle =3 . DID groom the connections down to 3.

Why did Staging act like it did? Keep in mind this was literally about 36 hours, and the connections stayed pegged at the MysSQL's maximum limit.

**Comment by billoneil** [comment]
Did you have leak detection enabled? Also did you turn on logging? The logging is pretty clear when connections are created and closed.

**Comment by mikebell90** [comment]
Remember I can run this locally in a simple JUNIT where I try (Connection c = datasource.getConnection()) {
stuff
}

So while your suggestion is good, reasonable, etc, it is probably not relevant.
Note no major "spike" was noticed in other environments (we have INT and TST before STG). But those recycle a lot.

**Comment by mikebell90** [comment]
oh and locally I have log4j.xml set to TRACE. I did notice it was insisting with maxTimeout that it was returning them. But it wasn't as SHOW Threads_Connected, proved.

**Comment by mikebell90** [comment]
`
 @Test
    public void reallySimple() throws Exception {
        int max = 30;
        String server = "127.0.0.1";
        int port = 3306;
        String database  = "clearslide";

        String url = "jdbc:mysql://"+server+":"+port;
        if (!StringUtils.isNull(database)) {
            url += "/"+ database;
        }
        url += "?useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&zeroDateTimeBehavior=convertToNull";
        try {
            Class.forName("com.mysql.jdbc.Driver").newInstance();
        } catch (Exception e) {
            throw new SQLRuntimeException(e);
        }
        HikariConfig config = new HikariConfig();
        config.setInitializationFailTimeout(-1);
        config.setJdbcUrl(url);
        config.setUsername("clearslide");
        config.setPassword("clearslide");
        config.setPoolName("pool");
        config.setRegisterMbeans(true);
        config.setMaximumPoolSize(max);

        //   config.setIdleTimeout(10000L);
        // config.setMinimumIdle(3);
        // config.setMaxLifetime(30000L);
        config.addDataSourceProperty("cachePrepStmts", "true");
        config.addDataSourceProperty("prepStmtCacheSize", "250");
        config.addDataSourceProperty("prepStmtCacheSqlLimit", "2048");
        config.addDataSourceProperty("useServerPrepStmts","true");

        HikariDataSource hikariDataSource = new HikariDataSource(config);

        for (int i = 0; i < max; i++) {
            try (Connection c = hikariDataSource.getConnection()) {
                try {
                    Thread.sleep(200L);
                } catch (Exception e ) {
                    //
                }
            }
        }

        while(true) {
            int active = hikariDataSource.getHikariPoolMXBean().getActiveConnections();
            int total = hikariDataSource.getHikariPoolMXBean().getTotalConnections();
            int idle = hikariDataSource.getHikariPoolMXBean().getIdleConnections();
            System.err.println("idle/active/total " + idle + "/" + active + "/" + total );
            try {
                Thread.sleep(2000L);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }


    }
`

**Comment by mikebell90** [comment]
When I enable maxLifeTime = 30000L, it says

2017-05-03 17:02:51 DEBUG PoolBase:134 - pool - Closing connection com.mysql.jdbc.JDBC4Connection@1ac29293: (connection has passed maxLifetime)
2017-05-03 17:02:51 DEBUG PoolBase:134 - pool - Closing connection com.mysql.jdbc.JDBC4Connection@1ac29293: (connection has passed maxLifetime)
2017-05-03 17:02:51 DEBUG HikariPool:634 - pool - Added connection com.mysql.jdbc.JDBC4Connection@bf46d91
2017-05-03 17:02:51 DEBUG HikariPool:634 - pool - Added connection com.mysql.jdbc.JDBC4Connection@bf46d91

So as soon as it drops, it  readds

**Comment by billoneil** [comment]
If you do not set a `minimumIdle` it defaults to max pool size.

**Comment by billoneil** [comment]
Yes `200` is probably too high. Tell them to look at this https://github.com/brettwooldridge/HikariCP/wiki/About-Pool-Sizing. It really depends what the queries are doing though.

**Comment by mikebell90** [comment]
Bill - yes - you'll see when I set idleTimeout I also set minimumIdle

**Comment by billoneil** [comment]
Right so how is that an ugly kludge? I'm not sure what you are trying to do here.

**Comment by mikebell90** [comment]
So it's an ugly kludge because you cannot guarantee the sawtooth BEFORE the idleTimeout won't cause all the servers to go kablooey

It seems like the best answer is a 
- conservative idleTimeout/minIdleConnections - maybe 10min/10% of max
- reduce max greatly because it is probably this max * number of servers that is unhappy

**Comment by billoneil** [comment]
I would say 200 seems too high but it does depend on the queries. If you have long running queries sometimes you need more connections in the pool. In this case its often good to create multiple pools, one for short lived transactional queries with a very small pool size and a slightly larger one for longer running queries. This would probably require some rearchitecting of the code though.

You could keep a lower minIdle and I would bet its still much more performant than your in house solution was.

**Comment by brettwooldridge** [comment]
@Mikebell90 By default HikariCP acts as a fixed size pool, unless *minimumIdle* is set.  Regarding pool sizes, everybody thinks they need a larger pool than they do, but an oversized pool can really degrade throughput.  I recommend reading [this](https://github.com/brettwooldridge/HikariCP/wiki/About-Pool-Sizing).

Having said that, if you really feel like you must have a "large" pool, I would recommend trying: *maximumPoolSize=40*, *minimumIdle=5*, *idleTimeout=30000*.  Everything else at default.

With *minimumIdle=5* the pool will attempt to keep 5 free connections on-deck.  If the pool has 5 connections and one is borrowed, leaving 4, the pool will add one to get back to 5.  If the pool becomes idle, that connection will be retired.  The overhead is negligible, as MySQL is capable of establishing and retiring hundreds of connections per second -- two orders of magnitude greater than the pool will demand.

Lastly, I see you have a lot of properties in the URL.  I recommend moving those to *dataSource.xxx* style properties for maintain ability.

**Comment by mikebell90** [comment]
Thanks, we'll try this
