### ISSUE TITLE
JDBC4Connection didn't being garbage collected.

### ISSUE THREAD

**Issue by JasonHuangHuster** [brettwooldridge/HikariCP#884]
#### Environment
```
HikariCP version: java6-2.3.9 
JDK version     : 1.7 32bit
Database        : MySql
Driver version  : mysql-connector-java-5.1.31
```
-----------------------------------------------------------------------------------------
I use HikariCP as datasource of my java server , i wanna check how many db connections used by my java process , so i've dump the heap and checked the number of PoolBagEntry which is the same as what i get by running linux `netstat` command . but i found the number of JDBC4Connection instance is not equivalent to PoolBagEntry . there are hundreds of JDBC4Connection instance , most of them  have no `GC Root` ( jvisualvm showed this ) . so apparently , those instance hasn't being Garbage Collected . I use `jmap -dump:live,format=b,file=path pid ` to dump the heap , the `live` option means there's will be a FULL GC operation before the thread is being dumped . i read the code of close a connection , i think there must be something wrong with it , but i don't have any further clue . 

`

   /**
    * Permanently close the real (underlying) connection (eat any exception).
    *
    * @param connectionProxy the connection to actually close
    */
   @Override
   protected void closeConnection(final PoolBagEntry bagEntry, final String closureReason)
   {
      bagEntry.cancelMaxLifeTermination();
      if (connectionBag.remove(bagEntry)) {
         final int tc = totalConnections.decrementAndGet();
         if (tc < 0) {
            LOGGER.warn("Internal accounting inconsistency, totalConnections={}", tc, new Exception());
         }
         final Connection connection = bagEntry.connection;
         closeConnectionExecutor.execute(new Runnable() {
            public void run() {
               poolUtils.quietlyCloseConnection(connection, closureReason);
            }
         });
      }
      bagEntry.connection = null;
   }
`
may be there's a latency and won't trigger a Memory Leak , but i'm curious about the strategy used here .  : )

**Comment by brettwooldridge** [comment]
@JasonHuangHuster If there is no path to GC root, the objects will be collected eventually.  The only thing I can think of is that HikariCP uses thread local storage, so the number of unreferenced (by Java) objects that are still retained can maximally equal the number of live threads.  If you want to force the thread local object into weak references (to speed up collection), you can set [an undocumented System property](https://github.com/brettwooldridge/HikariCP/blob/dev/src/main/java/com/zaxxer/hikari/util/ConcurrentBag.java#L385).
