### ISSUE TITLE
Connection / Query time out?

### ISSUE THREAD

**Issue by L4BORG** [brettwooldridge/HikariCP#885]
#### Environment
```
HikariCP version: 2.6.1
JDK version     : 1.8.0_111
Database        : MariaDB
Driver version  : mariadb-java-client/1.1.7
```
-----------------------------------------------------------------------------------------

Is it possible to set query time out and connection time out?

a. I would like to set maximum time allowed for query to return result/finish (and ignore result/cancel if the query didn't get executed for some reason).

b. how can I set connection time out? We're using remote mariadb server (different dedicated server in the same datacenter) however every now and then there could be some downtime (1 or 2 minutes in case of upgrades/updates/...) the problem is I can't seem to find a way to set max time allowed for MariaDB server to respond (and fail and try to reconnect if timelimit is not meet).

**Comment by chryschabs** [comment]
Also facing the same issue, as of today it seems that there is no way of setting query specific timeouts, how does one go about this ?

**Comment by brettwooldridge** [comment]
@chryschabs See the new wiki page about [Rapid Recovery](https://github.com/brettwooldridge/HikariCP/wiki/Rapid-Recovery).  In addition, you'll want to look at the HikariCP ``connectionTimeout`` and ``maxLifetime`` properties.

**Comment by chryschabs** [comment]
Hi, thank you for the reply, `connectionTimeout` is not what we're looking for. Will try `maxLifetime`, what jdbc driver property does it map to ? `socketTimeout` (i don't see it in the link you pasted).

**Comment by brettwooldridge** [comment]
@chryschabs The word ``socketTimeout`` occurs three times on the [Rapid Recovery page](https://github.com/brettwooldridge/HikariCP/wiki/Rapid-Recovery).   The ``socketTimeout`` property of MySQL/MariaDB (and PostgreSQL, actually), relates to the underlying TCP timeout for socket operations.

The ``maxLifetime`` property is a HikariCP property and does not "map" to any specific JDBC driver property.  However, in the case of MySQL/MariaDB, it roughly "maps" to the database ``wait_timeout`` setting, and should be set (in HikariCP) to several seconds shorter than the database ``wait_timeout``.

Keep in mind that all HikariCP timeouts are denoted in *milliseconds*, while MySQL/MariaDB timeouts (e.g. ``wait_timeout``) are denoted in *seconds*.
