### ISSUE TITLE
Document HikariConfig.copyState(HikariConfig other)

### ISSUE THREAD

**Issue by cowwoc** [brettwooldridge/HikariCP#892]
#### Environment
```
HikariCP version: 2.6.1
```
-----------------------------------------------------------------------------------------

Please add Javadoc to `HikariConfig.copyState(HikariConfig other)`. I keep on mistakenly thinking the method means "copy the state of `other` (into `this`)" when in fact it does the opposite: it copies `this` into `other`.

Renaming the method to `copyStateTo` or `copyStateInto` would also help.

**Comment by brettwooldridge** [comment]
@cowwoc Just cleaning up old issues.  I'm leaving this one open for now.  Pull requests welcome.
