### ISSUE TITLE
JNDI prepStmtCache + can't register mbean

### ISSUE THREAD

**Issue by 7fantasy7** [brettwooldridge/HikariCP#895]
#### Environment
```
HikariCP version: 2.6.0
JDK version     : 1.8.0_111
Database        :  MySQL 5.6
Driver version  : 5.1.38
```
-----------------------------------------------------------------------------------------
I found an example using ds object, but do these properties work in JNDI configuration?
ds.addDataSourceProperty("prepStmtCacheSize", 250);
ds.addDataSourceProperty("prepStmtCacheSqlLimit", 2048);
ds.addDataSourceProperty("useServerPrepStmts", true);

And also I can't register MBean
18-May-2017 02:25:37.269 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.listenerStart Exception sending context initialized event to listener instance of class com.epam.heroes.rest.util.ApplicationListener
 org.springframework.jmx.export.UnableToRegisterMBeanException: Unable to register MBean [HikariDataSource (MyDataSource)] with key 'dataSource'; nested exception is javax.management.InstanceAlreadyExistsException: MXBean already registered with name com.zaxxer.hikari:type=PoolConfig (MyDataSource)
at org.springframework.jmx.export.MBeanExporter.registerBeanNameOrInstance(MBeanExporter.java:625)
at org.springframework.jmx.export.MBeanExporter.registerBeans(MBeanExporter.java:550)
at org.springframework.jmx.export.MBeanExporter.afterSingletonsInstantiated(MBeanExporter.java:432)

When I remove "registerMBeans=true" property from JNDI config,
I'm still getting MBean with statistics for dataSource.

Tried to setExcludedBeans and change registrationPolicy on MBeanExporter, but it didn't help.

**Comment by brettwooldridge** [comment]
[Here are some JNDI examples.](https://github.com/brettwooldridge/HikariCP/wiki/JNDI-DataSource-Factory-(Tomcat,-etc.))

Regarding the JMX name conflict, this implies that you have two pools in the same JVM with the same "poolName" configured.  Either configure two different names, or leave the *poolName* property unset, in which case HikariCP will auto-number them.

**Comment by 7fantasy7** [comment]
I gave JNDI resources different names, but it didn't help.

**Comment by brettwooldridge** [comment]
http://stackoverflow.com/questions/28607506/disabling-jmx-in-a-spring-application

**Comment by 7fantasy7** [comment]
Finally, I found the problem.
There was @EnableMBeanExport annotation which exported PoolConfig bean for the first time,
and registerMbeans="true" option did it once again.

But, another question is:
How can I set up prepared statements pool within JNDI xml config?
