### ISSUE TITLE
Pool failed finishing starting: Aurora(mysql) + MariaDB JDBC Connector + HikariCP

### ISSUE THREAD

**Issue by duxing** [brettwooldridge/HikariCP#898]
#### Environment
```
HikariCP version: 2.6.1
JDK version     : 1.8.0_125
Database        : MySQL
Driver        :org.mariadb.jdbc.Driver
Driver version  : 2.0.1
```
-----------------------------------------------------------------------------------------

Running into this weird issue while using HikariCP with mariadb connector to Aurora.
Usage attached here:
`String driver = "org.mariadb.jdbc.Driver";`
`String jdbcUrl = "jdbc:mysql://aurora-cluster-end-point:3306";`
`Class.forName(driver);`
`HikariConfig  config = new HikariConfig();`
`config.setDriverClassName(driver);`
`config.setJdbcUrl(jdbcUrl);`
`config.setUsername(user);`
`config.setPassword(password);`
`config.setConnectionTimeout(30000);`
`config.setMaximumPoolSize(20);`
`config.setAutoCommit(false);`
`config.addDataSourceProperty("cachePrepStmts", true);`
`config.addDataSourceProperty("prepStmtCacheSize", 250);`
`config.addDataSourceProperty("prepStmtCacheSqlLimit", 2048);`
`datasource = new HikariDataSource(config);`

Nothing went wrong when I specified driver to be `"com.mysql.jdbc.Driver"` but as soon as I switch the driver, connection pool failed starting.

Got this log while I'm using `"com.mysql.jdbc.Driver"`:
`thread="main" log="INFO" class="c.z.h.HikariDataSource" HikariPool-5 - Starting...`
`thread="main" log="INFO" class="c.z.h.HikariDataSource" HikariPool-5 - Start completed.`

But when using mariadb connector, the process is stuck after printing out the "Starting" log. i.e. seeing this line only:
`thread="main" log="INFO" class="c.z.h.HikariDataSource" HikariPool-5 - Starting...`

**Note**: I've got normal mysql servers and Aurora servers. Regardless of which one is used as jdbc URL, HikariDataSource fails starting as long as I use mariadb driver.

Does anyone know how I get use HikariCP with mariadb connector?

**Comment by brettwooldridge** [comment]
Try taking out the cachePrepStmts and other MySQL driver specific properties.

**Comment by duxing** [comment]
hi Brett,

I've gone through HikariCP source code and did more testing and I don't think this is an issue with HikariCP (switching to a different cp lib also surfaced the same issue)

I'll move this to mariadb driver issue tracker instead. Thanks for helping out and sorry to bother you

**Comment by duxing** [comment]
Confirmed this is an issue with MariaDB driver. More specifically, version 1.6.0 / 2.0.0 or above
1.5.9 works fine with this set up in case anyone is trying the same thing

**Comment by jstultz** [comment]
@duxing would you mind providing a link to that issue? I think I am encountering this problem when upgrading past 1.5.9, and would greatly appreciate it.

**Comment by duxing** [comment]
@jstultz 
https://jira.mariadb.org/browse/CONJ-477
https://jira.mariadb.org/browse/CONJ-484

took me a while to dig these up. I hope it helps

**Comment by jstultz** [comment]
@duxing yes, very much, thank you!
