### ISSUE TITLE
Performance drop with BoneCP -> HikariCP

### ISSUE THREAD

**Issue by duxing** [brettwooldridge/HikariCP#900]
#### Environment
```
HikariCP version: 2.6.1
BoneCP version: 0.8.0-RELEASE
JDK version     : 1.8.0_121
Database        : MySQL
Driver version  : 5.1.4
```
-----------------------------------------------------------------------------------------

Hi all,

I did a CP lib upgrade recently for my servers from BoneCP to HikariCP for the purpose of maintainability and performance. The integration is fairly straightforward. After going through all the configurations and fixing the issues on my side, I was finally able to test the change with production traffic.

Surprisingly I noticed a slight performance drop for all the db queries on my server. Compare 2 servers with 2 different CP libs integrated, I'm seeing an almost constant 1ms delay per query, regardless of the type of the query (update, select, etc)

The servers I used for this experiment are on the same AWS AZ with the same instance type. They have minor difference in ping delay for accessing the db servers, and the 2 lib are using similar configurations.
I'm getting 2 connections per host for boneCP (with 1 partition and 5 max connection) and 5 connections per host for HikariCP (with 5 as pool max connection), both have auto commit turned on.

According to this article:
https://github.com/brettwooldridge/HikariCP/wiki/Pool-Analysis

The perf difference is probably caused by testing connection when getting one. I did not specify a test connection query so it's using isValid to test connection. 

I understand they way BoneCP gets connection is trading off reliability for performance, and I was wondering if there is a flag / way in HikariCP that I can use to disable the connection testing. 

Thanks in advance!

**Comment by brettwooldridge** [comment]
> I'm getting 2 connections per host for boneCP (with 1 partition and 5 max connection) and 5 connections per host for HikariCP (with 5 as pool max connection), both have auto commit turned on.

HikariCP operates as a fixed size pool by default.  If you want dynamic sizing, similar to BoneCP, you need to set ``minimumIdle=2``.

> The servers I used for this experiment are on the same AWS AZ with the same instance type. They have minor difference in ping delay for accessing the db servers, and the 2 lib are using similar configurations.

What is the difference in ping times?

> I understand they way BoneCP gets connection is trading off reliability for performance, and I was wondering if there is a flag / way in HikariCP that I can use to disable the connection testing.

I would say that is a Bad Idea<sup>tm</sup> because you will be vulnerable to lengthy delays if a network partition even happens (where the server is unable to reach the database).  By default, if it has been more than 500ms since a connection was used, HikariCP will test it.  This is called the *bypass* window, because the check will be bypassed for connections used more actively.

If you wish to increase the bypass window, causing HikariCP to validate connections less frequently, there is an undocumented system property, ``com.zaxxer.hikari.aliveBypassWindowMs`` (again 500ms by default), that you can set to a higher number.  I would not recommend a bypass window larger than 5000ms (5 seconds).  If a network partition even occurs in the 5 seconds between when a connection is returned and when it is borrowed again, your application may hang due to unacknowledged TCP packets.  BoneCP is vulnerable to this at all times.

**Comment by duxing** [comment]
> HikariCP operates as a fixed size pool by default. If you want dynamic sizing, similar to BoneCP, you need to set minimumIdle=2
Did this test yesterday to isolate the change and getting the same result. 5 connections per host vs 2 connections per host (both using HikariCP) did not result in any noticeable perf difference.

> What is the difference in ping times?
the difference in ping time to the tested db servers are on the order of 0.1ms
I also did a same server test with 2 different versions of server jar: one with BoneCP and the other with HikariCP. The test was done in 2 days at the same hour of the day to ensure the traffic is roughly the same. And still seeing the same result.

Thanks for the advice on "aliveBypassWindowMs". I've got a chance to test that flag this morning, overriding it to 5s instead of 500ms. The perf metric did not improve (same compared other instances using HikariCP but default aliveBypassWindowMs)

The perf difference is likely caused by something else but I'm out of clues at this point. 
Any suggestions on how I can tweak the configuration?

My current configuration:
maxLifetime=250s (300s on my mysql server side)
idleTime=150s
maxConnection=5
connectionTimeout=30s
cachePrepStmts=true
prepStmtCacheSize=250
prepStmtCacheSqlLimit=2048

everything else is using default value

**Comment by brettwooldridge** [comment]
@duxing A couple of suggestions.  Use the *driver* not the MySqlDataSource.  Some other settings have a pretty major impact on performance as well for HikariCP (I clearly need to update my MySQL tips page).  Even when using the driver, you still use the ``dataSource.`` properties format:
 ```
jdbcUrl=jdbc:mysql://<host>/<database>
dataSource.user=<user>
dataSource.password=<password>

dataSource.cachePrepStmts=true
dataSource.prepStmtCacheSize=250
dataSource.prepStmtCacheSqlLimit=2048

# important new properties
dataSource.useServerPrepStmts=true
dataSource.useLocalSessionState=true
dataSource.useLocalTransactionState=true
dataSource.rewriteBatchedStatements=true

# other performance improvements
dataSource. cacheResultSetMetadata=true
dataSource.cacheServerConfiguration=true
dataSource. elideSetAutoCommits=true
dataSource.maintainTimeStats=false
```
