### ISSUE TITLE
Connection not closed in class CodahaleHealthChecker.ConnectivityHealthCheck

### ISSUE THREAD

**Issue by udayshnk** [brettwooldridge/HikariCP#901]
It looks like that the connection fetched during health check is not closed

Below is the current implementation of check method 

@Override
      protected Result check() throws Exception
      {
         try (Connection connection = pool.getConnection(checkTimeoutMs)) {
            return Result.healthy();
         }
         catch (SQLException e) {
            return Result.unhealthy(e);
         }
      }

#### Environment
```
HikariCP version: 2.4.11
JDK version     : 1.7
```
-----------------------------------------------------------------------------------------

**Comment by shakuzen** [comment]
This is covered by [Java's try-with-resources](https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html).

**Comment by udayshnk** [comment]
Thanks @shakuzen, missed the trick

**Comment by brettwooldridge** [comment]
😁
