### ISSUE TITLE
Connection Issue

### ISSUE THREAD

**Issue by satrox28** [brettwooldridge/HikariCP#909]
#### Environment
```
HikariCP version: HikariCP-java7-2.4.11.jar
JDK version     : 1.7.0_80
Database        : PostgreSQL 9.5.2
Driver version  : postgresql-42.1.1.jre7.jar
```
-----------------------------------------------------------------------------------------
We are running our application on 2core,7.5Gb RAM, below are our HikariCP config.
For rest of the configuration will it use default values??.

Parameters:-
hikari.dataSourceClassName=org.postgresql.ds.PGSimpleDataSource
hikari.maximumPoolSize=4

We are getting the below error, do we need to change any settings. Please suggest.

Application error:
java.sql.SQLTransientConnectionException: springHikariCP - Connection is not available, request timed out after 30000ms.

 java.sql.SQLException: springHikariCP - Interrupted during connection acquisition

 - com.ibatis.common.jdbc.exception.NestedSQLException:
--- The error occurred in ibatis/oauth.xml.
--- The error occurred while executing mapped statement.
--- Check the insertNonceUsed.
--- Check the statement or the result map.
--- Cause: java.sql.SQLException: HikariDataSource HikariDataSource (springHikariCP) has been closed.

**Comment by zhan2016** [comment]
Have you solved  this problem?I'm in trouble, too.

**Comment by brettwooldridge** [comment]
Looks like a Spring configuration issue.  The DataSource is being destroyed while in use. Maybe post your configuration on stackoverflow.

**Comment by zhan2016** [comment]
ok,thank you!
