### ISSUE TITLE
NPE closing connection after forced eviction

### ISSUE THREAD

**Issue by dconnelly** [brettwooldridge/HikariCP#914]
#### Environment
```
HikariCP version: 2.6.2
JDK version     : 1.8.0_111
Database        : MySQL (Aurora)
Driver version  : 5.1.41
```
-----------------------------------------------------------------------------------------
We recently added some code to handle recovery following Aurora failover. Aurora failover is handled by a DNS change to the cluster address, and when this occurs existing pooled connections will suddenly be pointing to the read-only replica and will have to be evicted from the pool. Our recovery code is to detect the specific SQL error code associated with this event, evict the connection from the pool, then restart the transaction. Unfortunately, after evicting the connection we get an NPE when subsequently trying to close the connection (actually, the JDBI handle wrapping the connection):
```
Exception in thread "main" java.lang.NullPointerException
	at com.zaxxer.hikari.pool.PoolBase.resetConnectionState(PoolBase.java:219)
	at com.zaxxer.hikari.pool.PoolEntry.resetConnectionState(PoolEntry.java:102)
	at com.zaxxer.hikari.pool.ProxyConnection.close(ProxyConnection.java:240)
	at org.skife.jdbi.v2.BasicHandle.close(BasicHandle.java:128)
       ...
```
Looks like evictConnection already closes the underlying JDBC connection in pooled connection, but ProxyConnection.close() doesn't check for that case.

I can certainly skip closing the DBI handle / connection but I'm worried that this will bypass other cleanup tasks associated with closing the connection (cached prepared statements etc).

On the other hand, if I close the connection first then "soft" evict the connection another thread might just end up immediately grabbing the stale connection again and recovery will be incomplete.

What is the best way to handle close following eviction?

Thanks,
- David

**Comment by brettwooldridge** [comment]
A couple of things.  If you evict a connection then close() should not be called.  Nothing will be leaked, as the actual connection is closed, forcing it to cleanup its resources.

Having said that, HikariCP should be detecting the original SQLException, and acting accordingly, without the need for you to manually evict the connection.  What is the SQLstate and errorcode in the original exception?

**Comment by mkozioro** [comment]
Hi.

I'm also getting a "Failed to update database "xxx" because the database is read-only." but when using failover on Azure SQL database.

Here is full stacktrace:
Caused by: org.springframework.jdbc.UncategorizedSQLException: PreparedStatementCallback; uncategorized SQLException for SQL [INSERT INTO batches (uuid, status, apikey_hash, creation_date, last_update_date) VALUES (?, ?, ?, ?, ?)]; SQL state [S0002]; error code [3906]; Failed to update database "batch" because the database is read-only.; nested exception is com.microsoft.sqlserver.jdbc.SQLServerException: Failed to update database "batch" because the database is read-only.
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:84)
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
        at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:649)
        at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:870)
        at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:931)
        at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:941)

Restarting app helps immediately. Without that I need to wait ~ connection maxLifetime.

My environment:
HikariCP version: 2.6.2
JDK version     : 1.8.0_131
Database        : Azure SQL (SQL Server 2014)
Driver version  : 6.1.7.jre8-preview (https://github.com/Microsoft/mssql-jdbc/tree/v6.1.7)

**Comment by brettwooldridge** [comment]
This looks like and Azure configuration issue.

https://docs.microsoft.com/en-us/azure/sql-database/sql-database-designing-cloud-solutions-for-disaster-recovery

https://docs.microsoft.com/en-us/azure/sql-database/sql-database-geo-replication-overview

The replication policy may be set incorrectly.  I am not that familiar with Azure, but the documentation seems to recommend manual failover that coordinates the application and database.

**Comment by mkozioro** [comment]
We're using failover groups and manual failover, so we don't need to change hostname to second region. Only problem is when we are testing failover when both primary and replica are healthy and responding. 

Primary server becomes replica and replica becomes primary server, dns entries are automatically updated. Old primary server becomes read only and new one is read write. But from what I see, old connections are usually not dropped, so we are getting "database is read-only." error until db connection is renewed. Probably similar thing is happening with AWS MySQL (Aurora).

**Comment by dconnelly** [comment]
@brettwooldridge 

Sorry for the late reply...

Aurora returns ```Error: 1290 SQLSTATE: HY000 (ER_OPTION_PREVENTS_STATEMENT)``` after failover indicating that the connection is now pointing to the read-only replica and should be evicted. Not sure if this is true for RDS failover in general, but it's definitely what Aurora is returning (shame that Amazon does not document this). It'd be great if Hikari could evict automatically but I'm not sure this error code alone is specific enough to indicate failover vs other recoverable conditions.

Manual eviction is a fine option for us but not sure it's possible to avoid calling close() after eviction in all cases. Our data source is wrapped with a JDBI DBI instance, and that instance also needs to be closed in order to release its own resources, so after eviction we need to close the DBI instance and that will cause the underlying connection to be closed regardless.

**Comment by brettwooldridge** [comment]
@dconnelly If you are using RDS failover, I recommend reading these issues.

https://github.com/brettwooldridge/HikariCP/issues?q=is%3Aissue+mysql+failover+is%3Aclosed
