### ISSUE TITLE
Failing to validate connection at frequent intervals (connection closed)

### ISSUE THREAD

**Issue by aloraps** [brettwooldridge/HikariCP#917]
#### Environment
```
HikariCP version: 2.6.2
JDK version     : 1.8.0_111
Database        : MySQL
Driver version  : 5.1.40
```
-----------------------------------------------------------------------------------------

Hi, when running my application for more than 30 minutes, I receive the following error repeatedly:
`Jun 12, 2017 2:22:03 PM com.zaxxer.hikari.pool.PoolBase isConnectionAlive
WARNING: HikariPool-1 - Failed to validate connection 
com.mysql.jdbc.JDBC4Connection@5387fdc0 (No operations allowed after connection closed.)`

This error log will repeat about 20 times within the same second, and then I won't see it again for ~30-40 minutes.

`Jun 12, 2017 2:55:05 PM com.zaxxer.hikari.pool.PoolBase isConnectionAlive
WARNING: HikariPool-1 - Failed to validate connection com.mysql.jdbc.JDBC4Connection@5387fdc0 (No operations allowed after connection closed.)`

`Jun 12, 2017 3:36:16 PM com.zaxxer.hikari.pool.PoolBase isConnectionAlive
WARNING: HikariPool-1 - Failed to validate connection
com.mysql.jdbc.JDBC4Connection@5387fdc0 (No operations allowed after connection closed.) `

As you can see, it seems to be reoccuring itself at consistent intervals.

Configurations:

`config.setMaximumPoolSize(/*75*/18);
  config.setAutoCommit(true);
  config.addDataSourceProperty("cachePrepStmts", "true");
  config.addDataSourceProperty("prepStmtCacheSize", "250");
  config.addDataSourceProperty("prepStmtCacheSqlLimit", "2048");
  config.addDataSourceProperty("leakDetectionThreshold", "5000");
  config.setInitializationFailTimeout(5000);`

The wait_timeout of the mysql server is the default (around 8 hours).

I appreciate you taking the time to look into this and for your hard work on this project, thank you!

**Comment by brettwooldridge** [comment]
Regardless of the wait_timeout something is closing the connection.  We will investigate whether the close is somehow originating internally. I would suggest setting the HikariCP *maxLifetime* to just shorter than the interval of the log message you are observing.

**Comment by aloraps** [comment]
maxLifetime defaults at 30 minutes right? The interval is always slightly greater than 30 minutes which is odd. I'll try setting it to ~25 minutes and see if anything changes, though. Thank you.

**Comment by brettwooldridge** [comment]
The referenced issue was closed are resolved.
