### ISSUE TITLE
Improve documentation about: HikariConfig.setMaximumPoolSize best value

### ISSUE THREAD

**Issue by manueljordan** [brettwooldridge/HikariCP#920]
#### Environment
```
HikariCP version: 2.6.1
JDK version     : 1.8.0_131
Database        : MySQL (Windows 10)
Driver version  : 6.0.6
```
-----------------------------------------------------------------------------------------

According with the following experience: 
[HikariPool PoolInitializationException when some @Test method is added](https://stackoverflow.com/questions/44595713/hikaripool-poolinitializationexception-when-some-test-method-is-added)

I think would be valuable indicate what is the criteria to set a `HikariConfig.setMaximumPoolSize` value, for example why fails with `10` (_default_ value) and pass with `2`. In a first glance would be obvious that a higher value is better than a lower.

It with the purpose to improve the current documentation.

**Comment by KITSAntonioTerreno** [comment]
@manueljordan did you read this https://github.com/brettwooldridge/HikariCP/wiki/About-Pool-Sizing ? 

I think that's quite good documentation, maybe it should be linked again in the maximumPoolSize section of the README

**Comment by manueljordan** [comment]
@KITSAntonioTerreno, I did not read that valuable link. Thanks by share it.

>I think that's quite good documentation

Agree

> maybe it should be linked again in the maximumPoolSize section of the README

Wooh, why was removed? Interesting...

**Comment by brettwooldridge** [comment]
Added link back to documentation.
