### ISSUE TITLE
 Exception in Connection is not available, giving a high load of 53 TPS

### ISSUE THREAD

**Issue by yoshikakoba** [brettwooldridge/HikariCP#922]
#### Environment
```
HikariCP version: 2.6.0
JDK version     : 1.8.0_121
Database        : PostgreSQL9.4
Driver version  :PostgreSQL JDBC Driver JDBC41
```
-----------------------------------------------------------------------------------------
I checked the load with one application server and one DB server.
By Jmeter, when load of 35 TPS was applied, it ended normally, but with a load of 53 TPS the response worsened. The load of the CPU of the application server and the DB server is lowered.
After a while the following error began to occur. It seems that a connection leak has occurred.
Hikaricp only performs the following settings.
MaximumPoolSize = 1000

Are there other parameters to set?

```
Caused

 by: java.sql.SQLTransientConnectionException: HikariPool-2 - Connection is not available, request timed out after 30001ms.
	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:591)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:194)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:146)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
	at org.springframework.jdbc.datasource.LazyConnectionDataSourceProxy$LazyConnectionInvocationHandler.getTargetConnection(LazyConnectionDataSourceProxy.java:403)
	at org.springframework.jdbc.datasource.LazyConnectionDataSourceProxy$LazyConnectionInvocationHandler.invoke(LazyConnectionDataSourceProxy.java:376)
	at com.sun.proxy.$Proxy8.prepareStatement(Unknown Source)
	at org.hibernate.jdbc.AbstractBatcher.getPreparedStatement(AbstractBatcher.java:534)
	at org.hibernate.jdbc.AbstractBatcher.getPreparedStatement(AbstractBatcher.java:452)
	at org.hibernate.jdbc.AbstractBatcher.prepareQueryStatement(AbstractBatcher.java:161)
	at org.hibernate.loader.Loader.prepareQueryStatement(Loader.java:1700)
	at org.hibernate.loader.Loader.doQuery(Loader.java:801)
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:274)
	at org.hibernate.loader.Loader.doList(Loader.java:2542)
	... 222 more
```

Other
The following message appears at the beginning of Tomcat, but is there any relation to the above error phenomenon?

```
12:36:39,637 INFO  [localhost-startStop-1][HikariDataSource:95] HikariPool-1 - Starting...
12:36:39,731 INFO  [localhost-startStop-1][PoolBase:491] HikariPool-1 - Driver does not support get/set network timeout for connections. (org.postgresql.jdbc4.Jdbc4Connection.getNetworkTimeout() メソッドはまだ実装されていません。)
12:36:39,747 INFO  [localhost-startStop-1][HikariDataSource:107] HikariPool-1 - Start completed.
12:36:39,762 INFO  [localhost-startStop-1][DialectDetector:75] Determine dialect for PostgreSQL 9.4
12:36:39,872 INFO  [localhost-startStop-1][DialectDetector:148] Found dialect org.hibernate.dialect.PostgreSQLDialect
12:36:41,169 INFO  [localhost-startStop-1][HikariDataSource:95] HikariPool-2 - Starting...
12:36:41,184 INFO  [localhost-startStop-1][PoolBase:491] HikariPool-2 - Driver does not support get/set network timeout for connections. (org.postgresql.jdbc4.Jdbc4Connection.getNetworkTimeout() メソッドはまだ実装されていません。)
12:36:41,184 INFO  [localhost-startStop-1][HikariDataSource:107] HikariPool-2 - Start completed.
```

**Comment by brettwooldridge** [comment]
@yoshikakoba Setting ``maximumPoolSize`` to 1000 is going to create 1000 connections, because by default HikariCP is a fixed-size pool.  If you want the number of connections to grow and shrink depending on load, you need to also set ``minimumIdle``.

Having said that, setting ``maximumPoolSize`` to 1000 makes no sense unless your DB server has ~512 CPU cores.  With efficient queries you should be able to achive 3000+ TPS with a pool of only 10 connections.  If you haven't read it already, I recommend reading [About Pool Sizing](https://github.com/brettwooldridge/HikariCP/wiki/About-Pool-Sizing).

Also, it is intentional that you have two pools?  I see ``HikariPool-1`` and ``HikariPool-2`` are starting.  If it is intentional, that is fine, I just wanted to point it out.  Two pools with 1000 connections each (totalling 2000 connections) is likely to overload almost any database.

**Comment by yoshikakoba** [comment]
Hi brettwoolddridge,
I appreciate your early reply.
I was surprised that there is such a calculation formula.
Connections = (core_count * 2) + effective_spindle_count)
Since I have 8 cores of DB server I need 17 connections.
Perform load verification with the following settings.
■maximumPoolSize = 17
How do I set the minimumIdle value?

**Comment by brettwooldridge** [comment]
If your pool has only 17 connections (compared to 1000), I would advise keeping HikariCP as a fixed size pool.

minimumIdle is typically only needed when there are many applications connected to a single DB.  A fixed size pool will always provide higher and more consistent performance.

**Comment by yoshikakoba** [comment]
Hi Brett,
Thanks.
I understood your advice
Best Regard.

**Comment by brettwooldridge** [comment]
@yoshikakoba I just wanted to check back with you on this issue.  Did a pool size of ~17 connections eventually work for you?
