### ISSUE TITLE
Connection disapearing from stats, no cleaning performed that explaing it.

### ISSUE THREAD

**Issue by FabianIB** [brettwooldridge/HikariCP#926]
#### Environment
```
HikariCP version: 2.6.1
JDK version     : 1.8.0_111
Database        : DB2
Driver version  : com.ibm.db2.jcc.DB2Driver
```
-----------------------------------------------------------------------------------------
Hi there!
CP stats shows this:
`2017-06-30 11:21:34 [Hikari Housekeeping Timer (pool HikariPool-0)] DEBUG com.zaxxer.hikari.pool.HikariPool - Before cleanup pool stats HikariPool-0 (total=2, inUse=2, avail=0, waiting=0)
2017-06-30 11:21:34 [Hikari Housekeeping Timer (pool HikariPool-0)] DEBUG com.zaxxer.hikari.pool.HikariPool - After cleanup pool stats HikariPool-0 (total=2, inUse=2, avail=0, waiting=0)
2017-06-30 11:21:36 [Hikari Housekeeping Timer (pool HikariPool-0)] DEBUG com.zaxxer.hikari.pool.HikariPool - Before cleanup pool stats HikariPool-0 (total=0, inUse=0, avail=0, waiting=0)
2017-06-30 11:21:36 [Hikari Housekeeping Timer (pool HikariPool-0)] DEBUG com.zaxxer.hikari.pool.HikariPool - After cleanup pool stats HikariPool-0 (total=0, inUse=0, avail=0, waiting=0)`

Wondering how it could go from total=2 to total=0, without notifying of any kind of cleaning?
Between 11:21:34 and 11:21:36, there is nothing in the logs that explain how total went to 0.

Once I saw total gets down to 0, I start to see these errors:
`2017-06-30 11:21:56 [hystrix-ClientApp-10] WARN c.z.hikari.proxy.ConnectionProxy - Connection com.ibm.db2.jcc.t4.b@553350 (HikariPool-0) marked as broken because of SQLSTATE(08003), ErrorCode(-4470)`

This is my configuration
```
HikariCP pool HikariPool-0 configuration:
allowPoolSuspension.............false
autoCommit......................false
catalog.........................
connectionCustomizer............com.zaxxer.hikari.AbstractHikariConfig$1@3590fc5b
connectionCustomizerClassName...
connectionInitSql...............
connectionTestQuery.............
connectionTimeout...............30000
dataSource......................
dataSourceClassName.............
dataSourceJNDI..................
dataSourceProperties............{password=<masked>}
driverClassName.................com.ibm.db2.jcc.DB2Driver
healthCheckProperties...........{}
healthCheckRegistry.............
idleTimeout.....................60000
initializationFailFast..........true
isolateInternalQueries..........false
jdbc4ConnectionTest.............false
jdbcUrl.........................jdbc:db2://test.server.com:5221/DDB_DBP1
leakDetectionThreshold..........30000
maxLifetime.....................1800000
maximumPoolSize.................3
metricRegistry..................
minimumIdle.....................0
password........................<masked>
poolName........................HikariPool-0
readOnly........................false
registerMbeans..................false
threadFactory...................
transactionIsolation............
username........................USERP
validationTimeout...............5000
```

**Comment by brettwooldridge** [comment]
There is not enough information to tell.  Can you grep the log for all WARN level messages, as well as all messages containing the word "Closing"?

**Comment by brettwooldridge** [comment]
Also, why is your housekeeper thread running every 2 seconds?  The internal default is 30 and can only be changed by an undocumented system property.

**Comment by brettwooldridge** [comment]
@FabianIB Without additional information, we can't draw any hard conclusions, but there are several things to note.

Connection closing occurs on a separate thread, so it *is* possible to see a "before" housekeeping log showing connections, and an "after" log showing 0 connections -- followed later by the actual log of the close action by the closer thread.

Some logging frameworks also support asynchronous logging, which can also further separate removal from the pool, closing of the connection, and the timing of the log entry in the log file.

Having said *that*, there are some interesting observations (again, no conclusions, just observations):
 * The log by the proxy indicating the broken connection occurs almost exactly 30 seconds after the housekeeper thread's "after" log.  Possibly coincidental, but interesting.
 * The housekeeping thread appears to be running with a high frequency.  Your log indicates two housekeeping runs separated by only 2 seconds (``11:21:34`` and ``11:21:36``).  HikariCP uses a ScheduledExecutor to schedule the housekeeper with ``scheduleWithFixedDelay()`` and a value of 30 seconds, so this should not be possible unless the internal delay was overridden via a system property.

**Comment by FabianIB** [comment]
@brettwooldridge Thanks for the observations! 

I think I found out the root cause of the housekeeping high frequency, I was running multiple instances of the app (POD on kubernetes) and they were all writing to the same output.

Thanks for the insight provided, that help me a lot!  I'm still dealing with closed connections, but I think that should be something on my end.
