### ISSUE TITLE
wait on datasource close till references are cleared

### ISSUE THREAD

**Issue by udayshnk** [brettwooldridge/HikariCP#929]
Calling close on the HikariDataSource seems to be returning before all the background helper threads/connections are closed. 

Hot redeployment of the app is causing a permgen oom error as there are references to the previous version of the application. We are running in an constrained environment where we have limited permgen memory.

Assuming the connections are still in use by another thread or close call is taking some time to finish, how can we force wait on datasource close till all the connections in the pool are closed and the background helper threads created by hikari are all shutdown.

Thanks in advance.

#### Environment
```
HikariCP version: 2.6.3
JDK version     : 1.8.0_111
```
-----------------------------------------------------------------------------------------

**Comment by zimmi** [comment]
Having `HikariDataSource::close` block seems to be the better default. One can always run it in another thread if necessary. Retuning a `CompleteableFuture` could also work, but that seems like overkill.

**Comment by brettwooldridge** [comment]
Can you get a thread dump?  Looking at the code, it appears that all executors are shutdown.

**Comment by zimmi** [comment]
I'm not the original author of this issue, but I just created and closed around 800 pools in a loop and watched the heap and metaspace. I couldn't find any leak there, after a GC everything gets freed.
There are also no Hikari-Threads running after closing the datasource. So this does not seem to be an issue with HikariCP.

@udayshnk If you still have those leaks and you are running a Servlet-Application, you could try including [this library](https://github.com/mjiderhamn/classloader-leak-prevention). It will try to stop any threads that are still running when shutting down the app.

**Comment by udayshnk** [comment]
Sorry @brettwooldridge it's difficult to capture a thread dump of the process. I was observing the method HikariCp::shutdown, it is calling shutdown method on the executors **addConnectionExecutor**, **houseKeepingExecutorService**, **assassinExecutor** and **closeConnectionExecutor** and awating termination on each of them for a maximum of 5 secnods. 

There might be a case when addConnectionExecutor is creating a new connection and is awaiting for the network response which might take more than 5 seconds. Is it possible to give a configurable option asking it to wait for the complete process instead of waiting for a max of 5 seconds on the shutdown method, which guarantees that the there is no more references to pool.

**Comment by brettwooldridge** [comment]
@udayshnk I can investigate waiting on the addConnectionExecutor for DataSource.getLoginTimeout() seconds [ref](https://github.com/brettwooldridge/HikariCP/blob/dev/src/main/java/com/zaxxer/hikari/pool/PoolBase.java#L600).

**Comment by brettwooldridge** [comment]
@udayshnk I implemented the above, waiting for up to the login timeout for the ``addConnectionExecutor`` to shutdown.  I also extended the other timeouts to 10 seconds.  That is as far as I am willing to go.  If you need the pool to wait longer, you will need to poll the active connections yourself and block until they reach zero.

The reason we cannot keep waiting until all we are sure that 100% of the activity is complete is that in the event of a network partition event, each connection's TCP traffic may hang for up to the operating system TCP timeout (3 hours by default).  Nobody wants their pool to hang the shutdown, particularly if the shutdown might allow recovery.

**Comment by udayshnk** [comment]
Thanks for the update @brettwooldridge . 

Can you please provide a sample code of how we can poll the pool from outside. Looks like the hikariPool object is a private field in the datasource bean.

**Comment by brettwooldridge** [comment]
The pool JMX bean, accessible from the DataSource (and through the MBean server), is where you would poll the total connections (until the count reaches zero).

**Comment by udayshnk** [comment]
Thanks @brettwooldridge
