### ISSUE TITLE
Underlying connection pool does not represent better performance than common-pool2

### ISSUE THREAD

**Issue by wyzssw** [brettwooldridge/HikariCP#931]
#### Environment
```
HikariCP version: master
JDK version     : 1.8.0_102
Database        : jedis
Driver version  : x.x.x
```
-----------------------------------------------------------------------------------------

Recently i extract the HicariCp connection pool code to GenericPool which can apply to redis connection and others. The repository is `https://github.com/wyzssw/fastpool`(Fastpool.java derives from ConcurrentBag,and GenericFastPool.java derives from HicariCpPool.java ) , I write a test code `FastPoolVsCommonPoolTest.java` to
compare common-pool2 ,i find it‘s  performance not better than common-pool2, can you explain that?

**Comment by brettwooldridge** [comment]
In terms of a generic pools, there are faster pools.  For example, StormPot is impossible to beat.  However, connection pools have additional constraints.

Generic pools hand out whatever object is available, but in doing so make it impossible to implement idle timeout behavior.  For example, if the pool has 10 connection objects, and there are only 2 consumers, every connection is equally likely to be returned when get() is called.  Therefore, statistically every connection gets touched, preventing them from reaching idle.

HikariCP (ConcurrentBag) in the same scenario, will always return the same 2 connections, leaving the other 8 untouched, which allows an effective implementation of idle timeout behavior.

**Comment by wyzssw** [comment]
Thanks for your reply
