### ISSUE TITLE
when using aop, it seems that starting up becomes slowly

### ISSUE THREAD

**Issue by fightchwang** [brettwooldridge/HikariCP#936]
#### Environment
```
HikariCP version:2.6.3
JDK version     : 1.8.0_111
Database        : MySQL
Driver version  : 6.0.6
```
-----------------------------------------------------------------------------------------
Hi,
I'm using spring boot (v.1.5.1),when i add an custom aspect,which intercepts service methods, the app's starting up takes around two minutes before i can ues it, but when i comment the aspect, it starts up so fast(less than one minute). i have three datasources.

Anybody help me with that?

Thx.

**Comment by brettwooldridge** [comment]
No idea.  Maybe you can post details of the aspect...

**Comment by johnou** [comment]
From your IDE? Hope you don't have a breakpoint on a method :)

**Comment by fightchwang** [comment]
@brettwooldridge @johnou 
FYI.
## apsect

` @Aspect
@Component  
public class XXX{
@PointCut("execution(* com.xx.service.impl.*(..))")
public void pointCut(){
}

@Around("pointCut()")
public Object logIt(PreccedingJointPoint jp){
//some code
Object result = jp.proceed();
//other code
return result;
}
//another @AfterThrowing method is omitted
} `

## service
`
@Service
public class XXService{

@Autowired
@Qualifier("testDataSource1")
private DataSource datasource;


private DSLContext context;

@PostConstruct
public void init(){
context = DSL.using(datasource, mysqlDialect);
}

//the rest parts are some service methods

}
`

sorry for forgetting to mention that, i use jooq as DAO.

thx for your reply, @johnou, i'm sure that there's no breakpoint when i launch the app:).

**Comment by johnou** [comment]
@fightchwang would you please provide a full reproducer project?

**Comment by fightchwang** [comment]
@johnou wait,plz, i'll provide the sample project in github.
