### ISSUE TITLE
 jdbc logon attempts more than 5 times from Application - when the password is changed in database.

### ISSUE THREAD

**Issue by svatada** [brettwooldridge/HikariCP#937]
Ubuntu 14.0
```
HikariCP version: 2.3.8
JDK version     : 1.8
Database        : Oracle 11g
Driver version  : latest
```
-----------------------------------------------------------------------------------------
1. Write DB application connecting to oracle/mysql. Start your application.
2. After successful DB operation from application, alter user password in data base.
4. Now, check for the audit log- Once the password is changed in db server, validating account in application- causing 5-6 attempts in server and account will locked.

-------------------------------------------------------------------------------- 
TO_CHAR(TIMESTAMP,'	ACTION ACTION_NAME	RETURNCODE 
------------------- ---------- ---------------------------- ---------- 
snapuser 
05-22-2017 11:31:19	101 LOGOFF	0 
snapuser 
05-22-2017 11:31:20	101 LOGOFF	0 
snapuser 
05-22-2017 11:32:09	100 LOGON	1017 
OS_USERNAME 
-------------------------------------------------------------------------------- 
TO_CHAR(TIMESTAMP,'	ACTION ACTION_NAME	RETURNCODE 
------------------- ---------- ---------------------------- ---------- 
snapuser 
05-22-2017 11:32:10	100 LOGON	1017 
snapuser 
05-22-2017 11:32:10	100 LOGON	1017 
snapuser 
05-22-2017 11:32:11	100 LOGON	1017 
OS_USERNAME 
-------------------------------------------------------------------------------- 
TO_CHAR(TIMESTAMP,'	ACTION ACTION_NAME	RETURNCODE 
------------------- ---------- ---------------------------- ---------- 
snapuser 
05-22-2017 11:32:14	100 LOGON	1017 
snapuser 
05-22-2017 11:32:18	100 LOGON	1017 
44 rows selected. 

Because of the connection retry attempts , oracle account is getting locked. Is there any way to control the retry hits to db.

**Comment by brettwooldridge** [comment]
See #357

**Comment by Syed-SnapLogic** [comment]
Hi,
  The issue #357 talks about how to evict existing connections and how to update modified username/password.
  Is there a way to tell HikariCP not to attempt any more connections if the authentication failed?

**Comment by brettwooldridge** [comment]
If the pool gives up, it can never recover.
