### ISSUE TITLE
Support default schema in configuration

### ISSUE THREAD

**Issue by ghusta** [brettwooldridge/HikariCP#941]
There is an option to select a default _catalog_ in HikariConfig, but none for selecting a default _schema_.
Could it be possible ?

The option to set the schema in `java.sql.Connection` has been added in **Java 7** : [Connection.setSchema(...)](http://docs.oracle.com/javase/7/docs/api/java/sql/Connection.html#setSchema(java.lang.String))

FYI, for setting _catalog_ there is in [Connection.setCatalog(...)](http://docs.oracle.com/javase/7/docs/api/java/sql/Connection.html#setCatalog(java.lang.String)) in  JDK.

**Comment by lfbayer** [comment]
This is a good idea and it's surprising that this isn't already implemented. It seems like it should be a trivial change. What database and driver is this with?

**Comment by ghusta** [comment]
For example, Postgresql uses schemas.
See [official documentation](https://www.postgresql.org/docs/current/static/ddl-schemas.html).

The JDBC driver can be found [there](https://jdbc.postgresql.org/).

**Comment by ghusta** [comment]
FYI, I made a similar request for Commons DBCP : 
https://issues.apache.org/jira/browse/DBCP-479
