### ISSUE TITLE
HikariCP: Database pooling- 'Failed to initialize' the pool and "Too many connection" and data not saved into table

### ISSUE THREAD

**Issue by scrumvisualize** [brettwooldridge/HikariCP#942]
Windows 8.1 
---------------
HikariCP version: 2.5.1
JDK version     : 1.7.0_79
Database        : MySQL| 5.5.57
Apache Tomcat 7
Eclipse IDE:

While saving the details from jsp, system throws following error in console 'Failed to initialize' the pool and "Too many connection" and data not saved into table.
While checking the process list  in mysql > show full processlist; 
System display number of connection in sleep mode 
-----------------------------------------------------------------------------------------
I have created a Database pooling Class and method in Java usingHikariCP [ HikariCP » 2.5.1 version]. I have used( jdk 1.7.0_79), Servlets, Tomcat Apache 7 and Mysql 5.5+ version
I have Set 'maximum connection' in MySQL to 200

Following is my Database pooling config;

HikariConfig config = new HikariConfig();

config.setJdbcUrl("jdbc:mysql://localhost/mytestdb");
config.setDriverClassName("com.mysql.jdbc.Driver");
config.setUsername("root");
config.setPassword("root");
config.setPoolName("MySQLPool");
config.setMinimumIdle(2);
config.setMaximumPoolSize(5);
config.setAutoCommit(false);
config.addDataSourceProperty("cachePrepStmts", "true");
config.addDataSourceProperty("prepStmtCacheSize", "250");
config.addDataSourceProperty("prepStmtCacheSqlLimit", "2048");
datasource = new HikariDataSource(config);

How do I resolve the above error ?

**Comment by billoneil** [comment]
Does it always fail? Does it only fail sometimes? Is the database local or on another machine? You should only have 1 instance of the pool for the application. Make sure you are not creating a new one on every request.

**Comment by scrumvisualize** [comment]
Yes, it is failing always. Database is on the same machine. But one thing, I have got another Java class with another method which still using the 'normal mysql connection' with the same Database for login and other tables.  I was checking whether the new 'Database pool' will work for a new screen in my application ?

**Comment by scrumvisualize** [comment]
Any other suggestion ?

**Comment by brettwooldridge** [comment]
First, I'm a little confused.  v2.5.1 was built with a target in Java 8, so how is it running on Java 7?

Update to the latest version appropriate for you JVM.  Then enable the leakDetectionThreshold and enable debug logging for package com.zaxxer.hikari.

**Comment by scrumvisualize** [comment]
Thanks Brett, I wrongly mention the HikariCP version, my bad. when I looked again, I found that I am using HikariCP version: 2.0.1 in my project. I have enabled the leakDetectionThreshold and found I am getting 
leakDetectionThreshold exception in console. Now I am trying to figure out where is the leak happening.

**Comment by scrumvisualize** [comment]
Figured the leak, closed all resultSet, preparedStatement and connection. I could see HikariCP started using the pool. But after 15 minutes, i can see still it throw exception 'two many connection'

**Comment by brettwooldridge** [comment]
Please enable debug logging for com.zaxxer, reproduce the issue, zip the log file and attach it here.

**Comment by scrumvisualize** [comment]
[HikariCP_errorlog.txt](https://github.com/brettwooldridge/HikariCP/files/1202109/HikariCP_errorlog.txt)
Hello
I have attached the log file

**Comment by brettwooldridge** [comment]
It looks like you are constructing a pool for every servlet request in the service() method.  This is sure to quickly exhaust all available database connections.  The pool needs be constructed at the container level and exist for the life if the application.

**Comment by namjitharavind** [comment]
> constructed



> It looks like you are constructing a pool for every servlet request in the service() method. This is sure to quickly exhaust all available database connections. The pool needs be constructed at the container level and exist for the life of the application.

How we would do this in spring boot?
