### ISSUE TITLE
implement HikariDataSource.getConnection(String username, String password) to avoid readable password in context.xml of tomcat

### ISSUE THREAD

**Issue by mseele** [brettwooldridge/HikariCP#944]
#### Environment
```
HikariCP version: 2.6.3
JDK version     : 1.8.0_144
Database        : Oracle
Driver version  : Oracle 12.1.0.2.0 JDBC 4.1
```
-----------------------------------------------------------------------------------------

Please implement com.zaxxer.hikari.HikariDataSource.getConnection(String username, String password) to avoid readable password in tomcat's context.xml.

This is our szenario:

We are using a tomcat with multiple jndi DataSource instances in context.xml with oracle ucp:

```xml
<Resource name="jdbc/OracleDS_DB1"
	auth="Container"
	factory="oracle.ucp.jdbc.PoolDataSourceImpl" 
	type="oracle.ucp.jdbc.PoolDataSource"
	connectionFactoryClassName="oracle.jdbc.pool.OracleDataSource" 
	url="jdbc:oracle:thin:@server:1521:db1"
	connectionPoolName="UCPPool DB1" 
	defaultAutoCommit="false"
	...
	logAbandoned="true" />

<Resource name="jdbc/OracleDS_DB2"
	auth="Container"
	factory="oracle.ucp.jdbc.PoolDataSourceImpl" 
	type="oracle.ucp.jdbc.PoolDataSource"
	connectionFactoryClassName="oracle.jdbc.pool.OracleDataSource" 
	url="jdbc:oracle:thin:@server:1521:db2"
	connectionPoolName="UCPPool DB2" 
	defaultAutoCommit="false"
	...
	logAbandoned="true" />

...
```

To avoid readable passwords we load the passwords via .netrc at runtime and open a connection via this method:

```
public static Connection establishOracleDatabaseConnectionForTomcat(String sid, String username, String password) throws NamingException, SQLException {
	final Context initialContext = new InitialContext();
	final Context envContext = (Context) initialContext.lookup("java:comp/env"); //$NON-NLS-1$
	final DataSource dataSource = (DataSource) envContext.lookup("jdbc/OracleDS_" + sid); //$NON-NLS-1$
	final Connection connection = dataSource.getConnection(username, password);
	connection.setAutoCommit(false);
	return connection;
}
```

E.g. to open DB1 Connection it looks like this:

```
String username = <username from the code>
String password = <password for username from .netrc>
Connection connection = establishOracleDatabaseConnectionForTomcat("DB1", username, password);
```

When we tested HikariCP we realised that it's not possible to use HikariCP like this because `HikariDataSource.getConnection(String username, String password)` is not implemented like it is in Oracle UCP.

Even your documentation at https://github.com/brettwooldridge/HikariCP writes:

> This property sets the default authentication password used when obtaining Connections from the underlying driver. Note that for DataSources this works in a very deterministic fashion by calling DataSource.getConnection(username, *password*) on the underlying DataSource. However, for Driver-based configurations, every driver is different. In the case of Driver-based, HikariCP will use this password property to set a password property in the Properties passed to the driver's DriverManager.getConnection(jdbcUrl, props) call. If this is not what you need, skip this method entirely and call addDataSourceProperty("pass", ...), for example. Default: none

Why we also want to exclude username in context.xml is that we want to connect with different users, too.

Is there any workaround we can use or is this right now just not possible?

**Comment by lfbayer** [comment]
Would it be sufficient to just subclass the HikariDataSource yourself and override the getConnection method with your desired behavior?

**Comment by mseele** [comment]
We tried that but how to configure the jndi DataSource?
You also need to write your own JNDI Factory like it's written in in https://github.com/brettwooldridge/HikariCP/wiki/JNDI-DataSource-Factory-(Tomcat,-etc.).

And like i mentioned before, even the documentation says that it is possible to use `getConnection(String username, String password)`

For me it's a "core feature" and makes sense to be implemented for everybody.

**Comment by brettwooldridge** [comment]
Google these three words "hikaricp encrypted password".  There are many ways to solve this, and all of them are documented by other users on the internet.
