### ISSUE TITLE
SQLTransientConnectionException when i try to save or get data

### ISSUE THREAD

**Issue by Elikill58** [brettwooldridge/HikariCP#946]
Hello,

Linux
HikariCP version: 2.6.3
JDK version     : 1.8.0_111

This is my code : 
`public static volatile HikariDataSource POOL;

    static {
        HikariConfig config = new HikariConfig();
        config.setJdbcUrl("jdbc:mysql://localhost:3306/myDb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false");
        config.setUsername("user");
        config.setPassword("passWord");
        config.setDriverClassName("com.mysql.jdbc.Driver");
        config.setMaximumPoolSize(10);
        config.setLeakDetectionThreshold(10);
        config.setInitializationFailTimeout(3000);
        POOL = new HikariDataSource(config);
    }

    public static Connection useDB(String database) throws SQLException {
        Connection connection = POOL.getConnection();
        connection.prepareStatement("use " + database).execute();
        return connection;
    }`

And, (not the first time) when i get the connection (in the line "POOL.getConnection()) i get this error : 

`15:41:33 [SEVERE] java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30000ms.
15:41:33 [SEVERE] 	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:601)
15:41:33 [SEVERE] 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:194)
15:41:33 [SEVERE] 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:144)
15:41:33 [SEVERE] 	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:85)`

Can you help me ?
Do you need more informations ?

**Comment by nunnr** [comment]
First thing to check: Please make sure the connections you take from your useDB() method are closed when done.

If the code never calls connection.close() you will suffer "connection leak" where all the pool connections are in use. That does lead to the "Connection is not available" exception.

**Comment by RedNesto** [comment]
Hi, I am working with Elikill.

We are using everywhere try-catch blocks where we ask a connection via the useDB method. So don't they are all returned to the pool ?

**Comment by nunnr** [comment]
Ok, try-catch blocks are a very good approach to use with JDBC connections.

Do you have a "finally" block after each catch block, with connection.close() call? Add that and it should be perfect. This will return connection to the pool, no matter if execution is ok, or exception occurs.

To be clear: Without connection.close() the connection is not returned to the pool.

**Comment by RedNesto** [comment]
We don't use finally blocks at all in this project.
But this problem appeared months after the first day of development of this project, which is strange.

Something to note is that this problem seems to occur ~30 minutes after the start of the program, or a couple of minutes after a connection is used.

**Comment by nunnr** [comment]
Yes, that sounds strange.

I see you are setting the leak detection threshold, so hikari can warn when connections are borrowed for an unusually long time. However I think the value set "10" is not correct, at least according to the docs... "Lowest acceptable value for enabling leak detection is 2000 (2 seconds)". Maybe it should be 10000, i.e. 10 seconds?

May be useful to check the mysql process list, to see what connections are active. Looks like you are running mysql locally, so simply query "show processlist" on it. I don't mean to be rude - it can be pretty easy to overlook a misconfiguration of the database, connectivity, etc.!

**Comment by RedNesto** [comment]
Oh, I must have misunderstood the leak detection threshold, thanks for pointing this out.

**Comment by RedNesto** [comment]
After killing all connections and connecting to the program, many connections are created  (17 to be precise, we use a proxy with the same configuration) but they are all sleeping.

**Comment by brettwooldridge** [comment]
Enable debug logging for the com.zaxxer package and attach the log here when you observe the issue.

I'm not sure what you mean by "they are all sleeping".  If you are observing from the database side that is what you would expect to see the majority of the time.

If you are saying that they are all sleeping but you are getting connection timeouts from HikariCP, then it sounds like they have been borrowed but not returned.

Either way, the debug log should show fairly conclusively.

**Comment by Elikill58** [comment]
Hello,

Finally, with RedNesto we find the error.
It's because of a wrong use (we don't close connection ...)

I close this issue :) thanks
