### ISSUE TITLE
Feature: retrieve the started date of a datasource

### ISSUE THREAD

**Issue by SuperPat45** [brettwooldridge/HikariCP#948]
#### Environment
```
HikariCP version: 2.6.0
JDK version     : 1.8.0_111
Database        : PostgreSQL
Driver version  : 42.0.0
```
-----------------------------------------------------------------------------------------

Can you save the creation date in the HikariDataSource?

The mettric allow us to know how many connections have been opened but if we do not know since when ...

**Comment by brettwooldridge** [comment]
This isn't really a metric, as the value never changes.  You can get this information from JMX:

https://crunchify.com/java-how-to-get-the-start-time-of-a-jvm/

Presumably the start time of the JVM and the pool are nearly identical.

**Comment by SuperPat45** [comment]
In my case, my DataSources are not necessarily started at the same time as the JVM and they are closed after a long inactivity. Hence the utility of saving the creation date in the HikariDataSource.

Too bad I will have to save this date in a map next to my datasource list...
