### ISSUE TITLE
Request: Method to kill a broken connection manually

### ISSUE THREAD

**Issue by SuperPat45** [brettwooldridge/HikariCP#949]
#### Environment
```
HikariCP version: 2.6.0
JDK version     : 1.8.0_111
Database        : PostgreSQL
Driver version  : 42.0.0
```
-----------------------------------------------------------------------------------------

When I detect a connection is broken, are there any way to kill them manually (I don't know the HikariDatasource to which this connection belongs) ?

I know that Proxool connection poll has a static method ProxoolFacade.killConnecton(Connection, bool) for this

**Comment by brettwooldridge** [comment]
HikariDataSource.evictConnection().  Having said that, it should be extremely rare that a connection fails without HikariCP knowing.  All known exception paths flow through the pool proxies, even for connections that are out of the pool and in use.
