### ISSUE TITLE
Hot Undeploy Deploy war file to Tomcat "HikariPool-1 - Cannot acquire connection from data source"

### ISSUE THREAD

**Issue by daqianwang** [brettwooldridge/HikariCP#953]
#### Environment
```
Tomcat 8.5.16
HikariCP version: 2.6.3
JDK version     : 1.8.0_92
Database        : PostgreSQL
Driver version  : 42.0.0
```

The problem happens when I undeploy the war file from the tomcat and redeploy it.

then I initial the database connection again, after about 2-5 mins this line printed 

   
`HikariPool-1 - Cannot acquire connection from data source`
if you call any method which is database related it will work, but will create new HikariPool
then after you will get

`HikariPool-2 - Cannot acquire connection from data source`

I mean it will not affect you to use it, but this problem only happens if you redeploy war without restart the tomcat.

By the way I don't have a Resource.xml file, will that be the problem?

-----------------------------------------------------------------------------------------

**Comment by brettwooldridge** [comment]
It is likely that the pool is not being destroyed when the war is undeployed.

One solution is to configure HikariCP at the global level: https://github.com/brettwooldridge/HikariCP/wiki/JNDI-DataSource-Factory-(Tomcat,-etc.)

Or this might help: https://stackoverflow.com/questions/13595794/jdbc-connection-pool-runs-out-of-connections-when-context-reload-true-is-enabl/13631242#13631242

**Comment by daqianwang** [comment]
I finally managed to get the answer which is add following code to the 

**ServletContextListener**

``
dataSource.close();
``

In class which implement the `@Override
    public void contextDestroyed(ServletContextEvent sce)`

method  close the datab source.

So every time when redeploy the war file, the listener get called, the   above code will close the connection, there will be no more cannot accquire connection from data source
