### ISSUE TITLE
HikariCP ignores dataSource.logWriter?

### ISSUE THREAD

**Issue by emmenlau** [brettwooldridge/HikariCP#954]
#### Environment
```
HikariCP version: 2.6.3
JDK version     : 1.8.0_144
```
-----------------------------------------------------------------------------------------

I initialize HikariCP with my own OutputStream logger:
```
Properties vProperties = new Properties();

// Log HikariCP messages to our Logger:
final int vHikariCPLoggerVerbosity = 8;
vProperties.put("dataSource.logWriter", new PrintWriter(new LogOutputStream(vHikariCPLoggerVerbosity)));

HikariConfig vHikariConfig = new HikariConfig(vProperties);
mPooledDataSource = new HikariDataSource(vHikariConfig);
```
but it continues to log to stdout/stderr and does never invoke my OutputStream logger. I continue to see on the console messages like:
```
[main] WARN com.zaxxer.hikari.HikariConfig - HikariPool-1 - idleTimeout is close to or more than maxLifetime, disabling it.
[main] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
[main] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
```
I do not want to disable HikariCP logging. But I want to redirect it (exclusively) to my logfile appender. Is that possible?

**Comment by billoneil** [comment]
If you are using SLF4J you can have an appender dedicated to HiariCP if you want.

**Comment by emmenlau** [comment]
Thanks @billoneil any solution sounds good. Can you give me an idea how I would do that?

**Comment by brettwooldridge** [comment]
The logger you are setting is the one used by the driver, not HikariCP.  See the slf4j documentation for how to configure loggers and appenders.  Appenders are what determines what files are logged to (or stdout/stderr).

**Comment by emmenlau** [comment]
Ok I think I understand. But I found this not easy to grasp. Could logging be (very briefly) be explained on the front page examples? I guess you have a three-liner that gives you useful logging from both the driver and HikariCP? It took me a few days to just realize I'm on the completely wrong track with `dataSource.logWriter`.

**Comment by billoneil** [comment]
If you use SLF4J it is probably backed by logback or log4j there are tons of examples for setting up multiple appenders. Just google whichever implementation you use. This isn't something specific to HikariCP.

**Comment by emmenlau** [comment]
@billoneil its not important what logger I use, or am I wrong? I have my own logger based on `java.util.logging`. The important question is which logger HikariCP uses? After your feedback I found that it must be slf4j, but I did not know this before. I first tried `java.util.logging` and did not get log output, and then I tried `logback` and did not get log output.

So my suggestion is to write on the front page something like

## Logging
HikariCP uses slf4j for logging. Please see https://www.slf4j.org/manual.html on how to configure slf4j with your favorite logging backend. Without configuration, slf4j should log at level XXX to stdout.
