### ISSUE TITLE
Thread are waiting but the pool didn't reach the maximum connections

### ISSUE THREAD

**Issue by marcusavi** [brettwooldridge/HikariCP#956]
We had issue in which many SQLExceptions  were thrown for Timeout after waiting for a connection.

We saw that during that time period, there were many threads waiting for a connection that time,
but the pool didn't reach its maximum connection limit, 

How can such case happen?  Why the pool don't create new connections before it reach its limits?

Thanks,
Avi

#### Environment
```
HikariCP version: 2.2.5
JDK version     : 1.8.0_25
Database        : Oracle
Driver version  : ojdbc7
```
-----------------------------------------------------------------------------------------

**Comment by brettwooldridge** [comment]
HikariCP v2.2.5 is extremely old, many bugs have been fixed since then, please upgrade to the latest version.
