### ISSUE TITLE
Change log level when exception caught in HikariPool.createPoolEntry() from DEBUG to higher

### ISSUE THREAD

**Issue by joaoandremartins** [brettwooldridge/HikariCP#959]
When connecting to a database fails for any reason, Hikari [logs the errors at debug level](https://github.com/brettwooldridge/HikariCP/blob/dev/src/main/java/com/zaxxer/hikari/pool/HikariPool.java#L463). Normally, logger levels are usually INFO by default, so it's as if Hikari is swallowing these errors.

It makes sense that the exceptions be logged at the warning or error level.

#### Environment
```
HikariCP version: 2.5.1
JDK version     : 1.8.0_111
Database        : PostgreSQL and MySQL
```
-----------------------------------------------------------------------------------------

**Comment by brettwooldridge** [comment]
@joaoandremartins HikariCP is used in some ridiculously brutal environments.

There is a major customer running nearly a billion transactions per-day through HikariCP.

There are also customers that pre-start application servers in a cloud environment, even though the database they will eventually connect to is itself *not* started.  HikariCP in this case can "pend" (block) the application, attempting a connection every 1.5 seconds or so, until the database appears.

In these kinds of environments (and other esoteric deployments), HikariCP would flood the log with thousands of messages.

In the case of a running application, if the pool is unable to establish new connections, and cannot satisfy a demand for a connection, the ``SQLTransientConnectionException`` thrown by HikariCP will contain the last exception thrown by the driver, accessible via the ``getNextException()`` method.  

Typically, an exception thrown from the pool into the application, or into a framework such as Hibernate, will result in an error level log at that level.
