### ISSUE TITLE
‘validationTimeout’ should be able less than 1000ms

### ISSUE THREAD

**Issue by kenny319** [brettwooldridge/HikariCP#960]
The document said ‘validationTimeout’ can be lower than 1000ms, the acceptance lowest value is 250ms, but the code will replace it with 1000ms when the value is less than 1000ms. So the document is not precise enough. 

Furthermore, sometimes the big timeout will cause very serious availability issue in very high throughput circumstance, we have to tune every timeout to a suitable value which is less than 1 second, usually 200~300ms according to our experience. Although the unit of both the timeout argument in Statement.setQueryTimeout(timeout) and Connection.isValid(timeout) is in second, we still can make it work by using the API directly from the mysql driver. There is an API named com.mysql.jdbc.MySQLConnection.pingInternal(boolean, int timeout), the timeout is in millisecond. We forked HikariCP and add the new 'validationTimeout' support by using this way. 

We are glad to contribute the patch if it is helpful.

**Comment by brettwooldridge** [comment]
@kenny319 The code only rounds up to 1000ms for the APIs that only accept seconds -- such as ``Statement.setQueryTimeout()`` and ``Connection.isValid()``.  *However*, if the driver supports ``Connection.setNetworkTimeout()``, the raw millisecond value will be used.
