### ISSUE TITLE
HikariCP

### ISSUE THREAD

**Issue by dpotam** [brettwooldridge/HikariCP#962]
Hello! Is this possible to add HikariCP to Glassfish for create connection pool for connect with Oracle Database?

**Comment by brettwooldridge** [comment]
I'm sure it is.  Ask on stackoverflow ... or better yet, search first, someone may have already done it.

**Comment by dpotam** [comment]
I'm not java developer. Is this possible to add support of hikaricp to glassfish for get availability choose it from dropdown list when creating connection pool at glassfish's web interface?

**Comment by billoneil** [comment]
Again it is probably possible, but a dropdown as you described would probably require the web server to know all the versions of HikariCP, know how to download them, know how to add it to the classpath (which can be done in different ways with different configurations), as well as how to configure all of the settings. That isn't really a realistic feature request from either library.

I highly doubt the maintainers of either library will be willing to build such implementation specific code into their libraries. You are going to be better off learning how to set it up the standard ways that you can Google for.
