### ISSUE TITLE
HikariPool is closed after application redeploy in tomcat

### ISSUE THREAD

**Issue by tomas-silhavy** [brettwooldridge/HikariCP#966]
#### Environment
```
HikariCP version: 2.6.3
JDK version     : 1.8.0_111
Database        : MariaDB|MySQL
Driver version  : mysql-connector-java:5.1.39
Tomcat          : 7
```
-----------------------------------------------------------------------------------------

I have defined connection pool in tomcat `server.xml` using `HikariJNDIFactory`. When I undeploy and redeploy my application, pool is closed and app cannot connect to it anymore. I need to restart tomcat to get it running again. This is problem because this redeploy process is done automatically by bamboo server on several machines. When I used tomcat's default connection pool everything worked fine. There are no errors in log during undeploy or deploy until I try hitting the DB then I get:

```java
Caused by: java.sql.SQLException: HikariDataSource HikariDataSource (HikariPool-2) has been closed.
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:81) ~[HikariCP-2.6.3.jar:na]
	at org.springframework.jdbc.datasource.DataSourceTransactionManager.doBegin(DataSourceTransactionManager.java:246) ~[spring-jdbc-4.3.10.RELEASE.jar:4.3.10.RELEASE]
...
```

`server.xml`
```xml
<GlobalNamingResources>
    <Resource name="jdbc/myDatasource" auth="Container"
              factory="com.zaxxer.hikari.HikariJNDIFactory"
              type="javax.sql.DataSource"
              minimumIdle="5" 
              maximumPoolSize="10"
              connectionTimeout="300000"
              driverClassName="com.mysql.jdbc.Driver"
              jdbcUrl="jdbc:mysql://localhost:3306/app"
              dataSource.user="xxx"
              dataSource.password="xxx" />
 <!-- also tried adding this
              registerMbeans="true"
              allowPoolSuspension="true"
  -->
</GlobalNamingResources>
```
`context.xml`
```xml
<ResourceLink name="jdbc/myDatasource"
              global="jdbc/myDatasource"
              type="javax.sql.DataSource" />
```

**Comment by brettwooldridge** [comment]
This looks similar: https://stackoverflow.com/questions/25149969/why-does-datasources-close-on-tomcat-7-undeploy-with-spring-boot

If I recall, Tomcat JNDI also has a destroy method setting... maybe you can disable it.

**Comment by brettwooldridge** [comment]
You can also try adding auth="Container" to your ResourceLink definition.  Other than that, I don't see anything obviously wrong with your configuration.  I can think it is uncommon for the global resource to be closed.  You can try running under a debugger and breakpointing the HikariPool.shutdown() method, causing an undeploy, and seeing who is calling it.

**Comment by tomas-silhavy** [comment]
Is it possible that the problem is the other way around? Looking at stack trace I see that when undeploying the context, spring correctly closes all beans including datasource looked up through JNDI. Somewhere on SO I've seen comment saying that JNDI resources should be created upon request by server, so it would mean that tomcat is not actually starting the pool when deploying the app again. Is this the case or was that comment wrong?
