### ISSUE TITLE
Odd state of PoolEntry objects 

### ISSUE THREAD

**Issue by robinshine** [brettwooldridge/HikariCP#969]
#### Environment
```
HikariCP version: 2.6.2
JDK version     : 1.8.0_131
Database        : MySQL
Driver version  : mariadb-java-client 1.5.2
```
-----------------------------------------------------------------------------------------

Our application uses Hibernate and Hikari and occasionally it reports that "connection is not available, request timed out after 30000ms".
I took a memory dump of the application when this happens, and found that all PoolEntry objects are in state 1 and evict flags are true, and this causes the application unable to retrieve any new connections. However there is no HikariProxyConnection object in the memory dump and I guess this indicates that all connections retrieved from Hikari previously have been closed. 
Is this a bug of Hikari? Worth to mention that I specified autocommit flag as "false" as I want to rely on Hikari to rollback uncommitted updates automatically at the time of closing the connection.

**Comment by brettwooldridge** [comment]
This sound like an issue  elsewhere to me.  Two things to try: enable the leakDetectionThreshold, and set the Hibernate release mode to AFTER_TRANSACTION.

See [this discussion](https://github.com/brettwooldridge/HikariCP/issues/923#issuecomment-327201478).  Hibernate has a habit of holding onto connections.

If a connection is in-use when maxLifetime is reached, the connection will be flagged for eviction.  That explains why the PoolEntry objects would be both in-use as well as marked for eviction.  It still *does not* explain why you do not see HikariProxyConnection objects in memory.

If we take the absence of proxy objects *as fact*, that indicates a *true leak*.  If a client obtains a connection from the pool, and then abandons it without closing, the proxy objects will be garbage collected -- but the PoolEntry will remain (held onto by HikariCP), and the maxLifetime timer will eventually mark them evicted.  This fits exactly the pattern you have reported.

The leakDetectionThreshold will quickly identify the source of the leak in that case.
