### ISSUE TITLE
I have done OS upgrade from tomcat 8.0.36 to 8.0.43 through suse linux sles12-sp2-201702 

### ISSUE THREAD

**Issue by tssujatha** [brettwooldridge/HikariCP#979]
#### Environment
```
HikariCP version: x.x.x
JDK version     : 1.8.0_111
Database        : PostgreSQL|MySQL|...
Driver version  : x.x.x
```
-----------------------------------------------------------------------------------------
*Have you searched the CLOSED issues already? How about checking [stackoverflow](https://stackoverflow.com/search?q=HikariCP)?*

**Comment by tssujatha** [comment]
After OS upgrade from tomcat 8.0.26 to 8.0.43 the JNDI lookup is not working ,


WARNING [localhost-startStop-1] org.apache.naming.NamingContext.lookup Unexpected exception resolving reference
 java.lang.IllegalArgumentException: The local resource link ......that refers to global resource ..........does not specify the required attribute type
        at org.apache.naming.factory.ResourceLinkFactory.getObjectInstance(ResourceLinkFactory.java:156)


This was absolutely working fine with the previous tomcat 8.0.26 , we are getting OS from SUSE linux (sles12-sp2-201702). 
From the above posts i got to know even this kinda issue faced during tomcat 7 os upgrade, someone please guide.

**Comment by jnehlmeier** [comment]
https://tomcat.apache.org/tomcat-8.0-doc/config/context.html#Resource_Links
https://bz.apache.org/bugzilla/show_bug.cgi?id=60151#c6

So fix your tomcat configuration file.

**Comment by tssujatha** [comment]
Is that new tomcat(8.0.43) expects type as mandatory parameter as it was working fine without the type till 8.0.36 tomcat version.Please suggest .
Also we are facing problems in valve adapter instance as well

**Comment by tssujatha** [comment]
Hello sir,Thanks for your response your bug reference was helpful for me to provide the reference to my clients and solve the issue.

I have one more issue witht this new SLES (tomcat 8.0.43)
Actually My global resource look up for JNDI is happening properly with java:/resourcelink and when it comes to local reourcelink which is java:comp/env i am facing below issue which suppose to get the connetion ldap pool.


Provider.lookup jndi property java:comp/env/server/IAPJLET/LDIServiceLink could not be retrieved. The local resource link [LDIServiceLink] that refers to global resource [/server/IAPJLET/GlobalLDIService] was expected to return an instance of
 [com.ldi.DirectoryService] but returned an instance of [java.util.HashMap]


See its returning hashmap but it suppose to be the class(type) object instance.
This is exactly we are facing in intialcontext.lookup(jndipropname) 
One more added point here we are CDI injection also using weld-se.jar  2.3.3 jar. 
Please share if you have information on this.

**Comment by brettwooldridge** [comment]
I’m sorry, I don’t know much about JNDI and even less about how Tomcat uses it.  I suggest that you ask this question on stackoverflow.

**Comment by brettwooldridge** [comment]
https://stackoverflow.com

**Comment by tssujatha** [comment]
i tried but no luck :( 
https://stackoverflow.com/questions/46728350/os-upgrade-causing-issue-tomcat-local-resource-lookup-in-tomcat-8-0-43

**Comment by lfbayer** [comment]
@tssujatha Did you see this post?

https://stackoverflow.com/questions/40978635/error-launching-tomcat-while-migrating-from-java7-tomcat7-to-java8-tomcat8

Maybe you need to add `type="javax.sql.DataSource"` to your ResourceLink definition?

**Comment by tssujatha** [comment]
Thanks. Actually yes we have already included type because we got error as soon as we migrated that the local resources expecting type and we have already had type for global resources. So we implemented this. after that this issue we faced.
