### ISSUE TITLE
HikariConfig#setDriverClassName ClassLoader precedence is backwards

### ISSUE THREAD

**Issue by beargiles** [brettwooldridge/HikariCP#982]
We provide bundled reference JDBC driver jars for our customers that use open source databases but allow them to upload and use their own version at runtime. We recently discovered that this isn't working as expected and tracked it down to the code in HikariConfig#setDriverClassName():

    public void setDriverClassName(String driverClassName)
    {
       Class<?> driverClass = null;
       try {
          driverClass = this.getClass().getClassLoader().loadClass(driverClassName);
          LOGGER.debug("Driver class found in the HikariConfig class classloader {}", this.getClass().getClassLoader());
       } catch (ClassNotFoundException e) {
          ClassLoader threadContextClassLoader = Thread.currentThread().getContextClassLoader();
          if (threadContextClassLoader != null && threadContextClassLoader != this.getClass().getClassLoader()) {
             try {
                driverClass = threadContextClassLoader.loadClass(driverClassName);
                LOGGER.debug("Driver class found in Thread context class loader {}", threadContextClassLoader);
             } catch (ClassNotFoundException e1) {
                LOGGER.error("Failed to load class of driverClassName {} in either of HikariConfig class classloader {} or Thread context classloader {}", driverClassName, this.getClass().getClassLoader(), threadContextClassLoader);
             }
          } else {
             LOGGER.error("Failed to load class of driverClassName {} in HikariConfig class classloader {}", driverClassName, this.getClass().getClassLoader());
          }
       }
    ....

The same code appears in DriverDataSource

         if (driver == null) {
            LOGGER.warn("Registered driver with driverClassName={} was not found, trying direct instantiation.", driverClassName);
            Class<?> driverClass = null;
            try {
               driverClass = this.getClass().getClassLoader().loadClass(driverClassName);
               LOGGER.debug("Driver class found in the HikariConfig class classloader {}", this.getClass().getClassLoader());
            } catch (ClassNotFoundException e) {
               ClassLoader threadContextClassLoader = Thread.currentThread().getContextClassLoader();
               if (threadContextClassLoader != null && threadContextClassLoader != this.getClass().getClassLoader()) {
                  try {
                     driverClass = threadContextClassLoader.loadClass(driverClassName);
                     LOGGER.debug("Driver class found in Thread context class loader {}", threadContextClassLoader);
                  } catch (ClassNotFoundException e1) {
                     LOGGER.warn("Failed to load class of driverClassName {} in either of HikariConfig class classloader {} or Thread context classloader {}", driverClassName, this.getClass().getClassLoader(), threadContextClassLoader);
                  }
               } else {
                  LOGGER.warn("Failed to load class of driverClassName {} in HikariConfig class classloader {}", driverClassName, this.getClass().getClassLoader());
               }
            }
         }

The problem is that the reference JDBC jar is in the same classloader as the HikariCP jar - it will always be loaded before the Thread's currentContext classloader is checked. It should be the other way around - the reason for a thread-specific classloader is to allow the developer to have runtime flexibility.

We've identified a potential workaround of creating our own classloader and immediately instantiating the JDBC driver class and registering it with the DriverManager. I don't know if it will work since some of the customer-uploaded drivers are actually multiple jars (e.g., for enhanced authentication or encryption) and we might have issues with assignments between objects loaded from different classloaders, 

This isn't an abstract concern - we've been burned by it. We might have an assignment between "identical" objects but one object was loaded via reference from an object loaded from classlooader A and the second object loaded via reference from a class loaded classloader B. Identical classes, literally the same physical file, but classes loaded via different classloaders are not assignable. The "solution" is to ensure you have the jar visible to a single classloader but it's not always possible.

There are a few other places where classloader assumptions are made but it's not clear what the impact would be. E.g., ConcurrentBag

    private boolean useWeakThreadLocals()
    {
       try {
          if (System.getProperty("com.zaxxer.hikari.useWeakReferences") != null) {   // undocumented manual override of WeakReference behavior
             return Boolean.getBoolean("com.zaxxer.hikari.useWeakReferences");
          }

          return getClass().getClassLoader() != ClassLoader.getSystemClassLoader();
       }
       catch (SecurityException se) {
          return true;
       }
    }

Bear

#### Environment
```
HikariCP version: 2.7.2-SNAPSHOT and before
JDK version     : 1.8.0_111
Database        : All
Driver version  : x.x.x
```

**Comment by brettwooldridge** [comment]
All perfectly reasonable.  The thread context classloader change was a contributed enhancement; I agree that the context classloader should be tried first.

The other classloader usage, in ConcurrentBag, is there to determine whether HikariCP itself in running in application container (Tomcat, JBoss, etc).  If HikariCP believes it is running in an environment where *in situ* restart/redeploy is possible, it will use WeakReferences in ThreadLocals to avoid memory leaks.  That determination is fairly simplistic; if HikariCP's classloader is the Java root classloader, it behaves as if in a standalone application (no WeakReferences). Anyway, unrelated to the above issue.

**Comment by brettwooldridge** [comment]
@beargiles HikariCP v2.7.2 containing this fix has been released.
