### ISSUE TITLE
HikariCP does not close all idle connections

### ISSUE THREAD

**Issue by cbxp** [brettwooldridge/HikariCP#983]
#### Environment
```
HikariCP version: 2.6.3
JDK version     : 1.8.0_91
Database        : any
Driver version  : any
```
-----------------------------------------------------------------------------------------

Given that "minIdle" is set to N, Hikari CP does never close more than N+1 idle connections at a time.

For example, we have `minIdle=0` and `maxPoolSize=70`.
In this case, house keeper thread closes only **1** connection at a time, **leaving the rest 69 idle connections open**.

The following code is guilty: 

```java
private final class HouseKeeper implements Runnable
...
       final List<PoolEntry> notInUse = connectionBag.values(STATE_NOT_IN_USE);
       int removed = 0;
       for (PoolEntry entry : notInUse) {
          if (elapsedMillis(entry.lastAccessed, now) > idleTimeout && connectionBag.reserve(entry)) {
            closeConnection(entry, "(connection has passed idleTimeout)");
             if (++removed > config.getMinimumIdle()) { // THIS IS WRONG CONDITION!
                break;
             }
          }
       }
}
```

**Comment by cbxp** [comment]
@brettwooldridge Can you comment this issue? Do I correctly understand that this is a wrong IF?
If yes, I can prepare a pull request.

**Comment by nitincchauhan** [comment]
to me its yes. good find.

**Comment by johnou** [comment]
@cbxp confusing example. if minIdle is set to 0 that's a configuration for a fixed size pool and connections should not be closed.

**Comment by brettwooldridge** [comment]
@johnou Actually, if minimumIdle is explicitly set to 0, that value will be honored, and the pool will not backfill Connections.

**Comment by brettwooldridge** [comment]
So, this looks like a regression.  This used to be fine, so clearly a unit test is warranted to catch regressions in the future.

**Comment by cbxp** [comment]
@brettwooldridge Thank you! Can you say when it will be released?

P.S. We tried to make a pull request, but failed with tests. Tests were red. **Why HikariCP tests are constantly failing in `dev` branch?**

**Comment by johnou** [comment]
@cbxp tests passed, see https://travis-ci.org/brettwooldridge/HikariCP/builds/281815383?utm_source=github_status&utm_medium=notification

**Comment by brettwooldridge** [comment]
@cbxp @johnou HikariCP v2.7.2 containing this fix has been released.
