### ISSUE TITLE
Publish release 2.7.2 to Maven Repository

### ISSUE THREAD

**Issue by coman1977** [brettwooldridge/HikariCP#995]
Hi,

I can't find the release 2.7.2 on mvnrepository.com
https://mvnrepository.com/artifact/com.zaxxer/HikariCP/2.7.1

Cheers,
Liviu

#### Environment
```
HikariCP version: 2.7.2
JDK version     : 1.8.0_111
Database        : PostgreSQL|MySQL|...
Driver version  : x.x.x
```
-----------------------------------------------------------------------------------------
*Have you searched the CLOSED issues already? How about checking [stackoverflow](https://stackoverflow.com/search?q=HikariCP)?*

**Comment by lfbayer** [comment]
Searching for the same type of issue on the internet shows that Maven Central normally responds to this kind of issue like this:
> There is no formal relationship between Maven Central and mvnrepository.com, so I can't speak to the frequency or accuracy of their updates.

The 2.7.2 artifact is currently available from maven central: http://search.maven.org/#artifactdetails%7Ccom.zaxxer%7CHikariCP%7C2.7.2%7Cbundle

**Comment by coman1977** [comment]
thanks for hint. i will close it.
