### ISSUE TITLE
API report for HikariCP

### ISSUE THREAD

**Issue by lvc** [brettwooldridge/HikariCP#996]
Hi,

Here is the review of API changes for the HikariCP library since 2.0.0 version: https://abi-laboratory.pro/java/tracker/timeline/hikaricp/

The report is generated by the https://github.com/lvc/japi-tracker tool for jars at http://central.maven.org/maven2/com/zaxxer/HikariCP/ according to the article https://wiki.eclipse.org/Evolving_Java-based_APIs_2.

The report is updated three times a week. Hope it will be helpful for users and maintainers of the library.

The tool checks all public API methods and classes by default. Please let me know if it should not check some parts of the API (private, undocumented, etc.).

Thank you.

![hikaricp-1](https://user-images.githubusercontent.com/1517837/31483256-432a35ae-af34-11e7-88c2-2246f52bb3e9.png)

![hikaricp-2](https://user-images.githubusercontent.com/1517837/31483255-42dbf326-af34-11e7-978f-a21cc413048a.png)

#### Environment
HikariCP version: 2.0.0 - 2.7.2
JDK version: 1.8.0_65

**Comment by brettwooldridge** [comment]
@lvc That’s pretty cool.  We definitely have non-public APIs that are public out of necessity (cross-package visibility) that should be excluded.

My suggestion is that you honor a “dot” file in the root of the repository, such as *.abi-tracker*, that allows the developer to exclude packages and/or classes.

**Comment by lvc** [comment]
Hello,

Great idea!

Packages and classes can be filtered by regexp. Should the tool check only `com.zaxxer.hikari` and `com.zaxxer.hikari.metrics` (http://javadoc.io/doc/com.zaxxer/HikariCP/2.7.2)?

The `.abi-tracker` filter file may contain the following:

    com\.zaxxer\.hikari\.metrics\.(micrometer|dropwizard|prometheus).*
    com\.zaxxer\.hikari\.(pool|util|proxy).*

Thank you.
