### ISSUE TITLE
Postgres failback to master after the failover (to slave) once the master is back up

### ISSUE THREAD

**Issue by amarkanth1984** [brettwooldridge/HikariCP#999]
#### Environment
```
HikariCP version: 2.4.7
JDK version     : 1.8.0_144
Database        : PostgreSQL 9.4
Driver version  : postgresql 9.4.1209
```
-----------------------------------------------------------------------------------------
*Have you searched the CLOSED issues already?  YES

As a follow-up to the below issue, It would be great if HikariCP can do the following.
https://github.com/brettwooldridge/HikariCP/issues/742

Current Behaviour
==============
https://jdbc.postgresql.org/documentation/head/connect.html (connection failover section). When we provide both master and slave (master first) in the jdbc connect string, the connection pool is initialized against master and then read-write happens nicely. Upon master failure, within seconds, the pool automatically gets intialized to connect to the slave which is setup in read-only mode. So far so good!
Now, when the master comes back up (we currently use monit for this), Hikari doesn't seem to reconnect back to master. 

New behaviour which will help everyone
==============================
It would be awesome if you can support this since the underlying driver seem to do a round-robin check on all the hosts using 'hostRecheckSeconds' property (default is 10 seconds).
Without this, we have to now build out our own functionality to acheive it. I think it would benefit a lot of folks if you can add this support!

**Comment by amarkanth1984** [comment]
@brettwooldridge

**Comment by brettwooldridge** [comment]
@amarkanth1984 Thank you for the suggestion, but we are not likely to implement such a DB-specific feature.  Other users (you can search the closed issues) have implemented simple failover solutions on top of HikariCP using a combination of *monitoring*, the *suspect/resume* feature, and the ``softEvictConnections()`` MBean API.

Basically, when you want to *fail back* to master, you suspend the pool, poll the pool until idleConnections == totalConnections, then evict and resume the pool.  Detecting *when* to fail back is up to your own monitoring solution.

**Comment by brettwooldridge** [comment]
@amarkanth1984 The other thing to note is that ``maxLifetime`` defaults to 30 minutes, so within 30 minutes all connections should re-establish to master.  If you want to speed that up, you can set ``maxLifetime`` lower -- though I wouldn't recommend setting it to less that 5 minutes or so.

**Comment by klichukb** [comment]
Hello guys. Is it possible to just swap the current connection pool with a newly created one, then later calling `softEvictConnections` on the old pool?
